### ISSUE TITLE
have a signalling file in /home/git/data to indicate precompile status

### ISSUE THREAD

**Issue by hans-d** [sameersbn/docker-gitlab#100]
when a gitlab container is started, it takes some time (and cpu) to precompile.
When doing a scripted deploy, it would be usefull to be able to wait for this to complete.
Eg by touching a file at the beginning of the init script, and removing it at the end.

**Comment by sameersbn** [comment]
The assets can now be compiled at build time. The referenced commit does this. You should now have much faster container startup time. I think this issue may no longer be relevant in this context. Please let me know if you have any concerns. Thanks
