### ISSUE TITLE
Upgrade to 8.14.4 (Incorrect gitlab-shell)

### ISSUE THREAD

**Issue by GJRTimmer** [sameersbn/docker-gitlab#1009]
I've just upgraded from 8.14.1 => 8.14.4, and I'm getting the following warning in my log.
Anyone have any suggestion how to fix it ?

```bash
Migrating database...
WARNING: This version of GitLab depends on gitlab-shell 4.0.3, but you're running 4.0.0. Please update gitlab-shell.
Clearing cache...
```

**Comment by sameersbn** [comment]
Are you facing any issues with the deployment @GJRTimmer  apart from the message in the logs?

**Comment by GJRTimmer** [comment]
not at the moment.

**Comment by GJRTimmer** [comment]
close this issue until I experience a problem ?

**Comment by sameersbn** [comment]
the shell version has been updated in the master. If you were seeing any problems with the older shell version then i would create a new point release. but since it appears to be working fine (so far) then we can just wait until the next release from upstream.

Please leave the issue open.

**Comment by Quexer69** [comment]
+1

Besides there is currently no 4.0.3 release (https://github.com/gitlabhq/gitlab-shell/releases) with 4.0.0 everthing`s just fine.

**Comment by GJRTimmer** [comment]
@Quexer69 Thanks for the confirmation.
