### ISSUE TITLE
[question] Can I forward ssh connection to container (for the git user)?

### ISSUE THREAD

**Issue by averissimo** [sameersbn/docker-gitlab#1020]
### Scenario

I have gitlab running using these docker images and I want to use ssh both for git (container) and to login to the host.

### Questions

* Can it be done via the `ForceCommand` in sshd of the host? (having also a git user on host)
  * I've tried with `ForceCommand ssh git@localhost -p 10022 $SSH_ORIGINAL_COMMAND` but I still require to pass the same publickey in order for gitlab-shell to know which user it is (otherwise it thinks it is simple git from host)
* Is there any other way to forward ssh to container by User? (firewall/sshd_config/something else)
* Should I have a gitlab-shell running on host that is connected to container?

### How I have it now

Have port 22 for git alone and use something else for all other ssh

**Comment by solidnerd** [comment]
Hey,

@IlyaSemenov wrote a guide about it. It is on a pr #737 feel free to use it.

**Comment by averissimo** [comment]
_o_ @solidnerd _o_ thank you for pointing in the right direction :)

I feel stupid for not finding this, but it did not appear in my search engine's queries or when using github search
