### ISSUE TITLE
new image, 8.15.0 has wrong nginx configuration for ssl

### ISSUE THREAD

**Issue by phpb-com** [sameersbn/docker-gitlab#1032]
assets/runtime/config/nginx/gitlab-ssl on line 27 does not have "_ssl" in the end of the variable, which is later referred in reverse proxy config.

**Comment by solidnerd** [comment]
I fixed it. I will be available on latest und later in `8.15.1` .

**Comment by phpb-com** [comment]
Thank you, @solidnerd for a fast fix! 🥇
