### ISSUE TITLE
gitlab workhorse still missing in 8.15.1

### ISSUE THREAD

**Issue by GJRTimmer** [sameersbn/docker-gitlab#1036]
Upgraded to 8.15.1, anyone idea how to fix this.

![2016-12-27 10_47_27-admin area gitlab](https://cloud.githubusercontent.com/assets/6072255/21496979/969e9a9a-cc22-11e6-892a-d127c13fd962.png)

**Comment by paolomainardi** [comment]
I confirm the same bug here on 8.15.2

**Comment by GJRTimmer** [comment]
Also confirmed on 8.15.2
![2016-12-27 10_47_27-admin area gitlab](https://cloud.githubusercontent.com/assets/6072255/21852129/27f5dd64-d812-11e6-8d62-24dd7fa2087f.png)

**Comment by QuickJack** [comment]
Still missing in 8.15.4

**Comment by solidnerd** [comment]
If have the feeling that this bug exists only on our Image. So far what I know is that GitLab Workhorse passes his version via a http request header to the rails application.

**Comment by QuickJack** [comment]
Still missing in 9.04

**Comment by solidnerd** [comment]
I will close this because it's fixed now with #1187 and will be available in `9.1.0-1` or `latest`.
