### ISSUE TITLE
Upgrade to 8.14.5: Cannot push/ protected branches are not working

### ISSUE THREAD

**Issue by QuickJack** [sameersbn/docker-gitlab#1041]
There seems to be an upstream problem in GitLab https://gitlab.com/gitlab-com/support-forum/issues/207

**Comment by QuickJack** [comment]
OK, just a duplicate: https://github.com/sameersbn/docker-gitlab/issues/995

**Comment by xueshanf** [comment]
@QuickJack It seems working for me now with 8.15.4 version.
