### ISSUE TITLE
gitlab and postresql restart loop because disk is full

### ISSUE THREAD

**Issue by SylvainGirod** [sameersbn/docker-gitlab#1079]
Hello,

I'm having trouble with an issue.
it seems that gitlab and postresql can't run because my disk is full.
Do someone know which files I could delete from the /var/lib/docker/* directories in order to free some space ?

**Comment by iamchanghyunpark** [comment]
Perhaps you want to remove some older (unused) images? [link](https://gist.github.com/ngpestelos/4fc2e31e19f86b9cf10b)

**Comment by SylvainGirod** [comment]
Well, the problem was about gitlab's backups.
I had some backup for a month, and deleted those in order to free some space.

**Comment by Br41n** [comment]
@SylvainGirod You can configure GITLAB_BACKUP_EXPIRY in order to limited the days to remove backups.

**Comment by SylvainGirod** [comment]
@Br41n I changed the backups interval from day to week (which is OK for my project), and created a CRON task to delete the old backups. It's a little bit gross, but it works so I will wait the migration in order to clean it =)
Thanks for your fix, I will keep it in mind !
