### ISSUE TITLE
add ldap later

### ISSUE THREAD

**Issue by elderone** [sameersbn/docker-gitlab#108]
what if I want to add ldap integration after first RUN with setup this container?
will i need to run it again with clear all data in database?
how I can do it with working production container?

**Comment by farrukhnajmi** [comment]
@sameersbn I cant seem to configure gitlab for ldap via "LDAP_" env vars.

I start my gitlab docker container like this:

`docker run -d -p <dockerHostIp>:80:80/tcp --env-file src/docker/gitlab/env.list --name gitlab1 me/gitlab
`
My src/docker/gitlab/env.list file looks like this:

```
LDAP_ENABLED=true
LDAP_LABEL=LDAP
LDAP_HOST=ldap.corp.acme.com
LDAP_PORT=389
LDAP_UID=sAMAccountName
LDAP_METHOD=tls
LDAP_BIND_DN=CN=Git Service,OU=Non User Accounts,DC=corp,DC=acme,DC=com
LDAP_PASS=MySecretPassword
LDAP_BASE=OU=people,DC=corp,DC=acme,DC=com
LDAP_VERIFY_SSL=false
```

However, when I access gitlab login screen I do not see the ldap login tab.

My image is "FROM gitlab/gitlab-ce:10.7.3-ce.0"

My docker version is:

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Any advice on what could be wrong?
