### ISSUE TITLE
How to enable Prometheus?

### ISSUE THREAD

**Issue by nixel2007** [sameersbn/docker-gitlab#1082]
Hello!

I use your docker images via docker-compose.
I want to start included in GitLab 8.16 Prometheus service. I've exposed 9090 port in docker-compose.yml, but no luck.
[Official docs](https://docs.gitlab.com/ce/administration/monitoring/performance/prometheus.html) says, that I need to change /etc/gitlab/gitlab.rb with `prometheus['enable'] = true` string, but I can't find this file on my docker container.

Any tips?

/cc @dchernykhss

**Comment by lyda** [comment]
I'm going to look at doing this unless someone is going to be working on that.

**Comment by damiendurant** [comment]
Hi,

Official docs talks about Gitlab Omnibus package. This docker is build from source.

So the prometheus exporter should be add and build in the docker image (in the install.sh script).
Repository for gitlab-monitor is here : 
https://gitlab.com/gitlab-org/gitlab-monitor/

I'm also interrested by this feature, I will work on this if I get some time.

**Comment by damiendurant** [comment]
Hi,

I have updated the docker image here : 
https://github.com/damiendurant/docker-gitlab

It install and configure the gitlab-monitor exporter. I will update my prometheus configuration and check it's ok  next week before the do a pull request.

**Comment by nixel2007** [comment]
Good news, thanks!

**Comment by damiendurant** [comment]
I have validated with prometheus,using a shared grafana dashboard (https://grafana.net/dashboards/1575 ). It's working correctly.

I have doen a pull request https://github.com/sameersbn/docker-gitlab/pull/1102

**Comment by GJRTimmer** [comment]
Any update on this ?
I would like to enable prometheus for Gitlab

**Comment by GJRTimmer** [comment]
@damiendurant I've seen your update, is there no environment variable added for the gitlab.yml which allows the user to configure the prometheus host etc ??

**Comment by MacGyver27** [comment]
any updates??

**Comment by danielsss** [comment]
any updates?
