### ISSUE TITLE
GITLAB_REGISTRY_PATH vs GITLAB_REGISTRY_DIR

### ISSUE THREAD

**Issue by xueshanf** [sameersbn/docker-gitlab#1096]
Three  questions:
- Template/scripts are using GITLAB_REGISTRY_DIR, but the container registry README uses GITLAB_REGISTRY_PATH. Are they same thing or not? 
- If I use s3 storage backend, what is the configuration for the **path** in gitlab.yml's registry: section? Currently, if left un-set, it uses default GITLAB_REGISTRY_DIR, which is /home/git/gitlab/share/registry.
- No matter what I use for container registry backend, s3 or file system, I don't seem to be able to make images show up on GitLab UI.
It always shows "No images in Container Registry for this project", even the docker command line can push/pull and query the images. I wonder if this has anything to do with the **path** setting.  I noticed there are issues with proxy/noproxy that can cause the same problem, but I don't (at least I am not aware of) that I have set proxy/noproxy.

**Comment by xueshanf** [comment]
Figured out the right configuration for this.

**Comment by codereviewvideos** [comment]
Hi @xueshanf,

Please could you share the config you used to fix this? I'm experiencing the exact same issue.

Thanks

Chris

**Comment by xueshanf** [comment]
@codereviewvideos

Here is I think the relevant part:

For the GitLab container:
```
GITLAB_REGISTRY_ENABLED=true
GITLAB_REGISTRY_HOST=registry.example.com
GITLAB_REGISTRY_PORT=443
GITLAB_REGISTRY_API_URL=http://code.cluster.local:5500
GITLAB_REGISTRY_DIR=""
GITLAB_REGISTRY_KEY_PATH=/certs/gitlab.key
```
For the registry container:

```
DOCKER_IMAGE='registry:2.6'
DOCKER_OPTS="-p 5500:5000 \
  -e REGISTRY_AUTH_TOKEN_REALM=https://gitlab.example.com/jwt/auth \
  -e REGISTRY_AUTH_TOKEN_SERVICE=container_registry \
  -e REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/gitlab.crt \
  -e REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer \
  -e REGISTRY_STORAGE=s3 \
  -e REGISTRY_STORAGE_S3_REGION=us-west-2 \
  -e REGISTRY_STORAGE_S3_BUCKET=my-gitlab-registry \
  -e REGISTRY_STORAGE_S3_ROOTDIRECTORY=/data \
  -e REGISTRY_STORAGE_DELETE_ENABLED=true \
  -v /efs/gitlab/data/certs:/certs \
  -v /var/lib/apps/gitlab-registry/config.yml:/etc/docker/registry/config.yml"
```
Note  `GITLAB_REGISTRY_API_URL=http://gitlab.cluster.local:5500`, in which I use a private AWS Route53 DNS.  

I made a simple mistake to use http://localhost:5500 in my original configuration - there is no  service at localhost:5500  inside of GitLab container!  If run docker logs on GitLab container, I'd see timeout to localhost:5500. 

You may implement the Registry differently, but whatever you do, make sure that's resolvable and reachable *inside* of GitLab container.

**Comment by codereviewvideos** [comment]
Thanks for sharing. Unfortunately I still haven't solved my issue. I think I have something more fundamentally incorrect given everything I know at this point. It's frustrating, as I have had this working within the last 48 hours, but can't remember how. I really appreciate you sharing your config though, much appreciated.
