### ISSUE TITLE
Rotation of backup archives not working in 8.16.6

### ISSUE THREAD

**Issue by QuickJack** [sameersbn/docker-gitlab#1122]
I have two servers running 8.16.6. I noticed that both hard discs are nearly full. One intance had 27 backup archives. It seems that old backups are not deleted automatically. This is a big problem because it could fill up hard discs quickly.

**Comment by jeinwag** [comment]
Same here. Might be an upstream issue?

**Comment by QuickJack** [comment]
Thanks for confirming this.

I upgraded my server from 8.13.6. In 8.14 we had the permissions issue which wasn‘t fully resolved in 8.15. 3 months later we have several backup related issues in 8.16. Yes, I guess that these are all upstream issues.

**Comment by QuickJack** [comment]
There is an issue for this problem: https://gitlab.com/gitlab-org/gitlab-ce/issues/24530 which was created 3 months ago.

**Comment by QuickJack** [comment]
Is there any news about this issue? Will this be fixed in 8.17?

**Comment by boeserwolf91** [comment]
I'm running GitLab 8.17.3 and it seems to work. The backup directory only contains the last 7 days (which is the default value)

**Comment by QuickJack** [comment]
Many thanks. I will start testing 8.17 this afternoon.

**Comment by QuickJack** [comment]
I have just tested 8.17.4. Backup rotation is indeed working again.
