### ISSUE TITLE
Automatic backups on multiple instances

### ISSUE THREAD

**Issue by mcampo** [sameersbn/docker-gitlab#1140]
Hi, I was wondering if it's possible to have the automatic backup setup (via `GITLAB_BACKUP_SCHEDULE`) if you are running several instances of the image on a cluster, as I don't see any means of locking or synchronization when creating backups.

Thanks!

**Comment by solidnerd** [comment]
Hey,
this should be possible with an remote backup like aws, gce or minio :). For this you can use the `GITLAB_BACKUP_SCHEDULE`
