### ISSUE TITLE
gitlab not support git 2.11 and above

### ISSUE THREAD

**Issue by ledocc** [sameersbn/docker-gitlab#1144]
After updating to docker-gitlab with gitlab 8.17.4-ee, git 2.11.3 is installed in the gitlab container, but according to this [issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/25301), git 2.11 and above is not well supported by gitlab.
My solution is to download build and install git 2.10 from git repository

**Comment by solidnerd** [comment]
We don't support the ee version. So in the ce we got no problems with git directly.
