### ISSUE TITLE
Upgrade to 9.0

### ISSUE THREAD

**Issue by dereknex** [sameersbn/docker-gitlab#1148]
Gitlab 9.0 has been released. https://about.gitlab.com/2017/03/22/gitlab-9-0-released/

**Comment by andrewstuart** [comment]
I've gotten my configuration at least working in my fork, so I'll at least submit a PR for those minor updates. Mostly I just followed the docs [here](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/update/8.17-to-9.0.md) or updated the versions in the Dockerfile environment variables to the latest tags on Gitlab.

**Comment by andrewstuart** [comment]
Although it seems I missed the pre-existing PR #1147, which is getting much more activity, so I'll probably just contribute to that one and close mine. :-)

**Comment by dereknex** [comment]
I missed the PR #1147. 
Close this issue now.
