### ISSUE TITLE
PlantUML Support

### ISSUE THREAD

**Issue by MarZab** [sameersbn/docker-gitlab#1151]
GitLab supports PlantUML now, 
https://docs.gitlab.com/ee/administration/integration/plantuml.html

I propose a optional docker-compose/Dockerfile plugin/integration for the needed Tomcat Server and associated enviorment variables for GitLab.

**Comment by tuschl-digitalmobil** [comment]
Simply adding an additional service to my docker-compose.yml (see below) and setting the chosen hostname in the corresponding gitlab settings page works fine for me.  

~~~yaml
plantuml:
  image: plantuml/plantuml-server
  restart: always
  environment:
  - VIRTUAL_HOST=plantuml.mydomain.com
  - LETSENCRYPT_HOST=plantuml.mydomain.com
  - LETSENCRYPT_EMAIL=certs@mydomain.com
~~~

NOTE: I'm using [nginx-proxy](https://github.com/jwilder/nginx-proxy) and [its letsencrypt companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) for environment based reverse-proxying and SSL termination.

**Comment by MarZab** [comment]
Thanks @tuschl-digitalmobil 

here is a  `mydomain.com/plantuml/` example if anyone needs it

docker-compose.yml
``` yml
plantuml:
  image: plantuml/plantuml-server
  restart: always
  ports:
   - "127.0.0.1:9542:8080"
```
nginx.conf
``` nginx
    location /plantuml/ {
	rewrite			^/plantuml(/.*)$ $1 break;
    	proxy_redirect		off;
        proxy_set_header	Host				$http_host;
        proxy_set_header	X-Real-IP			$remote_addr;
        proxy_set_header	X-Forwarded-Ssl			on;
        proxy_set_header	X-Forwarded-For			$proxy_add_x_forwarded_for;
        proxy_set_header	X-Forwarded-Proto		$scheme;
        proxy_pass		http://127.0.0.1:9542;
    }
```
