### ISSUE TITLE
mac /home/git/data changing permissions Operation not permitted

### ISSUE THREAD

**Issue by tsouhaieb** [sameersbn/docker-gitlab#1169]
![screen shot 2017-04-08 at 2 18 44 pm](https://cloud.githubusercontent.com/assets/15350774/24829277/83a090a8-1c66-11e7-8746-87d34cb229a5.png)
i created the folder /home/git/data
i even set /home directory (and all it's element to chmod 777) but it did not resolved the problem,

is there any why to resolve it

**Comment by solidnerd** [comment]
Hey,
could you post your `docker-compos.yml` . It seems that you have something wroing in your `docker-compose.yml`

**Comment by tsouhaieb** [comment]
i used the one included

**Comment by onelson** [comment]
I'm seeing the same thing, though I'm not using compose.

I'm running with `-v /docker-data/gitlab:/home/git/data` and using `USERMAP_UID`/`USERMAP_GID`.
The directory on the host is 775 with matching uid/gid.

The log output shows

```
Mapping UID and GID for git:git to 40102:2013
chown: changing ownership of '/home/git/data': Operation not permitted
Initializing logdir...
Initializing datadir...
chmod: changing permissions of '/home/git/data': Permission denied
Initializing logdir...
Initializing datadir...
chmod: changing permissions of '/home/git/data': Permission denied
... repeated ...
```

**Comment by solidnerd** [comment]
Did you use Docker on Linux  or something Else ?

Am 17.04.2017 20:41 schrieb "Owen Nelson" <notifications@github.com>:

**Comment by onelson** [comment]
Yep - docker on linux:
`Docker version 1.12.3, build 6b644ec`

**Comment by onelson** [comment]
I've been messing with `assets/runtime/functions` to see if I can side-step the issue by prefixing some commands in `initialize_data_dir()` with `exec_as_git` but it feels a bit like pushing peas around my plate.

The init runs great when I don't use UID/GID mapping. Seems like some steps in this script should be run as the git user and some as root. Not sure how best to straddle the fence here...

**Comment by tsouhaieb** [comment]
i'm using docker on mac and i created those folder and i add permissions to user but it does not resolve the problem, i ended up using the official docker images on gitlab and it worked like a charm, but i wanted to use yours because the documentation is why better,
