### ISSUE TITLE
Reverse proxy with nginx proxy and let's encrypt 

### ISSUE THREAD

**Issue by Ludea** [sameersbn/docker-gitlab#1170]
Hello, 
I try to setup gitlab on Docker with a reverse proxy : https://github.com/jwilder/nginx proxy and let's encrypt : https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion but it is not working. 

I would like a subdomain like : gitlab.example.com

Here is my docker compose file:

version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab 
    environment:
      - VIRTUAL_HOST=gitlab.example.com 
      - LETSENCRYPT_HOST=gitlab.example.com 
      - LETSENCRYPT_EMAIL=contact@example.com

**Comment by Ludea** [comment]
Fix with a good configuration

**Comment by niksubramanian** [comment]
@Ludea could you post your final configuration?

Thanks in advance.

**Comment by NetIds** [comment]
@Ludea same, i would like to set also github behind nginx-proxy. Could you post your fival config? Thx
