### ISSUE TITLE
can't send email

### ISSUE THREAD

**Issue by yknext** [sameersbn/docker-gitlab#1172]
Hello,
after  upgrade to sameersbn/gitlab:9.0.5 ,cant send email,

gitlab:
  restart: always
//old  image: sameersbn/gitlab:8.16.4
  image: sameersbn/gitlab:9.0.5
  ports:
    - "10022:22"
    - "10080:80"
    - "10443:443"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - gitlab_data:/home/git/data
    - gitlab_log:/var/log/gitlab
  environment: 
    GOOGLE_ANALYTICS_ID: example
    GITLAB_SSH_PORT: 10022
    GITLAB_EMAIL: example@qq.com
    SMTP_DOMAIN: qq.com
    SMTP_HOST: smtp.qq.com
    SMTP_PORT: 465
    SMTP_USER: example@qq.com
    SMTP_PASS: password
    IMAP_USER: example@qq.com
    IMAP_PASS: password
    GITLAB_HTTPS: "true"
    SSL_SELF_SIGNED: "true"
    NGINX_HSTS_MAXAGE: 2592000
    GITLAB_HOST: example.com
    GITLAB_SECRETS_OTP_KEY_BASE: xxx
    GITLAB_SECRETS_SECRET_KEY_BASE: xxx
    GITLAB_SECRETS_DB_KEY_BASE: xxx
  links:
    - gitlab_mysql:mysql
    - gitlab_redis:redisio

 some log :

/usr/lib/ruby/2.3.0/net/imap.rb:1196:in `get_tagged_response': Lookup failed m103mb99974731ioo (Net::IMAP::NoResponseError)
	from /usr/lib/ruby/2.3.0/net/imap.rb:1250:in `block in send_command'
	from /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /usr/lib/ruby/2.3.0/net/imap.rb:1232:in `send_command'
	from /usr/lib/ruby/2.3.0/net/imap.rb:436:in `login'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.1/lib/mail_room/connection.rb:84:in `log_in'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.1/lib/mail_room/connection.rb:68:in `setup'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.1/lib/mail_room/connection.rb:8:in `initialize'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.1/lib/mail_room/mailbox_watcher.rb:57:in `new'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.1/lib/mail_room/mailbox_watcher.rb:57:in `connection'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.1/lib/mail_room/mailbox_watcher.rb:28:in `run'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.1/lib/mail_room/coordinator.rb:19:in `each'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.1/lib/mail_room/coordinator.rb:19:in `run'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.1/lib/mail_room/cli.rb:52:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.1/bin/mail_room:5:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/bin/mail_room:22:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/bin/mail_room:22:in `<main>'

**Comment by avluis** [comment]
Have you tried without the `@<domain>.<tld>` portion? -- I know my smtp server won't authenticate with it.

**Comment by yknext** [comment]
@avluis i am try to remove domain.tld portion ,but now working

**Comment by timfeirg** [comment]
close this issue then? @yknext
