### ISSUE TITLE
LDAP config causes 502 error on webinterface

### ISSUE THREAD

**Issue by metamorphious** [sameersbn/docker-gitlab#1173]
I'm trying to setup gitlab via the docker-compose file.
Everything works fine until I configure LDAP, then I constantly get a 502 error on the webinterface and sidekiq and unicorn keep exiting with exit status 1 (and are restarted).

One problem I identified is that the password for the LDAP bind contains a '
That breaks some config inside the gitlab container I think. Unfortunately it is (at the moment) not
an option to change the password.
Is there a way to properly escape that character or do something else?

Thanks for the help and the good work!!

**Comment by avluis** [comment]
That's not exactly the greatest character in a password (not because of security) when it comes to scripting.
In my experience, if you can't wrap strings with `''` then you can use `""` -- but in the case of a Dockerfile, as well as any other files read by cli, single quotes are just nasty to deal with: https://github.com/docker/docker/issues/5701

Have you tried wrapping that password in double quotes?
This is the environment variable used for [LDAP PASS](https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/env-defaults#L236): `LDAP_PASS=${LDAP_PASS:-}` so I'm not sure how it will resolve, but best of luck.

As for escaping: `\` is what you are looking for -- but once again, this `${LDAP_PASS:-}` is usually used as a literal -- give it a try though. And please let us know if you had to change the password to address this.

**Comment by metamorphious** [comment]
Thats the backdraw of generated passwords.. Until no it was no problem.

I tried using double quotes as well as escaping with a `\`. Makes no difference. The password is wrappend in `''` inside the gitlab.yml config inside the gitlab container. So I think that is the place where it breaks.

I looked up the logs inside the gitlab container. I found a repeating error message in the unicorn.stderr.log but I'm not sure if it helps:

`I, [2017-04-18T09:31:06.221681 #535]  INFO -- : Refreshing Gem list
/usr/lib/ruby/2.3.0/psych.rb:379:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 247 column 9 (Psych::SyntaxError)
	from /usr/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /usr/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /usr/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:37:in `[]'
	from /home/git/gitlab/config/initializers/1_settings.rb:113:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
	from /home/git/gitlab/config/environment.rb:5:in `<top (required)>'
	from config.ru:19:in `require'
	from config.ru:19:in `block in <main>'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `eval'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `block in builder'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/bin/unicorn_rails:139:in `block in rails_builder'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:752:in `build_app!'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:129:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/bin/unicorn_rails:22:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/bin/unicorn_rails:22:in `<main>'`

**Comment by avluis** [comment]
The error you are seeing there is confirming that process not being able to read or missing all the launch arguments that it needs -- in this case, it's the `'` in the password causing this unfortunately.

If the password was wrapped with double quotes, that wouldn't be an issue -- but then it would break with a double quote 😆

What this field needs is sanitation, but why go thru all that trouble and instead sanitize the password itself.

Anyways, addressing this issue would be up to the image author, and how much time spent fixing this vs. results or other improvements 😢
Unless someone has a shell trick to escape this, I'm not certain of any other way to get around this.

**Comment by hanej** [comment]
If you're using docker-compose to set this environment variable, you have to escape the ' character in YAML.  The way to escape the ' character in YAML is to double it.  So if your LDAP password is `pass'word` then you should put `pass''word` in your YAML file.

**Comment by metamorphious** [comment]
Thanks for the tips and the help
