### ISSUE TITLE
Can't enable mattermost 

### ISSUE THREAD

**Issue by stepanorda** [sameersbn/docker-gitlab#1175]
In docker-compose.yml I have:
```
    - GITLAB_MATTERMOST_ENABLED=true
    - GITLAB_MATTERMOST_URL=http://chat.mydomain.com
```
Updated with `docker-compose up -d` and nothing. Regular gitlab is loaded from this URL. 
When it starts I see `gitlab_1      | Configuring gitlab::mattermost...` among others.
I have `sameersbn/gitlab:9.0.5`

**Comment by jostyee** [comment]
Can you visit http://chat.mydomain.com directly?

**Comment by stepanorda** [comment]
Yes, it opens gitlab.

**Comment by jostyee** [comment]
I guess it should be forwarded to a Mattermost instance?

**Comment by stepanorda** [comment]
Yes that's what I was expecting to see.

**Comment by jostyee** [comment]
I mean it's your work to establish the Mattermost instance, before enable the `GITLAB_MATTERMOST_ENABLED` setting.

**Comment by stepanorda** [comment]
It's built in gitlab now https://docs.gitlab.com/omnibus/gitlab-mattermost/ so you should only set one setting and run `sudo gitlab-ctl reconfigure`. Is it not implemented here yet?

**Comment by jostyee** [comment]
What you referred to is GitLab Omnibus(bundled with Mattermost), this repo only contains GitLab CE.

**Comment by stepanorda** [comment]
Oh, my bad. Now I get it. Thank you for clearing things up!
