### ISSUE TITLE
SMTP does not work

### ISSUE THREAD

**Issue by johnjelinek** [sameersbn/docker-gitlab#118]
Even with STMP settings set, `production.rb` still says sendmail.

``` bash
docker run -it --rm --link postgresql:postgresql --link redis:redisio \
-e 'GITLAB_PROJECTS_VISIBILITY=public' -e 'GITLAB_PORT=80' \
-e 'GITLAB_SSH_PORT=2222' -e 'NGINX_MAX_UPLOAD_SIZE=800m' \
-e 'DB_USER=git' -e 'DB_PASS=password' -e 'SMTP_DOMAIN=www.example.com' \
-e 'SMTP_HOST=smtp.example.com' -e 'SMTP_PORT=25' \
-e 'SMTP_AUTHENTICATION=none' -v /opt/gitlab/data:/home/git/data sameersbn/gitlab:7.1.1 bash
```

```
 root@gitlab:/home/git/gitlab# grep mailer config/environments/production.rb
  # config.action_mailer.raise_delivery_errors = false
  config.action_mailer.delivery_method = :sendmail
  # # config.action_mailer.sendmail_settings = {
  config.action_mailer.perform_deliveries = true
  config.action_mailer.raise_delivery_errors = true
```

**Comment by hsitaa** [comment]
Its not Working. Specified the conf. Do i need to expose any port in Docker compose yml.

my Host machine : Centos7
running it on Docker for gitlab, 

mails are working for Host machine. But when try to send mail from gitlab. Nothing happens.

1.) Do i need to install postfix on Docker machine?
2.) Do i need to expose any port.
3.) Tried using Gmail smtp as well as extrernal mailserver. : Which 1 suggested?

**Comment by sameersbn** [comment]
please create a new issue report.
