### ISSUE TITLE
dhparam and trusted certs

### ISSUE THREAD

**Issue by jonkristian** [sameersbn/docker-gitlab#1181]
I am not using self-signed certs. I have .cert and .key.

For some reason if i leave out dhparam gitlab won't run at all, well I get connection refused, and if I generate the .pem file it works fine in the browser and ssh git but not https:// through git, I get this error:
`fatal: unable to access 'https://***': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`

I've also tried to generate the .pem file from my cert and key but that doesn't seem to work either.

Any ideas?

**Comment by truck0321** [comment]
I'm having the same problem.  Relevant docker-compose.yml entries below:


  gitlab:
    restart: always
    image: sameersbn/gitlab:9.0.5
    depends_on:
    - redis
    - postgresql
    ports:
    - "80:80"
    - "443:443"
    - "10022:22"
    volumes:
    - /opt/docker/gitlab/gitlab:/home/git/data:Z
    environment:

    - GITLAB_HTTPS=true
    - SSL_SELF_SIGNED=false
    - SSL_CERTIFICATE_PATH=/home/git/data/certs/gitlab-public.crt
    - SSL_KEY_PATH=/home/git/data/certs/gitlab-private.key
    - SSL_DHPARAM_PATH=/home/git/data/certs/dhparam.pem

**Comment by truck0321** [comment]
Here is the error.  

[root@DC1DKRPRD01 ~]# docker logs --tail all -f root_gitlab_1
Initializing logdir...
Initializing datadir...
Updating CA certificates...
find: `./ACCVRAIZ1.pem': No such file or directory
find: `./ACEDICOM_Root.pem': No such file or directory
find: `./AC_Ra\303\255z_Certic\303\241mara_S.A..pem': No such file or directory
find: `./Actalis_Authentication_Root_CA.pem': No such file or directory
find: `./AddTrust_External_Root.pem': No such file or directory
find: `./AddTrust_Low-Value_Services_Root.pem': No such file or directory
find: `./AddTrust_Public_Services_Root.pem': No such file or directory
find: `./AddTrust_Qualified_Certificates_Root.pem': No such file or directory
find: `./AffirmTrust_Commercial.pem': No such file or directory
find: `./AffirmTrust_Networking.pem': No such file or directory
find: `./AffirmTrust_Premium.pem': No such file or directory
find: `./AffirmTrust_Premium_ECC.pem': No such file or directory
find: `./ApplicationCA_-_Japanese_Government.pem': No such file or directory
find: `./Atos_TrustedRoot_2011.pem': No such file or directory
find: `./Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.pem': No such file or directory
find: `./Baltimore_CyberTrust_Root.pem': No such file or directory
find: `./Buypass_Class_2_CA_1.pem': No such file or directory
find: `./Buypass_Class_2_Root_CA.pem': No such file or directory
find: `./Buypass_Class_3_Root_CA.pem': No such file or directory
find: `./CA_Disig.pem': No such file or directory
find: `./CA_Disig_Root_R1.pem': No such file or directory
find: `./CA_Disig_Root_R2.pem': No such file or directory
find: `./CA_WoSign_ECC_Root.pem': No such file or directory
find: `./CFCA_EV_ROOT.pem': No such file or directory
find: `./CNNIC_ROOT.pem': No such file or directory
find: `./COMODO_Certification_Authority.pem': No such file or directory
find: `./COMODO_ECC_Certification_Authority.pem': No such file or directory
find: `./COMODO_RSA_Certification_Authority.pem': No such file or directory
find: `./Camerfirma_Chambers_of_Commerce_Root.pem': No such file or directory
find: `./Camerfirma_Global_Chambersign_Root.pem': No such file or directory
find: `./Certification_Authority_of_WoSign_G2.pem': No such file or directory
find: `./Certigna.pem': No such file or directory
find: `./Certinomis_-_Autorit\303\251_Racine.pem': No such file or directory
find: `./Certinomis_-_Root_CA.pem': No such file or directory
find: `./Certplus_Class_2_Primary_CA.pem': No such file or directory
find: `./Certum_Root_CA.pem': No such file or directory
find: `./Certum_Trusted_Network_CA.pem': No such file or directory
find: `./Chambers_of_Commerce_Root_-_2008.pem': No such file or directory
find: `./China_Internet_Network_Information_Center_EV_Certificates_Root.pem': No such file or directory
find: `./ComSign_CA.pem': No such file or directory
find: `./Comodo_AAA_Services_root.pem': No such file or directory
find: `./Comodo_Secure_Services_root.pem': No such file or directory
find: `./Comodo_Trusted_Services_root.pem': No such file or directory
find: `./Cybertrust_Global_Root.pem': No such file or directory
find: `./D-TRUST_Root_Class_3_CA_2_2009.pem': No such file or directory
find: `./D-TRUST_Root_Class_3_CA_2_EV_2009.pem': No such file or directory
find: `./DST_ACES_CA_X6.pem': No such file or directory
find: `./DST_Root_CA_X3.pem': No such file or directory
find: `./Deutsche_Telekom_Root_CA_2.pem': No such file or directory
find: `./DigiCert_Assured_ID_Root_CA.pem': No such file or directory
find: `./DigiCert_Assured_ID_Root_G2.pem': No such file or directory
find: `./DigiCert_Assured_ID_Root_G3.pem': No such file or directory
find: `./DigiCert_Global_Root_CA.pem': No such file or directory
find: `./DigiCert_Global_Root_G2.pem': No such file or directory
find: `./DigiCert_Global_Root_G3.pem': No such file or directory
find: `./DigiCert_High_Assurance_EV_Root_CA.pem': No such file or directory
find: `./DigiCert_Trusted_Root_G4.pem': No such file or directory
find: `./E-Tugra_Certification_Authority.pem': No such file or directory
find: `./EBG_Elektronik_Sertifika_Hizmet_Sa\304\237lay\304\261c\304\261s\304\261.pem': No such file or directory
find: `./EC-ACC.pem': No such file or directory
find: `./EE_Certification_Centre_Root_CA.pem': No such file or directory
find: `./Entrust.net_Premium_2048_Secure_Server_CA.pem': No such file or directory
find: `./Entrust_Root_Certification_Authority.pem': No such file or directory
find: `./Entrust_Root_Certification_Authority_-_EC1.pem': No such file or directory
find: `./Entrust_Root_Certification_Authority_-_G2.pem': No such file or directory
find: `./Equifax_Secure_CA.pem': No such file or directory
find: `./Equifax_Secure_Global_eBusiness_CA.pem': No such file or directory
find: `./Equifax_Secure_eBusiness_CA_1.pem': No such file or directory
find: `./GeoTrust_Global_CA.pem': No such file or directory
find: `./GeoTrust_Global_CA_2.pem': No such file or directory
find: `./GeoTrust_Primary_Certification_Authority.pem': No such file or directory
find: `./GeoTrust_Primary_Certification_Authority_-_G2.pem': No such file or directory
find: `./GeoTrust_Primary_Certification_Authority_-_G3.pem': No such file or directory
find: `./GeoTrust_Universal_CA.pem': No such file or directory
find: `./GeoTrust_Universal_CA_2.pem': No such file or directory
find: `./GlobalSign_ECC_Root_CA_-_R4.pem': No such file or directory
find: `./GlobalSign_ECC_Root_CA_-_R5.pem': No such file or directory
find: `./GlobalSign_Root_CA.pem': No such file or directory
find: `./GlobalSign_Root_CA_-_R2.pem': No such file or directory
find: `./GlobalSign_Root_CA_-_R3.pem': No such file or directory
find: `./Global_Chambersign_Root_-_2008.pem': No such file or directory
find: `./Go_Daddy_Class_2_CA.pem': No such file or directory
find: `./Go_Daddy_Root_Certificate_Authority_-_G2.pem': No such file or directory
find: `./Hellenic_Academic_and_Research_Institutions_RootCA_2011.pem': No such file or directory
find: `./Hongkong_Post_Root_CA_1.pem': No such file or directory
find: `./IGC_A.pem': No such file or directory
find: `./IdenTrust_Commercial_Root_CA_1.pem': No such file or directory
find: `./IdenTrust_Public_Sector_Root_CA_1.pem': No such file or directory
find: `./Izenpe.com.pem': No such file or directory
find: `./Juur-SK.pem': No such file or directory
find: `./Microsec_e-Szigno_Root_CA.pem': No such file or directory
find: `./Microsec_e-Szigno_Root_CA_2009.pem': No such file or directory
find: `./NetLock_Arany_=Class_Gold=_F\305\221tan\303\272s\303\255tv\303\241ny.pem': No such file or directory
find: `./NetLock_Business_=Class_B=_Root.pem': No such file or directory
find: `./NetLock_Express_=Class_C=_Root.pem': No such file or directory
find: `./NetLock_Notary_=Class_A=_Root.pem': No such file or directory
find: `./NetLock_Qualified_=Class_QA=_Root.pem': No such file or directory
find: `./Network_Solutions_Certificate_Authority.pem': No such file or directory
find: `./OISTE_WISeKey_Global_Root_GA_CA.pem': No such file or directory
find: `./OISTE_WISeKey_Global_Root_GB_CA.pem': No such file or directory
find: `./PSCProcert.pem': No such file or directory
find: `./QuoVadis_Root_CA.pem': No such file or directory
find: `./QuoVadis_Root_CA_1_G3.pem': No such file or directory
find: `./QuoVadis_Root_CA_2.pem': No such file or directory
find: `./QuoVadis_Root_CA_2_G3.pem': No such file or directory
find: `./QuoVadis_Root_CA_3.pem': No such file or directory
find: `./QuoVadis_Root_CA_3_G3.pem': No such file or directory
find: `./RSA_Security_2048_v3.pem': No such file or directory
find: `./Root_CA_Generalitat_Valenciana.pem': No such file or directory
find: `./S-TRUST_Authentication_and_Encryption_Root_CA_2005_PN.pem': No such file or directory
find: `./S-TRUST_Universal_Root_CA.pem': No such file or directory
find: `./SecureSign_RootCA11.pem': No such file or directory
find: `./SecureTrust_CA.pem': No such file or directory
find: `./Secure_Global_CA.pem': No such file or directory
find: `./Security_Communication_EV_RootCA1.pem': No such file or directory
find: `./Security_Communication_RootCA2.pem': No such file or directory
find: `./Security_Communication_Root_CA.pem': No such file or directory
find: `./Sonera_Class_1_Root_CA.pem': No such file or directory
find: `./Sonera_Class_2_Root_CA.pem': No such file or directory
find: `./Staat_der_Nederlanden_EV_Root_CA.pem': No such file or directory
find: `./Staat_der_Nederlanden_Root_CA.pem': No such file or directory
find: `./Staat_der_Nederlanden_Root_CA_-_G2.pem': No such file or directory
find: `./Staat_der_Nederlanden_Root_CA_-_G3.pem': No such file or directory
find: `./Starfield_Class_2_CA.pem': No such file or directory
find: `./Starfield_Root_Certificate_Authority_-_G2.pem': No such file or directory
find: `./Starfield_Services_Root_Certificate_Authority_-_G2.pem': No such file or directory
find: `./StartCom_Certification_Authority.pem': No such file or directory
find: `./StartCom_Certification_Authority_2.pem': No such file or directory
find: `./StartCom_Certification_Authority_G2.pem': No such file or directory
find: `./SwissSign_Gold_CA_-_G2.pem': No such file or directory
find: `./SwissSign_Platinum_CA_-_G2.pem': No such file or directory
find: `./SwissSign_Silver_CA_-_G2.pem': No such file or directory
find: `./Swisscom_Root_CA_1.pem': No such file or directory
find: `./Swisscom_Root_CA_2.pem': No such file or directory
find: `./Swisscom_Root_EV_CA_2.pem': No such file or directory
find: `./T-TeleSec_GlobalRoot_Class_2.pem': No such file or directory
find: `./T-TeleSec_GlobalRoot_Class_3.pem': No such file or directory
find: `./TC_TrustCenter_Class_3_CA_II.pem': No such file or directory
find: `./TURKTRUST_Certificate_Services_Provider_Root_2007.pem': No such file or directory
find: `./TWCA_Global_Root_CA.pem': No such file or directory
find: `./TWCA_Root_Certification_Authority.pem': No such file or directory
find: `./Taiwan_GRCA.pem': No such file or directory
find: `./TeliaSonera_Root_CA_v1.pem': No such file or directory
find: `./Trustis_FPS_Root_CA.pem': No such file or directory
find: `./T\303\234B\304\260TAK_UEKAE_K\303\266k_Sertifika_Hizmet_Sa\304\237lay\304\261c\304\261s\304\261_-_S\303\274r\303\274m_3.pem': No such file or directory
find: `./T\303\234RKTRUST_Elektronik_Sertifika_Hizmet_Sa\304\237lay\304\261c\304\261s\304\261_H5.pem': No such file or directory
find: `./T\303\234RKTRUST_Elektronik_Sertifika_Hizmet_Sa\304\237lay\304\261c\304\261s\304\261_H6.pem': No such file or directory
find: `./USERTrust_ECC_Certification_Authority.pem': No such file or directory
find: `./USERTrust_RSA_Certification_Authority.pem': No such file or directory
find: `./UTN_USERFirst_Email_Root_CA.pem': No such file or directory
find: `./UTN_USERFirst_Hardware_Root_CA.pem': No such file or directory
find: `./VeriSign_Universal_Root_Certification_Authority.pem': No such file or directory
find: `./VeriSign_Class_3_Public_Primary_Certification_Authority_-_G4.pem': No such file or directory
find: `./VeriSign_Class_3_Public_Primary_Certification_Authority_-_G5.pem': No such file or directory
find: `./Verisign_Class_1_Public_Primary_Certification_Authority.pem': No such file or directory
find: `./Verisign_Class_1_Public_Primary_Certification_Authority_-_G2.pem': No such file or directory
find: `./Verisign_Class_1_Public_Primary_Certification_Authority_-_G3.pem': No such file or directory
find: `./Verisign_Class_2_Public_Primary_Certification_Authority_-_G2.pem': No such file or directory
find: `./Verisign_Class_2_Public_Primary_Certification_Authority_-_G3.pem': No such file or directory
find: `./Verisign_Class_3_Public_Primary_Certification_Authority.pem': No such file or directory
find: `./Verisign_Class_3_Public_Primary_Certification_Authority_-_G2.pem': No such file or directory
find: `./Verisign_Class_3_Public_Primary_Certification_Authority_-_G3.pem': No such file or directory
find: `./Verisign_Class_3_Public_Primary_Certification_Authority_2.pem': No such file or directory
find: `./Visa_eCommerce_Root.pem': No such file or directory
find: `./WellsSecure_Public_Root_Certificate_Authority.pem': No such file or directory
find: `./WoSign.pem': No such file or directory
find: `./WoSign_China.pem': No such file or directory
find: `./XRamp_Global_CA_Root.pem': No such file or directory
find: `./certSIGN_ROOT_CA.pem': No such file or directory
find: `./ePKI_Root_Certification_Authority.pem': No such file or directory
find: `./thawte_Primary_Root_CA.pem': No such file or directory
find: `./thawte_Primary_Root_CA_-_G2.pem': No such file or directory
find: `./thawte_Primary_Root_CA_-_G3.pem': No such file or directory
Error opening Certificate ca-certificates.crt
140642280973984:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('ca-certificates.crt','r')
140642280973984:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
unable to load certificate
WARNING: ca-certificates.crt does not contain a certificate or CRL: skipping
Installing configuration templates...
SSL Key, SSL Certificate and DHParam were not found.
Assuming that the container is running behind a HTTPS enabled load balancer.
Configuring gitlab...
Configuring gitlab::database.
Configuring gitlab::redis
Configuring gitlab::secrets...
Configuring gitlab::sidekiq...
Configuring gitlab::gitlab-workhorse...
Configuring gitlab::unicorn...
Configuring gitlab::timezone...
Configuring gitlab::rack_attack...
Configuring gitlab::ci...
Configuring gitlab::artifacts...
Configuring gitlab::lfs...
Configuring gitlab::mattermost...
Configuring gitlab::project_features...
Configuring gitlab::smtp_settings...
Configuring gitlab::oauth...
Configuring gitlab::ldap...
Configuring gitlab::backups...
Configuring gitlab::backups::schedule...
Configuring gitlab::registry...
Configuring gitlab::pages...
Configuring gitlab-shell...
Configuring nginx...
Configuring nginx::gitlab...
Configuring nginx::gitlab::hsts...
2017-04-20 13:47:41,444 CRIT Supervisor running as root (no user in config file)
2017-04-20 13:47:41,445 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2017-04-20 13:47:41,445 WARN Included extra file "/etc/supervisor/conf.d/gitlab-workhorse.conf" during parsing
2017-04-20 13:47:41,445 WARN Included extra file "/etc/supervisor/conf.d/mail_room.conf" during parsing
2017-04-20 13:47:41,445 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2017-04-20 13:47:41,445 WARN Included extra file "/etc/supervisor/conf.d/sidekiq.conf" during parsing
2017-04-20 13:47:41,445 WARN Included extra file "/etc/supervisor/conf.d/sshd.conf" during parsing
2017-04-20 13:47:41,445 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
2017-04-20 13:47:41,462 INFO RPC interface 'supervisor' initialized
2017-04-20 13:47:41,462 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-04-20 13:47:41,462 INFO supervisord started with pid 1
2017-04-20 13:47:42,465 INFO spawned: 'sidekiq' with pid 3168
2017-04-20 13:47:42,466 INFO spawned: 'unicorn' with pid 3169
2017-04-20 13:47:42,468 INFO spawned: 'gitlab-workhorse' with pid 3170
2017-04-20 13:47:42,469 INFO spawned: 'cron' with pid 3171
2017-04-20 13:47:42,470 INFO spawned: 'nginx' with pid 3172
2017-04-20 13:47:42,471 INFO spawned: 'sshd' with pid 3173
2017-04-20 13:47:44,224 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-04-20 13:47:44,224 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-04-20 13:47:44,224 INFO success: gitlab-workhorse entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-04-20 13:47:44,224 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-04-20 13:47:44,224 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-04-20 13:47:44,225 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-04-20 13:47:54,119 INFO exited: sidekiq (exit status 1; not expected)
2017-04-20 13:47:55,120 INFO spawned: 'sidekiq' with pid 3189
2017-04-20 13:47:56,122 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Updating CA certificates

**Comment by jonkristian** [comment]
I managed to get a working pem file by following [this](http://wiki.znc.in/Signed_SSL_certificate).

What I did was move my chain file to `dhparam.pem` and generate the pem file: `openssl dhparam -out tmp.pem 2048` then apply that to my chain file like this: `cat tmp.pem >> dhparam.pam`

**Comment by jonkristian** [comment]
Spoke too soon. It's not working. I wonder if it's possible to turn off dhparam?

**Comment by NathanaelA** [comment]
For anybody having this issue; I just solved it on my own instance by using the full chain of certificates in the .crt file.   My certificate was the first, and then the rest of the validation certs was next in the file.   If you are using Letsencrypt; the `fullchain.pem` is already setup and so you use this for your `gitlab.crt` file.
