### ISSUE TITLE
Root user not creating [kubernetes]

### ISSUE THREAD

**Issue by Dm3Ch** [sameersbn/docker-gitlab#1183]
Hello!
I've deployed kubernetes version of your docker-gitlab. When I haven't set email and password for root I got set password page with error. But when I setted up email and password before deploy, i got login or password incorrect. 
I realized that `users` table in DB is empty.

P.S. I'm useing your default yamls

**Comment by xueshanf** [comment]
My guess - make sure the password is not too short.

**Comment by Dm3Ch** [comment]
@xueshanf Your suggestion was right. Thank you for help
