### ISSUE TITLE
docker build failed

### ISSUE THREAD

**Issue by iwater** [sameersbn/docker-gitlab#1188]
got error
 The command '/bin/sh -c bash ${GITLAB_BUILD_DIR}/install.sh' returned a non-zero code: 137

test with tag 9.1.0-1/9.0.5/8.17.4 got that same error message

docker build on DigitalOcean Docker 17.04.0-ce on Ubuntu 16.04 instance

**Comment by catesandrew** [comment]
You need to also copy `./config/resque.yml.example` to `./config/resque.yml` for `assets:precompile` to work now. perhaps others too but I believe that is it for now in addition to `gitlab.yml` and `database.yml`.

**Comment by lsm** [comment]
Add 

```exec_as_git cp ${GITLAB_INSTALL_DIR}/config/resque.yml.example ${GITLAB_INSTALL_DIR}/config/resque.yml``` 

to file `assets/build/install.sh` before rake bundle the assets.

**Comment by solidnerd** [comment]
I can confirm this. It allows us to build again. I have no clue why this solves the problem. It will build again on Docker Hosts. @lsm would you make an PR for that or should I ?

**Comment by lsm** [comment]
https://github.com/sameersbn/docker-gitlab/pull/1208 here you go @solidnerd
