### ISSUE TITLE
SSH key permissions

### ISSUE THREAD

**Issue by plasmaphase** [sameersbn/docker-gitlab#1207]
when trying to connect via SSH, we get:

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0755 for '/home/git/data/ssh/ssh_host_rsa_key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
bad permissions: ignore key: /home/git/data/ssh/ssh_host_rsa_key
Could not load host key: /home/git/data/ssh/ssh_host_rsa_key

Then we tried modifying the permissions on the files in /home/git/data/ssh/* and noticed that when doing :

chmod 600 *

The files aren't taking those permissions, even though we are root.
-rwxr-xr-x 1 root root   99 Apr 28 20:44 ssh_host_ed25519_key.pub
-rwxr-xr-x 1 root root  411 Apr 28 20:44 ssh_host_ed25519_key
-rwxr-xr-x 1 root root  179 Apr 28 20:44 ssh_host_ecdsa_key.pub
-rwxr-xr-x 1 root root  227 Apr 28 20:44 ssh_host_ecdsa_key
-rwxr-xr-x 1 root root  607 Apr 28 20:44 ssh_host_dsa_key.pub
-rwxr-xr-x 1 root root  668 Apr 28 20:44 ssh_host_dsa_key
-rwxr-xr-x 1 root root  399 Apr 28 20:44 ssh_host_rsa_key.pub
-rwxr-xr-x 1 root root 1.7K Apr 28 20:44 ssh_host_rsa_key
-rwxr-xr-x 1 root root  647 Apr 28 20:44 ssh_host_key.pub
-rwxr-xr-x 1 root root  982 Apr 28 20:44 ssh_host_key
drwxr-xr-x 2 root root 4.0K Apr 28 20:44 ..

**Comment by r2evans** [comment]
I'm assuming you have a volume mounted on `/home/git/data` (as you likely should).

1. What is the host OS?
3. If not windows, on the host side of that volume, what are the mount options? For instance, something like:
    `/dev/sdb3 on /srv type ext4 (rw,relatime,data=ordered)`

If the host is Windows, you're likely out-of-luck, as unix-y perms don't really work well in this regard.

**Comment by r2evans** [comment]
(BTW, this might be assisted by https://github.com/sameersbn/docker-gitlab/pull/907)

**Comment by plasmaphase** [comment]
Yes, it's Windows.  That's unfortunate.  Thanks for the reply.
