### ISSUE TITLE
Missing LDAP Options

### ISSUE THREAD

**Issue by GJRTimmer** [sameersbn/docker-gitlab#1215]
The following LDAP options are not mapped to a container enviroment variable.

[Reference Documentation](https://docs.gitlab.com/ce/administration/auth/ldap.html)

* group_base
* admin_group
* sync_ssh_keys

**Comment by hanej** [comment]
Those variables are for EE only

**Comment by GJRTimmer** [comment]
Found the comment about EE, yhou are correct. Issue Closed

**Comment by mehrdadhosseinzadeh** [comment]
i want to set admin_group config for login admin user into gitlab from LDAP server
please help me
