### ISSUE TITLE
cannot custom domain

### ISSUE THREAD

**Issue by zhonger** [sameersbn/docker-gitlab#1218]
docker-gitlab version : `9.1.4`
When I use `docker-compose.yml` like this:
```yml
- GITLAB_PAGES_ENABLED=true
- GITLAB_PAGES_DOMAIN=shuosc.cn
- GITLAB_PAGES_DIR=/home/git/data/share/pages
- GITLAB_PAGES_PORT=80
- GITLAB_PAGES_HTTPS=false
```
`gitlab-page` works, `*.shusoc.cn` is reachable.But after I add this content:
```yml
- GITLAB_PAGES_EXTERNAL_HTTP=true
- GITLAB_PAGES_EXTERNAL_HTTPS=false
```
and add a custom domain. `gitlab-page` doesn't work, `*.shusoc.cn` is unreachable.
When I `docker logs` this `gitlab` container, I get that `INFO exited: gitlab-pages (exit status 1; not expected)`.
I am looking forward some help from someone, Thanks.

**Comment by pkorthal** [comment]
According to: https://docs.gitlab.com/ee/administration/pages/#custom-domains-with-tls-support 
`gitlab_pages['external_http'] = ['1.1.1.2:80', '[2001::2]:80']`

GITLAB_PAGES_EXTERNAL_HTTP should point to interface and port on which custom pages will be served

`GITLAB_PAGES_EXTERNAL_HTTP=gitlab:8080` should be set, where `gitlab` is your container name
