### ISSUE TITLE
ENV for email_from

### ISSUE THREAD

**Issue by lippoliv** [sameersbn/docker-gitlab#1221]
I configured GitLab for a friend of mine, like I did it for me too. Regarding Mails his Hoster has a difference to my own Hosting: The username is no mail address (just "genereated_user", not "user@domain.tld")

In GitLab Omnibus you could edit config:

```
# If your SMTP server does not like the default 'From: gitlab@localhost' you
# can change the 'From' with this setting.
gitlab_rails['gitlab_email_from'] = 'gitlab@example.com'
```

But in GitLab Docker (wich i REALLY like) there is no Environment Variable thatfor...

Can you please add this env variable?

**Comment by solidnerd** [comment]
How about `GITLAB_EMAIL_REPLY_TO` ? If it's doesn't solve your issue. Feel free to reopen it.

**Comment by lippoliv** [comment]
@solidnerd There is no context between your answer and my Issue?

I need to realize the following:

Login via SMTP with Username w7365ds and some PW. But that username is no valid E-Mail-Adress. So I have to set the "Email From" Mail adress seperate.

Please re-open this Issue.

**Comment by solidnerd** [comment]
@lippoliv Why is there no context ? We have an environment variable that solves your problem. I posted it directly. We don't need to add a new one. You can set the `SMTP_USER` with your credentials and set the `GITLAB_EMAIL` and `GITLAB_EMAIL_REPLY_TO` to your real address for the mail server. 


| Parameter | Description |
|-----------|-------------|
| `GITLAB_EMAIL` | The email address for the GitLab server. Defaults to value of `SMTP_USER`, else defaults to `example@example.com`. |
| `GITLAB_EMAIL_REPLY_TO` | The reply-to address of emails sent out by GitLab. Defaults to value of `GITLAB_EMAIL`, else defaults to `noreply@example.com`. |

**Comment by lippoliv** [comment]
@solidnerd oh my goodness, better to read, than to ask... sorry I really did not see the `GITLAB_EMAIL` env :/

THANK you for answering that fast and good. It works now.
