### ISSUE TITLE
How to migrate EE

### ISSUE THREAD

**Issue by kujiy** [sameersbn/docker-gitlab#1229]
Hi, I'm making a migration plan from this image to EE. I read #1150 #701 #849 and known there is no EE image. Does anybody know the procedure? I'm wondering how I can migrate the over 20GB data in my container to EE. Must I build EE in my another container by myself and maintenance & upgrade it regularly, mustn't I? What image is good for the base image for EE?

**Comment by kujiy** [comment]
I found the official image

https://docs.gitlab.com/omnibus/docker/README.html

But I'm still not sure how to migrate from self-hosting gitlab CE.

https://docs.gitlab.com/ee/workflow/importing/README.html

**Comment by frostieDE** [comment]
Maybe [this](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/migrate_ci_to_ce) may help.

**Comment by solidnerd** [comment]
I will close this issue. I think this problem is not in our scope.
