### ISSUE TITLE
Slow SSH connection

### ISSUE THREAD

**Issue by johnjelinek** [sameersbn/docker-gitlab#123]
I deployed the container to a new server in a different data center and strangely, SSH fetching/pulling/pushing was taking ~20 seconds each. I tracked down the issue to this: http://www.thegeekstuff.com/2010/07/openssh-slow-at-ssh2_msg_service_accept-received/.

The fix is to make sure `UseDNS no` is in the `/etc/ssh/sshd_config`. I tried to mount a modified version of `/app/init` but that gets permission denied. Do you think you could maybe `echo "UseDNS no" >> /etch/ssh/sshd_config` in the init script and I can pull a new version? Can you think of any reason why we should not set `UseDNS no`?

**Comment by tamasgal** [comment]
Holy cr*p, this was the solution for the ~20s long SSH auth on our GitLab server. Many thanks!
