### ISSUE TITLE
gitlab-rails can't find

### ISSUE THREAD

**Issue by virusystem** [sameersbn/docker-gitlab#1235]
Good day. Where i can found gitlab-rails, or how make 
 gitlab-rails c
 Rails.logger.level = 0
 LdapSyncWorker.new.perform
Thanks.

**Comment by solidnerd** [comment]
Hey,

this image uses an source installation and not an omnibus version. So you have only the `gitlab-rails` when you install GitLab with omnibus. If you want to do  that use the official image.
