### ISSUE TITLE
Gitlab + Registry: foo.bar/group/project/image

### ISSUE THREAD

**Issue by CrystalMethod** [sameersbn/docker-gitlab#1252]
After numerous adventures my Gitlab + Registry setup works on Synology with external SSL termination (Synology Reverse Proxy). One thing which amazes me is the note on the "Registry" tab:

```
...
Then you are free to create and upload a container image with build and push commands:

docker build -t foo.bar/group/project/image .
docker push foo.bar/group/project/image
```

But I can use ``foo.bar/group/project`` without any problems. Does anybody know where the ``image`` suffix come from or what it means?

**Comment by avluis** [comment]
I have one repository for which the directory tree uses the full path (all the way to the image directory) while others are created directly in the project directory.

The only difference is that the repository with the image directory was an import from GitHub (for which I then followed the usual docker instructions to pull/push the latest image).
I won't be able to point you to the definitive answer, but this could simply be a side-effect of v2 registry.

**Comment by CrystalMethod** [comment]
Ok, https://gitlab.com/help/user/project/container_registry clearifies some details, in particular

```GitLab supports up to three levels of image repository names.```

And there is an upcoming change: https://gitlab.com/gitlab-org/gitlab-ce/issues/30651
