### ISSUE TITLE
How to garbage collect container registry

### ISSUE THREAD

**Issue by Daxten** [sameersbn/docker-gitlab#1257]
I have problems running garbage-collect in the container registry, anyone has a snippet which works on the default docker-compose.yaml with registry?

**Comment by jostyee** [comment]
`docker exec -it gitlab_registry_1 registry garbage-collect /etc/docker/registry/config.yml`

**Comment by Daxten** [comment]
perfect thanks!

**Comment by harridu** [comment]
I am not sure if this is correct. Apparently there is no semaphore protecting the repository, so it should be "in read-only mode or not running at all", according to the documentation. Thats the tricky (and poorly documented, boooooooh!) part.

**Comment by ragaar** [comment]
The suggested way is to edit `gitlab.rb`.<sup>[[1]](https://docs.gitlab.com/omnibus/maintenance/#performing-garbage-collection-without-downtime)</sup>

## REF:

1. https://docs.gitlab.com/omnibus/maintenance/#performing-garbage-collection-without-downtime

**Comment by dimm0** [comment]
Yeah, would be nice to add some docs on how to do it here

**Comment by josefglatz** [comment]
```
With registry:2.7 running the command throws

docker-compose exec registry garbage-collect /etc/docker/registry/config.yml
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"garbage-collect\": executable file not found in $PATH": unknown
```

**Comment by josefglatz** [comment]
Is it A correct way to run the garbage-collection via crontab like so?

```
0 5 * * * docker-compose -f /srv/docker-compose/projects/gitlab/docker-compose.yml exec registry registry garbage-collect /etc/docker/registry/config.yml
```
