### ISSUE TITLE
Restore automated backup via docker run

### ISSUE THREAD

**Issue by willycws** [sameersbn/docker-gitlab#1286]
Hi all,

I managed to perform an automated backup and deleted all my gitlab-redis, gitlab-postgres and gitlab containers to test if the restoration work. So i created new gitlab-redis and gitlab-postgres containers. As for the creation of gitlab container, i use the following command. But it didn't run successful and the gitlab containers exists . 

docker run --name gitlab -d --link gitlab-postgresql:postgresql \
--link gitlab-redis:redisio \
--publish 10022:22 \
--publish 10080:80 \
--env 'GITLAB_PORT=10080' \
--env 'GITLAB_SSH_PORT=10022' \
--env 'GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string' \
--env 'GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alpha-numeric-string' \
--env 'GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alpha-numeric-string' \
-e TZ=Asia/Malaysia \
-m 4G --memory-swap 4G \
--env 'GITLAB_BACKUP_TIME=14:35' \
--env 'GITLAB_BACKUP_EXPIRY=604800' \
--env 'GITLAB_BACKUP_SCHEDULE=daily' \
-v /gitlab_backup:/home/git/data/backups sameersbn/gitlab:latest app:rake gitlab:backup:restore \
BACKUP=1499841943_2017_07_12_9.3.5

My backup TAR name is **1499841943_2017_07_12_9.3.5_gitlab_backup.tar**

The **logs (docker logs gitlab)** from the restoring process as follows:
Initializing logdir...
Initializing datadir...
Generating OpenSSH host keys... RSA1 RSA DSA ECDSA ED25519
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database
Configuring gitlab::redis
Configuring gitlab::secrets...
Configuring gitlab::sidekiq...
Configuring gitlab::gitaly...
Configuring gitlab::gitlab-workhorse...
Configuring gitlab::unicorn...
Configuring gitlab::timezone...
Configuring gitlab::rack_attack...
Configuring gitlab::ci...
Configuring gitlab::artifacts...
Configuring gitlab::lfs...
Configuring gitlab::mattermost...
Configuring gitlab::project_features...
Configuring gitlab::smtp_settings...
Configuring gitlab::oauth...
Configuring gitlab::ldap...
Configuring gitlab::cron_jobs...
Configuring gitlab::backups...
Configuring gitlab::backups::schedule...
Configuring gitlab::registry...
Configuring gitlab::pages...
Configuring gitlab-shell...
Configuring nginx...
Configuring nginx::gitlab...
Running raketask gitlab:backup:restore...
Missing Rails.application.secrets.jws_private_key for production environment. The secret will be generated and stored in config/secrets.yml.
rake aborted!
NoMethodError: undefined method `chomp' for nil:NilClass
/home/git/gitlab/lib/tasks/gitlab/task_helpers.rb:48:in `prompt'
/home/git/gitlab/lib/tasks/gitlab/task_helpers.rb:13:in `ask_to_continue'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:44:in `block (3 levels) in <top (required)>'
Tasks: TOP => gitlab:backup:restore
(See full trace by running task with --trace)
Unpacking backup ... done
Before restoring the database we recommend removing all existing tables to avoid future upgrade problems. Be aware that if you have custom tables in the GitLab database these tables and all data will be removed.
Do you want to continue (yes/no)?

Any help would be appreciated.

**Comment by webdeb** [comment]
How did you solved it?

**Comment by ksioposbuilder** [comment]
Same issue as https://github.com/sameersbn/docker-gitlab/issues/487
and still looking for a fix :(

**Comment by laoshancun** [comment]
same issue.
but may be this command `docker exec -it gitlab /sbin/entrypoint.sh app:rake gitlab:backup:restore BACKUP=1516259681_2018_01_18_10.3.3` will work.
