### ISSUE TITLE
GitLab Critical Security Update Pre-Announcement

### ISSUE THREAD

**Issue by pieterlange** [sameersbn/docker-gitlab#1289]
Updates next wednesday

https://about.gitlab.com/2017/07/14/gitlab-critical-release-preannouncement/

**Comment by phenomax** [comment]
I'll prepare a PR asap.
Hope that this will be checked and merged fast.

**Comment by phenomax** [comment]
https://about.gitlab.com/2017/08/04/gitlab-critical-release-preannouncement/

Another one coming up this wednesday.
