### ISSUE TITLE
Duplicated column running db migration

### ISSUE THREAD

**Issue by johnroyer** [sameersbn/docker-gitlab#1290]
I get an error message while upgrading Gitlab from `9.2.7` to `9.3.0`:

```
Mapping UID and GID for git:git to 5566:5566
Initializing logdir...
Initializing datadir...
Installing configuration templates...
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <main>'
Mysql2::Error: Duplicate column name 'job_events'
..........
```

I search from mysqldump file before upgrade, but still can not find any column named `job_events` in db schema in `9.2.7`. Any ideas ?

Thanks

**Comment by amannocci** [comment]
Seems to refer to this [issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/34358)

**Comment by johnroyer** [comment]
Thanks, @amannocci . Comfirm as duplicate.

Close issue. I will open another issue if I can not solve this problem by following #1278 .
