### ISSUE TITLE
Tag for 9.3.7 is missing on docker hub?

### ISSUE THREAD

**Issue by lyda** [sameersbn/docker-gitlab#1295]
Currently this is on [docker hub](https://hub.docker.com/r/sameersbn/gitlab/tags/) - the 9.3.7 tag is missing. Did the tagging step fail?

Tag Name | Compressed Size | Last Updated
---------- | --------------- | ------------
latest | 548 MB | 36 minutes ago
9.3.6 | 548 MB | 19 hours ago
9.3.5 | 547 MB | 14 days ago
9.3.4 | 547 MB | 16 days ago
9.3.3 | 547 MB | 17 days ago

**Comment by solidnerd** [comment]
Hey @lyda,
it's not missing. It will be builded by the hub ci system. https://hub.docker.com/r/sameersbn/gitlab/builds/ . It takes sometime ;) .
