### ISSUE TITLE
API Deprecation

### ISSUE THREAD

**Issue by QuickJack** [sameersbn/docker-gitlab#1299]
The Release notes for GitLab 8.17 (https://about.gitlab.com/2017/02/22/gitlab-8-17-released/) include a v3 API deprecation in favor of the new v4.

Does this mean that the v3 API will be removed completely? What happens to the v1 API? Note, that the runner (https://github.com/sameersbn/docker-gitlab-ci-multi-runner) is still using v1 API calls (see production log).

**Comment by QuickJack** [comment]
The Release notes for the latest version of GitLab include a new depcreation notice for API v1. It clearly says that runners before <9.0 will stop working in GitLab 9.6+. There is an onging MR for the runner at https://github.com/sameersbn/docker-gitlab-ci-multi-runner/pull/33

**Comment by solidnerd** [comment]
Hey @QuickJack,
first of all you are correct. I think in releases higher than `9.6+` you can only use the api v4. I would reccommend to get to the new gitlab version as far as possible. So the migration are not so hard and can't brake so much instead when you are trying to upgrade from an very old version. It's only delaying the problem in the future.

**Comment by QuickJack** [comment]
Here is the issue on GitLab https://gitlab.com/gitlab-org/gitlab-ce/issues/35459
