### ISSUE TITLE
Error in javascript in version 9.4.0

### ISSUE THREAD

**Issue by xNevo** [sameersbn/docker-gitlab#1301]
After upgrading to v9.4.0, I noticed that the javascript has some errors and some thing

![image](https://user-images.githubusercontent.com/16116826/28549233-ea38137e-70d8-11e7-8dc2-a29592057a48.png)

Dynamic pages like the repository dashboard keep loading

![image](https://user-images.githubusercontent.com/16116826/28549310-74315f2c-70d9-11e7-8e78-a5e990c6e8ff.png)

 Also: GitLab doesn't show diff colors in commits anymore

![image](https://user-images.githubusercontent.com/16116826/28549268-32ac08d6-70d9-11e7-84ae-e59541686c6f.png)

Am I the only one with this issue or is this a general problem with the current version?

Note: I'm not using the new navigation design.

**Comment by avluis** [comment]
@xNevo Note that you aren't the only one seeing no diff coloring (I am as well): https://gitlab.com/gitlab-org/gitlab-ce/issues/35510 (not the OP, but good to have it linked).

I am seeing some javascript errors -- but I don't have any issues with dynamic pages.
Try a Ctrl+F5 on those pages just in case.

**Comment by masakij** [comment]
same errors in MR page.
I no longer access to Commits tab & Changes tab.

**Comment by masakij** [comment]
I found a workaround for the issue.

## solution

1. run a gitlab container
1. open a shell in the running container (e.g. `docker exec -it gitlab bash`)
    1. compile locale po files to js (`bundle exec rake gettext:compile RAILS_ENV=production`)
    1. recompile assets (`bundle exec rake gitlab:assets:compile RAILS_ENV=production NODE_ENV=production`)

## cause

* lack of locale data in js

**Comment by solidnerd** [comment]
Hey at all,
I got the same error. Thanks for @masakij for the hint. I will try to add the gettext:compile. Would you like to make an PR for that or should I do it ? It can be placed in the same place for compiling the assets. https://github.com/sameersbn/docker-gitlab/blob/master/assets/build/install.sh#L167

**Comment by solidnerd** [comment]
It has been fixed by #1302  and will be available in `9.4.0-1`. If the issue still persits please reopen this issue.

**Comment by avluis** [comment]
Would like to ref the following issue, for those who like to have all info in one location:
https://gitlab.com/gitlab-org/gitlab-ce/issues/35193
