### ISSUE TITLE
Upgrade + CloudFlare + jwilder/nginx-proxy

### ISSUE THREAD

**Issue by Laul0** [sameersbn/docker-gitlab#1312]
Hi,

Since I upgrade GitLab with the latest versions (9.3.5, 9.3.9, 9.4.1) I occur a big problem with NGINX and Gitlab server.
The error is : **Too many redirections**

![28306039-22f3c48c-6b9e-11e7-8721-9a62a39a86d0](https://user-images.githubusercontent.com/15279205/28745231-402216d8-7474-11e7-8740-4d46c6c7079c.png)

## Environment
* I use GitLab Docker behind jwilder/nginx-proxy and a CloudFlare HTTPS.
* I always used the same command line to launch the GitLab container and it always works before the GitLab 9.3.5.

### Connexion Schema

User ------> CloudFlare + HTTPS redirection -------> jwilder/nginx-proxy (Reverse Proxy) -------> Gitlab Server

### Command line
```bash
docker run --name gitlab --restart always -d -e VIRTUAL_HOST=[MyFQDN] -p 443 -p 22 \
--link sdb:mysql --link gitlab-redis:redisio --env 'GITLAB_HOST=[MyFQDN]' \
--env 'DB_ADAPTER=mysql2' --env 'DB_NAME=[DBNAME]' --env 'DB_USER=[DBUSER]' --env 'DB_PASS=[DBPASSWORD]' \
--env 'GITLAB_SECRETS_DB_KEY_BASE=[SECRETKEY]' \
--env 'GITLAB_SECRETS_SECRET_KEY_BASE=[SECRETKEY]' --env 'GITLAB_SECRETS_OTP_KEY_BASE=[SECRETKEY]' \
--env 'SMTP_USER=[SMTPADDRESS]' --env 'SMTP_PASS=[SMTPPASSWORD]' --env 'SMTP_DOMAIN=[SMTPDOMAIN]' --env 'SMTP_HOST=[SMTPHOST]' --env 'GITLAB_EMAIL_REPLY_TO=[REPLYEMAIL]' --env 'GITLAB_EMAIL_DISPLAY_NAME=GitLab' \
--env 'GITLAB_HTTPS=true' --env 'SSL_SELF_SIGNED=true' \
--env 'OAUTH_GITHUB_API_KEY=[GITHUBOAUTHAPIKEY]' --env 'OAUTH_GITHUB_APP_SECRET=[GITHUBSECRETKEY]' \
--env 'GOOGLE_ANALYTICS_ID=[GOOGLEANALYTICS]' \
--volume /path/to/data:/home/git/data \
sameersbn/gitlab:latest
```

If I 
* Remove **--env 'GITLAB_HTTPS=true'**
* Remove **--env 'SSL_SELF_SIGNED=true'** 
* Change -p 443 to **-p 80**

**GitLab works but :**

* Git connexion string has to be in HTTP and not HTTPS anymore
* The Pipeline console doesn't show the output
* OAuth of GitHub doesn't works anymore too
* etc.

No error log with Gitlab and I use this environment schema for others docker servers and I don't occur this error.

What has changed since the version 3.9.5 ? A new Parameter ?

Thx you by advance for your help.

**Comment by avluis** [comment]
Maybe you are seeing this issue: #1248
I have a similar setup as yours [`Cloudflare` -> `NGINX` -> `Gitlab`]

Hopefully some excerpts from my configuration can help resolve your issue.
Run command:
```yml
docker run --name="gitlab" --net="none" -e TZ="America/Chicago" -e HOST_OS="unRAID" \
-v "/mnt/user/appdata-store/gitlab/shared/lfs-objects/":"/home/git/data/shared/lfs-objects":rw \
-v "/mnt/user/appdata-store/gitlab/backups/":"/home/git/data/backups":rw \
-v "/mnt/user/appdata-store/gitlab/shared/registry/":"/home/git/data/shared/registry":rw \
-v "/mnt/user/appdata/gitlab/certs/":"/certs":rw \
-v "/mnt/user/appdata/gitlab/":"/home/git/data":rw \
--network <DOCKER_NET> --ip <GITLAB_IP> --hostname='gitlab' \
--env-file /mnt/user/appdata/gitlab/DockerEnv sameersbn/gitlab
```

Relevant entries from `/mnt/user/appdata/gitlab/DockerEnv`:
```
GITLAB_HOST=gitlab.<domain>.<tld>
GITLAB_PORT=443
GITLAB_SSH_HOST=repo.<domain>.<tld>
GITLAB_SSH_PORT=22
GITLAB_TRUSTED_PROXIES=<NGINX_IP>
GITLAB_HTTPS=true
SSL_CERTIFICATE_PATH=/this_path_must_not_exist_for_https_to_work_properly
SSL_KEY_PATH=/this_path_must_not_exist_for_https_to_work_properly
SSL_DHPARAM_PATH=/this_path_must_not_exist_for_https_to_work_properly
NGINX_REAL_IP_RECURSIVE=on
NGINX_REAL_IP_TRUSTED_ADDRESSES=<NGINX_IP>
```

NGINX:
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name gitlab.<domain>.<tld>;

    ssl_certificate /path/to/cert/fullchain.pem;

    ssl_certificate_key /path/to/key/privkey.pem;

    add_header Strict-Transport-Security "max-age=15768000; includeSubdomains; preload" always;

    location / {
        proxy_set_header        Host                $http_host;
        proxy_set_header        X-Real-IP           $remote_addr;
        proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto   $scheme;
        proxy_intercept_errors  on;
        proxy_http_version      1.1;

        proxy_pass http://<GITLAB_IP>:80;

    }

}
```

**Comment by Laul0** [comment]
Hi @avluis, thx for your answer.
In fact, after had updated the docker command, I managed to make it work my Gitlab server in TLS mode. Thx, I can close my issue.
