### ISSUE TITLE
documentation about gitlab pages behind nginx reverse proxy

### ISSUE THREAD

**Issue by fevxie** [sameersbn/docker-gitlab#1319]
Hi, 
The documentation doesn't any configuration about gitlab pages behind nginx reverse proxy.  anyone can give some guid about this.

Thanks in advance.

**Comment by xNevo** [comment]
Depends on what webserver you're using. There are bunch of tutorials if you are using Nginx or Apache2 for example

- Nginx: https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-as-a-web-server-and-reverse-proxy-for-apache-on-one-ubuntu-16-04-server
- Apache2: https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension
- Caddy: https://caddyserver.com/docs/proxy#examples

**Comment by fevxie** [comment]
I know nginx config is out of scope of this documentation.  I fix the issue myself,  still thanks.

**Comment by kominoshja** [comment]
Can you post the steps you took?
