### ISSUE TITLE
Support for Database Load Balancing

### ISSUE THREAD

**Issue by avluis** [sameersbn/docker-gitlab#1339]
I make use of Sameer's PostgreSQL image alongside this GitLab image.

I've been looking into database replication\load balancing and GitLab itself [supports it](https://docs.gitlab.com/ee/administration/database_load_balancing.html) as well as Sameer's [PostgreSQL image](https://github.com/sameersbn/docker-postgresql#setting-up-a-replication-cluster).
Unfortunately, unless I modify [`database.yml`](https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/config/gitlabhq/database.yml) manually, I'm not seeing a way to make the changes I need on container startup.

Is this something that can be considered supporting or is there an additional software requirement (like HAProxy) needed for this to work properly?

Finally, is it currently possible to add load balancing (if you already have replication setup) without modifying GitLab (as a router, in essence)?

**Comment by phenomax** [comment]
Sadly Load Balancing is only available in the Enterprise Edition.

> Introduced in GitLab Enterprise Edition Premium 9.0.

**Comment by avluis** [comment]
Ugh! That puts a few nails on my plans -- thank you for replying!
