### ISSUE TITLE
unzip dependency missing?

### ISSUE THREAD

**Issue by nachokb** [sameersbn/docker-gitlab#1351]
I tried setting up pages on a project, and been getting "pages failed to extract" which, according to [1], might be because the `unzip` package is missing and it's supposedly fixed with `apt install unzip`.

![pages-deploy](https://user-images.githubusercontent.com/17967/30510929-950cb328-9aa4-11e7-97e8-26aedef472b2.png)

[1] https://gitlab.com/gitlab-org/gitlab-ee/issues/1719

**Comment by solidnerd** [comment]
Hey @nachokb, 

it would be nice to add an example of your `.gitlab-ci.yml` and the configured parameters for this image. So we can easy try to reproduce it and make a correct fix for that.

**Comment by nachokb** [comment]
@solidnerd just tried forking and adding it, and the error persists. I thought the gitlab host itself lacked the unzip binary, but that's definitely not the problem.

Found the problem in my .gitlab-ci.yml file (plus one of my runners was using an outdated version of gitlab-ci-multi-runner).

Please ignore this, sorry for the noise.
