### ISSUE TITLE
Add verify_certificates to config vars

### ISSUE THREAD

**Issue by LordFPL** [sameersbn/docker-gitlab#1366]
Hello,

As in gitaly problem, gitlab config template should be modified to cover https://about.gitlab.com/2017/09/22/gitlab-10-0-released/#ldap-config-%22verify_certificates%22-defaults-to-secure
```
        # Enables SSL certificate verification if encryption method is
        # "start_tls" or "simple_tls". Defaults to true.
        verify_certificates: true
```

**Comment by in8d3v** [comment]
I really need this before I can upgrade to 10

**Comment by BirgerK** [comment]
It is already added: https://github.com/sameersbn/docker-gitlab/pull/1367

But the related environemnt-variable is named `LDAP_VERIFY_SSL`

**Comment by solidnerd** [comment]
I will close this because it was merged- If the issue still exists please reopen the issue and ping me.
