### ISSUE TITLE
"Features", "Container Registry" sections missing from `README.md`

### ISSUE THREAD

**Issue by rysiekpl** [sameersbn/docker-gitlab#1373]
Seems like the "Features" and "Container Registry" sections are missing from `README.md`. The menu lists them as between "Shell access" and "References", but they are no-where to be found. At the bottom of `README.md` "References" section follows immediately after "Shell access".

**Comment by solidnerd** [comment]
@rysiekpl  I think not. If it's not true make a feel free to make a PR for this issue. I will close this issue temporarly if it's not true re-open it.
