### ISSUE TITLE
How to restore from backup in docker stack

### ISSUE THREAD

**Issue by ggilley** [sameersbn/docker-gitlab#1375]
I'm migrating from the omnibus version to the docker version. However, I'm running using docker stack. How can I restore from the omnibus backup into the docker version running under a stack?

**Comment by solidnerd** [comment]
@ggilley You can use the normal way how to restore backups. Have a look in the readme https://github.com/sameersbn/docker-gitlab#restoring-backups

**Comment by trumhemcut** [comment]
It doesn't work for my case since docker stack running in another network

**Comment by solidnerd** [comment]
Hey @trumhemcut,
could you describe your problem with some more facts ?
