### ISSUE TITLE
Deprecated values for LDAP-encryption

### ISSUE THREAD

**Issue by BirgerK** [sameersbn/docker-gitlab#1376]
The [LDAP-docu](https://docs.gitlab.com/ee/administration/auth/ldap.html) says that the values `tls` and `ssl` for the variable `encryption` are deprecated. The related environment-variable in this image is `LDAP_METHOD`.

The new possible values for this config are `start_tls` or `simple_tls` or `plain`.

Maybe you want to change also the environment-variable from `LDAP_METHOD` to `LDAP_ENCRYPTION`?

**Comment by solidnerd** [comment]
Hey @BirgerK,

did you see #1367 ? I think that should could solve your problems.

**Comment by BirgerK** [comment]
Yeah, I saw that already.

But that PR handles the new config-param `verify_certificates`. I'm talking about they changed the values (and name) for the `encryption` config-param. You know?

**Comment by BirgerK** [comment]
I did a [PR](https://github.com/sameersbn/docker-gitlab/pull/1383) for this.

**Comment by solidnerd** [comment]
@BirgerK  I will close the issue since #1383 is merged and available. If this issue still persists please reopen this one.
