### ISSUE TITLE
Runner not working anymore

### ISSUE THREAD

**Issue by QuickJack** [sameersbn/docker-gitlab#1377]
The suggested runner sameersbn/gitlab-ci-multi-runner is not working anymore. This is because GitLab 10+ does no longer support the v1 API. sameersbn/gitlab-ci-multi-runner seems to be totally outdated.

What runner do you suggest? Is there any future of sameersbn/gitlab-ci-multi-runner?

**Comment by patrickc91** [comment]
I recently needed to get a runner up and going and switched over to this one: https://github.com/digitalLumberjack/docker-gitlab-ci-multi-runner

I believe there's a PR in the sameersbn/gitlab-ci-mutli-runner repository to merge digitalLumberjack's changes. But it just never got done.

**Comment by QuickJack** [comment]
Yes, you are right. The PR is here sameersbn/docker-gitlab-ci-multi-runner#33. There's an ongoing discussion but no solution yet.

The repository at https://github.com/digitalLumberjack/docker-gitlab-ci-multi-runner has it's last commit at July 3, 2017. None of the these runners is up to date.

@sameersbn and @solidnerd: What runner do you suggest for GitLab 10+?

**Comment by siruslan** [comment]
I switched to https://github.com/vivienm/docker-gitlab-runner/commit/95227484bc35b3c2a7193cb5fade271691a964c3 and it works. Just pay attention to the mount volume path, it's a little bit different.

**Comment by davidwindell** [comment]
Ping @digitalLumberjack for your comments
