### ISSUE TITLE
LDAP_VERIFY_SSL parameter isn't working

### ISSUE THREAD

**Issue by damiendurant** [sameersbn/docker-gitlab#1379]
Hi,

LDAP_VERIFY_SSL parameter isn't working properly because this attribute should be a boolean and is set as a string in gitlab.yml template.

Here is the simple patch to fix it : 

```
--- a/assets/runtime/config/gitlabhq/gitlab.yml
+++ b/assets/runtime/config/gitlabhq/gitlab.yml
@@ -265,7 +265,7 @@ production: &base
         port: {{LDAP_PORT}}
         uid: '{{LDAP_UID}}'
         encryption: '{{LDAP_METHOD}}' # "tls" or "ssl" or "plain"
-        verify_certificates: '{{LDAP_VERIFY_SSL}}'
+        verify_certificates: {{LDAP_VERIFY_SSL}}
         bind_dn: '{{LDAP_BIND_DN}}'
         password: '{{LDAP_PASS}}'
```

**Comment by LordFPL** [comment]
My fault, sorry, i just make a patch : https://github.com/sameersbn/docker-gitlab/pull/1380

**Comment by solidnerd** [comment]
#1380 is merged i think we can gonna close this issue. @damiendurant If the problem still exists feel free to re-open this issue.
