### ISSUE TITLE
How do you access the gitlab-rails console?

### ISSUE THREAD

**Issue by Nepoxx** [sameersbn/docker-gitlab#1384]
I tried using `docker exec -it myContainer bash` and `gitlab-rails` was not on the path, what would be the best way to do it? (I want to test my SMTP settings)

**Comment by cat5** [comment]
After connecting to the container, try this:

bin/bundle exec rake gitlab:env:info RAILS_ENV=production

**Comment by Nepoxx** [comment]
Awesome, merci!

**Comment by bsylvain** [comment]
Once in the container, where is the rails gitlab folder ?

**Comment by Wicowyn** [comment]
`docker exec -it gitlab bin/rails console`

**Comment by hannesa2** [comment]
I was able that way:
search for your Docker CONTAINER_ID
`docker ps -all` 

eg
![image](https://user-images.githubusercontent.com/3314607/56364747-9ec06e00-61ef-11e9-894e-02f88c1fc3c1.png)

`docker exec -it d0bbe0e1e3db bash` <-- with your CONTAINER_ID
`$ gitlab-rails console production`
![image](https://user-images.githubusercontent.com/3314607/56364870-e34c0980-61ef-11e9-8b40-ed1f5ec1e97d.png)
`...`
`exit`

**Comment by mhellmeier** [comment]
None of the above solutions worked for me. As mentioned in [this GitLab issue](https://gitlab.com/gitlab-org/gitlab/-/issues/213745), the correct command should be `gitlab-rails console -e production`.

So go into your Docker container with
`docker exec -it CONTAINER_ID/NAME bin/bash`
and then execute
`gitlab-rails console -e production`
It could take some time until the command line appears.

**Comment by CSRedRat** [comment]
```
docker exec -it gitlab_gitlab_1 gitlab-rails console
```
and wait

**Comment by glebteterin** [comment]
For me it was
```
./bin/rails console -e production
```

**Comment by waynema02** [comment]
> ```
> docker exec -it gitlab_gitlab_1 gitlab-rails console
> ```
> 
> 
>      
>   
> 
> and wait

The key is `wait`.. For me, it takes over 40 seconds to start, during which time there is **no** output. I was worried something is wrong, and found this thread:)
