### ISSUE TITLE
502 Bad Gateway reverse proxy from version 10.0.4 to 10.1.0

### ISSUE THREAD

**Issue by sprucify** [sameersbn/docker-gitlab#1396]
For months I only had to update my `docker-compose.yml` file to the latest gitlab version and do a `docker-compose up -d`

But the upgrade from 10.0.4 to 10.1.0 results in a 502 Bad gateway

Does anyone know if something has changed in regards to reverse proxy or SSL?

**Comment by solidnerd** [comment]
@sprucify I don't have those problems. I think it's a timeout problem.

Which LB do you use for ssl termination ? 

So far I know nothing had change in this direction.

**Comment by sprucify** [comment]
Load balancing you mean?
I just have one instance and 10m ssl termination

**Comment by solidnerd** [comment]
@sprucify  Do you use a nginx or something else to do the ssl termination.

**Comment by sprucify** [comment]
Yes nginx with reverse proxy

**Comment by hugomd** [comment]
@sprucify I had the same issue, and in my case it was because I had run out of disk space..

Would you be able to post your logs?

**Comment by solidnerd** [comment]
@sprucify What I did when I used nginx was to increase the failtimeout of the upstream. Here is an example configuration

```nginx
upstream gitlab {
 server gitlab:8181 fail_timeout=60s;
}

map $http_upgrade $connection_upgrade_gitlab_ssl {
    default upgrade;
    ''      close;
}

server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name gitlab.example.com;

        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 24h;
        ssl_buffer_size 1400;
        ssl_session_tickets off;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

	ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
	ssl_ecdh_curve secp384r1;
        ssl_prefer_server_ciphers on;

        ssl_certificate /etc/letsencrypt/live/gitlab.example.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/gitlab.example.com/privkey.pem;
        ssl_dhparam /etc/nginx/ssl/dhparam.pem;

        ssl_stapling on;
        ssl_stapling_verify on;
        resolver 8.8.4.4 8.8.8.8 valid=300s;
        resolver_timeout 10s;

        add_header Strict-Transport-Security max-age=63072000;


        location /ci/api/v1/builds/register.json {
		access_log off;
	      proxy_set_header Host              $http_host;
        proxy_set_header Referer           $http_referer;
        proxy_set_header Referrer          $http_referer;
        proxy_set_header Cookie            $http_cookie;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port  $server_port;
        proxy_set_header X-NGINX-Proxy     true;
        proxy_set_header X-Forwarded-SSL   on;
        proxy_set_header    Upgrade             $http_upgrade;
        proxy_set_header    Connection          $connection_upgrade_gitlab_ssl;


       client_max_body_size 1000m;

        proxy_redirect                     off;
        proxy_http_version                 1.1;

                proxy_pass http://gitlab;

	}

	location / {
        proxy_set_header Host              $http_host;
        proxy_set_header Referer           $http_referer;
        proxy_set_header Referrer          $http_referer;
        proxy_set_header Cookie            $http_cookie;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port  $server_port;
        proxy_set_header X-NGINX-Proxy     true;
        proxy_set_header X-Forwarded-SSL   on;
        proxy_set_header    Upgrade             $http_upgrade;
        proxy_set_header    Connection          $connection_upgrade_gitlab_ssl;


       client_max_body_size 1000m;

        proxy_redirect                     off;
        proxy_http_version                 1.1;

  		proxy_pass http://gitlab;
  }

}
server {
        listen 80;
        listen [::]:80;
        server_name gitlab.example.com;
        return 301 https://$server_name$request_uri;  # enforce https
}
```

**Comment by sprucify** [comment]
I don't have an upstream yet.
This is my redacted nginx config that fails:
`server
{
        server_name gitlab.example.nl www.gitlab.example.nl;
        listen myIP:80;

        return 301 https://$host$request_uri;
}

server
{
        server_name gitlab.example.nl www.gitlab.example.nl;
        listen myIP:443 ssl;

        access_log /var/log/nginx/domains/example.nl.log;
        access_log /var/log/nginx/domains/example.nl.bytes bytes;
        error_log /var/log/nginx/domains/example.nl.error.log;


        ssl on;
        ssl_certificate /usr/local/directadmin/data/users/example/domains/example.nl.cert.combined;
        ssl_certificate_key /usr/local/directadmin/data/users/example/domains/example.nl.key;
        ssl_session_timeout 10m;
        #include /usr/local/directadmin/data/users/example/nginx_php.conf;

        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;

                #proxy_redirect off;

                proxy_set_header X-Forwarded-Ssl on;
                proxy_pass http://127.0.0.1:10080;
        }

        #include /etc/nginx/webapps.ssl.conf;
}
`

**Comment by solidnerd** [comment]
@sprucify Could you post the `production.log` from `/var/log/gitlab/gitlab/production.log`

**Comment by sprucify** [comment]
@solidnerd It is not able to spin up the gitlab container.
When I do a `docker-compose up` without `-d` option I see it loops.
The output is too long for here, but a couple of interesting lines:

`  gitlab_1      | Migrating database...
   gitlab_1      | Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.
   gitlab_1      | rake aborted!
   gitlab_1      | StandardError: An error has occurred, all later migrations canceled:
   gitlab_1      | PG::DuplicateColumn: ERROR:  column "merge_requests_ff_only_enabled" of relation "projects" already exists
   gitlab_1      | : ALTER TABLE "projects" ADD "merge_requests_ff_only_enabled" boolean
`

**Comment by solidnerd** [comment]
@sprucify Something on your machine went wrong during the last update. I would use a backup an upgrade after this backup version.

**Comment by sprucify** [comment]
10.1.3 works fine now.
There is something going wrong in there migration files in version 10.1.0-10.1.2
Existing column names.
