### ISSUE TITLE
Pages Artifact Server variable is incorrectly documented

### ISSUE THREAD

**Issue by jasl8r** [sameersbn/docker-gitlab#1397]
https://github.com/sameersbn/docker-gitlab/blob/2ff0acc95ef4589a0b73c4ef40435035f752475f/README.md#L882

Should be `GITLAB_PAGES_ARTIFACTS_SERVER`... right?

**Comment by solidnerd** [comment]
@jasl8r you are right. https://github.com/sameersbn/docker-gitlab/commit/f765ef06bef510e47c4bd6d15831de08de4e7759#diff-06791a442f4393b736ecf1395b7090cfR986 . Feel free to make a PR for that.
