### ISSUE TITLE
git action over https -> The requested URL returned error: 500

### ISSUE THREAD

**Issue by reynold-lariza** [sameersbn/docker-gitlab#1399]
After upgrading to 10.1.1 (with 10.1.0 changes)
I get the following error when cloning over https (via ELB)

```
Cloning into 'sample'...
remote: Internal server error
fatal: unable to access 'https://mygitlab.domain.com/sample/': The requested URL returned error: 500
```

SSH git action works, but not on HTTPS. I also passed the following params
```
--env 'GITALY_ENABLED=false' \
```

but same issue.

**Comment by solidnerd** [comment]
For me is working everything HTTPS Clone or SSH Clone. I think it's a problem on your site with the ELB .

**Comment by reynold-lariza** [comment]
Ahh, that config.toml -- I forgot to add it. Its working now after I rebuilt it.
