### ISSUE TITLE
No 9.4.6 or 9.4.7

### ISSUE THREAD

**Issue by otheus** [sameersbn/docker-gitlab#1404]
Hi, 

We cannot find images for the security patches to the 9.4 series. Will someone please create an image for 9.4.7 so that we can continue using docker with the 9.4 release?

**Comment by hex-m** [comment]
If you look at the changes for other minor versions [here](https://github.com/sameersbn/docker-gitlab/commit/7b8167fac5b73be497026773dbd2c75ba909ca63) and [here](https://github.com/sameersbn/docker-gitlab/commit/2d4be2b6b8dab04a243e55e4ca25c98fecc2092c) it seems like this should be trivial. I didn't test it but I wish you the best of luck.

**Comment by solidnerd** [comment]
Sorry we are don't support older versions because it's not possible with this gitflow. For this an own release branch needed. But you should be able to do it by your own. Have a look a README for this case.

**Comment by otheus** [comment]
@solidnerd I would like to point out that GitLab 9.4 was released July 2017. That's 4 months ago. While I appreciate the work done here, but it's not feasible for real end-users to keep up with a lifecycle that lasts only 4 months. If I can't expect 9.4 series to be updated, that means I have to test & deploy a new major release every few months; who has that time? 

@hex-m the main problem is taking the time to understand the build system, the 2nd problem is testing, the 3rd problem is the registry.
