### ISSUE TITLE
how to set X-Frame-Options

### ISSUE THREAD

**Issue by egbertzeng** [sameersbn/docker-gitlab#1423]
I want to take my gitlab inside a iframe,but the X-Frame-Options is DENY,so how can I change the x-frame-options?

**Comment by balajidl** [comment]
Can this link help you https://gitlab.com/gitlab-org/gitlab-ce/issues/2689?

**Comment by yacaeh** [comment]
edit this file 
/var/opt/gitlab/nginx/conf/gitlab-http.conf
add the following

```
  proxy_hide_header Content-Security-Policy;
  proxy_hide_header X-Frame-Options;
```
