### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by edbergavera** [sameersbn/docker-gitlab#1425]
Hi,

Does the CE version supports activating maintenance mode such as when we perform an upgrade and that avoiding someone to commit during this period. As per this [article](https://www.digitalocean.com/community/questions/how-to-display-maintenance-mode-notification-on-gitlab) suggests:

> The closest thing that GitLab offers to this is displaying a static page during deploys. This can be initialed manually with:
>
`gitlab-ctl deploy-page up`
> 
> and taken down again with:
> 
`gitlab-ctl deploy-page down`

However, it looks like this command is not available in this docker version of Gitlab.

**Comment by faultylee** [comment]
Correct me if I'm wrong, I don't think that will work, when upgrading through docker, the container is brought down, recreated and up again. No web application to serve the maintenance page during the transition time, and no one can push anyway. Only thing is it might break those who is in the middle of a push

**Comment by edbergavera** [comment]
Thanks @faultylee
