### ISSUE TITLE
Be carefull upgrading to 10.3.0 using Mysql.

### ISSUE THREAD

**Issue by pmoralesp** [sameersbn/docker-gitlab#1448]
Hi there.  This morning I broke my gitlab instance upgrading to 10.3.0. Looking for a areason, I found a upstream bug related to migrations with Mysql or MariaDB.

https://gitlab.com/gitlab-org/gitlab-ce/issues/41498

Please stay tunned if you dont want to break your gitlab :)

**Comment by jannwe** [comment]
Hi, exactly the same problem for me... They are just fixing the failed migration under:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/16141#note_52701562

It would be great @solidnerd and @sameersbn if you could update the repository with the new release (10.3.2) as soon as possible. 

Thanks!

**Comment by solidnerd** [comment]
A PR for 10.3.2 is available in #1454

**Comment by pmoralesp** [comment]
Now works flawless. Thank you @solidnerd
