### ISSUE TITLE
Issue cleanup / Automation

### ISSUE THREAD

**Issue by drubin** [sameersbn/docker-gitlab#1450]
This project is very active/well maintained. Thank you for that both @sameersbn and @solidnerd  :) 

The issue list, on the other hand, needs a bit of a spring clean, it currently makes it look like there are a large number of open issues even though they have been either fixed in a new version or simple were support requests that were forgotten about. 

I started going through them to try and maybe clean up a few issues/fix some documentation or figure out if issues are still valid, but most of them are pre-2016....

Maybe you could set up a cleanup bot to auto close issues without activity after 30 days?

I have seen people use https://github.com/probot/stale 

Or maybe just go through them and tag once that should be closed? Thoughts?

**Comment by drubin** [comment]
@sameersbn Any feedback on this?

**Comment by balajidl** [comment]
Good point @drubin 
Its worth auto closing issue that are older than 30 days. Gitlab-ce does it.

**Comment by drubin** [comment]
Closing due to lack of interest.
