### ISSUE TITLE
Can not upload avatar/logo

### ISSUE THREAD

**Issue by Laul0** [sameersbn/docker-gitlab#1478]
## Summary
Recently, I have seen that I am no longer able to upload a logo for groups and project

## GitLab information
Version:	10.3.5
Revision:	7c30d48
Directory:	/home/git/gitlab
DB Adapter:	postgresql
URL:		https://mydomain
HTTP Clone URL:	https://mydomain/some-group/some-project.git
SSH Clone URL:	git@mydomain:some-group/some-project.git
Using LDAP:	no
Using Omniauth:	yes
Omniauth Providers: github

## Steps to reproduce
1. Create or open project/group settings
2. Expand **General project settings**
3. Upload an avatar/logo
4. Save settings
5. Reload the page

## Expected behavior

New avatar is uploaded and visible

## Actual behavior

Old avatar or no avatar is present instead

**Comment by balajidl** [comment]
Its working fine for me @Laul0 
I am using 10.3.5

**Comment by chrislovsund** [comment]
It wasn't working for me on 10.3.3 (at least that's when I noticed it) but is now working again on 10.3.5.

**Comment by Laul0** [comment]
Hi, maybe I found an other issue in relation with this one :

When I want to upload an image in to an issue, I obtain the error below : 

<img width="564" alt="screen shot 2018-01-23 at 16 50 04" src="https://user-images.githubusercontent.com/15279205/35285542-f5313688-005d-11e8-9e46-f964f0fdb1ce.png">

Someone can share me the permission and folders that I have to check ? Maybe they're a rake command tool for reset folders permissions ?

**Comment by QuickJack** [comment]
I am on 10.3.5 and uploading a group avatar is working fine.

**Comment by dansch94** [comment]
I am on Gitlab 10.3.5 and uploading a group or repository avatar is still not working but i can see the avatars from older generated repositorys and groups.

Error 500

**Comment by Laul0** [comment]
Yes, I can see the older avatars that already uploaded previously too.
But currently, I can’t update them or when I create a new repo or group I can’t define an avatar.
And I discovered yesterday that I can’t upload image in to an issue too !
I think that some permissions are not correctly configured on a specific folder, isn’t it ?

**Comment by dansch94** [comment]
At first all my repository were also empty then i fixed the premission and after that all was working fine, only uploading avatar is not working.

My steps for fixing the repository premissions: https://blackit.de/2017/12/10/gitlab-leeres-repository-nach-serverumzug/

**Comment by Laul0** [comment]
Hi guys, I upgraded today my version 10.3.5 to 10.3.6 and everything is ok now.
All of my issues are fixed.
Thank you for your investigations 😃

**Comment by dansch94** [comment]
I get still error 500

**Comment by Laul0** [comment]
Hi @dansch94, did you check the upload folder chmod and gown ?

**Comment by gazben** [comment]
@dansch94 The link is broken. Can you help us out?
I've git similar problems
