### ISSUE TITLE
Latest redis throws fatal error

### ISSUE THREAD

**Issue by cwildfoerster** [sameersbn/docker-gitlab#1485]
Using the latest and only available redis image now throws a fatal error and keeps restarting, gitlab won't start without redis.
`Fatal error, can't open config file '/etc/redis/redis.conf'`
Using the default docker-compose redis block, no funny volume mounts or anything special.

**Comment by balajidl** [comment]
I am using redis 2.8.4
What version of redis was it ? 
Can you post more error messages ?

I see https://hub.docker.com/r/sameersbn/redis/tags/ was updated recently (2 days ago). Is this something do to with that @sameersbn ?

**Comment by cwildfoerster** [comment]
I already opened an issue in his repository and already could boil it down to the usermapping he provides in his image...
