### ISSUE TITLE
Use Go 1.9 instead of 1.8 due to performance issue

### ISSUE THREAD

**Issue by david50407** [sameersbn/docker-gitlab#1489]
According to the GitLab official blog post, [How a fix in Go 1.9 sped up our Gitaly service by 30x](https://about.gitlab.com/2018/01/23/how-a-fix-in-go-19-sped-up-our-gitaly-service-by-30x/), Gitaly (GitLab Git RPC service) with Go 1.8 uses `fork` for `ForkExec` caused child process starting with a copy of the parent processes' memory, in other words, `ForkExec` takes longer when the process has larger virtual memory footprint.

In Go 1.9, `ForkExec` switch from `fork` to [`clone(2)`](http://man7.org/linux/man-pages/man2/clone.2.html) with `CLONE_VFORK` and `CLONE_VM` flags, or as known as [`posix_spawn(3)`](http://man7.org/linux/man-pages/man3/posix_spawn.3.html), which doesn't copy parent processes' memory space and has a roughly constant time.

ref: https://github.com/golang/go/issues/5838
ref: https://go-review.googlesource.com/c/go/+/37439

**Comment by solidnerd** [comment]
Hey,
it's already in there see #1479 . It will be available with the `10.4.0` release.

**Comment by solidnerd** [comment]
It can be closed now.
