### ISSUE TITLE
Projects avatars are gone after upgrade to 10.5.1

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [sameersbn/docker-gitlab#1526]
404 error for all custom uploaded avatars. Am I missed some configuration?

**Comment by shkrid** [comment]
https://github.com/sameersbn/docker-gitlab/commit/52b669a7a3e36a1d51699435139e83210e723073
move uploads -> shared/public/uploads
Or setup: GITLAB_UPLOADS_STORAGE_PATH=/home/git/gitlab/public

**Comment by Ilya-Kuchaev** [comment]
Yep. It works...
Hm... @solidnerd Maybe it has to be configured with the default value?

**Comment by shkrid** [comment]
> move uploads -> shared/public/uploads

```2018/02/25 22:03:52 error: POST "/groupname/newproject": handleFileUploads: extract files from multipart: mkdir for tempfile: mkdir /home/git/gitlab/public/uploads: file exists```

"uploads" directory should exist for tmpfiles creations. Strange behavior

**Comment by dansch94** [comment]
will this fix in the next update?

**Comment by f3l1x** [comment]
Confirmed, It requires to keep `uploads` folder.

**Comment by dansch94** [comment]
Just new uploading the avatars is also working

**Comment by Edke** [comment]
it worked also on for me, thank you @shkrid

**Comment by vitalyzhakov** [comment]
> setup: GITLAB_UPLOADS_STORAGE_PATH=/home/git/gitlab/public
Works for me. Thank you @shkrid .

**Comment by jostyee** [comment]
then `GITLAB_UPLOADS_STORAGE_PATH=/home/git/gitlab/public` should be the default value.

**Comment by maikelvl** [comment]
Fixing file permissions fixed it for us:

```
sudo chown -R git:git /home/git/data/shared
```

**Comment by shkrid** [comment]
For those who moved the uploads dir - check your backups.

**Comment by jstdoit** [comment]
it works by setting the environment.

**Comment by leslau** [comment]
@maikelvl works well, but you need to delete /home/git/gitlab/public/uploads link or you will not be able to upload any avatar.

**Comment by ociotec** [comment]
I added to my docker run script with `--env GITLAB_UPLOADS_STORAGE_PATH=/home/git/gitlab/public` and it worked. Thanks @shkrid.

But I agree with @jostyee, these kind of changes could use default values to allow previous installations to work properly without issues.

**Comment by f3l1x** [comment]
If I've moved uploads to `shared/public/uploads`. Will it work on latest version? I've looked it's changed again. :-) Thanks for help.

**Comment by leslau** [comment]
@f3l1x no, you need to move it back to `/home/git/data/uploads`

**Comment by f3l1x** [comment]
@leslau Thanks. I've thought so.
