### ISSUE TITLE
Precompile gitlab assets during container preparation.

### ISSUE THREAD

**Issue by dkapanidis** [sameersbn/docker-gitlab#153]
During first startup phase, Gitlab is compiling assets. This can be prepared during container preparation.

Is there a specific reason not to include it? If you want I can prepare it.

**Comment by cmckni3** [comment]
> I'd vote for precompiling assets without relative url. In case relative URL
> is activated start script could rebuild assets automatically during startup.

I agree with this. One solution would be to turn off precompilation and the app would compile assets on the first request but this requires an application setting change.

To get around a connecting to the database, a  configuration setting, `config.assets.initialize_on_precompile=false `, would need to be changed. An environment setting, `RAILS_ASSETS_PRECOMPILE ` is also required when using devise.

It seems like the asset pipeline is really the problem but again application changes would have to be made. I would have to look around sprockets to see what is going on but I believe the issue involves image assets and cache digests. This can be fixed but would have to happen in sprockets/Rails.

**Comment by sameersbn** [comment]
The assets can now be compiled at build time. The referenced commit does this. You should now have much faster container startup time.
