### ISSUE TITLE
Failed to connect to 127.0.0.1 port 9000: Connection refused

### ISSUE THREAD

**Issue by gastongouron** [sameersbn/docker-gitlab#1538]
Hello, 

And sorry if this issue is not in the correct location, I just herited of this project and it seems to me it's the correct place to post because it's related to docker and gitlab in the context of the CI agent.

I’m currently using gitlab-ci with a custom docker setup and trying to connect to an hapi server  http://127.0.0.1:9000 in order to run a test suite while deploying but my tests cannot reach http://127.0.0.1:9000 in the context of the tests (they can locally) just like if Docker was refusing to run something on 127.0.0.1:9000. 

Here is my process and understanding of the problem:

**Process:**
I have written a test suite for a client, and mocked our backend with an Hapi test server. The Hapi server is ran thanks to a grunt task using grunt-forever. The process works like a charm locally, The server starts, I run the test suite and I can even navigate to the client on a web browser and use it thanks to the fake answers provided by my test server. 

**Problem:**
Wrapping up, I updated my gitlab-ci file with 3 operations such as:
1. run server: `grunt forever:test_server:start` (which calls `forever start test_server.js`)
2. pass tests: `casperjs test tests`
3. stop server: `grunt forever:test_server:start` (which calls `forever stop test_server.js`)

When I deploy theses changes, the server seems to start but my tests fails to connect my server (supposed to be available on the `http://localhost:9000` of this machine). 

My first idea was that the server was initialised correctly and, because of some Docker wizardry I might not be aware of, but available on a different url. Then, by digging up and running the docker runner locally to repeat the procedure, I ended up realising the test server is not listening on any port:

1. I find the container ID with `docker ps`
2. I execute the container with `docker exec -ti <CONTAINER_ID> bash`
3. Once inside, I navigate to the current build and run the server manually (with the exact same command): `grunt forever:test_server:start`
4. I list the current processes with `ps auxww`
5. I see an occurence of my server running such as: 
`root       828  0.6  1.6 884476 33228 ?        Ssl  16:13   0:00 /usr/bin/nodejs /builds/FOLDER/FOLDER/node_modules/grunt-forever/node_modules/forever/bin/monitor ./tests/server/test_server.js`
6. It seems like the process is not actively running on a port but on a kind of node, because when I run `netstat -anp` I get the following output:
`unix  2      [ ACC ]     STREAM     LISTENING     229045   828/nodejs          /root/.forever/sock/worker.1520266414304lf1.sock`

At this point, my server should be accessible but I cannot reach it, for example, using `curl http://127.0.0.1:9000` will result in:

`url: (7) Failed to connect to 127.0.0.1 port 9000: Connection refused`

Sorry again if this issue should not be posted here (please let me know where it should be)

Any help is greatly appreciated

**Comment by guizmaii** [comment]
Hi,

What was the solution for this problem ?


Thanks.

**Comment by scottwio** [comment]
Just had this same issue and ended up here. For us it was sentry not being able to upload source maps so it's worth checking that isn't the case.

**Comment by mudassir-ahmed** [comment]
Did anyone have a solution??

**Comment by elmerborines14** [comment]
same issue
