### ISSUE TITLE
Upgrade to 10.5.6 required for security reasons

### ISSUE THREAD

**Issue by dachary** [sameersbn/docker-gitlab#1555]
In case you're not already aware, there is a need to upgrade to 10.5.6 because of the security problem described at https://about.gitlab.com/2018/03/20/critical-security-release-gitlab-10-dot-5-dot-6-released/

**Comment by freeseacher** [comment]
should be closed ?

**Comment by dachary** [comment]
Oh, yes https://github.com/sameersbn/docker-gitlab/releases/tag/10.5.6 is released :tada:
