### ISSUE TITLE
Webhook Integrations failing with 500 error

### ISSUE THREAD

**Issue by patrickc91** [sameersbn/docker-gitlab#1563]
I have some webhook integrations that trigger Jenkins CI builds but they're no longer working after upgrading from 10.4.4 to 10.5.6.

When a project is pushed to, it should send a request out to Jenkins to complete a build and deploy the project. I've tried using the testing feature on the Project Integrations page and receive the classic 500 error page.

The Production Logs show this:

![image](https://user-images.githubusercontent.com/4616287/38058044-4ef10a1c-3296-11e8-8cce-580e18d68c6a.png)

I'm running:

- Ubuntu 16.04 host
- Docker (18.03.0-ce)
- Gitlab 10.5.6

My upgrade was unconventional, as I simply pulled the latest image, built a new local image with `docker-compose` and started up the new one. It's work well for me in the past though.

**Comment by vemcaster** [comment]
Allowing local network requests in the Gitlab`s Admin Settings may help you.

Pay attention to [omnibus-gitlab#3307](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/3307).

**Comment by chrislovsund** [comment]
@vemcaster Yes, changing that setting solved it for us.

**Comment by patrickc91** [comment]
That was it! Thanks for pointing this out. I need to be better about checking issues on the actual Gitlab board too.

Everything seems to be working again. Thanks for your guys' help!
