### ISSUE TITLE
restore gitlab container failed

### ISSUE THREAD

**Issue by YTS85205107** [sameersbn/docker-gitlab#1565]
Hi
I used docker export to back up the gitlab container and recover it in the virtual machine, but when I resumed, I encountered a problem.

Start dockercompose_gitlab-redis_1 ... complete
Start dockercompose_gitlab-postgresql_1 ... complete
error:
Please configure the database connection.
See http://git.io/wkYhyA for more information.
Can not continue without a database. Abort...

What am I doing wrong ?

thanks.

**Comment by solidnerd** [comment]
Hey @YTS85205107, 

I need some more information about this ? Could you provide something more useful with the Detailed output. You could also enable the Debug Mode  with `DEBUG=true` for more information.

**Comment by YTS85205107** [comment]
Hi , @solidnerd 

Thanks your reply.
I refer to the previous container config , and I reconfig docker-compose.yml.
my docker-compose config as below:



version: '2'

services:
  gitlab-postgresql:
    restart: always
    image: local/gitlab-postgresql
    volumes:
      - /srv/docker/gitlab/postgresql:/var/lib/postgresql
    environment:
      - DB_NAME=gitlabhq_production
      - DB_USER=gitlab
      - DB_PASS=1qaz@WSX
      - PG_USER=postgres
      - PG_HOME=/var/lib/postgresql
      - PG_CONFDIR=/etc/postgresql/9.4/main
      - PG_BINDIR=/usr/lib/postgresql/9.4/bin
      - PG_DATADIR=/var/lib/postgresql/9.4/main
    command: [ "/start" ]

  gitlab-redis:
    restart: always
    image: local/gitlab-redis
    volumes:
      - /srv/docker/gitlab/redis:/var/lib/redis
    environment:
      - REDIS_USER=redis
      - REDIS_DATA_DIR=/var/lib/redis
      - REDIS_LOG_DIR=/var/log/redis
    entrypoint:
      - /sbin/entrypoint.sh

  gitlab:
    restart: always
    image: local/gitlab
    ports:
      - "10022:22"
      - "10080:80"
    volumes:
      - /srv/docker/gitlab/gitlab:/home/git/data
    links:
      - gitlab-postgresql:postgresql
      - gitlab-redis:redisio
    environment:
      - DEBUG=true

      - GITLAB_PORT=10080
      - GITLAB_SSH_PORT=10022
      - GITLAB_USER=git
      - GITLAB_HOME=/home/git
      - GITLAB_LOG_DIR=/var/log/gitlab
      - GITLAB_INSTALL_DIR=/home/git/gitlab
      - GITLAB_SHELL_INSTALL_DIR=/home/git/gitlab-shell
      - GITLAB_DATA_DIR=/home/git/data

      - DB_TYPE=postgres
      - DB_ADAPTER=postgresql
      - DB_HOST=gitlab-postgresql
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=1qaz@WSX
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=gitlab-redis
      - REDIS_PORT=6379

      - SETUP_DIR=/var/cache/gitlab
      - RAILS_ENV=production
    entrypoint:
      - /sbin/entrypoint.sh



After I use docker-compose up -d , only gitlab container failed.
I use docker logs , but nothing.
Thanks.
