### ISSUE TITLE
failed to upgrade from gitlab-10.4.2-1 to gitlab-10.6.1.

### ISSUE THREAD

**Issue by tonyxyl** [sameersbn/docker-gitlab#1571]
![image](https://user-images.githubusercontent.com/12979723/38293443-0ecdac4a-381a-11e8-8e12-84b879d5c631.png)

i execute command below to upgrade
```
docker run --name gitlab2 -d --link gitlab-mysql:mysql --link gitlab-redis:redisio --publish 10022:22 --publish 10080:80 -e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=10022' -e 'GITLAB_BACKUPS=daily' -e 'GITLAB_BACKUP_TIME=01:00' -e 'GITLAB_HOST=git.domain.com' -e 'GITLAB_SECRETS_DB_KEY_BASE=a_long_string' -e 'GITLAB_SECRETS_SECRET_KEY_BASE=a_long_string' -e 'GITLAB_SECRETS_OTP_KEY_BASE=a_long_string' -e 'TZ=Asia/Shanghai' -e 'GITLAB_TIMEZONE=Beijing' -v /home/opt/gitlab/data:/home/git/data -v /home/opt/gitlab/log:/home/git/log sameersbn/gitlab:10.6.1
```
then run the command `docker logs gitlab2`, message below

![n h64o r_8p7cd9dc 2 hd7](https://user-images.githubusercontent.com/12979723/38293661-f8413fae-381a-11e8-9fa9-291cafb827f2.png)

shows that while mirations, `Index name 'index_lfs_file_locks_on_user_id' on table 'lfs_file_locks' already exists`.

**Comment by tonyxyl** [comment]
i try to `drop table lfs_file_locks;`, then another problem took place, the sql `CREATE TABLE `lfs_file_locks` (`id` int(11) auto_increment PRIMARY KEY, `project_id` int(11) NOT NULL, `user_id` int(11) NOT NULL, `created_at` datetime NOT NULL, `path` varchar(511),  INDEX `index_lfs_file_locks_on_user_id`  (`user_id`) ) ENGINE=InnoDB` runs smooth, but tells me length of path filed not enough for 767 bytes.

**Comment by ckeyer** [comment]
I have the same problem

**Comment by janorn** [comment]
You are aware that there are several issues with running later gitlab versions on mysql? You might want to consider migrating to postgres.

**Comment by janorn** [comment]
https://docs.gitlab.com/ce/install/requirements.html#database

**Comment by moriyas1984** [comment]
Any update?

**Comment by tonyxyl** [comment]
I solve the problem, by migrating to mysql 5.7
