### ISSUE TITLE
error latest gitlab

### ISSUE THREAD

**Issue by ChessSpider** [sameersbn/docker-gitlab#1591]
Hi!

```
Attaching to gitlab_gitlab_1
gitlab_1      | /etc/docker-gitlab/runtime/functions: line 1020: syntax error near unexpected token `}'
gitlab_1      | /etc/docker-gitlab/runtime/functions: line 1020: syntax error near unexpected token `}'
gitlab_1      | /etc/docker-gitlab/runtime/functions: line 1020: syntax error near unexpected token `}'
gitlab_1      | /etc/docker-gitlab/runtime/functions: line 1020: syntax error near unexpected token `}'
gitlab_1      | /etc/docker-gitlab/runtime/functions: line 1020: syntax error near unexpected token `}'
gitlab_1      | /etc/docker-gitlab/runtime/functions: line 1020: syntax error near unexpected token `}'
gitlab_gitlab_1 exited with code 2
```

Was this fixed by https://github.com/sameersbn/docker-gitlab/commit/9543f1297e185ae8528653a94212282e662e65a1 ?

Because I have the latest gitlab version, but i still get this error

**Comment by ChessSpider** [comment]
IT seems the builds are still pending https://hub.docker.com/r/sameersbn/gitlab/builds/ ? I momentarily reverted back to 10.6.4

**Comment by Yoshi325** [comment]
*Exact* same error for me.

**Comment by CrystalMethod** [comment]
Are you using 10.7.2? This version runs fine for me after upgrading from 10.6.4.

**Comment by giangiangian** [comment]
> Are you using 10.7.2? This version runs fine for me after upgrading from 10.6.4.

+1 for this, just finished the upgrade over the lab deployment, after testing it on a local machine, and everything went smooth on both machines.
Also, to avoid confusion, I'd suggest to never refer to version as "latest", since it creates confusion.

**Comment by ChessSpider** [comment]
I didn't know he was going to release 10.7.0, 10.7.1 and 10.7.2 on the same day ;)

I'll fetch 10.7.2 and test it momentarily, if it works ill close this issue

**Comment by cdalvaro2** [comment]
I had the same error, but it was solved by downloading the latest build after it was properly built.
