### ISSUE TITLE
Latest release failed to build on dockerhub

### ISSUE THREAD

**Issue by HEM42** [sameersbn/docker-gitlab#1602]
Hi,

The lastest release failed to build on dockerhub

And just want to thank you all for the effort being put into this.

**Comment by beevelop** [comment]
@solidnerd Builds for `10.7.3` and `latest` failed due to:
> requesting key E1DF1F24 from hkp server keyserver.ubuntu.com
> Executing: /tmp/tmp.rsmQlDc6gW/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv E1DD270288B4E6030699E45FA1715D88E1DF1F24
> **gpg: keyserver timed out**
> gpg: keyserver receive failed: keyserver error
> Removing intermediate container 3d194997ea0f

Retriggering the affected builds will most probably fix the issue.

**Comment by HEM42** [comment]
There is now a finished build, thank you

**Comment by Ilya-Kuchaev** [comment]
What about latest tag?
