### ISSUE TITLE
How do I set up LDAP for my users?

### ISSUE THREAD

**Issue by streetlist** [sameersbn/docker-gitlab#1612]
I can't seem to find a lot of things like /etc/gitlab/gitlab.rb (like some other youtube videos teaching how to setup gitlab)

I have ldap server but I can't find the ldap menu setting. Pls help. Thanks.

**Comment by Nepoxx** [comment]
Set the following environment variables when starting your container:

```yaml
    - LDAP_ENABLED=true
    - LDAP_LABEL=
    - LDAP_HOST=
    - LDAP_BIND_DN=
    - LDAP_PASS=
    - LDAP_BASE=
```

Please close this issue.

**Comment by streetlist** [comment]
thanks.
