### ISSUE TITLE
10.8.1 Tag is missing

### ISSUE THREAD

**Issue by webdeb** [sameersbn/docker-gitlab#1614]
Hi as long the release is hot, the 10.8.1 tagged image is missing in the hub.

![bildschirmfoto 2018-05-26 um 13 02 53](https://user-images.githubusercontent.com/14992140/40575437-5c36f8bc-60e5-11e8-942b-cb42a28beeeb.png)

**Comment by solidnerd** [comment]
Build isn't finished Check the details at
https://hub.docker.com/r/sameersbn/gitlab/builds/

Boris <notifications@github.com> schrieb am Sa., 26. Mai 2018, 13:04:

**Comment by webdeb** [comment]
Ah, sorry, thanks for clarifying
