### ISSUE TITLE
Question: Run 2 parallel GitLab Containers

### ISSUE THREAD

**Issue by Wyall** [sameersbn/docker-gitlab#1619]
What do I have to change in the docker-compose.yml to achieve 2 completely independent versions of GitLab, each with their own DB and redis?

I guess the ports 10080 and 10022 as they are how I access GitLab. 
But what about the ports that the containers use to communicate, like 5432 for the DB. Do I have to tell postgresql and GitLab to use another port or does docker handle this seperation in any way?

I'm sorry for these general questions, but I couldn't really figure out the correct search terms during my "research"

**Comment by mikew** [comment]
Since redis/DB ports are not exposed to the host, there's no need to change them.

You can change port 80, but an alternative would be put an nginx proxy in front of both Gitlab instances so you don't have to worry about that.

The tricky part will be port 22. Gitlab expects to own that port. For your other host, you will have to tell SSH to use the other port (or use the HTTPS interface).

**Comment by Wyall** [comment]
So even if I'm running 2 complete instances with docker-compose (so 2x redis, DB, gitlab), each gitlab knows which of the DBs to call?

The idea is that we have a running GitLab instance on our QNAP NAS but this was created with QNAP's docker-compose script which is pretty short and e.g. doesn't declare the used volumes in the dc.yml which I find annoying. But I think I need to make some changes to the dc.yml from here for it to work on QNAP, at least the paths seem to be different. Still figuring that out. For that I wanted to run a second instance just for testing along the actual working one and once I figured everything out concerning the docker-compose file, merge them.

**Comment by frenchbeard** [comment]
@Wyall regarding ssh, [orca](https://github.com/clusterit/orca) may be what you're looking for, it even mentions gitlab by name in the [readme](https://github.com/clusterit/orca#using-gitlab).
I have been meaning to try it for a while, but never had the time to get to it, so any feedback on this would be welcome (the setup seems a little cumbersome, though).
