### ISSUE TITLE
Upgrade GitLab CE to 10.8.2 Not working

### ISSUE THREAD

**Issue by mcgowanb** [sameersbn/docker-gitlab#1624]
Clean clone and docker-compose up with this fails and the gitlab container falls into an infinite loop of trying to start. 

The only error message I can get is 
`docker-gitlab_gitlab_1 exited with code 1`

> gitlab_1      | Configuring gitlab::lfs...
> gitlab_1      | Configuring gitlab::uploads...
> gitlab_1      | Configuring gitlab::mattermost...
> gitlab_1      | Configuring gitlab::project_features...
> gitlab_1      | Configuring gitlab::oauth...
> gitlab_1      | Configuring gitlab::ldap...
> gitlab_1      | Configuring gitlab::cron_jobs...
> gitlab_1      | Configuring gitlab::backups...
> gitlab_1      | Configuring gitlab::registry...
> gitlab_1      | Configuring gitlab::pages...
> gitlab_1      | Configuring gitlab-shell...
> gitlab_1      | Configuring nginx...
> gitlab_1      | Configuring nginx::gitlab...
> gitlab_1      | Setting up GitLab for firstrun. Please be patient, this could take a while...
> gitlab_1      | Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.
> docker-gitlab_gitlab_1 exited with code 1
> gitlab_1      | Loading /etc/docker-gitlab/runtime/env-defaults
> gitlab_1      | Initializing logdir...
> gitlab_1      | Initializing datadir...
> gitlab_1      | Generating OpenSSH host keys... RSA DSA ECDSA ED25519 
> gitlab_1      | Installing configuration templates...
> gitlab_1      | Configuring gitlab...
> gitlab_1      | Configuring gitlab::database....

If I roll the git lab version back from `10.8.2` to `10.7.4` in the docker-compose.yml then the app builds

**Comment by roberthass** [comment]
i have the same problem

**Comment by Methol** [comment]
I have the same problem too.

**Comment by jboxberger** [comment]
same here :-(

**Comment by solidnerd** [comment]
Hey, 

sorry for that. I will be fixed when '10.8.3' is out. Try this version and it should work again. If not please reopen this issue.
