### ISSUE TITLE
This probably isn't the expected value for this secret. To keep using a literal Erb string in config/secrets.yml, replace `<%` with `<%%`.

### ISSUE THREAD

**Issue by zc1024** [sameersbn/docker-gitlab#1625]
I run the latest yml.And I get the problem in `unicorn.stderr.log*`.
Hers is the log:
`This probably isn't the expected value for this secret. To keep using a literal Erb string in config/secrets.yml, replace `<%` with `<%%`.`

Can you help me.
Thanks !

**Comment by adamlc** [comment]
I'm also getting the same error :(

**Comment by npotier** [comment]
Just my 2 cents here, but it worked with the **10.8.2** version 

**10.8.3 logs** :

```bash
gitlab_1       | Rails.application.secrets.openid_connect_signing_key was blank, but the literal value in config/secrets.yml was:
gitlab_1       |   -----BEGIN RSA PRIVATE KEY-----
...
gitlab_1       | -----END RSA PRIVATE KEY-----
gitlab_1       | 
gitlab_1       | 
gitlab_1       | This probably isn't the expected value for this secret. To keep using a literal Erb string in config/secrets.yml, replace `<%` with `<%%`.

gitlab_gitlab_1 exited with code 0
```

and the **10.8.2 logs** :

```bash
gitlab_1       | Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.
gitlab_1       | Clearing cache...
```

**Comment by ogasada** [comment]
I also experienced the same error, but now it works as I recreate the docker container of gitlab.

**Comment by dimm0** [comment]
I've rebuilt the container and updated to 10.8.4, still the same error

**Comment by dimm0** [comment]
Read the manual again, and found that ALL secret keys should be more than 64 bytes. That seemed to fix it
