### ISSUE TITLE
Unable to restart gitlab container

### ISSUE THREAD

**Issue by mcgowanb** [sameersbn/docker-gitlab#1629]
Following on from this [issue](https://github.com/sameersbn/docker-gitlab/issues/1624) I'm not able to restart the containers once they are stopped. The containers themselves start, but the gitlab container throws the following error, either using docker-compose up or docker-compose start.

The only way I can fix this currently is to delete the mounted drives under /srv and it will rebuild it again

> Configuring gitlab::oauth...
> Configuring gitlab::ldap...
> Configuring gitlab::cron_jobs...
> Configuring gitlab::backups...
> Configuring gitlab::registry...
> Configuring gitlab::pages...
> Configuring gitlab-shell...
> Configuring nginx...
> Configuring nginx::gitlab...
> /sbin/entrypoint.sh: line 22:   558 Terminated              /usr/bin/supervisord -nc /etc/supervisor/supervisord.conf
>

**Comment by solidnerd** [comment]
Hey @mcgowanb ,

it will be probably fix with #1628 . It will be released soon.

**Comment by solidnerd** [comment]
Release is underway if your errror still exists please reopen this issue. You check https://hub.docker.com/r/sameersbn/gitlab/builds/ when the latest version is ready.
