### ISSUE TITLE
gitlab upgrade to version 10.8.1，Create the gitlab user, reset the password  can not receive mail

### ISSUE THREAD

**Issue by LivesMountain** [sameersbn/docker-gitlab#1644]
docker-compose.yml
version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - /data/gitlab/redis:/var/lib/redis:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.5-1
    volumes:
    - /data/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm

  gitlab:
    restart: always
    image: sameersbn/gitlab:10.8.1
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "10022:22"
    volumes:
    - /data/gitlab/gitlab:/home/git/data:Z
    environment:
    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - TZ=Asia/Shanghai
    - GITLAB_TIMEZONE=Beijing
    
    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=false

    - GITLAB_HOST=###
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
    - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
    - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string

    - GITLAB_ROOT_PASSWORD=
    - GITLAB_ROOT_EMAIL=

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=###
    - GITLAB_EMAIL_DISPLAY_NAME=###
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00
    - SMTP_ENABLED=true
    - SMTP_DOMAIN=exmail.qq.com
    - SMTP_HOST=smtp.exmail.qq.com
    - SMTP_PORT=587
    - SMTP_USER=###
    - SMTP_PASS=MIma632
    - SMTP_TLS=true
    - SMTP_STARTTLS=true

    - SMTP_AUTHENTICATION=login

**Comment by LivesMountain** [comment]
![image](https://user-images.githubusercontent.com/19382017/41702985-79f7ffb6-7564-11e8-9107-deab8c049077.png)I found this error in the execution queue

**Comment by mrnonz** [comment]
I think this issue is related to #1638 .

**Comment by LivesMountain** [comment]
I found a solution to the problem
![image](https://user-images.githubusercontent.com/19382017/41705227-f47053aa-756a-11e8-8c18-d9c888c0c74c.png)
The port written in the gitlab mail configuration document is 587 
But 587 is not the sending port

![kfzc899 g5t6e h9 0qhk1](https://user-images.githubusercontent.com/19382017/41705334-42098244-756b-11e8-9de4-875286a0f784.png)

**Comment by LivesMountain** [comment]
@mrnonz

**Comment by mikew** [comment]
Does setting the `SMTP_PORT` environment variable get it working?
