### ISSUE TITLE
External mysql link timeout one minute

### ISSUE THREAD

**Issue by sufengxue** [sameersbn/docker-gitlab#1646]
when I start gitlab container ,gitlab container exited after one minute. 
Docker version 1.10.3
Centos: 7
docker-gitlab:8.9.5
external mysql
external redis.
the docker logs:
Configuring gitlab::database+ gitlab_finalize_database_parameters
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -z 192.168.132.4 ]]
+ DB_ADAPTER=mysql2
+ case ${DB_ADAPTER} in
+ DB_ENCODING=utf8
+ DB_COLLATION=utf8_general_ci
+ DB_PORT=3306
+ DB_USER=root
+ DB_NAME=gitlab_production
+ gitlab_check_database_connection
+ case ${DB_ADAPTER} in
+ prog='mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status'
+ timeout=60
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 60 - 1
+ timeout=59
+ [[ 59 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 59 - 1
+ timeout=58
+ [[ 58 -eq 0 ]]
.+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 58 - 1
+ timeout=57
+ [[ 57 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 57 - 1
+ timeout=56
.+ [[ 56 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 56 - 1
+ timeout=55
+ [[ 55 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 55 - 1
+ timeout=54
+ [[ 54 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 54 - 1
+ timeout=53
+ [[ 53 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
.++ expr 53 - 1
+ timeout=52
+ [[ 52 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 52 - 1
+ timeout=51
.+ [[ 51 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 51 - 1
.+ timeout=50
+ [[ 50 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 50 - 1
+ timeout=49
+ [[ 49 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 49 - 1
+ timeout=48
+ [[ 48 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 48 - 1
.+ timeout=47
+ [[ 47 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 47 - 1
.+ timeout=46
+ [[ 46 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 46 - 1
.+ timeout=45
+ [[ 45 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 45 - 1
.+ timeout=44
+ [[ 44 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 44 - 1
.+ timeout=43
+ [[ 43 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 43 - 1
.+ timeout=42
+ [[ 42 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 42 - 1
+ timeout=41
+ [[ 41 -eq 0 ]]
.+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 41 - 1
+ timeout=40
+ [[ 40 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 40 - 1
.+ timeout=39
+ [[ 39 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 39 - 1
.+ timeout=38
+ [[ 38 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 38 - 1
+ timeout=37
.+ [[ 37 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 37 - 1
+ timeout=36
+ [[ 36 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 36 - 1
+ timeout=35
+ [[ 35 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 35 - 1
.+ timeout=34
+ [[ 34 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 34 - 1
.+ timeout=33
+ [[ 33 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 33 - 1
+ timeout=32
+ [[ 32 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 32 - 1
+ timeout=31
+ [[ 31 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 31 - 1
+ timeout=30
+ [[ 30 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 30 - 1
+ timeout=29
+ [[ 29 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 29 - 1
+ timeout=28
+ [[ 28 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 28 - 1
.+ timeout=27
+ [[ 27 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 27 - 1
.+ timeout=26
+ [[ 26 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 26 - 1
.+ timeout=25
+ [[ 25 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 25 - 1
.+ timeout=24
+ [[ 24 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 24 - 1
+ timeout=23
+ [[ 23 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 23 - 1
+ timeout=22
+ [[ 22 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 22 - 1
.+ timeout=21
+ [[ 21 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 21 - 1
+ timeout=20
.+ [[ 20 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 20 - 1
+ timeout=19
.+ [[ 19 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 19 - 1
+ timeout=18
+ [[ 18 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 18 - 1
+ timeout=17
+ [[ 17 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 17 - 1
+ timeout=16
+ [[ 16 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 16 - 1
+ timeout=15
+ [[ 15 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 15 - 1
+ timeout=14
+ [[ 14 -eq 0 ]]
.+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 14 - 1
.+ timeout=13
+ [[ 13 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 13 - 1
.+ timeout=12
+ [[ 12 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 12 - 1
.+ timeout=11
+ [[ 11 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 11 - 1
.+ timeout=10
+ [[ 10 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
.++ expr 10 - 1
+ timeout=9
+ [[ 9 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 9 - 1
+ timeout=8
.+ [[ 8 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 8 - 1
+ timeout=7
+ [[ 7 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 7 - 1
+ timeout=6
+ [[ 6 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 6 - 1
+ timeout=5
+ [[ 5 -eq 0 ]]
+ echo -n .
+ sleep 1
.+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 5 - 1
.+ timeout=4
+ [[ 4 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
.++ expr 4 - 1
+ timeout=3
+ [[ 3 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 3 - 1
.+ timeout=2
+ [[ 2 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 2 - 1
.+ timeout=1
+ [[ 1 -eq 0 ]]
+ echo -n .
+ sleep 1
+ mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status
++ expr 1 - 1
+ timeout=0

**Comment by ye** [comment]
Make sure your MySQL connection parameters are correct and able to connect from insider of your GitLab container.

`mysqladmin -h 192.168.132.4 -P 3306 -u root -pquyu@mysql@mgr status` is not responding, check your host ip, port, user, password(perhaps needs to be quoted?) are correct.

**Comment by sufengxue** [comment]
Thank you for reply. It has done. The reason is network problem. Container's network is different from the host. Set the docker run --net=host. Done. Thank you again.

**Comment by ye** [comment]
@sufengxue glad that you were able to figure it out. In your particular case, another way to get it working, you  can probably use `docker run --link $CONTAINER_NAME` to get the default bridge mode networking working as well.
