### ISSUE TITLE
How to upgrade Gitlab Shell and Workhorse to the latest version?

### ISSUE THREAD

**Issue by skorotkiewicz** [sameersbn/docker-gitlab#1649]
How to upgrade Gitlab Shell and Workhorse to the latest version with sameersbn/docker-gitlab?

![update](https://user-images.githubusercontent.com/899351/41862984-bb0e822e-78a5-11e8-8feb-c1370622ac93.png)

**Comment by spritle** [comment]
I guess you are already on latest as per sameersbn docker repo

**Comment by modInfo** [comment]
why is _sameersbn/docker-gitlab_ image not updated?

**Comment by spritle** [comment]
Its mainly maintained by @sameersbn @solidnerd as an open source initiative. They will do it at their own course but dedicated enough for others to relay.
