### ISSUE TITLE
Gitlab 11.0.1 does no longer work with Mysql

### ISSUE THREAD

**Issue by mikehaertl** [sameersbn/docker-gitlab#1652]
The nasty MySQL error as described in #1492 is back. But this time it's worse: Gitlab does not work at all anymore. I only get 500 errors.

Here's what `log/production.log` says:

```
Started GET "/" for 1.2.3.4 at 2018-06-26 19:55:15 +0200
Processing by RootController#index as HTML
Completed 500 Internal Server Error in 133ms (ActiveRecord: 91.3ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Lost connection to MySQL server during query: SELECT MAX(`project_authorizations`.`access_level`) AS maximum_access_level, `project_authorizations`.`project_id` AS project_authorizations_project_id FROM `project_authorizations` WHERE `project_authorizations`.`user_id` = 1 AND `project_authorizations`.`project_id` IN (49, 5, 104, 100, 87, 105, 107, 98, 102, 106, 99, 108, 43, 101) GROUP BY `project_authorizations`.`project_id`):
  config/initializers/connection_fix.rb:20:in `execute'
  app/models/user.rb:1209:in `block in max_member_access_for_project_ids'
  app/models/concerns/bulk_member_access_load.rb:27:in `max_member_access_for_resource_ids'
  app/models/user.rb:1206:in `max_member_access_for_project_ids'
  app/controllers/concerns/renders_member_access.rb:21:in `public_send'
  app/controllers/concerns/renders_member_access.rb:21:in `preload_max_member_access_for_collection'
  app/controllers/concerns/renders_member_access.rb:9:in `prepare_projects_for_rendering'
  app/controllers/dashboard/projects_controller.rb:55:in `load_projects'
  app/controllers/dashboard/projects_controller.rb:10:in `index'
  app/controllers/root_controller.rb:18:in `block in index'
  lib/gitlab/gitaly_client.rb:331:in `allow_n_plus_1_calls'
  app/controllers/root_controller.rb:17:in `index'
  lib/gitlab/i18n.rb:50:in `with_locale'
  lib/gitlab/i18n.rb:56:in `with_user_locale'
  app/controllers/application_controller.rb:362:in `set_locale'
  lib/gitlab/middleware/multipart.rb:95:in `call'
  lib/gitlab/request_profiler/middleware.rb:14:in `call'
  lib/gitlab/middleware/go.rb:17:in `call'
  lib/gitlab/etag_caching/middleware.rb:11:in `call'
  lib/gitlab/middleware/read_only/controller.rb:28:in `call'
  lib/gitlab/middleware/read_only.rb:16:in `call'
  lib/gitlab/request_context.rb:18:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'
  lib/gitlab/middleware/release_env.rb:10:in `call'
```

**Comment by mikehaertl** [comment]
Ok, there's more in `production.log`. This message sounds weird:

```
Mysql2::Error (Unknown MySQL server host 'mysql' (0)):
  lib/gitlab/request_context.rb:18:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'
  lib/gitlab/middleware/release_env.rb:10:in `call'
```

`mysql` is the hostname I've used with all previous versions for my mysql docker container. I can ping that host from inside the gitlab container. So which service is complaining here and why?

**Comment by mikehaertl** [comment]
I've configured the IP address of my mysql container, now the error changes, but it still does not work. 

```
Mysql2::Error (Can't connect to MySQL server on '192.168.0.6' (111)):
  lib/gitlab/request_context.rb:18:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'
  lib/gitlab/middleware/release_env.rb:10:in `call'
```

**Comment by handcode** [comment]
I switched from mysql to maria a while ago. Mainly to get rid of the annoying index length errors. Since then I have no more problems with the gitlab updates.

Upgraded from 10.8.3-1 to 11.0.1 without problem.

You wrote that you can ping the mysql, but does a mysql connect from the gitlab container work?

**Comment by handcode** [comment]
JFYI: currently used Version is 10.2.16-MariaDB-10.2.16+maria~jessie, not dockerized, no special config

**Comment by mikehaertl** [comment]
> You wrote that you can ping the mysql, but does a mysql connect from the gitlab container work?

@handcode I'm very sure. The exact same setup runs fine with any other version of gitlab. And I even think, it executes some command on the DB before the error happens.

**Comment by handcode** [comment]
I've just asked, because error 111 means  'connection refused'  which indicates network error, eg. because mysql is not reachable under this ip/port/hostname (at this time) or server refused connection from this client IP, or NAT or Docker Network problems, or....

thus i would begin to test/debug connection from gitlab to mysql on the lowest possible level.

**Comment by mikehaertl** [comment]
Meanwhile I've tried to make the setup run locally for a test. There it works, so it really seems to be somehow related to the infrastructure.

The big question that remains: Why do some versions of Gitlab work just fine, while others don't?

**Comment by ld0574** [comment]
upgrade 11.0.1 ,not appear this bug, may be just the mysql's config file matters

**Comment by mikehaertl** [comment]
MySQL config is fine. The connection limit there is increased to 1000 (which is much higher then the max connection count). There are also other apps using the same DB container - they all run fine.

It's only some specific versions of Gitlab that have this problem.

**Comment by simonswine** [comment]
Having similar issues with 11.0.2. Seems like `project_authorizations` is messed up (not using this docker images). Haven't found an upstream issue yet :slightly_frowning_face: 

The mysql server crases with:
```
E  2018-07-03T14:58:34.205291Z 11 [ERROR] Table ./gitlab_gitlab/project_authorizations has no primary key in InnoDB data dictionary, but has one in MySQL! If you created the table with a MySQL version < 3.23.54 and did not define a primary key, but defined a unique key with all non-NULL columns, then MySQL internally treats that key as the primary key. You can fix this error by dump + DROP + CREATE + reimport of the table.
E  2018-07-03T14:58:34.206260Z 11 [Warning] Table ./gitlab_gitlab/project_authorizations key_used_on_scan is 0 even though there is no primary key inside InnoDB.
E  2018-07-03T14:58:34.206830Z 11 [ERROR] Index index_project_authorizations_on_project_id of gitlab_gitlab/project_authorizations has 2 columns unique inside InnoDB, but MySQL is asking statistics for 3 columns. Have you mixed up .frm files from different installations? Please refer to http://dev.mysql.com/doc/refman/5.7/en/innodb-troubleshooting.html for how to resolve the issue. 
````

**Comment by npotier** [comment]
Hello @simonswine thanks for reporting your problem. I have the similar issue, and for now the only way I found to have gitlab working is to drop the table `project_authorizations` and recreate it but without the lines : 
```
UNIQUE KEY `index_project_authorizations_on_user_id_project_id_access_level` (`user_id`,`project_id`,`access_level`),
KEY `index_project_authorizations_on_project_id` (`project_id`),
```
As a result, Gitlab is working, but the Activity Dashboard  (dashboard/activity ) is empty.

Would you mind explaining more specifically what you did to recover the table ? And share your MySQL query ? Thank you !

**Comment by simonswine** [comment]
I had a full dump of the project_authorizations, I basically created the table `project_authorizations` with the migrations how it should look like in 11.0.x (cf. https://github.com/gitlabhq/gitlabhq/blob/11-0-stable/db/schema.rb#L1482) and took the INSERT commands out of the backup and executed them.

I think I needed to clear the cache `gitlab-rake cache:clear` to make the activity appear afterwards

**Comment by npotier** [comment]
Thanks @simonswine :)

**Comment by sameersbn** [comment]
Could anyone facing this issue try to run `mysql_upgrade` in there mysql container and retry?

**Comment by pavan5107** [comment]
hello guys i am new to gitlab...! is it possible to configure gitlab with mysql..? if it is possible kindly share the document or link...it was helpfull for me.

**Comment by nixel2007** [comment]
no, gitlab does not support mysql anymore
