### ISSUE TITLE
Gitlab doesn't work | 500 Whoops, something went wrong on our end.

### ISSUE THREAD

**Issue by ChrAu** [sameersbn/docker-gitlab#1669]
Hi,
since the weekend my Gitlab not work correct. 

I see no Error last version was 11.0.3. On Friday it works perfectly with this version. 

> lab_1      | Configuring nginx...
gitlab_1      | Configuring nginx::gitlab...
gitlab_1      | Configuring nginx::gitlab::hsts...
gitlab_1      | /sbin/entrypoint.sh: line 16:   656 Terminated              /usr/bin/supervisord -nc /etc/supervisor/supervisord.conf
gitlab_1      | 2018-07-17 21:11:05,691 CRIT Supervisor running as root (no user in config file)
gitlab_1      | 2018-07-17 21:11:05,691 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
gitlab_1      | 2018-07-17 21:11:05,691 WARN Included extra file "/etc/supervisor/conf.d/gitaly.conf" during parsing
gitlab_1      | 2018-07-17 21:11:05,691 WARN Included extra file "/etc/supervisor/conf.d/gitlab-workhorse.conf" during parsing
gitlab_1      | 2018-07-17 21:11:05,691 WARN Included extra file "/etc/supervisor/conf.d/mail_room.conf" during parsing
gitlab_1      | 2018-07-17 21:11:05,691 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
gitlab_1      | 2018-07-17 21:11:05,691 WARN Included extra file "/etc/supervisor/conf.d/sidekiq.conf" during parsing
gitlab_1      | 2018-07-17 21:11:05,691 WARN Included extra file "/etc/supervisor/conf.d/sshd.conf" during parsing
gitlab_1      | 2018-07-17 21:11:05,691 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
gitlab_1      | 2018-07-17 21:11:05,718 INFO RPC interface 'supervisor' initialized
gitlab_1      | 2018-07-17 21:11:05,718 CRIT Server 'unix_http_server' running without any HTTP authentication checking
gitlab_1      | 2018-07-17 21:11:05,718 INFO supervisord started with pid 1
gitlab_1      | 2018-07-17 21:11:06,721 INFO spawned: 'gitaly' with pid 671
gitlab_1      | 2018-07-17 21:11:06,724 INFO spawned: 'sidekiq' with pid 672
gitlab_1      | 2018-07-17 21:11:06,733 INFO spawned: 'unicorn' with pid 673
gitlab_1      | 2018-07-17 21:11:06,736 INFO spawned: 'gitlab-workhorse' with pid 674
gitlab_1      | 2018-07-17 21:11:06,741 INFO spawned: 'cron' with pid 675
gitlab_1      | 2018-07-17 21:11:06,761 INFO spawned: 'nginx' with pid 687
gitlab_1      | 2018-07-17 21:11:06,777 INFO spawned: 'sshd' with pid 690
gitlab_1      | 2018-07-17 21:11:07,933 INFO success: gitaly entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-07-17 21:11:07,933 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-07-17 21:11:07,933 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-07-17 21:11:07,933 INFO success: gitlab-workhorse entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-07-17 21:11:07,933 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-07-17 21:11:07,933 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-07-17 21:11:07,933 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-07-17 21:11:43,477 INFO exited: sidekiq (exit status 1; not expected)
gitlab_1      | 2018-07-17 21:11:44,484 INFO spawned: 'sidekiq' with pid 811
gitlab_1      | 2018-07-17 21:11:45,487 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-07-17 21:12:16,355 INFO exited: sidekiq (exit status 1; not expected)
gitlab_1      | 2018-07-17 21:12:17,360 INFO spawned: 'sidekiq' with pid 822
gitlab_1      | 2018-07-17 21:12:18,362 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-07-17 21:12:51,708 INFO exited: sidekiq (exit status 1; not expected)
gitlab_1      | 2018-07-17 21:12:52,535 INFO spawned: 'sidekiq' with pid 856
gitlab_1      | 2018-07-17 21:12:53,552 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-07-17 21:13:21,767 INFO exited: sidekiq (exit status 1; not expected)
gitlab_1      | 2018-07-17 21:13:22,108 INFO spawned: 'sidekiq' with pid 863
gitlab_1      | 2018-07-17 21:13:23,559 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-07-17 21:14:08,899 INFO exited: sidekiq (exit status 1; not expected)
gitlab_1      | 2018-07-17 21:14:09,906 INFO spawned: 'sidekiq' with pid 876
gitlab_1      | 2018-07-17 21:14:10,909 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-07-17 21:14:41,761 INFO exited: sidekiq (exit status 1; not expected)
gitlab_1      | 2018-07-17 21:14:42,765 INFO spawned: 'sidekiq' with pid 886
gitlab_1      | 2018-07-17 21:14:43,767 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-07-17 21:15:08,973 INFO exited: sidekiq (exit status 1; not expected)
gitlab_1      | 2018-07-17 21:15:09,976 INFO spawned: 'sidekiq' with pid 895
gitlab_1      | 2018-07-17 21:15:10,979 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-07-17 21:15:38,984 INFO exited: sidekiq (exit status 1; not expected)
gitlab_1      | 2018-07-17 21:15:39,989 INFO spawned: 'sidekiq' with pid 904
gitlab_1      | 2018-07-17 21:15:40,996 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

The log on startup

> root@d3e0fb94e13a:/home/git/gitlab/log# cat sidekiq.log
'#Logfile created on 2018-07-17 21:11:08 +0200 by logger.rb/56815
2018-07-17T19:11:43.277Z 672 TID-6em60 INFO: Booting Sidekiq 5.1.3 with redis options {:host=>"redis", :port=>6379, :password=>nil, :db=>0, :namespace=>"resque:gitlab", :id=>"Sidekiq-server-PID-672", :url=>nil}
2018-07-17T19:12:16.244Z 811 TID-8wojb INFO: Booting Sidekiq 5.1.3 with redis options {:host=>"redis", :port=>6379, :password=>nil, :db=>0, :namespace=>"resque:gitlab", :id=>"Sidekiq-server-PID-811", :url=>nil}
2018-07-17T19:12:51.579Z 822 TID-21gku INFO: Booting Sidekiq 5.1.3 with redis options {:host=>"redis", :port=>6379, :password=>nil, :db=>0, :namespace=>"resque:gitlab", :id=>"Sidekiq-server-PID-822", :url=>nil}
2018-07-17T19:13:20.603Z 856 TID-4j0ao INFO: Booting Sidekiq 5.1.3 with redis options {:host=>"redis", :port=>6379, :password=>nil, :db=>0, :namespace=>"resque:gitlab", :id=>"Sidekiq-server-PID-856", :url=>nil}
2018-07-17T19:14:08.819Z 863 TID-64y87 INFO: Booting Sidekiq 5.1.3 with redis options {:host=>"redis", :port=>6379, :password=>nil, :db=>0, :namespace=>"resque:gitlab", :id=>"Sidekiq-server-PID-863", :url=>nil}
2018-07-17T19:14:40.427Z 876 TID-9kqk4 INFO: Booting Sidekiq 5.1.3 with redis options {:host=>"redis", :port=>6379, :password=>nil, :db=>0, :namespace=>"resque:gitlab", :id=>"Sidekiq-server-PID-876", :url=>nil}
2018-07-17T19:15:08.918Z 886 TID-7pnwm INFO: Booting Sidekiq 5.1.3 with redis options {:host=>"redis", :port=>6379, :password=>nil, :db=>0, :namespace=>"resque:gitlab", :id=>"Sidekiq-server-PID-886", :url=>nil}
2018-07-17T19:15:38.927Z 895 TID-32oob INFO: Booting Sidekiq 5.1.3 with redis options {:host=>"redis", :port=>6379, :password=>nil, :db=>0, :namespace=>"resque:gitlab", :id=>"Sidekiq-server-PID-895", :url=>nil}
2018-07-17T19:16:05.361Z 904 TID-8os6w INFO: Booting Sidekiq 5.1.3 with redis options {:host=>"redis", :port=>6379, :password=>nil, :db=>0, :namespace=>"resque:gitlab", :id=>"Sidekiq-server-PID-904", :url=>nil}

I don't know why the sidekiq starts every 30 to 60 seconds. 
Can someone help me?

**Comment by ChrAu** [comment]
I have found the issue something went wrong with the new Redis version 4.X.X

I go now directly on the 3.0.6 version´.

**Comment by robertzhouxh** [comment]
i encounter the issue too!
