### ISSUE TITLE
Unable to login to Gitlab using LDAP

### ISSUE THREAD

**Issue by tejas1493** [sameersbn/docker-gitlab#1676]
Added the below config to `docker-compose.yml` file 

`    - LDAP_ENABLED= true

    - LDAP_LABEL= Login

    - LDAP_HOST= HostNAme

    - LDAP_PORT= 389

    - LDAP_METHOD= plain

    - LDAP_UID= samAccountName

    - LDAP_BIND_DN= CN=Administrator,CN=Users,DC=company,DC=com

    - LDAP_PASS= password

    - LDAP_BASE= DC=company,DC=com

    - LDAP_ALLOW_USERNAME_OR_EMAIL_LOGIN= false

    - LDAP_ACTIVE_DIRECTORY= true

    - LDAP_USER_FILTER= `

But after spinning, in production log getting below error

` Started POST "/users/auth/ldapmain/callback" for 10.10.100.254 at 2018-07-25 15:53:09 +0530

OmniAuth::LDAP::Adaptor::ConfigurationError (" plain" is not one of the available connect methods: :simple_tls, :start_tls, :plain, :ssl, :tls):

        lib/gitlab/middleware/multipart.rb:97:in `call'

        lib/gitlab/request_profiler/middleware.rb:14:in `call'

        lib/gitlab/middleware/go.rb:17:in `call'

        lib/gitlab/etag_caching/middleware.rb:11:in `call'

        lib/gitlab/middleware/read_only/controller.rb:38:in `call'

        lib/gitlab/middleware/read_only.rb:16:in `call'

        lib/gitlab/request_context.rb:18:in `call'

        lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'

        lib/gitlab/middleware/release_env.rb:10:in `call'

`
Tried with all other methods but still getting same error. I am damn sure its `plain` only. Can anyone help me with this

**Comment by geberl** [comment]
You have space characters between the equal sign and the values.

**Comment by tejas1493** [comment]
Thanks @geberl it worked !! 👍
