### ISSUE TITLE
GITLAB_RELATIVE_URL_ROOT requires access to https://registry.yarnpkg.com

### ISSUE THREAD

**Issue by paddy-hack** [sameersbn/docker-gitlab#1696]
\# Posting findings of my debugging efforts after the fact.

I have been using a `GITLAB_RELATIVE_URL_ROOT` in my GitLab instance since the beginning and have not met any trouble upgrading until now.  I have started from 10.6.1 and gone through the following upgrades

>  10.6.1 → 10.6.3 → 10.6.4 → 10.7.2 → 10.8.3 → 11.0.1

The above all went without a hitch.

Now I'm trying to upgrade to 11.1.4 and my `docker-compose up -d` gets into a boot loop.  When I remove the `GITLAB_RELATIVE_URL_ROOT`, things start fine.  Re-enabling the `GITLAB_RELATIVE_URL_ROOT` again gives me back the boot loop.

**Comment by paddy-hack** [comment]
Hmm, #1628 put me on the wrong track.

I realized that `restart: always` in my `docker-compose.yml` is most likely causing the looping so I took that out and tried again.

The last part of the log is
```
gitlab_1      | 2018-08-06 00:58:23,528 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-08-06 00:58:23,528 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-08-06 00:58:23,528 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_gitlab_1 exited with code 1
```
where the container exists approximately 20 seconds after the `sshd` line.  The unexpected exit leaves a unicorn PID file that triggers the boot loop when `restart: always` is in effect.  Without `restart: always` the boot loop disappears.

**Comment by paddy-hack** [comment]
I didn't quite like making my proxy settings available in the `gitlab` container at *run-time*.  You can take them out after the assets have been recompiled (at least until the next upgrade and/or change of your `GITLAB_RELATIVE_URL_ROOT` and/or removal of the `/home/git/data/tmp/GITLAB_RELATIVE_URL_ROOT` file in the container).

That would be one way to deal with things, but I also noticed that `yarn check` downloads *all* the dependencies in `package.json`.  This effectively restores (part of) the cache that got nuked in #1678 :unamused:  So yes, it's not in the image anymore, but it will be in any container that has a non-empty `GITLAB_RELATIVE_URL_ROOT` :disappointed: 

Looking at the [`yarn check`](https://yarnpkg.com/en/docs/cli/check) documentation, I think that for the image's use case, adding an `--integrity` option in `lib/tasks/yarn.rake` would be a nice solution.  This option still checks that everything is a-okay but does not need network access.  Alternatively, nuking that whole `yarn check` line would do the trick as well.

So, for the moment, I added the following to my customized `entrypoint.sh`, right before the `case` statement
```sh
sed -i \
  -e 's/\(yarn check\)/\1 --integrity/' \
  ${GITLAB_INSTALL_DIR}/lib/tasks/yarn.rake
```

**Comment by LouisKottmann** [comment]
Nice debug :)

Furthermore, I find that you can simply modify the command passed to the image (which lets use you use verbatim images) like this:

```bash
docker run ... <options> ... \
  sameersbn/gitlab:12.3.1 \
  bash -c "/bin/sed -i -e 's/\(yarn check\)/\1 --integrity/' /home/git/gitlab/lib/tasks/yarn.rake && /sbin/entrypoint.sh app:start"
```

**Comment by paddy-hack** [comment]
I volume mount my customized `entrypoint.sh` over the one that's in the "verbatim" image :smile:
