### ISSUE TITLE
Cannot create/update cross-fork MRs

### ISSUE THREAD

**Issue by xasx** [sameersbn/docker-gitlab#1721]
Pulling the issue from GitLab to here after investigation:

https://gitlab.com/gitlab-org/gitlab-ce/issues/51176

### Summary

I have encounter problems when approaching several cross-fork actions belonging to my usual workflow:
* Opening a merge request from a branch within my fork towards the master of the upstream repo, this results in 503 errors.
* Updating existing cross-fork merge request with new commits, they do not show up in the merge requests, neither do the diffs.
  However, the branch in the fork shows the newly added commit.

The issues happened first after upgrading from 11.1.4 to 11.2.3

### Steps to reproduce

1. Use a fresh setup from this variant, then either of the following:

---

1. Have a repo forked
1. Open a merge request from a branch with new commits that forked repo into the upstream repo

---

1. Have a forked repo
1. Create a new branch without changes
1. Create a cross-fork MR for this branch into upstream repo
1. Add commits to this branch

**Comment by xasx** [comment]
### Test run (<5min)
* [opt] remove `/srv/docker`
* [opt] `docker-compose down`
* `docker-compose up`
* wait for boot, goto localhost:10080, set `root` password, login
* create group
* create project
* create README
* fork repo
* create branch
* edit readme
* commit
* create merge request

**Comment by xasx** [comment]
Works for 11.1.4

**Comment by malfter** [comment]
We have the same problem. We are using version 11.2.3

`gitlab_1      | 2018-09-07 13:25:39,348 INFO reaped unknown pid 26672`

**Comment by xasx** [comment]
Seen another similar issue https://gitlab.com/gitlab-org/gitlab-ce/issues/50691

Intermediate fix

```
docker-compose exec gitlab bash
ln -s $(which gitaly-ssh) /
```

Apparently gitaly(-ssh) needs a bit more caring ;)

**Comment by malfter** [comment]
Hi @xasx, thanks for the fix. Works :-)

**Comment by Uporaba1** [comment]
@xasx  Hi! I tried your method 1) i used command `docker exec -ti (id) bash` for access to docker container 2)found gitaly-ssh file 3)used the command `ln -s (file gitaly-ssh directory) /` and restart docker container.

**Comment by xasx** [comment]
@Uporaba1 which exact problem do you encounter?

Have you seen the specific error message in the log files, as linked in the GitLab issue?

**Comment by Uporaba1** [comment]
After the ln -s command and reboot docker, the rebase did not work. No i didn't see error message in the log files.

**Comment by Uporaba1** [comment]
@xasx in gitlab issue i see this:
![image](https://user-images.githubusercontent.com/32709525/45811699-3ce66700-bce7-11e8-98cc-038417f0c158.png)
