### ISSUE TITLE
Confirmation mail never received....again and again the same post

### ISSUE THREAD

**Issue by MickaelCruzDB** [sameersbn/docker-gitlab#1724]
Hi! 2 days with this BIG BIG issue with the repo. WE CAN NOT RECEIVE emails confirmation! Please help. I spent hours on google without any success. I just followed this : https://blog.golimb.com/2017/07/16/synology-docker-gitlab-redis-postgresql/
And same problem - > No confirmation email received

Here is my complete docker-compose.yml : https://gist.github.com/MickaelCruzDB/8ff728eb7c63e2537763306d637e1978

Please reply. Thanks!

**Comment by MickaelCruzDB** [comment]
It's needed to install/configure Mail Server on the Synology in order to receive this stupid email ? Thanks!

**Comment by MickaelCruzDB** [comment]
I tried to install/configure GitLab always with docker but on my mac. Exactly the same issue...... -__-

**Comment by solidnerd** [comment]
It seems that you are using gmail. There instructions are for that in the readme https://github.com/sameersbn/docker-gitlab#mail .

I use the same and it's working for me.
