### ISSUE TITLE
gitlab container restarts indefinitely setting GITLAB_RELATIVE_URL_ROOT

### ISSUE THREAD

**Issue by fdellabetta** [sameersbn/docker-gitlab#1739]
I found a strange behavior changing GITLAB_RELATIVE_URL_ROOT on 11.3.4 version.

I use the same docker-compose file as provided in the repository, but set GITLAB_RELATIVE_URL_ROOT to /git as below
```
- GITLAB_RELATIVE_URL_ROOT=/git
```    
launching docker-compose up -d I noticed that gitlab container exits and restarts indefinitely.

**Comment by fdellabetta** [comment]
Same behaviour for 11.5.3 version. Anyone else facing the same issue?

**Comment by marisbahtins** [comment]
Yes, facing the same issue for sameersbn/gitlab:11.7.3. Checked production_json.log can see ""status":500,"error":"ActionView::Template::Error: Could not load compiled manifest from /home/git/gitlab/public/assets/webpack/manifest.json - have you run `rake webpack:compile`? (original error No such file or directory @ rb_sysopen - /home/git/gitlab/public/assets/webpack/manifest.json)" file is missing. Run rake webpack:compile and it start to work. 

I don't think that a solution.

**Comment by Albenss** [comment]
I have the same issue with the 11.8.0 version, in my log there is a problem with the gitlab-workhorse.log file. I try to running gitlab with the gitlab_relative_url_root=/gitlab on the reverse-proxy named Traefik.

```
Recompiling assets (relative_url in use), this could take a while...
Error: The directory named as part of the path /home/git/gitlab/log/gitlab-workhorse.log does not exist. in section 'program:gitlab-workhorse' (file: '/etc/supervisor/conf.d/gitlab-workhorse.conf')
For help, use /usr/bin/supervisord -h
```

**Comment by Mengkzhaoyun** [comment]
I have the same issue with the 11.8.3 version

`- GITLAB_RELATIVE_URL_ROOT=/git`

**Comment by LockwoodChris** [comment]
> I have the same issue with the 11.8.0 version, in my log there is a problem with the gitlab-workhorse.log file. I try to running gitlab with the gitlab_relative_url_root=/gitlab on the reverse-proxy named Traefik.
> 
> ```
> Recompiling assets (relative_url in use), this could take a while...
> Error: The directory named as part of the path /home/git/gitlab/log/gitlab-workhorse.log does not exist. in section 'program:gitlab-workhorse' (file: '/etc/supervisor/conf.d/gitlab-workhorse.conf')
> For help, use /usr/bin/supervisord -h
> ```
I'm having the exact same issue. I am using the same `gitlab_relative_url_root=/gitlab` param as well as Traefik as the reverse-proxy. However I am using `sameersbn/gitlab:12.5.2`.

> Yes, facing the same issue for sameersbn/gitlab:11.7.3. Checked production_json.log can see ""status":500,"error":"ActionView::Template::Error: Could not load compiled manifest from /home/git/gitlab/public/assets/webpack/manifest.json - have you run `rake webpack:compile`? (original error No such file or directory @ rb_sysopen - /home/git/gitlab/public/assets/webpack/manifest.json)" file is missing. Run rake webpack:compile and it start to work.
> 
> I don't think that a solution.
I also have the exact same error and running `rake2.6 webpack:compile` doesn't even run, I get the following error

```
root@dc3fe98930e2:/home/git/gitlab# rake2.6 webpack:compile
Traceback (most recent call last):
        2: from /usr/bin/rake2.6:23:in `<main>'
        1: from /usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem rake (>= 0.a) with executable rake (Gem::GemNotFoundException)
```

Has anyone managed to get the RELATIVE_URL working?

**Comment by Pastel001** [comment]
so，how to fix this issue?

**Comment by Pastel001** [comment]
Recompiling assets (relative_url in use), this could take a while...
Clearing cache...
2020-08-03 14:18:37,938 WARN received SIGTERM indicating exit request
2020-08-03 14:18:37,938 INFO waiting for sshd, gitlab-workhorse, sidekiq, cron, nginx, gitaly, unicorn to die
2020-08-03 14:18:37,939 INFO stopped: sshd (exit status 0)


I am in k8s.
I remove readiness probe and liveness probe,and wait for a long time.
it restart and go well itself.
