### ISSUE TITLE
Docker build fails with non-zero error code

### ISSUE THREAD

**Issue by martinspaeth** [sameersbn/docker-gitlab#1743]
I tried to build the latest tag locally on my mac.

It fails with:
`/home/git/gitlab/node_modules/.bin/webpack --config /home/git/gitlab/config/webpack.config.js --bail
The command '/bin/sh -c bash ${GITLAB_BUILD_DIR}/install.sh' returned a non-zero code: 137
`

I found a similar issue from 2017 but the corresponding fix had been merged already.
 
https://github.com/sameersbn/docker-gitlab/issues/1188

**Comment by dareolu** [comment]
Does anyone have a solution to this issue? I am facing the same problem.

`rake:assets:precompile` finished in 134.386947952 seconds
The command '/bin/sh -c bash ${GITLAB_BUILD_DIR}/install.sh' returned a non-zero code: 137

The install.sh script already has copy ./config/resque.yml.example to ./config/resque.yml as suggested in #1477 

See below

# gitlab.yml and database.yml are required for `assets:precompile`
exec_as_git cp ${GITLAB_INSTALL_DIR}/config/resque.yml.example ${GITLAB_INSTALL_DIR}/config/resque.yml
exec_as_git cp ${GITLAB_INSTALL_DIR}/config/gitlab.yml.example ${GITLAB_INSTALL_DIR}/config/gitlab.yml
exec_as_git cp ${GITLAB_INSTALL_DIR}/config/database.yml.mysql ${GITLAB_INSTALL_DIR}/config/database.yml

# Installs nodejs packages required to compile webpack
exec_as_git yarn install --production --pure-lockfile
exec_as_git yarn add ajv@^6.0.0

But still, i have had no luck building the Dockerfile.
