### ISSUE TITLE
docker-compose up failed:exit code 1 

### ISSUE THREAD

**Issue by feixiang622** [sameersbn/docker-gitlab#1748]
gitlab_1_d1e1f2771f34 | Recompiling assets (relative_url in use), this could take a while...
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:35,209 CRIT Supervisor running as root (no user in config file)
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:35,210 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:35,210 WARN Included extra file "/etc/supervisor/conf.d/gitaly.conf" during parsing
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:35,210 WARN Included extra file "/etc/supervisor/conf.d/gitlab-workhorse.conf" during parsing
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:35,210 WARN Included extra file "/etc/supervisor/conf.d/mail_room.conf" during parsing
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:35,210 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:35,210 WARN Included extra file "/etc/supervisor/conf.d/sidekiq.conf" during parsing
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:35,210 WARN Included extra file "/etc/supervisor/conf.d/sshd.conf" during parsing
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:35,210 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:35,327 INFO RPC interface 'supervisor' initialized
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:35,327 CRIT Server 'unix_http_server' running without any HTTP authentication checking
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:35,327 INFO supervisord started with pid 595
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:36,330 INFO spawned: 'gitaly' with pid 612
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:36,334 INFO spawned: 'sidekiq' with pid 613
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:36,338 INFO spawned: 'unicorn' with pid 614
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:36,342 INFO spawned: 'gitlab-workhorse' with pid 615
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:36,361 INFO spawned: 'cron' with pid 616
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:36,369 INFO spawned: 'nginx' with pid 617
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:36,382 INFO spawned: 'sshd' with pid 618
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:38,282 INFO success: gitaly entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:38,282 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:38,282 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:38,282 INFO success: gitlab-workhorse entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:38,282 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:38,282 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1_d1e1f2771f34 | 2018-10-21 14:34:38,283 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
root_gitlab_1_d1e1f2771f34 exited with code 1

==============================
 docker-compose.yml  is :

version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    - --protected-mode no
    volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:10
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm

  gitlab:
    image: sameersbn/gitlab:11.3.4
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "10022:22"
    volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data:Z
    environment:
    - DEBUG=true

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Asia/Shanghaidd
    - GITLAB_TIMEZONE=Beijing

    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=false

    - GITLAB_HOST=192.168.244.136
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=/git
    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
    - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
    - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string

    - GITLAB_ROOT_PASSWORD=
    - GITLAB_ROOT_EMAIL=

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=notifications@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false

    - OAUTH_ENABLED=false
    - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
    - OAUTH_ALLOW_SSO=
    - OAUTH_BLOCK_AUTO_CREATED_USERS=true
    - OAUTH_AUTO_LINK_LDAP_USER=false
    - OAUTH_AUTO_LINK_SAML_USER=false
    - OAUTH_EXTERNAL_PROVIDERS=

    - OAUTH_CAS3_LABEL=cas3
    - OAUTH_CAS3_SERVER=
    - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
    - OAUTH_CAS3_LOGIN_URL=/cas/login
    - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
    - OAUTH_CAS3_LOGOUT_URL=/cas/logout

    - OAUTH_GOOGLE_API_KEY=
    - OAUTH_GOOGLE_APP_SECRET=
    - OAUTH_GOOGLE_RESTRICT_DOMAIN=

    - OAUTH_FACEBOOK_API_KEY=
    - OAUTH_FACEBOOK_APP_SECRET=

    - OAUTH_TWITTER_API_KEY=
    - OAUTH_TWITTER_APP_SECRET=

    - OAUTH_GITHUB_API_KEY=
    - OAUTH_GITHUB_APP_SECRET=
    - OAUTH_GITHUB_URL=
    - OAUTH_GITHUB_VERIFY_SSL=

    - OAUTH_GITLAB_API_KEY=
    - OAUTH_GITLAB_APP_SECRET=

    - OAUTH_BITBUCKET_API_KEY=
    - OAUTH_BITBUCKET_APP_SECRET=

    - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=
    - OAUTH_SAML_IDP_CERT_FINGERPRINT=
    - OAUTH_SAML_IDP_SSO_TARGET_URL=
    - OAUTH_SAML_ISSUER=
    - OAUTH_SAML_LABEL="Our SAML Provider"
    - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
    - OAUTH_SAML_GROUPS_ATTRIBUTE=
    - OAUTH_SAML_EXTERNAL_GROUPS=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=

    - OAUTH_CROWD_SERVER_URL=
    - OAUTH_CROWD_APP_NAME=
    - OAUTH_CROWD_APP_PASSWORD=

    - OAUTH_AUTH0_CLIENT_ID=
    - OAUTH_AUTH0_CLIENT_SECRET=
    - OAUTH_AUTH0_DOMAIN=

    - OAUTH_AZURE_API_KEY=
    - OAUTH_AZURE_API_SECRET=
    - OAUTH_AZURE_TENANT_ID=

**Comment by zer01ike** [comment]
Maybe the `TimeZone`  error
my config is 
```
- TZ=Asia/Shanghai
- GITLAB_TIMEZONE=Beijing
```

**Comment by feixiang622** [comment]
thankyou,  My configuration error
