### ISSUE TITLE
sed: -e expression #1, char 23: unknown option to `s'

### ISSUE THREAD

**Issue by matejkramny** [sameersbn/docker-gitlab#175]
Spent 4 hours debugging, no idea what it is, where it comes from..

Can you help?

Thanks

**Comment by YvanDaSilva** [comment]
Had the same issue with TimeZone, in my case I was using Europe/Zurich which is not supported by : http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html

**Comment by sameersbn** [comment]
@YvanDaSilva maybe you need to set it as Paris https://gist.github.com/jpmckinney/767070
