### ISSUE TITLE
No Tag for 11.3.6 on Dockerhub

### ISSUE THREAD

**Issue by Wyall** [sameersbn/docker-gitlab#1750]
Can't install 11.3.6 from dockerhub, as there's no tag for that version. That version was released few days ago here on GitHub.

**Comment by faultylee** [comment]
Same here, though I saw 11.3.5, but that version not listed in the release

**Comment by Wyall** [comment]
I just installed 11.3.5 and in admin settings it also says 11.3.5. I was hoping that it's 11.3.6 and just mislabeled on dockerhub

**Comment by solidnerd** [comment]
Hey,

sorry there was an error on the build. I published `11.3.6` via tag now. So you can use it.
