### ISSUE TITLE
GITLAB_ARTIFACTS_OBJECT_STORE_DIRECT_UPLOAD Is missing

### ISSUE THREAD

**Issue by GJRTimmer** [sameersbn/docker-gitlab#1755]
Option: GITLAB_ARTIFACTS_OBJECT_STORE_DIRECT_UPLOAD is missing.

Could this please be added.

See: https://docs.gitlab.com/ce/administration/job_artifacts.html for the information.
Direct upload is an option which is available.

**Comment by GJRTimmer** [comment]
Awaiting merge of PR #1660

**Comment by GJRTimmer** [comment]
Rebuilding on 11.4.4

**Comment by solidnerd** [comment]
Can be closed it will be available on master with the merge #1660.
