### ISSUE TITLE
Add documentation for migrations from Omnibus to this image

### ISSUE THREAD

**Issue by SamyCoenen** [sameersbn/docker-gitlab#1758]
There doesn't seem to be any documentation on how to migrate from a Omnibus installation to this image. Gitlab itself only seems to provide documentation for from-source to Omnibus installations.

Simply restoring a back-up is possible if the backup came from a CE-install, but you also need gitlab-secrets.json and the ssh folder and maybe more...

**Comment by egeneralov** [comment]
From this image to omnibus:

```
docker-compose exec gitlab /sbin/entrypoint.sh app:rake gitlab:backup:create
docker-compose exec gitlab bash -c 'tar --list -f /home/git/data/backups/*_gitlab_backup.tar'
```

From omnibus to image:
- run docker-compose, but change entrypoint to sleep infinity
- copy backup from omnibus to `/home/git/data/backups/`
- exec bash inside
  - `source /etc/docker-gitlab/runtime/functions`
  - `set +x`
  - `execute_raketask gitlab:backup:restore`
  - enter your backup's filename, agree with all
- restart docker-compose, with correct entrypoint

Enjoy)
