### ISSUE TITLE
Missing /etc/gitlab/gitlab.rb

### ISSUE THREAD

**Issue by Gaibhne** [sameersbn/docker-gitlab#1763]
As per https://docs.gitlab.com/omnibus/settings/configuration.html, GitLab has a lot of unexposed configuration options in the file `/etc/gitlab/gitlab.rb`. In this image, the file does not exist, and although a file with an identical name exists in `/home/git/gitlab/lib/gitlab.rb`, this does not appear to be the file referenced in the GitLab documentation.

Many configuration options are not exposed through environment variables, and I'm wondering how I can set/change them with this image. That I would have to roll my own Dockerfile that extends this one is understood.

**Comment by BartekWalocha** [comment]
I have this same problem. I can not even set the external url parameter. Any changes made in /home/git/gitlab/lib/gitlab.rb are overriden after docker container restart.
What is the proper way to configure this docker image?

**Comment by RobertAcksel** [comment]
@sameersbn Can you please help us with this?

**Comment by Gaibhne** [comment]
It's disappointing that something as basic as, well, basic configuration is not addressed in this image. It would be great if @sameersbn or @solidnerd could chime in to at least give us a rough headsup on what is going on with this. Pretty please ?

**Comment by kaotika** [comment]
Any updates on this?

**Comment by taomaree** [comment]
you can use enviroment variable to do most configuration , check the docs https://github.com/sameersbn/docker-gitlab#available-configuration-parameters

if there are some configuration missing, we need more enviroment variable, like this pr 
https://github.com/sameersbn/docker-gitlab/pull/1884

**Comment by Gaibhne** [comment]
So when there is a configuration missing, there is no way to manually configure it without a PR ?

If that is the case, that seems to be a big issue, which I am surprised isn't getting more votes. Maybe we could get some sort of blanket support as a stop-gap by allowing us to import a custom file with optional, additional settings that are blindly copied to the gitlab.rb file or whatever is used internally in this image ?

**Comment by solidnerd** [comment]
Hey @Gaibhne,
this Image using the install from source method as documented in the [official documentation](https://docs.gitlab.com/ce/install/installation.html). So in this Image  there will be never a `/etc/gitlab/gitlab.rb` if you want to use the `gitlab.rb` you should think about using the [omnibus image](https://docs.gitlab.com/ee/install/docker.html). 

Regarding your request of disabling the templating in this image. I think it could be an option. I would appreciate a proposal in a PR.

**Comment by vl-bwalocha** [comment]
Hi guys! Nothing has changed?
