### ISSUE TITLE
chown of ${GITLAB_BACKUP_DIR} can fail on NFS

### ISSUE THREAD

**Issue by lewismarshall** [sameersbn/docker-gitlab#1765]
When using a network backup NFS device for backups, startup will fail when trying to `chown` the backups directory as specified here:
https://github.com/sameersbn/docker-gitlab/blob/1f71b9999a51c4075ba9468ea0b584e0a6f4eb28/assets/runtime/functions#L1332

It would be desirable to be able to configure this as an optional action (when the storage NFS device is NOT configurable).

**Comment by solidnerd** [comment]
I will close it if your problems still persists. Please feel free to reopen your issue.
