### ISSUE TITLE
can't attach a file in wiki (error: Server responede with 0 code)(sameersbn/gitlab:11.4.5)(docker)

### ISSUE THREAD

**Issue by cmsts007** [sameersbn/docker-gitlab#1777]
Hi

Follow error occurred when i attach a file in wiki of sameersbn/gitlab:11.4.5.

![error1](https://user-images.githubusercontent.com/22828497/48828207-794f4580-edb2-11e8-9429-b9a9ab564bd3.PNG)

And when i checked the network with chrome's developer tools.
I found follow errors ... Maybe the wiki pulgin has the CORS issue?

![error2](https://user-images.githubusercontent.com/22828497/48828408-f5498d80-edb2-11e8-946b-bc485e4458a1.PNG)

Is it a bug of current version? thankfully if help me

**Comment by ElaraFX** [comment]
I met the same issue.

**Comment by 360buyliulei** [comment]
hi be careful:
notice that errors in chrome's developer tools:           
"localhost/api/v4/pro_wikis/attachements:1"

the request url is "localhost"  !!!! 

Resolve:

(1) edit configure file of gitlab: 
 /etc/gitlab/gitlab.rb

modify:
for example:
 external_url    'http://123.112.17.155:8023' ;

(2) execute command to reconfigure gitlab and restart server:
gitlab-ctl reconfigure

(2) reflush browser

**Comment by 360buyliulei** [comment]
> Hi
> 
> Follow error occurred when i attach a file in wiki of sameersbn/gitlab:11.4.5.
> 
> ![error1](https://user-images.githubusercontent.com/22828497/48828207-794f4580-edb2-11e8-9429-b9a9ab564bd3.PNG)
> 
> And when i checked the network with chrome's developer tools.
> I found follow errors ... Maybe the wiki pulgin has the CORS issue?
> 
> ![error2](https://user-images.githubusercontent.com/22828497/48828408-f5498d80-edb2-11e8-946b-bc485e4458a1.PNG)
> 
> Is it a bug of current version? thankfully if help me

hi be careful:
notice that errors in chrome's developer tools:
"localhost/api/v4/pro_wikis/attachements:1"

the request url is "localhost" !!!!

Resolve:

(1) edit configure file of gitlab:
/etc/gitlab/gitlab.rb

modify:
for example:
external_url 'http://123.112.17.155:8023' ;

(2) execute command to reconfigure gitlab and restart server:
gitlab-ctl reconfigure

(3) reflush browser than it is ok

**Comment by cmsts007** [comment]
@360buyliulei 
Thank you. 
But `/etc/gitlab/gitlab.rb` does not exist. refer to #1763 

I think maybe 'GITLAB_HOST' parameter in docker-compose.yml will work. refer to #1043 

```
version: '2'

services:
  gitlab:
    image: sameersbn/gitlab:11.4.4
    depends_on:
      - redis
      - postgresql
    restart: always
    ports:
      - '80:80'
    environment:
      - GITLAB_HOST = mydomain
      - GITLAB_PORT = 80
...
```

**Comment by lincoln310** [comment]
hi i run gitlab in docker with port 5680:80, and i changed the external_url : "http://git.testhost.com". 
I login to http://git.testhost.com:5680
Then when i upload png in wiki, it called api: http://git.testhost.com/api/v4/projects/4/wikis/attachments
which missed port.
