### ISSUE TITLE
missing # leads to build errors

### ISSUE THREAD

**Issue by CrystalMethod** [sameersbn/docker-gitlab#1781]
https://github.com/sameersbn/docker-gitlab/blob/d51ba2d5f1d0bf5e0066d6ac08b5657ca4c50e5e/hooks/build#L1

**Comment by solidnerd** [comment]
Hey,
I fixed it on master. I'll be working now for the latest release. Later when I'm home I'll publish the missing tags.

In future this shouldn't happen anymore. I added shellcheck to prevent this cases.

https://github.com/sameersbn/docker-gitlab/pull/1783

**Comment by CrystalMethod** [comment]
Thx.
