### ISSUE TITLE
upgrade 11.4.5 -> 11.4.7 not working

### ISSUE THREAD

**Issue by MatthiasHertel** [sameersbn/docker-gitlab#1782]
hi there 

i have a curios problem with my morning upgrade procedure.

i did the following steps:

```
root@ht001 ~/code/gitlab # docker-compose pull
Pulling redis           ... done
Pulling postgresql      ... done
Pulling registry        ... done
Pulling gitlab          ... done
Pulling dind            ... done
Pulling runner          ... done
Pulling register-runner ... done
root@ht001 ~/code/gitlab # docker-compose up -d --no-deps --build gitlab
Recreating gitlab_gitlab_1 ... done
```

but the admin-dashboard still hangs on 11.4.5 see below:

![image](https://user-images.githubusercontent.com/8426566/48929185-735a8100-eee6-11e8-9b7d-3aea9973d858.png)

**did I do something wrong?**

-matthias

**Comment by MatthiasHertel** [comment]
i think you are right ...
there are some build errors on docker hub.

e.g. v11.4.7
https://hub.docker.com/r/sameersbn/gitlab/builds/bmd6z59mx2cky8kq8kxuyza/

![image](https://user-images.githubusercontent.com/8426566/48931154-23cf8180-eef5-11e8-99de-5909dd689c3a.png)

![image](https://user-images.githubusercontent.com/8426566/48931179-38137e80-eef5-11e8-827a-7d1f23e93422.png)

**Comment by nixel2007** [comment]
@solidnerd please check this and #1781

**Comment by solidnerd** [comment]
Hey at all,

I fixed it on master. I'll be working now for the latest release. Later when I'm home I'll publish the missing tags.

In future this shouldn't happen anymore. I added shellcheck to prevent this cases.

https://github.com/sameersbn/docker-gitlab/pull/1783

**Comment by mikehaertl** [comment]
@solidnerd I see that the `latest` tag was rebuilt successfully yesterday. Could you also trigger build for 11.4.7 again? I like to use fixed tag versions in my setup and so far 11.4.7 is stil missing.

**Comment by solidnerd** [comment]
@mikehaertl I can't retrigger the build. I rebuilded through my ci and pushed it for you so the tags should also be available back again.

**Comment by mikehaertl** [comment]
Cool, thanks! Just upgraded to 11.4.7 and it worked fine.
