### ISSUE TITLE
11.5.0 build failure

### ISSUE THREAD

**Issue by codereviewvideos** [sameersbn/docker-gitlab#1787]
Hi, 

Thanks for this extremely useful image.

I noticed `11.5.0` is tagged, but not available from Dockerhub. On checking, the build failed: 

```
Step 1/18 : FROM ubuntu:xenial-20181113 unauthorized: authentication required build hook failed! (1)
```

https://hub.docker.com/r/sameersbn/gitlab/builds/b4y6nbkln5cvjc3chbe9j4h/

This is a heads up, as afaik, I don't have any way to debug this further at this stage.

Thanks

**Comment by solidnerd** [comment]
Hey, 
yesterday was some outages on the docker hub. I got a lot of times that pushes was not correct or pulling. I pushed manually there from my ci. The tag `11.5.0` is available.

![image](https://user-images.githubusercontent.com/886383/48997569-b0c24700-f150-11e8-8a4c-86ce91287e89.png)

If it's not working for you. Please reopen this  issue.
