### ISSUE TITLE
Gitlab Pages is too old / Gitlab Pages Access requires additional arguments

### ISSUE THREAD

**Issue by GJRTimmer** [sameersbn/docker-gitlab#1793]
For the Gitlab Pages access control, gitlab pages `v1.3.0` is required, current gitlab pages is too old.

**Comment by GJRTimmer** [comment]
Also gitlab pages daemon start script need to be extended with the oauth -auth-* commandline parameters

**Comment by martinspaeth** [comment]
I run into an issue: when access controll is active pages won’t work with the message  “to many redirects“. I was wondering if this issue means that Pages with access controll might not work currently or if it’s an configuration problem?

**Comment by mantiz** [comment]
> But one has to configure the path to the auth endpoint like:
> https://projects.example.io/**auth**

Thank you very much, you saved me from going crazy :wink:
