### ISSUE TITLE
Versions in Dockerfile don't match gitlab-ce repository

### ISSUE THREAD

**Issue by tiredofit** [sameersbn/docker-gitlab#1797]
Correct should be for current 11.5.1 release as per https://gitlab.com/gitlab-org/gitlab-ce/tree/v11.5.1

    GITLAB_SHELL_VERSION="8.4.1" \
    GITLAB_WORKHORSE_VERSION="7.1.3" \
    GITLAB_PAGES_VERSION="1.3.1" \
    GITALY_SERVER_VERSION="0.129.0"

**Comment by solidnerd** [comment]
I will close this with a new release `11.5.1-1`

**Comment by solidnerd** [comment]
It can be closed since `11.5.1-1` is released also `11.5.5` will be available
