### ISSUE TITLE
How to backup/restore to another machine when using docker-compose?

### ISSUE THREAD

**Issue by justinushermawan** [sameersbn/docker-gitlab#1810]
Hi, is it possible if I want to migrating entire of my containers into another machine/server without losing my volume and settings?

**Comment by GJRTimmer** [comment]
@justinushermawan This is how I do it.
I have created a container for this which can make a complete backup of the containers and even restore them. It uses S3 compatiable storage to store the backups.

You can run your own S3 storage with [minio](https://www.minio.io/)

I use the dockup container: https://hub.docker.com/r/datacore/dockup

Repository: https://github.com/GJRTimmer/dockup

TIP:
If you run the dockup `restore` command in an interactive prompt, it will fetch a list from the S3 server and ask you which volume to restore.

Hope this helps.
