### ISSUE TITLE
How to configure external database in docker-compose file

### ISSUE THREAD

**Issue by Beanben** [sameersbn/docker-gitlab#1818]
This is how my `docker-compose.yml` file looks

    version: '2'
    services:
      redis:
        restart: always
        image: sameersbn/redis:latest
        command:
        - --loglevel warning
        volumes:
        - /srv/docker/gitlab/redis:/var/lib/redis:Z
      gitlab:
        restart: always
        image: sameersbn/gitlab:11.5.1
        depends_on:
        - redis    
        ports:
        - "10080:80"
        - "10022:22"
      volumes:
        - /srv/docker/gitlab/gitlab:/home/git/data:Z
        environment:
        - DEBUG=true
        - DB_ADAPTER=mysql2
        - DB_HOST=<ip address of mysql>
        - DB_PORT=3306
        - DB_USER=gitlab
        - DB_PASS=password
        - DB_NAME=gitlabhq_production
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - TZ=Asia/Kolkata
        - GITLAB_TIMEZONE=Kolkata
        - GITLAB_HTTPS=false
        - SSL_SELF_SIGNED=false
        - GITLAB_HOST=localhost
        - GITLAB_PORT=10080
        - GITLAB_SSH_PORT=10022
        - GITLAB_RELATIVE_URL_ROOT=
        - GITLAB_SECRETS_DB_KEY_BASE=d464ce478a298a3843879a27e5849c0bf8d176e63570dfcf8941ba7484025b3d
        - GITLAB_SECRETS_SECRET_KEY_BASE=803b413fcf537468fcda4b7844a1c9f57e49edb3d655b2e6b24f448a083653f3
        - GITLAB_SECRETS_OTP_KEY_BASE=4fe745b89be6a40748ec24e4a765646b93fd29c1830bdd2f675adb7559212ab3

But am unable to connect to external data base. With containers its working Can any one help us with this

**Comment by GJRTimmer** [comment]
@Beanben can you edit you question and use MarkDown source highlighting, will be easier for anyone to read it. https://help.github.com/articles/creating-and-highlighting-code-blocks/

To your question your external database needs to be resolved from within the container. Your `DB_HOST` is empty. You need to at least enter the IP of the external database. If it is run on the host, put in the IP address of the Host.

**Comment by Beanben** [comment]
@GJRTimmer  sorry missed out formatting it. `DB_HOST` i provided my external database IP but still not working. That's why i posted.

**Comment by YogurtOlderMan** [comment]
how to solve

**Comment by barkurguru** [comment]
I am also stuck with same situation..
Does , docker won't support existing , external-SQL server?

Can you please help..

**Comment by liz-capradio** [comment]
I can't figure this out either... i'm trying to connect my docker containers to a server with a SQL DB on it and there's no clear documentation how... please help

**Comment by sameersbn** [comment]
@liz-capradio GitLab dropped support for MySQL and now only supports PostgreSQL. If you are connecting to an external postgresql server please see https://github.com/sameersbn/docker-gitlab#external-postgresql-server. All you need to do is define the environment variables listed in the command line as env variables in the docker compose file.

If you are still not able to connect, please sure that connections to your db server are not firewalled and that the database user is configured correctly for remote access. 

It would be helpful if you could share a example docker-compose.yml file so that we can reproduce the issue.
