### ISSUE TITLE
manifest for sameersbn/gitlab:11.5.5 not found

### ISSUE THREAD

**Issue by xyzaxyz** [sameersbn/docker-gitlab#1822]
Hi,  
in all the other update cases everything worked good, but today, as 11.5.5 got released, I'm sadly unable to pull the image:  
```
$ docker pull sameersbn/gitlab:11.5.5
Error response from daemon: manifest for sameersbn/gitlab:11.5.5 not found
```

**Comment by nsymms** [comment]
No problems with my `docker pull`. Maybe you tried too early? 11.5.5 was only pushed out a few hours ago.

Have you tried it again?
