### ISSUE TITLE
Unable to trigger mails

### ISSUE THREAD

**Issue by Beanben** [sameersbn/docker-gitlab#1833]
Getting error like below when i mention someones name

> OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol

Using `gitlab:11.5.3` version

And my `docker-compose.yml` file is l:

    version: '3'
    services:
      redis:
        restart: always
        image: sameersbn/redis:4.0.9-1
        command:
        - --loglevel warning
        volumes:
        - /home/tri/Downloads/docker/redis:/var/lib/redis:Z

    gitlab:
        restart: always
        image: sameersbn/gitlab:11.5.3
         depends_on:
        - redis
         ports:
        - "10022:22"
        - "10080:80"
        - "10443:443"

    volumes:
    - /home/tri/Downloads/docker/gitlab/gitlab:/home/git/data:Z
    environment:
    - DEBUG=true

    - DB_ADAPTER=postgresql
    - DB_HOST=HOST_IP
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Asia/Kolkata
    - GITLAB_TIMEZONE=Kolkata

    - GITLAB_HTTPS=true
    - SSL_SELF_SIGNED=true

    - GITLAB_HOST=
    - GITLAB_PORT=10443
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=ZTQyYTkxY2U3ODE4MjgyMzk0ZjU4NDA0ODdlMzBmYWY5OTRlMTYxNDFhMjBjMmY
    - GITLAB_SECRETS_SECRET_KEY_BASE=YWRjMmY0MGEyMTlmYzU2YTlmMGRiMDA0OTQ0ZmY0MmZkYTgyNzEyZDcxNWNlN2Nj
    - GITLAB_SECRETS_OTP_KEY_BASE=ZDdhODVkYWVhM2E0ZDA0Zjk0NjA0MTNmYjQ4ZDdmM2RkZTgyMWY4YzE2MDAwNzU4

    - GITLAB_ROOT_PASSWORD=
    - GITLAB_ROOT_EMAIL=operate@domain.com

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=operate@domain.com
    - GITLAB_EMAIL_REPLY_TO=operate@domain.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=true
    - SMTP_DOMAIN=smtp.office365.com
    - SMTP_HOST=smtp.office365.com
    - SMTP_PORT=587
    - SMTP_USER=operate@domain.com
    - SMTP_PASS=123tri
    - SMTP_STARTTLS=false
    - SMTP_AUTHENTICATION=login
    - SMTP_TLS=true
    
   
please help us with this

**Comment by Beanben** [comment]
@sameersbn any help on this?

**Comment by Beanben** [comment]
any updates on this?

**Comment by Beanben** [comment]
After multiple stop/start it started working. Thanks

**Comment by rtfmpliz** [comment]
in My case I had using this config 

```
gitlab_rails[‘smtp_enable’] = true
gitlab_rails[‘smtp_address’] = ‘172….’ #use IP
gitlab_rails[‘smtp_port’] = 25 # Port 25
gitlab_rails[‘smtp_user_name’] = ’email address’
gitlab_rails[‘smtp_password’] = ‘your password’
gitlab_rails[‘smtp_domain’] = ‘your domain ‘
gitlab_rails[‘smtp_authentication’] = ‘login’
gitlab_rails[‘smtp_enable_starttls_auto’] = true

gitlab_rails[‘smtp_tls’] = true # it has to be deleted or cemmented

gitlab_rails[‘smtp_openssl_verify_mode’] = ‘none’

gitlab_rails[‘smtp_ssl’] = false
gitlab_rails[‘smtp_force_ssl’] = false

user[‘git_user_email’] = ‘same smtp user name’

gitlab_rails[‘gitlab_email_enabled’] = true
gitlab_rails[‘gitlab_email_from’] = ‘same smtp user name’
```
`sudo gitlab-ctl reconfigure`

`sudo gitlab-rake cache:clear RAILS_ENV=production`

i get instruction from here

https://0x0d.im/archives/some-problems-when-build-gitlab-on-aliyun.html
