### ISSUE TITLE
11.6 project edit gives 500, 503, Fedora server 28

### ISSUE THREAD

**Issue by wildlee2** [sameersbn/docker-gitlab#1835]
Hi,
been using docker-compose for some while, but since 11.6 I keep getting the same error. 

with last update to 11.6 I couldnt edit any project on web - 500. Push to directory gives remote closed. When project Files on web - I get 503. 
For a while I thought then migrating from 11.5 was a problem - so I tested a new docker-compose with new volume mount, resulting in the same. 

I am running Fedora server 28, that might be related, but hopefully not.  I did some search in logs - but i didnt find anything that would point out anything. 

Not sure where to look. Any ideas where to look and what to try?

**Comment by solidnerd** [comment]
Hey, 

I think there is problem with your permissions. Did you try to set the correct permissions on your system with:

```
docker run --name gitlab -d [OPTIONS] \
    sameersbn/gitlab:11.6.3 app:sanitize
```

**Comment by wildlee2** [comment]
Assuming my docker compose case : `docker-compose run --rm gitlab app:sanitize`

`docker-compose run --rm gitlab app:sanitize
Creating network "gitlab_default" with the default driver
Creating gitlab-redis   ... done
Creating gitlab-postgre ... done
Loading /etc/docker-gitlab/runtime/env-defaults
Initializing logdir...
Initializing datadir...
Installing configuration templates...
SSL Key, SSL Certificate and DHParam were not found.
Assuming that the container is running behind a HTTPS enabled load balancer.
Configuring gitlab...
Configuring gitlab::database..
Configuring gitlab::redis
Configuring gitlab::secrets...
Configuring gitlab::sidekiq...
Configuring gitlab::gitaly...
Configuring gitlab::monitoring...
Configuring gitlab::gitlab-workhorse...
Configuring gitlab::unicorn...
Configuring gitlab::timezone...
Configuring gitlab::rack_attack...
Configuring gitlab::ci...
Configuring gitlab::artifacts...
Configuring gitlab::lfs...
Configuring gitlab::uploads...
Configuring gitlab::mattermost...
Configuring gitlab::project_features...
Configuring gitlab::smtp_settings...
Configuring gitlab::oauth...
Configuring gitlab::ldap...
Configuring gitlab::cron_jobs...
Configuring gitlab::backups...
Configuring gitlab::backups::schedule...
Configuring gitlab::registry...
Configuring gitlab::pages...
Configuring gitlab-shell...
Configuring nginx...
Configuring nginx::gitlab...
Configuring nginx::gitlab::hsts...
Sanitizing datadir. Please be patient...
Creating gitlab-shell hooks...
`

And that did not fixed the problem.

**Comment by wildlee2** [comment]
Just migrated to fresh new 11.5, and got 500 error on same project pages again. I have given up, and I am about to migrate to some other self-hosted solution - mostly likely Gitbucket. Thanks for help and I guess this can be closed, since I am the only one having these problems :]

**Comment by solidnerd** [comment]
Did you try to set the SELinux Labels ? 

To give you a better support would be to show your current docker-compose.yml without secret values.

**Comment by wildlee2** [comment]
SELinux is off, and sure - here we go:  
version: '2'

services:
  redis:
    container_name: gitlab-redis
    restart: always
    image: sameersbn/redis:4.0.9-1
    command:
    - --loglevel warning
    volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis:Z

  postgresql:
    container_name: gitlab-postgre
    restart: always
    image: sameersbn/postgresql:10
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=###redacted###
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm

  gitlab:
    container_name: gitlab-web
    restart: always
    image: sameersbn/gitlab:11.5.5
    depends_on:
    - redis
    - postgresql
    ports:
    - "9080:80"
    - "9060:22"
    volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data:Z
    environment:
    - http_proxy=https://###redacted###
    - https_proxy=https://###redacted###
    - DEBUG=false

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=###redacted###
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Europe/Prague
    - GITLAB_TIMEZONE=Prague

    - GITLAB_HTTPS=true
    - SSL_SELF_SIGNED=true

    - GITLAB_HOST=https://###redacted###
    - GITLAB_PORT=
    - GITLAB_SSH_PORT=9060
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=###redacted###
    - GITLAB_SECRETS_SECRET_KEY_BASE=###redacted###
    - GITLAB_SECRETS_OTP_KEY_BASE=###redacted###

    - GITLAB_ROOT_PASSWORD=###redacted###
    - GITLAB_ROOT_EMAIL=###redacted###@gmail.com
    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false
    
    - GITLAB_EMAIL=
    - GITLAB_EMAIL_REPLY_TO=
    - GITLAB_INCOMING_EMAIL_ADDRESS=
    
    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=02:00
    
    - SMTP_ENABLED=true
    - SMTP_DOMAIN=smtp.gmail.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=###redacted###@gmail.com
    - SMTP_PASS=###redacted###
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
    
    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=###redacted###@gmail.com
    - IMAP_PASS=###redacted###
    - IMAP_SSL=true
    - IMAP_STARTTLS=false
    
    - OAUTH_ENABLED=false
    - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
    - OAUTH_ALLOW_SSO=
    - OAUTH_BLOCK_AUTO_CREATED_USERS=true
    - OAUTH_AUTO_LINK_LDAP_USER=false
    - OAUTH_AUTO_LINK_SAML_USER=false
    - OAUTH_EXTERNAL_PROVIDERS=
    
    - OAUTH_CAS3_LABEL=cas3
    - OAUTH_CAS3_SERVER=
    - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
    - OAUTH_CAS3_LOGIN_URL=/cas/login
    - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
    - OAUTH_CAS3_LOGOUT_URL=/cas/logout
    
    - OAUTH_GOOGLE_API_KEY=
    - OAUTH_GOOGLE_APP_SECRET=
    - OAUTH_GOOGLE_RESTRICT_DOMAIN=
    
    - OAUTH_FACEBOOK_API_KEY=
    - OAUTH_FACEBOOK_APP_SECRET=
    
    - OAUTH_TWITTER_API_KEY=
    - OAUTH_TWITTER_APP_SECRET=
    
    - OAUTH_GITHUB_API_KEY=
    - OAUTH_GITHUB_APP_SECRET=
    - OAUTH_GITHUB_URL=
    - OAUTH_GITHUB_VERIFY_SSL=
    
    - OAUTH_GITLAB_API_KEY=
    - OAUTH_GITLAB_APP_SECRET=
    
    - OAUTH_BITBUCKET_API_KEY=
    - OAUTH_BITBUCKET_APP_SECRET=
    
    - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=
    - OAUTH_SAML_IDP_CERT_FINGERPRINT=
    - OAUTH_SAML_IDP_SSO_TARGET_URL=
    - OAUTH_SAML_ISSUER=
    - OAUTH_SAML_LABEL="Our SAML Provider"
    - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
    - OAUTH_SAML_GROUPS_ATTRIBUTE=
    - OAUTH_SAML_EXTERNAL_GROUPS=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=
    
    - OAUTH_CROWD_SERVER_URL=
    - OAUTH_CROWD_APP_NAME=
    - OAUTH_CROWD_APP_PASSWORD=
    
    - OAUTH_AUTH0_CLIENT_ID=
    - OAUTH_AUTH0_CLIENT_SECRET=
    - OAUTH_AUTH0_DOMAIN=
    
    - OAUTH_AZURE_API_KEY=
    - OAUTH_AZURE_API_SECRET=
    - OAUTH_AZURE_TENANT_ID=

**Comment by kdlslyv** [comment]
Hi,
Actually having the same issue, but only at one of the gitlab instances I upgraded.
The difference between them is that the one that won't interact with gitlab-shell anymore has http_proxy set.
I skimmed through plenty of logs and found that a health check was failing due to a Bad Request returned by the http_proxy.

Using docker-compose, I disabled the proxy like this:
```
- http_proxy=
- https_proxy=
- HTTP_PROXY=
```

after down and up -d **everything works completely fine again.**

**Comment by wildlee2** [comment]
Health check as to be be found in Admin area -> Monitoring -> Health check : No Health Problems Detected

Also the proxy worked before - I just leaved these proxy settings empty in docker-compose - to no use. Some projects still gives 500 on project general settings. 

I am wondering what these settings do actually - It is true I am behind nginx https proxy, and some issued might be there...

    - http_proxy=https://###redacted###
    - https_proxy=https://###redacted###

I will try to test these variables a bit with different values, but I admit it just shouting in a darkness.

**Comment by kdlslyv** [comment]
@wildlee2 
These environment variables don't have anything to do with your nginx reverse proxy setup. 
They are used for client applications e.g. if you'd want to use wget in your container, wget would connect to the proxy and then fetch the file etc.
I recommend you to unset them like I did above. Do not forget the caps'd one.
If you're not sure about your nginx reverse proxy setup entirely, I recommend you to check out this project https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion.

Kind regards

**Comment by kdlslyv** [comment]
Hmm, I only got a 503 at the repository view due to the proxy settings I had set, which was weird enough. You could try to reproduce that - although that might not help you identify the root cause.

**Comment by eshion** [comment]
Actually having the same issue!  still got a 503 at the repository view although unset proxy settings.

**Comment by eshion** [comment]
you can try to set the repositories fold owner
`chown -R git:git repositories`

**Comment by wildlee2** [comment]
Well, just updated to 11.9.1 and some projects are still not working and settings gives 500. 
How to run this chown command inside docker?

**Comment by wildlee2** [comment]
docker exec -it gitlab bash

**Comment by wildlee2** [comment]
chown -R git:git /home/git/data/repositories  
still general settings instantly throws 500 :/ I am rolling back
