### ISSUE TITLE
Error while pulling 11.6.3

### ISSUE THREAD

**Issue by justinushermawan** [sameersbn/docker-gitlab#1837]
Docker throwed an error while pulling version 11.6.3.

`docker pull sameersbn/gitlab:11.6.3`
Error response from daemon: manifest for sameersbn/gitlab:11.6.3 not found

**Comment by geberl** [comment]
Tag doesn't exist yet on [https://hub.docker.com/r/sameersbn/gitlab/tags/](). I assume `sameersbn/gitlab:latest` is v11.6.3 though, since it has been built 9h ago (vs 2 days ago for v.11.6.2).

**Comment by solidnerd** [comment]
I think something goes wrong on docker hub automated builds again. I published it from my ci systems. If this issue still exists please reopen it.
