### ISSUE TITLE
11.6.4 image not yet available

### ISSUE THREAD

**Issue by edbergavera** [sameersbn/docker-gitlab#1841]
Hi,

The instruction now uses **11.6.4** tag but it seems the image is not available as of yet.

`$ docker-compose up -d`
`Creating gitlab_postgresql_1...`
`Creating gitlab_redis_1...`
`Pulling gitlab (sameersbn/gitlab:11.6.4)...`
`Pulling repository docker.io/sameersbn/gitlab`
`Tag 11.6.4 not found in repository docker.io/sameersbn/gitlab`

**Comment by geberl** [comment]
Interesting. Same issue as for the last version? https://github.com/sameersbn/docker-gitlab/issues/1837

**Comment by lorenz** [comment]
11.6.4 was not tagged somehow, it doesn't look like this is Quay/Docker Hub's issue

**Comment by lorenz** [comment]
I think this can be closed, .4 and .5 were tagged.

**Comment by edbergavera** [comment]
Thanks @lorenz. Closing the issue.
