### ISSUE TITLE
New releases are not correctly tagged on GitHub

### ISSUE THREAD

**Issue by geberl** [sameersbn/docker-gitlab#1844]
On https://github.com/sameersbn/docker-gitlab/releases **11.6.5** and **11.6.4** and **11.6.3** are available but not marked as being the "latest release". Instead **11.6.2** is still marked as being the latest.

Not sure why.

![screenshot 2019-01-22 at 11 47 16](https://user-images.githubusercontent.com/7255425/51530541-78cb3d80-1e3b-11e9-82c2-e3d01ea5799f.png)

**Comment by solidnerd** [comment]
Thanks for pointing this out. I'll fix it today.
