### ISSUE TITLE
[stable/charts] Could we make helm chart for this project?

### ISSUE THREAD

**Issue by colachg** [sameersbn/docker-gitlab#1845]
I have used this project for 3 years and I think it's very good :) using `docker-compose` to start up quickly.

Recently, I have moved my services from `docker-compose` to `kubernetes`. I think it's very convenient to use `helm install gitlab --name gitlab` like `docker-compose up -d`.

I find some files in kubernetes dir.It works using `deploy.sh` but I think we can do something more.
So should we make a chart for this project and make it more convenient in kubernetes?

Here is the official chart repo:
https://github.com/helm/charts

**Comment by MatthiasHertel** [comment]
whats up here ?

**Comment by Overv** [comment]
I don't think there is a point to this as GitLab has released its own Helm chart already: https://docs.gitlab.com/charts/

**Comment by colachg** [comment]
@Overv Yes, it does. The reason why I want to build chart for this project is that there are too many pods within Gitlab's released chart but there are only 3 here and other convenience :)
