### ISSUE TITLE
Still getting port number while cloning

### ISSUE THREAD

**Issue by Beanben** [sameersbn/docker-gitlab#1846]
I have gitlab docker up and running with self signed certificate. While setting up mirroring one thing i found that while cloning the repository it still shows the `port as 100080` instead of `port as 10443`. Can anyone help me with this?. 

And also i want to know how to hide port number from the `url clone`
`https://gitlab.domain.com/root/test.git` instead `https://gitlab.domain.com:10080/root/test.git`

**Comment by drubin** [comment]
@Beanben You might be missing the following configs 

```
   - GITLAB_PORT=443
   - GITLAB_SSH_PORT=22 # ifyou have ssh running on port 22
   - GITLAB_HTTPS=true 
```
