### ISSUE TITLE
NPM Registry

### ISSUE THREAD

**Issue by wormen** [sameersbn/docker-gitlab#1849]
How to enable npm registry?
https://docs.gitlab.com/ee/administration/packages.html

**Comment by pmoralesp** [comment]
It is a premium feature and we use Community Edition (Gitlab Core).
https://about.gitlab.com/2019/01/22/gitlab-11-7-released/#npm-registry

**Comment by johnrocke** [comment]
This is part of the comunity edition as version 13.3 points out.

> [Moved](https://gitlab.com/gitlab-org/gitlab/-/issues/221259) from GitLab Premium to GitLab Free in 13.3.

Can we have some instruction on how to install the npm registry? In special in docker-compose enviroment

**Comment by M0dM** [comment]
It is now very simple to make it work:

The only thing to give ownership to git user to /home/git/data/shared/packages directory
`# chown -R git:git /home/git/data/sharedpackages/`
