### ISSUE TITLE
Question: Are LFS assets migrated automatically when enabling GITLAB_LFS_OBJECT_STORE_ENABLED

### ISSUE THREAD

**Issue by Nepoxx** [sameersbn/docker-gitlab#1850]
For Omnibus installations, one can do `gitlab-rake gitlab:lfs:migrate` to migrate existing LFS objects to object storage. I was wondering if this was done automatically if I enable `GITLAB_LFS_OBJECT_STORE_ENABLED` and if not, how to achieve this.

Same questions for
- `GITLAB_ARTIFACTS_OBJECT_STORE_ENABLED`
- `GITLAB_UPLOADS_OBJECT_STORE_ENABLED`

Cheers!

**Comment by leslau** [comment]
No, It doesnt migrate old artifacts and uploads automatic, it'll use for the new ones

To migrate the old one's you need to run a rake task, like this:

```
sudo -u git -H bundle exec rake gitlab:uploads:migrate:all ENV=production
```

**Comment by Nepoxx** [comment]
Thank you. I did that and the assets are indeed migrated to GitLab. Do you happen to know the upload schedule for background uploads?

**Comment by Nepoxx** [comment]
For anyone wondering, by default `GITLAB_LFS_OBJECT_STORE_BACKGROUND_UPLOAD` is set to false in this repository https://github.com/sameersbn/docker-gitlab/blob/13e856141ec14eff47569bb765a08cd1ea7d0f8d/assets/runtime/env-defaults#L121

This does not match GitLab's default: https://docs.gitlab.com/ee/workflow/lfs/lfs_administration.html#storing-lfs-objects-in-remote-object-storage

(also mentionned here: https://github.com/sameersbn/docker-gitlab/blob/13e856141ec14eff47569bb765a08cd1ea7d0f8d/assets/runtime/config/gitlabhq/gitlab.yml#L186 )

**Comment by leslau** [comment]
if you enable direct_uploads there's no need to enable background_upload, cuz thats nothingo to upload in background :)

**Comment by Nepoxx** [comment]
`GITLAB_LFS_OBJECT_STORE_DIRECT_UPLOAD` is also set to false by default (and undocumented on the README.md (I can do a PR if that would be helpful)).

I feel like `GITLAB_LFS_OBJECT_STORE_BACKGROUND_UPLOAD` should default to true, thoughts @leslau ?
