### ISSUE TITLE
SSH push options not supported

### ISSUE THREAD

**Issue by donbowman** [sameersbn/docker-gitlab#1856]
In [this](https://gitlab.com/gitlab-org/gitlab-ce/issues/44546) support was added for -o ci.skip on push (e.g. git push -o ci.skip). This is great, it means you don't need [ci skip] in the commit message.

However, w/ the omnibus docker image here, I get:

fatal: the receiving end does not support push options

https://gitlab.com/gitlab-org/gitlab-ce/issues/33061 suggests that it should now

https://gitlab.com/gitlab-org/omnibus-gitlab/merge_requests/2113 was the change.

the install docs suggest `sudo -u git -H git config --global receive.advertisePushOptions true`

**Comment by edbergavera** [comment]
I've having the same exact issue. Updated Gitlab to 11.7.5. Git client version is 2.20.1. The following is the error:

`fatal: the receiving end does not support push options`
`fatal: the remote end hung up unexpectedly`

**Comment by donbowman** [comment]
@edbergavera you can work around it by kubectl exec or docker exec into the running container and running the `sudo -u git -H git config --global receive.advertisePushOptions true` command, once.

**Comment by edbergavera** [comment]
@donbowman I'll try this out and update here. Thank you.

**Comment by edbergavera** [comment]
@donbowman The workaround solution is working. Thank you!
