### ISSUE TITLE
How to get the submission method according to gitlab api

### ISSUE THREAD

**Issue by liuqu11** [sameersbn/docker-gitlab#1862]
Hello ！
     Recently encountered a problem, I would like to ask, when I git submit java code, how to get the code I submitted through gitlab api is which method of java? thank！

**Comment by frenchbeard** [comment]
Your issue is lacking a couple of elements to be answered properly : 
- do you mean pushing java source through git or using Java code to push source code to git ?
- when you ask for the method in Java, I guess you mean in the Java API bindings ?

**Comment by liuqu11** [comment]
Thank you for your answer
   Now I pushing java source through git
  What I want is to submit the java code via git and get the modified java class name and method name.
  I am currently using the Get the diff of a commit method in https://gitlab.cae.com/help/api/commits.md, but this method can only get the submitted java class name , can not get the submission The java method name, would you like to ask if there is a way to get the java method name?

**Comment by frenchbeard** [comment]
First of all, that kind of question shouldn't be posted as an issue on this repository, it's linked to the way git works and would be more at home on a forum dedicated to git itself (not a docker container for Gitlab). The commit API only provides information on the underlying git commit, and, if the name of the method, whatever language is concerned (Java or anything else), has not been modified, git won't know about it.

You should learn the way git (and its commits) work a little before attempting to use an API providing information on some of its elements, be it Gitlab's or any other.
