### ISSUE TITLE
Passing argument to automated backup

### ISSUE THREAD

**Issue by djelenc** [sameersbn/docker-gitlab#1863]
How do I pass extra parameters to the automated backup?

In particular, I'd like to pass in a flag [to exclude artifacts](https://docs.gitlab.com/ee/raketasks/backup_restore.html#excluding-specific-directories-from-the-backup), but looking at the docs, I could not find a setting that would correspond to the `SKIP` flag.

**Comment by geberl** [comment]
As I see it there is `GITLAB_BACKUP_SKIP`, that takes the same values as described in your documentation link.

**Comment by djelenc** [comment]
Thank you. It must be the lack of sleep.
