### ISSUE TITLE
ERROR: Downloading artifacts from coordinator... error

### ISSUE THREAD

**Issue by edbergavera** [sameersbn/docker-gitlab#1864]
Hi,

We recently encountered an intermittent issue when running the pipeline. We've recently upgraded to latest GitLab 11.7.5 and GitLab Runner 11.7.0, reverse proxy to Nginx 1.14.0 on Ubuntu 18.04. The following errors occurs intermittently, however the build/stage passes after a retry. We didn't have issues like this when we were in version 8.16.6 and Gitlab CI multi runner 1.x. 

`Downloading artifacts for build (53092)...
ERROR: Downloading artifacts from coordinator... error  error=read tcp 172.17.0.3:59476->xx.xxx.59.37:443: read: connection reset by peer id=53092 responseStatus=200 OK token=GrTYH7v2
WARNING: Retrying...                               
ERROR: Downloading artifacts from coordinator... error  error=read tcp 172.17.0.3:59478->xx.xxx.59.37:443: read: connection reset by peer id=53092 responseStatus=200 OK token=GrTYH7v2
WARNING: Retrying...                               
ERROR: Downloading artifacts from coordinator... error  error=read tcp 172.17.0.3:59480->xx.xxx.59.37:443: read: connection reset by peer id=53092 responseStatus=200 OK token=GrTYH7v2
FATAL: invalid argument                            
ERROR: Job failed: exit code 1`

**Comment by jpsamper2009** [comment]
We've been starting to see this error too:

Gitlab 11.7.5 with Runner 11.2

**Comment by infraengineer-sre** [comment]
Please help.

Solution/workaround/debug method needed!

```
gitlab-runner --version
Version:      12.9.0
Git revision: 4c96e5ad
Git branch:   12-9-stable
GO version:   go1.13.8
Built:        2020-03-20T13:01:56+0000
OS/Arch:      linux/amd64
```

```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.18.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.603GiB
 Name: srv-v-gitlab-runner01.example.com
 ID: IJPZ:GV3T:SOME:TEXT:HERE:7G4U:6VYX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
GitLab Community Edition 12.3.5

**Comment by FinnFrotscher** [comment]
+1
