### ISSUE TITLE
sameersbn/gitlab:11.8.0 is not tagged in docker hub

### ISSUE THREAD

**Issue by lspvic** [sameersbn/docker-gitlab#1868]
only see latest but 11.8.0 not found

https://hub.docker.com/r/sameersbn/gitlab/tags

**Comment by fhandschuch** [comment]
and the last build has failed as well
https://hub.docker.com/r/sameersbn/gitlab/builds

**Comment by lorenz** [comment]
11.8.0 is not tagged in the Git repository so it won't be picked up by the Docker registries. Build failure seems to be a fluke, I've just successfully built master.

**Comment by Ilya-Kuchaev** [comment]
@sameersbn @solidnerd ?

**Comment by solidnerd** [comment]
That it's not tagged is correct because I'm thinking of implementing new features. But latest should work. I'll figure out why. I think we need to push this tags through circle ci the docker hub is not reliable enough.

**Comment by lorenz** [comment]
The problem is not that you're not tagging it since you want to make some additional changes, but that the README currently says one should use a version that doesn't exist.

**Comment by Ilya-Kuchaev** [comment]
Any news here?

**Comment by nixel2007** [comment]
I think maintainers should impmement new features *before* breaking old behavior...

**Comment by solidnerd** [comment]
Everything is like before `11.8.0` is tagged and it's released on docker hub. So you can use it. I'll think about it how can't have this type of impact again in future releases.
