### ISSUE TITLE
Change GITLAB_SECRETS_XXXX

### ISSUE THREAD

**Issue by edbergavera** [sameersbn/docker-gitlab#1869]
Hi,

I just found out recently that our previous sysadmin uses the default string when setting up GitLab. The following is the excerpt from the existing _**docker-compose.yml**_ file:

`- GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string`
`- GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string`
`- GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string`

I am reluctant to update any of these but would like to solicit your advise.

Thank you.

**Comment by drubin** [comment]
You should definitely change them ASAP knowing these values a user can login as an admin user to your gitlab instance (manually setup cookies)

When you change the following could happen maybe more, you should **always verify from a backup instance.**

* All your secret variables in gitlabCI could be reset 
* Any encrypted data stored in gitlab could break 
* None of your user's 2FA otps will work any more 
* All your users will be logged out of gitlab (although they should be able to login) 

I am not 100% sure what will happen but you should **always** test these types of changes on a backup instance.

The easiest one to cycle should be `GITLAB_SECRETS_SECRET_KEY_BASE` then `GITLAB_SECRETS_OTP_KEY_BASE` as you could potentially disable 2FA for all users and make them re-enable it. 

`GITLAB_SECRETS_DB_KEY_BASE` this is the one I really am not sure how it will affect. You should do some research in the official gitlab docs about cycling this value. 

Hope this helps.

**Comment by edbergavera** [comment]
Thanks @drubin I'll take note of that.

**Comment by lordvlad** [comment]
Had the same issue once. One thing that we did _not_ think about were CI
variables on group and project level. We were not able to edit ci variables
anymore via the ui, the server failed to decrypt the old values. In the end
we had to remove all ci varables in the database directly (using `psql`)
and recreate them after a server restart. Thinking back, it would've been
easier removing all variables before changing the keys, and recreating them
afterwards. using the gitlab web API, you could write a script to iterate
all groups and projects, back up and remove all ci variables, and restore
them after changing the keys.
