### ISSUE TITLE
GitLab 11.9?

### ISSUE THREAD

**Issue by MacGyver27** [sameersbn/docker-gitlab#1887]
Pretty big update 4days ago.. any ETA??

[GitLab 11.9
Friday, March 22, 2019](https://about.gitlab.com/releases/)

**Comment by GJRTimmer** [comment]
I require it too. Gitlab Runners have deprecation warning:

```
DEPRECATION: this GitLab server doesn't support refspecs, gitlab-runner 12.0 will no longer work with this version of GitLab
```

**Comment by lillem4n** [comment]
Hm, I'm getting 11.10.4 when running the latest compose file from this repository. This issue should be closed, no?

**Comment by tomislater** [comment]
Yeah, it should be closed.
