### ISSUE TITLE
Gitlab security release 11.9.4, 11.8.6, 11.7.10

### ISSUE THREAD

**Issue by flobaader** [sameersbn/docker-gitlab#1889]
Hi,

Gitlab has released new security patches:
https://about.gitlab.com/2019/04/01/security-release-gitlab-11-dot-9-dot-4-released/

**Comment by mrnonz** [comment]
I don't know why them not provide another contributor to release version.

**Comment by GJRTimmer** [comment]
Hopefully will be updated soon because of gitlab-runner.

From gitlab runner log:

```
DEPRECATION: this GitLab server doesn't support refspecs, gitlab-runner 12.0 will no longer work with this version of GitLab
```
