### ISSUE TITLE
gitlab-ci.yml自定义个人模板

### ISSUE THREAD

**Issue by cai823294620** [sameersbn/docker-gitlab#1893]
### 新建gitlab-ci.yml脚本时,如何定义个人模板呢.

![image](https://user-images.githubusercontent.com/44595276/55536474-6a778880-56ec-11e9-903d-c2efca2c2812.png)

**Comment by geberl** [comment]
Google Translate: "How to define a personal template when creating a new gitlab-ci.yml script."

**Comment by yen3** [comment]
If you have any problem about the usage of gitlab, you have to ask support from gitlab. https://about.gitlab.com/support/

**Comment by ifsc01** [comment]
这不应该看 gitlab 的文档吗 https://segmentfault.com/a/1190000010442764
