### ISSUE TITLE
Crash within few minutes after upgrading from 11.8.3 to 11.9.5 

### ISSUE THREAD

**Issue by tomastzn** [sameersbn/docker-gitlab#1895]
Previous upgrades, up to 11.8.3, sometimes crashed too right after upgrade, but as noted in one other issue, removing the containers and then starting them up resolved that problem.
Now, after upgrading to 11.9.5, it starts up fine, but within minutes it will crash and docker restarts the container. I have reviewed the logs but did not see anything indicating what's happening.
Any ideas?

**Comment by geberl** [comment]
This looks like the issue I had. https://github.com/sameersbn/docker-gitlab/issues/1861

**Comment by tomastzn** [comment]
Sounds similar, however, I forgot to mention that we had Gitlab up & running for a while before it crashed. Maybe it wasn't done with compiling assets at that time and that caused the issue.

**Comment by geberl** [comment]
For us everything looked ok for the first 12 minutes after each restart as well. GitLab was a bit slow, but responding correctly for the most part (some pages showed error 500s). I'd check my container's RAM usage...

<img width="700" alt="Screenshot 2019-04-08 at 10 17 13" src="https://user-images.githubusercontent.com/7255425/55708974-85e1dc80-59e7-11e9-9d2a-e1203ade0eee.png">
