### ISSUE TITLE
Helm chart for sameersbn/docker-gitlab

### ISSUE THREAD

**Issue by xtof2all** [sameersbn/docker-gitlab#1913]
Hi Maintainers, 

In the last months, I have create at my current employer a helm chart around this sameersbn/docker-gitlab. It includes the both the redis and the gitlab-ce as statefulsets in a chart template. Today, I have added this code in a fork of your repo as I'm believe it might be of interest of the community. You can find it in https://github.com/xtof2all/docker-gitlab/tree/add-a-chart. 

The relevant chart (and a README.md) can be found in the directory helm-chart. I've merged the latest 11.10.4 into this (add-a-chart) branch. The helm-chart assumes an external available postgres database as this is our situation.  I have not been able to include all the available configuration parameters, but I was able to do the most relevant ones (at least from our perspective). If you are interested in including a chart along with this code, I'm willing to do the boilerplate templating for the other parameters as well. 

What do you think? 
Yours,
Christof Debaes

**Comment by xtof2all** [comment]
No interests?

**Comment by Maghin** [comment]
I'll try that soon, thanks !

**Comment by sharkymcdongles** [comment]
I am interested and will check it out.
