### ISSUE TITLE
app:rake: command not found

### ISSUE THREAD

**Issue by hanxiaoer1992** [sameersbn/docker-gitlab#1916]
![image](https://user-images.githubusercontent.com/29499769/57607222-a15a7d00-757b-11e9-9af4-f0f0cd68cb9d.png)

**Comment by geberl** [comment]
For me commands like these work:

```bash
cd /home/git/gitlab/bin
./rake gitlab:backup:create SKIP=builds,artifacts,registry,lfs
```

**Comment by adaliszk** [comment]
Use `/sbin/entrypoint.sh app:rake`
