### ISSUE TITLE
Gitlab 11.11

### ISSUE THREAD

**Issue by paolomainardi** [sameersbn/docker-gitlab#1920]
Is it planned the 11.11 release ?

**Comment by paolomainardi** [comment]
cc @solidnerd

**Comment by solidnerd** [comment]
@paolomainardi  I'll doing it by end of the day or tomorrow by end of the day. If someone wants to do it. A PR could help for this.

**Comment by paolomainardi** [comment]
Thank you so much @solidnerd, would be nice if you can write down some notes about the upgrade process you follow, so we can help you better for the next releases.

**Comment by solidnerd** [comment]
I'll do it. I think some steps should be added [CONTRIBUTING.md](https://github.com/sameersbn/docker-gitlab/blob/master/CONTRIBUTING.md) how to prepare a release and which steps are required for an easy review und faster setup. 

I'll close this issue because `11.11.0` is shipped.
