### ISSUE TITLE
Gitlab crashes after enabling 2FA

### ISSUE THREAD

**Issue by AmoXJS** [sameersbn/docker-gitlab#1933]
We experience an "Oops something went wrong" error when enabling the 2FA setting. It happens if as a single user or if set/enforced globally for all users. Experienced this on 11.9.1 and on 11.11.0. Only solution was to roll back.
GITLAB_SECRETS keys have been set

==> production_json.log <==
{"method":"GET","path":"/profile/two_factor_auth","format":"html","controller":"Profiles::TwoFactorAuthsController","action":"show","status":500,"error":"ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column \"id\" violates not-null constraint\nDETAIL:  Failing row contains (null, 19, 0, 0, 2019-06-06 14:59:17.097356+00, 2019-06-06 14:59:17.097356+00, null, null, null).\n: INSERT INTO \"user_preferences\" (\"user_id\", \"created_at\", \"updated_at\") VALUES ($1, $2, $3) RETURNING \"id\"","duration":76.16,"view":0.0,"db":12.13,"time":"2019-06-06T14:59:17.028Z","params":[],"remote_ip":"10.42.231.92","user_id":19,"username":"REDACTED","ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36","queue_duration":null,"correlation_id":"AftV8lPbf53"}

==> production.log <==
  
ActiveRecord::StatementInvalid (PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, 19, 0, 0, 2019-06-06 14:59:17.097356+00, 2019-06-06 14:59:17.097356+00, null, null, null).
: INSERT INTO "user_preferences" ("user_id", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"):
  
config/initializers/active_record_locking.rb:14:in `_create_record'
app/services/users/update_service.rb:21:in `execute'
app/services/users/update_service.rb:30:in `execute!'
app/controllers/profiles/two_factor_auths_controller.rb:15:in `show'
lib/gitlab/i18n.rb:55:in `with_locale'
lib/gitlab/i18n.rb:61:in `with_user_locale'
app/controllers/application_controller.rb:434:in `set_locale'
lib/gitlab/middleware/multipart.rb:103:in `call'
lib/gitlab/request_profiler/middleware.rb:16:in `call'
lib/gitlab/middleware/go.rb:20:in `call'
lib/gitlab/etag_caching/middleware.rb:13:in `call'
lib/gitlab/middleware/correlation_id.rb:16:in `block in call'
lib/gitlab/correlation_id.rb:15:in `use_id'
lib/gitlab/middleware/correlation_id.rb:15:in `call'
lib/gitlab/middleware/read_only/controller.rb:40:in `call'
lib/gitlab/middleware/read_only.rb:18:in `call'
lib/gitlab/middleware/basic_health_check.rb:25:in `call'
lib/gitlab/request_context.rb:26:in `call'
lib/gitlab/metrics/requests_rack_middleware.rb:29:in `call'
lib/gitlab/middleware/release_env.rb:13:in `call'

**Comment by DROMZEE** [comment]
This command disable 2FA 
`sudo -u git -H bundle exec rake gitlab:two_factor:disable_for_all_users RAILS_ENV=production`
