### ISSUE TITLE
Attach image/file in wiki give 404 Project not found since upgrade to 11

### ISSUE THREAD

**Issue by drmclem** [sameersbn/docker-gitlab#1943]
I am running the docker on a NAS system and have recently upgrade from 9.2.2 to 11.11.3

Since the upgrage when I try and paste or attach a file/image into the wiki I get

![image](https://user-images.githubusercontent.com/35807311/60585682-2bf37780-9d88-11e9-84c4-2ffb76ca5735.png)

Looking at  [https://gitlab.com/gitlab-org/gitlab-ce/issues/52243](url) one suggestion was that this was related to https being false which I think is the default for the docker version.

I suspect that this is due to a combination of my port forwarding on the home network and http v https but haven't been able to resolve. Enabling https in the docker compose yml file chanegs the error to that reported in issue 1777.

My compose file is (with the external things redacted)
```
environment:
    DEBUG: 'false'
    GITLAB_PORT: 10080
    GITLAB_SECRETS_DB_KEY_BASE: qcs-gitlab-app
    GITLAB_SSH_PORT: 10022
    SMTP_ENABLED: 'true'
    SMTP_USER: 'XXXX.XXXX@gmail.com'
    SMTP_PASS: 'XXXXXXXX'
    GITLAB_HOST: 'XXXX.XXXX.com'
    GITLAB_HTTPS: 'false'
  ports:
  - "10080:80"
  - "10443:443"
  - "10022:22"
```
And my interior network router is mapping port 80 -> 10080 and port 443-> 10443

Any suggestions on how to resolve ?

Many thanks

Matthew

**Comment by drmclem** [comment]
Hi

Small update - still not sure how to resolve but ... 

It looks lke if i access the web interface via the portmapping, insertion of images fails 

ie. http://XXXX.XXXX.com:/root/TestProject/wikis/home/edit

but if I explicitly include the port

http://XXXX.XXXX.com:10080/root/TestProject/wikis/home/edit - its ok.

Matthew

**Comment by Silicomancer** [comment]
I have the same issue. Did you find a solution?

**Comment by drmclem** [comment]
Not really - I ended up default forwarding to that Port on the router for standard HTTP which was not ideal. Some magic is needed on the docker port/http configuration - I think the gitlab sends the image upload reqest back out without explicitly setting the 10080 port so instead of the request going to the docker it goes to the default http server (I'm running this on a NAS so it goes to admin page of the NAS) and therefore fails.
