### ISSUE TITLE
Number of forks not correctly shown on Project > Details page in GitLab 11.10.4

### ISSUE THREAD

**Issue by QuickJack** [sameersbn/docker-gitlab#1953]
I do have several forked projects on my GitLab 11.10.4 instance which were created using earlier versions of GitLab. The number of forks is correctly shown on the Project > Details page. 

However, when forking a newly created project, the number of forks is shown as 0. When clicking on the 0 the forked project is shown correctly. An upgrade to 11.11.3 doesn't change anything.

Does anybody experience the same behaviour?

**Comment by drujd** [comment]
This might be better suited for GitLab issue tracker...

**Comment by daniel-deutscher** [comment]
Are there any concerning logs in your postgresql container?

**Comment by QuickJack** [comment]
I don't think so. Following is my postgresql log:

> Initializing datadir...
> Initializing certdir...
> Initializing logdir...
> Initializing rundir...
> Setting resolv.conf ACLs...
> Creating database user: gitlab
> Creating database: gitlabhq_production...
> ‣ Loading pg_trgm extension...
> ‣ Granting access to gitlab user...
> Starting PostgreSQL 10...
> 2019-08-23 13:05:13.505 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> 2019-08-23 13:05:13.505 UTC [1] LOG:  listening on IPv6 address "::", port 5432
> 2019-08-23 13:05:13.521 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> 2019-08-23 13:05:13.546 UTC [2589] LOG:  database system was shut down at 2019-08-23 13:05:13 UTC
> 2019-08-23 13:05:13.572 UTC [1] LOG:  database system is ready to accept connections

**Comment by QuickJack** [comment]
I started to work on a forked project and after a few day, the number of forks display was updated correctly. I did not track down, what actually caused the update.

This strange effect seems to be related to GitLab itself. I will close this issue now.
