### ISSUE TITLE
sameersbn/gitlab not only start  accordong to usage docs

### ISSUE THREAD

**Issue by nongzhi9950** [sameersbn/docker-gitlab#1954]
https://hub.docker.com/r/sameersbn/gitlab

**Comment by nongzhi9950** [comment]
Tried the below command as wel
docker run --name gitlab -d \ --env 'DB_ADAPTER=mysql2' --env 'DB_HOST=mysql_IP' \ --env 'DB_NAME=gitlabhq_production' \ --env 'DB_PORT=3306' \ --env 'DB_USER=gitlab' --env 'DB_PASS=password' \ --volume /srv/docker/gitlab/gitlab:/home/git/data \ sameersbn/gitlab:latest

but getting like below

Loading /etc/docker-gitlab/runtime/env-defaults Initializing logdir... Initializing datadir... Installing configuration templates... Configuring gitlab... Configuring gitlab::database...........................................................

**Comment by nongzhi9950** [comment]
i feel this image is bad?

**Comment by saknarak** [comment]
I found DB_ADAPTER=mysql2 is not used.
it try to connect postgresql anyway...
add DEBUG=true to environment to see what happen

**Comment by saknarak** [comment]
i found gitlab no longer support mysql

https://about.gitlab.com/2019/06/27/removing-mysql-support/
