### ISSUE TITLE
`Update ASAP` displayed just after upgrade

### ISSUE THREAD

**Issue by y0va** [sameersbn/docker-gitlab#1955]
This is a bit distracting.

![image](https://user-images.githubusercontent.com/21321805/61043574-e9105000-a3d6-11e9-838b-d51c40e5ea1a.png)

**Comment by icedream** [comment]
The docker image has not been updated to the current GitLab versions 11.11.5/12.0.3 yet. I noticed this myself yesterday as well.

**Comment by spantaleev** [comment]
Feels like updates are coming in more and more rarely.

Why does it take so long to keep up with upstream?
Perhaps this image is unmaintained and it's time to move on to another one?

I can see people trying to contribute and push it further along, but pull requests stay open for weeks without being merged by a maintainer..

**Comment by icedream** [comment]
Probably this image needs quite some testing for updates now that GitLab 12 is out. I am seeing this confirmed now that the first GitLab 12 updates have been pushed into this docker image (12.0.1 as of writing this post).

**Comment by spantaleev** [comment]
12.0.0 is released for this image, but that's not good enough.

12.0.x versions have been released after it and already contain tens of fixes, 10 of which for security.
Being stuck on 12.0.0 is not good.

Thankfully, one can stay behind on 11.11.3, which while outdated (11.11.4 is out with fixes), is likely not vulnerable to all the new stuff introduced in 12.x. Although.. given that Gitlab is now at 12.1.0, I'm unsure as to whether they are still backporting fixes to 11.11.x. Their [GitLab Release and Maintenance Policy](https://docs.gitlab.com/ee/policy/maintenance.html) does not say it definitively. Maybe they still are..
