### ISSUE TITLE
Error database connection after upgrade 11.0.4 to 12.0.0

### ISSUE THREAD

**Issue by DROMZEE** [sameersbn/docker-gitlab#1958]
Hi,

After upgrade synology_gitlab 11.0.4 to 12.0.0 on a NAS Synology DS218+
The errors that I found were : 
Configuring gitlab::database
ERROR:
  Please configure the database connection.
  Refer http://git.io/wkYhyA for more information.
  Cannot continue without a database. Aborting...

Of course the synology_gitlab_postgresql container has been started

Any suggestion to resolve this issue?

**Comment by icedream** [comment]
Sounds like no environment variable values are set for the GitLab container to be able to find the database, though it is weird for it to happen suddenly after an update.

**Comment by DROMZEE** [comment]
I am dependent on package manager provided by synology.
They update slowly (only every two years)
Docker is also obsolete. 
It seems too risky to continue using this NAS as a repository. 
In the meantime I use gitab.com
