### ISSUE TITLE
sameersbn/gitlab:12.0.1 not found

### ISSUE THREAD

**Issue by danielschlegel** [sameersbn/docker-gitlab#1960]
I think there is an issue with autobuild on https://hub.docker.com/r/sameersbn/gitlab 
Latest version shown on docker hub is 11.8.0.

I see there should be 12.0.1 available.

docker pull sameersbn/gitlab:12.0.1
Error response from daemon: manifest for sameersbn/gitlab:12.0.1 not found

**Comment by solidnerd** [comment]
Hey,
I think this can be closed because 12.0.3 is out and available also your requested version is available on the docker hub. I think it was a timing problem.

**Comment by danielschlegel** [comment]
I still see 11.8.0 as on https://hub.docker.com/r/sameersbn/gitlab/

**Comment by danielschlegel** [comment]
But now i can pull other versions. e.g. 12.0.1 and 12.0.3
