### ISSUE TITLE
fatal: git fetch-pack: expected shallow

### ISSUE THREAD

**Issue by cyklodev** [sameersbn/docker-gitlab#1968]
I just notice that my gitlab-runner stop working after upgrade gitlab image to 12.0.0 (centos 7).

`Running with gitlab-runner 12.1.0 (de7731dd)
  on gitlab-runner-shell UsRs12q
Using Shell executor...
Fetching changes with git depth set to 50...
Reinitialized existing Git repository in /home/gitlab-runner/builds/UsRs12q/0/group/project/.git/
fatal: git fetch-pack: expected shallow list
fatal: The remote end hung up unexpectedly`

Similar to [Issue 60466](https://gitlab.com/gitlab-org/gitlab-ce/issues/60466) but on gitlab 12.0.0 and gitlab-runner 12.1.0 . 

The fix is to upgrade git in 2.X , Instruction for Centos 7 below

`git --version
git version 1.8.3.1
yum remove git*
yum -y install  https://centos7.iuscommunity.org/ius-release.rpm
yum -y install  git2u-all
git --version
git version 2.16.5`

To bad that the upgrading section of the readme didn't warn about that.

**Comment by solidnerd** [comment]
Hey @cyklodev,

I think you aren't using this image in the image is the latest git version available. Here is a screenshot of an version from `12.0.3` .

![image](https://user-images.githubusercontent.com/886383/62848770-469d0280-bcdd-11e9-9dd0-6064fff622f7.png)

**Comment by Th3ABombs** [comment]
@cyklodev you saved my day!

**Comment by Andrey2G** [comment]
Just getting the same issue, but everything is fine with versions.
This is what helped me
variables
GIT_STRATEGY: clone
