### ISSUE TITLE
Documentet 12.0.4 is not on docker-hub

### ISSUE THREAD

**Issue by xeor** [sameersbn/docker-gitlab#1969]
As title sais... Is there any delays, did the build-job fail, or is the doc wrong? :)

https://hub.docker.com/r/sameersbn/gitlab/tags

**Comment by solidnerd** [comment]
Hey,
something went wrong with the publishing. It doesn't added an github release for this case. Only the git tag exists. I'll figure out why and bring them back.

**Comment by MRigal** [comment]
@solidnerd are you sure to have pushed the git tag? Can't see it here... 
https://github.com/sameersbn/docker-gitlab/tags

**Comment by solidnerd** [comment]
@MRigal thanks for pointing this out. I think some local tags missing here but the image is available on the docker hub https://hub.docker.com/r/sameersbn/gitlab/tags. 

I pushed the missing parts back. So it is also available here.
