### ISSUE TITLE
looking forward to upgrade to 12.2 

### ISSUE THREAD

**Issue by chenjie4255** [sameersbn/docker-gitlab#1985]
version 12.2 include advanced filter expression which I have expected for a long time, and I refresh this repo more than five times per day to check if it was updated [cry], so it will be kind of you for an updating.

**Comment by danyill** [comment]
I guess we're all after the latest and greatest features. 

But open source is more about community effort than "having other people develop free software for you". If you can't contribute code you can always donate to the project or try and create a merge request based on the previous examples.

Gitlab 12.2 was released only 4 days ago... IMHO @solidnerd and @sameersbn do a good job tracking releases (they too are allowed holidays) and a few extra days to allow things to stabilise and for them to find time to look at this would be the minimum reasonable expectation.

If you need or want a faster moving release then then I'd suggest looking at the Omnibus edition of Gitlab on [Docker Hub](https://hub.docker.com/r/gitlab/gitlab-ce/) (see also the [docs](https://docs.gitlab.com/omnibus/docker/))

**Comment by solidnerd** [comment]
The update will happen today and followed by the patch release so stay tuned.

**Comment by chenjie4255** [comment]
I am sorry for the inconvenience may I caused to you, I truly didn't mean to.

As far as I see in this readme file which says this repo would be upgraded almost immediately after the official release was made, that is the only reason I came here to see if there is something wrong.  I never take any open source project as granted, and it is just a kind reminder.
