### ISSUE TITLE
12.2.1 Image not pushed to Docker hub

### ISSUE THREAD

**Issue by johnmccabe** [sameersbn/docker-gitlab#1988]
Hey, just a heads up that the 12.2.1 image hasn't pushed to Docker hub, only the 12.2.0 release is up there currently.

Thanks for all the hard work on keeping the project so awesome !

**Comment by solidnerd** [comment]
Hey @johnmccabe,
I retriggered the deployment and tested it. Everything should be there now. Thanks for pointing this out.
