### ISSUE TITLE
I can't login as admin to gitlab

### ISSUE THREAD

**Issue by enagora** [sameersbn/docker-gitlab#2002]
Documentation says that admin account uses admin@example.com and 5iveL!fe password but these data return error.
I'm doing something wrong?

Thanks

Redited--
 I solved with these steps

	1. docker exec -it GITLAB_CONTAINER_ID /bin/bash
	2. su - git
	3. cd gitlab
	4. bundle exec rails c production
	5. User.where(id: 1).first.password = 'NEW_PASS'
	6. User.where(id: 1).first.password_confirmation = 'NEW_PASS'
	7. User.where(id: 1).first.save
	8. exit

**Comment by se7vet** [comment]
hi , i have the same problem  you . I with these steps.  
`
[root@gitlab ~]# 
[root@gitlab ~]# docker exec -it gitlab_gitlab_1  bash
root@9aa82ff8db65:/home/git/gitlab# 
root@9aa82ff8db65:/home/git/gitlab# su - git
git@9aa82ff8db65:~$ cd gitlab
git@9aa82ff8db65:~/gitlab$ bundle exec rails c production
Traceback (most recent call last):
        15: from bin/rails:4:in `<main>'
        14: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:325:in `require'
        13: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:291:in `load_dependency'
        12: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:325:in `block in require'
        11: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        10: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
         9: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
         8: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
         7: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
         6: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/commands.rb:18:in `<main>'
         5: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/command.rb:46:in `invoke'
         4: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/command/base.rb:69:in `perform'
         3: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         2: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         1: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/commands/console/console_command.rb:95:in `perform': wrong number of arguments (given 1, expected 0) (ArgumentError)
        16: from bin/rails:4:in `<main>'
        15: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:325:in `require'
        14: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:291:in `load_dependency'
        13: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:325:in `block in require'
        12: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        11: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        10: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
         9: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
         8: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
         7: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/commands.rb:18:in `<main>'
         6: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/command.rb:46:in `invoke'
         5: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/command/base.rb:69:in `perform'
         4: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         3: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         2: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:20:in `run'
         1: from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:34:in `rescue in run'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:506:in `handle_argument_error': ERROR: "rails console" was called with arguments ["production"] (Thor::InvocationError)
Usage: "rails console [options]"
git@9aa82ff8db65:~/gitlab$ 
`
i dont`t how to do . please help me .
