### ISSUE TITLE
We still use 12.2.1 version

### ISSUE THREAD

**Issue by tomislater** [sameersbn/docker-gitlab#2003]
https://github.com/sameersbn/docker-gitlab/blob/fc2b7a4bb58422b99ecbb588eee97b36a272868a/Dockerfile#L5

**Comment by solidnerd** [comment]
Hey @tomislater, 

thanks for pointing it out but it's not really true in relation which version is currently out.

When you start `sameersbn/gitlab:12.2.5` you will receive this version also.

![image](https://user-images.githubusercontent.com/886383/65051532-8eace600-d969-11e9-9128-dae7b5f63ea0.png)

The `ARG` is only a placeholder for version and can be overriden by `docker image build --build-arg VERSION=12.2.5`

Your fix is correct but the version `12.2.5` is also out.

**Comment by tomislater** [comment]
Ahh, I see. Thanks!

**Comment by solidnerd** [comment]
Yep. But your mr was good because it was missing for the default case ;)
