### ISSUE TITLE
Setting up behind a reverse proxy for ssl

### ISSUE THREAD

**Issue by kabengwa** [sameersbn/docker-gitlab#2017]
Is there an example of yml file to have this set up behind a reverse proxy ... i have setup the reverse proxy with the jwilder/nginx-proxy:0.7.0 and it works fine woth everything else... i am just not sure i found some documentation on how to set this up behind such a proxy so that a domain with ssl is added to the git setup ..

Note: when i set it up with just the ports it works just fine .. but now i want tp add a domain to it to make is easier to work with. 

Any help is welcome.

`version: '2'
services:
  web:
    image: nginx
    container_name: gitlab_webserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - gitlab
    volumes_from:
      - gitlab
    environment:
      - VIRTUAL_HOST=de.gitlab.xx.com
      - VIRTUAL_NETWORK=tb_internal_network
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=dev.gitlab.xx.com
      - LETSENCRYPT_EMAIL=xx@yyy.com
    networks:
      - _internal_network
    restart: unless-stopped
  redis:
    restart: always
    image: sameersbn/redis:4.0.9-3
    container_name: gitlab_redis
    command:
      - --loglevel warning
    volumes:
      - ./gitlab_files/redis:/var/lib/redis
    networks:
      - _internal_network
  postgresql:
    restart: always
    image: sameersbn/postgresql:10-2
    container_name: gitlab_postgresql
    volumes:
      - ./files/postgresql:/var/lib/postgresql
    environment:
      - DB_USER=user
      - DB_PASS=Pass
      - DB_NAME=gitlabhq_production
      - DB_EXTENSION=pg_trgm
    networks:
      - _internal_network
  gitlab:
    image: sameersbn/gitlab:12.3.1
    container_name: gitlab_server
    links:
      - redis
      - postgresql
    ports:
      - "1008:80"
      - "1002:22"
    volumes:
      - ./files/gitlab/config:/etc/gitlab
      - ./files/gitlab/logs:/var/log/gitlab
      - ./files/gitlab/data:/home/git/data
      - ./files/gitlab/opt:/var/opt/gitlab
    environment:
      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASS=pass
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Europe/Berlin
      - GITLAB_TIMEZONE=Europe/Berlin
      - GITLAB_HOST=dev.gitlab.xx.com
      - GITLAB_ROOT_EMAIL=xx@yyy.com

      - GITLAB_SECRETS_DB_KEY_BASE=[i have secrets here]
      - GITLAB_SECRETS_SECRET_KEY_BASE=[i have secrets here]
      - GITLAB_SECRETS_OTP_KEY_BASE=[i have secrets here]
    networks:
      - _internal_network

networks:
  _internal_network:
    external:
      name: _internal_network

`

I have tried this above with this as the nginx file content
`# config file for nginx webserver to work with gitlab app.

user www-data;

events {
  worker_connections 768;
}
http {
  upstream backend {
      server gitlab:1008;
  }
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 80;

    # Add headers to serve security related headers
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;

    root /var/www/html;
    client_max_body_size 0; # 0=unlimited - set max upload size
    fastcgi_buffers 64 4K;

    gzip off;

    index index.php;
    error_page 403 /core/templates/403.php;
    error_page 404 /core/templates/404.php;

    rewrite ^/.well-known/carddav /remote.php/dav/ permanent;
    rewrite ^/.well-known/caldav /remote.php/dav/ permanent;

    location = /robots.txt {
      allow all;
      log_not_found off;
      access_log off;
    }

    location ~ ^/(build|tests|config|lib|3rdparty|templates|data)/ {
      deny all;
    }

    location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
      deny all;
    }

    location / {
      rewrite ^/remote/(.*) /remote.php last;
      rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;
      try_files $uri $uri/ =404;
    }

    location ~ \.php(?:$|/) {
      fastcgi_split_path_info ^(.+\.php)(/.+)$;
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param PATH_INFO $fastcgi_path_info;
      fastcgi_param HTTPS on;
      fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
      fastcgi_pass backend;
      fastcgi_intercept_errors on;
    }

    # Adding the cache control header for js and css files
    # Make sure it is BELOW the location ~ \.php(?:$|/) { block
    location ~* \.(?:css|js)$ {
      add_header Cache-Control "public, max-age=7200";
      # Add headers to serve security related headers
      add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
      add_header X-Content-Type-Options nosniff;
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Robots-Tag none;
      add_header X-Download-Options noopen;
      add_header X-Permitted-Cross-Domain-Policies none;
      # Optional: Don't log access to assets
      access_log off;
    }

    # Optional: Don't log access to other assets
    location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|swf)$ {
      access_log off;
    }
  }

}
`

**Comment by tomastzn** [comment]
I think the environment variables you need in your docker compose file are:
```
GITLAB_HTTPS=true
GITLAB_HOST=dev.gitlab.xx.com
```
With these, but without providing the SSL certificate files, the startup process will realize you are running with SSL termination done on a reverse proxy.
Then in your nginx you will need:
```
server {
  server_name dev.gitlab.xx.com;
  listen 443 ssl;
  location / {
                proxy_set_header X-Forwarded-Ssl on;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://backend;
                proxy_redirect https://$host/ https://$host:$server_port/;
                client_max_body_size 10M;
                proxy_buffer_size 8k;
                gzip off;
     }
}
```
The SSL parameters were left out for readability, however, you need them, you don't want to be serving up your gitlab on HTTP (unencrypted connection).
Also, remove all that other stuff from your "server" section for gitlab.
