### ISSUE TITLE
gitlab root welcome page didn't load images

### ISSUE THREAD

**Issue by omidabc** [sameersbn/docker-gitlab#2040]
images didnt load and i dont know why!!!!
![image](https://user-images.githubusercontent.com/49809655/68113796-ca940e80-ff09-11e9-8198-eda5138faccc.png)

i just clone the repository and then i used `docker-compose up`

**Comment by mahmoudshirivaramini** [comment]
Please provide more information. Which GitLab, Redis, and Postgresql version do you use? And did you inspect the browser to detect HTTP/HTTPS error?

**Comment by omidabc** [comment]
i just run this two command

> git clone https://github.com/sameersbn/docker-gitlab.git
> docker-compose up

here are the versions i use 
gitlab:12.4.1
postgresql:10-2
redis:4.0.9-2

![image](https://user-images.githubusercontent.com/49809655/68115147-f4026980-ff0c-11e9-8f77-252d6f43473b.png)

**Comment by chawax** [comment]
Same problem for me. Did you find a solution ?
