### ISSUE TITLE
Scheduled backup does not work after upgrading (12.0.3 to 12.2.1-1 and after upgrading 12.2.1-1 to 12.4.2) 

### ISSUE THREAD

**Issue by timureh** [sameersbn/docker-gitlab#2044]
after upgrading from version 12.0.3 to 12.2.1-1 (27.08.2019)
daily backup does not work (settings for backup in the docker-compose file look like this: 
- GITLAB_BACKUP_SCHEDULE=daily
- GITLAB_BACKUP_TIME=03:00
- GITLAB_BACKUP_EXPIRY=86500 )
postgres not in container
there is nothing in the logs (docker-compose logs, /var/log/posgres.log) that would allow diagnosing the problem
what could be the problem?
update gitlab?

**Comment by tomaaron** [comment]
- Check your if there is a cronjob on the container `runuser -l git -c 'crontab -l'`
- Check if you find backup part in `/home/git/gitlab/config/gitlab.yml`
Are you running multiple containers of gitlab?

**Comment by timureh** [comment]
really, my cronjob look outdated:
`00 03 * * * /bin/bash -l -c 'cd /home/git/gitlab && bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production'`

my docker-gitlab version is 12.2.1-1
in official documentation said:

> Note For GitLab 12.1 and earlier, use gitlab-rake gitlab:backup:create.

command in container:
`find /usr/ -name gitlab-backup`
finds nothing

in the hours of least load I will try to perform:
`docker exec -t <container name> gitlab-backup create`

thanks!

**Comment by timureh** [comment]
yes, there is no new binary in my container =(
`OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"gitlab-backup\": executable file not found in $PATH": unknown`

**Comment by timureh** [comment]
![image](https://user-images.githubusercontent.com/51699692/69038482-b53fd980-0a0b-11ea-802c-4913c79d1d42.png)
Updated its installation but cronjob still looks old and there is no binary in the new container...
Does everything work for the others?

**Comment by timureh** [comment]
![image](https://user-images.githubusercontent.com/51699692/69149561-93705080-0af8-11ea-9f4b-70f5d6897820.png)
when I try to run a command from cron I get pg_dump version mismatch

**Comment by timureh** [comment]
rebuilt the image and included the 12 version postgresql-client.
working.
