### ISSUE TITLE
a problem arise when i try to up gitlab by docker-compose

### ISSUE THREAD

**Issue by bruse-peng** [sameersbn/docker-gitlab#2051]
a problem arise when i try to up gitlab by docker-compose with external postgresql,now i can solve the problem

![image](https://user-images.githubusercontent.com/47881861/69945848-62931100-1525-11ea-9b6a-b1b113d349f5.png)

**Comment by bruse-peng** [comment]
below is my docker yaml
[root@pe-gitlab-vpc compose-file]# cat docker-compose.yml 
web:
  image: 'gitlab/gitlab-ce:12.4.5-ce.0'
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.example.com'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '80:80'
    - '443:443'
    - '8822:22'
  volumes:
    - '/usr/local/gitlab-docker/gitlab/config:/etc/gitlab'
    - '/usr/local/gitlab-docker/gitlab/logs:/var/log/gitlab'
    - '/usr/local/gitlab-docker/gitlab/data:/var/opt/gitlab'
[root@pe-gitlab-vpc compose-file]#

**Comment by vl-bwalocha** [comment]
Hi @bruse-peng , you are using gitlab/gitlab-ce:12.4.5-ce.0 and this repo is about sameersbn/gitlab:latest.
Try to turn off letsencrypt['enable'] param in your gitlab.rb by setting it to 'false'.

cheers!
