### ISSUE TITLE
readiness health check fails after upgrading from 12.4.2 to 12.5.2

### ISSUE THREAD

**Issue by thomasf** [sameersbn/docker-gitlab#2058]
I don't know if this is an upstream issue or not but health check returns this after the upgrade. The gitlab admin UI says that its working as expected and I can't see that anything actually is wrong with the install.

```js
{
status: "failed",
master_check: [
{
status: "failed",
message: "unexpected Master check result: false"
}
]
}
```

**Comment by thomasf** [comment]
Hmm adding the &all=1 to the check returns this which seems weird.

```json
{
  "status": "failed",
  "master_check": [
    {
      "status": "failed",
      "message": "unexpected Master check result: false"
    }
  ],
  "db_check": [
    {
      "status": "ok"
    }
  ],
  "redis_check": [
    {
      "status": "ok"
    }
  ],
  "cache_check": [
    {
      "status": "ok"
    }
  ],
  "queues_check": [
    {
      "status": "ok"
    }
  ],
  "shared_state_check": [
    {
      "status": "ok"
    }
  ],
  "gitaly_check": [
    {
      "status": "ok",
      "labels": {
        "shard": "default"
      }
    }
  ]
}
```

**Comment by thomasf** [comment]
I restarted the gitlab container and not it seems to be killing and restarting nginx constantly

```
gitlab_1             | 2019-12-10 15:05:44,525 INFO exited: nginx (exit status 1; not expected)
gitlab_1             | 2019-12-10 15:05:44,660 INFO spawned: 'nginx' with pid 1042
gitlab_1             | 2019-12-10 15:05:45,678 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1             | 2019-12-10 15:05:47,180 INFO exited: nginx (exit status 1; not expected)
gitlab_1             | 2019-12-10 15:05:47,233 INFO spawned: 'nginx' with pid 1043
gitlab_1             | 2019-12-10 15:05:48,240 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1             | 2019-12-10 15:05:49,752 INFO exited: nginx (exit status 1; not expected)
gitlab_1             | 2019-12-10 15:05:50,067 INFO spawned: 'nginx' with pid 1044
gitlab_1             | 2019-12-10 15:05:51,089 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1             | 2019-12-10 15:05:52,592 INFO exited: nginx (exit status 1; not expected)
gitlab_1             | 2019-12-10 15:05:53,437 INFO spawned: 'nginx' with pid 1045
```

This did not occur before I restarted.

**Comment by thomasf** [comment]
I can't find anything in the gitlab logs that hints at whats wrong.. I don't have time to dig in this more right now so I'm just removing the readiness check from our monitoring and leaving this issue open   until I have time to return to it.

**Comment by tomaaron** [comment]
I can confirm the readinessprobe bug but I think it has nothing to do with your constant respawning nginx process. Maybe someone finds time to update the container to 12.5.3/4 and see if the error still occurs.

**Comment by thomasf** [comment]
I spent a couple of hours trying to find something that wasn't working or what the message even means at all and could not find anything. 

We only use gitlab for git and issues at work so maybe it's one of the features we are not using that not ready internally or something.

I didn't find anything interesting in the upstream issue tracker except this issue that seems to be suggesting that they might be thinking about removing readiness check https://gitlab.com/gitlab-org/gitlab/issues/34238  

I am not using readiness or liveness checks for any load balancer routing desicions, we just monitor the URLs of our single gitlab instance with Prometheus blackbox exporter. I have just commeted out the readiness check from prometheus for now since I don't understand why it is failing.. I'll try to remember to check it next time I upgrade gitlab and report back here.

**Comment by EugRomanchenko** [comment]
Good afternoon. We also encountered a similar problem after updating GitLab. Judging by these changes (https://gitlab.com/gitlab-org/gitlab-foss/commit/90a06a20be61bb6d48d77746091492831153e075#d2c9d1578c42c9953349e1dd32a689136a5d0f3e), a check of the state of the master node in the GitLab Cluster configuration has been added in recent versions. And it is precisely in the case of an unconfigured cluster that leads to an error in readiness health check. As a workaround, we switched to liveness healthcheck endpoint.

**Comment by smartbit** [comment]
I had the same issue that `/-/readiness` started failing and had to remove the `readinessProbe`. 
[Kubernetes 1.16](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md) added a [startupProbe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes). I'm considering adding `StartupProbe` and wonder what would be good values for both `livenessProbe` and `startupProbe` using Gitlab 12.6.3?
```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/liveness
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /-/health
            port: 80
            scheme: HTTP
          failureThreshold: 30
          periodSeconds: 10
```
On my cluster I noticed that pulling from gcr.io, starting. upgrading 12.5.5 --> 12.6.3, etc took around 5min = 30 * 10sec. Do above combination of values make sense? Suggestions?

**Comment by adrb** [comment]
I recently had similar problem, so I just leave description for someone passing by this thread like I did ;)

In my case problem was initiated by lack of disk space. After removing some backups and services restart, everything seems fine beside master_check. As it turns out, puma service orphaned it's worker processes. So the solution was to stop puma service, manually kill orphaned processes and start puma.
