### ISSUE TITLE
Sendmail

### ISSUE THREAD

**Issue by msteinert** [sameersbn/docker-gitlab#208]
This is more of a question than an issue. I found your instructions for using config overrides and that part worked great. Next I added sendmail to my image and started it in the init script (msteinert/docker-gitlab@edf390b113530ba4d1adedfe3c5e379931158bbf). Is there a better way to do this?

I suspect this change is too specialized to add to your base configuration. Perhaps there might be some way to add a sendmail configuration variable and use that to decide whether or not to start sendmail?

Cheers!

**Comment by sameersbn** [comment]
@msteinert should we close this issue?

**Comment by msteinert** [comment]
Sorry, I forgot about this. The solution suggested by @skython worked perfectly.
