### ISSUE TITLE
ArgumentError: 'import/{{oauth2_generic_name}}' is not a supported controller name.

### ISSUE THREAD

**Issue by achretien** [sameersbn/docker-gitlab#2101]
When an oAuth is configured (Azure in our case) the config file is wrongly generated.

There is no else case to remove the unused generic oauth part

https://github.com/sameersbn/docker-gitlab/blob/2ea27eef8139b3be0d7cb13f96fae183c0e6e7c0/assets/runtime/functions#L616

**Comment by raphaelyancey** [comment]
I'm experiencing the same problem.

**Comment by f-io** [comment]
same here with google.

after upgrading from 12.7.7 to 12.7.8 gitlab will fail to start as long as the config contains google_oauth2 settings.

#OAUTH

OAUTH_ENABLED=true
OAUTH_ALLOW_SSO=google_oauth2
OAUTH_GOOGLE_API_KEY=xxxxxxxx.apps.googleusercontent.com
OAUTH_GOOGLE_APP_SECRET=xxxxx
OAUTH_GOOGLE_RESTRICT_DOMAIN=DOMAIN.com
OAUTH_BLOCK_AUTO_CREATED_USERS=false
OAUTH_AUTO_LINK_LDAP_USER=true

`gitlab | ArgumentError: 'import/{{oauth2_generic_name}}' is not a supported controller name. This can lead to potential routing problems. See http://guides.rubyonrails.org/routing.html#specifying-a-controller-to-use`

**Comment by achretien** [comment]
@solidnerd before releasing 12.8 you should look at this issue there a missing else case and an extra line break in the template. 

I can’t send a pull request on my phone but it is easily to correct before new releases

**Comment by solidnerd** [comment]
I did already a fix. I think I didn’t had pushed it 😅

Aurélien Chretien <notifications@github.com> schrieb am Sa. 28. März 2020
um 19:56:
