### ISSUE TITLE
v12.9.2 README.md not rendering

### ISSUE THREAD

**Issue by echeeng** [sameersbn/docker-gitlab#2122]
Is there an option that I missed? Not sure if this is particular to 12.9.2 as I just moved from omnibus official to testing 12.9.2 from here.

I was expecting the content of a project's README.md to be automatically rendered on the landing page but it is currently appearing as a link with text 'README.md' instead of displaying its content.

**Comment by werty1st** [comment]
I have the same problem with gitlab/gitlab-ce:12.9.4-ce.0.
I moved the installation from an old server and had some other problem so i thought it's my fault.

**Comment by werty1st** [comment]
its not a bug of this repo. i think its because of this: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/32616

with "HTTPS Everywhere" the readme renders. i checked my external_url and it was http instead of https. after changing that the problem was solved for me.

**Comment by sameersbn** [comment]
thanks for info @werty1st
