### ISSUE TITLE
upgrade gitlab to 12.9.4

### ISSUE THREAD

**Issue by woodsmur** [sameersbn/docker-gitlab#2128]
A patch version comes out with a few bugs fixed. https://about.gitlab.com/releases/2020/04/20/gitlab-12-9-4-released/

Any plan to upgrade to this patch release?

**Comment by sachilles** [comment]
A patch release (version 12.10.1) was already published (see <https://about.gitlab.com/releases/2020/04/24/gitlab-12-10-1-released/>).

**Comment by woodsmur** [comment]
Yep. According to the [upgrade doc](https://docs.gitlab.com/ce/update/),  you should take care when doing an upgrade. Anyone knows if there's any guideline on how to choose gitlab version when doing an upgrade and make sure that version works, without backing up and restoring the database when upgrade fails.

**Comment by sameersbn** [comment]
https://github.com/sameersbn/docker-gitlab/releases/tag/12.9.5 is available now.
we're working on a 12.10 release and will update it's status in https://github.com/sameersbn/docker-gitlab/issues/2130. Thanks for the patience.
