### ISSUE TITLE
Any plan for 12.10 release ?

### ISSUE THREAD

**Issue by paolomainardi** [sameersbn/docker-gitlab#2130]
Hello @solidnerd are there any plans to have the updated image ?

Thanks!

**Comment by paolomainardi** [comment]
ping @solidnerd

**Comment by sameersbn** [comment]
Hi. I'll take a look on the weekend. Sorry about the delay

**Comment by paolomainardi** [comment]
No need to sorry about it, just need to know if the project is still alive, thanks a lot @sameersbn

**Comment by sameersbn** [comment]
Hi. Apparently 12.10 needs postgres 11. I will be updating the sameersbn/postgres image to 11 in preparation of this work.

**Comment by paolomainardi** [comment]
hi @sameersbn according to this thread: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/63567 postgresql 9.6 is still supported and it will be deprecated just starting from gitlab 13.x

**Comment by achretien** [comment]
I am running 12.10.4 with Postgres 10 dB image and postgres 11 client package in the gitlab image

**Comment by sameersbn** [comment]
Hi. I've created https://github.com/sameersbn/docker-gitlab/pull/2141 with 12.10.4.
If anyone would like to build and take it for a quick spin it would be really great.

**Comment by beanaroo** [comment]
@sameersbn Initial testing looks good. I also tried 12.10.5 with GITLAB_WORKHORSE_VERSION=8.31.0, GITLAB_PAGES_VERSION=1.18.0 and GITALY_SERVER_VERSION=12.10.5.

I haven't confirmed if pages work, though.

**Comment by solidnerd** [comment]
I'll gonna close this in favor of `13.0.0`
