### ISSUE TITLE
Gitlab: 13.0.0 Pages Deamon error

### ISSUE THREAD

**Issue by GJRTimmer** [sameersbn/docker-gitlab#2155]
Pages daemon with version 13.0.0 has several problems.

Error from `gitlab-pages.log`

```bash
level=fatal msg="Using invalid arguments, use -config=gitlab-pages-config file instead" error="invalid command line arguments: -auth-client-id, -auth-client-secret, -auth-secret"
```

Anyone any clue ?

**Comment by solidnerd** [comment]
@GJRTimmer  Could be something related to https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/functions#L1684

**Comment by ttphi88** [comment]
Hi, I'm also having this issue.

After checking gitlab document, it seems that those params `-auth-client-id, -auth-client-secret, -auth-secret` was replaced by `gitlab-pages-config` since 12.8
ref: https://docs.gitlab.com/ee/administration/pages/source.html#access-control
