### ISSUE TITLE
Permission issue when migrating PostgreSQL 10 to 11

### ISSUE THREAD

**Issue by jirsbek** [sameersbn/docker-gitlab#2156]
Today I've decide to upgrade PostgreSQL 10 to 11 as was suggested in GitLab admin area notification (was using sameersbn/postgresql:10-2).

In my `docker-compose.yml` I've change PostgreSQL image to sameersbn/postgresql:11-20200524 but after `docker-compose up` I've got following permissions error (from bottom to top):

```
2020-05-25 16:45:03 | stderr | child process exited with exit code 1
-- | -- | --
2020-05-25 16:45:03 | stderr | 2020-05-25 16:45:03.548 UTC [1390] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
2020-05-25 16:45:03 | stderr | 2020-05-25 16:45:03.548 UTC [1390] FATAL:  data directory "/var/lib/postgresql/11/main" has invalid permissions
2020-05-25 16:44:56 | stderr | debconf: delaying package configuration, since apt-utils is not installed
2020-05-25 16:44:28 | stdout | ‣ Installing PostgreSQL 10...
2020-05-25 16:44:28 | stdout | ‣ Migrating PostgreSQL 10 data to 11...
```

I've tried to create the folder manually with correct permissions, I've added "z" to volume mapping `- volumes: ./postgresql:/var/lib/postgresql:z` but both attempts failed.

**Comment by solidnerd** [comment]
Hey, there was a discussion about how to migrate you can check this out: https://github.com/sameersbn/docker-gitlab/pull/2154#issuecomment-633497099

**Comment by jirsbek** [comment]
Unfortunately only folder in my postgresql volume is `10` so I'm affraid referenced issue doesn't apply to my issue 😕

During upgrade the folder `10` is renamed to `10.migrating` and the folder is `11` created.

**Comment by MatthiasHertel** [comment]
@jirsbek 

try the following:

```
chown -R 101:103 /path/to/mounted/postgresql
```


see this comment before my mounted dir it has other permissions:
https://github.com/sameersbn/docker-gitlab/pull/2154#issuecomment-634229651

i guess during upgrade the permission changes:

from:
```
$ /srv/docker/gitlab/postgresql
total 12
drwxr-xr-x 3 syslog syslog 4096 Jun 12  2018 ./
drwxr-xr-x 7 root   root   4096 Jun 18  2018 ../
drwx------ 3 syslog syslog 4096 Jun 12  2018 9.6/
$ id syslog
uid=102(syslog) gid=106(syslog) groups=106(syslog),4(adm)
```
to:
```
$ ll /srv/docker/gitlab/postgresql/
total 24
drwxr-xr-x 4 systemd-resolve systemd-resolve 4096 May 26 22:02 ./
drwxr-xr-x 7 root            root            4096 Jun 18  2018 ../
drwx------ 3 systemd-resolve systemd-resolve 4096 May 26 22:02 11/
drwx------ 3 systemd-resolve systemd-resolve 4096 Jun 12  2018 9.6/
-rwx------ 1 systemd-resolve systemd-resolve  771 May 26 22:02 analyze_new_cluster.sh*
-rwx------ 1 systemd-resolve systemd-resolve   49 May 26 22:02 delete_old_cluster.sh*
$ id systemd-resolve 
uid=101(systemd-resolve) gid=103(systemd-resolve) groups=103(systemd-resolve)
```

**Comment by jirsbek** [comment]
Thank you @MatthiasHertel for your tip, but no luck. `postgresql` folder already had those permissions: 

```
root@DS218plus:/volume1/docker/gitlab# ls -la
total 28
drwxr-xr-x+  5 admin users 4096 May  3 21:18 .
drwxr-xr-x+  5 root  root  4096 May 25 20:06 ..
-rwxr-xr-x+  1 admin users 1659 May 27 09:29 docker-compose.yml
drwxrwxrwx+  2 root  root  4096 May 25 19:39 @eaDir
drwxr-xr-x  11  1000  1000 4096 Dec 28  2018 gitlab
drwxr-xr-x+  3   101   103 4096 May 26 09:41 postgresql
root@DS218plus:/volume1/docker/gitlab# chown -R 101:103 postgresql
root@DS218plus:/volume1/docker/gitlab# ls -la
total 28
drwxr-xr-x+  5 admin users 4096 May  3 21:18 .
drwxr-xr-x+  5 root  root  4096 May 25 20:06 ..
-rwxr-xr-x+  1 admin users 1659 May 27 09:29 docker-compose.yml
drwxrwxrwx+  2 root  root  4096 May 25 19:39 @eaDir
drwxr-xr-x  11  1000  1000 4096 Dec 28  2018 gitlab
drwxr-xr-x+  3   101   103 4096 May 26 09:41 postgresql
root@DS218plus:/volume1/docker/gitlab# 
```

**Comment by jirsbek** [comment]
I've got to correct my statement, I believe I've got lucky at last.

Correct CHMOD (0700) and CHOWN 101:103 (thanks @MatthiasHertel) on following folders probably did the trick:
```
path/to/postgresql
path/to/postgresql/10 // Latest version
path/to/postgresql/10/main
```

**Comment by johnmccabe** [comment]
The issue I had were due to files in the postgres volume having ACLS, doing an `ls` you could see them with the `+` after the permissions.
```
3014858 4 drwxr-xr-x+ 19 101 103 4096 May 27 23:47 main
```
Running the `chmod -R 0700` on the postgre volume then did the trick.
I didn't have to `chown` anything as all files were already owned by `101:103`.
