### ISSUE TITLE
Postgres update causes 500 (10.9 => 11/12)

### ISSUE THREAD

**Issue by mash1t** [sameersbn/docker-gitlab#2158]
I'm currently experiencing an issue with migrations after bumping the postgresql version from sameersbn/postgresql:10-2 to sameersbn/postgresql:12-20200524. Migrating causes the db to not find a column, so i assumed it had to do with migrations.

> postgresql_1  | 2020-05-25 21:55:25.381 UTC [124] ERROR:  column projects.pool_repository_id does not exist at character 2072

When running `sudo -u git -H bundle exec rake --trace db:migrate RAILS_ENV=production` i encounter the output 

> root@c9de40947e9c:/home/git/gitlab# sudo -u git -H bundle exec rake --trace db:migrate RAILS_ENV=production
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Invoke schema_version_check (first_time)
** Invoke environment
** Execute schema_version_check
rake aborted!
**Your current database version is too old to be migrated. You should upgrade to GitLab 11.11.0 before moving to this version. Please see https://docs.gitlab.com/ee/policy/maintenance.html#upgrade-recommendations**
/home/git/gitlab/lib/tasks/migrate/schema_check.rake:13:in `block in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:236:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:236:in `invoke_prerequisites'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/bin/rake:23:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate => schema_version_check

Checking migration status with `sudo -u git -H bundle exec rake --trace db:migrate:status RAILS_ENV=production` shows missing migrations starting at

>   down    20180115094742  Add default project creation setting
  down    20180115113902  Add project creation level to groups

Going back to 11.11.0 doesn't work either because Gitlab won't start anymore (sth. like "already migrated"). Also the Gitlab backups could potentially not be imported into a fully migrated database after setting up a fresh Gitlab volume + db due to not being compatible with tables due to already applied migrations...

As i assume that this issue does not only affect me:

**How can one handle this situation?**

**Comment by jirsbek** [comment]
I believe this issue is discussed here https://github.com/sameersbn/docker-gitlab/pull/2154#issuecomment-633497099

**Comment by solidnerd** [comment]
Hey @mash1t,
so far what I know is that GitLab doesn't support Postgres 12.X at the moment. There as already an discussion on this: https://github.com/sameersbn/docker-gitlab/issues/2121

**Comment by mash1t** [comment]
@jirsbek thank you for the hint, much appreciate it.
After deleting /var/lib/postgresql/9.6 the container automatically migrated PostgreSQL 10 data on startup to PostgreSQL 11.
