### ISSUE TITLE
Gitlab backup fail after upgrade PostgreSQL 10 to 11 

### ISSUE THREAD

**Issue by nickbug** [sameersbn/docker-gitlab#2160]
After upgrade PostgreSQL 10 to 11, the gitlab backup fail with error  

"**pg_dump version mismatch**"

> ** Execute gitlab:backup:db:create
2020-05-26 17:22:39 +0800 -- Dumping database ...
Dumping PostgreSQL database gitlabhq_production ... pg_dump: server version: 11.8 (Ubuntu 11.8-1.pgdg18.04+1); pg_d                                       ump version: 10.13 (Ubuntu 10.13-1.pgdg18.04+1)
pg_dump: aborting because of server version mismatch
[FAILED]
rake aborted!
Backup::Error: Backup failed

**Comment by solidnerd** [comment]
Hey @nickbug,
it will be available for the short term in `sameersb/gitlab:latest` image and later in the next release. Thanks for reporting it. I'll gonna close this if you Issue still persists please reopen this issue.
