### ISSUE TITLE
since 13.0.0: can't view plaintext files via https anymore

### ISSUE THREAD

**Issue by TimB87** [sameersbn/docker-gitlab#2170]
Hi,
I have no idea what's going wrong tbh - i was upgrading from 11.8.0 by making steps through 12.x.x up to 13.0.0 - everything went fine that way but i noticed some time later that I am unable to view plaintext files by browsing the git repository from within my browser.
While my standard browser (palemoon, UXP engine) does nothing when I click on a textfile, qutebrowser (chromium engine) redirects me to about:blank.
However, both browsers are able to show the textfile when I append it's name manually to the url. Web IDE works fine as well.. 
Can somebody hint to me where I should look to get this sorted?

**Comment by TimB87** [comment]
Problem persists with 13.0.5 and I still have no idea why..

**Comment by TimB87** [comment]
still persists with 13.0.6 - i flushed redis but that didn't help it

**Comment by TimB87** [comment]
Nobody got an idea? @sameersbn @solidnerd

**Comment by TimB87** [comment]
Problem still persists with 13.2.1

**Comment by solidnerd** [comment]
I can’t reproduce it. Could you provide some more information ?

Tim Biermann <notifications@github.com> schrieb am So. 2. Aug. 2020 um
18:46:

**Comment by TimB87** [comment]
@solidnerd Thanks for getting back at me!

Which information could I provide?

I tried in the meantime: restoring from a backup and looked around inside the containers namespace, but didn't find anything that looked suspicious.

**Comment by TimB87** [comment]
And w/ 13.2.3.. let me know what information could help you, because i have no idea what would w/ docker.

**Comment by TimB87** [comment]
@solidnerd 
So, I just switched to docker-compose and updated to 13.4.2 (from 13.2.4 I think) and it seems like it finally works again. In the process, I needed to install `btree_gist` extension to the pgsql DB, maybe this was it?
Still clueless, but happy that it works again!
