### ISSUE TITLE
12.10.10 support

### ISSUE THREAD

**Issue by smartbit** [sameersbn/docker-gitlab#2174]
Any plans to make a build for [12.10.10](https://about.gitlab.com/releases/2020/06/04/gitlab-12-10-10-released/)? 

BTW thanks for the great work.

**Comment by smartbit** [comment]
On Jun 10, 2020 patch version [12.10.11](https://about.gitlab.com/releases/2020/06/10/critical-security-release-13-0-6-released/) was released.

> #### CI Token Access Control
> An authorization issue discovered in the mirroring logic allowed read access to private repositories. This issue is now mitigated in the latest release and is waiting for a CVE ID to be assigned.

**Comment by solidnerd** [comment]
Hey @smartbit, 
we aren't able to maintain older Major versions. So you need to upgrade to at least 13.0.x to get the latest security patches.
