### ISSUE TITLE
Images broken again after update...

### ISSUE THREAD

**Issue by ninja-** [sameersbn/docker-gitlab#218]
Generated urls are in form: https://example.com/gitlab//gitlab/uploads/user/avatar/1/name.png

and others are generated correctly...why?

**Comment by sameersbn** [comment]
@ninja- can you try with release `7.9.0`. Gitlab have changed their emoji library. Could it have ended up resolving this issue?

**Comment by ninja-** [comment]
yeah I'll check and report back

**Comment by ktwalrus** [comment]
I also am seeing broken images in the Help files:

https://example.com/help/workflow/gitlab_flow.md

Seems like the current directory for the browser is incorrect to resolve the image locations in these .md files.

**Comment by sameersbn** [comment]
@ktwalrus The images in the gitlab docs seem to have been fixed in the upstream. I am running `7.10.0.rc4` and the issue does not exist.
