### ISSUE TITLE
Pages error 502 "Bad Gateway" after upgrade to 13.0.6 

### ISSUE THREAD

**Issue by ay-b** [sameersbn/docker-gitlab#2180]
Hi. 
After upgrade to 13.0.6 from 13.0.1 got 502 Bad Gateway at pages service

Docker logs at start gave me:
```
gitlab_1      | 2020-06-21 18:08:21,290 INFO exited: gitlab-pages (exit status 1; not expected)
gitlab_1      | 2020-06-21 18:08:23,294 INFO spawned: 'gitlab-pages' with pid 880
gitlab_1      | 2020-06-21 18:08:23,312 INFO exited: gitlab-pages (exit status 1; not expected)
gitlab_1      | 2020-06-21 18:08:26,317 INFO spawned: 'gitlab-pages' with pid 885
gitlab_1      | 2020-06-21 18:08:26,334 INFO exited: gitlab-pages (exit status 1; not expected)
gitlab_1      | 2020-06-21 18:08:27,335 INFO gave up: gitlab-pages entered FATAL state, too many start retries too quickly
```

Tried to 777 and kill pages folders recreating them, but no luck. 

UPD: Tried `/usr/local/bin/gitlab-pages -listen-http=0.0.0.0:8090` but gitlab returns 404
UPD2: gitlab-pages log contains only:
```
time="2020-06-21T17:47:11+03:00" level=info msg="GitLab Pages Daemon" revision=c94ba37 version=1.18.0
time="2020-06-21T17:47:11+03:00" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2020-06-21T17:47:11+03:00" level=fatal msg="Using invalid arguments, use -config=gitlab-pages-config file instead" error="invalid command line arguments: -auth-client-id, -auth-client-secret, -auth-secret"
```
UPD3: I have Google SAML auth set up for pages and it's being used — I can't disable it. 

Any hints how to fix it?

**Comment by ay-b** [comment]
I see a PR to fix this issue: https://github.com/sameersbn/docker-gitlab/pull/2177
Please, approve.

**Comment by mmerickel** [comment]
This is affecting me as well. Things were working with 12.10.6 and broken after upgrade to 13.0.6.

**Comment by mash1t** [comment]
Issue can be closed, https://github.com/sameersbn/docker-gitlab/pull/2177 has successfully been merged

**Comment by ay-b** [comment]
yup.
