### ISSUE TITLE
Any plans for 13.1?

### ISSUE THREAD

**Issue by cwildfoerster** [sameersbn/docker-gitlab#2189]
Any plans for the 13.1 release? Seems the last couple of months, releases have been really slow, need any help?

**Comment by flavienbwk** [comment]
@sameersbn already [expressed](https://github.com/sameersbn/docker-gitlab/issues/2104#issuecomment-623289979) his willingness to get help.

**Comment by cwildfoerster** [comment]
Created 2 PRs today.
https://github.com/sameersbn/docker-gitlab/pull/2196
https://github.com/sameersbn/docker-gitlab/pull/2197
