### ISSUE TITLE
Fresh 7.5.1 installation fails due to libdevmapper.so filename mismatch

### ISSUE THREAD

**Issue by keigoi** [sameersbn/docker-gitlab#219]
Hi there,

I found my fresh 7.5.1 installation fails on CentOS 6.6 host.
```shell
$ sudo docker run -it -d -e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=10022' -p 10022:22 -p 10080:80 -v /var/run/docker.sock:/run/docker.sock -v $(which docker):/bin/docker sameersbn/gitlab
Database connection details not specified.
Will try to spin up a new postgresql image with the name postgresql-gitlab.
Please manually configure the database connection in production.
Starting up a new postgresql container...
$ echo $?
127
```

This is due to failure of nested docker invocation in the gitlab container. In the container, you can see:
```shell
root@d7fea951fcc9:/# docker
docker: error while loading shared libraries: libdevmapper.so.1.02: cannot open shared object file: No such file or directory
```
Here libdevmapper.so somehow has slightly different version (1.02 -> 1.02.1).
Creating a symbolic link will solve the isssue.
```shell
root@d7fea951fcc9:/# ln -s /lib/x86_64-linux-gnu/libdevmapper.so.1.02.1 /lib/x86_64-linux-gnu/libdevmapper.so.1.02 && ldconfig
root@d7fea951fcc9:/# docker
Usage: docker [OPTIONS] COMMAND [arg...]

A self-sufficient runtime for linux containers.
...
```

**Comment by xphoon** [comment]
For the benefit of others who may stumble on this thread when having this problem: I was able to fix the problem on my 64bit machine by simply adding -v /usr/lib64/libdevmapper.1.02:/usr/lib/libdevmapper.1.02 to the command line. I briefly tried simply using -v /usr/lib64:/usr/lib (in case there were other problematic libraries) but this created other problems.

**Comment by jdossantos** [comment]
On coreOS, you must add a slightly different option : -v /usr/lib/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02

**Comment by chgangaraju** [comment]
In Fedora 21, I fixed it by adding
`-v /lib64/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02`

**Comment by sameersbn** [comment]
@chgangaraju every distribution/environment seems to require its own quirks. The best resolution to this issue is to purge the docker socket mounting feature and instead use docker-compose/fig or start each container manually.

**Comment by sameersbn** [comment]
for people seeing this issue, can you try the following command and let me know the result

```bash
docker run -it --rm \
-v /var/run/docker.sock:/run/docker.sock \
-v $(which docker):/bin/docker \
-v $(ldconfig -p | grep libdevmapper | awk '{print $4}'):/usr/lib/libdevmapper.so.1.02 \
sameersbn/ubuntu:latest docker ps
```

**Comment by sameersbn** [comment]
@keigoi if the above does not work for you on centos 6.6, the you might have to modify the command to

```bash
docker run -it --rm \
-v /var/run/docker.sock:/run/docker.sock \
-v $(which docker):/bin/docker \
-v $(ldconfig -p | grep libdevmapper.so.1.02.1 | awk '{print $4}'):/usr/lib/libdevmapper.so.1.02.1 \
ubuntu:trusty docker ps
```

**Comment by sameersbn** [comment]
volume mounting the docker binary and socket in the quick start guide has been replaced with manually start of postgresql and redis images or using docker-compose to orchestrate the startup.
