### ISSUE TITLE
Trusted SSL certificate: Git clone not working

### ISSUE THREAD

**Issue by maxclac** [sameersbn/docker-gitlab#2193]
Hello,

I have some SSL certificate problem when I clone:

$ git clone https://localhost:10443/root/bookmarks.git
Cloning into 'bookmarks'...
fatal: unable to access 'https://localhost:10443/root/bookmarks.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

I tried to follow instructions to add this to my trusted SSL certificates but I don't get it right.

Can someone please help me? I am using Linux Mint 19.
Thanks

**Comment by cwildfoerster** [comment]
Possibly not a docker-gitlab problem.

You may try `git -c http.sslVerify=false clone https://localhost:10443/root/bookmarks.git` but the correct solution would be to add your ca certificate to your computers trust store.

```
$ mkdir -p /usr/local/share/ca-certificates/extra
$ cp your-ca-cert.crt /usr/local/share/ca-certificates/extra/your-ca-cert.crt
$ update-ca-certificates
```
