### ISSUE TITLE
How to disable CI

### ISSUE THREAD

**Issue by lingli198343** [sameersbn/docker-gitlab#2195]
I just want it be a local github. I don't need CI. 
But I couldn't find configuration files like gitlab.rb in the mapping volume.  should I change it inside container?

**Comment by kkimurak** [comment]
GitLab is not best for such case (local github without CI). Please use other git hosting software (let me introduce gitea, GitBucket, Gogs, etc... : search with "self hosting gitlab alternatives" for more)

If you really want to use this docker-gitlab without CI, just set `GITLAB_PROJECTS_BUILDS: false`. If you're using `docker-compose`, setting the variable in `docker-compose.yml` works.
Please note that user still be able to change repository setting to enable CI even you turn CI disabled as admin. See [docs.gitlab.com](https://docs.gitlab.com/ee/ci/enable_or_disable_ci.html#site-wide-admin-setting)

**Comment by solidnerd** [comment]
@lingli198343  A better fit could be for your use case could be https://gitea.io/en-us/ .
