### ISSUE TITLE
git push doesn't work with relative url

### ISSUE THREAD

**Issue by thiller2018** [sameersbn/docker-gitlab#2200]
when I try to push changes to my repository (gitlab 13.2.2) with relative url enabled I get Internal API error (404). The log file shows an access to /api/... and not /<relpath>/api.

after removing relative path it works.

where is the relative path missing?

**Comment by smanthe** [comment]
For me it is the same after upgrading to 13.2.2

I receive the following error message when pushing to my repo:

```
Username for 'https://XXXX.net': XXX
Password for 'https://XXXX@XXXX': 
Counting objects: 14, done.
Delta compression using up to 24 threads.
Compressing objects: 100% (14/14), done.
Writing objects: 100% (14/14), 1.26 KiB | 1.26 MiB/s, done.
Total 14 (delta 10), reused 0 (delta 0)
remote: GitLab: Internal API error (404)
To https://XXXXX.git
 ! [remote rejected] 23-improved-distortion-model -> 23-improved-distortion-model (pre-receive hook declined)
error: failed to push some refs to 'https://XXXXXX.git'
```

With 
* sameersbn/postgresql:10, 
* sameersbn/gitlab:13.0.5 
* and sameersbn/redis:4.0.9-1 

everything works fine for me.

**Comment by f-io** [comment]
Did not tried to reproduce it, but I can recommend to use traefik instead, if this is urgent.

- traefik:2.2.1
- sameersbn/gitlab:13.2.2
- sameersbn/postgresql:12
- redis:4.0.14-alpine

**Comment by cwildfoerster** [comment]
Mind sharing your docker-compose.yml / enviornment so i maybe can take a look?

**Comment by thiller2018** [comment]
Hi, I'm using the image from docker hub.

**Comment by cwildfoerster** [comment]
> Hi, I'm using the image from docker hub.

I don't know your configuration, hence enviornment variables (`GITLAB_RELATIVE_URL_ROOT `) so i'm unable to get a "copy" of your installation to investigate.

https://github.com/sameersbn/docker-gitlab#deploy-to-a-subdirectory-relative-url-root

**Comment by thiller2018** [comment]
Ok. I use microk8s. Here is the deployment script;

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image:  sameersbn/gitlab:13.2.2
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Europe/Stockholm
        - name: GITLAB_TIMEZONE
          value: Stockholm
        - name: DEBUG
          value: "true"

        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: P26qS5+Csz50Dkd0DLM2oN9owVBFg0PB
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: KVaMTKLAIElEp0s4L02c1O9JCP0Rfapb
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: nXJJ358Qnci0yF9qpAsLrF2vImaoFR03

        - name: GITLAB_ROOT_PASSWORD
          value: graograman
        - name: GITLAB_ROOT_EMAIL
          value: root@example.com

        - name: GITLAB_HOST
          value: tom-nas2.fritz.box
        - name: GITLAB_PORT
          value: "443"
        - name: GITLAB_SSH_HOST
          value: "tom.nas2"
        - name: GITLAB_SSH_PORT
          value: "1022"
        - name: GITLAB_HTTPS
          value: "true"
        - name: GITLAB_RELATIVE_URL_ROOT
          value: "/gitlab"

        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"

        - name: GITLAB_PAGES_ENABLED
          value: "true"

        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: 01:00
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: gitlab-postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: +BP52QIxpT/flVCMpL3KXA==
        - name: DB_NAME
          value: gitlab_production

        - name: REDIS_HOST
          value: gitlab-redis
        - name: REDIS_PORT
          value: "6379"

        - name: SMTP_ENABLED
          value: "false"
        - name: SMTP_DOMAIN
          value: ""
        - name: SMTP_HOST
          value: ""
        - name: SMTP_PORT
          value: ""
        - name: SMTP_USER
          value: ""
        - name: SMTP_PASS
          value: ""
        - name: SMTP_STARTTLS
          value: "true"
        - name: SMTP_AUTHENTICATION
          value: login

        - name: IMAP_ENABLED
          value: "false"
        - name: IMAP_HOST
          value: imap.gmail.com
        - name: IMAP_PORT
          value: "993"
        - name: IMAP_USER
          value: mailer@example.com
        - name: IMAP_PASS
          value: password
        - name: IMAP_SSL
          value: "true"
        - name: IMAP_STARTTLS
          value: "false"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: ssh
          containerPort: 22
        volumeMounts:
        - mountPath: /home/git/data
          name: data
        livenessProbe:
          httpGet:
            path: /gitlab/users/sign_in
            port: 80
          initialDelaySeconds: 600
          timeoutSeconds: 20
       readinessProbe:
          httpGet:
            path: /gitlab/users/sign_in
            port: 80
          initialDelaySeconds: 600
          timeoutSeconds: 20
      volumes:
      - name: data
        hostPath:
          path: /data/k8s/gitlab/gitlab
          type: DirectoryOrCreate

**Comment by thiller2018** [comment]
to remove potential other errors I run against the clusterid (direct ip of image) with same result.

**Comment by thiller2018** [comment]
I see this entry in  gitlab-workhorse.log:
localhost:8181 ::1 - - [2020/08/10:14:28:25 +0200] "POST /api/v4/internal/allowed HTTP/1.1" 404 37 "" "Go-http-client/1.1" 0

Shouldn't this refer to /gitlab/api/... ?

**Comment by cwildfoerster** [comment]
> I see this entry in gitlab-workhorse.log:
> localhost:8181 ::1 - - [2020/08/10:14:28:25 +0200] "POST /api/v4/internal/allowed HTTP/1.1" 404 37 "" "Go-http-client/1.1" 0
> 
> Shouldn't this refer to /gitlab/api/... ?

I already think i know what could cause the issue. When im back home later i will fire up a new instance and check it.

It may be cause by https://github.com/sameersbn/docker-gitlab/blob/dc698f8456eb98d77d8b706dce93d12970a78109/assets/runtime/config/gitaly/config.toml#L97 ... but the workhorse process is started with the correct backend https://github.com/sameersbn/docker-gitlab/blob/9b612b8a0771bfaa8113f00ec40b32609d348ff6/assets/build/install.sh#L338

**Comment by cwildfoerster** [comment]
Yes, the error was where i expected it, sorry about that. Currently pushing the fix.

**Comment by thiller2018** [comment]
I created an image with your PR and it works for me. Closing this issue,

**Comment by cwildfoerster** [comment]
Glad i could help.
