### ISSUE TITLE
Need a new env to allow package registry

### ISSUE THREAD

**Issue by umputun** [sameersbn/docker-gitlab#2217]
With 13.3 package registry is a part of the [core version](https://about.gitlab.com/releases/2020/08/22/gitlab-13-3-released/#package-registry-now-available-in-core). According to [this doc](https://docs.gitlab.com/ee/administration/packages/index.html#enabling-the-packages-feature) some `/etc/gitlab/gitlab.rb` modification required to enable it.

```
gitlab_rails['packages_enabled'] = true
```

Probably it should be configured with some new ENV var

**Comment by cwildfoerster** [comment]
We're using the installation from source type and its already enabled: https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/config/gitlabhq/gitlab.yml#L322-L323
