### ISSUE TITLE
how to configure "remote storage" when backing up

### ISSUE THREAD

**Issue by datajerk** [sameersbn/docker-gitlab#223]
I noticed this output when doing a manual backup today:

```
Uploading backup archive to remote storage  ... skipped
```

However the docs do no specify how to set this up and what the options are.  Not critical, just curious.

**Comment by stephencooke** [comment]
I noticed this "Uploading backup archive to remote storage  ... skipped"  .  I am currently using a custom script to undertake this.   I fire the rsync at a remote, then pack it as backup, then have the client run an auto restore based on the backup number.   Very keen to see if this option can save me some custom scripts.  when will it available?

**Comment by sameersbn** [comment]
@stephencooke at the moment only uploading to a AWS bucket is configurable. However, you can manually override the `gitlab.yml` configuration stated in my previous comment.
