### ISSUE TITLE
Backup Expiry not working anymore after update 13.3.4 => 13.4.2

### ISSUE THREAD

**Issue by mash1t** [sameersbn/docker-gitlab#2241]
As for the last update something must have affected the backup functionality.
=> backups do not expire anymore, tar-files stay on the server (no auto-cleanup)
=> leads to file system being full and the next backup to not write all data

![Bildschirmfoto 2020-10-12 um 11 14 58](https://user-images.githubusercontent.com/9307310/95728793-38999780-0c7c-11eb-90fb-fd6e97edc7b8.png)

<img width="809" alt="Bildschirmfoto 2020-10-12 um 11 31 41" src="https://user-images.githubusercontent.com/9307310/95730445-8ca57b80-0c7e-11eb-9010-5571765bfdea.png">

Currently i'm using the following config:

```
##### GITLAB backups #####
# ---
# Keep 2 daily backups
GITLAB_BACKUP_SCHEDULE=daily
GITLAB_BACKUP_ARCHIVE_PERMISSIONS=0600
GITLAB_BACKUP_EXPIRY=172800
GITLAB_BACKUP_TIME=02:00
GITLAB_BACKUP_SKIP=artifacts,registry,pages
```

Is this a general problem in Gitlab, the repository or a wrong configuration on my side?

**Comment by bjf893** [comment]
Maybe this solves your problem?
https://gitlab.com/gitlab-org/gitlab/-/issues/18510#note_215007645

**Comment by mash1t** [comment]
@bjf893 thank you for the hint, will give it a go on monday 👍

**Comment by mash1t** [comment]
@bjf893 sorry for the late response, worked like a charm. Thank you!
