### ISSUE TITLE
GITLAB_HOST and GITLAB_PATH not enough behind SSL proxy

### ISSUE THREAD

**Issue by phpwutz** [sameersbn/docker-gitlab#2252]
First i wanted to say thanks for providing this very useful image.

### The issue:
Apparently GITLAB_HOST and GITLAB_PORT do in some cases (i found it on the webIDE feature, server side generated URLs seem to work fine) not lead to correct URL generation.
In the gitlab page source there is a JS injected that goes along the lines of
`window.gon={};gon.api_version="v4";gon.gitlab_url="http://gitlab.myhost.net"`
This leads to all frontend-generated links to go to http instead of https

### My setup:
system nginx takes the https connection, handles certificates, then forwards the request to the docker container.
docker container has GITLAB_PORT set to 80 and GITLAB_HTTPS=false and exposes that to the outside world.

## Idea for a solution:
Apparently, this JS is generated by this file in gitlab: `https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/gon_helper.rb`
which in particular contains 

`gon.gitlab_url             = Gitlab.config.gitlab.url` 

From what I understand, this value could be populated by updating `https://github.com/sameersbn/docker-gitlab/blob/e2d7d726f5530d5d0343cd0ef985e762a47513f3/assets/runtime/config/gitlabhq/gitlab.yml` and adding a new env variable GITLAB_URL that can be passed in docker-compose.

Please let me know if i can help further in fixing this, because i really wanna get those advanced features to work and would hate to have to fork this project.

best regards

**Comment by bjf893** [comment]
Try with GITLAB_HTTPS=true, works for me.

https://github.com/sameersbn/docker-gitlab#using-https-with-a-load-balancer

**Comment by phpwutz** [comment]
Thanks for taking the time to respond.
Unfortunatley, GITLAB_HTTPS does not seem to be working for me. The URL generated for the frontend JS now looks like this: `https://gitlab.myhost.net:80` 
It seems the linked documentation area also assumes a different setup where gitlab is configured to use self-signed SSL (which i don't want and need, because nginx and gitlab are running on the same server and i don't want the extra layer of SSL overhead between nginx and gitlab).

**Comment by vkukk** [comment]
> Thanks for taking the time to respond.
> Unfortunatley, GITLAB_HTTPS does not seem to be working for me. The URL generated for the frontend JS now looks like this: `https://gitlab.myhost.net:80`

I checked my config for Kubernetes and found following comment:
```
# specifying this is necessary even if docs say it's 443 if GITLAB_HTTPS=true
# if not specifying 443 here, it will be filled with tcp://pod_ip_addr:80
GITLAB_PORT=443
```

**Comment by bjf893** [comment]
> Thanks for taking the time to respond.
> Unfortunatley, GITLAB_HTTPS does not seem to be working for me. The URL generated for the frontend JS now looks like this: `https://gitlab.myhost.net:80`

Unset GITLAB_PORT or set to 443, as suggested by vkukk.

> It seems the linked documentation area also assumes a different setup where gitlab is configured to use self-signed SSL (which i don't want and need, because nginx and gitlab are running on the same server and i don't want the extra layer of SSL overhead between nginx and gitlab).

No, it just covers both use cases.

**Comment by phpwutz** [comment]
Thank you both!
`GITLAB_PORT=443` did the trick. 
so for anyone future stumbling over this: the container will *always* expose port 80 and 443, GITLAB_PORT just configures how the links are generated.
