### ISSUE TITLE
Monitoring > Logs menu missing after upgrade to 13.2.6

### ISSUE THREAD

**Issue by QuickJack** [sameersbn/docker-gitlab#2254]
I have upgraded my testing instance from 12.10.6-1 to 13.0.6 and then to 13.2.6. A few days later I noticed, that the Monitoring > Logs menu in the admin area is not shown anymore.

**Comment by QuickJack** [comment]
Even a fresh installation of 13.2.6 or the latest 13.5.3 does not have the Logs menu. Does nobody miss this menu? Is this a bug in sameersbn/docker-gitlab or has this been officially removed in Gitlab 13?

**Comment by kkimurak** [comment]
"Logs" in admin sidebar have been officially removed. Please refer https://gitlab.com/gitlab-org/gitlab/-/issues/209250 and https://gitlab.com/gitlab-org/gitlab/-/merge_requests/30485

**Comment by QuickJack** [comment]
Thanks for clearing up this point. I will close this issue because it's not related to sameersbn/docker-gitlab.
