### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by jonaskac** [sameersbn/docker-gitlab#230]
As always it's nice to have some stats, any thought about adding google analytics to the docker?

Gitlab has the support:
https://gitlab.com/gitlab-org/gitlab-ce/blob/6-1-stable/config/gitlab.yml.example

**Comment by sameersbn** [comment]
@jonaskac yes. it is possible to add the option.

**Comment by jonaskac** [comment]
Sweet! Would be awesome :)...
