### ISSUE TITLE
Configuration parameter for "prevent_ldap_sign_in"

### ISSUE THREAD

**Issue by l00v3** [sameersbn/docker-gitlab#2300]
Hello,
thank you for the amazing project!

It would be very nice to include configuration parameter for "prevent_ldap_sign_in"
https://docs.gitlab.com/ee/administration/auth/ldap/#disable-ldap-web-sign-in

So when LDAP and OIDC are enabled, we only allow LDAP user attribute sync, but login is allowed only through OIDC.

Thank you very much!

**Comment by l00v3** [comment]
Is it possible to do this manually, without configuration parameter? Modifying `gitlab.yml` will not work as is it rewritten. 
Does anybody have a workaround for this situation?
Thank you!

**Comment by sameersbn** [comment]
@l00v3 Could you submit a PR that adds a parameter ?

**Comment by l00v3** [comment]
@sameersbn I don't want to be rude or anything, but would like to kindly ask when can we expect this to be merged? 
Thank you!

**Comment by sameersbn** [comment]
@l00v3 sorry about this. the feature in#2321 has been merged
