### ISSUE TITLE
Change images such as logo

### ISSUE THREAD

**Issue by xeno1991** [sameersbn/docker-gitlab#231]
I would like to change logo. Do you have a plan to add this feature?
I guess what to do is replacing images such as `/home/git/gitlab/app/assets/images/logo-black.png` and recompiling assets.

**Comment by jonaskac** [comment]
:+1:

**Comment by sameersbn** [comment]
@xeno1991 custom branding is a Gitlab EE feature. Given which I don't think GitLabHQ will appreciate adding this feature.

**Comment by xeno1991** [comment]
@sameersbn 
Thank you for your comment. I will do it by myself and keep it local when I really want to do this. Let me close this issue.

**Comment by flungo** [comment]
As an update, this is now a CE feature under `Admin > Appearance`
