### ISSUE TITLE
how to generate new recovery codes using SSH under sameersbn / docker-gitlab 11.11

### ISSUE THREAD

**Issue by Auggie321** [sameersbn/docker-gitlab#2315]
[Generate new recovery codes using SSH](http://www.obsis.unb.br/gitlab/help/user/profile/account/two_factor_authentication.md#generate-new-recovery-codes-using-ssh)
[Reset passwd issues-929](https://github.com/sameersbn/docker-gitlab/issues/929)

```
checking from those,  reset root passwd and login, but still need input 2F code.
forget the recovery codes, how to regenerate it in sameersbn-gitlab ,thanks.
```

gitlab domain: git.xxx.com
```
ssh git@git.xxx.com 2fa_recovery_codes
The authenticity of host 'git.xxx.com (xx.xx.xx.xx)' can't be established.
ECDSA key fingerprint is SHA256:t0M1k2SzvMP3IY6AI/I6Bt+FRFFRYdOKlHh37uIDX9c.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'git.xxx.com,xx.xx.xx.xx' (ECDSA) to the list of known hosts.
Password:
pam_unix: pam_sm_authenticate: UNIX authentication refused
Password:
pam_unix: pam_sm_authenticate: UNIX authentication refused
```

is the the password should be the  "user = User.where(id: 1).first"'s passwd ?
or something else ?

**Comment by ahills60** [comment]
Hello @Auggie321, According to [the documentation](https://docs.gitlab.com/11.11/ee/user/profile/account/two_factor_authentication.html#generate-new-recovery-codes-using-ssh), you'll need to have [an SSH key](https://docs.gitlab.com/11.11/ee/ssh/README.html) set up on your account *before* you can use an SSH login to generate new 2FA recovery codes.

The SSH key will need to be loaded into the SSH agent (for example, `ssh-add ~/.ssh/your_gitlab_key`) and then attempt the above.

**Comment by Auggie321** [comment]
@ahills60  thank you, sir.

i will test it in dev servers.
