### ISSUE TITLE
Differentiate nginx host and port from external ones

### ISSUE THREAD

**Issue by StreakyCobra** [sameersbn/docker-gitlab#232]
Hello,

For some external reasons, I *must* use the following configuration:

I have one virtual machine running `apache` which is listening on port 443. This port is the only one open to the outside. This same VM is running `docker-gitlab`, and sadly it can not directly run on port 443 because `apache` is already listening on this one. Also I can not remove `apache` because it is dispatching request localy regarding to relative urls (`/git` -> docker-gitlab, `/wiki` -> dokuwiki) and serve as HTTPS proxy for all those services. And finally I can not run docker-gitlab on another virtual machine.

So my current solution is to run docker gitlab locally on HTTP (port 10080), and configure `apache` to proxy `/git` to this port (notice to make it work I have set `GITLAB_RELATIVE_URL_ROOT=/git`):

            ProxyPass /git http://0.0.0.0:10080/git
            ProxyPassReverse /git http://0.0.0.0:10080/git

It is a dirty solution, and even not working always correctly: `gitlab` is still thinking that he is serving on port 10080, so all links he is sending via mail, or content loaded via ajax requests are still refering to this port, which is not accessible.

It seems possible to correct this behaviour according to this answer [1], especially the **step 3**. I could probably manage to cobble something manually on my server, but it would be far better to have a configuration parameter for this. Sadly my docker-fu is not yet sufficient to propose you a patch.

In my mind the solution looks something like this:

* `GITLAB_HOST` and `GITLAB_PORT` specifying host and port served by nginx.
* `EXTERNAL_HOST` and `EXTERNAL_PORT` specifying host and port served by gitlab (e.g. to generate URLs). If not specified, they should be the same as nginx ones.

It doesn't *seems* very difficult to implement, at least for what I saw on Server Fault. Also this separation between **nginx's** host and port and **external** ones would probably solve some other network architecture problems.

[1] http://serverfault.com/a/630298

BTW thanks for all your amazing work :+1:

**Comment by sameersbn** [comment]
@StreakyCobra The image already supports what you are trying to achieve. Basically you need to set the GITLAB_PORT to 443. This setting does not configure the internal listening port. It soft of indicates on which public port the server is accessible, which in your case is 443.

To clarify things, consider the setup.

| user |   -- 443 -->   | apache proxy |  --10080-->  | gitlab |

In this setting you should launch the gitlab container with the following parameters
`-p 10080:80 -e 'GITLAB_PORT=443'` additionally you should set `GITLAB_HTTPS=true` for HTTPS support.

In this case you also don't need to run gitlab at a relative url so long as you can setup a new subdomain.

**Comment by StreakyCobra** [comment]
Oh, my bad. I was thinking that `GITLAB_PORT` was setting the listening port, but it is the `-p 10080:80` only that set it… All this make sense actually :neutral_face:

Sadly I can neither create subdomains, so continuing with relative url.

Thanks very much for your explanations! Closing the issue then.

**Comment by jwijffels** [comment]
@sameersbn I'm setting up the gitlab container with `-p 10080:80 -e 'GITLAB_PORT=443'` but I'm getting stuck on setting up the subdomain. Would it be possible to share an Apache conf file where you show this subdomain and how the proxy refers to the docker container which is started up?
