### ISSUE TITLE
Sending email does not work - how to test SMTP settings?

### ISSUE THREAD

**Issue by mradeschnig** [sameersbn/docker-gitlab#2334]
I installed gitlab with docker-compose.  In general gitlab works (cloned my gitea projects and can commit and clone the projects).
Later I realized that the email notification does not work and the gitlab container is in unhealty status.
How to find out what is the cause for the unhealty state and second why the email does not work.

image: sameersbn/gitlab:13.9.4
docker on Ubuntu 18.04.

Except the email notifications seems not to work.
I set 
    - GITLAB_EMAIL=<myemailaddress>@<mydomain.com>
    - GITLAB_EMAIL_REPLY_TO=<myemailaddress>@<mydomain.com>
    - GITLAB_INCOMING_EMAIL_ADDRESS=<myemailaddress>@<mydomain.com>
    - SMTP_ENABLED=true
    - SMTP_DOMAIN=<mydomain.com>
    - SMTP_HOST=server.<mydomain.com>
    - SMTP_PORT=587
    - SMTP_USER=<myemailaddress>@<mydomain.com>
    - SMTP_PASS=<mypassword>
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

If I look in thunderbird - I have
Server Name: server.domain.com
Port: 587
User Name: <myemailaddress>@domain.com
Authentication method: Normal password
Connection Security: STARTTLS

How could I test the email notification in the most easy way, possibly from the docker container by script.
How can I trigger an email (I thought when creating an user I should get an email) or check the email is correctly setup?
I have no firewall enabled on the server.

**Comment by navrocky** [comment]
You can test email settings as follows:

Enter in rails console ([docs](https://docs.gitlab.com/ee/administration/operations/rails_console.html)):
```bash
docker exec -it gitlab-container bundle exec rails console -e production
```
Execute email test command ([docs](https://docs.gitlab.com/omnibus/settings/smtp.html#testing-the-smtp-configuration)):
```ruby
Notify.test_email('destination_email@address.com', 'Message Subject', 'Message Body').deliver_now
```

**Comment by mradeschnig** [comment]
Thank you very much.
First it did not state an error and processed the email in 800ms without really sending it.

Now I commented those line out from the config
#    - SMTP_STARTTLS=true
#    - SMTP_AUTHENTICATION=login
and got it working.
Hard to say what was wrong. 
I use all-inkl.com as email provider.
