### ISSUE TITLE
How to restore gitlab-secret.json

### ISSUE THREAD

**Issue by marawu** [sameersbn/docker-gitlab#2348]
Hi, we'd like to migrate to GitLab Omnibus, but I can't find gitlab-secret.json, can you help me? Where I can find it?

There isn't secret file:

```
lrwxrwxrwx 1 git git 22 Apr  6 10:32 .secret -> /home/git/data/.secret
root@3ff23eddaaa8:/home/git/gitlab# cat .secret
cat: .secret: No such file or directory
```

**Comment by hassani0393** [comment]
We really need the answer to this...

**Comment by kkimurak** [comment]
`gitlab-secrets.json` is available only for omnibus-installed gitlab. This, `sameersbn/gitlab` provides source-installed gitlab.  
You can see required information (such as `db_key_base`) in `/home/git/gitlab/config/secrets.yml` instead.

**Comment by andyzheung** [comment]
> `gitlab-secrets.json` is available only for omnibus-installed gitlab. This, `sameersbn/gitlab` provides source-installed gitlab. You can see required information (such as `db_key_base`) in `/home/git/gitlab/config/secrets.yml` instead.

I have the screts.yaml, but how can we restore this env:
- GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
- GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string
- GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string

**Comment by bsodmike** [comment]
> > `gitlab-secrets.json` is available only for omnibus-installed gitlab. This, `sameersbn/gitlab` provides source-installed gitlab. You can see required information (such as `db_key_base`) in `/home/git/gitlab/config/secrets.yml` instead.
> 
> I have the screts.yaml, but how can we restore this env:
> 
> * GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
> * GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string
> * GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string

You'll find those values in the `secrets.yml`
```
---
production:
  db_key_base: "COPY_ME"
  secret_key_base: "COPY_ME"
  otp_key_base: "COPY_ME"
```
