### ISSUE TITLE
Whether to support gitlab-ee

### ISSUE THREAD

**Issue by jicki** [sameersbn/docker-gitlab#2359]
Whether to support gitlab-ee ?

**Comment by jicki** [comment]
@cwildfoerster

**Comment by jicki** [comment]
> I don't know, i guess no one who pays for a subscription wants to wait weeks for security updates. This project also did not "care" much about older release patched. After months of slow PR merges / lack of activity by its owners, i migrated to the official omnibus docker images two weeks ago.

OK  Thank !

**Comment by sameersbn** [comment]
@jicki it does not really make sense for user to adopt this image when they're subscribed to the GitLab EE edition. I you're on the EE you SHOULD use the official images from GitLab so that you can get the support your paying for.

Apologies for  the delayed response.
