### ISSUE TITLE
gitlabs command not exported to PATH inisde container

### ISSUE THREAD

**Issue by delacosta456** [sameersbn/docker-gitlab#2383]
hi
I am very new to gitlab and using this image. But it's looks like gitlab's commands like rake, rails are not automatically exported to **PATH** insiside container.
i am using Gitlab on docker inside QNAP (Container Sation)
to use command i have to

1. docker exec -it container-name bash
2. cd /home/git/gitlab/bin
is that the normal way please ?
Thaznks

**Comment by sachilles** [comment]
Hi,

you describe how to open a bash as user `root` in the container. If you instead run `docker exec -it -u git container-name bash`, you will get a bash as user `git`.

That should solve your problem.

**Comment by kkimurak** [comment]
In general, It is important to pass correct user, but it should not solves this issue. 

Such commands like `rake`, `rails` are listed in `Gemfile` and installed/managed using `bundle`. They are usually executed via `bundle exec`. It automatically resolves PATH for commands. See [bundle exec(1)](https://bundler.io/v2.1/man/bundle-exec.1.html#ENVIRONMENT-MODIFICATIONS) 

So the command should be like : `docker exec -it -u git container-name bundle exec rails`

**Comment by delacosta456** [comment]
hi 
ok thanks for clarifications. ,i will try that
