### ISSUE TITLE
Can't restore from backup

### ISSUE THREAD

**Issue by faradaytrs** [sameersbn/docker-gitlab#239]
I pulled you image and try to use it, but i can't restore from my backup.
I put my backup file to /home/git/data/backups but when i make 
    
    fig run gitlab app:rake gitlab:backup:restore
    
I get such output: 
    
    Creating SSH2 RSA key; this may take some time ...
    Creating SSH2 DSA key; this may take some time ...
    Creating SSH2 ECDSA key; this may take some time ...
    Creating SSH2 ED25519 key; this may take some time ...
    invoke-rc.d: policy-rc.d denied execution of restart.
    sed: -e expression #1, char 24: unknown option to `s'
    
Result above i get if i started image with fig start, if i didn't i get: 
    
    Starting gitlab_postgresql_1...
    Starting gitlab_redis_1...
    Creating SSH2 RSA key; this may take some time ...
    Creating SSH2 DSA key; this may take some time ...
    Creating SSH2 ECDSA key; this may take some time ...
    Creating SSH2 ED25519 key; this may take some time ...
    invoke-rc.d: policy-rc.d denied execution of restart.
    Running gitlab rake task...
    ls: cannot access /home/git/data/backups/*_gitlab_backup.tar: No such file or directory
    No backup present. Cannot continue restore process.
    
How to restore from my backup? Please help.

**Comment by sameersbn** [comment]
@faradaytrs It appears like there is some character in one of the emvironment variables that might need to be escaped, due to which one of the sed substitutions is failing. The password variables are generally the culprits in this case.

Please refer to #92 for additional information

**Comment by sameersbn** [comment]
@faradaytrs any update on this?

**Comment by faradaytrs** [comment]
yes @sameersbn it worked when i came into bash and used rake inside of working container.

**Comment by sameersbn** [comment]
@faradaytrs got it. i will check it locally to make sure its not broken.

**Comment by sameersbn** [comment]
@faradaytrs seems to be working fine using the docker cli. Maybe the issue occurs while using fig.

**Comment by siuying** [comment]
Hi,

I had similar issue, got ``sed: -e expression #1, char 24: unknown option to `s'`` if I included the SMTP_PASS lines below:

```
gitlab:
  image: sameersbn/gitlab:7.7.2
  environment:
    - RAILS_ENV=production
    - SMTP_PASS=abc/1234
```

Any idea how I can escape the line so that sed will not fail?

**Comment by sameersbn** [comment]
@siuying can you try `SMTP_PASS=abc\/1234`

**Comment by sameersbn** [comment]
@siuying oh sorry that will probably not work. you might have to change the password to not have the `/` character.

**Comment by siuying** [comment]
Would you accept PR to fix this, perhaps use proper template like mustache?

**Comment by sameersbn** [comment]
@siuying sure. if we can fix this to handle all characters there would be nothing like it. before you submit a PR, please suggest your fix.

**Comment by KingCrunch** [comment]
@siuying I'd really like it. I have the same issue, but I cannot figure out, what's the cause. At the end I've commented the entire environment section out...

**Comment by siuying** [comment]
@KingCrunch the script (/assets/init) use sed to replace configuration variables. Expression like this:

```
sed 's/{{SMTP_PASS}}/'"${SMTP_PASS}"'/'
```
fails when SMTP_PASS contains "/", which is the delimiter for sed. Use other characters as delimiter do not solve the issue.

In last comment I was looking for alternative template, but that's a big change and need to migrate a lot of logic. A better way to do it might be write a [function to escape the input before feeding it to sed](http://stackoverflow.com/questions/407523/escape-a-string-for-a-sed-replace-pattern).

**Comment by KingCrunch** [comment]
@siuying That I've already read, but my SMTP-password only consists of characters and numbers, so that cannot be the issue. There are many many other `sed`-calls and the error message doesn't tell, which one is the faulty one, so I commented out one after the other, but no change. Probably at the end I'll say "Oh, yeah, of course, me idiot", but not now :|
