### ISSUE TITLE
Missing 7.7.0 build on Docker Hub

### ISSUE THREAD

**Issue by Jack12816** [sameersbn/docker-gitlab#241]
See: https://registry.hub.docker.com/u/sameersbn/gitlab/builds_history/4161/ ->
![missing_build](https://cloud.githubusercontent.com/assets/2496275/5866611/414d5118-a293-11e4-96a3-6910e8d8bb22.png)

The tag 7.7.0 is missing, see: https://registry.hub.docker.com/u/sameersbn/gitlab/tags/manage/ ->

![versions](https://cloud.githubusercontent.com/assets/2496275/5866632/79bf47cc-a293-11e4-8271-24542e5ba9ab.png)

```bash
$ docker pull sameersbn/gitlab:7.7.0
Pulling repository sameersbn/gitlab
FATA[0003] Tag 7.7.0 not found in repository sameersbn/gitlab 
```

Something went wrong i guess.

**Comment by sameersbn** [comment]
@Jack12816 there is some [issue](http://status.docker.com/pages/incident/533c6539221ae15e3f000031/54c135bce0354e3856000229) with the docker hub. Docker Inc has indicated that they have applied a hotfix to resolve the issue.

Trying to rebuild now.

**Comment by sameersbn** [comment]
@Jack12816 The build is now ready

**Comment by Jack12816** [comment]
Looks good. :) Keep on doing the great work!
