### ISSUE TITLE
Upgrade from 14.1.x to 14.2.x fails

### ISSUE THREAD

**Issue by l00v3** [sameersbn/docker-gitlab#2412]
Hello,
suddenly the upgrade fails to 14.2.2 (and 14.2.1). Git is unusable, get a lot of 500 errors. The error in host machine is:

```
Sep  2 08:10:59 git systemd[1]: Started Process Core Dump (PID 195721/UID 0).
Sep  2 08:11:35 git systemd-coredump[195726]: Process 195521 (ruby2.7) of user 1000 dumped core.#012#012Stack trace of thread 2721:#012#0  0x00007f89d8a1d18b n/a (/usr/lib/x86_64-linux-gnu/libc-2.31.so)#012#1  0x00007f89d8bc3643 n/a (/usr/lib/x86_64-linux-gnu/libc-2.31.so)
Sep  2 08:11:36 git systemd[1]: systemd-coredump@3-195721-0.service: Succeeded.
```

There is nothing useful in Docker containers logs.

If somebody needs more information, tell me what is needed and I will try to provide it.

Thank you for your help!

**Comment by politsin** [comment]
confirm
subscribe

**Comment by l00v3** [comment]
v14.2.3 seems to work ok.
