### ISSUE TITLE
Can't create project

### ISSUE THREAD

**Issue by flecno** [sameersbn/docker-gitlab#243]
A few days ago I have upgraded my gitlab container from `6.2.1` to `7.7.1`. But now I can't create new projects. If I try to create a new project gitlab says `Failed to create repository`.

I can't find more informations in the logs in the admin section.

Anybody has the same problem and can help me?

**Comment by sameersbn** [comment]
@flecno can you try running the container with the `app:sanitize` argument first. Just run the container in interactive mode and append `app:sanitize` to the command line. Once completed, launch the container without the `app:sanitize` option.

If there is some file/directory permission issue `app:sanitize` will fix it.

**Comment by flecno** [comment]
@sameersbn thanks for this tips. I ran `app:sanitize` which outputs to me with:

```
Checking repository directories permissions...
Checking satellites directories permissions...
Checking uploads directory permissions...
Checking tmp directory permissions...
```

But it doesn't helps... It looks like a permission problem, because I can't push anythink in existing repos (` ! [remote rejected] master -> master (unpacker error)`). Do you have any other ideas?

**Comment by flecno** [comment]
thanks for your help, but I have not realize that there is no space left on disk >.<
