### ISSUE TITLE
A lot of page 500 when upgrading from 13.12.4 to 14.0.0

### ISSUE THREAD

**Issue by sprucify** [sameersbn/docker-gitlab#2430]
I can upgrade up to gitlab version 13.12.4, but as soon as I go to 14.0.0 I'm facing a lot of page 500 errors.
When I turn 2FA off, it seems to work a bit better, but 2FA is required.

I tried to turn off 2FA in version 13.12.4 before starting the upgrade, but no luck.

The changes in my docker-compose file are:

- sameersbn/gitlab:13.12.4 to sameersbn/gitlab:14.0.0
- image: redis:5.0.9 to image: redis:6.2
- redis-data:/var/lib/redis:Z to redis-data:/data:Z

So a lot is changing on redis side.
Does the mapped redis volume maybe contain some previous 2FA cache?

I tried to remove and add 2FA, but this didn't trigger any cache clean up I think

**Comment by koubas** [comment]
Hi, I nedded to set these envs:
- RACK_ATTACK_ENABLED=false (fixed 500s on login)
- prometheus_multiproc_dir=/dev/shm (fixed 500 in admin/metrics)

And I had to upgraded to latest Redis because my ancient one didn't know the UNLINK command

**Comment by sprucify** [comment]
Thanks.
Did you turn off Rack Attack temporarily and turn it back on in later upgrades?

**Comment by kkimurak** [comment]
Yes of course. Please follow [upgrade path](https://docs.gitlab.com/ee/update/#upgrade-paths). It says "latest 13.12.Z -> latest 14.0.Z -> latest 14.Y.Z" is supported.

**Comment by kkimurak** [comment]
Thanks for checking up, then you can run background migration manually. See https://docs.gitlab.com/ee/user/admin_area/monitoring/background_migrations.html#manually-finishing-a-batched-background-migration 
Note that this repo provides source-instaled gitlab, so `sudo gitlab-rake` command should be replaced by `docker exec -it your-gitlab-container-name bundle exec rake` (or `docker exec -it your-gitlab-container-name /bin/bash` then `bundle exec rake`).
