### ISSUE TITLE
Sends the link with a port when resetting the user password.

### ISSUE THREAD

**Issue by kabengwa** [sameersbn/docker-gitlab#2431]
When I reset the user password the system sends the link to reset with a port and that just fails until you manually remove the port from the URL. How can I solve this so that no port is sent?

I  have this container behind a reverse proxy from `jwilder/nginx-proxy` and `jrcs/letsencrypt-nginx-proxy-companion`.

Thank you in advance.

**Comment by kkimurak** [comment]
Is your setting parameter `GITLAB_PORT` correct? This parameter will appear to emails as-is I think.

**Comment by kabengwa** [comment]
This is what I have in the ymal file `GITLAB_PORT=1008`. What is the right way of doing it? should I remove it or there is a setting that I must change so that it is not sent in emails.

**Comment by kkimurak** [comment]
Well, according to your comment, You want to remove port number from link in email, right?  
Then **just remove (or comment out) `GITLAB_PORT` settings.** 

This will automatically set port in generated URL to [80 (or 443 if https enabled)](https://github.com/sameersbn/docker-gitlab/blob/7665a499af62ddf2f67e49548c6bd6f795b80d84/assets/runtime/env-defaults#L22-L26), and gitlab will [remove if not a custom port](https://gitlab.com/gitlab-org/gitlab-foss/-/blob/d67ccb290ab5e54ff42f9cd464a132fc1d3067e1/config/settings.rb#L176-178) when generating email.
