### ISSUE TITLE
push error : rpc failed

### ISSUE THREAD

**Issue by zipeldiablo** [sameersbn/docker-gitlab#245]
Hi, i got an issue on transfering big directories, by big i mean lot of files, size is low (about 80mb).
I tried to fix this by : 
-setting NGINX_MAX_UPLOAD_SIZE=1G
-setting UNICORN_TIMEOUT=180
-setting GITLAB_MAX_SIZE=500M
None of this worked, kinda don't know what to do now, the issue is when i use git through http, i cannot use ssh for work reasons.

Also mail doesnt send when a user register, do i have to provider a google auth key besides my log?
Regards

**Comment by sameersbn** [comment]
@zipeldiablo please share your setup details. Additionally provide a sample docker command line to test this case out.

Mail sending should work provided it is configured correctly.

**Comment by zipeldiablo** [comment]
what do you mean by setup details? 
I cannot provide a sample docker command line this is a git issue, i tried to push 380 files who are in multiples subdirectory, except for screenshots or maybe a video i have no idea how i can help you reproduce this bug.

I used git remote add gitlab http://domain.name/root/42_First_Year.git to set a new remote for git and when i push i got this : 
git push -u gitlab master
Counting objects: 562, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (358/358), done.
Writing objects: 100% (562/562), 2.08 MiB | 0 bytes/s, done.
Total 562 (delta 377), reused 206 (delta 178)
error: RPC failed; result=22, HTTP code = 413
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

to run the image i use this : 
docker run --name=gitlab -d --link mysql:mysql --link redis:redisio \
    -e "DB_USER=gitlab" \
    -e "DB_PASS=pass" \
    -e "DB_NAME=gitlabhq_production" \
    -e 'GITLAB_HOST=domain.name' \
    -e 'UNICORN_TIMEOUT=180' \
    -e 'GITLAB_SSH_HOST=domain.name' \
    -e 'GITLAB_EMAIL=user@gmail.com' \
    -e 'GITLAB_WEBHOOK_TIMEOUT=100' \
    -e 'SMTP_AUTHENTICATION=plain' \
    -e 'GITLAB_PROJECTS_SNIPPETS=true' \
    -e 'GITLAB_EMAIL_ENABLED=true' \
    -e VIRTUAL_HOST=domaine.name \
    -e 'GITLAB_SIGNUP=true' \
    -e 'NGINX_MAX_UPLOAD_SIZE=1G' \
    -e 'SMTP_HOST=smtp.gmail.com' \
    -e 'SMTP_PORT=567' \
    -e 'SMTP_USER=user@gmail.com' \
    -e 'SMTP_PASS=pass' \
    -e 'SMTP_DOMAIN=gmail_account_domain' \
    -e 'GITLAB_MAX_SIZE=500M' \
    -e 'SMTP_ENABLED=true' \
    -v /home/zipeldiablo/git/data:/home/git/data \
    sameersbn/gitlab:latest

the VIRTUAL_HOST variable is for the nginx reverse proxy container

**Comment by sameersbn** [comment]
@zipeldiablo I tested pushing a repo containing 50992 files and folders amounting to 2.6G of storage space and had no problem. But before I list out my test commands, I would like to mention that if you are using a reverse proxy then you should configure the upload limits on the reverse proxy as well. If this is the case than the proxy itself will not forward the request to the gitlab container. I strongly believe this is the problem.

Continuing with my test, here are the test commands I used

```bash
# start mysql container
docker run -it --name=mysql -e 'DB_USER=gitlab' -e 'DB_PASS=password' -e 'DB_NAME=gitlabhq_production' sameersbn/mysql

# start redis container
docker run -it --rm --name=redis sameersbn/redis

# start gitlab container
docker run -it --rm \
--link mysql:mysql --link redis:redisio \
-p 10080:80 -p 2222:22 \
-e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=2222' \
-e 'NGINX_MAX_UPLOAD_SIZE=1g' \
sameersbn/gitlab:latest

# login to gitlab and create a project for the push

# push largerepo
cd largerepo
git remote add origin http://localhost:10080/root/largerepo.git
git push -u origin master
```

**Comment by zipeldiablo** [comment]
Tried lauching the container by assigning port in order to bypass the reverse proxy and it works, so it's an issue related to the reverse proxy not your container, thanks for your time and sorry for bothering you
