### ISSUE TITLE
How to access gitlab service in kubernetes on Intranet cloud from external network?

### ISSUE THREAD

**Issue by SuperGeo0928** [sameersbn/docker-gitlab#2453]
I've already set up the gitlab service on my k8s which is deployed on our company's MobileCloud,and I can get access with node ip and nodeport.but when i try to get access from my own laptop in the external network ,it will be redricted to another ip, then 404,like the following pic.Besides ,our gateway has received the request from me ,the gateway is also set correctly.So I think it is caused by the internal nginx ,but I cannot find the related settings.
What should I do now?how can I get to the correcct page?
pic 1 shows success when I visit gitlab in cloud
pic 2 shows failure when i visit from my own laptop in external network
pic 3 shows the redirect ,and port "3721" & "/gitlab" just disappered
![微信图片_20211112185755](https://user-images.githubusercontent.com/56472824/141456524-19b11cab-d793-4a93-a2da-81f068942ecb.jpg)
<img width="279" alt="微信图片_20211112190209" src="https://user-images.githubusercontent.com/56472824/141457375-1d070566-aada-43b7-8907-43b4927a7c89.png">
<img width="495" alt="微信截图_20211112190226" src="https://user-images.githubusercontent.com/56472824/141457384-9a7d57e7-7379-4de0-9e0c-c421f805a47a.png">

**Comment by MybatisYang** [comment]
Brother, could you please tell me how to solve it? I have also encountered it
