### ISSUE TITLE
Gitlab 404 error for /asset/ paths when installing with docker compose

### ISSUE THREAD

**Issue by virob** [sameersbn/docker-gitlab#2454]
I did the docker-compose up. The installation seemed to work well. After I've log in the 404 is seen for all the resources requests (css/js/icons). What could be the problem, maybe someone faced it as well:
the production log:

=====
{"method":"GET","path":"/assets/webpack/runtime.24628ad3.bundle.js","format":"js","controller":"ApplicationController","action":"route_not_found","status":404,"time":"2021-11-14T20:19:25.923Z","params":[{"key":"unmatched_route","value":"assets/webpack/runtime.24628ad3.bundle"}],"remote_ip":"127.0.0.1","user_id":1,"username":"root","ua":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36","correlation_id":"95da618f-d952-47ba-9e24-037472a1d715","meta.user":"root","meta.caller_id":"ApplicationController#route_not_found","meta.remote_ip":"127.0.0.1","meta.client_id":"user/1","redis_calls":3,"redis_duration_s":0.009587,"redis_read_bytes":181,"redis_write_bytes":853,"redis_shared_state_calls":3,"redis_shared_state_duration_s":0.009587,"redis_shared_state_read_bytes":181,"redis_shared_state_write_bytes":853,"db_count":1,"db_write_count":0,"db_cached_count":0,"db_replica_count":0,"db_replica_cached_count":0,"db_replica_wal_count":0,"db_replica_wal_cached_count":0,"db_primary_count":1,"db_primary_cached_count":0,"db_primary_wal_count":0,"db_primary_wal_cached_count":0,"db_replica_duration_s":0.0,"db_primary_duration_s":0.007,"cpu_s":0.171047,"pid":1085,"db_duration_s":0.0,"view_duration_s":0.00013,"duration_s":0.00492}

==> production.log <==
Processing by ApplicationController#route_not_found as CSS
  Parameters: {"unmatched_route"=>"assets/application-775f130d36e9eb14cb67c6a63551511b87f78944cebcf6cdddb78292030341df"}
Completed 404 Not Found in 2ms (ActiveRecord: 0.0ms | Elasticsearch: 0.0ms | Allocations: 743)
======

**Comment by Alan-LOL** [comment]
Hello, @virob Did you solve this?

**Comment by jicki** [comment]
Did you solve this? @Alan-LOL @virob

**Comment by mgarrido** [comment]
Does anyone know how ti fix it?
