### ISSUE TITLE
14.4.2 manifest unknown

### ISSUE THREAD

**Issue by josefschroettle** [sameersbn/docker-gitlab#2467]
When I try to upgrade from 14.3.0 to 14.4.2 I get the error:
ERROR: manifest for sameersbn/gitlab:14.4.2 not found: manifest unknown: manifest unknown
Is this on my side?

**Comment by kkimurak** [comment]
That's not. Something went wrong when publishing image to docker.io. and quay.io. The "latest" tag is updated correctly but "14.4.2" is not up.  
If urgent, please run `docker pull sameersbn/gitlab:latest` then `docker tag sameersbn/gitlab:latest sameersbn/gitlab:14.4.2`.

**Comment by sachilles** [comment]
@sameersbn Could you be so kind and check on it?

**Comment by kkimurak** [comment]
hi @sachilles , could you retry pushing tag name without "v" (in this case `14.4.2`, not `v14.4.2`)?  
Most likely it was excluded because the tag did not match the ["only" pattern in circle-ci configuration](https://github.com/sameersbn/docker-gitlab/blob/f1156cf07af88c703601cf9124bd89f36b81a26f/.circleci/config.yml#L312).

**Comment by josefschroettle** [comment]
Sorry, cannot try any longer. I did the update with 'latest' which worked and got me the 14.4.2.

**Comment by sachilles** [comment]
Hi,

I pushed a new tag. The CI should produce a correctly tagged image. Thanks for your advise.

**Comment by jinixx** [comment]
Hi @sachilles ,

It is happening again, latest is not tagged to 14.8.1.

Getting below error after running `docker-compose up`

`ERROR: manifest for sameersbn/gitlab:14.8.1 not found: manifest unknown: manifest unknown`

**Comment by sachilles** [comment]
I forgot to tag the version. I did that just now.

Sorry for the inconvenience!

**Comment by sachilles** [comment]
The build process usually takes about an hour. This means, that today in the evening the release informations and docker images will be published.

**Comment by sachilles** [comment]
I guess this ticket can be closed. I will pay better attention next time. 😄
