### ISSUE TITLE
Do not create https config for nginx

### ISSUE THREAD

**Issue by elderone** [sameersbn/docker-gitlab#247]
# docker --version
Docker version 1.3.2, build 39fa2fa/1.3.2

# cat /etc/centos-release
CentOS Linux release 7.0.1406 (Core)

docker run -d \
 --privileged \
 --name gitlab \
 --link mysql:mysql \
 --link redis:redisio \
 -p 172.16.1.101:22:22 \
 -p 172.16.1.101:443:443 \
 -h example.com \
 -e GITLAB_BACKUPS=daily \
 -e GITLAB_HTTPS=true \
 -e GITLAB_HTTPS_HSTS_MAXAGE=2592000 \
 -e DB_USER=gitlab \
 -e DB_PASS=password \
 -e DB_NAME=gitlabhq_production \
 -e SMTP_USER=git@example.com \
 -e SMTP_DOMAIN=smtp.example.com \
 -e SMTP_PASS=password \
 -e GITLAB_HOST=git.example.com \
 -e GITLAB_EMAIL=gitlab@example.com \
 -e GITLAB_SUPPORT=support@example.com \
 -v /dock/gitlab/data:/home/git/data \
 sameersbn/gitlab:latest

# docker exec gitlab netstat -nvltp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2800/sshd
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      2797/unicorn.rb -E
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2799/nginx -g daemo
tcp6       0      0 :::22                   :::*                    LISTEN      2800/sshd
tcp6       0      0 :::80                   :::*                    LISTEN      2799/nginx -g daemo

# docker exec gitlab printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=git.example.com
MYSQL_PORT=tcp://172.17.0.59:3306
MYSQL_PORT_3306_TCP=tcp://172.17.0.59:3306
MYSQL_PORT_3306_TCP_ADDR=172.17.0.59
MYSQL_PORT_3306_TCP_PORT=3306
MYSQL_PORT_3306_TCP_PROTO=tcp
MYSQL_NAME=/gitlab/mysql
REDISIO_PORT=tcp://172.17.0.58:6379
REDISIO_PORT_6379_TCP=tcp://172.17.0.58:6379
REDISIO_PORT_6379_TCP_ADDR=172.17.0.58
REDISIO_PORT_6379_TCP_PORT=6379
REDISIO_PORT_6379_TCP_PROTO=tcp
REDISIO_NAME=/gitlab/redisio
GITLAB_BACKUPS=daily
GITLAB_HTTPS=true
GITLAB_HTTPS_HSTS_MAXAGE=2592000
DB_USER=gitlab
DB_PASS=password
DB_NAME=gitlabhq_production
SMTP_USER=git@example.com
SMTP_DOMAIN=smtp.example.com
SMTP_PASS=password
GITLAB_HOST=git.example.com
GITLAB_EMAIL=gitlab@example.com
GITLAB_SUPPORT=support@example.com

# docker exec gitlab cat /etc/nginx/sites-enabled/gitlab | grep 443
...empty...

**Comment by sameersbn** [comment]
@elderone unless the ssl certificates are installed nginx will not be configured to listen on port 443 https://github.com/sameersbn/docker-gitlab/blob/master/assets/init#L319-L330. However the gitlab application will be configured to support SSL and this is to support case's where the gitlab container is running behind an SSL enabled proxy.

**Comment by elderone** [comment]
it was bad dhparam.pem
thank you!
