### ISSUE TITLE
Can't connect to local ssh externally and not correctly locally

### ISSUE THREAD

**Issue by LnAlex** [sameersbn/docker-gitlab#248]
I've some issues with SSH, when I want to connect to the SSH's container on my host machine with `ssh localhost -p 10022` it doesn't work (no response). However it works well with `ssh git.host.com -p 10022`. Then, externally with  `ssh git.host.com -p 10022` there is no response (even with opened port in iptables).

This is my running configuration: 
`docker run --name=gitlab -d --link redis:redisio -p 10022:22 -p 10080:80 -e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=10022' -e 'DB_HOST=172.16.1.1' -e 'DB_TYPE=mysql' -e 'DB_NAME=gitlabhq_production' -e 'DB_USER=gitlab' -e 'DB_PASS=mypass' -e 'GITLAB_HOST=git.host.com' -e 'GITLAB_EMAIL=git@host.com' -e 'SMTP_DOMAIN=mail.host.com' -e 'SMTP_USER=git@host.com' -e 'SMTP_PASS=mypass' -e 'SSL_SELF_SIGNED=true' -v /opt/gitlab/data:/home/git/data sameersbn/gitlab:latest`

I'm trying to troubleshoot for several hours, maybe it's a misunderstanding coming from me. 

Thanks

**Comment by netflash** [comment]
I assume that you should check on which  IP addresses 10022/tcp port attached to.
run this on your host system
```
sudo netstat -tapn|grep 10022
```

**Comment by sameersbn** [comment]
@LnAlex what is your host OS? I have a feeling this has got something to do with selinux.

**Comment by LnAlex** [comment]
@netflash  

    # netstat -tapn|grep 10022
    tcp6       0      0 :::10022                :::*                    LISTEN      
    2047/docker-proxy

@sameersbn Debian 7.6 64bits

**Comment by sameersbn** [comment]
@LnAlex can you enter the verbose mode while connecting to the server via ssh `ssh -v localhost -p 10022`. Hopefully it will give you some idea on what is going on.

IMO possible causes could be:
- selinux
- firewall configuration

Basically it looks like some security policy is preventing the communication. 

At the moment I am not in the position to install debian 7 and test the issue. Hopefully someone who has the image working on debian 7 could chime in.

**Comment by netflash** [comment]
I'm with Debian 7 and everything works fine.

**Comment by sameersbn** [comment]
@netflash @LnAlex maybe you guys can share the docker version in use?

**Comment by LnAlex** [comment]
# ssh -v localhost -p 10022
    OpenSSH_6.0p1 Debian-4+deb7u2, OpenSSL 1.0.1e 11 Feb 2013
    debug1: Reading configuration data /etc/ssh/ssh_config
    debug1: /etc/ssh/ssh_config line 19: Applying options for *
    debug1: Connecting to localhost [::1] port 10022.
    debug1: Connection established.
    debug1: permanently_set_uid: 0/0
    debug1: identity file /root/.ssh/id_rsa type -1
    debug1: identity file /root/.ssh/id_rsa-cert type -1
    debug1: identity file /root/.ssh/id_dsa type -1
    debug1: identity file /root/.ssh/id_dsa-cert type -1
    debug1: identity file /root/.ssh/id_ecdsa type -1
    debug1: identity file /root/.ssh/id_ecdsa-cert type -1
Still waiting at this last line.

I use Docker Docker version 1.4.1, build 5bc2ff8

**Comment by LnAlex** [comment]
Any suggestions ?

**Comment by sameersbn** [comment]
@LnAlex why don't you try connecting directly to the containers ssh post, 

```bash
ssh $(docker inspect --format {{.NetworkSettings.IPAddress}} gitlab)
```

If this works, then probably the iptables configuration is busted. Try adding the iptables rules listed here https://github.com/sameersbn/docker-gitlab/issues/253#issuecomment-73076889. Hopefully it should get this issue sorted.

**Comment by LnAlex** [comment]
`Connecting to 172.17.0.12 [172.17.0.12]`
Connection failed, the problem is due to a misconfiguration of the running container perhaps but I execute the same `docker run` command described in my first post...

**Comment by LnAlex** [comment]
Ok, so the problem is localized. After rebooting the system and disabling the firewall, all works. 
The issue is due to the firewall, still searching for a solution...

**Comment by LnAlex** [comment]
The solution is to start the container AFTER firewall otherwise, iptables overwrites gitlab rules and it doesn't work.
