### ISSUE TITLE
Is support redis password?

### ISSUE THREAD

**Issue by aispringli** [sameersbn/docker-gitlab#2486]
https://docs.gitlab.com/14.6/omnibus/settings/redis.html
gitlab_rails['redis_password'] = '<redis_password>'

How i configer redis password?

**Comment by aispringli** [comment]
can i like this :
REDIS_HOST  = password@host

**Comment by mpv945** [comment]
> can i like this : REDIS_HOST = password@host

This setting has no effect at all. My redis is also secret

**Comment by FANLIYANG-OPS** [comment]
I also had the same problem ... and redis  can use clusters ?
