### ISSUE TITLE
Whether there is data statistics for each item cloned or downloaded

### ISSUE THREAD

**Issue by qxqxq** [sameersbn/docker-gitlab#2487]
It's just used to analyze the number of downloads over time

**Comment by kkimurak** [comment]
I'm sorry but this is upstream issue. We cannot provide any solution here.
Please refer upstream issues:
- https://gitlab.com/gitlab-org/gitlab/-/issues/15807 (unique download/clone count of repository)
- https://gitlab.com/gitlab-org/gitlab/-/issues/327317 (download count of release binary).

----

I don't know what "item" you are talking about - released binary, project itself or something else.
Anyway, you can get clone count via project statistics API. Endpoint is /projects/:id/statistics. You can get the statistics of the last 30 days in json format. For example:

```sh
$ curl --header "Private-Token: <your_access_token>" https://your.gitlab-instance.com/api/v4/projects/<id or url-encoded path of project>/statistics
```

See https://docs.gitlab.com/ee/api/project_statistics.html for more detail.

Note that it does not counts actions via SSH. And, the "count" is sum of HTTP(s) clone/pull/fetch. One of gitlab team says:

> https://gitlab.com/gitlab-org/gitlab-foss/-/issues/42086#note_83225653
> from a GitLab viewpoint there is no difference between git clone, git pull and git fetch; it's all git upload-pack.

If your looking for download count of released binary, my answer is "Not implemented". Just wait for the future release.

Best,

**Comment by qxqxq** [comment]
Thank you very much. It's been very helpful.
