### ISSUE TITLE
Backup defunct with Postgres 9.4

### ISSUE THREAD

**Issue by minus7** [sameersbn/docker-gitlab#249]
Running the manual backup `... sameersbn/gitlab:7.7.2 app:rake gitlab:backup:create` fails when using an external Postgres 9.4 server with the following message:
`Dumping PostgreSQL database gitlabhq_production ... pg_dump: server version: 9.4.0; pg_dump version: 9.3.5`
The automated backup fails too, but there is no logging.

I see two possible solutions here: Installing pg 9.4 in the image too and making it (only /usr/bin/pg_dump I guess) selectable through an environment variable (defaulting to 9.3), or having a second docker image with 9.4.

**Comment by Jack12816** [comment]
I can confirm this.

```bash
root@a66e71f140ad:/var/log/gitlab/gitlab# sudo -u git bash -c "cd /home/git/gitlab && PATH=/usr/local/bin:/usr/bin:/bin bundle exec rake gitlab:backup:create RAILS_ENV=production"
Dumping database ... 
Dumping PostgreSQL database gitlabhq_production ... pg_dump: server version: 9.4.0; pg_dump version: 9.3.5
pg_dump: aborting because of server version mismatch
[FAILED]
Backup failed
```

**Comment by sameersbn** [comment]
@minus7 @Jack12816 interesting. will think of a  solution to fix this issue.

**Comment by sameersbn** [comment]
It is clear that various postgresql versions do not play nice with each other. In such a scenario, installing various postgresql client versions in the  gitlab image to handle with these incompatibilities is not a viable solution.

So this basically means that at the moment the gitlab image is compatible will `postgresql 9.3` and below.

**Comment by sameersbn** [comment]
@minus7 @Jack12816 looks like postgresql clients are backwards compatible, so using postgresql client version 9.4 resolves this issue without breaking anything.

**Comment by minus7** [comment]
Oh, I did not know that it was backwards compatible. Thanks for the quick fix :)

**Comment by Jack12816** [comment]
Thank you, I will test it on the next tagged version. I give you feedback afterwards.

**Comment by sydneyhenrard** [comment]
I tried to upgrade but it does not work because of missing a repository. 

```
root@a986e481390d:/# sudo apt-get install postgresql-client-9.4
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package postgresql-client-9.4
E: Couldn't find any package by regex 'postgresql-client-9.4'
```

I checked the Dockerfile and it includes the postgresql repository: `http://apt.postgresql.org/pub/repos/apt/`

Thanks
