### ISSUE TITLE
"EMFILE: too many open files" error at gitlab:assets:compile stage

### ISSUE THREAD

**Issue by stephane-klein** [sameersbn/docker-gitlab#2491]
When I execute:

```
$ make release
```
On MacOS ou Fedora 35, I have this error:

```
$ NODE_OPTIONS="--max-old-space-size=3584" webpack --config config/webpack.config.js
IncrementalWebpackCompiler: Status – disabled
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Warning: fragment with name PageInfo already exists.
graphql-tag enforces all fragment names across your application to be unique; read more about
this in the docs: http://dev.apollodata.com/core/fragments.html#unique-names
Error: EMFILE: too many open files, open '/home/git/gitlab/node_modules/.cache/compression-webpack-plugin/tmp/64ab441a'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Unable to compile webpack production bundle.
The command '/bin/sh -c bash ${GITLAB_BUILD_DIR}/install.sh' returned a non-zero code: 1
make: *** [Makefile:14 : build] Erreur 1
```

I managed to correct this error with this patch: add `NO_SOURCEMAPS=true` [here](https://github.com/sameersbn/docker-gitlab/blob/f357effe3dade1483ee22258598003a65d482f9e/assets/build/install.sh#L187):

```
echo "Compiling assets. Please be patient, this could take a while..."
exec_as_git bundle exec rake gitlab:assets:compile USE_DB=false SKIP_STORAGE_VALIDATION=true NO_SOURCEMAPS=true NODE_OPTIONS="--max-old-space-size=4096"
```

I am writing a Pull Request.

**Comment by sachilles** [comment]
Hi,

I'm not sure if we should change the way we compile the Ruby assets, as I checked the logfiles on different platforms (Debian, Ubuntu, Archlinux, including our Circle Ci) and did not find the bug you reported.

However, searching a bit on the Internet, I found some references to the bug you reported related to file limits:

* node and Error: EMFILE, too many open files (<https://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files>)
* OS X: "Error: EMFILE: too many open files, watch" when running tests (<https://github.com/facebook/create-react-app/issues/4540>)
* How to fix the: "EMFILE: too many open files, watch" error in macOS (<https://flaviocopes.com/react-native-emfile-too-many-open-files/>)

Did you check the system wide set and/or increased the current limits?

**Comment by stephane-klein** [comment]
> Did you check the system wide set and/or increased the current limits?

I searched in this direction, without success, I will continue, I may have missed something.

**Comment by sachilles** [comment]
Hi,

have you found the root cause or any progress?

**Comment by stephane-klein** [comment]
@sachilles always same bug on i7 gen 11 with 32Go ram on Fedora 35.

My patch is https://github.com/stephane-klein/docker-gitlab/commit/86b6bed1f012075124104122386fcab3fd5a8bbf

**Comment by stephane-klein** [comment]
On Fedora 35, I migrate from:

```
$ sudo dnf list --installed | grep "moby"
moby-engine.x86_64                                20.10.12-1.fc35                      @updates
```

to:

```
$ dnf list --installed | grep "docker"
containerd.io.x86_64                              1.5.11-3.1.fc35                      @docker-ce-stable
docker-ce.x86_64                                  3:20.10.14-3.fc35                    @docker-ce-stable
docker-ce-cli.x86_64                              1:20.10.14-3.fc35                    @docker-ce-stable
docker-ce-rootless-extras.x86_64                  20.10.14-3.fc35                      @docker-ce-stable
docker-compose.noarch                             1.29.2-3.fc35                        @fedora
docker-scan-plugin.x86_64                         0.17.0-3.fc35                        @docker-ce-stable
```

now, I no longer have this error:

```
Error: EMFILE: too many open files, open '/home/git/gitlab/node_modules/.cache/compression-webpack-plugin/tmp/64ab441a'
error Command failed with exit code 1.
```

I close this issue.

**Comment by p12tic** [comment]
I've got hit by this bug on podman. `podman build` uses lower file limit than `podman run` (see https://github.com/containers/podman/issues/21912).

This limit can be increased by passing `--ulimit=nofile=1048576:1048576` to podman build.
