### ISSUE TITLE
GitLab doesn't add Port-Number on links

### ISSUE THREAD

**Issue by theoneandonly-vector** [sameersbn/docker-gitlab#2497]
I have a nginx-reverse-proxy configured (with public 8443 port) in front of gitlab

using docker-compose.override.yml I pass
    - GITLAB_PORT=8443

when I access "https://myhost.tld:8443/users/sign_in" it loads.
but everyhting else redirects me to "https://myhost.tld/"
 
docker-compose config | grep GITLAB_PORT shows my '8443' correctly

**Comment by theoneandonly-vector** [comment]
the problem is that a few links / redirects point at the unencrypted port 80 which is serving osmething else on another host. but why is somehting like "http://git.myhost.tld/users/sign_in" being accessed when logging out without https? or better.. how can I change that?

**Comment by desnij** [comment]
I dont know if you have fixed this yet... You also need to set the _GITLAB_HTTPS_.  However, once you have done this you will also need to flush your browser cache and any links you have saved ( this part can be a pita). 
These should also be interesting to note for anyone with similar issues.
``` yaml
 - GITLAB_HTTPS=true
 - SSL_SELF_SIGNED=true
 - GITLAB_HOST=myhost.tld
 - GITLAB_PORT=8443
```
If you wish to debug this on the running gitlab container, you can look in /etc/nginx/sites-enabled
Also, the scripts called by the entrypoint can be found here /etc/docker-gitlab, if that helps focus your debugging lights ;)

Good luck

**Comment by theoneandonly-vector** [comment]
Hi, I created my own config with the gitlab-omnibus docker. there it was working without any issues.
