### ISSUE TITLE
Error: Invalid data directory for cluster 12 main

### ISSUE THREAD

**Issue by sprucify** [sameersbn/docker-gitlab#2508]
Before upgrading from sameersbn/gitlab:14.6.3 to sameersbn/gitlab:14.7.0 I took a snapshot of my entire VPS.

14.6.3 was working fine, but 14.7.0 gives me a postgres error:
`postgresql_1  | Initializing certdir...
postgresql_1  | Initializing logdir...
postgresql_1  | Initializing rundir...
postgresql_1  | Setting resolv.conf ACLs...
postgresql_1  | ‣ Setting postgresql.conf parameter: data_directory = '/var/lib/postgresql/12/main'
postgresql_1  | ‣ Setting postgresql.conf parameter: log_directory = '/var/log/postgresql'
postgresql_1  | ‣ Setting postgresql.conf parameter: log_filename = 'postgresql-12-main.log'
postgresql_1  | ‣ Setting postgresql.conf parameter: ssl = 'off'
postgresql_1  | Creating database user: gitlab
postgresql_1  | Error: Invalid data directory for cluster 12 main
postgresql_1  | Error: Invalid data directory for cluster 12 main
gitlab_postgresql_1 exited with code 1
`

So I decided to restore my VPS snapshot, but now also 14.6.3 gives me the same error.

Could it be some form of diskspace issue?

**Comment by sachilles** [comment]
I think that at least the postgres container has problems with its data directory. The cause can be very diverse, e.g.

* an incorrectly mapped data directory,
* incorrect permissions for the file `postgresql.conf`,
* missing `postgresql.conf`,
* incomplete upgrade of the postgresql container.

This list is fairly incomplete. Can you recall any changes related to the postgres container before or during the update?

**Comment by sprucify** [comment]
I think the error condition was created while 14.6.3 was running perfectly.
And that it only would show up when I rebooted the entire server (which I didn't)

I made a snapshot from my entire VPS server while 14.6.3 was running.
After upgrading to 14.7.0 I got the error.
Restoring the snapshot reboots my server 
And after that 14.6.3 also had the same error.

I remembered that I had done a `docker prune` command after 14.6.3 was upgraded.
This normally only clean up unused images.

So what errors can occur inside a postgresql container while gitlab is running perfectly?

**Comment by sprucify** [comment]
Somehow my postgresql.conf file inside the volume `/var/lib/docker/volumes/gitlab_postgresql-data/_data/12/main` is 0 bytes
Is there a way to repair this?

**Comment by sprucify** [comment]
I got things working again.
I got inside cluster 11 `/var/lib/docker/volumes/gitlab_postgresql-data/_data/12/main` and did a ` mv postgresql.conf ../../12/main/`

**Comment by sachilles** [comment]
This sounds like an issue while upgrading the postgresql setup, since the directories you are mention include the postgresql version (`_data/11/main` for postgresql 11 vs. `_data/12/main` for postgresql 12).

If your issue belongs to a version upgrade of postgresql, be careful since upgrading major PostgreSQL versions requires some extra maintenance. This might not be visible by using docker images, however for native host installations there are several ways to upgrade (see for instance <https://wiki.archlinux.org/title/PostgreSQL#Upgrading_PostgreSQL>).
