### ISSUE TITLE
Compliments

### ISSUE THREAD

**Issue by RomkeVdMeulen** [sameersbn/docker-gitlab#251]
Amazing! I would not have believed it if I hadn't seen it with my own eyes. This has got to be the most painless gitlab deploy I've ever done. This docker image is truly a marvel of engineering.

I'm sorry to abuse the issue system for this, but I could not rest without giving you my thanks for taking messy work that used to take up entire afternoons and compressing it into a few minutes.

Well done sir!

**Comment by rtrauntvein** [comment]
+1

**Comment by gaving** [comment]
:+1:

**Comment by schmunk42** [comment]
Thank you very @sameersbn  much also from my side, I can only second everything @Romke-vd-Meulen said!

**Comment by sameersbn** [comment]
i'm glad you guys like my work. thanks.

**Comment by grossjonas** [comment]
+1

**Comment by adamlc** [comment]
:+1: from me too! Takes 2 mins to do upgrades now :)

**Comment by jlachowski** [comment]
And from me, it's really a marvellous thing :)

**Comment by sameersbn** [comment]
@adamlc that's right. gitlab inside docker makes upgrades a breeze. Planning of adding similar functionality to my redmine image.

**Comment by DinosaurDad** [comment]
Completely agree with the thumbs up. This is fantastic, and raised the bar on image design and reusability. Only improvement I can think of is to base each of its parts (gitlab, redis, postgresql) on [phusion baseimage](http://phusion.github.io/baseimage-docker/) to make them smaller and lighter.

Thanks @sameersbn!

**Comment by DaveDavenport** [comment]
Thanks for the fantastic work.  It is very nice. :+1:

**Comment by hourliert** [comment]
Thanks a lot. No more pain with gitlab now!

**Comment by chanmix51** [comment]
Almost no pain, but less pain than normal install by far !

**Comment by tbeg** [comment]
Great! Thanks!

**Comment by jeremyvilleneuve** [comment]
Yes! Wonderful work! Thanks for your contributions to the community!
