### ISSUE TITLE
Security updates

### ISSUE THREAD

**Issue by bor8** [sameersbn/docker-gitlab#2513]
Hi,

when are versions 14.8.2 (or 14.7.4) available?

https://about.gitlab.com/releases/2022/02/25/critical-security-release-gitlab-14-8-2-released/

Kind regards

**Comment by kkimurak** [comment]
PR is going on #2512 - so please comment there, not in new issue.
If you're in hurry, just consider to build image by yourself or migrate to official image.

**Comment by bor8** [comment]
Thanks!
