### ISSUE TITLE
GITLAB_PORT not reflected in .well-known/openid-configuration

### ISSUE THREAD

**Issue by desnij** [sameersbn/docker-gitlab#2514]
( first thanks to Sameer, and everyone contributing, this is one of my favorite projects :bouquet:   )

The `.well-known/openid-configuration` reflects the correct `issuer`, however, it does not use the **GITLAB_PORT** option for `authorization_endpoint, token_endpoint, revocation_endpoint, introspection_endpoint, userinfo_endpoint, jwks_uri` 

**This may be a gitlab issue and not this project?**  I have been looking at the code, however my comprehension of Aramaic is better than ruby.

docker-compose.yml contains 
``` yaml
 - GITLAB_HTTPS=true
 - SSL_SELF_SIGNED=true
 - GITLAB_HOST=gitlab.domain
 - GITLAB_PORT=1443
 - GITLAB_SSH_PORT=10022
```
`curl https://gitlab.domain:1443/well-known/openid-configuration` lacks 1443 in most uris
``` json
{
  "issuer": "https://gitlab.domain:1443",
  "authorization_endpoint": "https://gitlab.domain/oauth/authorize",
  "token_endpoint": "https://gitlab.domain/oauth/token",
  "revocation_endpoint": "https://gitlab.domain/oauth/revoke",
  "introspection_endpoint": "https://gitlab.domain/oauth/introspect",
  "userinfo_endpoint": "https://gitlab.domain/oauth/userinfo",
  "jwks_uri": "https://gitlab.domain/oauth/discovery/keys",
...
```
My grep research, seemingly related.
1. ./config/application.rb: contains `origins Gitlab.config.gitlab.url`
1. ./config/initializers/default_url_options.rb:
1. ./config/routes.rb: `.well-known/openid-configuration`
1. ./vendor/bundle/ruby/2.7.0/gems/openid_connect-1.3.0/lib/openid_connect/discovery/provider/config/response.rb

**Comment by kkimurak** [comment]
Sorry but we have not set up configuration variables for openid authentication yet.  
We need to :
- add required variables to `production` ->  `omniauth` -> `provider` section of [assets/runtime/config/gitlabhq/gitlab.yml](https://github.com/sameersbn/docker-gitlab/blob/739480e81d20b3fc5f3f5a721fde1a4a4041de44/assets/runtime/config/gitlabhq/gitlab.yml#L923-L1018)
- add a function (with a name like `gitlab_configure_oauth_openid()`) to [assets/runtime/function](https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/functions#L458-L726) to update (if variables are set) or delete (vice versa) those settings 

Most of things to do is similar to other oauth provider.  

P.S. I have never searched detail so I'm not sure but does openid is supported by `omniauth-oauth2-generic`? If so, configuration parameters for them are ready (see `OAUTH2_GENERIC_*` in [README.md](https://github.com/sameersbn/docker-gitlab#available-configuration-parameters))

**Comment by desnij** [comment]
Thank you for your response. This looks like something I can contribute.  It might take a while for me to get the time to do this but it is in my requirements so once I get it working I will contribute
thanks.
