### ISSUE TITLE
To heavy on the 2> /dev/null ?

### ISSUE THREAD

**Issue by xeor** [sameersbn/docker-gitlab#252]
I just got bitten by the `2> /dev/null` at https://github.com/sameersbn/docker-gitlab/blob/master/assets/init#L728 hiding a very small but important error. postgres tried to tell me that it didn't get a password input... (A very simple fix as I just had forgotten to set `DB_PASS`)

Trying to start the container normally just ended in a silent death after it checked that it got an db connection.

There are a couple of dev/null error redirects. Should they be there? It really can screw with you hiding simple mistakes..

**Comment by sameersbn** [comment]
@xeor you are correct.

**Comment by xeor** [comment]
Awesome... What about the original `2>` that bit me? :) The one at https://github.com/sameersbn/docker-gitlab/blob/master/assets/init#L728

**Comment by sameersbn** [comment]
@xeor i seemed to have missed so of the redirections. now fixed.
