### ISSUE TITLE
GITLAB_SSH_PORT seems borked

### ISSUE THREAD

**Issue by gionn** [sameersbn/docker-gitlab#253]
Hi,

I have set GITLAB_SSH_PORT to an high port since the default 22 is already used (I am using host networking, so there is the host sshd running on 22), but it looks like it isn't properly pushed where it should:

```
2015-02-05 11:17:29,192 INFO spawned: 'sshd' with pid 296
2015-02-05 11:17:29,211 INFO exited: sshd (exit status 255; not expected)
2015-02-05 11:17:31,215 INFO spawned: 'sshd' with pid 297
2015-02-05 11:17:31,232 INFO exited: sshd (exit status 255; not expected)
2015-02-05 11:17:34,237 INFO spawned: 'sshd' with pid 298
2015-02-05 11:17:34,254 INFO exited: sshd (exit status 255; not expected)
2015-02-05 11:17:35,255 INFO gave up: sshd entered FATAL state, too many start retries too quickly
```

If I attach the container, I see that /etc/ssh/sshd_config contains:

```
Port 22
```

**Comment by sameersbn** [comment]
@gionn sshd inside the gitlab image listens on port `22` only. This is not changed when you set `GITLAB_SSH_PORT`. The `GITLAB_SSH_PORT` indicates on which port the SSH server is accessible to the outside world.

This works fine when the default docker networking is used. With host networking, however, this is bound to fail when port `22` or other ports like `80` or `443` are in use.

The question is whether the listening ports of the ssh and nginx servers should reflect the `GITLAB_PORT` and `GITLAB_SSH_PORT` configuration. This is easy to achieve, but would require a lot of testing to make sure nothing breaks.

The only other alternative  is to not use host networking. I understand using host networking for some applications, but why do you want to use host networking with the gitlab image?

**Comment by gionn** [comment]
The real reason I am using host networking is because of lack on docker side of an API to recreate the iptables rules on-demand, since I have an iptables firewall configured on host machine and all chains get flushed everytime it applies a new configuration, breaking the docker exposed ports.

I can easily workaround this by manually changing the */etc/ssh/sshd_config*, so it is not a problem, I was just expecting that GITLAB_SSH_PORT would reflect directly on sshd config, thanks for your clarifications.

**Comment by sameersbn** [comment]
@gionn i was able to get around that by adding the following rules.

```bash
-A POSTROUTING -s 172.17.0.0/24 ! -d 172.17.0.0/24 -j MASQUERADE
-A POSTROUTING -s 172.17.42.0/24 ! -d 172.17.42.0/24 -j MASQUERADE
```

**Comment by sameersbn** [comment]
@gionn before adding these rules the rules added by docker used to get flushed everytime i made some changes to my firewall config. This is now no longer the case. I hope this helps

**Comment by gionn** [comment]
Yup, re-adding MASQUERADE rules is a trivial fix to make network working again, but as I've stated on the last message the problem is for exposed ports.

It may be possible to use the docker API to enumerate over all active containers and retrieve the exposed ports, and then manually re-create the port forwarding rules, but I never dig into it.

However, many thanks for your interest!
