### ISSUE TITLE
latest-image fails to start puma and sidekiq (NameError: uninitialized constant RQRCode::QRCode")

### ISSUE THREAD

**Issue by smoebody** [sameersbn/docker-gitlab#2537]
Using the `latest` tag startup of puma and sidekiq are not working and give me the following error:
```
...
Unable to load application: NameError: uninitialized constant RQRCode::QRCode"}
...
```

appearently the  `latest` tag is not the same as `14.9.2`. 

sameersbn/gitlab:latest
Digest:sha256:52c3621541e2e553a3f7688f30a81f5c95548003db3c27b2c5fcaba773ed7345

sameersbn/gitlab:14.9.2
Digest:sha256:2e37b30ac6a86fc1f7a753e900ee2c75a09e929cb5a80d8d7c5759ab118dd806

using the version tag all works fine. is this intended?

cheers

**Comment by sachilles** [comment]
Hi,

using tagged versions will be much more better than using the tag latest. Images tagged by latest correspond (in general) to the latest commit in the master branch (which is used to integrate PRs) and is thus WIP. Specific version tags are mostly fixed.

Hopefully this helps.
