### ISSUE TITLE
Uploads Object Storage in GCP enviroment not working

### ISSUE THREAD

**Issue by Syphon83** [sameersbn/docker-gitlab#2538]
Hi everyone, 

I found a bug in the setting of the  object storage bucket for UPLOADS in a Google Cloud enviroment. 

All the below variables are never used. 
GITLAB_UPLOADS_OBJECT_STORE_CONNECTION_GOOGLE_PROJECT
GITLAB_UPLOADS_OBJECT_STORE_CONNECTION_GOOGLE_CLIENT_EMAIL
GITLAB_UPLOADS_OBJECT_STORE_CONNECTION_GOOGLE_JSON_KEY_LOCATION

In the uploads section of the gitlab.yml configuration file for the object storage, ARTIFACTS variables are used instead of the uploads ones. 

Thank you

**Comment by sachilles** [comment]
Close this issue because the corresponding PR is merged.
