### ISSUE TITLE
Push warning with 14.10.0: core.fsyncObjectFiles is deprecated

### ISSUE THREAD

**Issue by mikehaertl** [sameersbn/docker-gitlab#2547]
Since I've upgraded from 14.3.0 to 14.10.0 I see a warning whenever I push to a repository:

```
$ git push origin master 
warning: core.fsyncObjectFiles is deprecated; use core.fsync instead
Everything up-to-date
```

My local git configuration is fine: I don't have `core.fsyncObjectFiles` configured. I also can push to other repositories without this message.

In the container logs I see this message after pushing:

> 2022-04-26 12:35:11,847 INFO reaped unknown pid 6588

I've also grepped inside the container where this option is set but couldn't really find anything. There's also no related issue on GitLab.

Anyone else seeing this?

**Comment by mikehaertl** [comment]
Here's a probably related issue for gitaly: https://gitlab.com/gitlab-org/gitaly/-/issues/4117

They'll hopefully fix this with 15.0.0

**Comment by gjrtimmer** [comment]
@kkimurak @sameersbn Please overwrite version `14.10.0 ` I don't think its good practice to distribute corrupt / non working images

**Comment by kkimurak** [comment]
@gjrtimmer Im just a contributer so I have no permission to do that.

**Comment by mikehaertl** [comment]
Just upgraded to 14.10.2 and the warning seems to be gone now.
