### ISSUE TITLE
Does sameersbn/gitlab:14.10.1 use the same source code of gitlab with gitlab/gitlab-ce:14.10.1 ?

### ISSUE THREAD

**Issue by zengqingfu1442** [sameersbn/docker-gitlab#2559]
Only considering the features of gitlab, does sameersbn/gitlab:14.10.1 use the same source code of gitlab with gitlab/gitlab-ce:14.10.1 ? And does sameersbn/gitlab:14.10.1 support the features which are not available on **gitlab-ce** but available on **gitlab-ee** ? Thanks.

**Comment by kkimurak** [comment]
1. Not exactly. This, `sameersbn/gitlab:14.10.1` uses corresponding version of gitlab-foss (gitlab-ce) but modifies some of the code during build (for example : https://github.com/sameersbn/docker-gitlab/blob/7a2d308aa3c07321b947d58f11884d4745c09036/assets/build/install.sh#L162-L169)

2. No. It only supports gitlab-ce feature. There is a pull request to support gitlab-ee - see #2329
