### ISSUE TITLE
I use docker-compose to deploy sameersbn/gitlab:14.10.1 but gitlab is not accessible.

### ISSUE THREAD

**Issue by zengqingfu1442** [sameersbn/docker-gitlab#2560]
I use this file https://github.com/sameersbn/docker-gitlab/blob/14.10.1/docker-compose.yml and only changed the volumes path for my machine and use my own generated 64 long random characters for **GITLAB_SECRETS_DB_KEY_BASE**, **GITLAB_SECRETS_SECRET_KEY_BASE**, **GITLAB_SECRETS_OTP_KEY_BASE** and uses my machine's IP address which is a private IP for **GITLAB_HOST**, and also set the smtp server, then I use `docker-compose up -d` , the 3 containers are all up, but I cannot access the gitlab server using the IP address and 10080 port.  Why?

**Comment by kkimurak** [comment]
Some browsers such as chrome, firefox and so on may blocks accessing to 10080 port for security reason. Could you test different port

**Comment by zengqingfu1442** [comment]
> Some browsers such as chrome, firefox and so on may blocks accessing to 10080 port for security reason. Could you test different port

Thank you, it's OK after I changed to 80 port.
