### ISSUE TITLE
CircleCI worker image deprecation & EOL

### ISSUE THREAD

**Issue by kkimurak** [sameersbn/docker-gitlab#2563]
We use CircleCI to build / test / publish images in this repository. The orb currently used is `circleci/docker@1.0.1`, and the executor `docker/machine` for `circleci-docker@1.0.1` is based on ubuntu 16.04 (seems to [`ubuntu-1604:201903-01`](https://github.com/CircleCI-Public/docker-orb/blob/60fc972340fa31dbc50e6d5482f3b9c91ccd186b/src/executors/machine.yml#L8). Latest version available today 2022-05-13 is [`circleci/docker@2.1.1`](https://circleci.com/developer/orbs/orb/circleci/docker) and `docker-machine` is based on [`ubuntu-2004:202107-02`](https://github.com/CircleCI-Public/docker-orb/blob/281e5572b6e9e6f002d25d0113e80c0eedac1460/src/executors/machine.yml#L8)

https://github.com/sameersbn/docker-gitlab/blob/cf3cb35b6136dd2fa30366bf513b1884a69d2c34/.circleci/config.yml#L3-L6

As ubuntu 16.04 have reached to EOL, CircleCI announced that an EOL for ubuntu 16.04-based images will be Tuesday, May 31, 2022. We have to migrate to newer image by then.

Here is a email from CircleCI team.

> ---------- Forwarded message ---------
> From: CircleCI Ops <salesops@circleci.com>
> Subject: [Action Required] Ubuntu 16.04 machine image Deprecation & EOL
> 
> 
> Hello,
> 
> We are deprecating Ubuntu 16.04-based machine images on CircleCI in preparation for an EOL on Tuesday, May 31, 2022 to ensure your builds remain secure. For a detailed overview of how this will affect your workflow, [read the blog article here](https://go.circleci.com/NDg1LVpNSC02MjYAAAGCndarQhQBGwyugUjw_56rL0H0D3hwkTaKz4k2qs57_gB-zp-bje0BynLJLD1H1y4aEGpJbiY=).
> 
> We will also be conducting temporary brownouts on Tuesday, March 29, 2022, and again on Tuesday, April 26, 2022 during which these images will be unavailable.
> 
> We are contacting you because one or more of your projects has a job that uses an Ubuntu 16.04-based image.
> 
> The project(s) using an image based on Ubuntu 16.04 are:
> 
>     [docker-gitlab]
> 
> If you have specified an Ubuntu 16.04-based image please see our [migration guide](https://go.circleci.com/NDg1LVpNSC02MjYAAAGCndarQt37MF2OuRIDyrDTltVILMAMM7S4aFfxdAFXD_h1Yysf6PhhJTFtyUmK2nOzzMBeFEA=) to upgrade to a newer version of Ubuntu image in order to avoid any service disruption during the brownout & subsequent EOL.
> 
> We will also be releasing a CircleCI Ubuntu 22.04 image on April 22nd offering the flexibility to upgrade to the latest LTS version of Ubuntu image before we remove older versions permanently. A beta version of the image will be available March 21st.
> 
> Our team is committed to getting you the most performant builds while maintaining security.
> 
> Reply [here](https://go.circleci.com/NDg1LVpNSC02MjYAAAGCndarQnvKZzBsr0hvckRhR3MNsC68QQZn1_h3YJ86PZfmTdebIIkwnAUHHKCFZ4EXkP8lf7s=) to set up time with your Customer Success Manager if you have any further questions.
> 
> To better building,
> Ricardo N. Feliciano
> Community Partner Engineer at CircleCI

**Comment by sachilles** [comment]
Could you be so kind and check the corresponding PR?

**Comment by kkimurak** [comment]
Thank you, I'll check the PR this weekend.

**Comment by sachilles** [comment]
Thanks for your approval.
