### ISSUE TITLE
Can't create repository when using custom volume with boot2docker

### ISSUE THREAD

**Issue by sydneyhenrard** [sameersbn/docker-gitlab#259]
Win 8.1 using boot2docker.

I created 2 containers, one with no volume (default one) and one with a custom volume.

Source: http://stackoverflow.com/questions/27006643/docker-external-file-access-not-in-users-on-osx
I created a shared folder in the boot2docker-vm 
```
vboxmanage sharedfolder add "boot2docker-vm" --name settings-share --hostpath  k:\home\gitlab --automount
```

Then mount that shared folder in the boot2docker-vm.

```
$ sudo mkdir /settings-share-on-guest
$ sudo mount -t vboxsf settings-share /settings-share-on-guest
```

Run the container with

```
docker run --name='gitlab-ok' -i -t -e 'GITLAB_BACKUPS=daily' -e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=10022' -p 10022:22 -p 10080:80 -v /var/run/docker.sock:/run/docker.sock -v $(which docker):/bin/docker -v /settings-share-on-guest:/home/git/data sameersbn/gitlab:7.7.2
```

I can see in `k:\home\gitlab` the data for gitlab. The I try to create project and I get an error message saying that the repository cannot be created.

So I try to run a container with no volume.

```
docker run --name='gitlab-no-volume' -i -t -e 'GITLAB_BACKUPS=daily' -e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=10022' -p 10022:22 -p 10080:80 -v /var/run/docker.sock:/run/docker.sock -v $(which docker):/bin/docker sameersbn/gitlab:7.7.2
```

And everything works.

After some investigation, I compared the `/home/git/data` for both containers. I found out that the permissions are differents. So I guess that's the reason. I tried to change the permissions using `chmod` and `chown` but nothing works. I guess it's because the shared folder is on Windows.

No Volume:
```
root@1b6c090c780f:/home/git/data# ls -al
total 36
drwxr-xr-x 9 git  git  4096 Feb 15 20:27 .
drwxr-xr-x 8 git  git  4096 Feb 15 20:27 ..
drwx------ 2 git  git  4096 Jan 30 06:35 .ssh
drwxr-xr-x 2 git  git  4096 Feb 15 20:27 backups
drwxr-x--- 2 git  git  4096 Feb 15 20:27 gitlab-satellites
drwxrws--- 3 git  git  4096 Feb 15 20:30 repositories
drwxr-xr-x 2 root root 4096 Feb 15 20:27 ssh
drwxr-xr-x 4 git  git  4096 Feb 15 20:27 tmp
drwxr-xr-x 2 git  git  4096 Feb 15 20:27 uploads
```

Share folder volume:
```
root@6df30df6ea87:/home/git/data# ls -al
total 12
drwxrwxrwx 1 root root 4096 Feb 15 20:12 .
drwxr-xr-x 8 git  git  4096 Feb 15 20:33 ..
drwxrwxrwx 1 root root    0 Feb 15 20:09 .ssh
drwxrwxrwx 1 root root    0 Feb 15 20:09 backups
drwxrwxrwx 1 root root    0 Feb 15 20:09 gitlab-satellites
drwxrwxrwx 1 root root    0 Feb 15 20:20 repositories
drwxrwxrwx 1 root root 4096 Feb 15 20:09 ssh
drwxrwxrwx 1 root root    0 Feb 15 20:09 tmp
drwxrwxrwx 1 root root    0 Feb 15 20:09 uploads
```

**Comment by sameersbn** [comment]
@sydneyhenrard yes, this has something to with the shared folder on a NTFS filesystem. `chown` and `chmod` does not work on NTFS filesystems (including FAT32, etc.)

Gitlab seems to perform some filesystem checks while creating the repository, which seems to error out. There is nothing that we can do in the image to fix this issue.

**Comment by grahampugh** [comment]
It is also the case on OS X using Docker-machine (which uses boot2docker) that the chown commands fail. Therefore it doesn't appear possible to use this docker container persistently on a Mac.

**Comment by sameersbn** [comment]
its a filesystem thing. If you can create an ext partition and use that for the persistence then it should probably work. Alternatively you can create a separate volume in virtualbox for the persistent data.

There is nothing that can be done in the image to resolve this as it is an issue with the environment. For proper functioning, GitLab expects that files and directories have specific ownerships and permissions.
