### ISSUE TITLE
healthcheck not works

### ISSUE THREAD

**Issue by Srobin2020S** [sameersbn/docker-gitlab#2591]
If use in docker-compose 
healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m

and container always starting

Fix: need change to http protocol in line:
url=http://localhost/-/liveness

**Comment by hongeinh** [comment]
Have you tried to set the start_period to be a bit longer ? I faced the same issue when i set the start_period too soon. 
Got the health check to work when i changed the start_period to 15m

**Comment by Re4zOon** [comment]
Hi,

The URL is fine.
Its automatically generated here:
https://github.com/sameersbn/docker-gitlab/blob/32d0e27bda23b44c1a60faf27df68cafb15b724b/assets/runtime/functions#L1683

It uses http (unless you set the gitlab_https to true) and uses the URL you meantioned:
url=${HEALTHCHECK_PROTOCOL}://localhost${GITLAB_RELATIVE_URL_ROOT}/-/liveness

There is nothing to fix here, check your logs why it doesn't respond with http 200 (thats the only thing the healthcheck does) after 20 minutes (5 min start + 3*5 min check).

**Comment by Srobin2020S** [comment]
Hi,
I changed GITLAB_HTTPS=false and have status "healthy"
