### ISSUE TITLE
Quickstart not working

### ISSUE THREAD

**Issue by mko-x** [sameersbn/docker-gitlab#260]
Thanks for the great work, I was using it over months with different configurations.

Regretfully the image is unusable for me now for whatever reason.

Would have liked to reuse my former settings, but they didn't seem to work - no way. So I tried a minimal config with ext redis and postgresql, matching my requirements. See:

docker run --name db-git -d \
  -e 'DB_NAME=gitlabhq_production' \
  -e 'DB_USER=gitlab' \
  -e 'DB_PASS=jackson5famoustsong'\
  -v /opt/dockx/db/data:/var/lib/postgresql \
  sameersbn/postgresql:latest

docker run -d --name kv-git \
  sameersbn/redis:latest

docker run -d --name srv-git \
  --link db-git:postgresql \
  --link kv-git:redisio \
  -v /opt/dockx/gitlab/core/data:/home/git/data \
  -e 'GITLAB_HOST=das-repo.de' -e 'GITLAB_EMAIL=git@das-repo.de' \
  -e 'SMTP_USER=mymail' -e 'SMTP_PASS=alphabetagamma' \
  -e 'GITLAB_SSH_PORT=4242' \
  -e 'GITLAB_PORT=443' \
  -e 'GITLAB_HTTPS=true' \
  sameersbn/gitlab

I renamed and copied the ssl files to gitlab.** at the target path at host. I keep retrieving errors about starting the container. I just bought a new one for the used domain, it is valid and now I do not have any idea what to do.

Repeating error #01:

FATA[0000] Error response from daemon: Cannot start container 637cace45fedc95fe214c2e93034acea6bf5ff560aebe90811e10f44fe749c02:  (exit status 1) 

I tried to remove my customizations to identify the error's cause without success. So tried your quickstart sample and must notice that it didn't work either:

Repeating error #02:
CALL:
{ruse@dom}:02:35 # docker run -d --name srv-git \
>   --link db-git:postgresql \
>   --link kv-git:redisio \
>   -v /opt/dockx/gitlab/core/data:/home/git/data \
>   -e 'GITLAB_HOST=das-repo.de' -e 'GITLAB_EMAIL=git@das-repo.de' \
>   -e 'GITLAB_SSH_PORT=4242' \
>   sameersbn/gitlab
3f55dd3d13f52a2fe025f384df356dd9d95bcb87bd9ecec4b508bad147be373e
FATA[0000] Error response from daemon: Cannot start container 3f55dd3d13f52a2fe025f384df356dd9d95bcb87bd9ecec4b508bad147be373e:  (exit status 1) 

I was using latest - last try I used the 7.7.2 version - but without success.

I would really like to keep this image, maybe I'm to dumb, but I don't see my mistake. I was creating a new plain server instance, trying the quickstart suggested 1:1 from the info page to ensure exclusion of my changes.
Output again:

docker run --name='gitlab' -it --rm \
> -e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=10022' \
> -p 10022:22 -p 10080:80 \
> -v /var/run/docker.sock:/run/docker.sock \
> -v $(which docker):/bin/docker \
> sameersbn/gitlab:7.7.2
Unable to find image 'sameersbn/gitlab:7.7.2' locally
Pulling repository sameersbn/gitlab
78ac51e6fdf8: Download complete 
511136ea3c5a: Download complete 
53f858aaaf03: Download complete 
837339b91538: Download complete 
615c102e2290: Download complete 
b39b81afc8ca: Download complete 
a9d82619e13b: Download complete 
6ee48d1a59b6: Download complete 
3113ca2df33a: Download complete 
c9a62520eb96: Download complete 
92e4a72f5826: Download complete 
5a798d839452: Download complete 
40e324110ad1: Download complete 
86ed694281b6: Download complete 
d6e369f05288: Download complete 
9b6e779ae08f: Download complete 
1ab66e1d8e19: Download complete 
bf7dd00390db: Download complete 
84d30bdad4b1: Download complete 
b7ac55e6faa6: Download complete 
d3a82286e9af: Download complete 
7dc8f379ae6d: Download complete 
Status: Downloaded newer image for sameersbn/gitlab:7.7.2
FATA[0155] Error response from daemon: Cannot start container 4e2ca25775c9a829cf46c05d082548daaddbbfdd3eb5fd263e6f02e01e8e2fcf:  (exit status 1) 

My docker version output
# docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

and my local docker info
 docker info
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-202:0-132680-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Metadata Space Used: 733.2 kB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.14.18-x86_64-jb1
Operating System: Ubuntu 14.04.1 LTS
CPUs: 3
Total Memory: 1.948 GiB
Name:***box.net
ID: ***:MWQX

I'm not able to find a way out of this problem, so if someone could help me, feel free to contact me.

Warm Reagrds
Markus

**Comment by sameersbn** [comment]
@mko-x This is probably some issue with docker.

First please make sure a container with name `srv-git` does not already exist `docker ps -a | grep srv-git`. If it does, stop it `docker stop srv-git` and then remove it `docker rm srv-git`.  Next make sure the `db-git` and `kv-git` containers exist. `docker ps -a | grep db-git`, `docker ps -a | grep kv-git`. Docker will fail to start a container if any of the linked containers are missing. Once you have verified this, try starting the gitlab container.

If this does not help, there is a possibility that docker has encountered a bug. Collect whatever information you can regarding this state and reboot the machine and retry. If it works, there was an issue with docker. Report the issue at the docker project providing all the information you gathered before the reboot.

Either ways, the issue is not with the image. Docker does not seem to start the container in the first place.

I also tested your commands locally and had no issues.

```bash
# start postgresql
docker run --name db-git -it --rm \
-e 'DB_NAME=gitlabhq_production' \
-e 'DB_USER=gitlab' \
-e 'DB_PASS=jackson5famoustsong' \
sameersbn/postgresql:latest

# start redis
docker run -it --rm --name kv-git \
sameersbn/redis:latest

# start gitlab
docker run -it --rm --name srv-git \
--link db-git:postgresql \
--link kv-git:redisio \
-e 'GITLAB_HOST=das-repo.de' -e 'GITLAB_EMAIL=git@das-repo.de' \
-e 'SMTP_USER=mymail' -e 'SMTP_PASS=alphabetagamma' \
sameersbn/gitlab
```
Everything works as expected.

**Comment by mko-x** [comment]
Thank you very much in advance!

I will give your suggestions a try and report the results here.

**Comment by mko-x** [comment]
Working great again for almost a month without problems. Thank you once more.
Closing.
