### ISSUE TITLE
Cannot create a new project using the gui after upgrading gitlab from 15.0.3 to 15.1.1

### ISSUE THREAD

**Issue by cheewah-cd** [sameersbn/docker-gitlab#2606]
After upgrading from 15.0.3 to 15.1.1, when i try to create a new project from the gui, the create page doesn't show out.
I ran a health check and everything looks fine.

**Comment by tDo** [comment]
Maybe this could happen because of https://gitlab.com/gitlab-org/gitlab/-/merge_requests/91282 which might get fixed as soon as this project is updated to 15.1.2 via https://github.com/sameersbn/docker-gitlab/pull/2605

(Not 100% sure on this, but it looks like a possible culprit)

**Comment by cheewah-cd** [comment]
> Maybe this could happen because of https://gitlab.com/gitlab-org/gitlab/-/merge_requests/91282 which might get fixed as soon as this project is updated to 15.1.2 via #2605
> 
> (Not 100% sure on this, but it looks like a possible culprit)

Thanks for the quick update, will follow up on the issue

**Comment by cheewah-cd** [comment]
Issue fixed in version 15.1.2
