### ISSUE TITLE
M1 Mac Support?

### ISSUE THREAD

**Issue by tamanugi** [sameersbn/docker-gitlab#2612]
Hi, Thanks for awesome project ✨

I facing some issues. 

- Gitlab display 502 when `docker compose up`  
- `docker build -t sameersbn/gitlab github.com/sameersbn/docker-gitlab` is failed
    ```
    ...
    #8 259.7 GOBIN="/home/git/gitlab-shell/bin" go install -ldflags "-X main.Version=v14.7.4 -X main.BuildTime=20220728.053129" -tags "tracer_static tracer_static_jaeger continuous_profiler_stackdriver" -mod=mod ./cmd/...
    #8 259.7 qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
    #8 259.7 make: *** [Makefile:57: bin/gitlab-shell] Error 255
    ``` 

is not  support for M1 Mac?

**Comment by kkimurak** [comment]
If you get a 502 error, it seems that `sameersbn/gitlab` should be working on your M1 Mac so I think you don't have to build it. Please wait for a while (About 5 minutes when it is short, about 30 minutes when it is long) for the 502 error to disappear.   

Also note that running amd64 based image on an M1 Mac [emulates x86_64](, which should lead to poor performance. Therefore, the above waiting time may be further extended.

----

- It takes a while until 502 goes away (in my case with relative url enabled, typically takes 10 ~ 20 minutes). You may see "500 internal server error" if you have another issue (for example lacking / misunderstanding some configuration). Check `docker logs --follow <your gitlab image>`.
- At least now, we only provide AMD64 based image. As far as I've tried, the restriction only comes from golang. If you interested in building the image for other platform, please refer #2603.

**Comment by tamanugi** [comment]
@kkimurak 
Thanks quick reply. 
I  have confirmed that it works after long-long time 🎉 

> Also note that running amd64 based image on an M1 Mac emulates x86_64, which should lead to poor performance. Therefore, the above waiting time may be further extended.

uhhhhh ok 😇 
I will check #2603 after 👀 


Thanks!

**Comment by wlsc** [comment]
is there a possibility to have a proper ARM64 Docker image? emulation is very slow

**Comment by kkimurak** [comment]
Use `docker buildx`. See #2603
