### ISSUE TITLE
LDAP Login with SSL proxy fails

### ISSUE THREAD

**Issue by schmunk42** [sameersbn/docker-gitlab#263]
I have `docker-gitlab` running behind a SSL nginx proxy, configuration example:

```
GITLAB_HTTPS: true
LDAP_ENABLED: true
LDAP_HOST: 192.168.XX.XX
LDAP_PORT: 389
LDAP_METHOD: 'plain'
LDAP_ALLOW_USERNAME_OR_EMAIL_LOGIN: true
```

But I have to set `GITLAB_HTTPS: false` in order for my users to be able to login.
Which has the side effect, that all repo URLs are shown with HTTP instead of HTTPS and also the docs say I should set it to `true`.

But when I do so ... after LDAP login we see just a blank page with this URL `https://gitlab.ourdomain.com/users/auth/ldapmain/callback`

Is there another setting I've missed?

**Comment by jk** [comment]
It's probably a bug in 7.8.1 - I just upgraded from 7.8.0 (which was working fine) and I'm now said that my user is locked.

According to the [CHANGELOG](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CHANGELOG) they did change something in regard to LDAP: 
> - Fix the warning for LDAP users about need to set password

**Comment by jk** [comment]
I just downgraded to `7.8.0` and it works again. So for now you should try `7.8.0` until @sameersbn found a solution or it's fixed upstream.

**Comment by schmunk42** [comment]
K will try 7.8.0 - sorry I forgot to mention we're on 7.7.2

**Comment by sameersbn** [comment]
@schmunk42 @jk I suggest you file a bug at gitlab upstream.

**Comment by schmunk42** [comment]
fir reference: https://gitlab.com/gitlab-org/gitlab-ce/issues/1145

**Comment by sameersbn** [comment]
@schmunk42 @jk Were you able to get this issue resolved? Do the newer versions of gitlab exibit this issue?

**Comment by jk** [comment]
@sameersbn I've remigrated to the version in question and it went ok. I don't have any issues with LDAP support at the moment.

**Comment by sameersbn** [comment]
@jk ok. should we mark this issue resolved?

**Comment by jk** [comment]
@sameersbn Probably. If it's still an issue you can reopen the issue.

**Comment by sameersbn** [comment]
@jk cool.

**Comment by schmunk42** [comment]
Yep, it's fixed. I needed to add 

    X-Forwarded-Ssl: on

to my reverse proxy, see also https://gitlab.com/gitlab-org/omnibus-gitlab/issues/331#note_997411
