### ISSUE TITLE
Creating backups without removing the container

### ISSUE THREAD

**Issue by sydneyhenrard** [sameersbn/docker-gitlab#264]
Hi, 

In the documentation there is no mention of removing the container before creating a backup, just stoping it. If I don't remove the container, I get a conflict name error. So I removed the container before creating the backup and it's working.

I was wondering if I am doing something wrong, since the documentation does not mention removing the container.

```
docker@boot2docker:~$ docker run --name='gitlab' -i -t -e 'GITLAB_BACKUPS=daily' -e 'GITLAB_BACKUP_TIME=23:00'  -e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=10022' -p 10022:22 -p 10080:80 -v /var/run/docker.sock:/run/docker.sock -v $(whic
h docker):/bin/docker -v /home/docker/shared:/home/k/home/gitlab sameersbn/gitlab:7.8.1

docker@boot2docker:~$ docker stop gitlab
gitlab

docker@boot2docker:~$ docker run --name='gitlab' -i -t -rm -e 'GITLAB_BACKUPS=daily' -e 'GITLAB_BACKUP_TIME=23:00'  -e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=10022' -p 10022:22 -p 10080:80 -v /var/run/docker.sock:/run/docker.sock -v $(whic
h docker):/bin/docker -v /home/docker/shared:/home/k/home/gitlab sameersbn/gitlab:7.8.1 app:rake gitlab:backup:create

FATA[0000] Error response from daemon: Conflict, The name gitlab is already assigned to ef944cf28242. You have to delete (or rename) that container to be able to assign gitlab to a container again.

docker@boot2docker:~$ docker rm gitlab
gitlab

docker@boot2docker:~$ docker run --name='gitlab' -i -t --rm -e 'GITLAB_BACKUPS=daily' -e 'GITLAB_BACKUP_TIME=23:00'  -e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=10022' -p 10022:22 -p 10080:80 -v /var/run/docker.sock:/run/docker.sock -v $(whi
ch docker):/bin/docker -v /home/docker/shared:/home/k/home/gitlab sameersbn/gitlab:7.8.1 app:rake gitlab:backup:create
```

Thanks

**Comment by sameersbn** [comment]
@sydneyhenrard yes. you need to remove the existing gitlab container so that there are no name conflicts. If you want the old container to stay, then you would have to change the name of the new container.

**Comment by sameersbn** [comment]
@sydneyhenrard In the `latest` tag you can now run rake tasks on a running gitlab instance using `docker exec`. Please refer https://github.com/sameersbn/docker-gitlab#rake-tasks for information. However, I advise against running backup operations on a running gitlab instance since it is possible for the gitlab data to get updated while the backup is being created.
