### ISSUE TITLE
[nginx] Route uploads through GitLab to prevent XSS and enforce access control

### ISSUE THREAD

**Issue by Jack12816** [sameersbn/docker-gitlab#266]
The latest Gitlab version changed the nginx configuration to route all `/uploads/` request through the Gitlab application. We should do this also.

```
For installations from source, you will have to update your NGINX configuration.
We've added a route change for /uploads/. See the new config for /uploads/ here
for http and here for https.
```

Blog Post: https://about.gitlab.com/2015/02/22/gitlab-7-8-released/

See: https://gitlab.com/gitlab-org/gitlab-ce/blob/8ae3112b3f303c897c70952dd162589b1c394221/lib/support/nginx/gitlab#L59

**Comment by sameersbn** [comment]
@Jack12816 my visual diff program seems to have failed me. To be fair it did tell me that it could not parse the diff properly.

**Comment by Jack12816** [comment]
Oh, ok. I think its not a problem. :) Thanks for the great work!
