### ISSUE TITLE
Latest tag was not published for 15.6.0

### ISSUE THREAD

**Issue by umputun** [sameersbn/docker-gitlab#2666]
on [dockerhub](https://hub.docker.com/r/sameersbn/gitlab/tags):

<img width="1367" alt="rqswz-202211-25173623-62y9h" src="https://user-images.githubusercontent.com/535880/204063297-de0fff0c-3d4e-4ce7-86dd-5e930396c29c.png">

**Comment by Toka69** [comment]
I noticed the same thing. My Gitlab instance didn't update like every Saturday when there is a new release.

**Comment by sachilles** [comment]
Due to the considering the last three GitLab versions, there was a problem with the automatic assignment of the tag 'latest', which I couldn't fix easily.

In the meantime, however, the problem should no longer exist. Nevertheless, I apologize for the inconvenience that arose.
