### ISSUE TITLE
[README / Healthcheck] Shouldn't the check expect a 302 instead of a 200 ?

### ISSUE THREAD

**Issue by frenchbeard** [sameersbn/docker-gitlab#2677]
Hello, 

First of all, thanks for the work on this repo, have been using it for ages.

I just noted something on my deployment regarding the healthcheck currently implemented (and that I hadn't check for its status... ever) : when I curl localhost from within the container (as the script does), I get a 302 towards the sign_in page (which makes sense) but the healtcheck expects a 200. Am I missing something, or is the default configuration not Public, so 302 would be the actual default ?

**Comment by kkimurak** [comment]
302 would be the actual default. That's why we use [`--location` option for `curl` to follow redirect in healthcheck script](https://github.com/sameersbn/docker-gitlab/blob/24ca84395658731be39883d8ea808785769c4636/assets/runtime/functions#L1720-L1721).

**Comment by frenchbeard** [comment]
After coming back to the install itself, and checking the actual version of the local Git repository I skimmed through, it was still on a 13.X one, and didn't have that list of options. 
Thanks for the clarification, and I'll `git pull` before checking anything next time.
