### ISSUE TITLE
pg_dump: error: aborting because of server version mismatch

### ISSUE THREAD

**Issue by f-io** [sameersbn/docker-gitlab#2680]
Postgres 12 is deprecated and is scheduled for removal in GitLab 16.0.
https://docs.gitlab.com/ee/update/deprecations.html#postgresql-12-deprecated

Using this image with Postgres 13.8 (recommend/default for new installations) will end up in none working backups.  
Database dump (rake task) will fail with pg_dump missmatch.

```
pg_dump: error: server version: 13.8; pg_dump version: 12.13 (Ubuntu 12.13-1.pgdg20.04+1)
pg_dump: error: aborting because of server version mismatch
```

Due to the fact that this image use "postgresql-client-12" there is no pg_dump/restore available for 13.
https://github.com/sameersbn/docker-gitlab/blob/master/Dockerfile

Maybe we need to expose a new ENV to manage this and have both versions available or just make a breaking change?

**Comment by fhaefemeier** [comment]
I have the same issue. I use psql 14 as external database and has the same issue as described here.
