### ISSUE TITLE
Is Web IDE Beta available in 15.7+ build?

### ISSUE THREAD

**Issue by fidoedidoe** [sameersbn/docker-gitlab#2682]
In the release notes for 15.7.0, it suggests the following to Enable the Web IDE Beta: 

> To use the Web IDE Beta on a self-managed GitLab instance, ensure that the vscode_web_ide feature flag [is enabled](https://docs.gitlab.com/ee/administration/feature_flags.html).

Is there a docker environment variable to perform this currently - or will I have to set the flag as described above. If the latter, will the change persist through restarts restart?

Many thanks!!

**Comment by kingchun1991** [comment]
Same question here

**Comment by fidoedidoe** [comment]
Many thanks, this is great - I hadn't considered using the API.

**Comment by kkimurak** [comment]
As #2917 merged, `sameersbn/gitlab:16.10.1` or later contains the feature. You may want to set `GITLAB_FEATURE_FLAGS_ENABLE_TARGETS=vscode_web_ide`.
