### ISSUE TITLE
Gitlab is not ready to move to ruby v3

### ISSUE THREAD

**Issue by Daabramov** [sameersbn/docker-gitlab#2698]
Hi!

A couple of users have encountered a problem with JUnit running on versions 15.6.3+, there is an issue - https://gitlab.com/gitlab-org/gitlab/-/issues/385698. 
After investigating the problem, we found this - https://gitlab.com/gitlab-org/gitlab/-/issues/385698#note_1249613722

The cause of the problem: Gitlab is not yet ready to migrate to Ruby v3, but in community image this migration has already happened https://github.com/sameersbn/docker-gitlab/pull/2675

I suggest rolling back Ruby to version 2.7.7

**Comment by kkimurak** [comment]
Thank you for your reporting, there were a confusion on `RUBY_VERSION` we need to refer. PR #2699 is going on.

**Comment by Floyddotnet** [comment]
i can confirm, after downgrading back to ruby 2.7.7, it works now as before. thank you very much.

**Comment by sachilles** [comment]
I'm going to close this ticket now. Anyway thanks for your hints.
