### ISSUE TITLE
 GitLab Security Release: 15.8.1, 15.7.6, and 15.6.7

### ISSUE THREAD

**Issue by vkukk** [sameersbn/docker-gitlab#2709]
I'm interested in upgrading to 15.7.6, but it's not available yet on https://hub.docker.com/r/sameersbn/gitlab/

Please make security update version available ASAP!

Information about security issues https://about.gitlab.com/releases/2023/01/31/security-release-gitlab-15-8-1-released

**Comment by kkimurak** [comment]
There is an ongoing pull requests #2707, will be released within in a few hours. So please don't yell by creating separate issues.
If you are really concern about security and extremely on hurry, you have a choise to build the image by yourself. There is an [documentated step to do that](https://github.com/sameersbn/docker-gitlab#installation).

**Comment by vkukk** [comment]
Before creating this issue, I checked whether there are open issues.

**Comment by vkukk** [comment]
New versions are available.
