### ISSUE TITLE
exited: sidekiq (exit status 1; not expected) 

### ISSUE THREAD

**Issue by hyper-carrot** [sameersbn/docker-gitlab#271]
After docker run, the console constantly display same content, look like:

2015-03-10 08:38:07,049 INFO exited: sidekiq (exit status 1; not expected)
2015-03-10 08:38:08,052 INFO spawned: 'sidekiq' with pid 581
2015-03-10 08:38:09,054 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-03-10 08:38:32,064 INFO exited: sidekiq (exit status 1; not expected)
2015-03-10 08:38:33,067 INFO spawned: 'sidekiq' with pid 620

......

Have any suggestion?

**Comment by sameersbn** [comment]
@hyper-carrot i think its normal. just ignore the message.

**Comment by hyper-carrot** [comment]
OK, but it have not listen the specific port 80, my command like:

sudo docker run  -e 'GITLAB_HOST=<gitlab_host>' -e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=10022' -e 'GITLAB_BACKUPS=daily' -e 'DB_TYPE=postgres' -e 'DB_HOST=<db_host>' -e 'DB_NAME=gitlabhq_production' -e 'DB_USER=git' -e 'DB_PASS=<passport>' -p 10022:22 -p 10080:80 -e 'REDIS_HOST=<redis_host>' -e 'REDIS_PORT=6379' -v /opt/gitlab/data:/home/gitl/data -v /opt/gitlab/backups:/home/git/data/backups -v /opt/gitlab/tmp:/home/git/data/tmp sameersbn/gitlab:7.8.2

**Comment by sameersbn** [comment]
@hyper-carrot the container will start nginx on port 80 and `-p 10080:80` will forward the host port `10080` to port `80` of the container.

**Comment by hyper-carrot** [comment]
@sameersbn sorry, it's my mistake, the port is 10080, and I run the command:
```
wget http://<gitlab_host>:10080/
```

And the output is: 
```
--2015-03-10 17:49:05--  http://<gitlab_host>:10080/
Connecting to <gitlab_host>:10080... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2015-03-10 17:49:06 ERROR 500: Internal Server Error.
```

**Comment by sameersbn** [comment]
@hyper-carrot couple of things, this setting is not right `-v /opt/gitlab/data:/home/gitl/data`. Next, I am not sure why you want to mount a volume of the `tmp` directory, i.e. `-v /opt/gitlab/tmp:/home/git/data/tmp` and I do not know what implications this can have. Lastly, If you want the backups to be saved at a different location i.e. `-v /opt/gitlab/backups:/home/git/data/backups`, do not use the `/home/git/data/backups` mountpoint, use something like `/home/git/backups`, i.e. outside the `data` mountpoint and specify the path using the `GITLAB_BACKUP_DIR` option.

You docker command is pretty unusual. What exactly are you trying to achieve with these mountpoints. They do not make sense to me.

**Comment by sameersbn** [comment]
@hyper-carrot p.s. the readme clearly indicates the mountpoints that you should specify as volumes. Trying to do something the image is not designed to do would yield unexpected results.

**Comment by hyper-carrot** [comment]
@sameersbn I found some errors in /var/log/gitlab/gitlab/production.log:

```
Started GET "/" for 127.0.0.1 at 2015-03-10 10:04:41 +0000
Processing by DashboardController#show as HTML
Completed 401 Unauthorized in 7ms

Redis::TimeoutError (Connection timed out):
  config/initializers/redis-store-fix-expiry.rb:10:in `block in setex'
  config/initializers/redis-store-fix-expiry.rb:10:in `setex'
```
What does that mean?

**Comment by sameersbn** [comment]
@hyper-carrot first of, please fix your docker command. Next make sure the redis server and database servers are running and are accessible by the container.

**Comment by hyper-carrot** [comment]
@sameersbn Thanks, my lord. It have successfully been run. The docker command is
```
sudo docker run -d -e 'GITLAB_HOST=<gitlab_host>' -e 'GITLAB_BACKUPS=daily' -e 'DB_TYPE=postgres' -e 'DB_HOST=<db_host>' -e 'DB_NAME=gitlabhq_production' -e 'DB_USER=git' -e 'DB_PASS=<db_password>' -p 22:22 -p 80:80 -e 'REDIS_HOST=<redis_host>' -e 'REDIS_PORT=6379' -v /opt/gitlab/data:/home/git/data sameersbn/gitlab:7.8.2
```

**Comment by sameersbn** [comment]
@hyper-carrot congratulations!
I reviewed your docker command and it looks right.
