### ISSUE TITLE
Help please - safe way to update from 13.8.2 to the last stable Gitlab Version

### ISSUE THREAD

**Issue by Bouchaib124** [sameersbn/docker-gitlab#2729]
Hello respected Community member,

I need you help to make a plan to upgrade Gitlab 13.8.2 to the latest stable one with secure path.

Thanking you in advance.

Have a nice week.

Bouchaib

**Comment by emotroshylov** [comment]
13.8.2->13.8.8->13.12.15->14.0.12->14.3.6->14.9.5->14.10.5->15.0.5->15.4.6->15.9.3

**Comment by Bouchaib124** [comment]
Thank you for your reply emotroshylov.

@Community members,

Is there any advice for known issue in this path ?

if so, thank you to highligh.

Best Regards,

Bouchaib

**Comment by JohnDeGitt** [comment]
I've made successfully upgrade from 13.x -> 15.8. 
The path was as below:
1. `[x]` Upgrade z **`13.7.1`** -> **`15.8.0`**.
   1. `[x]` Upgrade z `13.7.1` -> `13.12.4`.
   1. `[x]` Upgrade z `13.14.4` -> `14.0.0`.  - INFO gave up: gitlab-pages entered FATAL state, too many start retries too quickly
   1. `[x]` Upgrade z `14.0.0` -> `14.1.2`.    - turn off GitlabPages.
   1. `[x]` Upgrade z `14.1.2` -> `14.3.0`.
   1. `[x]` Upgrade z `14.3.0` -> `14.6.0`.
   1. `[x]` Upgrade z `14.6.0` -> `14.6.2`.
   1. `[x]` Upgrade z `14.6.2` -> `14.10.5`.
   1. `[x]` Upgrade z `14.10.5` -> `15.0.0`.
   1. `[x]` Upgrade z `15.0.0` -> `15.4.6`.
   1. `[x]` Upgrade z `15.4.6` -> `15.6.0`.
   1. `[x]` Upgrade z `15.6.0` -> **`15.8.0`**.

**Comment by Bouchaib124** [comment]
Hello,

I tried to start migrating from 13.8.2 to 13.8.8, all seems working fine, after a background tasks during the night, I loged in my server, and he proposed me to change a password in the new installed version, I do it, and succeed to enter the dashboard, I see the version now correct with 13.8.8, but I can not see any previous, projects, group, and users.

I checked the database information, all the data seems correct and exist, but can not been see with the new version of gitlab.

This is the first time I try to do an upgrade of gitlab, for sure I missed something, this is why I ask if someone have any suggestion, or a step by step document that he tested himself, this will be very apprecied.

Counting on your support as usual.

Best Regards,

Bouchaib

**Comment by emotroshylov** [comment]
> Hello,
> 
> I tried to start migrating from 13.8.2 to 13.8.8, all seems working fine, after a background tasks during the night, I loged in my server, and he proposed me to change a password in the new installed version, I do it, and succeed to enter the dashboard, I see the version now correct with 13.8.8, but I can not see any previous, projects, group, and users.
> 
> I checked the database information, all the data seems correct and exist, but can not been see with the new version of gitlab.
> 
> This is the first time I try to do an upgrade of gitlab, for sure I missed something, this is why I ask if someone have any suggestion, or a step by step document that he tested himself, this will be very apprecied.
> 
> Counting on your support as usual.
> 
> Best Regards,
> 
> Bouchaib

Can you provide your docker-compose.yml before update and after update ?

**Comment by Bouchaib124** [comment]
Hello,

below an extract of the docker-compose.yml

the only changed for the migration is the two line, comment the old and changed by the new line 👍 
  before ( image: sameersbn/gitlab:13.8.2)
   comment the abouve and change it by (image: gitlab/gitlab-ce:13.8.8-ce.0)

for the below I only changed passwords and non needed information to share, changed by, login/password/xxxx/yyyy/zzzzz:

version: '2.3'

volumes:

  postgresql:
  postgresql_data:
  redis_data:
  gitlab_data:


networks:
  prodnet:
    driver: bridge
  postgresnet:
    driver: bridge
  redisnet:
    driver: bridge

services:
 postgres_data:
   restart: always
   image: busybox
   container_name: 'postgres_data'
   volumes:
     - /data/postgresql:/var/lib/postgresql
     - /data/postgresql_data:/var/lib/postgresql/data

 redis_data:
   restart: always
   image: busybox
   container_name: 'redis_data'
   volumes:
     - /data/redis_data:/data

 gitlab_data:
   restart: always
   image: busybox
   container_name: 'gitlab_data'
   volumes:
     - /data/gitlab_data:/home/git/data



 redis:
   restart: always
   image: redis:5.0.9
   container_name: 'sfactory_redis'
   command:
   - --loglevel warning
   hostname: 'redis'
   ports:
     - "xxxx:xxxx"
   networks:
     - redisnet
   volumes_from:
     - redis_data


 postgresql:
   restart: always
   image: sameersbn/postgresql:12-20200524
   container_name: 'sfactory_postgresql'
   hostname: 'postgresdb'
   volumes_from:
     - postgres_data
   ports:
     - "yyyy:yyyy"
   networks:
     - postgresnet
   environment:
     - DB_USER=login
     - DB_PASS=password
     - DB_NAME=xxxx,xxxxx,gitlab
     - DB_EXTENSION=pg_trgm,btree_gist
     - PG_TRUST_LOCALNET=true
     - PG_PASSWORD=passxxxxx

 gitlab:
   restart: always
   image: sameersbn/gitlab:13.8.2
   #image: gitlab/gitlab-ce:13.8.8-ce.0
   container_name: 'sfactory_gitlab'
   networks:
     - prodnet
     - redisnet
     - postgresnet
   depends_on:
     - redis
     - postgresql
   hostname: 'gitlab'
   ports:
     - "xxxx:xx"
     - "yyyy:yy"
   volumes_from:
     - gitlab_data
   environment:
     - DEBUG=true

     - DB_ADAPTER=postgresql
     - DB_HOST=postgresdb
     - DB_PORT=xxxx
     - DB_USER=login
     - DB_PASS=password
     - DB_NAME=gitlab

     - REDIS_HOST=redis
     - REDIS_PORT=xxxx

     - TZ=UTC
     - GITLAB_TIMEZONE=UTC

     - GITLAB_HTTPS=false
     - SSL_SELF_SIGNED=false

**Comment by Bouchaib124** [comment]
Thank you very much. I do appreciate.

Can you please advise on the path to follow to reach the last version based on sameersbn/gitlab:13.8.4 ?

Also the way I try to do the upgrade, is it the correct one ?

Thanking you in advance.

Bouchaib

**Comment by emotroshylov** [comment]
> 13.8.8->13.12.15->14.0.12->14.3.6->14.9.5->14.10.5->15.0.5->15.4.6->15.9.3

13.8.4->13.12.15->14.0.12->14.3.6->14.9.5->14.10.5->15.0.5->15.4.6->15.9.3

**Comment by emotroshylov** [comment]
> Thank you very much. I do appreciate.
> 
> Can you please advise on the path to follow to reach the last version based on sameersbn/gitlab:13.8.4 ?
> 
> Also the way I try to do the upgrade, is it the correct one ?
> 
> Thanking you in advance.
> 
> Bouchaib

13.8.4->13.12.15->14.0.12->14.3.6->14.9.5->14.10.5->15.0.5->15.4.6->15.9.3

**Comment by Bouchaib124** [comment]
Hello,

Thanks it work for 13.8.4, but for 13.12.15 I got the error below : 
 
Pulling gitlab (sameersbn/gitlab:13.12.15)...
ERROR: manifest for sameersbn/gitlab:13.12.15 not found: manifest unknown: manifest unknown

I checked docker images sameersbn/gitlab, found only 13.8.2 and 13.8.4.

Where Can I get the rest please of the communicated path ?

Sorry for my disturb.

and thank you very much

Bouchaib

**Comment by Bouchaib124** [comment]
I found 13.12.4 the highest in https://hub.docker.com/r/sameersbn/gitlab/tags?page=5

can I use it and jump to 14.0.12 ?

Regards

**Comment by Bouchaib124** [comment]
Hello,

Thank you very much for your help, here is the Path I follow based on availability of images on the sameersbn/gitlab repo.

   My start Gitlab version :  #image: sameersbn/gitlab:13.8.2
   #1 image: sameersbn/gitlab:13.8.4
   #2 image: sameersbn/gitlab:13.12.4
   #3 image: sameersbn/gitlab:14.0.6 
   #4 image: sameersbn/gitlab:14.3.3
   #5 image: sameersbn/gitlab:14.9.3
   #6 image: sameersbn/gitlab:14.10.5
   #7 image: sameersbn/gitlab:15.0.3
   #8 image: sameersbn/gitlab:15.4.6
   #9 image: sameersbn/gitlab:15.9.3

Now seems all works fine.

Thank you.

I am ready to help if someone need it.

Bouchaib
