### ISSUE TITLE
Container suddenly stops after a minute

### ISSUE THREAD

**Issue by kinghajj** [sameersbn/docker-gitlab#274]
I'm attempting to use the container with these options:

    docker run --name=gitlab -d -p 10022:22 -p 10080:80 \
      -e 'DB_TYPE=postgres' \
      -e 'DB_HOST=127.0.0.1' \
      -e 'DB_NAME=gitlabhq_production' \
      -e 'DB_USER=gitlab' \
      -e 'DB_PASS=whatever' \
      -e 'REDIS_HOST=127.0.0.1' \
      -e 'REDIS_PORT=6379' \
      -e 'SMTP_ENABLED=false' \
      -e 'GITLAB_HOST=git.mydomain.com' \
      -e 'GITLAB_HTTPS=true' \
      -e 'GITLAB_SSH_PORT=10022' \
      -e 'GITLAB_PORT=443' \
      -e 'SSL_SELF_SIGNED=true' \
      -v /opt/gitlab/data:/home/git/data \
      sameersbn/gitlab:7.8.4

I'm using "external" postgresql and redis instances, and a load balancer with a self-signed SSL certificate. After executing this script, the container runs for a minute, then suddenly stops.

	$ docker logs gitlab
	debconf: unable to initialize frontend: Dialog
	debconf: (TERM is not set, so the dialog frontend is not usable.)
	debconf: falling back to frontend: Readline
	debconf: unable to initialize frontend: Readline
	debconf: (This frontend requires a controlling tty.)
	debconf: falling back to frontend: Teletype
	Creating SSH2 RSA key; this may take some time ...
	Creating SSH2 DSA key; this may take some time ...
	Creating SSH2 ECDSA key; this may take some time ...
	Creating SSH2 ED25519 key; this may take some time ...
	invoke-rc.d: policy-rc.d denied execution of restart.
	SSL keys and certificates were not found.
	Assuming that the container is running behind a HTTPS enabled load balancer.

Running "journalctl -u docker" shows these lines among the soup of others:

    Mar 14 19:52:28 mydomain.com docker[4518]: time="2015-03-14T19:52:28-07:00" level="info" msg="-job start(bf05fc35629a4b12eeee45a671c9fef95889cf2763a1f7dae285a176d158d9ec) = OK (0)"
    Mar 14 19:53:28 mydomain.com docker[4518]: time="2015-03-14T19:53:28-07:00" level="info" msg="+job log(die, bf05fc35629a4b12eeee45a671c9fef95889cf2763a1f7dae285a176d158d9ec, sameersbn/gitlab:7.8.4)"
    Mar 14 19:53:28 mydomain.com docker[4518]: time="2015-03-14T19:53:28-07:00" level="info" msg="-job log(die, bf05fc35629a4b12eeee45a671c9fef95889cf2763a1f7dae285a176d158d9ec, sameersbn/gitlab:7.8.4) = OK (0)"
    Mar 14 19:53:28 mydomain.com docker[4518]: time="2015-03-14T19:53:28-07:00" level="info" msg="+job release_interface(bf05fc35629a4b12eeee45a671c9fef95889cf2763a1f7dae285a176d158d9ec)"
    Mar 14 19:53:28 mydomain.com docker[4518]: time="2015-03-14T19:53:28-07:00" level="info" msg="-job release_interface(bf05fc35629a4b12eeee45a671c9fef95889cf2763a1f7dae285a176d158d9ec) = OK (0)"

docker version:

	Client version: 1.5.0
	Client API version: 1.17
	Go version (client): go1.4.1
	Git commit (client): a8a31ef
	OS/Arch (client): linux/amd64
	Server version: 1.5.0
	Server API version: 1.17
	Go version (server): go1.4.1
	Git commit (server): a8a31ef

docker info:

	Containers: 1
	Images: 22
	Storage Driver: devicemapper
	 Pool Name: docker-254:1-1574678-pool
	 Pool Blocksize: 65.54 kB
	 Backing Filesystem: extfs
	 Data file: /dev/loop0
	 Metadata file: /dev/loop1
	 Data Space Used: 1.196 GB
	 Data Space Total: 107.4 GB
	 Metadata Space Used: 1.896 MB
	 Metadata Space Total: 2.147 GB
	 Udev Sync Supported: true
	 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
	 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
	 Library Version: 1.02.93 (2015-01-30)
	Execution Driver: native-0.2
	Kernel Version: 3.18.6-1-ARCH
	Operating System: Arch Linux
	CPUs: 2
	Total Memory: 1.959 GiB
	Name: mydomain.com
	ID: whatever
	WARNING: No swap limit support

This is on a Vultr VPS, if that's helpful. Any idea why this isn't working?

**Comment by bdentino** [comment]
my guess is that the database connection attempt isn't successful. literally spent all day yesterday debugging the same symptoms. container mysteriously dies after 60 seconds. try removing the pipe to /dev/null here:

https://github.com/sameersbn/docker-gitlab/blob/master/assets/init#L709

and see what the output says. If the app can't connect to the database within 60 seconds it terminates.

**Comment by kinghajj** [comment]
I managed to solve this by putting "--net=host" in the "docker run" command, and by ensuring that my iptables configuration accepted all incoming loopback connections.

**Comment by sameersbn** [comment]
@kinghajj i remember somebody have to do the same on linode vps. no idea what it is
