### ISSUE TITLE
gitlab container loops on restart without starting up properly

### ISSUE THREAD

**Issue by sramazzina** [sameersbn/docker-gitlab#2773]
For any version of the container after the merge of the following changes

https://github.com/sameersbn/docker-gitlab/commit/b3b700a7019a1a2a9f17a88f81d85cd2ec8a0e67
https://github.com/sameersbn/docker-gitlab/commit/260f548c5b4bd0c4e602740128aeca6058331f4d

the container starts correctly when starting everything up the first time with `docker compose up` command but as soon as I stop the container (just the gitlab container or all), trying to restart them with `docker compose start` command, the gitlab container fails to start and enters an endless loop that continuously prints the following lines 

_gitlab-gitlab-1  Initializing logdir... 
gitlab-gitlab-1  Initializing datadir... 
gitlab-gitlab-1  Container TimeZone -> Europe/Rome 
gitlab-gitlab-1  Installing configuration templates... 
gitlab-gitlab-1  Configuring gitlab... 
gitlab-gitlab-1  Configuring gitlab::database 
gitlab-gitlab-1  Configuring /home/git/.postgresqlrc to avoid version mismatch on dumping 
gitlab-gitlab-1  - Detected server version: 120003 
gitlab-gitlab-1  - Generating /home/git/.postgresqlrc 
gitlab-gitlab-1  12 postgresql:5432 gitlabhq_production 
gitlab-gitlab-1 exited with code 1_

I made some tries with all the versions before 15.11.4 (the first version that contains that two entries) and everything worked perfectly. From that version onward we got that problem

**Comment by wlsdn** [comment]
I Have the same Issues on gitlab 16.0.1, postgresql 13.8

```shell
Loading /etc/docker-gitlab/runtime/env-defaults
Initializing logdir...
Initializing datadir...
Container TimeZone -> Asia/Seoul
Installing configuration templates...
SSL Key, SSL Certificate and DHParam were not found.
Assuming that the container is running behind a HTTPS enabled load balancer.
SSL Key, SSL Certificate were not found.
Assuming that the container is running behind a HTTPS enabled load balancer.
Configuring gitlab...
Configuring gitlab::database
Configuring /home/git/.postgresqlrc to avoid version mismatch on dumping
- Detected server version: 130008
- Generating /home/git/.postgresqlrc
13 db_pg13:5432 gitlab
```

here are logs when `DEBUG=true`
```shell
+ gitlab_configure_database
+ echo -n 'Configuring gitlab::database'
Configuring gitlab::database+ gitlab_finalize_database_parameters
+ DB_HOST=db_pg13
+ DB_PORT=5432
+ DB_USER=gitlab_user
+ DB_PASS=gitlab_pass
+ DB_NAME=gitlab
+ DB_NAME=gitlab
+ DB_USER=gitlab_user
+ DB_PASS=gitlab_pass
+ DB_NAME=gitlab
+ DB_USER=gitlab_user
+ DB_PASS=gitlab_pass
+ DB_NAME=gitlab
+ DB_USER=gitlab_user
+ DB_PASS=gitlab_pass
+ DB_NAME=gitlab
+ [[ -z db_pg13 ]]
+ DB_PORT=5432
+ DB_ENCODING=unicode
+ DB_USER=gitlab_user
+ DB_NAME=gitlab
+ gitlab_check_database_connection
++ find /usr/lib/postgresql/ -name pg_isready -type f
++ sort
++ tail -n1
+ prog=/usr/lib/postgresql/13/bin/pg_isready
+ prog='/usr/lib/postgresql/13/bin/pg_isready -h db_pg13 -p 5432 -U gitlab_user -d gitlab -t 1'
+ timeout=60
+ /usr/lib/postgresql/13/bin/pg_isready -h db_pg13 -p 5432 -U gitlab_user -d gitlab -t 1
+ echo

+ gitlab_generate_postgresqlrc
+ echo 'Configuring /home/git/.postgresqlrc to avoid version mismatch on dumping'
Configuring /home/git/.postgresqlrc to avoid version mismatch on dumping
++ PGPASSWORD=gitlab_pass
++ psql -h db_pg13 -p 5432 -U gitlab_user -d gitlab -Atw -c 'SHOW server_version_num'
+ DB_SERVER_VERSION=130008
+ [[ 130008 -eq 0 ]]
+ echo '- Detected server version: 130008'
- Detected server version: 130008
+ DB_SERVER_VERSION_MAJOR=13
+ DB_CLIENT_VERSION_PACKAGE_NAME=
+ [[ 13 -ge 10 ]]
+ DB_CLIENT_VERSION_PACKAGE_NAME=13
++ apt-cache pkgnames postgresql-client
++ grep -e -13
++ wc -l
+ [[ 1 -ne 1 ]]
+ GITLAB_USER_POSTGRESQLRC=/home/git/.postgresqlrc
+ echo '- Generating /home/git/.postgresqlrc'
- Generating /home/git/.postgresqlrc
+ echo '13 db_pg13:5432 gitlab'
+ exec_as_git tee /home/git/.postgresqlrc
++ whoami
+ [[ root == git ]]
+ sudo -HEu git tee /home/git/.postgresqlrc
13 db_pg13:5432 gitlab
+ gitlab_uninstall_unused_database_client
+ [[ -f /home/git/.postgresqlrc ]]
++ awk '/^[^#]/ {printf("\|-%s",$1)}' /home/git/.postgresqlrc
+ DB_CLIENT_VERSIONS_IN_USE='\|-13'
+ REGEX_DB_CLIENT_VERSIONS_IN_USE='-common\|-13'
++ apt-cache pkgnames postgresql-client
++ tr '\n' ' '
++ grep -v -e '-common\|-13'
+ UNUSED_DB_CLIENTS=
```

I Hope helps to solve the issue.

**Comment by sramazzina** [comment]
@f-io you have the same behavior with any version from 15.11.4 onward. No problem with any version prior to that version. Moreover, because of the requirement you are indicating, to have a clearer picture I tried also with postgres 13 and 14 with gitlab version 15.11.4, 15.11.6, 16.0.0 and 16.0.01. Same behavior. 

Therefore I firstly cloned the sameersbn/docker-postgresql repository and updated postgresql to version 14. Tried with  gitlab 16.0.1 and I had same behavior. Next, I cloned this repository and commented the two lines

```  
gitlab_check_database_connection
gitlab_generate_postgresqlrc
```
and everything worked as a charm.

**Comment by tDo** [comment]
After playing around a bit with the scripts it seems that the culprit is the grep in this line:

https://github.com/sameersbn/docker-gitlab/blob/456fc76f6af904228c93060f3f2b11e91f2c5d38/assets/runtime/functions#L240

During the first time it is executed the grep will find matches for the unused clients.
When you stop and restart the container (Which would keep the changes of the container data)
during the next execution grep would not get any more matches, since only the wanted installed clients remain.
But when grep does not find any matches, it does return a non-zero exit code and thus terminates further execution
at this point. (As suggested by this so answer: https://stackoverflow.com/a/57699703)

Changing the line to:
```sh
UNUSED_DB_CLIENTS=$(apt-cache pkgnames postgresql-client | grep -v -e "${REGEX_DB_CLIENT_VERSIONS_IN_USE}" | tr '\n' ' ' || true)
```
would swallow the error when no matches are found and the script can proceed as wanted.

@sachilles , @kkimurak Would you confirm that this might be a solution to this issue?

**Comment by kkimurak** [comment]
Hi all, thank you for reporting and sorry for inconvinience.  
I'm glad you all here trying to resolve the issue by checking the code, not yelling loudly, pinging to maintainer so many times or shouts "same here".  

----

@tDo 
The change should not works as expected. `|| true` after pipe will only handle non-0 exit code on last command `tr`.  
Also, It may be better to check if `UNUSED_DB_CLIENTS` is empty or not before executing `apt purge`.  
So the change would be like:

````diff
diff --git a/gitlab/functions b/gitlab/functions
index 3f52ac2..e748d54 100755
--- a/gitlab/functions
+++ b/gitlab/functions
@@ -237,7 +237,12 @@ gitlab_uninstall_unused_database_client() {
     REGEX_DB_CLIENT_VERSIONS_IN_USE="-common${DB_CLIENT_VERSIONS_IN_USE}"

     # remove unused client using regex above
-    UNUSED_DB_CLIENTS=$(apt-cache pkgnames postgresql-client | grep -v -e "${REGEX_DB_CLIENT_VERSIONS_IN_USE}" | tr '\n' ' ')
+    UNUSED_DB_CLIENTS=$(apt-cache pkgnames postgresql-client | grep -v -e "${REGEX_DB_CLIENT_VERSIONS_IN_USE}" || true)
+    if [[ "${UNUSED_DB_CLIENTS}" == "" ]]; then
+      echo "- All installed version of clients are in use. Did not uninstalled any client...";
+      return
+    fi
+
     echo "- Uninstalling unused client(s): ${UNUSED_DB_CLIENTS}"
     DEBIAN_FRONTEND=noninteractive apt-get -qq -y purge -- ${UNUSED_DB_CLIENTS} >/dev/null
   fi
````

Here is a docker log for the case uninstallation executed:
````
Loading /etc/docker-gitlab/runtime/env-defaults
Initializing logdir...
Initializing datadir...
Container TimeZone -> Asia/Tokyo
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database
Configuring /home/git/.postgresqlrc to avoid version mismatch on dumping
- Detected server version: 140007
- Generating /home/git/.postgresqlrc
14 postgresql:5432 gitlabhq_production
- Uninstalling unused client(s): postgresql-client-13
postgresql-client-15
Configuring gitlab::redis
...
````

And here is another log on restart (that may not uninstall anything).
````
Loading /etc/docker-gitlab/runtime/env-defaults
Initializing logdir...
Initializing datadir...
Container TimeZone -> Asia/Tokyo
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database
Configuring /home/git/.postgresqlrc to avoid version mismatch on dumping
- Detected server version: 140007
- Generating /home/git/.postgresqlrc
14 postgresql:5432 gitlabhq_production
- All installed version of clients are in use. Did not uninstalled any client...
Configuring gitlab::redis
...
````

I have confirmed both works as expected on locally.

**Comment by tDo** [comment]
Yeah that makes more sense than my variant.

And please don't be sorry for anything. All of you maintainers and contributors are already investing
quite a bit of their free time so the rest of us can have nice things.

So thanks a lot for all the work you are doing here 👍

**Comment by kkimurak** [comment]
Submit a PR #2774 .

**Comment by sramazzina** [comment]
@sachilles I noticed that after merging this PR you built a new release 15.11.6-1. That's fine but why you didn't do the same for a 16.0.2?
