### ISSUE TITLE
braked backup after update to 16.2

### ISSUE THREAD

**Issue by vasyakrg** [sameersbn/docker-gitlab#2790]
after update gitlab version backup process braked:

`docker-compose exec --user git -T gitlab bundle exec rake gitlab:backup:create SKIP=registry,builds from /srv/gitlab`

log:
```
2023-06-29 07:50:58 +0700 -- Dumping repositories ... done
2023-06-29 07:50:58 +0700 -- Dumping uploads ...
2023-06-29 07:50:58 +0700 -- Dumping uploads ... done
2023-06-29 07:50:58 +0700 -- Dumping builds ... [SKIPPED]
2023-06-29 07:50:58 +0700 -- Dumping artifacts ...
2023-06-29 07:50:58 +0700 -- Dumping artifacts ... done
2023-06-29 07:50:58 +0700 -- Dumping pages ...
2023-06-29 07:50:58 +0700 -- Dumping pages ... done
2023-06-29 07:50:58 +0700 -- Dumping lfs objects ...
2023-06-29 07:50:58 +0700 -- Dumping lfs objects ... done
2023-06-29 07:50:58 +0700 -- Dumping terraform states ...
2023-06-29 07:50:58 +0700 -- Dumping terraform states ... done
2023-06-29 07:50:58 +0700 -- Dumping container registry images ... [SKIPPED]
2023-06-29 07:50:58 +0700 -- Dumping packages ...
2023-06-29 07:50:58 +0700 -- Dumping packages ... done
2023-06-29 07:50:58 +0700 -- Dumping ci secure files ...
rake aborted!
Errno::ENOENT: No such file or directory @ rb_check_realpath_internal - /home/git/data/shared/ci_secure_files
```

**Comment by kkimurak** [comment]
Temporal workaround: add `ci_secure_files` to `SKIP` like `SKIP=ci_secure_files`.   
If you have configured scheduled backup (`GITLAB_BACKUP_SCHEDULE`), you can use configuration parameter `GITLAB_BACKUP_SKIP`.

----

With the release of v16.1.0, rake tasks `gitlab:backup:create` now include ci_secure_files in their targets (See [gitlab.com/gitlab-org/gitlab!121142](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/121142)).

`ci_secure_files` is instroduced a year ago (with v16.1.0 release) and enabled by default (See [gitlab.com/gitlab-org/gitlab!78227](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/78227), especially [gitlab.com/gitlab-org/gitlab@41a553c1](https://gitlab.com/gitlab-org/gitlab/-/commit/41a553c1a83658b1d6d23ee6bd88a94ef675a6fa).  
As we have not been able to sync the configuration file yet, we cannot configure whether it is enabled or disabled.

**Comment by talvespe** [comment]
![image](https://github.com/sameersbn/docker-gitlab/assets/976965/0b925445-1695-4d59-a64a-a1dac08ea296)

**Comment by Swati-Gawali** [comment]
Please share the upgrade path from Gitlab CE from 15.9.1 to 16.x.x

**Comment by kkimurak** [comment]
@talvespe 

You are executing backup manually after logging into container (like `docker exec -it gitlab /bin/bash`), right?  
Then it has no effect even you set `GITLAB_BACKUP_SKIP`.  
Execute backup command adding `SKIP=ci_secure_files` like  
```sh
# on host
$ docker exec -u git -it gitlab /bin/bash
# (login to container, default cd to /home/git/gitlab = ~/gitlab)
git@your-gitlab-container:~/gitlab$ bundle exec rake gitlab:backup:create SKIP=ci_secure_files
````

----
I don't know what you want us to do if you upload an image without any comments...  
I personally apologize for the delay in replying to an issue that I had commented on, but next time you have a chance to report a problem, we would appreciate it if you could send us a text (with your request and situation, of course).

**Comment by gjrtimmer** [comment]
I had the same issue, I solved it differently, I just created a folder called `ci_secure_files` and then the backup runs fine again, just create a folder in `shared` called `ci_secure_files` and everything works.

**Comment by gjrtimmer** [comment]
We should create a PR that creates this empty directory on `install`

**Comment by kkimurak** [comment]
@gjrtimmer The "empty directory" should be added to target of [initialize_datadir()](https://github.com/sameersbn/docker-gitlab/blob/53cfbea50902746d08ed37973d976f4cac788caf/assets/runtime/functions#L1627-L1738) and [sanitize_datadir()](https://github.com/sameersbn/docker-gitlab/blob/53cfbea50902746d08ed37973d976f4cac788caf/assets/runtime/functions#L1740-L1790). I think.

**Comment by talvespe** [comment]
> I had the same issue, I solved it differently, I just created a folder called `ci_secure_files` and then the backup runs fine again, just create a folder in `shared` called `ci_secure_files` and everything works.

Yes, it really works. I created the directory and everything behaved well.
As I didn't know if I had done something wrong, I didn't report it here. My bad

Thanks

**Comment by kkimurak** [comment]
I wrote that the directory `ci_secure_files` should be added to target of [sanitize_datadir()](https://github.com/sameersbn/docker-gitlab/blob/53cfbea50902746d08ed37973d976f4cac788caf/assets/runtime/functions#L1740-L1790) but that was not required because the directory should be created in `GITLAB_SHARED_DIR` and [sanitized recursively](https://github.com/sameersbn/docker-gitlab/blob/cfad6e95c4c601f6930d5e58c0ceda02600553e6/assets/runtime/functions#L1756-L1757).  
So, #2901 will solve the issue.
