### ISSUE TITLE
Upgrade to 16.1.0 breaks because PostgreSQL 13+ needed

### ISSUE THREAD

**Issue by w4rell** [sameersbn/docker-gitlab#2791]
Hi, after we tried to upgrade to your last image, postgres is saying that it needs PostgreSQL 13 and above, on your image sameersbn/PostgreSQL it doesn't seems you already make the upgrade.

![image_20230629131934](https://github.com/sameersbn/docker-gitlab/assets/11441252/eac61fbd-ca3b-4f7b-9e84-2e3cffe3bfce)

Do you have any workaround?

Thanks!

**Comment by kkimurak** [comment]
Duplicate of #2771. You can see discussion and workaround there.

**Comment by w4rell** [comment]
Sorry, haven't seen it ! I upgraded the postgresql to 14.8 following the procedure, everything is OK, thanks !
