### ISSUE TITLE
Is it possible to send emails over the host?

### ISSUE THREAD

**Issue by kain88-de** [sameersbn/docker-gitlab#281]
I don't want set up an extra email account or have my email password in clear text in a docker start up script. Is is possible to set up the SMTP flags so that my host machine is used the send the email from gitlab?

**Comment by sameersbn** [comment]
@kain88-de Please refer to https://github.com/sameersbn/docker-gitlab/pull/211#issuecomment-73389035

**Comment by kain88-de** [comment]
Thanks looks like what I was looking for.

Could you link to that information in the README ?
