### ISSUE TITLE
Migration to package-based gitlab ce

### ISSUE THREAD

**Issue by alirezaghey** [sameersbn/docker-gitlab#2823]
Hey folks,

I have an old gitlab `version 13.11.4` that is spun up using `sameersbn/docker-gitlab` and I'm trying to migrate it to the packages-based `13.11.4-ce` instance. I have already the new instance running and the secrets configured. Problem is with the restoration of the backup. The current automatic backups produces the following files:

```console
-rw-rw-r--.  1 centos centos    212 Sep  6 02:02 backup_information.yml
drwxrwxr-x.  2 centos centos     29 Sep  6 02:01 db
-rw-------.  1 centos centos    146 Sep  6 02:02 lfs.tar.gz
-rw-------.  1 centos centos    146 Sep  6 02:02 pages.tar.gz
drwx------.  3 centos centos     21 Sep  6 02:01 repositories
-rw-------.  1 centos centos 213137 Sep  6 02:02 uploads.tar.gz
```

Accoring to [gitlab's documentation](https://docs.gitlab.com/ee/administration/backup_restore/restore_gitlab.html), `gitlab-backup restore` expects `tar` files like `11493107454_2018_04_25_10.6.4-ce_gitlab_backup.tar`.

I'm not sure how to convert my current backups to the required one for `gitlab-backup` and haven't found anything online.
Would appreciate any feedback! Thanks!

**Comment by kkimurak** [comment]
If the files are sufficient to back up your old gitlab instance (i.e. are not missing anything), I think you can compress them into a single tar archive and read it into the `gitlab-backup` command.

````sh
$ cd path/to/backup_information.yml-and-so-on
$ tar -caf "$(date +"%s_Y%_%m_%d_13.11.4_gitlab_backup.tar)" -C . *
````

But I recommend checking the backup log of the old-gitlab container. For recent versions, at least v16.3.1 which is currently running on me, is backup.json located at `/var/log/gitlab/gitlab`. I'm not sure if it's the same name in 13.11.4, but I believe it's same.

**Comment by alirezaghey** [comment]
Hey @kkimurak thank you for the swift reply. I came to the same conclusion after a lot of trial and error and guess work. Everything seems to be running fine. Thanks again.
