### ISSUE TITLE
RACK_ATTACK_WHITELIST  incorrect string

### ISSUE THREAD

**Issue by chodorenko** [sameersbn/docker-gitlab#2828]
Hello,
I have problem in add host in whiteList RACK ATTACK

i try add in whitelist more then one IP. 
as example:
in **docker-compose.yml**
`RACK_ATTACK_WHITELIST="1.1.1.1,192.168.0.0/24"`

after start containers i view in  **/home/git/gitlab/config/gitlab.yml** 
`ip_whitelist:  ["1.1.1.1,192.168.0.0/24"]`
its not a Ruby array its only one string value in array

By [ Official manual](https://docs.gitlab.com/omnibus/settings/configuration.html#configure-a-failed-authentication-ban) 
_ip_whitelist: IPs to not block. They must be formatted as strings in a Ruby array. CIDR notation is supported in GitLab 12.1 and later. For example, ["127.0.0.1", "127.0.0.2", "127.0.0.3", "192.168.0.1/24"]._
its not equal  ["1.1.1.1,192.168.0.0/24"]

in repository on file  **docker-gitlab/assets/runtime/config/gitlabhq/gitlab.yml**
i view      
`ip_whitelist: ["{{RACK_ATTACK_WHITELIST}}"]`
As its not correct

IMHO better change  to  
ip_whitelist: {{RACK_ATTACK_WHITELIST}}
and in **docker-compose.yml** write as RACK_ATTACK_WHITELIST= '["1.1.1.1","192.168.0.0/24"]'

and replace in **docker-gitlab/assets/runtime/env-defaults**
RACK_ATTACK_WHITELIST=${RACK_ATTACK_WHITELIST:-"127.0.0.1"}  to RACK_ATTACK_WHITELIST=${RACK_ATTACK_WHITELIST:-["127.0.0.1"]}

And add in manual example for multi IP  value

**Comment by chodorenko** [comment]
@sameersbn 
May be you read and cant fix it bug ?

**Comment by TimeBye** [comment]
try

```
RACK_ATTACK_WHITELIST='"1.1.1.1","192.168.0.0/24"'
```

**Comment by chodorenko** [comment]
> try

ip_whitelist: ["{{RACK_ATTACK_WHITELIST}}"] + RACK_ATTACK_WHITELIST='"1.1.1.1","192.168.0.0/24"' -> [""1.1.1.1","192.168.0.0/24""]
It not correct IMHO

**Comment by TimeBye** [comment]
Try writing like this
```
RACK_ATTACK_WHITELIST='1.1.1.1","192.168.0.0/24'
```

![image](https://github.com/sameersbn/docker-gitlab/assets/22651579/7accec38-f121-4945-89fa-12e9f7518ad6)

**Comment by chodorenko** [comment]
Yes, its work , also not best way IMHO

**Comment by kkimurak** [comment]
@chodorenko Thank you for your detailed report. For backwards compatibility, it would be nice to add code to make sure the value is double-quoted (to be a valid string array elements in ruby). 

Are you planning to submit a PR ?  
Or, If you don't mind co-authored-by-you, would you like me to create a PR on your behalf (adding the backward-compatibility code above and enhance documentation) ?

----

Note that `@sameersbn` has been away from his work as a maintainer for the past few years, so you may not get responce. The only active maintainer at this time is `@sachilles`.

**Comment by chodorenko** [comment]
@kkimurak I would really appreciate a commit like this. 

PS: Unfortunately, I'm not a very good programmer :)

**Comment by kkimurak** [comment]
@chodorenko Sorry for late, I have submit a PR #2846 .
