### ISSUE TITLE
Adapt clone-template for different SSH port

### ISSUE THREAD

**Issue by DeX3** [sameersbn/docker-gitlab#283]
When a new project is created, users can see how to first clone it/push existing repos to it. Typically, gitlab suggests something along the following lines:

    git remote add origin git@gitlab.lan:test/testproject.git
    git push -u origin master

However, because now that gitlab is not running directly on that host but inside a container, they would have to connect via a port other than the default SSH port. This means, that the template is incorrect. It ***should*** read:

    git remote add origin ssh://git@gitlab.lan:10022/test/testproject.git
    git push -u origin master

Or have `10022` replaced with whatever `GITLAB_SSH_PORT` is configured. I've looked a bit through the gitlab source code, and there seems to be a configuration option related to it: https://github.com/gitlabhq/gitlabhq/blob/435128171ddf41025f410429b8a639a368e77582/lib/gitlab/backend/shell.rb#L235

Would it be possible to incorporate this option into the image configuration as an environment variable?

**Comment by sameersbn** [comment]
@DeX3 You should set `GITLAB_SSH_PORT=10022` for the ssh clone url to appear correctly.

**Comment by DeX3** [comment]
Oh... I must've overlooked that - sorry.
