### ISSUE TITLE
Sending of mails fails since 14.0.6 with GITLAB_RELATIVE_URL_ROOT set to "/git"

### ISSUE THREAD

**Issue by rzetzsche** [sameersbn/docker-gitlab#2836]
Hi everyone,

We are trying to upgrade our gitlab instance from 13.9.4 to the latest version. Unfortunately, after upgrading to at least 14.0.6, sending mail doesn't work anymore and we get the following error message within the background jobs page:

```
Premailer::Rails::CSSHelper::FileNotFound: File with URL "https://dev.movisens.com/assets/mailer-e264c5d90846b52c5b52118742877add10abda90da38bd1ee55dba535912a198.css"
```

The file in question is indeed not accessible at ```https://dev.movisens.com/assets/mailer-e264c5d90846b52c5b52118742877add10abda90da38bd1ee55dba535912a198.css```, but it is accessible at ```https://dev.movisens.com/git/assets/mailer-e264c5d90846b52c5b52118742877add10abda90da38bd1ee55dba535912a198.css```. So I suspect that since 14.0.6 there is an issue with ```GITLAB_RELATIVE_URL_ROOT``` not working correctly when sending mails.

I've also tried running our configuration as a fresh instance and we still get the same problem.

We are configuring the host and relative url, and also configuring our own smtp server, which isn't gmail:

```yml
      - GITLAB_HOST=dev.movisens.com
      - GITLAB_HTTPS=true
      - GITLAB_PAGES_ENABLED=true
      - GITLAB_PAGES_EXTERNAL_HTTP=:8081
      - GITLAB_PAGES_DOMAIN=pages-dev.movisens.com
      - GITLAB_PORT=443
      - GITLAB_RELATIVE_URL_ROOT=/git
```

I can reproduce this problem with any version from 14.0.6 onwards. In 13.12.4 it works as expected and mails are functional.

I have also reproduced that deleting ```GITLAB_RELATIVE_URL_ROOT=/git``` from our ```docker-compose.yml``` will allow us to send mails again.

**Comment by kkimurak** [comment]
Temporal workaround: create a file named `premailer.rb` with contents below on host, then overwrite corresponding file in gitlab container by mounting the file to `/home/git/gitlab/config/initializer/premailer.rb` .

[premailer.rb - gitlab@7a0c278e](https://gitlab.com/gitlab-org/gitlab/-/blob/7a0c278ef9c4f6167d31af297e1b0c79200722ad/config/initializers/premailer.rb)
````
# frozen_string_literal: true

# See https://github.com/fphilipe/premailer-rails#configuration
Premailer::Rails.config.merge!(
  generate_text_part: false,
  preserve_styles: true,
  remove_comments: true,
  remove_ids: false,
  remove_scripts: false,
  output_encoding: 'US-ASCII'
)
````

----

This reverts the commit [gitlab@c194597a](https://gitlab.com/gitlab-org/gitlab/-/commit/c194597ae04e812f3b5be7339412413a04703ae4). The first contained tag is 14.1.0, as far as I checked by executing `git tag --contains c194597a | sort --version-sort`.  
Note that you cannot find out any docs or note in public gitlab repository - the gitlab team may not go through the normal merging process for security fixes. I am not a member of the team so I don't know the detail.  

I am still searching the detail so I have never been submit an issue yet, but the assets pipeline is always fails when the relative url root is used.  

I'll add a comment if I have more details. I apologize for the 2 years delay in sharing information.

**Comment by rzetzsche** [comment]
Hi @kkimurak I've tried your solution with 16.3.5 with the following volumes:

```yml
volumes:
      - "/srv/docker/gitlab2/gitlab4:/home/git/data"
      - "/srv/docker/gitlab2/config4/premailer.rb:/home/git/gitlab/config/initializer/premailer.rb"
```

But it still isn't working and I get the same Premailer::Rails::CSSHelper::FileNotFound error message.

**Comment by kkimurak** [comment]
@rzetzsche Oops sorry I have found  a typo. Could you try `/home/git/gitlab/config/initializers/premailer.rb` ? (lacks `s` after `initializer`)

**Comment by rzetzsche** [comment]
@kkimurak can confirm that this works on a new 16.3.5 instance. I'll try to test this now to see if it works when I try to upgrade from 13.9.4 to 14.0.6.

**Comment by rzetzsche** [comment]
@kkimurak I can confirm that it's also working when updating our existing instance. Thank you so much for your quick response.
