### ISSUE TITLE
Gitlab  and Redmine integration

### ISSUE THREAD

**Issue by epiphyllum** [sameersbn/docker-gitlab#284]
this gitlab only support two mount point:

VOLUME ["/home/git/data"]
VOLUME ["/var/log/gitlab"]

so when I integrate redmine with git.   I can not share the gitlab's  repositories to redmine!

should web add another mount point?    /home/git/data/repositories?

**Comment by epiphyllum** [comment]
since it will be more flexible

**Comment by sameersbn** [comment]
@epiphyllum Please refer to https://github.com/sameersbn/docker-gitlab#redmine. The answer to your question lies in there

**Comment by epiphyllum** [comment]
Greate!!!

**Comment by jc10051953** [comment]
Please tell me how to do this in docker-compose.yml file?
