### ISSUE TITLE
Configuration Options: Splash Screen Title, no package removal

### ISSUE THREAD

**Issue by wuebbel** [sameersbn/docker-gitlab#285]
We configure the GitLab splash screen by adding a brand title and brand text in appearances_helper.rb. We're doing this by copying the edited file into the container, it would be great to have an option for that.

Also, I would like to add additional gem packages. Unfortunately, gem install commands fail. To my understanding, since all compilation packages are removed at the end of Dockerfile. Maybe we could have an option for keeping them?

Best wishes, Frank

**Comment by sameersbn** [comment]
@wuebbel with respect to the branding you can try volume mounting `/home/git/gitlab/app/helpers/appearances_helper.rb`, eg. `-v /path/to/modified/appearances_helper.rb:/home/git/gitlab/app/helpers/appearances_helper.rb`

Regarding gem installation, what gems are you trying to install and for what reason? Either ways, if you need to install gems, you will have to inherit this image and install the gems and the required packages in the fork. Eg.

```dockerfile
FROM sameersbn/gitlab:latest
RUN apt-get update
RUN apt-get install -y ...
RUN gem install ...
```

The image will continue to function normally as long as you don't add a `ENTRYPOINT` or `CMD` statement

**Comment by wuebbel** [comment]
@sameersbn thanks very much for the comment. Yes, sure, volume mounting would help. Currently, I am waiting for the docker instance to become ready, stop the daemons in it, patch the file from a shell inside the docker, and then restart the daemons. Mounting is definitely more elegant.

Thanks also for the other comment. Yes, seems like forking is the only reasonable thing to do. 

Thank you, Frank
