### ISSUE TITLE
How use GITLAB_RAILS_RACK_TIMEOUT_ENABLE (contanier env var or new (?) configuration parameter)

### ISSUE THREAD

**Issue by fidoedidoe** [sameersbn/docker-gitlab#2855]
Hi 

I'm having issues with `Rack::Timeout::RequestTimeoutException (Request ran for longer than 60000ms ):` when fetching comments from a merge request. It appears I'm not alone ([link](https://forum.gitlab.com/t/unable-to-fetch-comments-in-merge-request-something-went-wrong-while-fetching-comments-please-try-again/80726/2))

Digging around on the web I found this MR: [Allow Rack::Timeout to be disabled](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/90958) which in summary allows the use of an env var "GITLAB_RAILS_RACK_TIMEOUT_ENABLE" to be set to false. I'm wondering whether I can simply set this env var to false, when the container is started or whether this needs to be first incorporated into the list of container configuration parameters (as outlined in [README.md](https://github.com/sameersbn/docker-gitlab#available-configuration-parameters))?

Any help/advice would be gratefully received

Thank you.

**Comment by kkimurak** [comment]
Looking into the code, gitlab itself [loads the environment variable `GITLAB_RAILS_RACK_TIMEOUT_ENABLE`](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/90958/diffs#c5953fb2fab3e07236b7dd2b36fe2e36fda57702_12_12). It works for both official `gitlab-ce` (`gitlab-ee`) and unofficial`sameersbn/gitlab`. So we have nothing to do here for `sameersbn/gitlab` image.  

I don't know how you are running the container, but here is a part of `docker-compose.yml` example:

```yml
services:
  gitlab:
    image: sameersbn/gitlab:16.5.1
   environment:
    - GITLAB_RAILS_RACK_TIMEOUT_ENABLE=false
```

**Comment by fidoedidoe** [comment]
Hey @kkimurak 

Thanks for your reply (and apologies for the delay in replying). I implemented the Docker Env Var (GITLAB_RAILS_RACK_TIMEOUT_ENABLE=false) but unfortunately it doesn't alleviate the issue I'm experiencing. 

In the logs (/var/log/gitlab/gitlab/production.log) I see (basically a MR has many many comments and times out rendering these to web UI): 

`Rack::Timeout::RequestTimeoutException (Request ran for longer than 60000ms ):`
  
Perhaps I'm misunderstanding the influence this env var has in respect to the above? Any further suggestions/further insight would be very welcomed. 

Kind regards

**Comment by kkimurak** [comment]
Hi @fidoedidoe , sorry for late.

I have noticed that the code introduced by [!90958](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/90958) have been removed by [!92200](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/92200). The environment variable `GITLAB_RAILS_RACK_TIMEOUT_ENABLE` have no effect.  

Alternatively `GITLAB_RAILS_RACK_TIMEOUT_ENABLE_LOGGING` is introduced but it may not solve your problem..

**Comment by kkimurak** [comment]
@fidoedidoe  
Your problem may be temporarily resolved by setting [`GITLAB_RAILS_RACK_TIMEOUT`](https://gitlab.com/gitlab-org/gitlab/-/blob/2d409e139315e8280ec93430b67dc475526d354e/doc/administration/operations/puma.md#change-the-worker-timeout) to a value higher than the default value of "60" (seconds). But it's just a temporal workaround. As far as I researched, we have no method to completely disable request timeout.

**Comment by fidoedidoe** [comment]
@kkimurak - thank you so much for the feedback/insight/understanding of my problem  - very much appreciated!! Let me look into this and I'll update (edit here) once I know more.
