### ISSUE TITLE
ENOENT: No such file or directory

### ISSUE THREAD

**Issue by sergius02** [sameersbn/docker-gitlab#2866]
Hi!

Everytime i try to restart the container the web shows a 500 error page. When i go to see the production.log this error appears when an user open the web:

<pre>
lib/gitlab/middleware/release_env.rb:13:in 'call'

ActionView::Template::Error (Could not load compiled manifest from /home/git/gitlab/public/assets/webpack/manifest.json.

Have you run 'rake gitlab:assets:compile'?

(original error Errno::ENOENT: No such file or directory @ rb_sysopen - /home/git/gitlab/public/assets/webpack/manifest.json)):
    52:
    53:   = webpack_bundle_tag 'super_sidebar' if show_super_sidebar?
    54:
    55:   = webpack_controller_bundle_tags
    56:
    57:   - unless omit_og
    58:     -# Open Graph - http://ogp.me/

lib/gitlab/webpack/manifest.rb:82:in 'rescue in load_manifest'
</pre>

As the error says, i executed rake gitlab:assets:compile, but when it finish, nothing happend and the webpage still no load

**Comment by iDmple** [comment]
I have the same issue after updating to 16.x from 15.x. Anyone has an idea?

**Comment by kkimurak** [comment]
If you are using relative url, #2884 may fix the issue I think.

**Comment by sergius02** [comment]
> If you are using relative url, #2884 may fix the issue I think.

Thats probably my problem. I'm using relative url, and when i delete manually the tmp folder, gitlab can launch succesfully.

**Comment by kkimurak** [comment]
Glad to hear that, and sorry for the delay in providing a solution. I was aware of this problem in May, but I was working on a series of tasks to support postgresql-13 (and later versions) at the same time and forgot I was applying patch to my local instance until I saw this issue..
