### ISSUE TITLE
Upgrade Ruby to 3.2.x to remove bug introduced on Ruby 3.1.x

### ISSUE THREAD

**Issue by CDann3r** [sameersbn/docker-gitlab#2886]
I am running GibLab on my Synology 916+ (Linux 3.10)
My GitLab is running currently with the image `16.6.5`.
When I upgraded to `16.7.3`  it failed with the following error message.

> /home/git/gitlab/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support.rb:26:in 'require'
> /home/git/gitlab/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support.rb:26:in '<top (required)>'
> /home/git/gitlab/vendor/bundle/ruby/3.1.0/gems/railties-7.0.8/lib/rails.rb:7:in 'require'
> /home/git/gitlab/vendor/bundle/ruby/3.1.0/gems/railties-7.0.8/lib/rails.rb:7:in '<top (required)>'
> /home/git/gitlab/config/application.rb:6:in 'require'
> /home/git/gitlab/config/application.rb:6:in '<top (required)>'
> /home/git/gitlab/Rakefile:9:in 'require'
> /home/git/gitlab/Rakefile:9:in '<top (required)>'
> /home/git/gitlab/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in '<top (required)>'
> /usr/local/bin/bundle:25:in 'load'
> /usr/local/bin/bundle:25:in '< main>'

When I tried to execute the `require 'securerandom'` on different ruby versions by using the official docker images, I can proof, that the issue is related to Ruby version 3.1.x
![image](https://github.com/sameersbn/docker-gitlab/assets/14169112/b7d6552b-3575-45e4-9bf1-e1abae0e653e)

Executed commands to reproduce:
```
docker run -it --rm --name ruby-3-2-3 ruby:3.2.3-slim irb
docker run -it --rm --name ruby-3-1-4 ruby:3.1.4-slim irb
docker run -it --rm --name ruby-3-0-6 ruby:3.0.6-slim irb

require 'securerandom'
```

Looking at the Ruby Release Notes, the corresponding features are responsible for the bug and the fix:
[Ruby 3.2.0.preview1](https://github.com/ruby/ruby/releases/tag/v3_2_0_preview1) => [Introduced Fix](https://bugs.ruby-lang.org/issues/13885)
[Ruby 3.1.0](https://github.com/ruby/ruby/releases/tag/v3_1_0) => [Introduced Bug](https://bugs.ruby-lang.org/issues/18190) during refactoring of the `Random::Formatter` class.

This is also related to the issue #2872 

Since GitLab 16.8.0 requires 16.7.x as a mandatory upgrade step, I propose that Ruby is being upgraded for both GitLab 16.7.x and 16.8.x to Ruby 3.2.x

**Comment by mihelm** [comment]
The release notes for GitLab 16.7 refer to Ruby 3.1 as a minimum version, not the required version, so this might be worth a try:

> Administrators installing from source must have Ruby 3.1 as a minimum version when upgrading to GitLab 16.7 or later...

**Comment by kkimurak** [comment]
Hi, I have noticed that my patch (#2884) blocks the upgrade of ruby to 3.2.x so I have submit a pull request to fix it. 

I'm happy if you submit pull request by yourlself if you know what to do (just bumping ruby version for this case). If you are not sure what to do on code even you know theorically what to do, just say so. Someone helps you (at least I'll try so).

**Comment by CDann3r** [comment]
This ticket here is then obsolete with by upgrading to Ruby 3.2.3 which is also backported to 16.7.5.

Thank you @kkimurak

**Comment by MarcusWolschon** [comment]
The 16.7.5 docker image still uses Ruby 3.1 and thus doesn't work on the affected Synology NAS generations.
