### ISSUE TITLE
GitLab Critical Security Release: 16.8.1, 16.7.4, 16.6.6, 16.5.8

### ISSUE THREAD

**Issue by fdcastel** [sameersbn/docker-gitlab#2892]
GitLab Critical Security Release: 16.8.1, 16.7.4, 16.6.6, 16.5.8

https://about.gitlab.com/releases/2024/01/25/critical-security-release-gitlab-16-8-1-released/

**Comment by sachilles** [comment]
This issue has been adressed PRs #2888, #2889, #2890 and #2891.
