### ISSUE TITLE
How to backup GitLab in Kubernetes? Do you have any good ideas, templates, or documentation? I'm not very familiar with Kubernetes, so please help me.

### ISSUE THREAD

**Issue by linux-golang** [sameersbn/docker-gitlab#2894]
How to backup GitLab in Kubernetes? Do you have any good ideas, templates, or documentation? I'm not very familiar with Kubernetes, so please help me.

**Comment by emotroshylov** [comment]
> How to backup GitLab in Kubernetes? Do you have any good ideas, templates, or documentation? I'm not very familiar with Kubernetes, so please help me.

Use https://github.com/sameersbn/docker-gitlab/blob/master/kubernetes/gitlab-rc.yml#L48

**Comment by linux-golang** [comment]
thanks
