### ISSUE TITLE
TERM is not set, so the dialog frontend is not usable.

### ISSUE THREAD

**Issue by lyongde** [sameersbn/docker-gitlab#293]
gitlab doesn't work in Ubuntu14.04,http://192.168.3.100:10080 is not working,postgresql and redis ok..

#docker run --name='gitlab' -d \
  -e 'GITLAB_HOST=192.168.3.100' \
  -e 'GITLAB_PORT=10080' \
  -e 'GITLAB_SSH_PORT=10022' \
  -e 'GITLAB_BACKUPS=weekly' \
  -e 'DB_TYPE=postgres' \
  -e 'DB_HOST=192.168.3.100' \
  -e 'DB_NAME=gitlabhq_production' \
  -e 'DB_USER=gitlab' \
  -e 'DB_PASS=password' \
  -e 'REDIS_HOST=192.168.3.100' \
  -e 'REDIS_PORT=6402' \
  -p 10022:22 -p 10080:80 \
  -v /opt/gitlab/data:/home/git/data \
  -v /opt/gitlab/backups:/home/git/data/backups \
  -v /opt/gitlab/log:ar/log/gitlab \
  sameersbn/gitlab:7.9.4

#docker logs gitlab
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
Creating SSH2 RSA key; this may take some time ...
Creating SSH2 DSA key; this may take some time ...
Creating SSH2 ECDSA key; this may take some time ...
Creating SSH2 ED25519 key; this may take some time ...
invoke-rc.d: policy-rc.d denied execution of restart.

**Comment by sameersbn** [comment]
@lyongde I don't think it would effect the normal function of the container. if TERM needs to be defined, then it should be done by the docker folks in their base images.
