### ISSUE TITLE
Gitlab behind a HTTP Load balancer

### ISSUE THREAD

**Issue by jpillora** [sameersbn/docker-gitlab#294]
Nice work with all your Gitlab docker images, they're very useful :)
I'm running a few webservers behind nginx, gitlab is one of them. Since it's all inside a VPN, I don't need HTTPS. However, in order to run behind nginx, I have to set `GITLAB_HTTPS=true` which yields HTTPS links to clients which then do not work. Is it possible to set the `external_url` somehow? I couldn't see anything about this in the README.

**Comment by jpillora** [comment]
Ah, I added had this `proxy_set_header    X-Forwarded-Ssl     off;` set to `on`. This nginx config seems to be working now with plain HTTP.

```
	# gitlab
	server {
		listen       80;
		server_name  docker.axon, git.axon;
		# add_header X-Frame-Options DENY;
		add_header X-Content-Type-Options nosniff;
		location / {
			## https://github.com/gitlabhq/gitlabhq/issues/694
			## Some requests take more than 30 seconds.
			proxy_read_timeout      300;
			proxy_connect_timeout   300;
			proxy_redirect          off;
	 
			proxy_set_header    Host                $http_host;
			proxy_set_header    X-Real-IP           $remote_addr;
			proxy_set_header    X-Forwarded-Ssl     off;
			proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
			proxy_set_header    X-Forwarded-Proto   $scheme;
			proxy_set_header    X-Frame-Options     SAMEORIGIN;

			proxy_pass http://172.17.8.100:10080;
		}
	}
```

**Comment by sameersbn** [comment]
@jpillora glad to hear that you got the issue figured out.
