### ISSUE TITLE
cannot clone

### ISSUE THREAD

**Issue by lordofinsomnia** [sameersbn/docker-gitlab#295]
I have problem with gitlab. I am using docker for it' starting.

docker-compose.yml
postgresql:
  image: sameersbn/postgresql:9.4
  environment:
    - DB_USER=gitlab
    - DB_PASS=secretpassword
    - DB_NAME=gitlabhq_production
gitlab:
  image: sameersbn/gitlab:7.9.3  
  links:
   - redis:redisio
   - postgresql:postgresql
  ports:
   - "10080:80"
   - "10022:22"
redis:
  image: sameersbn/redis:latest

I cannot clone or push repo.
When I try to clone repo I get this message:
$git clone http://localhost/lordofinsomnia/blog.git

Cloning into 'blog'...
fatal: unable to access 'http://localhost/lordofinsomnia/blog.git/': Failed to connect to localhost port 80: Connection refused

With git protocol I am assked for password, which I don't know
git clone git@localhost:lordofinsomnia/blog.git
Cloning into 'blog'...
git@localhost's password:

Thanks in advance.

**Comment by sameersbn** [comment]
@lordofinsomnia You configuration is incomplete. You should add `GITLAB_PORT=10080` to the gitlab environment variables. With this in place, the http clone urls will be of the form `http://localhost:10080/lordofinsomnia/blog.git`. Notice the port number in there.

In short, with your configuration the gitlab http server cannot be assessed via `localhost:80` on the host. It can only be accessed via `localhost:10080`.

**Comment by lordofinsomnia** [comment]
Thank You, that helped. :)
