### ISSUE TITLE
Is it possible to enable webide extension market?

### ISSUE THREAD

**Issue by aak1247** [sameersbn/docker-gitlab#2985]
![image](https://github.com/user-attachments/assets/64b30960-fba9-4ce3-8fcb-4b961c2fc6fe)

https://docs.gitlab.com/17.2/ee/user/project/web_ide/index.html#extension-marketplace

**Comment by kkimurak** [comment]
You can control its availability via feature flag [`web_ide_extensions_marketplace`](https://gitlab.com/gitlab-org/gitlab/-/blob/e92cae0bc33d1dfeb6ce190e2d3d1f0d3d209de4/config/feature_flags/beta/web_ide_extensions_marketplace.yml). See section ["feature flags"](https://github.com/sameersbn/docker-gitlab?tab=readme-ov-file#feature-flags) in README.md.  
If you are using `sameersbn/gitlab` and want to configure feature flag via configuration parameters,  [`GITLAB_FEATURE_FLAGS_ENABLE_TARGETS`](https://github.com/sameersbn/docker-gitlab?tab=readme-ov-file#gitlab_feature_flags_enable_targets) and [`GITLAB_FEATURE_FLAGS_DISABLE_TARGETS`](https://github.com/sameersbn/docker-gitlab?tab=readme-ov-file#gitlab_feature_flags_disable_targets) are introduced by #2917 but the feature requires #2986 (fix issue that cannot enable some feature). So you can use `sameersbn/gitlab:17.3.0`.

**Comment by aak1247** [comment]
Thanks @kkimurak
