### ISSUE TITLE
Retroactive configuration changes

### ISSUE THREAD

**Issue by jpillora** [sameersbn/docker-gitlab#300]
I just spun up a container without SMTP settings as we don't have it setup yet. What would be the simplest way to add SMTP settings and possibly others down the track?

**Comment by sameersbn** [comment]
@jpillora you could just stop/remove the container, add the required environment variables to configure SMTP support and launch the container again. Provided you have mounted volumes for the data, you will not have any problems.

**Comment by jpillora** [comment]
Ah great, so doing https://github.com/sameersbn/docker-gitlab#data-store is all I need?

**Comment by sameersbn** [comment]
@jpillora yep. mounting a data volume is absolutely necessary if you are using the image in production.

**Comment by jpillora** [comment]
Easy, thanks!
