### ISSUE TITLE
error when setting the GITLAB_HOST variable

### ISSUE THREAD

**Issue by aguilbau** [sameersbn/docker-gitlab#301]
I get the following error when adding the environment variable `GITLAB_HOST` (see last line):
`Database connection details not specified.

Will try to spin up a new postgresql image with the name postgresql-gitlab.
Please manually configure the database connection in production.
Using existing postgresql container...
Redis connection details not specified.
Will try to spin up a new redis image with the name redis-gitlab.
Please manually configure the redis connection in production.
Using existing redis container...
sed: -e expression #1, char 25: unknown option to s'
`

Here is the original functional launch command:
`docker run --name='gitlab' -d -e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=10022' -e 'SMTP_USER=?' -e 'SMTP_PASS=?' -p 10022:22 -p 10080:80 -v /var/run/docker.sock:/run/docker.sock -v $(which docker):/bin/docker -v /opt/gitlab/data:/home/git/data sameersbn/gitlab`

**Comment by sameersbn** [comment]
@aguilbau your `SMTP_PASS` probably has a `'` or a `/` character, which you should probably escape of remove it altogether. These characters confuse the `sed` substitution.

**Comment by sameersbn** [comment]
@aguilbau was your issue resolved?

**Comment by ivanalejandro0** [comment]
I've seen that issue, my problem was to set a value containing `/` for the `GITLAB_TIMEZONE` option.
For the case in the readme, instead of setting `Kolkata` I set it as `Asia/Kolkata`, (I misread "Kolkata" => "Asia/Kolkata" in the supported TimeZone docs).
Maybe that's the same problem for you since the command line doesn't seem to be complete.
Cheers.

**Comment by johnjelinek** [comment]
I'm getting this error too:
```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
Creating SSH2 RSA key; this may take some time ...
Creating SSH2 DSA key; this may take some time ...
Creating SSH2 ECDSA key; this may take some time ...
Creating SSH2 ED25519 key; this may take some time ...
invoke-rc.d: policy-rc.d denied execution of restart.
sed: -e expression #1, char 24: unknown option to `s'
```

I'm using external redis and external postgres.

environment vars:
```
GITLAB_BACKUPS=daily
GITLAB_EMAIL=gitlab@johnjelinek.com
GITLAB_EMAIL_REPLY_TO=noreply@johnjelinek.com
GITLAB_HOST=gitlab.cloudapps.johnjelinek.com
DB_TYPE=postgres
DB_HOST=postgresql.gitlab.svc.cluster.local
REDIS_HOST=redis.gitlab.svc.cluster.local
REDIS_PORT=6379
```

**Comment by johnjelinek** [comment]
(I got the error in both `7.10.4` and `latest`)

**Comment by sameersbn** [comment]
@johnjelinek some configuration parameter is confusing `sed`. This commonly occurs if a `/` character is present in one of the strings, eg. in password or as @ivanalejandro0 metioned, though the `GITLAB_TIMEZONE` parameter should not include a `/` character. 

Please try adding the configuration parameters one by one to find out which one is causing the issue. Or paste your docker run command here.

**Comment by johnjelinek** [comment]
I figured out that my environment was hijacking the REDIS_PORT env with tcp://IP:port. `set -x` helped me debug a lot. Maybe `set -x` should be on by default.



—

**Comment by sameersbn** [comment]
@johnjelinek setting `set -x` bu default might now be such a good thing. Maybe we can add a `DEBUG` configuration parameter that will do `set -x`

**Comment by johnjelinek** [comment]
I like that idea, it's nicer than `docker exec ..` and modifying the entrypoint manually.

**Comment by jcw9930** [comment]
I have a similar issue:
```
+ sudo -HEu git sed 's/{{GITLAB_PORT}}/tcp://10.254.118.109:10080/' -i config/gitlab.yml
sed: -e expression #1, char 24: unknown option to `s'
``` 
How to work around the "environment hijacking"?

**Comment by jcw9930** [comment]
For my case it was enough to rename the kubernetes service "gitlab" to "gitlab-svc"

**Comment by sameersbn** [comment]
closing this issue. please reopen if you are still facing problems with this.
