### ISSUE TITLE
v17.4.1 postgresql-client-16 is missing

### ISSUE THREAD

**Issue by fidoedidoe** [sameersbn/docker-gitlab#3015]
while testing a non-production upgrade from version v17.3.1 -> 17.4.1 I can see the postgresql-client-16 is no longer present. The log output being: 

```
...
Configuring /home/git/.postgresqlrc to avoid version mismatch on dumping
- Detected server version: 160004
gitlab_generate_postgresqlrc(): WARNING - Suitable client not installed. postgresql-client-17 will be used but you may face issue (database in backup will be empty, for example)
- Generating /home/git/.postgresqlrc
17 myhostname:8432 gitlab
- Uninstalling unused client(s): postgresql-client-13 postgresql-client-14 postgresql-client-15
...
```

The Official GitLab documentation ([link](https://docs.gitlab.com/ee/administration/package_information/postgresql_versions.html)), reads: 

```
First GitLab version | PostgreSQL versions | Default version for fresh installs | Default version for upgrades | Notes
17.4.0               | 14.11, 16.4         | 14.11                              |14.11                         |PostgreSQL 16 is available for new installations 
```

Am I mistaken, or should the postgresql-client-16 be included?

**Comment by kkimurak** [comment]
Good point, it should be added to [Dockerfile](https://github.com/sameersbn/docker-gitlab/blob/81e01989867875b025ef489d114729708c6f8898/Dockerfile#L49) and [README.md](https://github.com/sameersbn/docker-gitlab/blob/81e01989867875b025ef489d114729708c6f8898/README.md?plain=1#L264-L268).

Do you have plan to submit a PR? Or should I do that?

**Comment by fidoedidoe** [comment]
> Good point, it should be added to [Dockerfile](https://github.com/sameersbn/docker-gitlab/blob/81e01989867875b025ef489d114729708c6f8898/Dockerfile#L49) and [README.md](https://github.com/sameersbn/docker-gitlab/blob/81e01989867875b025ef489d114729708c6f8898/README.md?plain=1#L264-L268).
> 
> Do you have plan to submit a PR? Or should I do that?

a PR is probably beyond my skill level, if you're open to doing one it would be very much appreciated!!

**Comment by kkimurak** [comment]
@fidoedidoe Done - see #3017. Thank you for your report!
