### ISSUE TITLE
Critical Patch Release: 17.4.2, 17.3.5, 17.2.9

### ISSUE THREAD

**Issue by tomaszmrugalski** [sameersbn/docker-gitlab#3019]
A critical security update was released yesterday (Oct 9) for 17.4.2, 17.3.5, 17.2.9.

Details: https://about.gitlab.com/releases/2024/10/09/patch-release-gitlab-17-4-2-released/

**Comment by tc414103685** [comment]
The document has been updated to 17.4.2, but it is not available on Dockerhub.

**Comment by tc414103685** [comment]
@sachilles

**Comment by kkimurak** [comment]
@tc414103685 I think it will be released after #3023 is merged.  
The release process is automated and takes approximately 1 hour (triggered by pushing a version tag in the specified format to github).  
Just wait for it, or if you are extremely in hurry, just build the image by yourself.

**Comment by tc414103685** [comment]
@kkimurak Good, Thank you

**Comment by sachilles** [comment]
@kkimurak @tc414103685 Unfortunately, we mostly hit a (time) limit for the CI process. The build process is stopped automatically after one hour. Since there are different runners (with different processors and speed) the build time variies and thus, it's currently "just" a question of good luck to hit the fast runners for the CI.

**Comment by kkimurak** [comment]
@sachilles We have something to do to improve build speed - introducing multi stage build, using golang base image to build middlewares and just copy it to final image and so on - they are what I'm planning to try but I'm busy this month..  

It should be possible to extend the time until the timeout by changing the `no_output_timeout` setting in [.circleci/config.yml](, but will this have any effect? Or are there any parameters set in CircleCI web dashboard?

**Comment by tomaszmrugalski** [comment]
All releases (17.4.2, 17.3.5, 17.2.9) are now available. On behalf of myself and numerous users, thank you for doing this particular release and this whole packaging project in general.

Much appreciated!
