### ISSUE TITLE
Allow changing external_url parameter

### ISSUE THREAD

**Issue by andreptb** [sameersbn/docker-gitlab#302]
Hi,
I'm running GitLab behind a proxy and clone links are generated with **localhost** and not my domain address. As mentioned [here](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/README.md#configuring-the-external-url-for-gitlab), shouldn't I need to configure external_url parameter to fix this? I couldn't find a way to do that with this docker image.

**Comment by hydrosIII** [comment]
Hi, i had this problem. It is simple to solve just use the enviroment variable GITLAB_HOST in your docker startup script

example:

docker run --name=gitlab -it --rm  -e "GITLAB_HOST=mydomain.com"   sameersbn/gitlab:7.10.0

**Comment by sameersbn** [comment]
@hydrosIII thanks for pitching in. Much appreciated.

**Comment by sameersbn** [comment]
@andreptb did @hydrosIII's  suggestion resolve your issue?

**Comment by andreptb** [comment]
@sameersbn sorry for the delay, the clone links are now generating properly! However  I'm facing **Permission denied (publickey).** while cloning with SSH, using a key registrated  through GitLab GUI. Issue #26 seems to be similar, but I need to further investigate. Where can I find ssh access logs on the container?

Since my original problem is resolved I'm closing this issue.

**Comment by andreptb** [comment]
Answering my own question, I could found gitlab ssh logs inside the container in the following path: /var/log/gitlab/supervisor/sshd.log
