### ISSUE TITLE
docker image gitlab-ce:17.6.0-ce.0，OpenSSH_8.9p1 version is too low and has high-risk vulnerabilities

### ISSUE THREAD

**Issue by hellozrh** [sameersbn/docker-gitlab#3037]
docker image:
```ssh
docker pull gitlab/gitlab-ce:latest
```
or
```ssh
docker pull gitlab/gitlab-ce:17.6.0-ce.0
```

```ssh
docker exec gitlab-ce-demo ssh -V
OpenSSH_8.9p1 Ubuntu-3ubuntu0.10, OpenSSL 3.0.2 15 Mar 2022
```

The latest version of OpenSSH is OpenSSH_9.8p1, please upgrade to the latest version.

**Comment by kkimurak** [comment]
Here is a repository for `sameersbn/gitlab`, not `gitlab/gitlab-ce`. Please report it on https://gitlab.com/gitlab-org/omnibus-gitlab

**Comment by hellozrh** [comment]
> This is a repository for `sameersbn/gitlab`, not `gitlab/gitlab-ce`. Please report it on https://gitlab.com/gitlab-org/omnibus-gitlab

I see. Thanks for the reminder.
