### ISSUE TITLE
gitlab.yml resets after container restart

### ISSUE THREAD

**Issue by ParadoxDelta** [sameersbn/docker-gitlab#305]
I did some changes to the ~/git/gitlab/config/gitlab.yml of my gitlab-container to show the real SSH-URL in the Web-Interface and not ssl://localhost/projectname. But everytime i stop and start the container again, the config-file is set back to default.

**Comment by sameersbn** [comment]
You are not supposed to edit those files manually. Use GITLAB_HOST

**Comment by ParadoxDelta** [comment]
I see. Is there a way to change this on my current container or do i have to commit and start a new container with run -e GITLAB_HOST=my.domain

**Comment by sameersbn** [comment]
@ParadoxDelta If you have mounted a data volume then you can recreate the container with the new parameters without any loss of data.

**Comment by NezumiRyu** [comment]
You can use --env-file= with GITLAB_HOST=my.domain
