### ISSUE TITLE
Why i enable SSL, the port 443 is not open? 

### ISSUE THREAD

**Issue by YauzZ** [sameersbn/docker-gitlab#309]
> 3c5af6c97065        sameersbn/gitlab:latest       "/app/init app:start   22 seconds ago      Up 21 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:10022->22/tcp   gitlab

except 443, other port is open.

**Comment by sameersbn** [comment]
@YauzZ please be a bit more verbose with your query. I don't understand your question

**Comment by YauzZ** [comment]
@sameersbn i solved.   

because i don't path the ssl certs.  please forgive me.
