### ISSUE TITLE
unicorn continuously exits

### ISSUE THREAD

**Issue by alininja** [sameersbn/docker-gitlab#311]
Hi,

Thanks for providing the container.  It is extremely helpful.  :smile: 

I'm running into a similar problem as #255 

I'm getting the same error message:
```
gitlab_1        | Starting supervisord...
gitlab_1        | 2015-05-07 20:23:52,167 CRIT Supervisor running as root (no user in config file)
gitlab_1        | 2015-05-07 20:23:52,167 WARN Included extra file "/etc/supervisor/conf.d/sidekiq.conf" during parsing
gitlab_1        | 2015-05-07 20:23:52,167 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
gitlab_1        | 2015-05-07 20:23:52,167 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
gitlab_1        | 2015-05-07 20:23:52,167 WARN Included extra file "/etc/supervisor/conf.d/sshd.conf" during parsing
gitlab_1        | 2015-05-07 20:23:52,167 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
gitlab_1        | 2015-05-07 20:23:52,189 INFO RPC interface 'supervisor' initialized
gitlab_1        | 2015-05-07 20:23:52,189 CRIT Server 'unix_http_server' running without any HTTP authentication checking
gitlab_1        | 2015-05-07 20:23:52,189 INFO supervisord started with pid 1
gitlab_1        | 2015-05-07 20:23:53,192 INFO spawned: 'sidekiq' with pid 601
gitlab_1        | 2015-05-07 20:23:53,193 INFO spawned: 'unicorn' with pid 602
gitlab_1        | 2015-05-07 20:23:53,194 INFO spawned: 'cron' with pid 603
gitlab_1        | 2015-05-07 20:23:53,195 INFO spawned: 'nginx' with pid 604
gitlab_1        | 2015-05-07 20:23:53,198 INFO spawned: 'sshd' with pid 605
gitlab_1        | 2015-05-07 20:23:54,752 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1        | 2015-05-07 20:23:54,752 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1        | 2015-05-07 20:23:54,752 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1        | 2015-05-07 20:23:54,752 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1        | 2015-05-07 20:23:54,752 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1        | 2015-05-07 20:24:00,293 INFO exited: unicorn (exit status 1; not expected)
gitlab_1        | 2015-05-07 20:24:00,296 INFO spawned: 'unicorn' with pid 628
gitlab_1        | 2015-05-07 20:24:00,297 INFO exited: sidekiq (exit status 1; not expected)
gitlab_1        | 2015-05-07 20:24:00,810 INFO spawned: 'sidekiq' with pid 631
gitlab_1        | 2015-05-07 20:24:01,811 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1        | 2015-05-07 20:24:01,812 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1        | 2015-05-07 20:24:07,171 INFO exited: unicorn (exit status 1; not expected)
gitlab_1        | 2015-05-07 20:24:07,198 INFO spawned: 'unicorn' with pid 651
gitlab_1        | 2015-05-07 20:24:07,198 INFO exited: sidekiq (exit status 1; not expected)
gitlab_1        | 2015-05-07 20:24:07,712 INFO spawned: 'sidekiq' with pid 654
gitlab_1        | 2015-05-07 20:24:08,714 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1        | 2015-05-07 20:24:08,714 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1        | 2015-05-07 20:24:13,677 INFO exited: unicorn (exit status 1; not expected)
gitlab_1        | 2015-05-07 20:24:14,679 INFO spawned: 'unicorn' with pid 675
```

I'm using docker-machine and docker-compose with this docker-compose.yml snippet that was derived from your project's docker-compose.yml:
```
gitlab:
  image: sameersbn/gitlab:7.10.1
  links:
   - redis:redisio
   - postgresql:postgresql
  ports:
   - 80
   - 22
redis:
  image: sameersbn/redis:latest
postgresql:
  image: sameersbn/postgresql:9.4
  environment:
    - DB_USER=gitlab
    - DB_PASS=secretpassword
    - DB_NAME=gitlabhq_production
```

I've tried running these commands:
```
docker-compose run gitlab app:sanitize
```
```
docker-compose run gitlab mv /home/git/gitlab/tmp /home/git/gitlab/tmp_backup
```
```
docker-compose stop
docker-compose start
docker-compose restart
docker-compose rm
docker-compose up
```

The host os where these commands are issued from is:
ubuntu 14.04
Linux3.13.0-52-generic x86_64
Docker version 1.5.0, build a8a31ef
docker-machine version 0.2.0 (8b9eaf2)
docker-compose 1.1.0

The host os that the container resides is:
boot2docker 1.5.0

Also, when I first issued `docker-compose up` the site comes up fine.  But I was never able to bring it back up again after that first success.

Thanks again for this container and your time!

**Comment by JacobHenner** [comment]
How much memory are you running on? Are you exceeding the memory available?

**Comment by sameersbn** [comment]
@alininja you can exec into the container and check the supervisor and other logs. However @JacobHenner raises a very important question. Gitlab requires a minimum `1G` of RAM available to start without which the app will basically freak out.

**Comment by alininja** [comment]
Thank you @JacobHenner and @sameersbn for the suggestions.  I'll check the machine in a few days and will report back.  If I can rule out the memory requirement, then I'll check the supervisor logs following this (I've never used supervisor before):
http://supervisord.org/logging.html
If you know of an easier way to check logs, then please let me know.  Thanks again and have a good weekend.

**Comment by sameersbn** [comment]
@alininja you can `exec` into the container 

```bash
docker exec -it gitlab_1 bash
cd  /var/log/gitlab
```
You will find all the logs under various sub directories.

**Comment by alininja** [comment]
Hi @JacobHenner and @sameersbn.  Following your suggestions I up'ed the memory from `1GB` to `2GB` and things are working.  I had other containers running so they probably took up too much memory from GitLabs.

Thanks again for the container and your help.

For completeness, in the sidekiq log (`/var/log/gitlab/supervisor/sidekiq.log`), there was this line:
```
Cannot allocate memory - git
```

**Comment by changtimwu** [comment]
Hi!  I'd like add some notes here.    I encountered the same issue when hosting docker-gitlab on a digitalocean 10mo droplet.  Adding swap memory could be a really simple & quick fix.  Unicorn gets working instantly once upon I entering "swapon".  I even don't need to restart the gitlab container.  https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

**Comment by pbrackin** [comment]
I recently saw this same symptom trying to get this container up on Synology (because Synology is pretty far behind on theirs, and I needed some fixes in the newer Gitlab).  Execing into the container (thanks @sameersbn), I found my issue in the sidekiq.log:  "Invalid Timezone: Los_Angeles".  So, in the docker-compose.yml, I needed to fix GITLAB_TIMEZONE.  Had to be "America/Los_Angeles".  Totally my fault - but very difficult to debug if you don't know where to look.  Usually I use UTC for everything, but I couldn't use the default UTC for this particular project.  

I would add this:  the CPU was pegging at 50% with this issue, so someone may be a bit tight on their loop in there somewhere..

**Comment by davidmoshal** [comment]
I know this is closed, but I too struggled to find the problem, eventually finding exactly the same error: 

`Invalid Timezone: Los_Angeles` in the same log file.

Came here to post the solution, and found the above solution.

My bad for not reading to the end of the comments!
