### ISSUE TITLE
Invalid service name  of 7.10.3

### ISSUE THREAD

**Issue by linlinlinlin** [sameersbn/docker-gitlab#312]
After upgrade docker-compose.yml to 7.10.3.

It cannot work with docker-compose right now.

    Invalid service name "postgresql-gitlab" - only [a-zA-Z0-9] are allowed

**Comment by sameersbn** [comment]
@linlinlinlin I made the stupid mistake of adding `-` characters in the container names. I have removed them now. You can download the `docker-compose.yml` file and retry. Please close this issue once you verify that the issue has been resolved. Thanks.
