### ISSUE TITLE
Gitlab stuck on: "Checking for ability to automatically merge" for Merge Request

### ISSUE THREAD

**Issue by sabhiram** [sameersbn/docker-gitlab#313]
Hey Sameer - this is an awesome project and we use it for our development env daily. Things have been going smoothly so far, except today when I tried to merge a request - I got stuck on "Checking for ability to automatically merge...".

I tried the few things mentioned here: https://github.com/gitlabhq/gitlabhq/issues/1104 to no avail.

Would appreciate a pointer when you get to it. Also seems like when I try to run the container from inside the w/ docker exec, I am unable to kick off the rake job to enable automerges etc.

Any help would be appreciated! thanks!

**Comment by sameersbn** [comment]
@sabhiram I don't know what the issue could be or how to fix it. You should report it to the upstream gitlab project.

What database server are you using? If its mysql then it is probably the cause of your issue.

**Comment by sameersbn** [comment]
@sabhiram If you do use mysql then you can take a look at #125

**Comment by sabhiram** [comment]
Oh doh - it is mysql... I will attempt to bump the packet size right now and report back. Wish I knew about this sooner lol. Thanks for the pointer @sameersbn

**Comment by sabhiram** [comment]
The strange thing is - the instance also fails to allow me to fetch any of the downloads via the download buttons. Regardless of if it is a zip or a diff or a release. To make matters more awesome - we run a SELinux host, and use an NFS file mount :)

Worst case ill scratch it on a dedicated VM :)

**Comment by sameersbn** [comment]
@sabhiram that is one of the reason why there is a *Recommended* against Postgresql in the readme :smile:

**Comment by sabhiram** [comment]
@sameersbn - I guess what is strange to me is the fact that even plain text diffs do not download, nor do archives of git projects. I can try and whip up a postgres db and see where it lands - do you know if the other (download) issues occur (potentially) due to the sql container?

**Comment by sameersbn** [comment]
@sabhiram no idea. I am only aware of merge issues so far.

**Comment by johnjelinek** [comment]
This is happening to me too, and I'm using postgres 9.4.

**Comment by sabhiram** [comment]
Yep, I still use sameer's awesome other dockerfiles, but something as vital as gitlab should not be down for small organizations. We moved to a dedicated smartOS vm for gitlab that is snapshotted every hour or so.

**Comment by sameersbn** [comment]
@johnjelinek what version of gitlab are you using. Do you notice anything in the logs? Try looking up the logs in the `/var/log/gitlab` directory.

**Comment by sameersbn** [comment]
@johnjelinek @sabhiram can you please take a look at https://github.com/gitlabhq/gitlabhq/issues/1104

**Comment by sameersbn** [comment]
Also take a look at https://github.com/gitlabhq/gitlab-public-wiki/wiki/Trouble-Shooting-Guide

You might also want to try starting the container with `app:sanitize` argument to make sure that all files and directories have the right ownership and permissions as it is listed as a probable cause of the issue.

If that does not help, the please try launching the raketask to create the satellites directories https://github.com/gitlabhq/gitlabhq/blob/master/doc/raketasks/maintenance.md#re-create-satellite-repositories. Refer to the README on how to launch raketasks.

**Comment by sameersbn** [comment]
@johnjelinek let me know if any of the above suggestions fixes the issue.

**Comment by johnjelinek** [comment]
I'm using 7.11.4 and I grepped the logs and didn't find anything.

**Comment by sameersbn** [comment]
@johnjelinek please do try the other suggestions and let me know. Thank you.

**Comment by simkin** [comment]
I am having the same issue. upping the max_allowed_packet value in my.cn did not fix it for me. Log files contain no obvious errors.

GitLab 7.12.1 f6fb946 on Centos

**Comment by sameersbn** [comment]
@simkin can you please try the suggestions in https://github.com/sameersbn/docker-gitlab/issues/313#issuecomment-114942729

**Comment by simkin** [comment]
I upgrade to the latest version 7.13.2 that resolved the issue, thanks for your suggestion though!

**Comment by sameersbn** [comment]
@simkin great!
