### ISSUE TITLE
Add support for smtp over tls.

### ISSUE THREAD

**Issue by noonien** [sameersbn/docker-gitlab#315]
According to the [documentation](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/smtp.md) `smtp_tls` can be set so that the SMTP connection is done over TLS.

**Comment by andredasilvapinto** [comment]
+1

My server doesn't support STARTTLS but it supports TLS. As there is no environment property for enabling TLS, I have to use plain text...

This seems to have been added 1 year ago: https://gitlab.com/gitlab-org/omnibus-gitlab/merge_requests/152

**Comment by andredasilvapinto** [comment]
thanks!

**Comment by sameersbn** [comment]
@andredasilvapinto please test and let me know if it works and/or if you see any issues.

**Comment by andredasilvapinto** [comment]
@sameersbn it doesn't seem to be in docker hub yet?

https://registry.hub.docker.com/u/centurylink/gitlab/builds_history/38813/

**Comment by andredasilvapinto** [comment]
@sameersbn I am using this one: https://registry.hub.docker.com/u/centurylink/gitlab/ which builds on top of yours and still uses sameersbn/gitlab:7.3.0. I guess I will have to wait till they release a new version... or recreate it myself.

**Comment by andredasilvapinto** [comment]
asked for an upgrade on the project: https://github.com/CenturyLinkLabs/docker-gitlab/issues/3

and actually now that I think about it, the issue that I previously reported there, I should have reported it here, but considering that it is from an old release maybe it is even fixed already: https://github.com/CenturyLinkLabs/docker-gitlab/issues/2

**Comment by sameersbn** [comment]
@andredasilvapinto I don't know the reason you are using the `CenturyLinkLabs/docker-gitlab` image and under what environment. But whatever the `CenturyLinkLabs/docker-gitlab` is setup to do is now done by default in the `sameersbn/gitlab` image. That is probably why they have stopped updating it. Consider switching to `sameersbn/gitlab:7.12.0`

**Comment by andredasilvapinto** [comment]
OK. I started using CenturyLinkLabs/docker-gitlab simply because that's the image the templates in Panamax use.
I think I will create my own template (with PostgreSQL and Redis) then, but it's always better to not reinvent the wheel when you don't need to.

**Comment by andredasilvapinto** [comment]
I just had the chance to test this today. It is working properly. Thank you!

**Comment by sameersbn** [comment]
@andredasilvapinto thanks for the feedback.
