### ISSUE TITLE
redis can't work

### ISSUE THREAD

**Issue by alexwhen** [sameersbn/docker-gitlab#320]
redis_1      | [9] 14 May 13:19:52.866 # Server started, Redis version 2.8.4
redis_1      | [9] 14 May 13:19:52.866 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1      | [9] 14 May 13:19:52.866 * The server is now ready to accept connections on port 6379
redis_1      | [9] 14 May 13:19:52.866 * The server is now ready to accept connections at /var/run/redis/redis.sock

**Comment by sameersbn** [comment]
@alexwhen why do you say redis does not work? The log you pasted looks valid to me.

**Comment by alexwhen** [comment]
fixed it,thank you
