### ISSUE TITLE
use docker-compose in "Background saving started" loop

### ISSUE THREAD

**Issue by chyuaner** [sameersbn/docker-gitlab#336]
I use `wget https://raw.githubusercontent.com/sameersbn/docker-gitlab/master/docker-compose.yml
docker-compose up` to install gitlab.
But auto install redis docker is stuck.

    redis_1      | [1] 05 Jun 06:27:25.070 * Background saving started by pid 148
    redis_1      | [148] 05 Jun 06:27:25.097 * DB saved on disk
    redis_1      | [148] 05 Jun 06:27:25.098 * RDB: 0 MB of memory used by copy-on-write
    redis_1      | [1] 05 Jun 06:27:25.170 * Background saving terminated with success
    redis_1      | [1] 05 Jun 06:32:26.054 * 10 changes in 300 seconds. Saving...
    redis_1      | [1] 05 Jun 06:32:26.055 * Background saving started by pid 149

In this loop during 11 hours.
![un loop img](http://i.imgur.com/K38XLii.png)

**Comment by sameersbn** [comment]
@chyuaner This is normal behaviour of the redis-server. Nothing to be alarmed about.

**Comment by sameersbn** [comment]
@chyuaner Closing this issue as this is normal redis behaviour. Nothing to be alarmed about.

**Comment by fuadqerja** [comment]
hi there i'm facing the same issue here, the thing is i can't run my project in local if this keeps looping
