### ISSUE TITLE
backup failed via crontab

### ISSUE THREAD

**Issue by vince67** [sameersbn/docker-gitlab#337]
Using scripts I can make backups in manual.

But it failed when I write this task into crontab.

Error logs like this:
```
time="2015-06-08T14:02:01+08:00" level=fatal msg="cannot enable tty mode on non tty input"
```

And the crontab task is as follow:
```
02 14 * * * bash /.../gitlab/backups.sh > /.../gitlab/log/cron.log 2>&1
```

**Comment by sameersbn** [comment]
@vince67

You can enable automated backups in the image to take `daily`, `monthly` or `weekly` backups

Regarding the error you are seeing. I don't clearly understand where you are installing the above cron job (on host or container) and what the contents of `backup.sh` are. Either way, the issue could be with your use of `...` in the script path.

**Comment by vince67** [comment]
I installed the cron job on host not the container. 
And those `...` mean '/mypath/to/backups.sh',  :).

Here is the file backups.sh:
```bash
docker run \
	--name='gitlab-backup' \
	-it \
	--rm \
	--link gitlab-mysql:mysql \
	--link gitlab-redis:redisio \
	-v /var/run/docker.sock:/run/docker.sock \
	-v $(which docker):/bin/docker \
	-v /path/on/host/data:/home/git/data \
	-v /path/on/host/log:/var/log/gitlab \
	sameersbn/gitlab:7.10.4 app:rake gitlab:backup:create
```

In fact, I have enabled the automated backups in gitlab container's start env file.
when run `docker inspect gitlab`, can find these sentences:
```bash
 "GITLAB_BACKUP=daily",
 "GITLAB_BACKUP_EXPIRY=604800",
 "GITLAB_BACKUP_TIME=04:00",
```
But I haven't get any backups , that's why I tried  the crontab.

And sure I have mounted `/home/git/data` into `/path/on/host/data`, `/var/log/gitlab` into `/path/on/host/log`.

I can see logs correctly.

**Comment by sameersbn** [comment]
@vince67 is the container running running at all times? if not you can specify your timezone using the environment variable `TZ`, eg. `-e 'TZ=Asia/Kolkata'`. 

Can you share the docker run command you use to run the container. I can check it out locally.

**Comment by vince67** [comment]
Thx for attention.

I fixed it. It's my fault to give a wrong configure value. 

Can get backups now by enabling the automated backups.

**Comment by archcra** [comment]
What is the "wrong configure value"?
