### ISSUE TITLE
Merge updated Gitlab SSL config

### ISSUE THREAD

**Issue by robinro** [sameersbn/docker-gitlab#339]
There are updates to gitlab nginx SSL config that are not yet available in this image. Especially:
https://gitlab.com/gitlab-org/gitlab-ce/commit/8aff39a6d0a63e904ada910900ee07a1c3190a9d
This (between other tihngs) redirects http requests to the fqdn of the server, such that aliases and non-fqdn can be used when referencing without breaking ssl.

The 7.11 branch has the patch (also the 7.10 branch for that matter).
https://gitlab.com/gitlab-org/gitlab-ce/blob/7-11-stable/lib/support/nginx/gitlab-ssl

Thanks for providing the docker image. It is extremely useful for us!

**Comment by sameersbn** [comment]
@robinro are you refering to the `ssl_stapling` options?

**Comment by robinro** [comment]
nevermind, this was a configuration issue on our side

**Comment by sameersbn** [comment]
@robinro okay.. thanks for closing the issue :wink:
