### ISSUE TITLE
FATA[0126]  Error pulling image (14.04.20150604) from sameersbn/ubuntu, Untar exit status 1 unexpected EOF

### ISSUE THREAD

**Issue by kixiro** [sameersbn/docker-gitlab#340]
Problem:

~/docker-gitlab# docker build -t gitlab .
Sending build context to Docker daemon 99.33 kB
Sending build context to Docker daemon 
Step 0 : FROM sameersbn/ubuntu:14.04.20150604
14.04.20150604: Pulling from sameersbn/ubuntu
e118faab2e16: Downloading [>                                                  ] 621.7 kB/65.77 MB
e118faab2e16: Error downloading dependent layers 
e04c66a223c4: Download complete 
fa81ed084842: Download complete 
f5b77ae2c674: Download complete 
4088bd6c4599: Downloading [=>                                                 ] 85.55 kB/3.242 MB
4088bd6c4599: Error pulling image (14.04.20150604) from sameersbn/ubuntu, Untar exit status 1 unexpected EOF 
INFO[0126] Error pulling image (14.04.20150604) from sameersbn/ubuntu, Untar exit status 1 unexpected EOF
 
~/docker-gitlab# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

**Comment by sameersbn** [comment]
@kixiro this is docker hub download issue i think. The only suggestion I can give is to retry.

**Comment by kixiro** [comment]
I repeated several times. :

# docker build -t gitlab .
Sending build context to Docker daemon 99.33 kB
Sending build context to Docker daemon 
Step 0 : FROM sameersbn/ubuntu:14.04.20150604
14.04.20150604: Pulling from sameersbn/ubuntu
4088bd6c4599: Download complete 
4088bd6c4599: Error pulling image (14.04.20150604) from sameersbn/ubuntu, Untar read tcp 54.230.44.176:443: i/o timeout  
e118faab2e16: Download complete 
7e2c5c55ef2c: Download complete 
e04c66a223c4: Download complete 
fa81ed084842: Download complete 
f5b77ae2c674: Download complete 
INFO[0126] Error pulling image (14.04.20150604) from sameersbn/ubuntu, Untar read tcp 54.230.44.176:443: i/o timeout 

In log docker.log:
time="2015-06-10T11:05:41+03:00" level=error msg="Error from V2 registry: unable to copy v2 image blob data: read tcp 54.230.46.99:443: i/o timeout" 
Error pulling image (14.04.20150604) from sameersbn/ubuntu, Untar read tcp 54.230.44.176:443: i/o timeout 
time="2015-06-10T11:06:44+03:00" level=info msg="-job pull(sameersbn/ubuntu, 14.04.20150604) = ERR (1)" 
Error pulling image (14.04.20150604) from sameersbn/ubuntu, Untar read tcp 54.230.44.176:443: i/o timeout
time="2015-06-10T11:06:44+03:00" level=info msg="-job build() = ERR (1)"

**Comment by kixiro** [comment]
ОК.

docker pull sameersbn/ubuntu
latest: Pulling from sameersbn/ubuntu
d42614196ae9: Download complete 
d42614196ae9: Download complete 
e118faab2e16: Download complete 
7e2c5c55ef2c: Download complete 
e04c66a223c4: Download complete 
fa81ed084842: Download complete 
e468f2229f3f: Download complete 
Status: Downloaded newer image for sameersbn/ubuntu:latest

**Comment by sameersbn** [comment]
try `docker pull sameersbn/ubuntu:14.04.20150604` cause that is the specific tag used by the image
