### ISSUE TITLE
Could not start container when using timezone with a slash

### ISSUE THREAD

**Issue by urquilla** [sameersbn/docker-gitlab#342]
After configuring the environment variables and starting the containers using docker-compose received this output:

    gitlab_1     | sed: -e expression #1, char 31: unknown option to `s'
    gitlab_gitlab_1 exited with code 1

Which resulted somewhat cryptic, after fooling around found that using a slash in the timezone variable produced an error with the sed regex.

The workaround was using a backwards slash to escape it:

    - GITLAB_TIMEZONE=America\/El_Salvador

**Comment by sameersbn** [comment]
@urquilla you need to specify the constant that maps to your timezone listed here http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html.

For example, if I want to set the timezone to `Asia/Kolkata`, I need to use `GITLAB_TIMEZONE=Kolkata`. Please check the constants listed in the above link and use the appropriate one.

**Comment by urquilla** [comment]
I see, thank you very much

**Comment by sameersbn** [comment]
The `&` character is now automatically escaped. If you have manually escaped the `&` character, then you need to remove it in versions > 8.1.x.
