### ISSUE TITLE
GITLAB_HOST ignored

### ISSUE THREAD

**Issue by utrack** [sameersbn/docker-gitlab#345]
Here's my launch command:
```
docker run --name='gitlab' -d --link=pg1:postgresql --link=redis-gitlab:redisio --publish=10022:22 --publish=10080:80 --env='GITLAB_SSH_PORT=10022' --env='DB_NAME=gitlab' --env='DB_USER=gitlab' --env='GITLAB_HTTPS=true' --env='DB_PASS=mypass' --env='GITLAB_HOST=git.my.host' -v /opt/docks/gitlab:/home/git/data sameersbn/gitlab:7.11.4
```
Everything works OK, but the branch dropdowns still point to localhost:10080.

I'm talking about these ones:
![scrot-20150612_201359](https://cloud.githubusercontent.com/assets/3862920/8135390/aa30409e-113f-11e5-83cd-7c35fdfa409b.jpg)

**Comment by sameersbn** [comment]
@utrack u mean `GITLAB_HOST` right? Can you clear the browser cache and check again.

**Comment by utrack** [comment]
@sameersbn whoops, typo : )

Yeah, GITLAB_HOST as it is in code, and clearing cache doesn't help. It works on your side?

**Comment by utrack** [comment]
Tried to remove folder "tmp" in the storage directory, assets were recompiled according to logs, cleared cache in FF after that - still doesn't work...

**Comment by Z3roCoder** [comment]
I second that. Does not work for me either. Set up a reverse Proxy, configured it correctly (other projects work as well so it is not my error)

**Comment by Z3roCoder** [comment]
@sameersbn It would be awesome if you could look into that

**Comment by sameersbn** [comment]
@utrack @Z3roCoder I don't see this issue. Here is what i used

```bash
docker run -it --rm --name=pg1 \
--env='DB_NAME=gitlab' --env='DB_USER=gitlab' --env='DB_PASS=mypass' \
-v /tmp/docks/pg1:/var/lib/postgresql \
sameersbn/postgresql:latest

docker run -it --rm --name redis-gitlab \
sameersbn/redis:latest

docker run --name='gitlab' -it --rm \
--link=pg1:postgresql --link=redis-gitlab:redisio \
--publish=10022:22 --publish=10080:80 --env='GITLAB_SSH_PORT=10022' \
--env='DB_NAME=gitlab' --env='DB_USER=gitlab' --env='DB_PASS=mypass' \
--env='GITLAB_HOST=git.example.com \
-v /tmp/docks/gitlab:/home/git/data \
sameersbn/gitlab:7.11.4
```

Then I added a repo with multiple branches and was able to access the using `git.example.com` and change branches etc. without problems.

**Comment by sameersbn** [comment]
@utrack @Z3roCoder FWIW, here is my nginx reverse proxy configuration

```nginx
upstream gitlab {
  server                    172.17.42.1:10080 fail_timeout=0;
}

# let gitlab deal with the redirection
server {
  listen                    80;
  server_name               git.example.com;
  server_tokens             off;
  root                      /dev/null;

  # Increase this if you want to upload larger attachments
  client_max_body_size      20m;

  # individual nginx logs for this vhost
  access_log                /var/log/nginx/gitlab_access.log;
  error_log                 /var/log/nginx/gitlab_error.log;

  location / {
    proxy_read_timeout      300;
    proxy_connect_timeout   300;
    proxy_redirect          off;

    proxy_set_header        X-Forwarded-Proto $scheme;
    proxy_set_header        Host              $http_host;
    proxy_set_header        X-Real-IP         $remote_addr;
    proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header        X-Frame-Options   SAMEORIGIN;

    proxy_pass              http://gitlab;
  }
}

server {
  listen                    443   ssl spdy;
  server_name               git.example.com;
  server_tokens             off;
  root                      /dev/null;

  ## Increase this if you want to upload larger attachments
  client_max_body_size      20m;

  ## SSL
  ssl                       on;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
  ssl_prefer_server_ciphers on;

  ssl_ciphers 'ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4';

  ssl_session_cache builtin:1000  shared:SSL:10m;

  ssl_certificate /etc/nginx/ssl/server.crt;
  ssl_certificate_key /etc/nginx/ssl/server.key;
  ssl_dhparam /etc/nginx/ssl/dhparam.pem;

  ## Individual nginx logs for this vhost
  access_log                /var/log/nginx/gitlab_ssl_access.log;
  error_log                 /var/log/nginx/gitlab_ssl_error.log;

  location / {
    ## If you use https make sure you disable gzip compression
    ## to be safe against BREACH attack.
    gzip                    off;

    proxy_read_timeout      300;
    proxy_connect_timeout   300;
    proxy_redirect          off;

    proxy_set_header        Host                $http_host;
    proxy_set_header        X-Real-IP           $remote_addr;
    proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto   https;
    proxy_set_header        X-Frame-Options     SAMEORIGIN;

    proxy_pass http://gitlab;
  }
}
```

**Comment by Z3roCoder** [comment]
The only thing that changes for me when using GITLAB_HOST is the access to the SSL/HTTP-Repository. I can write "dasdasda" into GITLAB_HOST and still acces it via "localhost:10080", and when I make a reverse proxy, saying it should lead to "http://myIP.com/gitlab" and I access that site, I get instantly led to "http://myIP.com/users/sign_in"

**Comment by Z3roCoder** [comment]
@sameersbn - A reverse Proxy usually leads to www.myWebsite.com/gitlab and not gitlab.mywebsite.com

is there any way to do this correctly?

**Comment by utrack** [comment]
@sameersbn Sorry for no updates from me, I'll check your nginx settings out this weekend. The docker launch string looks close to mine.

Maybe it's relevant - I dunno. I did not put GITLAB_HOST envvar on first launch (when the database was migrated) - but I didn't find anything relevant to hosts in the DB anyway.

**Comment by Z3roCoder** [comment]
I have set GITLAB_PORT to 80, yet it is always shown as 10080 inside of my projects when going to the option to download it, aka

http://[url]:10080/gitlab/root/gh.git

should be 

http://[url]:80/gitlab/root/gh.git
Do I have to do more than just change GITLAB_PORT?

**Comment by sameersbn** [comment]
@Z3roCoder `GITLAB_PORT` specifies the port on which the application will be available to the outside world. For example, if your container is using `-p 10080:80` and you are using a load balancer to proxy requests on port `80` to the container on port `10080`, then `GITLAB_PORT` should be `80`. In case you have enabled `https` at the load balancer then set it to `443`.

The container by default sets `GITLAB_PORT=80`, if `GITLAB_SSL=true` is specified then it is set to `443`. If you want to override the port then you can specify it.

The `GITLAB_PORT` configuration is the only config that effects the port displayed in the urls. If this is the case even when it is set to `80` basically means that there is something wrong in your environment. Please check it and/or purge your browser cache and recheck.

In case you have enable the nginx_pagespeed module on the load balancer then turn it off during the tests.

**Comment by utrack** [comment]
Tested your nginx settings, after adding
```
    proxy_set_header        Host                $http_host;
    proxy_set_header        X-Real-IP           $remote_addr;
    proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto   https;
    proxy_set_header        X-Frame-Options     SAMEORIGIN;
```
and changing
    proxy_pass http://gitlab/;
to
    proxy_pass http://gitlab;
it works as intended. Guess the issue can be closed, but it's a thing to add to README :+1:
