### ISSUE TITLE
No way to make mail work

### ISSUE THREAD

**Issue by ohugues** [sameersbn/docker-gitlab#346]
Hi,

Everything is working fine except mail. Do I need to make something in gmail ?

Host: centos
release version: latest
docker version: 1.6.0
docker info:
---------------
Containers: 5
Images: 174
Storage Driver: devicemapper
 Pool Name: docker-8:2-5505490-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: 
 Metadata file: 
 Data Space Used: 4.214 GB
 Data Space Total: 107.4 GB
 Data Space Available: 103.2 GB
 Metadata Space Used: 7.905 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Udev Sync Supported: true
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.4.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 1.766 GiB

docker run command (yml):
----------------------------

  environment:
    - SMTP_ENABLED=true
    - SMTP_USER=my_gmail_user@gmail.com
    - SMTP_PASS=my_gmail_password
    - SMTP_AUTHENTICATION=login
    - GITLAB_EMAIL=my_gmail_user@gmail.com
    - GITLAB_EMAIL_REPLY_TO=my_gmail_user@gmail.com
    - GITLAB_EMAIL_ENABLED=true

**Comment by sameersbn** [comment]
@ohugues in the google mail setting you need to enable pop access.

**Comment by ohugues** [comment]
Hum, thanks for your answer. POP is activated since 16/07/2008 ;-) 

Perhaps it's caused by the need of SSL/TLS (https://support.google.com/a/answer/176600?hl=en) :

Port 465 (SSL required).
Port 587 (TLS required).

Do I need to enable SSL to make mail works ?

**Comment by sameersbn** [comment]
@ohugues I use google apps and this is what I have in my env to get mails working.

```bash
SMTP_ENABLED=true
SMTP_DOMAIN=mail.example.com
SMTP_USER=noreply@example.com
SMTP_PASS=mysecretpassword
```

**Comment by sameersbn** [comment]
@ohugues Check if the gitlab container is able to resolve dns addresses. This was the issue for some users. You can try to ping a address using the command `docker exec -it gitlab ping -c 4 mail.google.com`. If this does not work then it is a DNS issue.

You can also check the gitlab logs.

**Comment by ohugues** [comment]
Well, no problem to ping mail.google.com using docker exec. Can you help me to localize the gitlab logs ?

**Comment by ohugues** [comment]
I've found them. Here is a little part of the production.log.

Trying to add new user:
-------------------------------

Started GET "/" for 88.185.132.13 at 2015-06-14 17:19:02 +0200
Processing by DashboardController#show as HTML
Completed 200 OK in 166ms (Views: 81.3ms | ActiveRecord: 18.8ms)
Started GET "/?limit=20&offset=0" for 88.185.132.13 at 2015-06-14 17:19:02 +0200
Processing by DashboardController#show as JSON
  Parameters: {"limit"=>"20", "offset"=>"0"}
Completed 200 OK in 93ms (Views: 0.7ms | ActiveRecord: 14.6ms)
Started GET "/admin" for 88.185.132.13 at 2015-06-14 17:19:04 +0200
Processing by Admin::DashboardController#index as HTML
Completed 200 OK in 209ms (Views: 124.4ms | ActiveRecord: 27.6ms)

Sent mail to newuser_valid_email_adress@domain.fr (60039.3ms)

Changing email in the gitlab profile
-------------------------------------------

The email is admin@example.com even if I set something different using the environment variable)

Started PUT "/profile" for XX.XX.XX.XX at 2015-06-14 21:47:32 +0200
Processing by ProfilesController#update as HTML
  Parameters: {"utf8"=>"?~\~S", "authenticity_token"=>"[FILTERED]", "user"=>{"name"=>"Administrator", "email"=>"my_user_id@gmail.com", "public_email"=>"", "skype"=>"", "linkedin"=>"", "twitter"=>"", "websit
e_url"=>"", "location"=>"", "bio"=>""}}
Redirected to http://sub.domain.fr/profile
Completed 302 Found in 890ms (ActiveRecord: 25.8ms)
Started GET "/profile" for XX.XX.XX.XX at 2015-06-14 21:47:33 +0200
Processing by ProfilesController#show as HTML
Completed 200 OK in 266ms (Views: 201.9ms | ActiveRecord: 20.3ms)

Sent mail to my_user_id@gmail.com (545.1ms)
Started GET "/profile/account" for XX.XX.XX.XX at 2015-06-14 21:47:39 +0200
Processing by Profiles::AccountsController#show as HTML
Completed 200 OK in 250ms (Views: 181.6ms | ActiveRecord: 16.5ms)
Started GET "/profile" for XX.XX.XX.XX at 2015-06-14 21:47:41 +0200
Processing by ProfilesController#show as HTML
Completed 200 OK in 276ms (Views: 200.1ms | ActiveRecord: 23.8ms)

Sent mail to my_user_id@gmail.com (508.7ms)

Sent mail to my_user_id@gmail.com (696.5ms)

**Comment by sameersbn** [comment]
The default email address of the admin user is `admin@example.com`, you 
need to update it in the user profile settings.

**Comment by ohugues** [comment]
Yes, I did it. But I don't receive any email at all so there is no way to confirm a new user signing.

**Comment by sameersbn** [comment]
@ohugues I don't think gitlab sends an email when a new user signs in/registers. Mails are sent when SSH key is added/removed from your profile, or issue and pull request updates, etc. Please try adding/removing a SSH key and check if you are able to receive mails. Also keep an eye on the logs.

**Comment by ohugues** [comment]
Gitlab sends an email when a new user sign in to validate the fresh new account : 

     A message with a confirmation link has been sent to your email address. Please open the link to activate your account.

![message](https://cloud.githubusercontent.com/assets/4832281/8192503/eda9fe3c-146e-11e5-9c00-50e031394bb3.png)

Because the new user doesn't receive any email at all, he can't confirm the account so he can't login.

![confirmed](https://cloud.githubusercontent.com/assets/4832281/8192509/f8ac79ea-146e-11e5-821f-f91dfe8884fb.png) (obtained from the admin page)

Did you see anything strange in the logs ? I mean, there are many "Sent mail to my_user_id@gmail.com" but no emails have been received.

**Comment by ohugues** [comment]
Hi,

Here is another error observed in the sidekiq.log:

WARN: {"retry"=>true, "queue"=>"mailer", "class"=>"Devise::Async::Backend::Sidekiq", "args"=>["confirmation_instructions", "User", "48",
"S3jhb4eftD4dqPjG_Nyf", {}], "jid"=>"f2edc0e0a821eb27a40d25b5", "enqueued_at"=>1434549275.3202198, "error_message"=>"534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp
=1&scc=1&plt=AKgnsbsWE\n", "error_class"=>"Net::SMTPAuthenticationError", "failed_at"=>1434549276.0376217, "retry_count"=>1, "retried_at"=>1434549319.7833877}
2015-06-17T13:55:19.790Z 285 TID-we4ak WARN: 534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbsWE

Any idea ?

**Comment by ohugues** [comment]
Hum,

Do not forget to enable connections from new app in your google account settings...

[http://stackoverflow.com/questions/18124878/netsmtpauthenticationerror-when-sending-email-from-rails-app-on-staging-envir]

**Comment by sameersbn** [comment]
@ohugues so was your issue resolved?

**Comment by ohugues** [comment]
Yes, it is. Could you please add one line in the readme to help upcoming user ?

**Comment by ltchronus** [comment]
@sameersbn I also have the same problem.

yml:
```
gitlab:
  restart: always
  image: sameersbn/gitlab:8.0.4
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
    - "465:465"
    - "587:587"
  environment:
    - DEBUG=false
    - TZ=Asia/Kolkata
    - GITLAB_TIMEZONE=Kolkata
    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=XXX@XXX.com
    - GITLAB_EMAIL_REPLY_TO=XXX@XXX.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=XXX@XXX.com

    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=true
    - SMTP_DOMAIN=smtp.exmail.qq.com
    - SMTP_HOST=smtp.exmail.qq.com
    - SMTP_PORT=465
    - SMTP_USER=XXX@XXX.com
    - SMTP_PASS=XXX
    - SMTP_STARTTLS=false
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
```
docker info 
```
Containers: 3
Images: 100
Storage Driver: devicemapper
 Pool Name: docker-202:17-524291-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.323 GB
 Data Space Total: 107.4 GB
 Data Space Available: 27.66 GB
 Metadata Space Used: 5.145 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /mnt/docker/devicemapper/devicemapper/data
 Metadata loop file: /mnt/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.95-RHEL6 (2015-09-08)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 2.6.32-573.7.1.el6.x86_64
Operating System: <unknown>
CPUs: 4
Total Memory: 3.739 GiB
Name: Nodejs_Pre
ID: 37E4:36JM:66JD:YFJU:4OW6:AOHI:7OTE:NIN3:W2AI:GTK5:PO6U:HAP5
```
I try gmail turns out the same result.

**Comment by ltchronus** [comment]
```
Redirected to http://gitlab.airtake.me/admin/users/43243
Completed 302 Found in 692ms (ActiveRecord: 21.6ms)
Started GET "/admin/users/43243" for 112.16.79.214 at 2015-12-04 14:45:06 +0530
Processing by Admin::UsersController#show as HTML
Parameters: {"id"=>"43243"}
Completed 200 OK in 93ms (Views: 56.1ms | ActiveRecord: 9.9ms)
Sent mail to xxxx@xxxx.com (60127.1ms)
Started GET "/admin/application_settings" for 112.16.79.214 at 2015-12-04 14:47:42 +0530
Processing by Admin::ApplicationSettingsController#show as HTML
Completed 200 OK in 113ms (Views: 84.1ms | ActiveRecord: 5.5ms)
Started GET "/admin/logs" for 112.16.79.214 at 2015-12-04 14:47:44 +0530
Processing by Admin::LogsController#show as HTML
```
The logs seems that it has snet mail.

**Comment by ltchronus** [comment]
Solved with change SMTP_PORT to 25, SMTP_DOMAIN to smtp.qq.com
