### ISSUE TITLE
question: horizontal scaling

### ISSUE THREAD

**Issue by stefanfoulis** [sameersbn/docker-gitlab#348]
Assuming that I have external MySQL and Redis, as well as a shared filesystem (NFS): Is this docker image scalable (run multiple instances on multiple hosts behind a http loadbalancer for the web interface and a tcp loadbalancer for SSH).

Is there anything special I need to take core of about background workers?

**Comment by sameersbn** [comment]
@stefanfoulis i have not tried. But I don't see any issue running multiple instances of the image behind a load balancer as long as the updating of the git repositories is somehow serialized (via SSH or HTTP).

**Comment by Jack12816** [comment]
https://about.gitlab.com/2015/01/03/the-hardware-that-powers-100k-git-repos/

https://about.gitlab.com/features/:
> Scalable: support 25,000 users on one server or a highly available active/active cluster

It seems Gitlab is not designed to be horizontally scalable at the moment. They run only one active and one backup server for gitlab.com. The parallel access to the physical git repos could be a problem.

**Comment by sameersbn** [comment]
Closing issue as the anwser by @Jack12816 seems to clarify things.
