### ISSUE TITLE
Confusion in readme

### ISSUE THREAD

**Issue by blacksails** [sameersbn/docker-gitlab#350]
First of all im completely new to docker, so I might be wrong.

I got confused when i was setting up a redis container, following the instructions in the readme. In the section called "External Redis Server" you specify a redis volume why is that needed?

In the section "Linking to Redis Container", you don't specify a redis volume for the redis container. Doesn't that mean that redis will get wiped on a container restart?

Anyways I really love the thorough documentation that you supply! GJ :smiley:

**Comment by blacksails** [comment]
I made the following pull request showing what i mean: #351

**Comment by sameersbn** [comment]
@blacksails thanks for correcting the error.

> Doesn't that mean that redis will get wiped on a container restart?

This is true, however the loss of data in the redis store will not cause any functional issues with gitlab.
