### ISSUE TITLE
Please support http/https proxies for docker build process.

### ISSUE THREAD

**Issue by STOIE** [sameersbn/docker-gitlab#354]
Hi there,

I have been using your release for quite some time, however, I constantly need to hack at it with every release in order to build in my environment (behind a proxy server).

Can you please add the following into your build process:
* Anywhere you run `sudo` please run it as `sudo -E` - So we can keep HTTP_PROXY env vars etc.

I note you have just fixed the way you run gpg, now running the `hkp://` and `:80` - this now actually works for me with a proxy. (because of settings I have in my base image)

* Add the following to the top of the install script (now install.sh)
```
export HTTP_PROXY
export HTTPS_PROXY
export http_proxy
export https_proxy
```

I'm currently working on a scrubbed version of my base, which has all the proxy bits within... I'm hoping to get this up so others can use it in their environments. (and will work with all my upcoming docker releases).

Once, I have this up, you can see exactly how these generic mods to your repo will make the build process work correctly in both a NoProxy and Proxy environment.

Thanks,
Aaron

**Comment by STOIE** [comment]
Note. except for this line... sudo -E seemingly breaks here:

```
# install gitlab-shell
sudo -u ${GITLAB_USER} -H bundle exec rake 
```

**Comment by sameersbn** [comment]
> Add the following to the top of the install script (now install.sh)

I dont think it makes sense to add these to the `install.sh` script since you will have to edit the script either ways. I suggest you specify these as environment variable in the docker file. Add the following to the dockefile before any `RUN` instructions.

```dockerfile
ENV http_proxy=http://my.proxy.com:3128 \
        https_proxy=http://my.proxy.com:3128 \
        ftp_proxy=http://my.proxy.com:3128
RUN echo 'Acquire::http::Proxy "http://my.proxy.com:3142";' >> /etc/apt/apt.conf.d/01proxy
```

If you are using a base image, you can add the above to the base image instead.

> sudo -u ${GITLAB_USER} -H bundle exec rake

Are you sure about `-E` causing issues here? If yes, what issue do you see and how will gitlab-shell install work without the proxy settings?

**Comment by STOIE** [comment]
Hey man,

I'm glad you asked, easier to explain.

So, I already have both the apt-proxy and ENV http_proxy etc. settings set in my base image.
The reason I opted to have the exports in the install script is due to a few things.

I you just run export, it won't complain about null vars (when there is no proxy) and if there is one, it will make the environment usable for `sudo -E` - now, I will actually do some testing and get back to you in regards to having `ENV http_proxy ___` in my base, I actually do have that now, but, haven't tested since adding it I believe (was needed for something else.

The sudo -E doesn't seem to work on the bundle exec rake, as per the following issue in the log:

```
Installing unicorn-worker-killer 0.4.2
Installing version_sorter 2.0.0 with native extensions
Installing wikicloth 0.8.1
Bundle complete! 139 Gemfile dependencies, 211 gems now installed.
Gems in the groups development, test and aws were not installed.
Bundled gems are installed into ./vendor/bundle.
Post-install message from acts-as-taggable-on:
When upgrading

Re-run the migrations generator

    rake acts_as_taggable_on_engine:install:migrations

This will create any new migrations and skip existing ones
Version 3.5.0 has a migration for mysql adapter
Post-install message from haml:

HEADS UP! Haml 4.0 has many improvements, but also has changes that may break
your application:

* Support for Ruby 1.8.6 dropped
* Support for Rails 2 dropped
* Sass filter now always outputs <style> tags
* Data attributes are now hyphenated, not underscored
* html2haml utility moved to the html2haml gem
* Textile and Maruku filters moved to the haml-contrib gem

For more info see:

http://rubydoc.info/github/haml/haml/file/CHANGELOG.md

Post-install message from httparty:
When you HTTParty, you must party hard!
Post-install message from html-pipeline:
-------------------------------------------------
Thank you for installing html-pipeline!
You must bundle Filter gem dependencies.
See html-pipeline README.md for more details.
https://github.com/jch/html-pipeline#dependencies
-------------------------------------------------
Post-install message from mousetrap-rails:

[33mRemember to run generator to generate sample file and include mousetrap-rails with Rails Asset Pipeline[0m

    [32m$ rails generate mousetrap:install [0m

Post-install message from rdoc:
Depending on your version of ruby, you may need to install ruby rdoc/ri data:

<= 1.8.6 : unsupported
 = 1.8.7 : gem install rdoc-data; rdoc-data --install
 = 1.9.1 : gem install rdoc-data; rdoc-data --install
>= 1.9.2 : nothing to do! Yay!
[91mrake aborted!
[0m[91mURI::InvalidURIError: bad URI(is not URI?): XXX.XXX.XXX.XXX:3128
[0m[91m/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/omniauth-twitter-1.0.1/lib/omniauth/strategies/twitter.rb:11:in `<class:Twitter>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/omniauth-twitter-1.0.1/lib/omniauth/strategies/twitter.rb:6:in `<module:Strategies>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/omniauth-twitter-1.0.1/lib/omniauth/strategies/twitter.rb:5:in `<module:OmniAuth>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/omniauth-twitter-1.0.1/lib/omniauth/strategies/twitter.rb:4:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/omniauth-twitter-1.0.1/lib/omniauth-twitter.rb:2:in `<top (required)>'
/var/lib/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:76:in `require'
/var/lib/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/var/lib/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:72:in `each'
/var/lib/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:72:in `block in require'
/var/lib/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:61:in `each'
/var/lib/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:61:in `require'
/var/lib/gems/2.1.0/gems/bundler-1.10.4/lib/bundler.rb:134:in `require'
/home/git/gitlab/config/application.rb:6:in `<top (required)>'
/home/git/gitlab/Rakefile:5:in `require'
/home/git/gitlab/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
[0mThe command '/bin/sh -c bash ${SETUP_DIR}/install.sh' returned a non-zero code: 1
```

Seemingly the rake then wants to go via the proxy for local work?!?

Note. where XXX.XXX.XXX.XXX:3128 is my http proxy.

Anyway, glad someone is listening :)

**Comment by sameersbn** [comment]
@STOIE I am using local containers for `squid` and `apt-cacher-ng` and have no issue with the `rake` command you mentioned above.

```bash
# squid
docker run --name='squid' --publish=172.17.42.1:3128:3128 \
  sameersbn/squid:latest

# apt-cacher-ng
docker run --name='apt-cacher-ng' --publish=172.17.42.1:3142:3142 \
  sameersbn/apt-cacher-ng:latest
```

In the base image I have the following `ENV` configuration

```dockerfile
ENV http_proxy=http://172.17.42.1:3128/ \
    https_proxy=http://172.17.42.1:3128/ \
    ftp_proxy=http://172.17.42.1:3128/
RUN echo 'Acquire::http::Proxy "http://172.17.42.1:3142";' >> /etc/apt/apt.conf.d/01proxy
```

I see no issues whatsoever while building the image.

**Comment by STOIE** [comment]
Interesting, I will keep looking and report back.

**Comment by STOIE** [comment]
I can now close this.. thanks for all the help.

With the changes made using sudo -E etc. and having my base all setup now I can close as now it all works!!!

For reference, my build can be found here:

https://github.com/envris/docker-gitlab-govt

**Comment by sameersbn** [comment]
@STOIE great! thanks for closing the issue :wink:
