### ISSUE TITLE
can't connect to ssh 

### ISSUE THREAD

**Issue by shaunc** [sameersbn/docker-gitlab#363]
On a mac w/ yosemite, I am using latest master w/ docker-compose and following docker-compose.yml (below).

I have successfully started via docker-compose using this configuration, created a user, imported ssh key for user, and created a repo. I have configured git to push to this repo:

    git remote show -n gitlab
    * remote gitlab
      Fetch URL: ssh://git@192.168.53.103:8018/shauncutts/xquery.git
      Push  URL: ssh://git@192.168.53.103:8018/shauncutts/xquery.git
      HEAD branch: (not queried)
      Remote branch: (status not queried)
        master
      Local ref configured for 'git push' (status not queried):
        (matching) pushes to (matching)

However, I get an ssh timeout when I try to push. I also get a timeout when I ssh to this address manually.

What should be my next steps to debug? Thanks!

    data:
      image: cogniteev/echo
      volumes:
        - /var/lib/postgresql
        - /var/lib/redis
        - /home/gitlab_ci/data
       
    postgresql:
      image: sameersbn/postgresql:9.4
      environment:
        - DB_USER=gitlab
        - DB_PASS=password
        - DB_NAME=gitlabhq_production
      volumes_from:
        - data
    gitlab:
      image: sameersbn/gitlab:7.12.0
      links:
        - redis:redisio
        - postgresql:postgresql
      ports:
        - "8017:80"
        - "8018:22"
      environment:
        - TZ=America/New_York
        - SMTP_ENABLED=false
        - SMTP_DOMAIN=www.example.com
        - SMTP_HOST=smtp.gmail.com
        - SMTP_PORT=587
        - SMTP_USER=mailer@example.com
        - SMTP_PASS=password
        - SMTP_STARTTLS=true
        - SMTP_AUTHENTICATION=login
        - GITLAB_TIMEZONE=EST
        - GITLAB_HOST=192.168.53.103
        - GITLAB_PORT=8017
        - GITLAB_SSH_PORT=8018
        - GITLAB_EMAIL=admin@example.com
        - GITLAB_EMAIL_REPLY_TO=noreply@example.com
        - GITLAB_BACKUPS=daily
        - GITLAB_BACKUP_TIME=03:00
      volumes_from:
        - data
    redis:
      image: sameersbn/redis:latest
      volumes_from:
        - data

**Comment by sameersbn** [comment]
@shaunc I believe you are cloning from your osx environment right. Can you check if the `8018` port has been opened on the docker host (the docker host VM) using `sudo  iptables -nL | grep 8018`. If the port is closed (no output), then you need to open the port first.

**Comment by renrenfree** [comment]
the same question.
the error:
[root@server ~]# ssh -v  git@localhost:100222
OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 56: Applying options for *
ssh: Could not resolve hostname localhost:100222: Name or service not known

**Comment by renrenfree** [comment]
<container-ip>:22 is ok but docker host vm :10022 is not work  .what is the error?

**Comment by sameersbn** [comment]
@renrenfree You probably need to open the 10022 port on the docker host vm.

**Comment by shaunc** [comment]
@sameersbn ... thanks ... hmm -- looks like there are no restrictions on the OUTPUT chain:

---

Boot2Docker version 1.7.0, build master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
Docker version 1.7.0, build 0baf609
docker@boot2docker:~$ sudo iptables -nL | grep 8018
docker@boot2docker:~$ sudo iptables -nL 
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  0.0.0.0/0            172.17.0.40          tcp dpt:22
ACCEPT     tcp  --  0.0.0.0/0            172.17.0.40          tcp dpt:80
ACCEPT     tcp  --  0.0.0.0/0            172.17.0.52          tcp dpt:80

**Comment by sameersbn** [comment]
please refer to https://github.com/docker/docker/issues/4007
you need to perform some port forwarding steps. I don't use boot2docker so I dont exactly know what commands you should/could execute.

On Monday 06 July 2015 07:58 PM, Shaun Cutts wrote:
> @sameersbn ... thanks ... hmm -- looks like there are no restrictions on the OUTPUT chain:
>
> ---
>
> Boot2Docker version 1.7.0, build master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
> Docker version 1.7.0, build 0baf609
> docker@boot2docker:~$ sudo iptables -nL | grep 8018
> docker@boot2docker:~$ sudo iptables -nL
> Chain INPUT (policy ACCEPT)
> target     prot opt source               destination
>
> Chain FORWARD (policy ACCEPT)
> target     prot opt source               destination
> DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
> ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
> ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
> ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
>
> Chain OUTPUT (policy ACCEPT)
> target     prot opt source               destination
>
> Chain DOCKER (1 references)
> target     prot opt source               destination
> ACCEPT     tcp  --  0.0.0.0/0            172.17.0.40          tcp dpt:22
> ACCEPT     tcp  --  0.0.0.0/0            172.17.0.40          tcp dpt:80
> ACCEPT     tcp  --  0.0.0.0/0            172.17.0.52          tcp dpt:80
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sameersbn/docker-gitlab/issues/363#issuecomment-118872733
>

-- 
--
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com

**Comment by renrenfree** [comment]
I opened 10022 . I used localhost  but it's not work

**Comment by renrenfree** [comment]
I closed firewalld bug it's not work

**Comment by sameersbn** [comment]
can somebody with a similar setup and had to deal with this issue please help out here.

**Comment by renrenfree** [comment]
thank you @sameersbn .
 it's ok. i don't know how it's ok. but Just can

**Comment by sameersbn** [comment]
@shaunc @renrenfree if this is resolved for you, please close the issue.

**Comment by ruuds** [comment]
I had a similar issue today after upgrading from 7.11.4-1 to 7.13.2. GITLAB_SSH_PORT=10022 seems to be ignored after the update; SSH did still run on port 22.

**Comment by sameersbn** [comment]
@ruuds the internal ssh server always runs on port `22`. the `GITLAB_SSH_PORT` is only used to display the correct port number in the clone urls. So in the docker run if you have `-p 10022:22 GITLAB_SSH_PORT=10022`, the clone urls will look something like `ssh://git@git.example.com:10022/namespace/repo.git`.

**Comment by sp4ke** [comment]
@sameersbn @ruuds I upgraded from 7.10.0 to 7.13.2 and ssh is not working any more with port 10022. I explicitly open 10022 on the host firewall to make sure it was not the source problem. 

What can I do to fix this ?

**Comment by ruuds** [comment]
@sp4ke That was exactly our problem. We had GITLAB_SSH_PORT=10022 configured, but mapped the container's port 10022 to port 22 on the docker host. This stopped to work after the upgrade. Removing the GITLAB_SSH_PORT solved our problem because we would run it on port 22 anyways.

**Comment by sameersbn** [comment]
@sp4ke the line https://github.com/sameersbn/docker-gitlab/blob/master/entrypoint.sh#L285 was added recently that updates the ownership of the ssh directly. However I cannot understand how it managed to bungle the permissions set on the key files. I have added additional line to make sure the key files have the right permissions.

Thanks for investigating this issue.

**Comment by sp4ke** [comment]
@sameersbn thanks you're welcome

**Comment by sameersbn** [comment]
closing this issue.. please reopen if you still face problems. thanks.
