### ISSUE TITLE
2 factor authentication does not work after upgrade

### ISSUE THREAD

**Issue by outcoldman** [sameersbn/docker-gitlab#365]
It seems like that GitLab stores `.secret` key under rails root folder (`/home/git/gitlab/.secret`, see https://gitlab.com/gitlab-org/gitlab-ce/blob/master/app/models/user.rb#L82), which is required for generation 2 factor authentication codes. 
On every upgrade or image recreation current docker container regenerate this file, which means that all users who enabled 2 factor auth before will not be able to sign in. 
Temporary fix is to clean 2 factor auth for all users (see http://stackoverflow.com/a/31114188) and ask them re-enable it in their profiles.

**Comment by sameersbn** [comment]
@outcoldman You are right. I will symlink this file in the data volume

**Comment by sameersbn** [comment]
@outcoldman I have added the symlink. regarding the cleanup as linked in your above comment. Users will need to do this manually.
