### ISSUE TITLE
groupmod error with USERMAP

### ISSUE THREAD

**Issue by RoboMod** [sameersbn/docker-gitlab#366]
Hi,

I want to user the gitlab image started via docker compose. My problem is that I get the following error when I use the USERMAP_UID/GID environment variables:
gitlab_1     | Adapting uid and gid for git:git to $(id -u git):$(id -g git)
gitlab_1     | groupmod: invalid group ID '$(id'
Does anyone unterstand this error?

Regards
RoboMod

**Comment by sameersbn** [comment]
@RoboMod can you paste a sample of the docker command. I don't see this issue. I ran docker run with the following environment variables `-e USERMAP_UID=500 -e USERMAP_GID=500`

**Comment by RoboMod** [comment]
I don't use a docker command. As mentioned I work with compose. The .yml file looks like this:

gitlab:
  image: sameersbn/gitlab:7.12.1
  ...
  environment:
   - ...
   - USERMAP_UID=$(id -u git)
   - USERMAP_GID=$(id -g git)
...

It works with the uid and gid numbers like in your parameters. But I think the idea is that you don't have to type in the numbers but use the id command instead.

**Comment by sameersbn** [comment]
@RoboMod you cannot use `$(id -u git)` in the docker-compose file. You need to run `id -u git` and `$(id -g git)` on your host and use the printed values. p.s. in this case the `git` user needs to exist on the host

**Comment by RoboMod** [comment]
Okay, thanks for the clarification. You should mention both in the documentation.

**Comment by sameersbn** [comment]
@RoboMod This is a bash thing. You cannot expect such things to be documented in the readme here :smile:

**Comment by RoboMod** [comment]
Ahm, sorry, but the documentation doesn't make clear that you cannot use the id command in a compose file. So, please, that should be added!
