### ISSUE TITLE
After migrating from Omnibus to docker-gitlab: "Errno::ENOENT: No such file or directory @ realpath_rec - /opt/gitlab"

### ISSUE THREAD

**Issue by gopeter** [sameersbn/docker-gitlab#367]
I just moved my GitLab (7.12.2) installation, (previous installed on a virtualized Ubuntu), to my Synology which runs docker. Everything works fine, but hooks doesn't work (commits doesn't appear in activity stream, merge events doesn't fire, ...). Now I've checked GitLab with `sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production` and get the following message:

````
GitLab Shell version >= 2.6.3 ? ... OK (2.6.3)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ... 
Acceptance / ipad-vertriebsprasesentation ... rake aborted!
Errno::ENOENT: No such file or directory @ realpath_rec - /opt/gitlab
/home/git/gitlab/lib/tasks/gitlab/check.rake:488:in `realpath'
/home/git/gitlab/lib/tasks/gitlab/check.rake:488:in `block in check_repos_hooks_directory_is_link'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/relation/batches.rb:52:in `block (2 levels) in find_each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/relation/batches.rb:52:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/relation/batches.rb:52:in `block in find_each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/relation/batches.rb:126:in `find_in_batches'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/relation/batches.rb:51:in `find_each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/querying.rb:9:in `find_each'
/home/git/gitlab/lib/tasks/gitlab/check.rake:482:in `check_repos_hooks_directory_is_link'
/home/git/gitlab/lib/tasks/gitlab/check.rake:343:in `block (3 levels) in <top (required)>'
Tasks: TOP => gitlab:check => gitlab:gitlab_shell:check
(See full trace by running task with --trace)
````

Any ideas how to fix this? :)

**Update**

Just to let you know: I've created an backup with `sudo gitlab-rake gitlab:backup:create` on my Omnibus installation and restored it with `bundle exec rake gitlab:backup:restore RAILS_ENV=production` in my docker-gitlab installation.

**Update**

I just opened a config file of a repo and found out that the `remote "origin"` is wrong:

````
[core]
	repositoryformatversion = 0
	filemode = true
	bare = true
	autocrlf = input
[remote "origin"]
	url = /var/opt/gitlab/backups/repositories/acceptance/ipad-vertriebsprasesentation.bundle
````

Beside the fact that `/var/opt/gitlab` is wrong: should this really point to an backup directory?

**Comment by sameersbn** [comment]
@gopeter Regarding your last update. In my case, I see the path with `/home/git/data/backups/` prefix, eg. `/home/git/data/backups/repositories/docker/gitlab.bundle`, even though no such file exists. I think it is used when the rake task to generate a backup is started.

I guess you might have to change the path in the config files to replace `/var/opt/gitlab` with `/home/git/data`. You could also try to run the `gitlab:import:repos` raketask to see if that helps.

**Comment by gopeter** [comment]
Thanks!
I've adjusted the config file for `acceptance/ipad-vertriebsprasentation" but I'm getting the same error.

Now I've tried `gitlab:import:repos` but this doesn't work too. Now all repositories have an hook file which points to '/opt/gitlab/embedded/service/gitlab-shell/hooks' ...:
````
root@5581b4b6aef7:/home/git/data/repositories/acceptance/ipad-vertriebsprasesentation.git# ls -l
total 68
drwxrwxrwx 2 root users 4096 Jul  7 16:03 @eaDir
-rw-r--r-- 1 git  git     23 Jul 22  2014 HEAD
-rw-r--r-- 1 git  git    181 Jul  7 16:03 config
-rw-r--r-- 1 git  git     73 Jul 22  2014 description
lrwxrwxrwx 1 git  git     47 Sep 24  2014 hooks -> /opt/gitlab/embedded/service/gitlab-shell/hooks
drwxr-xr-x 2 git  git   4096 Jul 22  2014 hooks.old.1411560698
drwxr-xr-x 2 git  git   4096 Jul 22  2014 info
drwxr-xr-x 4 git  git   4096 Jul 22  2014 objects
-rw-r--r-- 1 git  git     98 Jul 22  2014 packed-refs
drwxr-xr-x 4 git  git   4096 Jul 22  2014 refs
````
I don't get what's wrong.

**Comment by sameersbn** [comment]
@gopeter apparently gitlab seems to hard code the file paths. You might have to manually update the symlinks to point to `/home/git/gitlab-shell/hooks`. 

(this whole ordeal is really such a shame :disappointed: )

**Comment by sameersbn** [comment]
@gopeter p.s. if you get everything working please do run the `app:sanitize` command on the docker image to make sure all files and directories have the right permissions. Also launch the rake task to create the satellite repositories using `app:rake gitlab:satellites:create` rake task.

**Comment by gopeter** [comment]
I just removed the `remote "origin"` (newly created repositories doesn't include this `remote` too) from the config file and added a new symlink to the correct hooks directory. 

Now it works... but I have to edit all files manually (> 50 repositories...). Time for :beer: 

Thank you very much for your help (and your `app:sanitize` and `app:rake gitlab:satellites:create` hints)! Maybe this issue is worth to mention in the readme (for all people who want to migrate from their Omnibus installations)?

**Comment by sameersbn** [comment]
@gopeter a bash script should help to get the job done quickly

**Comment by gopeter** [comment]
Already done :)

**Comment by sameersbn** [comment]
great! I hope you do not face any issues with the image :beer:

**Comment by gopeter** [comment]
Thanks! Didn't faced any issues, awesome image! Thank you so much for this :) Migrated GitLab in minutes. Docker ftw :beers:

**Comment by sameersbn** [comment]
@gopeter closing this issue since you got it resolved :+1:
