### ISSUE TITLE
Confirmation email is send with gitlab port

### ISSUE THREAD

**Issue by arielschiavoni** [sameersbn/docker-gitlab#368]
Hi,

I setup the image and it works great thanks for sharing ;-)

I just found a small issue, when I create a new user, an activation email is sent. The link into that email appends the gitlab port to the domain.

http://gitlab.mydomain.com:10080/users/confirmation?confirmation_token=xxxxxxxx

The problem is that I don't want to expose the port in this url because I have a nginx reverse proxy that redirects
gitlab.mydomain.com -> MY_SERVER_IP:10080

Is there any way to configure the gitlab container to use only the domain into email's url?

Thanks.
Ariel.

**Comment by outcoldman** [comment]
@arielschiavoni just specify `GITLAB_PORT` as `80` if you can access to the gitlab as `http://gitlab.mydomain.com/users/confirmation?confirmation_token=xxxxxxxx`
This setting does not change anything how gitlab is running, it is basically just to tell GitLab how to generate urls.

**Comment by arielschiavoni** [comment]
Thanks @outcoldman !, I thought that GITLAB_PORT was used to expose the gitlab's docker container port.

**Comment by sameersbn** [comment]
Yep.. the documentation could use a little clarity.

On Thursday 09 July 2015 11:57 AM, Ariel Schiavoni wrote:
> Thanks @outcoldman !, I thought that GITLAB_PORT was used to expose the gitlab's docker container port.
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sameersbn/docker-gitlab/issues/368#issuecomment-119838830
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com
