### ISSUE TITLE
How do I create a new user?

### ISSUE THREAD

**Issue by RobeDevOps** [sameersbn/docker-gitlab#373]
I want to login with a different user, gitlab says that a confirmation emails was sending and I need to do a confirmation if I want to login. But I dont receive any email.

**Comment by sameersbn** [comment]
@RobeDevOps you need to configure the SMTP settings for mail sending. You can create users from the admin panel as well

**Comment by RobeDevOps** [comment]
When I create the user from the Admin Area and I try to login with this user, the gitlab throw an error saying that a email confirmation is needed.

**Comment by RobeDevOps** [comment]
I just want to insert more user and create a different branchs and send some commits and show to my team how gitlab is working on my local machine.

**Comment by sameersbn** [comment]
@RobeDevOps Why dont you just enabled SMTP via google apps / mail.

**Comment by sameersbn** [comment]
@RobeDevOps disabling gitlab signup might disable the mail sending to activate the account `GITLAB_SIGNUP=false`. I am not sure about this. But worth a try.

**Comment by dobsiin** [comment]
it seems that there is really no option (searched the offical gitlab forum, github, etc) ended setting up the smtp settings, so gitlab can send those confirmation emails.

**Comment by sameersbn** [comment]
@dobsiin should we mark this issue as resolved?

**Comment by dobsiin** [comment]
https://forum.gitlab.com/t/no-confirmation-email-for-new-users/617

from tgdesrochers:
edit: /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/devise-3.2.4/lib/devise.rb
line: 123
change to: @@email_regexp = /\A[^@]+@[^@]+\z/

rerun: gitlab-cli reconfigure.

Now any new user you create will not be required to click on a verification email.

If there was an easier way to do this please tell me. I couldn't find one.

.... there is no easy way to accomplish this. Guess this is resolved.

**Comment by sameersbn** [comment]
From your investigation its pretty clear that right now it cannot be done.
This is a issue for Gitlab upstream.

I had read somewhere that disabling signups should allow you to workaround
this. I have not tried it, probably you already have.

Since this behaviour does not arise due to this image, I think we can close
it.

**Comment by sameersbn** [comment]
just realized that `GITLAB_SIGNUP` option is not available anymore. you should disable signups from the administration area
