### ISSUE TITLE
External Redis Password environment variable

### ISSUE THREAD

**Issue by kopax** [sameersbn/docker-gitlab#374]
I have just setup a REDIS external server.
I can't find any environment var for the password.
Did you add a REDIS_PASS environment var ?

**Comment by sameersbn** [comment]
At the momemt there is no option to specify the redis password
On Saturday 11 July 2015 12:52 AM, Dimitri KOPRIWA wrote:
> I have just setup a REDIS external server.
> You don't have an REDIS_PASS environment var ?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sameersbn/docker-gitlab/issues/374
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com

**Comment by sameersbn** [comment]
reopening.. this feature is coming soon! :smile:

**Comment by kopax** [comment]
Cool :) it mean I am installing everything for nothing.

Is it hard to update from docker-gitlab to another ?

**Comment by sameersbn** [comment]
@kopax Gitlab does not seem to work with password protected redis server. So this cannot be implemented for now. Closing the issue.

> Cool :) it mean I am installing everything for nothing.

I don't understand what you mean.

> Is it hard to update from docker-gitlab to another ?

What do you mean?

**Comment by kopax** [comment]
I meant that I prefere to have an external protected redis server, so I am ready to reinstall everything

I have no idea on how to update gitlab when using your image !

**Comment by sameersbn** [comment]
@kopax Please refer readme. Upgrading is probably the easiest task with this image

**Comment by lenovouser** [comment]
@sameersbn opened a issue for this at [gitlab:gitlab-org/gitlab-ce/issues#13305](https://gitlab.com/gitlab-org/gitlab-ce/issues/13305) because I need this too.

**Comment by r2evans** [comment]
It appears that another gitlab issue ([#729](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/729)) discussed this and it [was committed](https://gitlab.com/gitlab-org/omnibus-gitlab/commit/d847479b8bcb523110aae9230bcf480def3eab15) back in gitlab-8.0.2.

I too am interested in securing my redis installation. (Would it make better sense to share the redis unix socket as a volume and use that instead? I don't know if it would bring any performance improvements.)

(ping #619)
