### ISSUE TITLE
Using HTTPS over an nginx balancer

### ISSUE THREAD

**Issue by kopax** [sameersbn/docker-gitlab#376]
Hi, I am trying hard to get work docker-gitlab.

I have a Docker container which only has nginx, this container is open to the world on port 80 & 443.

I have signed certificate, I want to redirect to nginx gitlab from this nginx container (load balancer).

I have tried every possible config. I can't figure out why it still not work, here is my nginx file

    worker_processes auto;

    events { worker_connections 1024; }

    http {

    ##
    # Logging Settings
    ##

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    upstream gitlab {
        server gitlab:10080;
    }

    server {
        listen 80;
        listen 443 ssl;
        server_name www.domain.tld;

        ssl on;
        ssl_certificate         /usr/local/share/ca-certificates/domain.crt;
        ssl_certificate_key     /usr/local/share/ca-certificates/domain.key;
        ssl_trusted_certificate /usr/local/share/ca-certificates/GandiStandardSSLCA2.pem;

        ssl_session_timeout 5m;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES";
        ssl_prefer_server_ciphers on;

        root /usr/share/nginx/html;

        location /git/ {
            proxy_pass http://gitlab;
            proxy_set_header X-Forwarded-Ssl on;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

Without SSL, working url to acces gitlab is http://www.domain.tld:10080/git

With SSL, I want the url to be https://www.domain.tld/git

Using this nginx load balancer configuration

When I go on http://www.domain.tld/git

    400 Bad Request

The plain HTTP request was sent to HTTPS port
When i go on https://www.domain.tld/git

    ERR_CONNECTION_REFUSED

These are my first signed certificate, how is this supposed to work ?

Edit :

Btw, here is my docker-compose.yml, I tried almost all kind of settings

    gitlab:
    #  build: .
      image: sameersbn/gitlab:7.12.2-2
      links:
        - redis:redisio
      ports:
        - "10080:80"
    #    - "4430:443"
        - "22:22"
      environment:
        # my var
        - DB_TYPE=mysql
        - DB_HOST=sql-01.domain.com
        - DB_USER=gitlab
        - DB_PASS=2P9bDZn95B
        # default
        - TZ=Europe/Paris
        - SMTP_ENABLED=true
        - SMTP_DOMAIN=www.domain.com
        - SMTP_HOST=smtp.domain.com
        - SMTP_PORT=587
        - SMTP_USER=git@domain.com
        - SMTP_PASS=wyU64GPH4K
        - SMTP_STARTTLS=true
        - SMTP_AUTHENTICATION=login
        - GITLAB_RELATIVE_URL_ROOT=/git
        - GITLAB_TIMEZONE=Paris
    #    - GITLAB_HTTPS=true
        - GITLAB_HOST=www.domain.com
    #    - GITLAB_PORT=430
    #    - GITLAB_PORT=4430
        - GITLAB_PORT=10080
        - GITLAB_SSH_PORT=22
        - GITLAB_USERNAME_CHANGE=false
        - GITLAB_EMAIL=git@domain.com
        - GITLAB_EMAIL_REPLY_TO=no-reply@domain.com
        - GITLAB_BACKUPS=daily
        - GITLAB_BACKUP_TIME=01:00
    # certificate
    #    - SSL_CERTIFICATE_PATH=/usr/local/share/ca-certificates/domain.crt
    #    - SSL_KEY_PATH=/usr/local/share/ca-certificates/domain.key
    #    - SSL_DHPARAM_PATH=/usr/local/share/ca-certificates/dhparam.pem
    #    - CA_CERTIFICATES_PATH=/usr/local/share/ca-certificates/GandiStandardSSLCA2.pem
      volumes_from:
        - data_data_1
    redis:
      image: sameersbn/redis:latest
      volumes:
        - /srv/docker/gitlab/redis:/var/lib/redis

**Comment by sameersbn** [comment]
@kopax is your gitlab container linked to the nginx container? because I see the configuration

```nginx
upstream gitlab {
    server gitlab:10080;
}
```

This means that the nginx containers expects to talk to the gitlab container using the `gitlab` hostname. This is only possible if you have linked the gitlab container to the nginx container.

That being said. The way I do it is, on the gitlab container i publish the gitlab containers port `80` using `-p 172.17.42.1:10080:80`. Any connections to the docker bridge interface `172.17.42.1` on port `10080` will be routed to the `gitlab` containers port `80`. This way I don't have to bother about the `gitlab` containers ip address in the nginx configuration and also I don't have to link the gitlab container to the nginx container.

With that in place, I use the following nginx configuration on the load balancer,

```nginx
upstream gitlab {
  server 172.17.42.1:10080 fail_timeout=0;
}

# let gitlab deal with the redirection
server {
  listen 80;
  server_name git.example.com;
  server_tokens off;
  root /dev/null;

  # Increase this if you want to upload larger attachments
  client_max_body_size 20m;

  # individual nginx logs for this vhost
  access_log /var/log/nginx/gitlab_access.log;
  error_log /var/log/nginx/gitlab_error.log;

  location / {
    proxy_read_timeout 300;
    proxy_connect_timeout   300;
    proxy_redirect off;

    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Frame-Options   SAMEORIGIN;

    proxy_pass http://gitlab;
  }
}

server {
  listen 443 ssl spdy;
  server_name git.example.com;
  server_tokens off;
  root /dev/null;

  ## Increase this if you want to upload larger attachments
  client_max_body_size 20m;

  ## SSL
  ssl on;

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
  ssl_prefer_server_ciphers on;

  ssl_ciphers 'ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4';

  ssl_session_cache builtin:1000  shared:SSL:10m;

  ## Strong SSL Security
  ## https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html
  ssl_certificate /etc/nginx/ssl/server.crt;
  ssl_certificate_key /etc/nginx/ssl/server.key;

  ## [Optional] Generate a stronger DHE parameter (recommended):
  ##   cd /etc/ssl/certs
  ##   openssl dhparam -out dhparam.pem 2048
  ##
  ssl_dhparam /etc/nginx/ssl/dhparam.pem;

  ## Individual nginx logs for this vhost
  access_log /var/log/nginx/gitlab_ssl_access.log;
  error_log /var/log/nginx/gitlab_ssl_error.log;

  location / {
    ## If you use https make sure you disable gzip compression
    ## to be safe against BREACH attack.
    gzip off;

    proxy_read_timeout 300;
    proxy_connect_timeout 300;
    proxy_redirect off;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Frame-Options SAMEORIGIN;

    proxy_pass http://gitlab;
  }
}
```

I hope you find this useful.

**Comment by sameersbn** [comment]
@kopax Also please note that when you want to enable ssl support via a load balancer, you should not install the ssl certificates to the gitlab container. Only set `GITLAB_HTTPS=true`. Please refer to the SSL part of the readme regarding this.

**Comment by kopax** [comment]
@sameersbn  Thanks for your reply, I am since more than a day now trying to figure out how to setup properly the load balancer.

I have readen your doc 10 times now, and still have many details unclear. Could you check out my other ticket ?

**Comment by sameersbn** [comment]
@kopax There are 2 ways to setup SSL support

1. directly in the container
2. using a load balancer

Since you are using a load balancer i will try to describe how this works.

When using a load balancer, 
- the load balancer will talk to the gitlab container over plain http. 
- the SSL configuration has to done at the load balancer. 
- Since gitlab will be accessible to the outside world over https you should set `GITLAB_HTTPS=true`, this ensures that the urls, etc. have the `https` prefix.
- You should not install the SSL certificates in the gitlab container. Installing the SSL certificates in the gitlab container triggers native https support, which is not what you want. 
- You do not need to add `-p 4443:443` on the gitlab container, because it will only talk to the load balancer over `http` so this setting would be pointless.
- The `GITLAB_PORT` setting is only used to display the correct url, it has no other effect. So if your load balancer will be listening on port `443`, then set  `GITLAB_PORT=443`. Note: this is automatically set when `GITLAB_HTTPS=true`.

If this does not clear your doubts then please paste you docker command / docker-compose.yml file and the load balancer configuration. I will try and help you figure it out.

**Comment by kopax** [comment]
@sameersbn OK.

 * points 1,2,4 : I knew from the doc.
 * point 3 : OK

Everything is a little more clear.

So I think it might come from my Gandi SSL nginx configuration now. I have renewed the certificate so I can't test at the moment.

My configuration look like this

__nginx.conf__

    user www-data;
    worker_processes auto;
    pid /var/run/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;

      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log;

      ##
      # Virtual Host Configs
      ##

      include /etc/nginx/conf.d/*.conf;
      include /etc/nginx/sites-enabled/*;
    }

__/etc/nginx/sites-enabled/gitlab.conf__

	server {
	  # Sample from https://github.com/jlecour/ssl-gandi-nginx-debian
	  # listen 80;
	  # rewrite ^ https://$host$request_uri? permanent; <===== why is this line different BTW ?


	  listen 80;
	  server_name www.domain.tld;
	  server_tokens off;
	  root /dev/null;
	  rewrite ^ https://$server_name$request_uri permanent;
	}

	upstream git {
	  server gitlab:10080;
	}

	server {
	  listen 443 ssl spdy;
	  
	  server_name www.domain.tld;
	  server_tokens off;
	  root /dev/null;
	  
	  ## Increase this if you want to upload large attachments
	  ## Or if you want to accept large git objects over http
	  client_max_body_size 20m;

	  add_header Strict-Transport-Security max-age=63072000;
	  # add_header X-Frame-Options DENY;
	  add_header X-Content-Type-Options nosniff;

	  ## Individual nginx logs for this vhost
	  access_log  /var/log/nginx/gitlab_access.log;
	  error_log   /var/log/nginx/gitlab_error.log;

	  ## include domain ssl config
	  include /etc/nginx/domain_tld.ssl.conf;
	  
	  ## proxy pass the request to upsteam.
	  location / {
		## If you use https make sure you disable gzip compression
		## to be safe against BREACH attack.
		gzip off;

		## https://github.com/gitlabhq/gitlabhq/issues/694
		## Some requests take more than 30 seconds.
		proxy_read_timeout      300;
		proxy_connect_timeout   300;
		proxy_redirect          off;

		proxy_set_header    Host                $http_host;
		proxy_set_header    X-Real-IP           $remote_addr;
		proxy_set_header    X-Forwarded-Ssl     on;
		proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
		proxy_set_header    X-Forwarded-Proto   $scheme;
		proxy_set_header    X-Frame-Options     SAMEORIGIN;

		proxy_pass http://git;
	  }

	}

__/etc/nginx/domain_tld.ssl.conf__

	ssl on;

	# certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
	ssl_certificate /etc/ssl/certs/domain_tld.chain.pem;
	ssl_certificate_key /etc/ssl/private/domain_tld.key.pem;
	ssl_session_timeout 24h;
	ssl_session_cache shared:SSL:10m;

	# Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits or better
	ssl_dhparam /etc/ssl/dhparam.pem;

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
	ssl_prefer_server_ciphers on;

	## OCSP Stapling ---
	## fetch OCSP records from URL in ssl_certificate and cache them
	ssl_stapling on;
	ssl_stapling_verify on;

	## verify chain of trust of OCSP response using Root CA and Intermediate certs
	ssl_trusted_certificate /etc/ssl/certs/gandi-standardssl-2.chain.pem;

	resolver 127.0.0.1;

**Comment by sameersbn** [comment]
Please share you nginx and docker launch commands.

**Comment by kopax** [comment]
My nginx and docker launch commands ? Not sure I understand.

Here is my docker-compose for my nginx container :

	nginx:
	  build: ./nginx
	  ports:
	    - "443:433"
	    - "80:80"
	  volumes_from:
	    - data_data_1
	  external_links:
	    - gitlab_gitlab_1:gitlab

As GitLab, I launch it with `docker-compose up`

**Comment by sameersbn** [comment]
Please share you docker-compose.yml for launching gitlab as well. You can mask out the sensitive bits.

**Comment by kopax** [comment]
gitlab:
      image: sameersbn/gitlab:7.12.2-2
      links:
        - redis:redisio
      ports:
        - "10080:80"
        - "22:22"
      environment:
    # HTTP(S)
        - GITLAB_HTTPS=true
    #    - GITLAB_RELATIVE_URL_ROOT=/git
    # LOCALES
        - TZ=Europe/Paris
        - GITLAB_TIMEZONE=Paris
    # MYSQL
        - DB_TYPE=mysql
        - DB_HOST=sql.domain.com
        - DB_USER=gitlab
        - DB_PASS=123456
    # SMTP
        - SMTP_ENABLED=true
        - SMTP_DOMAIN=www.domain.com
        - SMTP_HOST=smtp.domain.com
        - SMTP_PORT=587
        - SMTP_USER=git@domain.com
        - SMTP_PASS=789456
        - SMTP_STARTTLS=true
        - SMTP_AUTHENTICATION=login
    # EMAIL
        - GITLAB_EMAIL=git@domain.com
        - GITLAB_EMAIL_REPLY_TO=no-reply@domain.com
    # GITLAB
        - GITLAB_HOST=localhost
        - GITLAB_PORT=443
        - GITLAB_SSH_PORT=22
    # BACKUP
        - GITLAB_BACKUPS=daily
        - GITLAB_BACKUP_TIME=01:00
      volumes_from:
        - data_data_1
    redis:
      image: sameersbn/redis:latest
      volumes:
        - /srv/docker/gitlab/redis:/var/lib/redis

**Comment by sameersbn** [comment]
@kopax since you are linking to the gitlab container from the nginx container and as a result the `gitlab` hostname in your nginx config,

``nginx
upstream git {
  server gitlab:10080;
}
```
Directly addresses the gitlab containers ip, you will have to use port `80` here, i.e.

```nginx
upstream git {
  server gitlab:80;
}
```

Can you please try this change. In the mean time I will continue my investigation

**Comment by kopax** [comment]
@sameersbn If it can help you, these are extra informations 

These are my firewall rules during configuration 

    2    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 (Use by nginx)
    3    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 (Use by nginx)
    4    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:22 (Use by gitlab for ssh)
    5    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:10022 (Use for ssh)
    6    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:10080 (Use by gitlab nginx http server)
    7    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:4443 (Not used anymore, was for gitlab https)

These are my docker running container 

    nginx_nginx:latest          "nginx -g 'daemon of   15 minutes ago      Up 15 minutes       443/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:443->433/tcp    nginx_nginx_1
    sameersbn/gitlab:7.12.2-2   "/sbin/entrypoint.sh   15 minutes ago      Up 15 minutes       0.0.0.0:22->22/tcp, 443/tcp, 0.0.0.0:10080->80/tcp   gitlab_gitlab_1
    sameersbn/redis:latest      "/start"               15 minutes ago      Up 15 minutes       6379/tcp                                             gitlab_redis_1

Using http://www.domain.com:10080 I can access GitLab sign in page (I can't click anywhere because links are using __https __ but it work)

I am trying using local container port 80 to see if it work

**Comment by sameersbn** [comment]
@kopax Well the issue is that in your nginx docker-compose.yml file you have the line `"443:433"`, i think you meant to write `"443:443"`

**Comment by sameersbn** [comment]
@kopax after doing the `gitlab:80` and `"443:443"` change I can see the load balancer working

**Comment by kopax** [comment]
Nice eyes of the tiger ! It worked

Do you know how I should configure nginx load balancer now to redirect to /git only ?

I need to do a second route on another container for /api

and leave the / to http protocole.

**Comment by sameersbn** [comment]
@kopax you need need to figure that out yourself. You should also find pointer in the past issues.

Couple of notes: 
- Since you are linking to the gitlab container from the nginx container, there is no need to publish `-p 10080:80`
- You seem to be using mysql. Gitlab Inc. recommends using postgresql. You will start seeing issues later on if you continue using mysql.

**Comment by kopax** [comment]
`You seem to be using mysql. Gitlab Inc. recommends using postgresql. You will start seeing issues later on if you continue using mysql.`

@sameersbn Ok, if Gitlab recommends using postgresql, doesn't mean you will have issues with mysql.

I am using MariaDB btw, I am using 3 differents GitLab, all using mariadb, never had any issues.

**Comment by sameersbn** [comment]
@kopax ok

**Comment by kopax** [comment]
About `10080:80`, If I remove it, I can't access gitlab using the load balancer (502 Bad Gateway)
If i keep `80` only, docker will assign an outbound port and configure the firewall to listen to 0.0.0.0:10080

Is there a way to prevent this behaviour ?

**Comment by kopax** [comment]
Oh, you just closed the issue :+1: 

Thanks a lot for your help, I really appreciate, you saved me a big headhache

**Comment by sameersbn** [comment]
@kopax BTW, gitlab seems to have small issues when running on a relative url. see https://github.com/sameersbn/docker-gitlab/issues/326

**Comment by kopax** [comment]
@sameersbn Thanks, I have the same issue
