### ISSUE TITLE
Question about load balancing

### ISSUE THREAD

**Issue by kopax** [sameersbn/docker-gitlab#377]
In your example you use two different publication port

    docker run --name=gitlab -d \
      --publish=10022:22 --publish=10080:80 \
      --env='GITLAB_SSH_PORT=10022' --env='GITLAB_PORT=443' \
      --env='GITLAB_HTTPS=true' --env='SSL_SELF_SIGNED=true' \
      --volume=/srv/docker/gitlab/gitlab:/home/git/data \
      sameersbn/gitlab:7.12.2-2

So is GITLAB_PORT the port used by gitlab meaning it's SSL ?
Does the load balancer has to point to 10080 or 4443 ?

In this example, --publish shouldn't be =10080:443 or GITLAB_PORT=10080?

On gitlab container side, I have activated 10080:80 && 443:43, is it supposed to be 10080:80 || 443:43 ?

How does the GITLAB_PORT work exactly ? 

Thanks

**Comment by sameersbn** [comment]
@kopax the command you quoted is from the section that enables https natively in the container. When using a load balancer, this is the section you should refer https://github.com/sameersbn/docker-gitlab#using-https-with-a-load-balancer.

When using a load balancer, no SSL certificates should be installed in the gitlab container. The container will only be listening on port 80. 

The `GITLAB_PORT` setting is only used to display the correct url. It has no effect on what ports the internet nginx server listens on.

**Comment by kopax** [comment]
@sameersbn the command quoted is from the section `using-https-with-a-load-balancer` but ok :+1:
