### ISSUE TITLE
SMTP does not work

### ISSUE THREAD

**Issue by kopax** [sameersbn/docker-gitlab#379]
I am trying to make work the smtp settings I tried.

For this, I have created an email account: git@domain.com

I have tried two config, first, using the account, the second, without auth method (i guess the domain is enough)

Here are my two configs :

__without auth__

	  ActionMailer::Base.smtp_settings = {
	    address: "smtp.domain.com",
	    port: 587,
	    domain: "www.domain.com",
	    openssl_verify_mode: "none",
	    enable_starttls_auto: true,
	    tls: false
	  }

__auth__ 

	  ActionMailer::Base.smtp_settings = {
	    address: "smtp.domain.com",
	    port: 587,
	    user_name: "git@domain.com",
	    password: "abcde456",
	    domain: "www.domain.com",
	    authentication: "login",
	    openssl_verify_mode: "none",
	    enable_starttls_auto: true,
	    tls: false
	  }

The auth config is correct, I can use it with thunderbird but I have to accept the self signed certificate of the mail server.

None of these two config work, when I go on sidekiq, all mail got refused with the following error :+1: 

    Connection refused - connect(2) for "smtp.domain.com" port 587

**Comment by sameersbn** [comment]
@kopax you will need to refer to your mail server docs to properly configure SMTP. 

One thing you can check first if the `smtp.domain.com` resolution happens from the gitlab container. ping your smtp server to see if name resolution is working. 

If the name resolution does not work, then there is a problem with you dns server configuration for the gitlab container. If you need to use an internet dns server, then use the `--dns` argument to specify your dns server address in your docker-compose file.

**Comment by kopax** [comment]
@sameersbn The smtp server was installed using iredmail.
Container can ping `smtp.domain.com`

I am accessing using this smtp server with this settings 

Souce : my thunderbird configuration !

**Comment by sameersbn** [comment]
@kopax  I cannot tell what your issue could. One thing you can try is to add the SSL server certificate in a `ca.crt` file in the `certs` directory in the data volume. Refer to https://github.com/sameersbn/docker-gitlab#installing-trusted-ssl-server-certificates. This will make sure that your server certificate is trusted since it is a self signed certificate.

**Comment by kopax** [comment]
The iredmail certificate was generated by iredmail and is different from the trusted certificate I use for gitlab.

However, I used to install gitlab and iredmail using self signed certificate, I never had a single issue to send mail before. 

I will dig a little bit more, otherwise I'll use gmail smtp :/

**Comment by sameersbn** [comment]
@kopax FYI, you can input multiple certificates you want to trust in the `ca.crt` file, just keep appending certificates in `ca.crt`
