### ISSUE TITLE
Best practice for making gitlab ssh port available externally

### ISSUE THREAD

**Issue by jwthomp** [sameersbn/docker-gitlab#38]
Hi,

I've gotten gitlab running inside of docker now and was able to backup from my old gitlab vm and restore it into the new docker container. I am now at the point where the docker gitlab instance is listening to port 22 on it's private IP.

I am looking for any information on the best way to expose that through the public host interface? 

Thank you!

Jeff

**Comment by uwydoc** [comment]
In my specific situation, where docker-gitlab is run inside the boot2docker-vm(host os is rhel 6.4, the kernel (2.6.32) is too old to run recent version of docker), the only workaround that I came up with is using `iptables` to forward git(ssh) connections. reference: http://stackoverflow.com/a/14637461/1994490
