### ISSUE TITLE
Gitlab 500 Error, assets:precompile fails

### ISSUE THREAD

**Issue by dobsiin** [sameersbn/docker-gitlab#380]
[root@d40542e9601c config]# rake assets:precompile RAILS_ENV=production
(in /home/git/gitlab)
D, [2015-07-13T06:44:45.939408 #417] DEBUG -- : Celluloid 0.17.0 is running in B
ACKPORTED mode. [ http://git.io/vJf3J ]
rake aborted!
Sprockets::FileNotFound: couldn't find file 'jquery.ui.all'
  (in /home/git/gitlab/app/assets/javascripts/application.js.coffee:8)
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/context.
rb:106:in `resolve'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/context.
rb:146:in `require_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/directiv
e_processor.rb:217:in `process_require_directive'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/directiv
e_processor.rb:167:in `block in process_directives'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/directiv
e_processor.rb:165:in `each'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/directiv
e_processor.rb:165:in `process_directives'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/directiv
e_processor.rb:99:in `evaluate'
/home/git/gitlab/vendor/bundle/ruby/gems/tilt-1.4.1/lib/tilt/template.rb:103:in
`render'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/context.
rb:197:in `block in evaluate'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/context.
rb:194:in `each'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/context.
rb:194:in `evaluate'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/processe
d_asset.rb:12:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/base.rb:
374:in `new'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/base.rb:
374:in `block in build_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/base.rb:
395:in `circular_call_protection'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/base.rb:
373:in `build_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/index.rb
:94:in `block in build_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/caching.
rb:58:in `cache_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/index.rb
:93:in `build_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/base.rb:
287:in `find_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/index.rb
:61:in `find_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/bundled_
asset.rb:16:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/base.rb:
377:in `new'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/base.rb:
377:in `build_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/index.rb
:94:in `block in build_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/caching.
rb:58:in `cache_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/index.rb
:93:in `build_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/base.rb:
287:in `find_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/index.rb
:61:in `find_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/manifest
.rb:211:in `block in find_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/manifest
.rb:257:in `benchmark'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/manifest
.rb:210:in `find_asset'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/manifest
.rb:119:in `block in compile'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/manifest
.rb:118:in `each'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/sprockets/manifest
.rb:118:in `compile'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-rails-2.3.2/lib/sprockets/rai
ls/task.rb:70:in `block (3 levels) in define'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-2.12.4/lib/rake/sprocketstask
.rb:146:in `with_logger'
/home/git/gitlab/vendor/bundle/ruby/gems/sprockets-rails-2.3.2/lib/sprockets/rai
ls/task.rb:69:in `block (2 levels) in define'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

I'm getting a 500 Error when loading the Gitlab Page. Has anyone ever experienced this?

**Comment by sameersbn** [comment]
@dobsiin can you try deleting the `/tmp` directory inside the data volume and relaunch the container. This will force the asset compilation while the image is starting up.

Make sure the container is able to access the internet. I think this step required a working internet connection. I am not sure though.

**Comment by dobsiin** [comment]
Thanks for the help.
But actually this error was because I added the addition gem onmiauth-cas. And permformed a bundle update which is not good because I ended up with different versions of the many many rubygems.
