### ISSUE TITLE
Email SocketError in Sidekiq

### ISSUE THREAD

**Issue by ovalin** [sameersbn/docker-gitlab#385]
Hello I am trying to configure email on my gitlab container and am running into the following error
and no email is sent,  just a timeout.

 WARN: {"retry"=>true, "queue"=>"mailer", "class"=>"Devise::Async::Backend::Sidekiq", "args"=>["confirmation_instructions", "User", "2", "zxp1DAwJEte2a7f9Ejwa", {}], "jid"=>"42605c5a5e20c1018892322e", "enqueued_at"=>1437453252.3136349, "error_message"=>"getaddrinfo: Name or service not known", "error_class"=>"SocketError", "failed_at"=>1437453253.062169, "retry_count"=>2, "retried_at"=>1437453354.572444}

has anyone come accross this one?

here is my docker-compose file

gitlab:
  environment:
  - GITLAB_PORT=10080
  - GITLAB_SSH_PORT=10022
  - GITLAB_HOST=192.168.1.116
  - GITLAB_EMAIL=*****
  - GITLAB_EMAIL_DISPLAY_NAME=*****
  - GITLAB_EMAIL_REPLY_TO=*****
  - GITLAB_EMAIL_ENABLED=SMTP_ENABLED
  - SMTP_ENABLED=true
  - SMTP_DOMAIN=*****
  - SMTP_PORT=587
  - SMTP_USER=*****
  - SMTP_PASS=*****
  - SMTP_STARTTLS=true
  - SMTP_HOST=smtp.*****
  - SMTP_AUTHENTICATION=plain
  image: sameersbn/gitlab:7.11.4
  links:
  - redis:redisio
  - postgresql:postgresql
  ports:
  - '10022:22'
  - 10080:80
postgresql:
  environment:
  - DB_USER=gitlab
  - DB_PASS=*****
  - DB_NAME=gitlabhq_production
  image: sameersbn/postgresql:9.4
redis:
  image: sameersbn/redis:latest

**Comment by ovalin** [comment]
chown -R git /etc/hosts
AND
/etc/resolv.conf

**Comment by sameersbn** [comment]
@ovalin hmm.. you are seeing permissions related issues that have never been seen before.
Can you please provide some information regarding your setup.

Are you using boot2docker on MacOS?
If you are using Linux, which distro?
Have you build the image or pulled it from the docker hub?
Output of `docker info` and `docker version` commands

**Comment by ovalin** [comment]
I am using a NAS produced by QNAP using an app called ContainerStation. On some flavour of linux which I am not sure of.

DOCKER INFO

Containers: 9
Images: 121
Storage Driver: devicemapper
 Pool Name: docker-253:0-38469648-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.103 GB
 Data Space Total: 107.4 GB
 Data Space Available: 103.3 GB
 Metadata Space Used: 5.53 MB
 Metadata Space Total: 1.074 GB
 Metadata Space Available: 1.068 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.12.6
Operating System: <unknown>
CPUs: 4
Total Memory: 1.851 GiB
Name: NASF09800
ID: 7H2Q:QRH3:TD6B:AS67:4NJT:5CCA:QVIT:XNLO:QMFN:CGMZ:PDV4:AGSD

DOCKER VERSION
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.1
Git commit (client): 85258fb
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.1
Git commit (server): 85258fb
OS/Arch (server): linux/amd64

**Comment by sameersbn** [comment]
@ovalin From the use of `devicemapper` as the storage driver, I am going to guess that it is some flavor of RHEL, which leads me to believe that the issues you are facing might have something to do with selinux. Can you try out the recommendation for selinux users in the [Persistence](https://github.com/sameersbn/docker-gitlab#persistence) section of the readme
