### ISSUE TITLE
Default password is wrong

### ISSUE THREAD

**Issue by chyuaner** [sameersbn/docker-gitlab#389]
I try install gitlab-docker with your README.md.
I finished install and try to login `root` account.
But I can't login.
I read origin gitlab and see default password is changed.
Default account: `root` password: `5iveL!fe`
[Source](https://github.com/sameersbn/docker-gitlab/#quick-start)

**Comment by sameersbn** [comment]
@chyuaner thanks for pointing it out. I was pretty certain they had changed the default password.
