### ISSUE TITLE
Changing Timezone parameters

### ISSUE THREAD

**Issue by javexed** [sameersbn/docker-gitlab#390]
Changing timezone parameters was rather difficult. If you do it wrong, the gitlab container won't come up and there isn't much of an error. Could be mitigated with a bit better documentation. For example, to convert to Eastern standard time:
TZ=Asia/Kolkata -> TZ=America/New_York
GITLAB_TIMEZONE=Kolkata -> GITLAB_TIMEZONE=EST

**Comment by LaurensRietveld** [comment]
Some more info: when you use a slash in the GITLAB_TIMEZONE, you'll get the following error: 
`sed: -e expression #1, char 30: unknown option to 's'`

Problem occurs because the slash isnt escaped before passing it on to sed. No problem with me to use another timezone notation, but would be good to document about allowed timezone notations (took some time locating the error)

**Comment by sameersbn** [comment]
@LaurensRietveld Its already documented in https://github.com/sameersbn/docker-gitlab#available-configuration-parameters

**Comment by LaurensRietveld** [comment]
How I interpreted that page was that `Europe/Amsterdam` was allowed (`Amsterdam` as well, which is mapped to `Europe/Amsterdam`). 
Is that correct? Because the issue here is with the `Europe/Amsterdam` TZ definition

**Comment by sameersbn** [comment]
You should use the mapping key. So if you want to set the  rails timezone as `Europe/Amsterdam`, then according to http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html you should set `GITLAB_TIMEZONE=Amsterdam`

**Comment by umputun** [comment]
For central time i have found "Central Time (US & Canada)" => "America/Chicago". Using the key leads to an error: "ArgumentError: Invalid Timezone: "Central Time (US {{GITLAB_TIMEZONE}} Canada)"

**Comment by michaelryanmcneill** [comment]
I'm having basically the same issue as @umputun. I'm trying to use `Eastern Time (US & Canada)` which bombs out on creation with the error: `ArgumentError: Invalid Timezone: Eastern Time (US {{GITLAB_TIMEZONE}} Canada)` I was able to get past this by escaping the special characters: `GITLAB_TIMEZONE=Eastern Time \(US \& Canada\)`

**Comment by njuaplusplus** [comment]
@sameersbn 

Could you tell me how does the `TZ` parameter work?
As I have not found any shell scripts or codes  are related to `TZ`.

Thank you!

**Comment by sameersbn** [comment]
The `&` character is now automatically escaped. If you have manually escaped the `&` character, then you need to remove it in versions > 8.1.x.

**Comment by blitzd** [comment]
Ran into this today - may be something worth adding to the 'Upgrade' portion of the readme?

**Comment by sameersbn** [comment]
these changes are logged in #39

**Comment by blitzd** [comment]
@sameersbn Awesome, I hadn't seen that - thanks!
