### ISSUE TITLE
Add grsec support

### ISSUE THREAD

**Issue by ninja-** [sameersbn/docker-gitlab#394]
I used the following snippet to make it work with grsec, it would be nice if you could merge it :)

```
 && apt-get update \
 && apt-get install -y supervisor logrotate locales curl \
      nginx openssh-server mysql-client postgresql-client redis-tools \
      git-core ruby2.1 python2.7 python-docutils nodejs \
      libmysqlclient18 libpq5 zlib1g libyaml-0-2 libssl1.0.0 \
      libgdbm3 libreadline6 libncurses5 libffi6 \
      libxml2 libxslt1.1 libcurl3 libicu52 paxctl \
 && update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX \
 && locale-gen en_US.UTF-8 \
 && dpkg-reconfigure locales \
 && gem install --no-document bundler \
 && rm -rf /var/lib/apt/lists/*

COPY assets/setup/ ${SETUP_DIR}/
RUN bash ${SETUP_DIR}/install.sh
RUN paxctl -cme `which nodejs`

COPY assets/config/ ${SETUP_DIR}/config/
COPY entrypoint.sh /sbin/entrypoint.sh
RUN chmod 755 /sbin/entrypoint.sh
```

**Comment by ninja-** [comment]
@sameersbn

**Comment by sameersbn** [comment]
@ninja- hi, sorry for not looking into this. I am not aware of grsec, looking it up now.

**Comment by sameersbn** [comment]
@ninja- I am not sure what the command ```paxctl -cme `which nodejs` ``` does exactly and why only `nodejs`? why not `nginx` or `ruby2.1`?

**Comment by sameersbn** [comment]
Now I have an idea of what `paxctl` does. But the question still remains, why not apply restrictions on `nginx` or `ruby2.1` or any other daemon processes?

**Comment by ninja-** [comment]
@sameersbn it's not about adding restrictions. it's about taking restrictions off :) it works fine when restrictions are disabled for nodejs

**Comment by sameersbn** [comment]
@ninja- do you see any issues otherwise?

**Comment by ninja-** [comment]
@sameersbn yeah, nodejs crashes ;)

**Comment by sameersbn** [comment]
can you check now. I have change the flags to `paxctl -Cm` as per https://en.wikibooks.org/wiki/Grsecurity/Application-specific_Settings#Node.js. Let me know if it does not work as expected

**Comment by sameersbn** [comment]
please close the issue if the changes are ok.

**Comment by sameersbn** [comment]
@ninja- ping

**Comment by ninja-** [comment]
@sameersbn sorry...I'll update to upstream and let you know

**Comment by sameersbn** [comment]
closing this issue. I believe it has been resolved.
