### ISSUE TITLE
Build fail "IPv6 address must be 16 bytes"

### ISSUE THREAD

**Issue by LordFPL** [sameersbn/docker-gitlab#396]
Hello,

I'm trying to build last version... but i have this error : 

````
ERROR:  While executing gem ... (ArgumentError)
    IPv6 address must be 16 bytes
````

An issue is actually open : https://github.com/rubygems/rubygems/issues/1274
Have you find another way to bypass this problem ?

**Comment by LordFPL** [comment]
For information, i made a little test : 
````
docker run -it --rm ruby:2.2 gem install bundler
ERROR:  While executing gem ... (ArgumentError)
    IPv6 address must be 16 bytes

docker run -it --rm ruby:2.1 gem install bundler
ERROR:  While executing gem ... (ArgumentError)
    IPv6 address must be 16 bytes

docker run -it --rm ruby:2.0 gem install bundler
Successfully installed bundler-1.10.6
1 gem installed
````

Strange... because it seems to work for other people..

**Comment by LordFPL** [comment]
A working but absolutely awful patch (to put just before gem install....) : 
````
sed -i 's/host = uri.host/host = "http:\/\/rubygems.org"/g' /usr/lib/ruby/2.2.0/rubygems/remote_fetcher.rb
````

**Comment by sameersbn** [comment]
Not sure if this is something that should be handled in the image. closing it. reopen if required.
