### ISSUE TITLE
Remove /Edit Command Line Instructions for New Project

### ISSUE THREAD

**Issue by jen-c** [sameersbn/docker-gitlab#401]
Hi. When creating new project on gitlab docker,
There is this Command Line Instructions.
Is it possible to delete or edit the 
"Existing folder or Git repository" part?
cd existing_folder
git init
git remote add origin ssh://git@be.happy.com:10022/user/d.git
git push -u origin master

**Comment by sameersbn** [comment]
@jen-c naah.. that comes from gitlab upstream. we do modify the upstream code in the image.
