### ISSUE TITLE
Gitlab, SSL, and API

### ISSUE THREAD

**Issue by pnelsonsr** [sameersbn/docker-gitlab#406]
Have you done any thing like repo creation through the api and into the gitlab container with ssl?

**Comment by sameersbn** [comment]
I used to be able to use https://github.com/grimborg/gitgitlab which 
talks to gitlab using the API. But I think the project has not been 
updated to keep up with the changes in Gitlab.

On Sunday 16 August 2015 05:00 AM, Patrick Nelson wrote:
> Have you done any thing like repo creation through the api and into the
> gitlab container with ssl?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-gitlab/issues/406>.
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com

**Comment by pnelsonsr** [comment]
That looks kinda interesting...  I'll look into it.  It also tells me that the api will allow me to create repos in groups which is what I really want.  Will let you know what I come up with!

**Comment by pnelsonsr** [comment]
I have been using curl with --cacert <a crt or pem file of the server> to get to other api's but I cannot seem to get the correct api call to create a project in a group.  I'm not getting ssl errors so I don't think its that.

**Comment by sameersbn** [comment]
@pnelsonsr Does this not work? https://gitlab.com/help/api/projects.md#create-project. The API has the option to specify the `namespace_id` where you would have to specify the id of the group.

**Comment by pnelsonsr** [comment]
namespace_id = group_id well that nice to know.  So OK so my URL needs to be something like:
'https://my-gitlab-server.com/projects/:name=myproject:namespace_id=mygroup:'
I've tried a bunch of things like this but I can not get the call right.  It says that this will create a project for an authenticated user but I can see that I'm not authenticating.  I admit I'm kind of new to this whole api thing and feel I'm missing something important.

**Comment by sameersbn** [comment]
@pnelsonsr naah... its a `POST` request. see http://superuser.com/questions/149329/what-is-the-curl-command-line-syntax-to-do-a-post-request

**Comment by pnelsonsr** [comment]
Wow that link is great!  Which method have you used?

**Comment by sameersbn** [comment]
@pnelsonsr I have not used the Gitlab api's. But from the list the first method should suffice.

**Comment by pnelsonsr** [comment]
It really helps as I have used API from GitHub, BitBucket, and Stash in the past.  I'll post here once I get it working so others can benefit!

**Comment by pnelsonsr** [comment]
So the trick is to get the id of the group, which I could not find anywhere in the webpages.  So I got this working with (I used the -k because I could not get a pem cert from chrome on windows and gave up trying to convert...):
`curl --header "PRIVATE-TOKEN: <my token>" "https://gitlab.example.com:10443/api/v3/namespaces" -k`
Once I had the namespace_id number associated with the wanted group I was able to get the repo created in the proper group with
`curl --header "PRIVATE-TOKEN: <my token>" -X POST "https://gitlab2.npn:10443/api/v3/projects?name=foobartest1&namespace_id=11&description=FooBarTest%201&wiki_enabled=false&snippets_enabled=true&visibility_level=10"`

I'm not really that good with the certs area.  Do you know how to pull the gitlab's server cert exported to pem format by any chance?

**Comment by pnelsonsr** [comment]
I'm not really that good with the certs area.  Do you know how to pull the gitlab's server cert exported to pem format, by any chance?

**Comment by pnelsonsr** [comment]
OK I just use the gitlab.crt from the certs dir by adding to the curl command
`--cacert <Path to gitlab data>/certs/gitlab.crt`

**Comment by pnelsonsr** [comment]
So the final API URL for adding to a group involves first getting the group namespace_id number using:
`curl --header "PRIVATE-TOKEN: <my token>" "https://gitlab.example.com:10443/api/v3/namespaces" --cacert <Path to gitlab data>/certs/gitlab.crt`
and then with that number running the create repo in a group API URL with:
`curl --header "PRIVATE-TOKEN: <my token>" -X POST "https://gitlab.example.com:10443/api/v3/projects?name=foobartest1&namespace_id=11&description=FooBarTest%201&wiki_enabled=false&snippets_enabled=true&visibility_level=10" --cacert <Path to gitlab data>/certs/gitlab.crt`
and that's that.  I wish gitlab would fix namespace_id with group_name which is what its called in all gitlab pages.

**Comment by sameersbn** [comment]
> I'm not really that good with the certs area. Do you know how to pull the gitlab's server cert exported to pem format, by any chance?

If you are still interested, the pem file simply consists of the servers certificate and key. The following command creates the pem file.

```bash
cat gitlab.crt gitlab.key > gitlab.pem
```

**Comment by pnelsonsr** [comment]
Thats good to know!
