### ISSUE TITLE
smtp isn't working

### ISSUE THREAD

**Issue by quartzinquartz** [sameersbn/docker-gitlab#411]
SMTP doesn't appear to work! 

I have changed the contents of the /home/git/gitlab/config/initializers/smtp_settings.rb:

> ...
> if Rails.env.production?
>  Gitlab::Application.config.action_mailer.delivery_method = :smtp
>
>  ActionMailer::Base.smtp_settings = {
>    address: "smtp.gmail.com",
>    port: 587,
>    user_name: "gitlab-username@mydomain.net",
>    password: "real-pw-for-^",
>    domain: "mydomain.net",
>    authentication: 'plain',
>    enable_starttls_auto: true,
>    openssl_verify_mode: 'peer' # See ActionMailer documentation for other >possible options
>  }
>end

Here's the email block from our gitlab.yml, with my changes:

>## Email settings
>   # Uncomment and set to false if you need to disable email sending from >GitLab (default: true)
>    email_enabled: true
>    # Email address used in the "From" field in mails sent by GitLab
>    email_from: "gitlab-username@mydomain.net"
>    email_display_name: "gitlab"
>    email_reply_to: "gitlab-username@mydomain.net"

Here's part of our production.rb:

>config.action_mailer.delivery_method = :smtp
>  # Defaults to:
>  # # config.action_mailer.sendmail_settings = {
>  # #   location: '/usr/sbin/sendmail',
>  # #   arguments: '-i -t'
>  # # }
>  config.action_mailer.perform_deliveries = true
>  config.action_mailer.raise_delivery_errors = true

FWIW - I can ping smtp.gmail.com from within the container and the output is healthy. 

...Am I missing something?

**Comment by sameersbn** [comment]
@quartzinquartz you should configure the SMTP setting using the `SMTP_` variables specified in the environment. If you manually edit the `smtp_setting.rb` file then you would need to restart the unicorn/sidekiq processes using.

Stop using: 

```bash
supervisorctl stop sidekiq
supervisorctl stop unicorn
```

Start using:

```bash
supervisorctl start unicorn
supervisorctl start sidekiq

**Comment by quartzinquartz** [comment]
Thanks for the information @sameersbn. 

I went on and ran those `supervisorctl` commands, which is something I had not known to do. I had previously ran `service gitlab restart` after each of those modifications that I listed above in the first post. After the `supervisorctl` commands that I just issued, I sent out a test email, though the test email hasn't coming through to my inboxes. 

I have `tail -f log/production.log` and I'm seeing `Sent mail to ...` lines one after the other. To note - I'm seeing multiple entries per email address; i.e. I sent one test email and user bob has just gotten at least 5 `Sent mail to ...` lines in the production.log over the past 5 minutes. I'm wondering, is that normal?

**Comment by sameersbn** [comment]
@quartzinquartz its not normal, maybe they were emails queued up from your previous attempts.

**Comment by quartzinquartz** [comment]
@sameersbn I'm uncertain about why that's happening, though I can say that there appear to be entries in that log for the emails that I have been attempting today. 

I was getting these:
`Sent mail to bob@email.com (3.0ms)
Emails disabled! Interceptor prevented sending mail test`
Now these:
`Sent mail to bob@email.com (219.5ms)`

I'm wondering if the length of time (200'ish ms) has something to do with these emails not coming through to my (or anyone else's) inbox. Do you think they could be timing out against some threshold? I'm not even sure where I would go to look for such a threshold.

**Comment by sameersbn** [comment]
@quartzinquartz you can check the sidekiq.log to see if you notice anything.

When I add an SSH key here's is what i see:

```
$ cd /var/log/gitlab/gitlab
$ tail -f production.log sidekiq.log
==> sidekiq.log <==
2015-08-30T04:27:25.459Z 2955 TID-cuoz4 GitlabShellWorker JID-48ac7ff47803c5cd602db7a5 INFO: done: 0.904 sec


2015-08-30T04:27:36.422Z 2955 TID-cuoz4 Sidekiq::Extensions::DelayedMailer JID-3424cb4cab377e0e67ced547 INFO: start

==> production.log <==

Sent mail to sameer@damagehead.com (7374.8ms)

==> sidekiq.log <==
2015-08-30T04:27:44.100Z 2955 TID-cuoz4 Sidekiq::Extensions::DelayedMailer JID-3424cb4cab377e0e67ced547 INFO: done: 7.678 sec
```

The mail sending task is actually performed by sidekiq. So if anything is a miss, you should notice it in the `sidekiq.log`

**Comment by quartzinquartz** [comment]
@sameersbn I ran `tail -f` for the production and sidekiq logs, then I removed/added an ssh key to suit your example:

`
Started POST "/profile/keys" for 127.0.0.1 at 2015-08-30 08:44:33 -0400
Processing by Profiles::KeysController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "key"=>{"title"=>"quartzinquartz@ethergen", "key"=>"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkBgg7J4A88CovWC7QwLNeny7WXrYdeSClvxhXDqMX5R5H42UWJZVid6gt8GOtrV3jo9P8lgH5bNUXLYnuztL2PszvVK6BRmhxWox8Y+Kcnu6ptB2vvpphizOuJPhnyl1bW9ukQJ2PEgZzIrU093baI+wWudoGYzCxEeLWojoxxUlSOqQKZaBNISpL9zNk4QbQ7pHuTY8JKdDA5rf90PGBxyri92oUf+8GFUDn2MMHF33ogGsLlYVXIHsjWAhsJE7RLJ4zom/0AwUYDeI29PFXsHFIeHTwHzsWXwL3Ki6RTt1n4YAi83ca+ugetftYjOUtYvC9KUw/EjY3NTknKitf quartzinquartz@ethergen"}}

==> sidekiq.log <==
2015-08-30T12:44:33.423Z 17972 TID-a6mno GitlabShellWorker JID-21f95220b4ce88376f3f4259 INFO: start

==> production.log <==
Redirected to https://gitlab.ourcompany.io/profile/keys/28
Completed 302 Found in 93ms (ActiveRecord: 13.5ms)
Started GET "/profile/keys/28" for 127.0.0.1 at 2015-08-30 08:44:33 -0400
Processing by Profiles::KeysController#show as HTML
  Parameters: {"id"=>"28"}
Completed 200 OK in 71ms (Views: 46.6ms | ActiveRecord: 8.9ms)

==> sidekiq.log <==
2015-08-30T12:44:34.093Z 17972 TID-a6mno GitlabShellWorker JID-21f95220b4ce88376f3f4259 INFO: done: 0.67 sec
2015-08-30T12:44:37.406Z 17972 TID-a6mno Sidekiq::Extensions::DelayedMailer JID-87a32d67b3e330bb38f910a9 INFO: start

==> production.log <==

Sent mail to quartzinquartz@ethergen.com (287.5ms)

==> sidekiq.log <==
2015-08-30T12:44:37.750Z 17972 TID-a6mno Sidekiq::Extensions::DelayedMailer JID-87a32d67b3e330bb38f910a9 INFO: fail: 0.344 sec
2015-08-30T12:44:37.751Z 17972 TID-a6mno WARN: {"retry"=>true, "queue"=>"default", "class"=>"Sidekiq::Extensions::DelayedMailer", "args"=>["---\n- !ruby/class 'Notify'\n- :new_ssh_key_email\n- - 28\n"], "jid"=>"87a32d67b3e330bb38f910a9", "enqueued_at"=>1440938673.4271758, "error_message"=>"SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed", "error_class"=>"OpenSSL::SSL::SSLError", "failed_at"=>1440938677.7497237, "retry_count"=>0}
2015-08-30T12:44:37.751Z 17972 TID-a6mno WARN: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
2015-08-30T12:44:37.751Z 17972 TID-a6mno WARN: /usr/lib/ruby/2.1.0/net/smtp.rb:586:in `connect'
/usr/lib/ruby/2.1.0/net/smtp.rb:586:in `tlsconnect'
/usr/lib/ruby/2.1.0/net/smtp.rb:563:in `do_start'
/usr/lib/ruby/2.1.0/net/smtp.rb:520:in `start'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `block in deliver'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.11/lib/action_mailer/base.rb:527:in `block in deliver_mail'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/notifications.rb:159:in `block in instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/notifications.rb:159:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.11/lib/action_mailer/base.rb:525:in `deliver_mail'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `deliver'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/extensions/action_mailer.rb:32:in `deliver'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/extensions/action_mailer.rb:20:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:75:in `execute_job'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/git/gitlab/lib/gitlab/sidekiq_middleware/memory_killer.rb:17:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidetiq-0.6.3/lib/sidetiq/middleware/history.rb:8:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/logging.rb:22:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:51:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:98:in `stats'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:50:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
2015-08-30T12:45:30.390Z 17972 TID-a6mno Sidekiq::Extensions::DelayedMailer JID-87a32d67b3e330bb38f910a9 INFO: start
`

Wondering if this is the culprit. Looks like something is unable to verify the SSL cert:

`
2015-08-30T12:44:37.751Z 17972 TID-a6mno WARN: {"retry"=>true, "queue"=>"default", "class"=>"Sidekiq::Extensions::DelayedMailer", "args"=>["---\n- !ruby/class 'Notify'\n- :new_ssh_key_email\n- - 28\n"], "jid"=>"87a32d67b3e330bb38f910a9", "enqueued_at"=>1440938673.4271758, "error_message"=>"SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed", "error_class"=>"OpenSSL::SSL::SSLError", "failed_at"=>1440938677.7497237, "retry_count"=>0}
2015-08-30T12:44:37.751Z 17972 TID-a6mno WARN: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
`

**Comment by sameersbn** [comment]
@quartzinquartz the issue appears to be `certificate verify failed`. try adding/changing  `openssl_verify_mode: 'none'` in your smtp configuration

**Comment by quartzinquartz** [comment]
@sameersbn good eye. Have a nice day. Fixed.

**Comment by sameersbn** [comment]
glad that the issue was resolved.

**Comment by march1993** [comment]
Although setting openssl_verify_mode to `none` may help solve the problem, would it be better to include ca-certificates in the docker file?

**Comment by bessalahAmar** [comment]
for me i had to add this **gitlab_rails['gitlab_email_enabled'] = true** in **/etc/gitlab/gitlab.rb**
