### ISSUE TITLE
Support Rack Attack Configuration

### ISSUE THREAD

**Issue by cmckni3** [sameersbn/docker-gitlab#413]

**Comment by sameersbn** [comment]
@cmckni3 I am not really sure what kind of options go here. However I see this seems to be an advanced use case and the image already allows users to fully customize the gitlab configuration templates, including `rack_attack.rb`.

Assuming that `/srv/docker/gitlab/gitlab` is the host path mounted at `/home/git/data`

```bash
cd /srv/docker/gitlab/gitlab
mkdir -p config/gitlabhq
wget https://raw.githubusercontent.com/sameersbn/docker-gitlab/master/assets/config/gitlabhq/rack_attack.rb -O config/gitlabhq/rack_attack.rb
# edit config/gitlabhq/rack_attack.rb
# start / restart gitlab container
```

This way you can override the entire gitlab configuration as you see fit https://github.com/sameersbn/docker-gitlab/blob/master/entrypoint.sh#L329-L348

See #11 and https://github.com/sameersbn/docker-gitlab/issues/11#issuecomment-34221545 for additional information.

Let me know if there is something more than this that you are interested in.

**Comment by sameersbn** [comment]
Couple of notes on this:
 1. On version updates you will need to make sure you migrate your changes to the newer `rack_attack.rb` if required.
 2. Copy only the configurations that you want to edit in the `config/` directory
 3. Change only the configurations that the image does not already allow you to customize using ENV variables. This would reduce maintenance on your end as a result of 1.

**Comment by cmckni3** [comment]
Yeah, I figured I could mount it. I just need to add whitelisted IPs to rack attack so I can use the API without being rate limited.

I was wondering more about adding an `ENV` variable to configure it.

**Comment by sameersbn** [comment]
@cmckni3 sorry for not reponding earlier. i am not aware of rack attack configurations. The thing is I try to avoid making changes (unless absolutely required) to the default GitLab configs to ease up the maintenance efforts. Avoiding such changes allows me to offer newer images as soon as gitlab makes new releases.

This is one of the reasons why I have not provided any way to customize the login screen etc. If possible add your configuration templates by sending a PR to the upstream gitlab project. Which will make it way easier to then support in our image.

**Comment by cmckni3** [comment]
Thanks @sameersbn but it isn't a big deal. I got it working by mounting the config file.

**Comment by sameersbn** [comment]
8b0511f9edc5d78577f59b2036d1b415f9c9e151 adds parameters to configure rack attack. can you please take a look and confirm that it works for you?
