### ISSUE TITLE
email from address is coming out as GitLab <example@example.com>

### ISSUE THREAD

**Issue by mike-pun** [sameersbn/docker-gitlab#414]
System is running fine except that my notification emails are coming out with a strange "from" address. Below is my docker command. Might be related to that we have a .media domain.

Much thanks for a wonderful docker.

sudo docker run --name=gitlab -d -p 8022:22 -p 8443:443\
  -e "DB_HOST=164.18.42.1" -e "DB_NAME=gitlabhq_production" \
  -e "DB_USER=gitlab" -e "DB_PASS=xxxy" \
  -e "DB_TYPE=mysql" \
  -e "GITLAB_RELATIVE_URL_ROOT=/gitlab" \
  -e "GITLAB_HOST=104.14.57.13" \
  -e "GITLAB_SSH_PORT=8022" -e "GITLAB_PORT=8443" \
  -e "GITLAB_HTTPS=true" -e "SSL_SELF_SIGNED=true" \
  -e "SMTP_USER=admin@xxxxy.media" -e "SMTP_PASS=xxx \
  -e "SMTP_DOMAIN=xxxxy.media" -e "SMTP_HOST=mail.xxxxy.media" \
  -e "SMTP_PORT=26" -e "SMTP_STARTTLS=false" -e "SMTP_TLS=false" \
  --link=redis-gitlab:redisio \
  -v /opt/gitlab:/home/git/data \
 sameersbn/gitlab:7.10.4

**Comment by sameersbn** [comment]
You should need to specify `GITLAB_EMAIL`, additionally you might want to specify `GITLAB_EMAIL_REPLY_TO` as well.

**Comment by mike-pun** [comment]
Got it. Thanks.
