### ISSUE TITLE
no default value to DB_TYPE

### ISSUE THREAD

**Issue by fernandoneto** [sameersbn/docker-gitlab#418]
In Readme you say the default database type is set to mysql, but if dont set the variable you get error. 

```bash
Sep 15 16:29:06 core-02 bash[19283]: ERROR:
Sep 15 16:29:06 core-02 bash[19283]: Please specify the database type in use via the DB_TYPE configuration option.
Sep 15 16:29:06 core-02 bash[19283]: Accepted values are "postgres" or "mysql". Aborting...

```

**Comment by sameersbn** [comment]
@fernandoneto you are right. Thanks for spotting the error. I will fix it but set the default value to `postgres` since gitlab recommends using postgresql over mysql.

**Comment by fernandoneto** [comment]
:+1: thanks
