### ISSUE TITLE
Backing up ssh Hostkey

### ISSUE THREAD

**Issue by JosephLutz** [sameersbn/docker-gitlab#421]
I am uncertain weather this is within the scope of your image or if I should perform this myself.

While testing the backup I completely removed all data from the data volumes and then performed the gitlab restore. I noticed that the /home/git/data/ssh/ssh_host_*_key files were not restored when I attempted to perform a new push to a repository and received a message about the server's key changing.

Are there any other files that are not backed up using the 'app:rake gitlab:backup:create'? (I am backing up the server certificate separately.)

**Comment by sameersbn** [comment]
@JosephLutz the gitlab backup function only backs up stuff that is directly related to gitlab such as the database, repositories, uploads, etc. The SSH server keys are not part of the gitlab application and as such gitlab does not back them up and rightly so.

The only things that are backups are:
 - db
 - repositories directory
 - uploads directory

Apart from this, anything else that you may notice in the data volume is not backed up. 
p.s. you can just open an existing backup.tar file and see whats backed up.
 - backups
 - certs
 -

**Comment by sameersbn** [comment]
Can this issue be closed?
