### ISSUE TITLE
Mattermost

### ISSUE THREAD

**Issue by utrack** [sameersbn/docker-gitlab#426]
Hi! Any way to enable Mattermost on 8.0.0?
Can't find anything related to it in live container really.

**Comment by sameersbn** [comment]
Mattermost is not part of gitlab. The Gitlab omnibus installer simply adds mattermost as an addon. If you want to install mattermost you can use their image https://github.com/mattermost/platform/blob/master/doc/install/single-container-install.md

**Comment by lazyfrosch** [comment]
Please be careful with their image, it runs the service as root...

I fiddled around with a new container: https://github.com/lazyfrosch/docker-mattermost

Maybe mergeable to upsteam later :)

**Comment by vassilvk** [comment]
@sameersbn - according to [this link](http://doc.gitlab.com/omnibus/gitlab-mattermost/), Mattermost can be set up alongside GitLab on the same server. Specifically the first approach discussed in the **Getting started** section indicates that Mattermost can be "enabled" by simply modifying `gitlab.rb`.

If this could be done in the Docker container running sameersbn/gitlab, it would provide out-of-the box integration of Mattermost with the GitLab instance.

Do you think this approach of setting up Mattermost is feasible?

**Comment by frenchbeard** [comment]
@vassilvk This would be on the "omnibus-type" install of gitlab, which comes bundled with mattermost and a couple of other things. In this docker image, gitlab (and only gitlab) is compiled and installed from source, meaning you don't have any part of mattermost within it.

**Comment by vassilvk** [comment]
I understand, thanks @frenchbeard.

**Comment by sameersbn** [comment]
I would just run mattermost from another container instead of adding it inside the gitlab container. I am not aware if there are any good mattermost images currently available. We have one listed by @lazyfrosch above :smile: .

**Comment by lazyfrosch** [comment]
the "offical" container of mattermost is rather ugly, bundling MySQL, and running the actual application as root - https://github.com/mattermost/platform/blob/master/docker/2.1/docker-entry.sh

Since I'm not using a chat tool as of now, I'm not updating my container, but feel free to take the "code" [lazyfrosch/docker-mattermost](https://github.com/lazyfrosch/docker-mattermost)

**Comment by vassilvk** [comment]
Thanks @sameersbn, @lazyfrosch.

I ended up setting up a parallel Mattermost server using [GitLab's official Docker container](https://hub.docker.com/r/gitlab/gitlab-ce/) following the **GitLab Mattermost** integration setup docs [here](http://doc.gitlab.com/omnibus/gitlab-mattermost/).

This way I get Sameer's lean GitLab setup and a parallel GitLab Mattermost setup, which integrates nicely (SSO, webhooks, etc.) with @sameersbn's GitLab container.

When running the official GitLab container solely for the purposes of using Mattermost, the trick is to turn off GitLab on that container: `gitlab_rails['enable'] = false`.

**Comment by marton78** [comment]
@vassilvk but what's the advantage to use "Sameer's lean GitLab setup" if you install the original Gitlab container anyway?

**Comment by vassilvk** [comment]
@marton78 - I keep the two running on different machines.

**Comment by pierreozoux** [comment]
@lazyfrosch thanks for your work, I got a bit inspired for the salts.

Here is my PR to the official mattermost docker repo:
https://github.com/mattermost/mattermost-docker/pull/31

Let me know if you have questions!

I still need to address the gitlab integration, but I think it will be fine-ish.

**Comment by lazyfrosch** [comment]
@pierreozoux I'm not using Mattermost at the moment, but feel free to salvage :wink:
