### ISSUE TITLE
Deploy to tutum no longer working

### ISSUE THREAD

**Issue by davidwindell** [sameersbn/docker-gitlab#427]
Tutum wants the compose file not to have a .dist extension;

https://support.tutum.co/support/solutions/articles/5000620449-deploy-to-tutum-button

**Comment by sameersbn** [comment]
@davidwindell let me check what i can do.. either need to revert #409 or create a copy of docker-compose.yml.dist as tutum.yml

**Comment by davidwindell** [comment]
:+1:
