### ISSUE TITLE
GITLAB_TIMEZONE with ampersand

### ISSUE THREAD

**Issue by devinrsmith** [sameersbn/docker-gitlab#428]
Not sure the correct way to set GITLAB_TIMEZONE when the key contains an ampersand, such as

`- "GITLAB_TIMEZONE=Central Time (US & Canada)"`
or
`- GITLAB_TIMEZONE=Central Time (US & Canada)`

both inspect out to:

```
$ docker inspect local_gitlab_1 | grep TIMEZONE
            "GITLAB_TIMEZONE=Central Time (US \u0026 Canada)",
```

aborts with error:

```
ArgumentError: Invalid Timezone: Central Time (US {{GITLAB_TIMEZONE}} Canada)
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/core_ext/time/zones.rb:72:in `rescue in find_zone!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/core_ext/time/zones.rb:56:in `find_zone!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/core_ext/time/zones.rb:40:in `zone='
```

**Comment by devinrsmith** [comment]
Maybe a YAML encoding thing? Not sure the proper way to do it.

**Comment by sameersbn** [comment]
I am not sure either, but http://stackoverflow.com/questions/2291165/escape-an-ampersand-at-the-start-of-a-yaml-entry says use double quotes.

**Comment by sameersbn** [comment]
Let me check the container though.

**Comment by sameersbn** [comment]
I think it confuses the sed substitution .

**Comment by sameersbn** [comment]
use `GITLAB_TIMEZONE=Central Time (US \& Canada)`

**Comment by devinrsmith** [comment]
Thanks for the quick reply!

**Comment by sameersbn** [comment]
The `&` character is now automatically escaped. If you have manually escaped the `&` character, then you need to remove it in versions > 8.1.x.
