### ISSUE TITLE
CI redirection not working when terminating SSL outside of this container

### ISSUE THREAD

**Issue by lorenz** [sameersbn/docker-gitlab#431]
I terminate all my SSL connections centrally with a NGINX server. Therefore `$scheme`  in [gitlab_ci](https://github.com/sameersbn/docker-gitlab/blob/master/assets/config/nginx/gitlab_ci) is always http. The request gets sent back to the frontend using HTTP which issues a 301 redirect to HTTPS. This redirect is passed upstream from the NGINX in this image to frontend and then to the client where it makes absolutely no sense as the client connected via HTTPS. Is there a way to prevent that from happening?

**Comment by sameersbn** [comment]
If you have few runners then you can just update the url in the runner to `https://git.example.com/ci` and get rid of that redirection all together :)

**Comment by lorenz** [comment]
That worked, thanks! But is took some time to track down this issue. Could you maybe add a warning to the migration docs or fix it so that others don't need to debug it?

**Comment by sameersbn** [comment]
Will do
