### ISSUE TITLE
Availing of CI functionality in new verison

### ISSUE THREAD

**Issue by Analect** [sameersbn/docker-gitlab#435]
@sameersbn 
Thanks for your continued work on bring the most up-to-date dockerized version of Gitlab.
I haven't used gitlab-ci before, but now that it is part of gitlab, I wanted to try.

I see your docs ref migration .. which are not relevant for me given I haven't used before ...
https://github.com/sameersbn/docker-gitlab/blob/master/CI_MIGRATION.md

Should I still be following some of the docs in docker-gitlab-ci in terms of setting up the database etc..?
https://github.com/sameersbn/docker-gitlab-ci#external-postgresql-server

**Comment by sameersbn** [comment]
no.. you dont need to do any extra setup apart from the fact that you need to setup runners to carry out the builds.

**Comment by phani1kumar** [comment]
@sameersbn Thank you for this great repository. I am also in the same situation as @Analect I've got the 7.11.x which I migrated to 8.1.3 using the documentation. 

Now when I login, I am seeing the project listing and stuff but couldn't see the CI specific links. Can you please suggest if I've to visit a different URL?

Thanks and Best Regards,
Phani

**Comment by sameersbn** [comment]
There used to be a direct link on the main dashboard. But it seems to have changed. Visit http://git.example.com/ci/ on your installation and you will get the relevant information. Once you have CI enabled for a project you will notice a Builds button for that project among other visual cues.

![selection_049](https://cloud.githubusercontent.com/assets/410147/11056516/9fe3dd64-87a8-11e5-9045-47958134b4ec.jpg)
