### ISSUE TITLE
Kubernetes gitlab replication controller 

### ISSUE THREAD

**Issue by kyzh** [sameersbn/docker-gitlab#438]
I'm trying to get the gitlab kubernetes rc to work.
I found a few easy to fix issues (see PR #436, PR#437)

I'm now a at the point where the pod is stuck with this error message:
```
master gitlab # kubectl logs gitlab-f565p
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
Creating SSH2 RSA key; this may take some time ...
Creating SSH2 DSA key; this may take some time ...
Creating SSH2 ECDSA key; this may take some time ...
Creating SSH2 ED25519 key; this may take some time ...
invoke-rc.d: policy-rc.d denied execution of restart.
```

To fix the first set of errors, I added the following (PR#)
Yet it still fails at 
```
invoke-rc.d: policy-rc.d denied execution of restart.
```

I tried to look into the container itself to figure out what was causing problem.
I haven't succeeded yet since the log files are pretty empty.

If you have any pointers, ways to increase debug output it, etc... that would be great.
I'm using `Kubernetes v1.0.3` on `CoreOS 766.3.0`

**Comment by sameersbn** [comment]
Try adding the env variable DEBUG_ENTRYPOINT to see what it hangs.

**Comment by kyzh** [comment]
Perfect.
I'll let you know how it goes

**Comment by sameersbn** [comment]
I tested the kubernetes samples on google container engine and had no issues.

**Comment by kyzh** [comment]
Exactly.
I'm not running it on google container engine and there is a few things that don't automatically work.

So far my issue is with `DB_HOST` value.
I cannot get it to be populated with the postgresql-gitlab k8s service IP.

I've also tried using `POSTGRESQL_GITLAB_SERVICE_HOST` as a value.
It doesn't work either (but I'm quite sure it work on GCK).

I will need to do more testing to figure out why/how I can get it to work.
I'll update the ticket with my findings as soon as I get some results

**Comment by sameersbn** [comment]
Hang on.. For the DB_HOST to work you need to have SkyDNS in your kubernetes cluster, else the service discovery won't happen. Please check you kubernetes setup docs to ensure that it installs the skydns addon. eg. https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/deployDNS.md

**Comment by sameersbn** [comment]
were you able to resolve the issue?

**Comment by sameersbn** [comment]
closing..
