### ISSUE TITLE
Mysql backup problem

### ISSUE THREAD

**Issue by fernandoneto** [sameersbn/docker-gitlab#440]
im running gitlab with mysql and im not linking containers. i also setup a daily backup but the problem is the `.sql` in backup path is empty.

**Comment by sameersbn** [comment]
Thats weird. Will check locally and let you know

**Comment by fernandoneto** [comment]
@sameersbn thanks
i will do some more tests this weekend to give you more feedback.

**Comment by fernandoneto** [comment]
@sameersbn 
i just found the problem and it's not related with gitlab, the problem is mysql instance. 
closing this issue 
thanks
