### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by billfig** [sameersbn/docker-gitlab#441]
after running docker gitlab container few days, users start to get error 500 on some pages, goes away after container restart.
any ideas what can cause this or what to look for.

**Comment by ivlis** [comment]
You have run out of memory, GitLab is very sensitive  the amount of memory you have. Try to add some swap, usually it helps.

**Comment by billfig** [comment]
saw used some swap slightly when this happened, increased swap from equal to double of memory to see if helps, thanks.

**Comment by sameersbn** [comment]
was your issue resolved after increasing the swap file size?
