### ISSUE TITLE
Cannot upgrade from 7.14.3

### ISSUE THREAD

**Issue by T-Grave** [sameersbn/docker-gitlab#444]
Output of 'docker info':
```
Containers: 4
Images: 221
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 229
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-49-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 23.55 GiB
Name: docker
```

The docker run command I use (I know it's long, I was about to make an env file, but then I run into this issue)
```
docker run -d --restart=always --name=gitlab -v /srv/docker/gitlab/gitlab:/home/git/data --link=postgresql-gitlab:postgresql --link=redis-gitlab:redisio --publish=[LOCALIP]:22:22 --publish=[LOCALIP]:80:80 --env='GITLAB_PORT=80' --env='GITLAB_SSH_PORT=22' --env='GITLAB_HOST=[domainname]' --env='GITLAB_BACKUPS=daily' sameersbn/gitlab:8.0.2
```

If I try without the --restart flag it just gives me the container ID and it crashes almost immediately.
With the --restart flag I can see it's in a constant state of restarting when I use 'docker ps' (restarts almost every 5 seconds)

Is there a way for me to access log information so I might be able to figure out where it's crashing?

postgresql & redis containers are both at their latest versions. OS and docker are both fully updated.

I've followed the upgrade procedure laid out in the README (as this worked perfectly before)

When I remove the new container and run the exact same run command with version 7.14.3 it runs without any issues. I've also tried the 8.0.0 version, but I get the same result as above.

Thanks in advance.

**Comment by Allineer** [comment]
`docker logs gitlab`?

**Comment by sharpner** [comment]
don't forget to specify `GITLAB_SECRETS_DB_KEY_BASE`

**Comment by T-Grave** [comment]
Thanks for the quick response! Seemed like specifying ```GITLAB_SECRETS_DB_KEY_BASE``` did the trick, had no idea this was a requirement since 8.0.0. My bad.

**Comment by sameersbn** [comment]
please subscribe to issue #39 to get notified about such breaking changes.
