### ISSUE TITLE
relative_root_url via http/https on v8.x

### ISSUE THREAD

**Issue by recteurlp** [sameersbn/docker-gitlab#446]
Hello,

Seem that the new http git handler does not support relative_url root for the moment

The official issue :  https://gitlab.com/gitlab-org/gitlab-ce/issues/2770

I've done a quick fix to make "/gitlab" relative_url working on http / https available here https://github.com/recteurlp/docker-gitlab/commit/7b770c4eea91f112cb488232ad71a702fd76328c

**Comment by sameersbn** [comment]
Hey @recteurlp thanks for letting me know about this. I though I had tested the relative_url functionality before making the `8.0` release. Seems like i fucked up :(

I think I will wait a couple of days for GitLab to fix the issue upstream. If nothing comes soon enough I will test and merge your commit into the image.

Thanks again.

**Comment by debovema** [comment]
+1 for the fix :)

**Comment by sameersbn** [comment]
will commit this fix tomorrow.

**Comment by sameersbn** [comment]
can you try the `latest` build and let me know if it works for you? I will tag a new release upon confirmation. Thanks

**Comment by sameersbn** [comment]
Please be advised  that http clones with relative_urls is broken in `8.1.0`.

**Comment by sameersbn** [comment]
`8.1.0-1` fixes the https/http cloning issue when `GITLAB_RELATIVE_URL_ROOT` is used.
