### ISSUE TITLE
Unable to start GitLab container

### ISSUE THREAD

**Issue by russellseymour** [sameersbn/docker-gitlab#449]
Hello,

I am trying to run the GitLab container using the image from the repository.  I am using my own MySQL and Redis containers so am linking to them.  The run command for GitLab is:

```
 docker run --name gitlab --link mysql-server:mysql --link redis-server:redisio \
 -v /usr/local/docker/data/gitlab:/home/git/data --publish 192.168.50.40:22:22 \
--publish 192.168.50.40:80:80 -e GIITLAB_SECRETS_DB_KEY_BASE=Pjzbv8CWX/d2gHqDg5nmmyM56P2UTFodoeGRG6q/IIQ=' \
-e 'DB_NAME=gitlabhq_production' -e 'DB_USER=gitlab' -e 'DB_PASS=password' \
 sameersbn/gitlab:8.0.3
```

(The secrets key is a new one that I generated for this post)

However when I run this I get the following error:

    sed: -e expression #1, char 44: unknown option to `s'

I have seen in the issues that other people have had similar problems and they have been able to track them down using 'set -x' .  However I am not sure where to put this.  Is this something that I should put in the Dockerfile in the Git repo I have cloned and build my own image?

The MySQL I have is just stock mysql-server and I have setup the database and set the appropriate permissions.  Redis is just stock image.

Any help is greatly appreciated.

Thanks, Russell

**Comment by Allineer** [comment]
Please, enable debugging, `DEBUG_ENTRYPOINT=true` and show me some lines from the log before this error.

PS: `DEBUG_ENTRYPOINT=true` is turn on `set -x`

**Comment by Allineer** [comment]
Wow!

By first, replace all symbols `/` in the `GIITLAB_SECRETS_DB_KEY_BASE` with any non-special (`[a-zA-Z0-9]`)

**Comment by Allineer** [comment]
Wow!!!

Replace the `GIITLAB_SECRETS_DB_KEY_BASE` => `GITLAB_SECRETS_DB_KEY_BASE` !!!

**Comment by russellseymour** [comment]
@Allineer thanks for that - that is the problem.

I had checked the strings on everything else .... DOH!!

I had just found the DEBUG_ENTRYPOINT flag when your email came in so was about to try that and then your second comment arrived.

Thanks again.
