### ISSUE TITLE
422 :The change you requested was rejected.

### ISSUE THREAD

**Issue by kps18** [sameersbn/docker-gitlab#453]
Hi

       We are using nginx loadbancer for load balancing gitlab. Authentication page is working and if i logged in  we faced the error "422 The change you requested was rejected." 

Here the nginx log

"POST /users/sign_in HTTP/1.1" 422 472 "https://domainname.com/users/sign_in"

If we configure a single server in upstream everything is working fine but if we add one more server we faced the above error. 

Here the nginx configuration
 
upstream server.https {
Server address
        }
 location / {
                proxy_pass https://server.https;
                proxy_set_header Host $host;
                proxy_hide_header X-Powered-By;
                proxy_read_timeout 600;
                proxy_set_header LB_SSL_REMOTE_IP $remote_addr;
                proxy_hide_header XCSession;
                proxy_next_upstream off;
                return 301 https://$host$request_uri;
                proxy_set_header X-Forwarded-Ssl on;

Any luck

**Comment by ninja-** [comment]
> If we configure a single server in upstream everything is working fine but if we add one more server we faced the above error.

what do you mean by this ? are you mirroring your gitlab files and database on two hosts

**Comment by kps18** [comment]
@ninja-  yes now it is working. After changed sticky mode. 

Thanks

**Comment by andyzheung** [comment]
I have the same problem, what is sticky mode?@kps18
