### ISSUE TITLE
Warn if redis server is not accessible

### ISSUE THREAD

**Issue by dg-ratiodata** [sameersbn/docker-gitlab#454]
@sameersbn 
The follwing [line](https://github.com/sameersbn/docker-gitlab/blob/master/entrypoint.sh#L913) in `entrypoint.sh`prevents an error message to bubble up if the redis server is not accessible - TCP SYN gets a TCP RST as response  because I used a "broken" redis container at first..

~~~bash
sudo -HEu ${GITLAB_USER} bundle exec rake assets:clean assets:precompile cache:clear >/dev/null 2>&1
~~~

Maybe you could add some kind of a check to `/sbin/entrypoint.sh` to tell the user whats wrong. Otherwise the script just stops and the git lab server does not start up. That's everythin `entrypoint.sh` writes to stderr/stdout.

~~~
Oct 08 12:54:58 host docker[9275]: Waiting for database server to accept connections
Oct 08 12:54:58 host docker[9275]: Migrating database...
Oct 08 12:55:14 host docker[9275]: Compiling assets. Please be patient, this could take a while...
~~~

**Comment by sameersbn** [comment]
The referenced commit pings the redis-server to ensure that it is reachable and responding,

**Comment by dg-ratiodata** [comment]
Thanks a lot.
