### ISSUE TITLE
swiched to quay.io

### ISSUE THREAD

**Issue by martingabelmann** [sameersbn/docker-gitlab#458]
Hi,

I`ve seen that you swiched to quay.io 
will the image on hub.docker.com still be available in the future (with automated builds) ?

Thanks, we really enjoy your work!
greetings

**Comment by martingabelmann** [comment]
sorry, didnt saw your announcement-comment https://github.com/sameersbn/docker-gitlab/issues/39 .

**Comment by sameersbn** [comment]
the builds on quay.io are also automated builds.
