### ISSUE TITLE
docker-compose: Could not reach any registry endpoint

### ISSUE THREAD

**Issue by mrBulb** [sameersbn/docker-gitlab#459]
Hey,

when i try to start with docker-compose i get the following result:

    xxx@ubuntu:~/docker_gitlab$ docker-compose up
    Pulling postgresql (quay.io/sameersbn/postgresql:9.4-3)...
    Pulling repository quay.io/sameersbn/postgresql
    Could not reach any registry endpoint

I tried with the current docker-compose.yml from 876c6a192b with the quay.io repo.
My system is a Ubuntu 15.04. I tried it also on a other machine (still ubuntu 15.04) and it still fails.

When i try to pull the images with docker-pull it works.

    docker-compose version: 1.4.2
    Docker-version:
    xxx@ubuntu:~/docker_gitlab$ docker version
    Client:
     Version:      1.8.2
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   0a8c2e3
     Built:        Wed Oct  7 17:53:44 UTC 2015
     OS/Arch:      linux/amd64

    Server:
     Version:      1.8.2
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   0a8c2e3
     Built:        Wed Oct  7 17:53:44 UTC 2015
     OS/Arch:      linux/amd64

**Comment by FlorianChedemail** [comment]
I'm having the same issue, on a similar setup (Debian)

```
~# docker-compose --version
docker-compose version: 1.4.0
~# docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:20:14 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:20:14 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by sameersbn** [comment]
needed to update the postgresql image version.
