### ISSUE TITLE
remote: not found / repository ... not found

### ISSUE THREAD

**Issue by codingnet** [sameersbn/docker-gitlab#460]
I'm using the same settings for 7.14.3 and 8.0.4 package. The issue shows in the 8.0.4 package only. If I switch back to the old package(7.14.3), it works just fine. I did try to run app:sanitize but it still does not work.

Cloning into 'myproject'...
remote: Not Found
fatal: repository 'https://somedomain.../group/myproject.git/' not found

Any idea?

**Comment by codingnet** [comment]
the issue may be related to the "relative_root_url via http/https on v8.x" #446

I have GITLAB_RELATIVE_URL_ROOT in my settings.

**Comment by sameersbn** [comment]
yea. probably is related to that.
There is a patch in one of issue for this image. I will apply it tomorrow and update this thread.

I was hoping they would have fixed it in upstream by now :(

**Comment by sameersbn** [comment]
can you try the `latest` build and let me know if it works for you? I will tag a new release upon confirmation. Thanks

**Comment by recteurlp** [comment]
I've tested the `latest` build and it's working for me.
Thanks

**Comment by codingnet** [comment]
The latest build works.

Thank you

**Comment by sameersbn** [comment]
initiated build of tag `8.0.4-1`
