### ISSUE TITLE
Precompile assets

### ISSUE THREAD

**Issue by ninja-** [sameersbn/docker-gitlab#461]
Why aren't they compiled when the image is built ?

**Comment by sameersbn** [comment]
Last time I checked:
- the assets had to be recompiled if GITLAB_RELATIVE_URL_ROOT is changed. 
- required a DB connection for the compilation procedure to execute
Due to these reasons, this step is executed at runtime.

I don't know if things have changed. Will need to check.

**Comment by ninja-** [comment]
oh...but doesn't the asset compiler work that way that even if the runtime url root was different than what was compiled in the image it would take only a few seconds to update with cache?

**Comment by sameersbn** [comment]
nope.. it has to be recompiled like it is being done now.

**Comment by ninja-** [comment]
but now it doesn't contain any asset cache

**Comment by electricmonk** [comment]
I'm not sure what @ninja-  experienced, but my problem is that startup time for a fresh install can be around 90 seconds due to assert compilation. My use case is end-to-end testing a system that uses Gitlab, the test takes 90+ seconds to run due to Gitlab compiling assets each time.

**Comment by sameersbn** [comment]
@electricmonk gitlab is started in your tests?

**Comment by electricmonk** [comment]
@sameersbn yes. We're talking about an end-to-end test.

**Comment by sameersbn** [comment]
@electricmonk ok. i will check if the assets can be precompiled.

**Comment by electricmonk** [comment]
@sameersbn thanks!

**Comment by sameersbn** [comment]
@electricmonk @ninja- i think it is now possible to compile the cache at build time. Have not tested it yet. but we may have something here. Will update you guys if there is any progress on this.

**Comment by sameersbn** [comment]
The assets can now be compiled at build time. The referenced commit does this. You should now have much faster container startup time.

**Comment by electricmonk** [comment]
Hmmm
My tests fail against `latest` (but pass against `8.0.5`). Apparently, cloning via HTTP (didn't try ssh as my tests currently use HTTP cloning) reports the repo is not found. When I query the Gitlab server via web or API, it DOES report that the repo exists.

(OS X 10.10.5, boot2docker)

```
  % git clone http://root:5iveL\!fe@192.168.59.103:10080/root/a-repo-1444990833566.git                                                                                                               !11081
Cloning into 'a-repo-1444990833566'...
remote: Not Found
fatal: repository 'http://root:5iveL!fe@192.168.59.103:10080/root/a-repo-1444990833566.git/' not found
```

**Comment by sameersbn** [comment]
@electricmonk fixed my PR #468

**Comment by electricmonk** [comment]
@sameersbn awesome. Test now runs in just over 60 seconds. It could run even faster if you could also run the database migration during build. Do you think that would be possible? :)

**Comment by ninja-** [comment]
:+1: :smile:

**Comment by sameersbn** [comment]
@electricmonk that is not possible. database migration requires a database connection which is a runtime thing.

**Comment by electricmonk** [comment]
@sameersbn hmm. Do you mean to create tables, insert initial data, stuff like that, right? makes sense.
Maybe some way to deliver a default setup of Gitlab + Redis + Postgress (like your compose file) which could point to a Postgress image on which the schema already exists? or do Gitlab change the schema often?

**Comment by sameersbn** [comment]
schemas change with every releases. using pre-initialized data volumes like you mentioned is one option for you use case to speed up the tests.

**Comment by sameersbn** [comment]
but i believe the bulk of that startup time would be attributed to gitlab and its components starting up. migration might not take that long.

**Comment by electricmonk** [comment]
I think it's ~10 seconds. Not sure if it's worth it. Oh well. Thanks!
