### ISSUE TITLE
unable to set OAUTH_ENABLED

### ISSUE THREAD

**Issue by mlewe** [sameersbn/docker-gitlab#463]
Currently, it is not possible to set OAUTH_ENABLED to false if settings for an oauth provider are provided.

However, this would be desirable if one wants to disable oauth login, while still providing the possibility of importing repositories from GitHub, Bitbucket and GitLab.com.

**Comment by sameersbn** [comment]
oh yeah.. thats a mistake. will fix it soon.

**Comment by mlewe** [comment]
Thanks for the quick fix.
Great work! :+1:
