### ISSUE TITLE
Enabling HTTPS without redirecting

### ISSUE THREAD

**Issue by dg-ratiodata** [sameersbn/docker-gitlab#464]
### Background

I've some troubles to get gitlab-ci-runner connect to gitlab using docker-gitlab. I'm quite sure, that's a problem with gitlab-ci-runner or even golang:

* https://github.com/golang/go/issues/12910
* https://gitlab.com/gitlab-org/gitlab-ci-multi-runner

So see this background information just as an head-up for you.

### Work Around

I think I'm going to bind mount a working configuration file via `-v` into docker-gitlab

### Request for Comments

It would be helpful, to have an environment variable which makes it possible to make nginx listen both on 80 and 443 without redirecting from 80 to 443 - at least for debugging and working around problems as temporary solution.

**Comment by 18601673727** [comment]
After saw your issue I‘m so doubt to use this project.

1. Are you enable SSL for your `gitlab`? 
2. How do you install your `gitlab-ci-runner`, maybe [this](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/master/docs/install/docker.md#docker-image-installation-and-configuration)?

**Comment by sameersbn** [comment]
@dg-ratiodata please provide more details about your setup and your issue. Please refer to the issues section of the readme and provide all the relavant informaton.

I use Gitlab with HTTPS and have no issues using gitlab-ci-multi-runner. 

@18601673727 Gitlab Inc. makes are docker image and is available at https://hub.docker.com/r/gitlab/gitlab-ce/.

**Comment by sameersbn** [comment]
@dg-ratiodata btw, you can override the default nginx configs with your own. see https://github.com/sameersbn/docker-gitlab/issues/51#issuecomment-41369496

Refer to #11 for additional information

**Comment by dg-ratiodata** [comment]
### Preface

I described the issue in more detail here https://github.com/golang/go/issues/12910. As said before and because of https://github.com/sameersbn/docker-gitlab/issues/464#issuecomment-147930784 I want to point out, that I think it's NOT an issue with https://github.com/sameersbn/docker-gitlab/, but more a problem of https://gitlab.com/gitlab-org/gitlab-ci-multi-runner or even https://gitlab.com/golang/go. 

!!!
I'm quite happy with https://github.com/sameersbn/docker-gitlab/. It's nice to use, nice to configure and run! Thanks for your afford to make gitlab easy to "install".
!!!

@sameersbn Thanks for the information about overwriding the nginx configuration. I really appreciate that. As work around I am going to provide access to :80 and :443 without redirecting users from :80 to :443.

### Details

I use a certificate with such a chain of trust:

~~~
Root-CA
  Sub-CA
     Sub Sub-CA
       Sub Sub Sub-CA
         Server-CRT
~~~

Serving the certificate chain via webserver makes `gitlab-ci-runner` fail on `register` and each other request `https://` to gitlab.

Served Chain.
~~~
  Sub-CA
     Sub Sub-CA
       Sub Sub Sub-CA
~~~

It fails with an encoding/asn.1-error.

### Conclusion

I think it's a problem with parsing the certificate chain. Maybe even caused by a bug in golang. I'm on the way to provide a docker image with a similar setup for the guys at https://github.com/golang/go/.

### Information
#### Docker Version

~~~
Client:
Version:      1.8.1
API version:  1.20
Go version:   go1.4.2
Git commit:   d12ea79
Built:        Thu Aug 13 02:19:43 UTC 2015
OS/Arch:      linux/amd64

Server:
Version:      1.8.1
API version:  1.20
Go version:   go1.4.2
Git commit:   d12ea79
Built:        Thu Aug 13 02:19:43 UTC 2015
OS/Arch:      linux/amd64
~~~

#### Distribution
RHEL 7

#### Docker run

~~~
/usr/bin/docker run --rm --name gitlab1 -p 443:443 -p 80:80 -p 10022:22 -v /srv/machines/gitlab/storage:/home/git/data -v /etc/machines/gitlab/config/gitlab-ssl.conf:/var/cache/gitlab/config/nginx/gitlab-ssl -v /etc/machines/gitlab/ssl/:/etc/ssl/gitlab/ --env-file=/etc/machines/gitlab/environment.db localhost:5000/sameersbn/gitlab:8.0.4
~~~

**Comment by sameersbn** [comment]
@dg-ratiodata thanks for the information. I am not really familiar with this issue and/or the possible resolution. If you come across something that can be made part of this image to resolve the issue, then please do let me know.

**Comment by dg-ratiodata** [comment]
Yeah, I will do. But in the meantime I will try the Gitlab image directly from GitLab... Although your's work like a charm, but I saw an option to run both HTTP and HTTPS, maybe I can work around "my" problem. 

One other question: What CI solution do you use with Gitlab? 

After reading the gitlab-ci-runner-issue tracker it seems to me, that they are a little bit understaffed: Many issues comming with 0.6.0 but only one developer working on that. 

Unfortunately Gitlab Integration of Drone CI seems to be broken (for some users) and this part of drone ci seems to be maintainer-less - at least this is what @bradrydzewski wrote on gitter.im.

**Comment by sameersbn** [comment]
@dg-ratiodata I use GitLab CI itself.

BTW, i use https with my GitLab installations and have no issues running the runner. As you rightly pointed this has something to do with the certificate chains.

**Comment by dg-ratiodata** [comment]
What do you use as `executor`? `"docker"`? If yes via `dind` or via `-v /var/lib/docker:/var/lib/docker`? Sorry for asking so much, but having someone in reach with some experience is quite helpful if you're a noob in that area.

**Comment by sameersbn** [comment]
@dg-ratiodata i use the `shell` executor for my needs.
But have tested the `docker` executor by exposing the docker socket to the container. see https://github.com/sameersbn/docker-gitlab-ci-multi-runner/issues/5 for additional info

**Comment by dg-ratiodata** [comment]
Thanks for sharing that information. :-)

**Comment by sameersbn** [comment]
closing issue. reopen if required
