### ISSUE TITLE
Add an option to "set_real_ip_from" in nginx config in case of reverse proxy

### ISSUE THREAD

**Issue by LordFPL** [sameersbn/docker-gitlab#466]
Hello,

I'm using your version of Gitlab from a long time now, and i'm always do a complete rebuild to do one simple thing : add lines in "gitlab" config of nginx in server part with

```
...
  ## Individual nginx logs for this GitLab vhost
  access_log  {{GITLAB_LOG_DIR}}/nginx/gitlab_access.log;
  error_log   {{GITLAB_LOG_DIR}}/nginx/gitlab_error.log;

  ## Manual add of my reverse proxy to have real source ip in logs
  set_real_ip_from XX.XX.XX.XX/16;
  set_real_ip_from YY.YY.YY.YY;
  set_real_ip_from ZZ.ZZ.ZZ.ZZ;
  real_ip_header X-Forwarded-For;
...
```

Maybe i'm not the only one in this case, and it could be interesting to add a var for that ? Something like NGINX_SET_REAL_IP_FROM=(XX.XX.XX.XX/16 YY.YY.YY.YY ZZ.ZZ.ZZ.ZZ). And following the array with some ${NGINX_SET_REAL_IP_FROM[@]}... or anything else...

I'm not very "clean" on doing shell script... so i don't know how you want to add this (if you want to add this ! ;)), but i can try a dirty PR :)

**Comment by sameersbn** [comment]
@LordFPL  you can override the default nginx configs with your own. see https://github.com/sameersbn/docker-gitlab/issues/51#issuecomment-41369496

Refer to #11 for additional information

**Comment by LordFPL** [comment]
Thx for your answer, but if i understand well, this is already what i do when i edit files under assets/config/nginx.
I will continue, no problem :)

**Comment by sameersbn** [comment]
@LordFPL Using this method you dont have to rebuild the image. you only edit the nginx config and place them at `config/nginx/` in the data volume. When the container is started it will see that you have specified your own nginx config and will override the default with yours. see https://github.com/sameersbn/docker-gitlab/blob/master/entrypoint.sh#L370-L379

**Comment by LordFPL** [comment]
Thank you very much for this clarification, I did not in fact understand correctly ... your solution is exactly what I was looking for (I hope at least this ticket serve others who, like me, done a search on "set_real_ip_from ").

Thx again and again :-)

**Comment by sameersbn** [comment]
keep in mind that when the base nginx template changes, you will need to update your template as well.
