### ISSUE TITLE
Error 500 when trying to import a project from GitHub

### ISSUE THREAD

**Issue by maximino** [sameersbn/docker-gitlab#469]
First of all, wonderful work done here with this project.

I was wondering if someone has encountered this error while trying to import projects from GitHub, I'm being frustrated with this issue and not sure why I can't make it work, any pointers for help will be greatly appreciate it.

```
Filter chain halted as :github_auth rendered or redirected
Completed 302 Found in 38ms (ActiveRecord: 2.5ms)
Started GET "/import/github/callback?code=[FILTERED]" for 127.0.0.1 at 2015-10-17 20:22:04 +0000
Processing by Import::GithubController#callback as HTML
  Parameters: {"code"=>"[FILTERED]"}
Completed 500 Internal Server Error in 42ms (ActiveRecord: 2.5ms)

Faraday::Error::ConnectionFailed (getaddrinfo: Name or service not known):
  lib/gitlab/github_import/client.rb:27:in `get_token'
  app/controllers/import/github_controller.rb:8:in `callback'
```

I have set my `OAUTH_GITHUB_API_KEY` and `OAUTH_GITHUB_APP_SECRET` *environment variables*, and also have tried instantiating the `OAUTH_ENABLED` variable to `true` and the `OAUTH_AUTO_SIGN_IN_WITH_PROVIDER` with the `github` value. But so far I haven't been able to get through a 500 error page.

I'm using the `8.0.5` `sameersbn/docker-gitlab` version.

Thanks in advance.

**Comment by sameersbn** [comment]
@maximino The message `Faraday::Error::ConnectionFailed (getaddrinfo: Name or service not known):` means that the DNS resolution is not happening in the container. Please check your DNS addresses configured on the container. You can override the defaults using `--dns` flag on the `docker run` line.

However, I am trying to check if the import from GitHub is working. So far, seems to be broken. Checking further.

**Comment by sameersbn** [comment]
@maximino the import works. only thing you might want to do is, import each project individually instead of hitting "Import All". While the "Import All" feature does work, I would suggest manually import each project individually, wait for the import to finish before importing the next. You may decide to choose "Import All", that's your choice.

**Comment by maximino** [comment]
@sameersbn Thanks for the prompt reply, I just got into the container and was able to ping google and github from in there:

```
synology> docker exec -it synology-gitlab bash
ERRO[0000] Unable to connect to local syslog daemon     
root@synology-gitlab:/home/git/gitlab# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:12  
          inet addr:172.17.0.18  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:12/64 Scope:Link
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:236212 errors:0 dropped:0 overruns:0 frame:0
          TX packets:158871 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:18631918 (18.6 MB)  TX bytes:47638265 (47.6 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:32 errors:0 dropped:0 overruns:0 frame:0
          TX packets:32 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2240 (2.2 KB)  TX bytes:2240 (2.2 KB)

root@synology-gitlab:/home/git/gitlab# ping google.com
PING google.com (74.125.227.67) 56(84) bytes of data.
64 bytes from qro01s11-in-f3.1e100.net (74.125.227.67): icmp_seq=1 ttl=57 time=8.27 ms
64 bytes from qro01s11-in-f3.1e100.net (74.125.227.67): icmp_seq=2 ttl=57 time=6.39 ms
64 bytes from qro01s11-in-f3.1e100.net (74.125.227.67): icmp_seq=3 ttl=57 time=9.18 ms
64 bytes from qro01s11-in-f3.1e100.net (74.125.227.67): icmp_seq=4 ttl=57 time=11.2 ms
64 bytes from qro01s11-in-f3.1e100.net (74.125.227.67): icmp_seq=5 ttl=57 time=8.75 ms
^C
--- google.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4007ms
rtt min/avg/max/mdev = 6.395/8.769/11.246/1.564 ms
root@synology-gitlab:/home/git/gitlab# ping github.com
PING github.com (192.30.252.129) 56(84) bytes of data.
64 bytes from github.com (192.30.252.129): icmp_seq=1 ttl=52 time=84.7 ms
64 bytes from github.com (192.30.252.129): icmp_seq=2 ttl=52 time=81.0 ms
64 bytes from github.com (192.30.252.129): icmp_seq=3 ttl=52 time=83.8 ms
64 bytes from github.com (192.30.252.129): icmp_seq=4 ttl=52 time=81.8 ms
```

So I guess the DNS resolution is working OK.

As for your other comment, I don't see where the "Import All" option is, probably because I don't get that far in the process. The error 500 I get is immediately after I hit the GitHub button from the "Import project from" section, inside the "New Project" GitLab form.

![screenshot 2015-10-18 12 13 39](https://github-cloud.s3.amazonaws.com/assets/647989/10565246/d11f149e-7591-11e5-82e4-0acd18fa5a4f.png)

**Comment by sameersbn** [comment]
the import all option is available once you click the "GitHub" bottom that is seen in the screenshot.

**Comment by maximino** [comment]
Hi @sameersbn,

Thanks for the feedback, it probably was a bug in the `8.0.5` version. Just upgraded over the weekend to the `8.2.2` version and it worked flawlessly.

Closing this now!
