### ISSUE TITLE
remote:Not Found when https cloning

### ISSUE THREAD

**Issue by urquilla** [sameersbn/docker-gitlab#470]
I recently upgraded to 8.0.5 but when trying to clone/pull/fetch projects through https I received the following message:

    git clone https://example.com:1090/bint-group/project1.git
    Cloning into 'project1'...
    Username for 'https://example.com:1090': urquilla
    Password for 'https://example.com:1090': 
    remote: Not Found
    fatal: repository 'https://example.com:1090/bint-group/project1.git/' not found

It happened with all the projects, but didn't when cloning through ssh.

What I could found at the logs was at the production.log and just:

    Started POST "/ci/api/v1/builds/register.json" for 127.0.0.1 at 2015-10-18 06:56:17 -0600
    Started POST "/ci/api/v1/builds/register.json" for 127.0.0.1 at 2015-10-18 06:56:20 -0600
    Started GET "/bint-group/project1.git/info/refs?service=git-upload-pack" for XXX.XXX.XX.X at 2015-10-18 06:56:20 -0600
    Started POST "/ci/api/v1/builds/register.json" for 127.0.0.1 at 2015-10-18 06:56:23 -0600
    Started POST "/ci/api/v1/builds/register.json" for 127.0.0.1 at 2015-10-18 06:56:26 -0600
    Started GET "/bint-group/project1.git/info/refs?service=git-upload-pack" for XXX.XXX.XX.X at 2015-10-18 06:56:28 -0600

As a workaround downgrading to 8.0.4 immediately fixed the issue.
Where could I search for more clues on this?

**Comment by Zenithar** [comment]
Same problem for me.

**Comment by knight42** [comment]
+1 same problem here. I have rolled back to 8.0.4-1.

**Comment by sameersbn** [comment]
Just checked this on a production system running `quay.io/sameersbn/gitlab:8.0.5` and had no issues cloning the repo using the https:// url. This could be an issue with the load balancer. But you can try looking at the logs on `/var/lib/gitlab/` to see if you notice anything in there.

**Comment by mikew** [comment]
I'm seeing this on 8.0.5 as well, our docker-gitlab is proxied behind an HTTPS nginx container, could that be the issue?

**Comment by sameersbn** [comment]
@mikew i do the same without problems. Are you using a relative_url by any chance as that can cause issues,

**Comment by mikew** [comment]
Nope, no `relative_url` stuff here.

**Comment by mikew** [comment]
Are you aware of the changes to [nginx.conf](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-cookbooks/gitlab/templates/default/nginx-gitlab-http.conf.erb)?

**Comment by mikew** [comment]
@sameersbn no clue how, but my `gitlab:8.0.5` has `gitlab-git-http-server 0.3.0`, which is causing this issue.

**Comment by sameersbn** [comment]
@mikew gitlab gitlab-git-http-server `0.3.0` is not compatible with GitLab `8.0.x`. Please see the changelog https://gitlab.com/gitlab-org/gitlab-git-http-server/blob/master/CHANGELOG

**Comment by sameersbn** [comment]
Oh sorry something is a miss.

**Comment by sameersbn** [comment]
can you guys try with `8.0.5-1`.. Build should be ready in a couple of minutes.

**Comment by knight42** [comment]
@sameersbn It works like a charm now :+1: What happened?

**Comment by sameersbn** [comment]
After the `GITLAB_GIT_HTTP_SERVER_VERSION` variable was added and fixed to `0.2.14`, i forgot to make a release.

**Comment by ithiru** [comment]
Thanks a lot ! I was pulling my hair for couple of hours

**Comment by mikew** [comment]
@sameersbn still not seeing `8.0.5-1` on [the tags page](https://hub.docker.com/r/sameersbn/gitlab/tags/)

**Comment by fernandoneto** [comment]
@mikew 
`docker pull quay.io/sameersbn/gitlab:8.0.5-1`

**Comment by sameersbn** [comment]
@mikew something wrong with quay.io. the pull will work.

**Comment by Sundypha** [comment]
@sameersbn `8.0.5-1` works like a charm :thumbsup:

**Comment by urquilla** [comment]
Just to report back, 8.1.0-1 working perfectly here

**Comment by urquilla** [comment]
Thanks!
