### ISSUE TITLE
https redirect, bad port number

### ISSUE THREAD

**Issue by kesopeso** [sameersbn/docker-gitlab#471]
Hi...

I'm having trouble with http to https redirect. I think that config is not written properly (or maybe I'm missing something). Anyway... when I try to access gitlab with https everything is OK, but when I try it from http, redirect to https doesn't work. The problem is that the port number doesn't get changed.... so when i visit http://my.gitlab.host:10080, I get redirected to https://my.gitlab.host:10080. It should however redirect me to https://my.gitlab.host:10443.

I checked the file "/assets/config/nginx/gitlab-ssl", line 59:
return 301 https://$host:{{GITLAB_PORT}}$request_uri;
... which compiles to:
return 301 https://$host:10080$request_uri;
... instead it should compile to (imo):
return 301 https://$host:10443$request_uri;

Am I doing something wrong?

**Comment by kesopeso** [comment]
Nevermind, I figured it out... I just need to set GITLAB_PORT=10443 and add port entry 10443:443 in docker-compose.yml

**Comment by sameersbn** [comment]
glad that you resolved the issue.

**Comment by nicolasgoudard** [comment]
The port number 10080 is considered as unsafe by web browers, you should use change the port number to another that works, sample 11080. It works for me
