### ISSUE TITLE
where do i configure gitlab-ci?

### ISSUE THREAD

**Issue by babatundebusari** [sameersbn/docker-gitlab#472]
I see gitlab-ci is now integrated into gitlab 8, but no mention of gitlab-ci setup with this docker container repo.

Anyone here have some help on how to set this up?

**Comment by sameersbn** [comment]
If you are migrating from GitLab CI to the Gitlab 8.0, then please refer to the migration document https://github.com/sameersbn/docker-gitlab/blob/master/CI_MIGRATION.md

If you were not using GitLab CI before and want to begin using the integrated CI, then please refer to the GitLab documentation.

**Comment by babatundebusari** [comment]
I am not migrating actually
Setting up a new gitlab instance

#2 Also is it possible to have redis internal instead of the external configuration that comes with your container?

Thanks

**Comment by sameersbn** [comment]
no internal redis.

**Comment by babatundebusari** [comment]
What about the previous question about gitlab-ci environment variables to setup as described in my previous message?

Thanks

**Comment by sameersbn** [comment]
There are only two env params with respect to CI

 - GITLAB_NOTIFY_ON_BROKEN_BUILDS
 - GITLAB_NOTIFY_PUSHER

You can find the details here https://github.com/sameersbn/docker-gitlab#available-configuration-parameters

**Comment by babatundebusari** [comment]
with new gitlab release can one have ci on another subdomain like i described above(seems you didn't see that part)?
 - gitlab on gitlab.example.com
 - ci ci.example.com
with current latest release?

Thanks

**Comment by sameersbn** [comment]
Prior to 8.x.x, GitLab and CI were separate packages and typically users would host them on separate sub-domains. Now they are one, so you don't have to create a separate sub-domain, the CI feature is available at the `/ci` path of GitLab. To make it easier for existing users to continue using their runners without changing the CI server path you have to option of creating a redirection. This is available in the image as the variable `GITLAB_CI_HOST`. You can use it, but it only means that there will be redirections  occurring before your runners can reach the CI server
