### ISSUE TITLE
Asset creation

### ISSUE THREAD

**Issue by ulrichSchreiner** [sameersbn/docker-gitlab#476]
hi,

we are using your image to run our company wide gitlab installation. We have a custom Dockerfile with a "FROM" clause to derive from yours and in our Dockerfile we add some custom CSS/Images to gitlab so the installation meets our company's Look&Feel.

With your latest optimization to compile the assets in your Build, our assets are ignored now. To work around this problem, i put this line at the end of our Dockerfile:

```
RUN sudo -HEu ${GITLAB_USER} bundle exec rake assets:clean assets:precompile >/dev/null 2>&1
```

Is this the correct run-command? Are there better ways to re-compile the assets?

**Comment by sameersbn** [comment]
@ulrichSchreiner That should be fine. Do you see any issues?

**Comment by ulrichSchreiner** [comment]
Running my local tests with the current base image this command seems to work as expected. No issues found until now ...

I will close this issue. Perhaps you can document this new behaviour somewhere; i don't know if others will have the same problem when patching/changing resources of gitlab in their dockerfiles.
