### ISSUE TITLE
GitLab 8.1 is out

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [sameersbn/docker-gitlab#478]
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CHANGELOG

**Comment by okaufmann** [comment]
Is there already a date this will be available? @sameersbn

**Comment by sameersbn** [comment]
build should be ready in a couple minutes.

**Comment by okaufmann** [comment]
That was quick! Thanks you !

**Comment by outcoldman** [comment]
For some reason registry does not have 8.1.0 tag. Is it a known issue?

**Comment by okaufmann** [comment]
@outcoldman no bug it's now builded with quay.io so you have to take this one `quay.io/sameersbn/gitlab:8.1.0`. More under: https://github.com/sameersbn/docker-gitlab#installation
