### ISSUE TITLE
After "docker-compose up", http://localhost:10080 refuses my connection

### ISSUE THREAD

**Issue by KurtRMueller** [sameersbn/docker-gitlab#479]
```
curl localhost:10080                                                                                                                                                                               
curl: (7) Failed to connect to localhost port 10080: Connection refused
```

Hey all,

I just pulled down the compose yaml listed in the [Quick Start](https://github.com/sameersbn/docker-gitlab#quick-start) and ran `docker-compose up` after generating a secret key. However, after pointing my browser to localhost:10080, I get a connection refused error.

I'm pretty new to docker (as In, I installed it today). How do I go about diagnosing/debugging this issue? Any help is appreciated. Thanks all.

Kurt

**Comment by mikew** [comment]
are you using OSX?

**Comment by KurtRMueller** [comment]
Yes.

**Comment by mikew** [comment]
Make sure to use the IP of your Docker VM. If you're using docker-machine, try this:

```bash
open http://$(docker-machine ip dev):10080
```

**Comment by KurtRMueller** [comment]
Yes! This worked for me. Thank you.

**Comment by sameersbn** [comment]
@KurtRMueller thanks for helping out. Much appreciated :+1:
