### ISSUE TITLE
port 80 added instead of 443 on uploads/ URL

### ISSUE THREAD

**Issue by ldgeo** [sameersbn/docker-gitlab#482]
Hello, 
after upgrade from  8.0.5-1 to 8.1.0-2  i have bad urls only on "uploads" links: 

*GET https://www.mydomain.net:80/git/uploads/user/avatar/32/8895057.jpg net::ERR_SSL_PROTOCOL_ERROR*

- GITLAB_HTTPS is set to 'true'
- GITLAB_PORT is set to 443
- My apache proxy has those lines : 
```
   RequestHeader set X-Forwarded-Ssl on
   RequestHeader set X_FORWARDED_PROTO 'https'
```
Any ideas why the port 80 is added while settings are on 443 ?

**Comment by ldgeo** [comment]
ok seems to be fixed after "rake assets:clean assets:precompile cache:clear RAILS_ENV=production"
closing...

**Comment by sameersbn** [comment]
hmmm... thats weird
