### ISSUE TITLE
CI migration guide: 8.1.0-2 doesn't have ci:migrate

### ISSUE THREAD

**Issue by danshaffer** [sameersbn/docker-gitlab#484]
In step 5 of the CI migration guide (https://github.com/sameersbn/docker-gitlab/blob/master/CI_MIGRATION.md), you suggest upgrading to gitlab:8.1.0-2, then running `app:rake ci:migrate`. Unfortunately https://github.com/gitlabhq/gitlabhq/commit/b7b0010f7b9fa70d13d499bf1c4b8c18a695989e removed ci:migrate from 8.1. It seems like we need to upgrade to 8.0.5, run `ci:migrate` and then upgrade beyond that to 8.1+.

**Comment by sameersbn** [comment]
@danshaffer wasn't aware. Thanks for letting me know. Will update the guide in a bit.
