### ISSUE TITLE
entrypoint seems to be failing because true != True

### ISSUE THREAD

**Issue by carukc** [sameersbn/docker-gitlab#485]
This seems strange.... In my docker-compose.yml file I have 

  SMTP_ENABLED: true
  and
  DEBUG_ENTRYPOINT: true

but this translates into 

  SMTP_ENABLED=True
  GITLAB_HTTPS=True

in the environment.  As a result it looks like all of the tests in the entrypoint that test for 'true' are not working.

Has anyone seen this behavior before?

**Comment by carukc** [comment]
using

- SMTP_ENABLED=true

works fine.  I wonder why docker-compose is translating these strings.

**Comment by lazyfrosch** [comment]
@carukc you should maybe quote 'true' since bash has no understanding of a true type, and go might do weird things when converting it to string.

**Comment by sameersbn** [comment]
@carukc Please use the `SMTP_ENABLED=true` syntax or quote the true values as @lazyfrosch indicated. This may be an issue with docker-compose. I am not sure.
