### ISSUE TITLE
Problems with github oauth

### ISSUE THREAD

**Issue by fernandoneto** [sameersbn/docker-gitlab#489]
every time i try to login with github ouath im gettinh this error
![captura de ecra de 2015-10-29 17 42 23](https://cloud.githubusercontent.com/assets/6515784/10827030/7f999c1c-7e64-11e5-9823-3b21ecb99014.png)

i already configure application on github with correct callback and im using this variables in compose file
```bash
OAUTH_ENABLED: 'true'
    OAUTH_BLOCK_AUTO_CREATED_USERS: 'false'
    OAUTH_ALLOW_SSO: 'true'
    OAUTH_GITHUB_API_KEY: xxxxxxxxx
    OAUTH_GITHUB_APP_SECRET: xxxxxxxxxxxxxxxxxxxxxxxxxx
```

if i search in the logs im getting this errors

```
Started POST "/users/auth/github" for 127.0.0.1 at 2015-10-29 17:45:51 +0000
Started GET "/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=00f89bd111cff5cba5b9copu623ce81438245cdd7ciw9ed3" for 127.0.0.1 at 2015-10-29 17:45:52 +0000
Processing by RootController#index as HTML
  Parameters: {"error"=>"redirect_uri_mismatch", "error_description"=>"The redirect_uri MUST match the registered callback URL for this application.", "error_uri"=>"https://developer.github.com/v3/oauth/#redirect-uri-mismatch", "state"=>"00c68bd8215cff5cba5b9cef623ce81438245cdd7fee9ed3"}
Completed 401 Unauthorized in 7ms (ActiveRecord: 1.6ms)
Started GET "/users/sign_in" for 127.0.0.1 at 2015-10-29 17:45:52 +0000
Processing by SessionsController#new as HTML
Completed 200 OK in 323ms (Views: 93.0ms | ActiveRecord: 3.1ms)

```

in github my callback url is 
`https://mydomain.com`
i already try 
`https://mydomain.com/`
`https://mydomain.com/users/oauth/github`
`https://mydomain.com/users`

someone facing the same problem

**Comment by sameersbn** [comment]
> in github my callback url is
> https://mydomain.com

This sounds about right.

I have the following in my yaml file

```yaml
    - OAUTH_ENABLED=true
    - OAUTH_ALLOW_SSO=true
    - OAUTH_BLOCK_AUTO_CREATED_USERS=false
    - OAUTH_GITHUB_API_KEY=xxxxxxxxxxxxxxxx
    - OAUTH_GITHUB_APP_SECRET=yyyyyyyyyyyyyyyyyyyyyyy
```

And it all works. Just need to click the GitHub icon to login.

Please refer to http://doc.gitlab.com/ce/integration/github.html for instruction to register GitLab on GitHub.

**Comment by fernandoneto** [comment]
@sameersbn i already read that documentation, and looks like everything is correct in my side. i just don't know what to do.

**Comment by fernandoneto** [comment]
just find the problem.
problem with `GITLAB_HOST`
im closing it

thanks anyway

**Comment by sameersbn** [comment]
what was the problem with `GITLAB_HOST`?

**Comment by fernandoneto** [comment]
the value of `GITLAB_HOST` is different from the value on callback. 

example:

Callback - http://mydomain.com
GITLAB_HOST - http://medomain.com
