### ISSUE TITLE
--env-file environment file values not resolved while invoking gitlab container

### ISSUE THREAD

**Issue by kalesastha** [sameersbn/docker-gitlab#490]
I've a environment file which contains the gitlab image environment variables. It can't resolve the value inside an container . Given below the content of environment 
```bash
TZ=Asia/Kolkata
REDIS_HOST=localhost
REDIS_PORT=6379  
GITLAB_HOST=localhost.csez.zohocorpin.com  
USERMAP_UID=200
USERMAP_GID=200
NGINX_WORKERS=8 
UNICORN_WORKERS=16 
DB_TYPE=mysql 
GITLAB_BACKUPS=daily 
GITLAB_BACKUP_DIR=/home/git/data/backups 
GITLAB_EMAIL=root@localhost.com 
SMTP_ENABLED=true 
SMTP_HOST=smtp 
SMTP_PORT=25 
GITLAB_HTTPS=true 
SSL_SELF_SIGNED=true 
GITLAB_PORT=443 
DB_TYPE=mysql 
DB_HOST=localhost
DB_NAME=gitlabhq_production 
DB_USER=root
DB_PASS=root
DB_POOL=50 
DB_PORT=3307 
```
The docker command is given below which i executed

sudo docker run --restart=always --name gitlab -d --env-file ./environment sameersbn/gitlab:7.14.3 

Gitlab can't start , it prints as following issue 

ERROR: 
  Please specify the database type in use via the DB_TYPE configuration option.
  Accepted values are "postgres" or "mysql". Aborting...

Docker version 

Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

Docker info 

Containers: 11
Images: 192
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 216
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-37-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 15.58 GiB
Name: kalees-2091
ID: MD3P:6I3Z:JXGI:QAAP:VTTZ:VHCT:M2BD:SF6M:6SMP:YCCU:MJAV:36A4
Username: root
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

Kindly help me to resolve the above error .....

Thanks,
Kaleeswaran N

**Comment by lazyfrosch** [comment]
Have you tried specifying a full path?

It works for me with that...

**Comment by kalesastha** [comment]
Yeah , I tried with both . It's not working for me . Could you please send me how you invoked an container with specifying --env-file option .??

**Comment by lazyfrosch** [comment]
Starting it with a systemd service:

```
[Unit]
Description=Redis cache
BindsTo=docker.service
BindsTo=gitlab-redis.service
After=postgresql@9.4-main.service
 
[Service]
ExecStartPre=-/usr/bin/docker kill gitlab
ExecStartPre=-/usr/bin/docker rm gitlab
ExecStartPre=-/usr/bin/docker pull sameersbn/gitlab
ExecStart=/usr/bin/docker run --name gitlab --link gitlab-redis:redisio --publish x.x.x.x:22:22 --publish 10080:80 --env-file /data/services/gitlab/environment -v /data/services/gitlab/data:/home/git/data sameersbn/gitlab
ExecStop=/usr/bin/docker stop gitlab
 
[Install]
WantedBy=multi-user.target
```
The environments file looks like this:

``` sh
DB_TYPE=postgres
DB_HOST=x.x.x.x
DB_NAME=gitlab
DB_USER=gitlab
DB_PASS=longpassphrase
GITLAB_HOST=git.lazyfrosch.de
GITLAB_TIMEZONE=Berlin
GITLAB_EMAIL=info@lazyfrosch.de
GITLAB_EMAIL_REPLY_TO=info@lazyfrosch.de
GITLAB_HTTPS=true
SSL_SELF_SIGNED=true
GITLAB_EMAIL_ENABLED=true
SMTP_ENABLED=true
SMTP_DOMAIN=lazyfrosch.de
SMTP_HOST=xxx.lazyfrosch.de
SMTP_PORT=25
GITLAB_SECRETS_DB_KEY_BASE=longpassphrase
```

**Comment by kalesastha** [comment]
In which version of docker are you using .? Is this issue related to docker version .?

**Comment by lazyfrosch** [comment]
`Docker version 1.8.3, build f4bf5c7` running on Debian Jessie

The container ran before with 1.7 as well.

Maybe a problem with 1.7.0, but not sure...

**Comment by kalesastha** [comment]
Then, i'll try it with this after upgrading my docker version and let you know the status of the issue . Thanks for your quick reply .

**Comment by sameersbn** [comment]
@kalesastha i believe its because you have trailing spaces in your `envfile`. Please remove all trailing spaces from the `envfile` before retrying.

Also, I could not help but notice that your `DB_HOST` parameter is set to `localhost`. This definitely is not going to work. Setting this value means that the mysql server is running inside the container, which it definitely is not.

Lastly, mysql is not recommended for GitLab. Use at your own risk.

**Comment by sameersbn** [comment]
@kalesastha any updates? can we close this issue?
