### ISSUE TITLE
INFO exited: unicorn (exit status 1; not expected)

### ISSUE THREAD

**Issue by samchristie** [sameersbn/docker-gitlab#492]
I have just started the docker servers for the first time and see the following cycle of error messages. I can't seem to find any more detailed logs regarding the cause of the Unicorn failure.

gitlab_1     | 2015-11-09 22:25:06,770 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1     | 2015-11-09 22:25:15,356 INFO exited: unicorn (exit status 1; not expected)
gitlab_1     | 2015-11-09 22:25:16,360 INFO spawned: 'unicorn' with pid 492
gitlab_1     | 2015-11-09 22:25:18,320 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1     | 2015-11-09 22:25:27,412 INFO exited: unicorn (exit status 1; not expected)
gitlab_1     | 2015-11-09 22:25:28,419 INFO spawned: 'unicorn' with pid 499
gitlab_1     | 2015-11-09 22:25:30,336 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

Suggestions?

**Comment by sameersbn** [comment]
Please make sure the system has more than 1GB of available RAM.

**Comment by samchristie** [comment]
thanks

 

Sam Christie

919-272-1368

**Comment by sameersbn** [comment]
was the issue resolved?

**Comment by samchristie** [comment]
Thanks for your help (and for following up). I am investigating the use of gitlab.com private project support as an alternative. If that doesn’t pan out for me I will enlarge the instance and try again.

 

Sam Christie

919-272-1368

**Comment by sameersbn** [comment]
closing the issue for now. reopen if required.
