### ISSUE TITLE
INFO gave up: nginx entered FATAL state, too many start retries too quickly

### ISSUE THREAD

**Issue by jshridha** [sameersbn/docker-gitlab#498]
It looks like one of the startup scripts has a typo that is creating an extra enabled site in /etc/nginx/sites-enabled/

This is the log info from the nginx supervisor log:
```nginx: [emerg] duplicate upstream "gitlab" in /etc/nginx/sites-enabled/gitlabe:41```

There are two sites enabled in /etc/nginx/sites-enabled
```
ls -l /etc/nginx/sites-enabled/
total 24
-rw-r--r-- 1 root root 9361 Nov 19 13:42 gitlab
-rw-r--r-- 1 root root 9360 Nov 19 13:42 gitlabe
```

**Comment by sameersbn** [comment]
This is very unusual. Can you share a sample `docker run` command or `docker-compose.yml` so that I can reproduce this issue? Also please state the image version in use. Thanks.

**Comment by xvonabur** [comment]
Same problem here. Nginx just doesn't start. Removing gitlabe and restarting nginx via supervisor resolves the issue.

**Comment by sameersbn** [comment]
I tested using 

```bash
wget https://raw.githubusercontent.com/sameersbn/docker-gitlab/master/docker-compose.yml
docker-compose up
```

and faced no such issue, can you please try the same?

Also, why do you have the following mounts in your docker run command

```bash
-v "/mnt/cache/appdata/gitlab-ci-runner/":"/etc/gitlab-runner":rw \
-v "/mnt/cache/appdata/postgresql":"/var/lib/postgresql":rw \
-v "/mnt/user/appdata/gitlab/etc/nginx/sites-enabled":"/etc/nginx/sites-enabled":rw \
```

**Comment by xvonabur** [comment]
I'll try soon to do so with master branch. By the way, master has more commits, than 8.1.4 tag release.

My mounts are just for testing purposes. I've removed them, but it didn't resolve the issue.

**Comment by sameersbn** [comment]
ok.. will try going from 8.1.3 -> 8.1.4

**Comment by sameersbn** [comment]
Here's what i tried.

Launch gitlab 8.1.3 using docker-compose

```bash
wget https://raw.githubusercontent.com/sameersbn/docker-gitlab/8.1.3/docker-compose.yml -O docker-compose.8.1.3.yml
docker-compose -f docker-compose.8.1.3.yml up -d
```

Stop and remove the container.

```bash
docker-compose -f docker-compose.8.1.3.yml stop
docker-compose -f docker-compose.8.1.3.yml rm -f
```

Launch `8.1.4` container

```bash
wget https://raw.githubusercontent.com/sameersbn/docker-gitlab/8.1.4/docker-compose.yml -O docker-compose.8.1.4.yml
docker-compose -f docker-compose.8.1.4.yml up -d
```

I did not see the mentioned issue.

**Comment by xvonabur** [comment]
I'm using primary `docker run`, not `docker-compose`. My target machine runs on [Unraid](http://lime-technology.com/download/). It's NAS software solution based on Slackware 14.1 and has Docker 1.7.1 in it. So far I haven't any problems with it since version 7 of your docker-gitlab repo. Till 8.1.4.

I'll try to reproduce the issue via VM on pure Slackware distro.

**Comment by jshridha** [comment]
My guess is it is caused when modifying the nginx configuration. I have an
environment variable for relative root set. Can you try setting that
variable and rerunning the docker?  The issue may pop up then.

**Comment by sameersbn** [comment]
will check it wilth relative url option. can you delete the gitlabe vhost file and start the container with `-e DEBUG_ENTRYPOINT=1` option. It will print all the commands being executed. This will provide vital info about why and when that file is being generated.

**Comment by sameersbn** [comment]
Checked it wilt relative_url option.. no issue seen.

**Comment by sameersbn** [comment]
also checked with the `latest` tag, still no issues. please run container with `-e DEBUG_ENTRYPOINT=1` and send me the logs.

**Comment by jshridha** [comment]
I'm sending them to your email just in case there's something sensitive in
them. You should have the email shortly.

**Comment by sameersbn** [comment]
Cool.

On Friday 20 November 2015 08:14 PM, Jay wrote:
> I'm sending them to your email just in case there's something sensitive in
> them. You should have the email shortly.
>
> On Fri, Nov 20, 2015 at 9:43 AM, Sameer Naik <notifications@github.com>
> wrote:
>
>  > also checked with the latest tag, still no issues. please run container
>  > with -e DEBUG_ENTRYPOINT=1 and send me the logs.
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/sameersbn/docker-gitlab/issues/498#issuecomment-158419189>
>  > .
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-gitlab/issues/498#issuecomment-158419583>.
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com

**Comment by sameersbn** [comment]
Found the issue. Please test with the `latest` tag once the build is ready. watch for the build status here https://hub.docker.com/r/sameersbn/gitlab/builds/. It could take a while of the build.

**Comment by xvonabur** [comment]
Yep. The issue is solved! :thumbsup: Thanks!

**Comment by jshridha** [comment]
It's working for me too. Thanks for the quick fix!

**Comment by sameersbn** [comment]
@jshridha thank you for effort in help fix and squash this bug.
