### ISSUE TITLE
Build trigger not working if branch name contains /

### ISSUE THREAD

**Issue by setiseta** [sameersbn/docker-gitlab#502]
Hi, I'm using release branches named for example release/1.0
If i want trigger a build over curl with the build triggers i get this command
```
curl -X POST \
     -F token=... \
     http://git.local/ci/api/v1/projects/21/refs/REF/trigger
```
If i replace the REF with release/1.0 or with URL encoded release%2F1.0 i get a gitlab 404 message.

Hopefully someone can help me out here.
I think it should be a nginx setting. But I'm not sure.
Thx for help

**Comment by lazyfrosch** [comment]
Are you sure this is a problem with the Docker container??

**Comment by setiseta** [comment]
No not really.
I think it could be an nginx thing. But im not sure.
Just started to search for help.

Does it work for you?

**Comment by lazyfrosch** [comment]
I'm not using CI currently, but since nginx does not translate URLs of some sort, it sounds like a problem in the CI component. Maybe they never tested slashed branches...

**Comment by sameersbn** [comment]
@setiseta for the sake of testing can you try create a release branch without the `/` and check if it works? I will try to check it locally as well.

**Comment by setiseta** [comment]
Its working if I'm triggering the master.
But at the moment I think its a gitlab problem, don't you?

**Comment by sameersbn** [comment]
Yes.. i think its a gitlab issue too. wanted to be sure.
Can you report the issue upstream?

**Comment by setiseta** [comment]
Its reported there: https://gitlab.com/gitlab-org/gitlab-ce/issues/3174
It seems that ther will be a change in the future.

**Comment by sameersbn** [comment]
:+1:
