### ISSUE TITLE
Upgrade fails from 7.8.1 to 8.2.0

### ISSUE THREAD

**Issue by liquid** [sameersbn/docker-gitlab#504]
I have been running GitLab 7.8.1 and wanted to upgrade to 8.2.0 but it's failing to start. Am getting the following info from the logs:

```
Initializing logdir...
Initializing datadir...
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database
Configuring gitlab::redis
Configuring gitlab::secrets...
Configuring gitlab::sidekiq...
Configuring gitlab::unicorn...
Configuring gitlab::timezone...
Configuring gitlab::ci...
Configuring gitlab::lfs...
Configuring gitlab::project_features...
Configuring gitlab::smtp_settings...
Configuring gitlab::oauth...
Configuring gitlab::ldap...
Configuring gitlab::backups...
Configuring gitlab-shell...
Configuring nginx...
Configuring nginx::gitlab...
Migrating database...
rake aborted!
NoMethodError: undefined method `*' for nil:NilClass
/home/git/gitlab/config/initializers/session_store.rb:19:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `block in load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:648:in `block in load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/notifications.rb:161:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:647:in `load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:611:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:611:in `block in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:44:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:54:in `run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:300:in `initialize!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `method_missing'
/home/git/gitlab/config/environment.rb:5:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:276:in `require_environment!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:405:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

Am using the following config parameters (read from an `--env` file during `docker run`):

```
GITLAB_HOST=my.own.host
GITLAB_EMAIL=notify@my.own.host
GITLAB_SECRETS_DB_KEY_BASE=IDIDTHISUSINGTHERECOMMENDEDTOOL
GITLAB_SHELL_SSH_PORT=8022
SMTP_USER=me@iwonttellyou.com
SMTP_PASS=IWONTSHARETHIS
UNICORN_WORKERS=1
DB_NAME=gitlabhq_production
DB_USER=gitlab
DB_PASS=password
SIDEKIQ_CONCURRENCY=5
```

Does this have anything to do with the new `GITLAB_SECRETS_DB_KEY_BASE` that was introduced since the version I used previously. I haven't found a relevant issue in the GitLab issue tracker so I am wondering whether this is caused by the increased complexity of the docker container...

Any help would be appreciated, thank you in advance

**Comment by liquid** [comment]
Also, the container is being run linked to a `sameersbn/postgresql:9.1-1` database and using the following options:
`
-d --link postgresql:postgresql --link redis:redisio --env-file /home/git/gitlab/docker.env -p 8081:80 -p 8022:22 -v /home/git/gitlab/data:/home/git/data`

**Comment by xueshanf** [comment]
Not sure if it helps, but I was able to upgrade with this path:
6.9.2 -> 7.14.3 -> 8.1.4- > 8.2.0

You might try to upgrade to 7.14.3 first, at least.

**Comment by sameersbn** [comment]
I have not tried it but I think what @xueshanf suggests is correct.

You may have to upgrade to `7.14.x` before migrating to `8.0.x` and then to the most recent version.
GitLab made some major changes in the `8.0.x` release with the additional requirement that you could only upgrade to it from `7.14.x`.

I don't know if you can go directly from `7.14.x` to `8.2.0`. I will check and let you know.

**Comment by sameersbn** [comment]
I tried upgrading from `7.8.1` -> `8.2.0` and had no issues at all. I used the sample [docker-compose.yml](https://raw.githubusercontent.com/sameersbn/docker-gitlab/master/docker-compose.yml) for the tests.

You need to follow the `7.8.1` -> `8.0.x` -> `8.2.x` upgrade path only if you were using the GitLab CI container (FMI: https://github.com/sameersbn/docker-gitlab/blob/master/CI_MIGRATION.md).

Assuming that you are not using GitLab CI, I do not see any reason why the migration would fail. All I can suggest is to remove the image and repull from DH. Sometimes the image seems to get corrupted during the pull.

**Comment by liquid** [comment]
You guys are awesome, thank you for such quick response @xueshanf and @sameersbn. Using the suggested upgrade path I am finally running the latest version.

I've been looking at the `CHANGELOG` to find out whether there's something important to do (removal of ENV vars, additional requirements etc) but the required upgrade path was not mentioned. Do you think you could mention these in the future to avoid people having to look at the upstream projects? (Just my $0.02)

Thanks again.

**Comment by sameersbn** [comment]
@liquid did you follow the `7.8.1` -> `8.0.x` -> `8.2.x` upgrade path to resolve the issue? If yes, do you use GitLab CI?

**Comment by liquid** [comment]
@sameersbn I did upgrade via 7.8.1 -> 7.14.3 -> then wen straight to 8.2.0 (I had no CI before and am not using it now either -- although I've read somewhere that CI is now built in?)

**Comment by sameersbn** [comment]
> I did upgrade via 7.8.1 -> 7.14.3 -> then wen straight to 8.2.0

Then I should probably document this in the README. My basic test allowed me to go straight from `7.8.1` -> `8.2.0`. Maybe it causes issues when there are projects in system. Thanks for confirming this.

> although I've read somewhere that CI is now built in?)

Yes, CI is merged into GitLab proper and there is no longer a  separate CI component, its all integrated. You only need to setup runners to complete the CI pipeline.
