### ISSUE TITLE
SSL connection refused

### ISSUE THREAD

**Issue by djskinner** [sameersbn/docker-gitlab#507]
I've had lots of success with docker-gitlab so first of all thanks for all the hard work that has gone into this project.

I'm now trying to get my long running gitlab instance to serve over SSL with SSL termination being provided at the load balancer. However, when a use `GITLAB_HTTPS=true` and `GITLAB_PORT=443` gitlab just refuses to serve anything on port 443 with a `connection refused` error.

Here are some curl requests executed from within the container itself:

```
root@gitlab:/home/git/gitlab# curl http://localhost                             
<html><body>You are being <a href="https://localhost/users/sign_in">redirected</
a>.</body></html>root@gitlab:/home/git/gitlab# curl https://localhost           
curl: (7) Failed to connect to localhost port 443: Connection refused           
root@gitlab:/home/git/gitlab# 
```

Any ideas where I'm going wrong?

**Comment by sameersbn** [comment]
Since you are using a load balancer to add the SSL support, Gitlab will serve requests only on port 80. When a connection is made from the load balancer to the gitlab backend it needs to see the request coming from https. If you are using nginx as the load balancer this can be done using `proxy_set_header X-Forwarded-Proto https;`

Following is the config that i use on my nginx load balancer. Hope you find it useful

```nginx
upstream gitlab {
  server 172.17.0.1:10080 fail_timeout=0;
}

# let gitlab deal with the redirection
server {
  listen 80;
  server_name git.example.com;
  server_tokens off;

  access_log /var/log/nginx/gitlab_access.log;
  error_log /var/log/nginx/gitlab_error.log;

  root /dev/null;
  client_max_body_size 20m;

  location / {
    proxy_read_timeout 300;
    proxy_connect_timeout 300;
    proxy_redirect off;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Frame-Options SAMEORIGIN;
    proxy_pass http://gitlab;
  }
}

server {
  listen 443 ssl spdy;
  server_name git.example.com;
  server_tokens off;

  access_log /var/log/nginx/gitlab_ssl_access.log;
  error_log /var/log/nginx/gitlab_ssl_error.log;

  root /dev/null;
  client_max_body_size 20m;

  ssl on;
  ssl_certificate /etc/nginx/ssl/git.example.com.crt;
  ssl_certificate_key /etc/nginx/ssl/git.example.com.key;
  ssl_verify_client off;

  ssl_ciphers "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 5m;
  ssl_dhparam /etc/nginx/ssl/dhparam.pem;

  add_header Strict-Transport-Security max-age=31536000;

  location / {
    ## If you use https make sure you disable gzip compression
    ## to be safe against BREACH attack.
    gzip off;

    proxy_read_timeout 300;
    proxy_connect_timeout 300;
    proxy_redirect off;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Frame-Options SAMEORIGIN;
    proxy_pass http://gitlab;
  }
}

```

**Comment by djskinner** [comment]
I'm trying to make use of a Rancher load balancer so this could be the issue. I'll try and create an alternative setup using nginx and get back to you.

**Comment by djskinner** [comment]
I've just asked in the forums and apparently the Rancher Load Balancer does set these headers (http://forums.rancher.com/t/load-balancer-set-headers/1048/4)

**Comment by djskinner** [comment]
Let's take the load balance out of the equation. Even if I add the Header I'm still getting connection refused:

```
root@gitlab:/home/git/gitlab# curl --header "X-Forwared-Proto https" https://localhost                                                                          
curl: (7) Failed to connect to localhost port 443: Connection refused           
root@gitlab:/home/git/gitlab# curl --header "X-Forwared-Proto https" https://loc
alhost:80                                                                       
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol  
```

**Comment by sameersbn** [comment]
@djskinner The container will only listen on port 443 if you install the ssl certificates in the container https://github.com/sameersbn/docker-gitlab#installation-of-the-ssl-certificates. When using a load balancer this is not required since the load balancer will proxy SSL requests to the gitlab container over plain http. In short, in your case, the container is only listening on port 80. I think the issue may be because of the use of `localhost` to access the backend container.

P.S. I am using a gitlab container behind and nginx load balancer that adds the SSL support, the config of which I have already shared. I tested the curl command `curl -H "X-Forwarded-Proto: https" http://172.17.0.1:10080/users/signin` and it does not work that way (i am redirected).

**Comment by djskinner** [comment]
Thanks for taking the time to explain this to me. I had read the documents but clearly didn't fully understand. I now have my load balancer running on 443 with HTTPS enabled. The load balancer forwards to port 80. `GITLAB_HTTPS=true` and `GITLAB_PORT=80` and everything is now working as expected. Thanks again!

**Comment by sameersbn** [comment]
You should set GITLAB_PORT to 443 to ensure the https clone urls are right.

On Nov 23, 2015 11:01 PM, "djskinner" <notifications@github.com> wrote:
>
> Thanks for taking the time to explain this to me. I had read the
documents but clearly didn't fully understand. I now have my load balancer
running on 443 with HTTPS enabled. The load balancer forwards to port 80.
GITLAB_HTTPS=true and GITLAB_PORT=80 and everything is now working as
expected. Thanks again!

**Comment by fernandoneto** [comment]
@djskinner did you have sucess?

**Comment by djskinner** [comment]
Not entirely. I changed `GITLAB_PORT` to `443` which makes sense and now gitlab is being served over HTTP. I also opened up HTTP port 80 on the load balancer and requests are successfully being redirected to port 80. However, I am constantly redirected to the login page every time I try to navigate. For example, hit the home page, login and I am shown the dashboard. Then if I click say the Activity page I'm just redirected back to the login page again.

**Comment by djskinner** [comment]
Many of the project avatar images are also broken because the links look like this `<img alt="" class="avatar project-avatar s46" src="http://gitlab.mydomain.com:443/uploads/project/avatar/17/hills-av.jpg">`

**Comment by djskinner** [comment]
The clone URLs look absolutely fine now that I changed `GITLAB_PORT=443`. It's just having to login every time I navigate and some (but not all) of the images trying to load from http rather than https.

**Comment by lazyfrosch** [comment]
In my setup I haven't set any ports via env variables. I'm just adding the forward proto header, and it works fine. Basically the whole site is redirected to https, and that is proxied to gitlab via port 80.

**Comment by djskinner** [comment]
Removing the env variable also works (with the exception of the missing images and constant redirects to the login screen). Interestingly navigations which use XHR are not affected and the profile images are not always served from the wrong URL. For example on a group home page the project avatar images aren't being served properly but if I go into a project that has a broken avatar the image is actually displaying fine on the project home page itself.

**Comment by djskinner** [comment]
Removing and re-adding all the avatar images seems to have fixed them having the wrong (http) URL on the dashboard, which also appears to have fixed the constant redirecting to the login screen. Perhaps it was something to do with HTTP content being served on an HTTPS page?

**Comment by djskinner** [comment]
For anyone else who comes across this, here is my working setup.

I've got the `docker-gitlab` stack up and running over SSL in a Rancher environment using a standard Rancher load balancer.

`docker-gitlab` is simply configured with `GITLAB_HTTPS=true` 

The Load Balancer is configured as follows:

Public Port `443` -> use `SSL` -> forwards to port `80` on `docker-gitlab`
Public Port `80` -> forwards to port `80` on `docker-gitlab`

Opening 80 allows gitlab to redirect HTTP users to HTTPS. If you have any issues with avatar images not displaying and being served over HTTP you will need to remove and re-upload each avatar image.

Thanks to everyone who was so quick to respond and help.

**Comment by lazyfrosch** [comment]
@djskinner :+1:

**Comment by fernandoneto** [comment]
@djskinner if you using rancher ehy dont you use your certeficates in rancher and configure your LB to redirect traffic from 443 to 80 in container ?

**Comment by fernandoneto** [comment]
@djskinner you don need `GITLAB_HTTPS=true`
