### ISSUE TITLE
Not working using overlay-fs

### ISSUE THREAD

**Issue by xeor** [sameersbn/docker-gitlab#509]
Looks like this image is currently broken when using overlayfs. I think its the issue at https://github.com/docker/docker/issues/9572 that is biting.

I tested with 2 different physical hosts, both using overlayfs.

The `.gitkeep` file looks like this; `c---------. 1 root root 0, 0 Nov 23 22:20 /var/lib/docker/overlay/dfd1.../upper/home/git/gitlab/builds/.gitkeep`, and I can't delete it inside the container. It shows up as `??????????? ? ?   ?    ?            ? .gitkeep`.

Pretty sure this is an overlayfs error as the linked issue suggest as well.

I have a bunch of containers running on the same system. Have had problems with socket-files on overlayfs, but not a problem like this.

Last lines when starting using docker-compose.

    gitlab_1     | Initializing logdir...
    gitlab_1     | rm: cannot remove '/home/git/gitlab/builds': Directory not empty
    gitlab_1     | Initializing datadir...
    gitlabtest_gitlab_1 exited with code 0
    Gracefully stopping... (press Ctrl+C again to force)
    Stopping gitlabtest_gitlab_1... error
    Stopping gitlabtest_redis_1... done
    Stopping gitlabtest_postgresql_1... done

**Comment by sameersbn** [comment]
From my understanding this is an issue with overlay and/or docker. There is nothing that can be done in the image to fix this. Only solution i can suggest is switching to another storage driver or wait for the respective project to resolve the issue.

If there is anything that can be done in the image to fix it then please let me know.

**Comment by xueshanf** [comment]
@xeor You probably already know - if you volume-mount  /home/git/data to a host's volume that is a non-overlay file system, such as NFS or ext4, that should work. It is also necessary for data persistence. I use AWS EFS, e.g. run the docker with "-v /efs/gitlab/data:/home/git/data".

**Comment by xeor** [comment]
If I make an image with something like this;

    FROM sameersbn/gitlab:8.2.0
    RUN rm -f /home/git/gitlab/builds/.gitkeep

I am getting 1 step further when starting the image. It now stops at:

    Initializing logdir...
    Initializing datadir...
    rm: cannot remove '/home/git/gitlab/shared/artifacts/tmp/cache': Directory not empty
    rm: cannot remove '/home/git/gitlab/shared/artifacts/tmp/uploads': Directory not empty

Doing the same to them doesn't do it tho, the "fixes" stops after the first `.gitkeep` deletion. 
So, something like;

    FROM sameersbn/gitlab:8.2.0
    RUN rm -rf \
          /home/git/gitlab/builds/.gitkeep \
          /home/git/gitlab/shared/artifacts/tmp/cache/.gitkeep \
          /home/git/gitlab/shared/artifacts/tmp/uploads/.gitkeep \
          /home/git/gitlab/shared/artifacts/tmp

gives this error when building the image.

    rm: cannot remove '/home/git/gitlab/shared/artifacts/tmp/cache': Directory not empty
    rm: cannot remove '/home/git/gitlab/shared/artifacts/tmp/uploads': Directory not empty

Maybe it works cleaning up all this gitkeep files when building on a non-overlay-fs system. I'm yet to try that.. Need to go to work now :)

@xueshanf It's `/home/git/gitlab` that is problematic, I already have `/home/git/data` on a separate volume. `/home/git/gitlab` as I see is used for setup. :/

**Comment by sameersbn** [comment]
@xeor can you try the `latest` tag (after its ready) from DH. It might help getting around this issue.

**Comment by xeor** [comment]
Almost... :)
Now we it is stuck on;

    gitlab_1 | Initializing logdir...
    gitlab_1 | Initializing datadir...
    gitlab_1 | rm: cannot remove '/home/git/gitlab/tmp/cache/assets/production/sass/04bd255ed9d8720c1b707e2e636ebcd28c86429b': Directory not empty
    gitlab_1 | rm: cannot remove '/home/git/gitlab/tmp/cache/assets/production/sass/1b51523bdfc6d43977c2cd4a0d7c8de241bbfdf9': Directory not empty
    gitlab_1 | rm: cannot remove '/home/git/gitlab/tmp/cache/assets/production/sass/4338974cc897dfabf2ee1af035b02a8c15eacf8a': Directory not empty
    gitlab_1 | rm: cannot remove '/home/git/gitlab/tmp/cache/assets/production/sass/657cbba3607ec87b451a52a7814712c3f7759bc5': Directory not empty
    .... a lot of these

This happens with the `sprokets` folders as well as `sass`, and happens more and more everytime I run it;

    $ docker-compose up gitlab | wc -l # 145
    $ docker-compose up gitlab | wc -l # 173
    $ docker-compose up gitlab | wc -l # 201

Removing the `tmp` dir that is mapped to `/home/git/data/tmp` doesnt solve the problem, as it still tries to delete those files.

I guess these files are there for making application startup faster. Don't know why mine is trying to delete them. The data-folder I mounted is from an older version. Is this a part of the upgrade process?

It do look like a fresh installation works fine tho, even if I stop it and start it.


This whole issue looks like a spider-web, there might be more errors. Maybe a warning saying that overlay-fs won't work at the moment is better than trying to solve this?

I will do all the tests you throw at me if you want to do that instead. :)

**Comment by sameersbn** [comment]
> Don't know why mine is trying to delete them

Its because you are using the `GITLAB_RELATIVE_URL_ROOT` option.

**Comment by xeor** [comment]
I see.. Because of https://github.com/sameersbn/docker-gitlab/issues/481. I tested, and as you said, it works without relative url root sat.

I need to have relative path's. So I'll just think I am migrating back to devicemapper with lvm-thin until they fix overlayfs. Or is there anything else you want to try?

**Comment by sameersbn** [comment]
@xeor I can only suggest waiting for docker/overlayfs to resolve this issue :smile:

**Comment by xeor** [comment]
This problem went away when I replaced `xfs` as a backing filesystem for overlay with `ext4` (shows up in docker-info as `extfs`). I did several testing converting the fs back and forth to verify this. All ok now :sunny:

**Comment by sameersbn** [comment]
perfect!
