### ISSUE TITLE
[Discussion] Abusing environment variables?

### ISSUE THREAD

**Issue by cridenour** [sameersbn/docker-gitlab#51]
For the most part, I love the setup you have and am using your redis and mysql dockerfiles as well. So first - thank you for what you do. 

I do worry though that to get all the information gitlab needs into the the container, my `docker run` command becomes 5+ lines long and should the container be forgotten, many of those variables require lots of time to craft again. Perhaps there is a middle ground of using config files from the volume - or config template files from the volume. 

I'm not sure if it's 100% better but when you start to add SSL in - it's going to get worse. I added custom volumes to replace the generated nginx config and so I could add in my SSL certs and it seems more manageable than all environment variables, albeit less flexible.

**Comment by davidwindell** [comment]
Or you can just use tutum ;)
