### ISSUE TITLE
"artifacts" directory is owned by root

### ISSUE THREAD

**Issue by ulrichSchreiner** [sameersbn/docker-gitlab#510]
the `artifacts` directory is created [here](https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/functions#L756) but the directory and its subdirectories are owned by "root" and so storing artifacts with gitlab-ci cannot put there artifacts here (permission denied).

i think you have to do
```
chown -R ${GITLAB_USER}:${GITLAB_USER} ${GITLAB_SHARED_DIR}/artifacts
```

so the git-user can write artifacts.

**Comment by sameersbn** [comment]
thanks for pointing it out. added a temporary fix for now.
Will evaluate the cases and make a proper fix as needed :smile:
