### ISSUE TITLE
Add Parameter DB_TIMEOUT

### ISSUE THREAD

**Issue by mpbzh** [sameersbn/docker-gitlab#514]
I have a Gitlab installation on a Synology DS1515+, which runs pretty well, except in the morning I tend to have 500 errors. Investigating the errors I found the problem to be the database:
`ActiveRecord::ConnectionTimeoutError (could not obtain a database connection within 5.000 seconds (waited 5.001 seconds))`

This probably happens in the night, wenn the NAS does its backup and other tasks, so the machine is slower than usual. As I assume this is a problem of my setup that is not to fix except for upgrading the hardware, it would be great if the database timeout could be raised by the configuration.

**Comment by sameersbn** [comment]
have to tried raising the `DB_POOL` value?

**Comment by mpbzh** [comment]
Not yet. Increased it now and will report back if the problem persists.

Thanks for the hint!

**Comment by mpbzh** [comment]
So far no 500 errors anymore, so I think we can consider this fixed. Thanks!
