### ISSUE TITLE
sed error on gitlab startup

### ISSUE THREAD

**Issue by JrCs** [sameersbn/docker-gitlab#516]
When i start my container i have:
<pre>Nov 27 15:30:52 sd-65534 docker[63801]: Configuring gitlab::database
Nov 27 15:30:52 sd-65534 docker[63801]: sed: -e expression #1, char 21: unknown option to `s'
Nov 27 15:30:52 sd-65534 systemd[1]: gitlab.service: Main process exited, code=exited, status=1/FAILURE</pre>
The problem is that you forget to declare the default values of the new variables (GITLAB_SHARED_DIR, GITLAB_ARTIFACTS_DIR, GITLAB_ARTIFACTS_ENABLED) in the Dockerfile

**Comment by sameersbn** [comment]
@JrCs just checked there is a typo that needs to be fixed.

**Comment by sameersbn** [comment]
fixed the typo. can you please check the `latest` tag once the build is ready. Once you confirm I will make a new point release

**Comment by sameersbn** [comment]
nevermind. i made a point release.

**Comment by JrCs** [comment]
Same error using **latest** tag:
<pre>Nov 28 14:09:29 sd-65534 docker[21806]: Configuring gitlab::database
Nov 28 14:09:29 sd-65534 docker[21806]: sed: -e expression #1, char 21: unknown option to `s'
Nov 28 14:09:29 sd-65534 systemd[1]: gitlab.service: Main process exited, code=exited, status=1/FAILURE</pre>

I thing some variables value are missing

**Comment by sameersbn** [comment]
@JrCs It appears that some character in some value like DB_PASS is confusing `sed`. Please add `DEBUG=true` to the environment of the gitlab container and you will see which sed command is failing.

**Comment by JrCs** [comment]
Found, it's DB_PASS that contain a | (your sed separator). Error will be raised if string contain another char use by sed like: $, ( , ), etc...
Perhaps the best is to use:
```bash
envsubst < template.txt
```
which work even if variables contain specific chars.
But you need to rewrite your templates from {{VAR}} to ${VAR}

**Comment by sameersbn** [comment]
this change looks massive in the way it would alter the setup procedure.
why not just change the password?

**Comment by JrCs** [comment]
I can but if someone define a pass containing things like $ ( ) [ ] | etc... the error will appear.
Perhaps it's better to find a definitive solution ?

**Comment by sameersbn** [comment]
actually in some places the configuration lines are deleted using `sed`, https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/functions#L145 for example. I will however experiment using `envsubst`. I agree it could resolve such issues, i want to be cautions with such changes because it could lead to breakages for existing users.

**Comment by JrCs** [comment]
You can use sed to delete the lines.
But to replace some placeholders it's better to use envsubst

**Comment by JrCs** [comment]
Is it ok to reopen this issue ?

**Comment by JrCs** [comment]
Fixed in #522
