### ISSUE TITLE
gitlab restore issue

### ISSUE THREAD

**Issue by abilashks** [sameersbn/docker-gitlab#519]
Hi we are trying to migrate gitlab to docker. As of now we are using gitlab 8.0.5 version. When we try to backup and restore the gitlab in gitlab docker (quay.io/sameersbn/gitlab:8.0.5) we get the below error.

This will rebuild an authorized_keys file.
You will lose any data stored in authorized_keys file.
Do you want to continue (yes/no)? yes

................................................................................................................................................................................................................................................................................................................................................................................................................................................./home/git/gitlab-shell/lib/gitlab_keys.rb:58:in `split'..: .invalid byte sequence in US-ASCII (ArgumentError)
    from /home/git/gitlab-shell/lib/gitlab_keys.rb:58:in`block (3 levels) in batch_add_keys'
    from /home/git/gitlab-shell/lib/gitlab_keys.rb:57:in `each_line'
    from /home/git/gitlab-shell/lib/gitlab_keys.rb:57:in`block (2 levels) in batch_add_keys'
.   from /home/git/gitlab-shell/lib/gitlab_keys.rb:56:in `open'
    from /home/git/gitlab-shell/lib/gitlab_keys.rb:56:in`block in batch_add_keys'
    from /home/git/gitlab-shell/lib/gitlab_keys.rb:107:in `block (2 levels) in lock'
    from /usr/lib/ruby/2.1.0/timeout.rb:90:in`block in timeout'
.   from /usr/lib/ruby/2.1.0/timeout.rb:33:in `block in catch'
    from /usr/lib/ruby/2.1.0/timeout.rb:33:in`catch'
    from /usr/lib/ruby/2.1.0/timeout.rb:33:in `catch'
    from /usr/lib/ruby/2.1.0/timeout.rb:105:in`timeout'
.   from /home/git/gitlab-shell/lib/gitlab_keys.rb:107:in `block in lock'
    from /home/git/gitlab-shell/lib/gitlab_keys.rb:104:in`open'
    from /home/git/gitlab-shell/lib/gitlab_keys.rb:104:in `lock'
.   from /home/git/gitlab-shell/lib/gitlab_keys.rb:55:in`batch_add_keys'
    from /home/git/gitlab-shell/lib/gitlab_keys.rb:19:in `exec'
.   from /home/git/gitlab-shell//bin/gitlab-keys:23:in`<main>'
......rake aborted!
Errno::EPIPE: Broken pipe
/home/git/gitlab/lib/gitlab/backend/shell.rb:7:in `write'
/home/git/gitlab/lib/gitlab/backend/shell.rb:7:in`puts'
/home/git/gitlab/lib/gitlab/backend/shell.rb:7:in `add_key'
/home/git/gitlab/lib/tasks/gitlab/shell.rake:114:in`block (2 levels) in setup'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/relation/batches.rb:52:in `block (2 levels) in find_each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/relation/batches.rb:52:in`each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/relation/batches.rb:52:in `block in find_each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/relation/batches.rb:126:in`find_in_batches'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/relation/batches.rb:51:in `find_each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/querying.rb:9:in`find_each'
/home/git/gitlab/lib/tasks/gitlab/shell.rake:113:in `block in setup'
/home/git/gitlab/lib/gitlab/backend/shell.rb:167:in`call'
/home/git/gitlab/lib/gitlab/backend/shell.rb:167:in `block in batch_add_keys'
/home/git/gitlab/lib/gitlab/backend/shell.rb:166:in`popen'
/home/git/gitlab/lib/gitlab/backend/shell.rb:166:in `batch_add_keys'
/home/git/gitlab/lib/tasks/gitlab/shell.rake:112:in`setup'
/home/git/gitlab/lib/tasks/gitlab/shell.rake:80:in `block (3 levels) in <top (required)>'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:35:in`block (3 levels) in <top (required)>'
Tasks: TOP => gitlab:shell:setup

Any idea why this error occurs?

**Comment by sameersbn** [comment]
no idea. can you try answering "no" in the prompt above?

**Comment by abilashks** [comment]
when i gave "no" restore exited with a message "Exiting.."

**Comment by xueshanf** [comment]
batch_add_keys has a 300 second timeout lock on the operation, did it take that long for you to hit the timeout error in the stack trace? do you have lots of keys to import? Just a thought.

**Comment by abilashks** [comment]
no it dint take that long for error to occur but we have so many keys to import. any idea how to solve this issue

**Comment by xueshanf** [comment]
Not sure, but this might help you? https://gitlab.com/gitlab-org/gitlab-ce/issues/3822

**Comment by sameersbn** [comment]
@abilashks this could be related to the issue mentioned by @xueshanf 
I am not sure how you should do about resolving it. maybe you will have to upgrade your local installation to a newer gitlab version which resolves this issue and then migrate to the image.

**Comment by Suley** [comment]
we have an old gitlab installation which version is 8.11.5. The installation broke due to hard drive failure. Fortunately , I have backups. 
But I still encounter the same problem. does any one have any idea how to fix this problem? thank you.

**Comment by Suley** [comment]
for anyone who stuck in this error. Set the env of LC_ALL=en_US.UTF-8 fix my problem.
