### ISSUE TITLE
admin settings doesn't work after upgraded to 8.2.2

### ISSUE THREAD

**Issue by chengweiv5** [sameersbn/docker-gitlab#523]
Hi,

I just upgraded my gitlab from 8.0.4 to 8.2.2 and looks great except that the admin settings page doesn't save any change, while it displays all changes saved.

For example, I added my email address to notification email like 'me@chengweiyang.cn' and click `SAVE` the production.log looks like below

```
Started PATCH "/admin/application_settings" for 127.0.0.1 at 2015-12-03 19:48:26 +0800
Processing by Admin::ApplicationSettingsController#update as HTML
  Parameters: {"utf8"=>"[34m~\~S", "authenticity_token"=>"[FILTERED]", "application_setting"=>{"default_branch_protection"=>"2", "default_project_visibility"=>"0", "default_snippet_visibilit>"0", "import_sources"=>["github", "bitbucket", "gitlab", "gitorious", "google_code", "fogbugz", "git"], "version_check_enabled"=>"1", "admin_notification_email"=>"me@chengweiyang.cn", "grav
atar_enabled"=>"1", "twitter_sharing_enabled"=>"0", "default_projects_limit"=>"10", "max_attachment_size"=>"10", "session_expire_delay"=>"10080", "user_oauth_applications"=>"1", "signup_enab
led"=>"0", "signin_enabled"=>"1", "restricted_signup_domains_raw"=>"", "home_page_url"=>"", "after_sign_out_path"=>"", "sign_in_text"=>"hello gitlab", "help_page_text"=>"", "shared_runners_enabled"=>"1", "max_artifacts_size"=>"100"}}
Redirected to http://gitlab.qiyi.domain/admin/application_settings
Completed 302 Found in 34ms (ActiveRecord: 5.2ms)
Started GET "/admin/application_settings" for 127.0.0.1 at 2015-12-03 19:48:26 +0800
Processing by Admin::ApplicationSettingsController#show as HTML
Completed 200 OK in 72ms (Views: 48.5ms | ActiveRecord: 3.4ms)
```

Sees it works fine, but when I refresh the settings page, no notification email added at all.

The same behavior as other fields, like `sign_in_text` and etc.

**Comment by sameersbn** [comment]
Yes. I can see the same issue. Maybe it is an upstream issue. I will check on a physical install  and confirm.

**Comment by chengweiv5** [comment]
It's very weird!

This morning when I access my gitlab service again, I found all changes I made yesterday saved!

**Comment by sameersbn** [comment]
I tested on a local install and the issue persists. This is an upstream issue.

**Comment by lafraia** [comment]
Looks like an 8.2.2 bug.
https://gitlab.com/gitlab-org/gitlab-ce/issues/3609

8.2.3 is on its way
https://gitlab.com/gitlab-org/gitlab-ce/commit/cd4a33120a39b23128e6798eae0a2ec7b5c9e658

**Comment by chengweiv5** [comment]
OK, thanks guys, waiting for the better 8.2.3

**Comment by sameersbn** [comment]
8.2.3 has been released.
