### ISSUE TITLE
configure scripts use pipe as seperator in sed with ldap user filter

### ISSUE THREAD

**Issue by tu-maurice** [sameersbn/docker-gitlab#526]
I'm currently updating gitlab from tag 8.1.3. I tried to use tag 8.2.2 as well as 8.2.1-1 which both show the following output:
```
gitlab_1     | Installing configuration templates...
gitlab_1     | SSL keys and certificates were not found.
gitlab_1     | Assuming that the container is running behind a HTTPS enabled load balancer.
gitlab_1     | Configuring gitlab...
( ... )
gitlab_1     | Configuring gitlab::ldap...
gitlab_1     | sed: -e expression #1, char 26: unknown option to `s'
gitlab_gitlab_1 exited with code 1
```

after viewing the file docker-gitlab/assets/runtime/functions line 323 (tag 8.2.2) i guess the problem is the pipe character used in the seds as a seperator seems to mess with our ldap user filter which also contains a pipe (ldap's or operator).

**Comment by sameersbn** [comment]
can you check with the `latest` build.

**Comment by tu-maurice** [comment]
Works. thanks
