### ISSUE TITLE
Bump to Postgres 9.4-9 breaks Gitlab while using compose file

### ISSUE THREAD

**Issue by Caligatio** [sameersbn/docker-gitlab#527]
I just pulled the newest docker-compose file and it appears that the Postgres:9.4-9 image only binds in the container on 127.0.0.1 causing the Gitlab container to be unable to connect to it.  Downgrading to 9.4-8 fixed the problem.

**Comment by nevermosby** [comment]
Got same problem with the latest version and it works for me with downgrading to 9.4-8 of postgres
