### ISSUE TITLE
image tag 7.8.3

### ISSUE THREAD

**Issue by taniadaniela** [sameersbn/docker-gitlab#528]
Hi.. I need to migrate my gitlab install to another server and I'm using the 7.8.3 version but I can't find the image tag for it.. Is there a reason? If I can't have that image can I restore my backup using 7.8.4 version?

**Comment by sameersbn** [comment]
Only reason is that `7.8.4` was released (by upstream) before i could release `7.8.3`. I have created a new tag for the `7.8.3` build. You can try using it once the build is ready https://hub.docker.com/r/sameersbn/gitlab/builds/

**Comment by sameersbn** [comment]
please close the issue if it resolves the issue

**Comment by taniadaniela** [comment]
thanks, the image works..
