### ISSUE TITLE
GITLAB_RELATIVE_URL_ROOT is broken in 8.2.2

### ISSUE THREAD

**Issue by osixia** [sameersbn/docker-gitlab#531]
There is some files not found with GITLAB_RELATIVE_URL_ROOT=/gitlab for example

![capture du 2015-12-08 19-21-24](https://cloud.githubusercontent.com/assets/6096236/11664325/68482bf4-9de1-11e5-8970-4a62c7ef1fc7.png)

**Comment by sameersbn** [comment]
@osixia I see the same issue. The weird thing is that the CSS points to the correct urls.
