### ISSUE TITLE
Docker Image for GITLAB with CentOS

### ISSUE THREAD

**Issue by DockerAsura** [sameersbn/docker-gitlab#533]
Hi team,
am little new to Docker. i trying to build docker image for git with centos 6.6 omnibus method
but unable to start the GIT service on container 

Regards
Asura

**Comment by sameersbn** [comment]
Please take a look at https://github.com/jasonbrooks/docker-gitlab

**Comment by DockerAsura** [comment]
Hi ,
Thank you...
But this is source code method right? can you help me with omnibus method.

Thanks 
Asura

**Comment by sameersbn** [comment]
@DockerAsura I have not used the omnibus package before. maybe gitlab upstream may be able to help.  I am not sure if the official gitlab docker images uses the omnibus package. you may want to check that as well.

**Comment by DockerAsura** [comment]
@sameersbn 
I tried omnibus method am getting error....
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

Thanks 
Asura

**Comment by sameersbn** [comment]
Please take a look at the official docker image for omnibus installs. Closing issue..
