### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by lazyfrosch** [sameersbn/docker-gitlab#534]
Hey Sameer,
I just wanted to express my thanks for your work with this container.

It is very stable, and works perfectly for deploying a Gitlab instance in the wink of an eye.

I migrated the data from my fiddled VM (with the old omnibus package) to this container months ago, and *never* looked back.

Greetings from Germany
Markus

**Comment by sameersbn** [comment]
Thank you for the appreciation :+1:
