### ISSUE TITLE
no builds are being triggered after upgrade from 7.14.3 to 8.2.3

### ISSUE THREAD

**Issue by grahovam** [sameersbn/docker-gitlab#540]
I upgraded my gitlab container from 7.14.3 to 8.2.3 the way it is suggested in the readme so i could use the now built in CI features. If I add a new project and push a .gitlab-ci.yml then everything works fine. But if I push this yml to a project that already existed in 7.14.3, then there is no build being triggered.

I compared every little config between a new project and an existing one. There is no difference.

**Comment by grahovam** [comment]
I solved the problem. My mistake was that I copied the volumes with scp to a new server. The proper way to go is to make a backup, scp the backup to the new server, use the backup to create a container of the old gitlab version, kill the container, create a new container with the new gitlab version

**Comment by sameersbn** [comment]
Glad you got it resolved.
