### ISSUE TITLE
The Members autocomplete is not working

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [sameersbn/docker-gitlab#541]
Here is the Chrome JS Console error:

```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://autocomplete/users.json?search=&per_page=20&active=true&current_user=false
```

It seems that some configuration item missed.

**Comment by llonchj** [comment]
+1

**Comment by zitsen** [comment]
@Ilya-Kuchaev @llonchj  , this is an upstream error, see [upstream gitlab issue#4136 ](https://gitlab.com/gitlab-org/gitlab-ce/issues/4136).

Here is current solution:

### First, enter gitlab container.
```
sudo docker-enter gitlab
```
### Now in the container shell:
```
cd /home/git/gitlab/public/assets
# **better backup the original file.**
sed -i 's/\/autocomplete/autocomplete/g' application-c3f6e83ef5cc6861b3f00e924494622c.js
gzip -c application-c3f6e83ef5cc6861b3f00e924494622c.js >application-c3f6e83ef5cc6861b3f00e924494622c.js.gz
```

It should works after refreshing your browser(to fetch the changed assets).

**Comment by Ilya-Kuchaev** [comment]
@zitsen Thanks! It works for me.

**Comment by sameersbn** [comment]
This probably is an upstream issue. I will check it on a physical install to confirm

**Comment by sameersbn** [comment]
this issue is because `relative_url_root` is being set to `/` in `gitlab.yml`
