### ISSUE TITLE
GitLab: Failed to authorize your Git request: internal API unreachable

### ISSUE THREAD

**Issue by ymettier** [sameersbn/docker-gitlab#544]
Hello,

I have a problem with push (both http and ssh protocols).

```
$ git push --mirror ssh://git@gitlab:10022/mygroup/myproject.git
Poussée vers ssh://git@gitlab:10022/mygroup/myproject.git
GitLab: Failed to authorize your Git request: internal API unreachable
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I logged inside the container and found something strange. 
```
# su - git
git@96c8bf28c991:/var/log/gitlab/gitlab-shell$ more gitlab-shell.log 
# Logfile created on 2015-12-18 18:16:29 +0000 by logger.rb/44203
[...]
W, [2015-12-18T18:22:35.156496 #464]  WARN -- : Failed to connect to internal API <POST http://localhost:8080//api/v3/internal/allowed>: #<SocketError: getaddrinfo: Name or service not known>
```

More fun :
```
git@96c8bf28c991:/var/log/gitlab/gitlab-shell$ getent hosts localhost
git@96c8bf28c991:/var/log/gitlab/gitlab-shell$ cat /etc/hosts
cat: /etc/hosts: Permission denied
```
OK, back with root permissions :
```
# ls -l /etc/hosts
-rw-r--r--+ 1 root root 399 Dec 18 18:29 /etc/hosts
```

Because `getfacl` and `setfacl` are not installed, I install them.
```
# apt-get update
# apt-get install acl
# getfacl /etc/hosts
getfacl: Removing leading '/' from absolute path names
# file: etc/hosts
# owner: root
# group: root
user::rw-
user:root:rwx			#effective:r--
user:nobody:---
group::rwx			#effective:r--
mask::r--
other::r--
```

No git ?

```
# setfacl -m u:git:r /etc/hosts
```

**And now it works for me.**

Could you help investigating why I have this problem ? Or just fix it with the same command I ran :
`setfacl -m u:git:r /etc/hosts`

For your information, I'm using a container-data :
```
# docker ps -a|grep gitlab | grep -v redis
96c8bf28c991        sameersbn/gitlab:8.2.3   "/sbin/entrypoint.sh "   21 hours ago        Up 21 hours             443/tcp, 0.0.0.0:10022->22/tcp, 0.0.0.0:10080->80/tcp   gitlab
489476f6ab75        sameersbn/gitlab:8.2.3   "/sbin/entrypoint.sh "   4 days ago          Exited (0) 4 days ago                                                           gitlab-data
```

Regards,
Yves

**Comment by sameersbn** [comment]
May I suggest you remove the image and pull it again. Sometimes the image tends to get corrupted during the pull. Repulling seems to resolve such weird issues. If that does not help then we call look deeper to figure whats going on.

Information such as the host, docker version, etc. maybe helpful here.

**Comment by ymettier** [comment]
Removed the image with `docker rmi`.

Now create the containers again...

```
# docker run --name gitlab-data sameersbn/gitlab:8.2.3 echo "Data-only container for gitlab"
Data-only container for gitlab
```
Now here are my problems...

Permissions on log dir
----------------------------
```
# docker run --name gitlab-shell -it --rm --volumes-from gitlab-data sameersbn/gitlab:8.2.3 bash
root@464f0207d95b:/home/git/gitlab# ls -l | grep log
lrwxrwxrwx  1 root root    22 Dec 11 08:18 log -> /var/log/gitlab/gitlab
root@464f0207d95b:/home/git/gitlab# ls -ld /var/log/gitlab
drwxr-xr-x+ 2 root root 4096 Dec 19 22:02 /var/log/gitlab
root@464f0207d95b:/home/git/gitlab# ls -l /var/log/gitlab
total 0
```

What you can see is that /var/log/gitlab/gitlab does not exist.
I `chown git:git /var/log/gitlab` and that fixed this problem.

Otherwise I have problems when I run the gitlab main container.

Permissions on /etc/hosts
---------------------------------
```
# ls -l /etc/hosts
-rw-r--r--+ 1 root root 326 Dec 19 22:03 /etc/hosts
root@464f0207d95b:/home/git/gitlab# su - git
git@464f0207d95b:~$ cat /etc/hosts
cat: /etc/hosts: Permission denied
```

Information about my hardware/software
---------------------------------------------------
The host is a NAS (QNAP TS-451). Yes, you can run docker on some NAS !

Here are some information about it :
```
# uname -a
Linux <my host name> 3.12.6 #1 SMP Wed Nov 18 01:49:20 CST 2015 x86_64 unknown
# docker --version
Docker version 1.8.2, build 6e97ca1
```
My temporary solution
----------------------------
So for me, it seems that I can create my container data as below. Then run a container with a shell and fix my problems :
```
docker run --name gitlab-shell -it --rm --volumes-from gitlab-data sameersbn/gitlab:8.2.3 bash
# apt-get install update
# apt-get install acl
# setfacl -m u:git:r /etc/hosts
# setfacl -m u:git:rwx /var/log/gitlab
# setfacl -m g:git:rwx /var/log/gitlab
```

Then run the main container with all the options I need.

Regards,
Yves

**Comment by ymettier** [comment]
Hello,

For your information, I cannot reproduce any of my problems on Fedora23 / sameersbn/gitlab:8.3.0.
So I think I can close the issue.

I will retry on my NAS with sameersbn/gitlab:8.3.0 and newer docker 1.9.1 and see if the problem persists. If yes, I will reopen this issue with more info.

Regards,
Yves
