### ISSUE TITLE
${GITLAB_DATA_DIR}/config/secrets.yml

### ISSUE THREAD

**Issue by Allineer** [sameersbn/docker-gitlab#559]
Hello!

```
# remove auto generated ${GITLAB_DATA_DIR}/config/secrets.yml
rm -rf ${GITLAB_DATA_DIR}/config/secrets.yml
```
[install.sh#L91-L92](https://github.com/sameersbn/docker-gitlab/blob/master/assets/build/install.sh#L91-L92)

We have no `secrets.yml` file in the `GITLAB_DATA_DIR` anytime.

On not?

**Comment by sameersbn** [comment]
The https://github.com/sameersbn/docker-gitlab/blob/master/assets/build/install.sh#L88-L89 line automatically generates `secrets.yml`. We don't want this file to be there, so we remove it after the asset compilation.

**Comment by Allineer** [comment]
Woops. Thanks!
