### ISSUE TITLE
How to modify path of volume?

### ISSUE THREAD

**Issue by vince67** [sameersbn/docker-gitlab#562]
I used to mount  `/home/git/data` at `/data1/data`.

Now I want to change the path and mount  `/home/git/data` at `/data2/data`.

I'm not sure that if the ssh key in `/data1/data` is the reason of failure.

I did the following commands:
   1. stop and rm containers(including gitlab redis mysql)
   2. copy  `/data1/data` into `/data2/data`.
   3. modify run config -v /data2/data:/home/git/data
   4. docker run containers

**Comment by sameersbn** [comment]
@vince67 it should be okay to move the files from `/data1/data` to `/data2/data`, you should take a little care while copying the files to the new location. i.e. either of these should be fine
 -  `cp -a /data1/data /data2/data`
 -  `rsync --progress -av /data1/data /data2/data`

Simply doing `cp -r /data1/data /data2/data` will not preserve the ownerships of the files which will case issues.

**Comment by vince67** [comment]
@sameersbn 
Thanks, it worked.
I should't use `cp -r` to copy files.
:)
