### ISSUE TITLE
SSL connection refused with no load balancer [SOLVED]

### ISSUE THREAD

**Issue by sisso19** [sameersbn/docker-gitlab#564]
I spent a lot of time on this and found out a issue in the documentation with the [ssl documentation](https://github.com/sameersbn/docker-gitlab#ssl). There it states that the .pem file is not needed when using self signed certificates but that is not true. When I skipped the strengthening security I got and error in the logs where it stated that the certificate files were missing. When I noticed that it was looking for the .pem file I added it to the certs folder and it worked. 

here are the log lines that pointed me to the problem. I already had key and crt file in the certs folder
    [36mgitlab_1     | [0m+ [[ -f /home/git/data/certs/gitlab.crt ]]
    [36mgitlab_1     | [0m+ [[ -f /home/git/data/certs/gitlab.key ]]
    [36mgitlab_1     | [0m+ [[ -f /home/git/data/certs/dhparam.pem ]]
    [36mgitlab_1     | [0m+ echo 'SSL keys and certificates were not found.'
    [36mgitlab_1     | [0m+ echo 'Assuming that the container is running behind a HTTPS enabled load balancer.'

### Here below is a description of the issue that I had already written before I figured out the solution.

I am deploying a gitlab on my private server and have deployed it successfully but only with http.
This weekend I have been trying to set up a https connection with gitlab but it has been unsuccessfull

I followed the step by step instructions [as described here](https://github.com/sameersbn/docker-gitlab#ssl)

my docker compose file looks like this:

    postgresql:
      restart: always
      image: sameersbn/postgresql:9.4-11
      environment:
        - DB_USER=usr
        - DB_PASS=pass
        - DB_NAME=temporary_stuff
      volumes:
        - /var/docker/gitlab/postgresql:/var/lib/postgresql
    gitlab:
      restart: always
      image: sameersbn/gitlab:8.3.2
      links:
        - redis:redisio
        - postgresql:postgresqli
      ports:
        - "10080:80"
        - "10443:443"
        - "10022:22"
      environment:
        - DEBUG=true
        - TZ=GMT
        - GITLAB_TIMEZONE=GMT
        - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
        - GITLAB_HOST=myHost
       # I changed the port
        - GITLAB_PORT=10443
        - GITLAB_SSH_PORT=10022
        - GITLAB_RELATIVE_URL_ROOT=
       # I added these two lines to the docker-compose file
        - GITLAB_HTTPS=true
        - SSL_SELF_SIGNED=true
       # to here
        - DB_ADAPTER=postgresql
        - DB_HOST=postgresqli
        - DB_NAME=temporary_stuff
        - DB_USER=usr
        - DB_PASS=pass
        - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
        - GITLAB_NOTIFY_PUSHER=false
        - GITLAB_EMAIL=notifications@example.com
        - GITLAB_EMAIL_REPLY_TO=noreply@example.com
        - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com
        - GITLAB_BACKUP_SCHEDULE=daily
        - GITLAB_BACKUP_TIME=01:00
        - SMTP_ENABLED=true
        - SMTP_DOMAIN=www.google.com
        - SMTP_HOST=smtp.gmail.com
        - SMTP_PORT=587
        - SMTP_USER=myemail@myemail.com
        - SMTP_PASS=mypass
        - SMTP_STARTTLS=true
        - SMTP_AUTHENTICATION=login
        - IMAP_ENABLED=false
        - IMAP_HOST=imap.gmail.com
        - IMAP_PORT=993
        - IMAP_USER=mailer@example.com
        - IMAP_PASS=password
        - IMAP_SSL=true
        - IMAP_STARTTLS=false
      volumes:
        - /var/docker/gitlab/gitlab:/home/git/data
    redis:
      restart: always
      image: sameersbn/redis:latest
      volumes:
        - /var/docker/gitlab/redis:/var/lib/redis

In my /var/docker/gitlab/gitlab/certs i have 2 files, gitlab.crt and gitlab.key. 
The key file permissions is -r-------- as instructed by the documentation.

When I run the docker-compose up  these are the [logs.txt](https://github.com/sameersbn/docker-gitlab/files/77871/logs.txt)

When I try to connect to port 10080 I get a SSL connection error (ERR_SSL_PROTOCOL_ERROR)
When I try to connect to port 10443 I get a This web page is not available (ERR_CONNECTION_REFUSED)

I am not using a load balancer.

I have looked at other issues but none of the fixes there have worked for me.

**Comment by sameersbn** [comment]
> There it states that the .pem file is not needed when using self signed certificates

I cannot see where it states that the dhparam.pem file is not needed. Can you point it out for me?

**Comment by sisso19** [comment]
I´m sorry but I seem to have misread this documentation

> When using self-signed certificates you need to generate these files yourself. Skip to Strengthening the server security section if you are armed with CA certified SSL certificates.

This is the line I am talking about. I read it as if you are using self-signed certificate skip strengthening the server security.

Can this be thread be deleted?

**Comment by sameersbn** [comment]
will just close it.

**Comment by krzkaczor** [comment]
That's funny I made exactly the same mistake. I think that documentation should emphasize that it's required.
