### ISSUE TITLE
Mailroom take 100% of one CPU

### ISSUE THREAD

**Issue by flexbrane** [sameersbn/docker-gitlab#571]
Hello,

Thanks for this docker image, it's very userful !

It work perfectly, but I notice that mail_room take one CPU at 100% almost all the time. I have seen some other same issues, but I doesn't understand how to resolve this problem with your gitlab image.

You can show details of this problem on the attached picture : 
![mail_room](https://cloud.githubusercontent.com/assets/14235706/12217681/26cccb22-b708-11e5-8011-3947fc18f56b.jpg)

**Comment by sameersbn** [comment]
@flexbrane Can you check the mail_room logfile located at  `/home/git/gitlab/log/mail_room.log` to see if you notice anything unusual? Also can you check if the reply by email feature works?

**Comment by flexbrane** [comment]
I have this in my mail_room.log :
/usr/lib/ruby/2.1.0/net/imap.rb:1454:in `connect': SSL_connect returned=1 errno=0 state=unknown state: unknown protocol (OpenSSL::SSL::SSLError)
        from /usr/lib/ruby/2.1.0/net/imap.rb:1454:in `start_tls_session'
        from /usr/lib/ruby/2.1.0/net/imap.rb:1047:in `initialize'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `new'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `imap'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:83:in `start_tls'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:68:in `setup'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:132:in `run'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `each'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `run'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/cli.rb:52:in `start'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/bin/mail_room:5:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/mail_room:23:in `load'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/mail_room:23:in `<main>'

**Comment by flexbrane** [comment]
Help ! It take lot lot of my -small- CPU ! Any way to resolve this ?

**Comment by sameersbn** [comment]
@flexbrane from my understanding you will get that error if the container is not able to connect to your imap server. This could be because the container does not have internet access or the DNS server cannot resolve queries.

Try logging onto the container using `docker exec -it gitlab bash` and then test if the DNS server can resolve queries using `ping` and test the internet connection using `curl`, etc.

The IMAP configuration allows users to comment on issue by replying to emails. This however requires certain features to be available on your imap server. see http://doc.gitlab.com/ce/incoming_email/README.html for details.

As a temporary fix you can disable IMAP support by setting `IMAP_ENABLED=false`. This means that reply_by_email feature will not work.

**Comment by flexbrane** [comment]
I have an internet connection, and the DNS is working well.

In /var/log/gitlab/gitlab/Mail_room.log I have this :
```sh
/usr/lib/ruby/2.1.0/net/imap.rb:1454:in `connect': SSL_connect returned=1 errno=0 state=unknown state: unknown protocol (OpenSSL::SSL::SSLError)
        from /usr/lib/ruby/2.1.0/net/imap.rb:1454:in `start_tls_session'
        from /usr/lib/ruby/2.1.0/net/imap.rb:1047:in `initialize'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `new'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `imap'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:83:in `start_tls'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:68:in `setup'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:132:in `run'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `each'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `run'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/cli.rb:52:in `start'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.6.1/bin/mail_room:5:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/mail_room:23:in `load'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/mail_room:23:in `<main>'
```
Again and again. What is this ?

**Comment by flexbrane** [comment]
You do not think That mail_room is doing to many loop or something like that ?

Is it possible to add a " sleep 1 " in the script / program for example? I think I have seen this somewhere , but I don't know how to Do That .

**Comment by sameersbn** [comment]
> I have an internet connection, and the DNS is working well.

Please note that if it works on the docker host, it does not necessarily mean that it will work inside the container. The only way to check it by logging into the container and testing.

> You do not think That mail_room is doing to many loop or something like that ?

It appears that the `mail_room` daemon terminates when it encounters the error. The supervisor then relaunches the daemon. This is the reason why you are seeing the message repeatedly. BTW, it is also possible that you have not configure IMAP correctly. That could also be the reason for the error. Are you using googlemail or google apps as the mail provider?

> Is it possible to add a " sleep 1 " in the script / program for example? I think I have seen this somewhere , but I don't know how to Do That .

This is not possible. The relaunch is performed by `supervisord`.

**Comment by flexbrane** [comment]
I have tested the DNS inside the the container (with <kbd>exec</kbd> command)

Although GitLab can send email, you think that IMAP can be is not configured correctly ? I use *privateemail*. That's the email system of namecheap for my domain name.

So right now I don't what I can do (expect change my VPS ^^)

**Comment by sameersbn** [comment]
On Tuesday 12 January 2016 12:19 PM, flexbrane wrote:
> I have tested the DNS inside the the container (with exec command)

Then it most probably means that IMAP is not configured correctly.

>
> Although GitLab can send email, you think that IMAP can be is not
> configured correctly ? I use /privateemail/. That's the email system of
> namecheap for my domain name.

IMAP is used for incoming mails, while SMTP is used for mail delivery. 
They both have different settings in terms of the ports used, etc. It is 
entirely possible that one or the other is not configured correctly or 
it is also possible that the mail host does not have the required 
features that are needed for reply_by_email to work. Please refer to 
http://doc.gitlab.com/ce/incoming_email/README.html for the specific 
requirements. From the link:

"Reply by email requires an IMAP-enabled email account, with a provider 
or server that supports email sub-addressing. Sub-addressing is a 
feature where any email to user+some_arbitrary_tag@example.com will end 
up in the mailbox for user@example.com, and is supported by providers 
such as Gmail, Google Apps, Yahoo! Mail, Outlook.com and iCloud, as well 
as the Postfix mail server which you can run on-premises."

You may also want to check with namecheap if they support email 
sub-addressing.

>
> So right now I don't what I can do (expect change my VPS ^^)

Change of VPS is probably not required. You need to check your settings. 
I recommend checking the namecheap KB for the settings. Here is 
something I found: 
https://www.namecheap.com/support/knowledgebase/article.aspx/1179/2175/general-configuration-for-mail-clients-and-mobile-devices.

I don't use and have never used namecheap VPS, so I am not in the 
position to suggest anything. Other users who have got IMAP working with 
Namecheap maybe able to help here. I hope someone takes note of this 
issue and replies.

>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-gitlab/issues/571#issuecomment-170815688>.
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com

**Comment by flexbrane** [comment]
>I don't use and have never used namecheap VPS, so I am not in the
position to suggest anything.

It's not a namecheap VPS, but a Kimsufi VPS. And my domain name was bought on namecheap who give me an email support (IMAP and SMTP).

>The IMAP configuration allows users to comment on issue by replying to emails. This however requires certain features to be available on your imap server. see http://doc.gitlab.com/ce/incoming_email/README.html for details.

As you said it's not fundamental, so I will see if I can disabled it.

**Comment by flexbrane** [comment]
Here my command to start the GitLab container :

```sh
docker run --name gitlab -d \
--restart=always \
--link gitlab-postgresql:postgresql --link gitlab-redis:redisio \
--publish 10022:22 --publish 10080:80 --publish 10443:443 \
--env 'GITLAB_SSH_PORT=10022' --env 'GITLAB_PORT=10443' \
--env 'GITLAB_HTTPS=true' --env 'SSL_SELF_SIGNED=true' \
--env 'GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string' \
--volume /srv/docker/gitlab/gitlab:/home/git/data \
--env 'GITLAB_HOST=X.X.X.X' \
--env 'SMTP_USER=my@email.com' --env 'SMTP_PASS=myPassword' \
--env 'IMAP_USER=my@email.com' --env 'IMAP_PASS=myPassword' \
--env 'SMTP_DOMAIN=www.mydomain.com' \
--env 'SMTP_HOST=mail.privateemail.com' \
--env 'SMTP_PORT=25' \
--env 'IMAP_HOST=mail.privateemail.com' \
--env 'IMAP_PORT=143' \
--env 'IMAP_STARTTLS=true' \
--env 'OAUTH_GITHUB_API_KEY=yyyyyyyyyyyyyyyyyy' \
--env 'OAUTH_GITHUB_APP_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
sameersbn/gitlab:8.3.2

```

Something appear wrong ?

**Comment by sameersbn** [comment]
Can you try.

```
IMAP_USER=my@email.com
IMAP_PASS=myPassword
IMAP_HOST=mail.privateemail.com
IMAP_PORT=993
IMAP_SSL=true
IMAP_STARTTLS=false
IMAP_MAILBOX=inbox
```

I am only suggesting these values based on 
https://www.namecheap.com/support/knowledgebase/article.aspx/1179/2175/general-configuration-for-mail-clients-and-mobile-devices. 
No guarantees.

On Tuesday 12 January 2016 01:07 PM, flexbrane wrote:
> Here my command to start the GitLab container :
>
> docker run --name gitlab -d \
> --restart=always \
> --link gitlab-postgresql:postgresql --link gitlab-redis:redisio \
> --publish 10022:22 --publish 10080:80 --publish 10443:443 \
> --env'GITLAB_SSH_PORT=10022'  --env'GITLAB_PORT=10443'  \
> --env'GITLAB_HTTPS=true'  --env'SSL_SELF_SIGNED=true'  \
> --env'GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string'  \
> --volume /srv/docker/gitlab/gitlab:/home/git/data \
> --env'GITLAB_HOST=X.X.X.X'  \
> --env'SMTP_USER=my@email.com'  --env'SMTP_PASS=myPassword'  \
> --env'IMAP_USER=my@email.com'  --env'IMAP_PASS=myPassword'  \
> --env'SMTP_DOMAIN=www.mydomain.com'  \
> --env'SMTP_HOST=mail.privateemail.com'  \
> --env'SMTP_PORT=25'  \
> --env'IMAP_HOST=mail.privateemail.com'  \
> --env'IMAP_PORT=143'  \
> --env'IMAP_STARTTLS=true'  \
> --env'OAUTH_GITHUB_API_KEY=yyyyyyyyyyyyyyyyyy'  \
> --env'OAUTH_GITHUB_APP_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'  \
> sameersbn/gitlab:8.3.2
>
> Something appear wrong ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-gitlab/issues/571#issuecomment-170825618>.
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com

**Comment by flexbrane** [comment]
It works ! 
Thanks :)

**Comment by flexbrane** [comment]
I also removed the IMAP lines and it work to.

On mar., janv. 12, 2016 at 10:01 AM, Sameer Naik < notifications@github.com [notifications@github.com] > wrote:
Can you try.

```
IMAP_USER=my@email.com
IMAP_PASS=myPassword
IMAP_HOST=mail.privateemail.com
IMAP_PORT=993
IMAP_SSL=true
IMAP_STARTTLS=false
IMAP_MAILBOX=inbox
```

I am only suggesting these values based on

https://www.namecheap.com/support/knowledgebase/article.aspx/1179/2175/general-configuration-for-mail-clients-and-mobile-devices.
No guarantees.

On Tuesday 12 January 2016 01:07 PM, flexbrane wrote:
> Here my command to start the GitLab container :
>
> docker run --name gitlab -d \
> --restart=always \
> --link gitlab-postgresql:postgresql --link gitlab-redis:redisio \
> --publish 10022:22 --publish 10080:80 --publish 10443:443 \
> --env'GITLAB_SSH_PORT=10022' --env'GITLAB_PORT=10443' \
> --env'GITLAB_HTTPS=true' --env'SSL_SELF_SIGNED=true' \
> --env'GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string' \
> --volume /srv/docker/gitlab/gitlab:/home/git/data \
> --env'GITLAB_HOST=X.X.X.X' \
> --env'SMTP_USER=my@email.com' --env'SMTP_PASS=myPassword' \
> --env'IMAP_USER=my@email.com' --env'IMAP_PASS=myPassword' \
> --env'SMTP_DOMAIN=www.mydomain.com' \
> --env'SMTP_HOST=mail.privateemail.com' \
> --env'SMTP_PORT=25' \
> --env'IMAP_HOST=mail.privateemail.com' \
> --env'IMAP_PORT=143' \
> --env'IMAP_STARTTLS=true' \
> --env'OAUTH_GITHUB_API_KEY=yyyyyyyyyyyyyyyyyy' \
> --env'OAUTH_GITHUB_APP_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
> sameersbn/gitlab:8.3.2
>
> Something appear wrong ?
>
> —
> Reply to this email directly or view it on GitHub
>
<https://github.com/sameersbn/docker-gitlab/issues/571#issuecomment-170825618>.
>

--
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com
—
Reply to this email directly or view it on GitHub
[https://github.com/sameersbn/docker-gitlab/issues/571#issuecomment-170844413] .[https://github.com/notifications/beacon/ANk4Oh5coY3p9Zn4T-6jxW5fZeCmoHvVks5pZLh5gaJpZM4HBvIU.gif]

**Comment by sameersbn** [comment]
> I also removed the IMAP lines and it work to.

removing the IMAP lines means that `mail_room` will be disabled and hence reply_by_email will be disabled.
