### ISSUE TITLE
"docker link" isn't allowed to use with "docker network"

### ISSUE THREAD

**Issue by kujiy** [sameersbn/docker-gitlab#572]
Hi. Thank you for your great project. I'm always happy whenever using your images.

I noticed this problem;
When I add `net: my-network` into the docker-compose.yml, Docker showed me this error message.
> Conflicting options: --net=<NETWORK> can't be used with links. This would result in undefined behavior

I'm using Docker 1.9.1 and sameersbn/docker-gitlab 8.3.2.
You know, Docker 1.9 has "Docker network" feature and it'll be replaced with "Docker link".
[(mentioned in here)](https://docs.docker.com/engine/userguide/networking/dockernetworks/#legacy-links)

I need to use docker network to access other containers from this gitlab container, so I tried above.
It seems to work fine if gitlab container can access to postgresql and redis containers by the linked name "postgresql" and "redisio". But I couldn't find how to attach a specific name to a container with "docker network". It seems no options.

"Docker network" allows to access by container name. So I can change those container name in my docker-compose.yml but I don't think it's a good way. Because container name should be unique in the docker world.

Does anybody have a good idea or do you have a plan for removing link for the future?

**Comment by sameersbn** [comment]
@kujiy the image uses links to automatically get the connection and authentication parameters. Apart from this it serves no other purpose. You can safely remove these links from the gitlab container, but you will need to specify the required `DB_` and `REDIS_` parameters.

You might find the steps listed here useful: https://github.com/docker/docker/issues/18238. Please note that the steps listed in the linked issue is only a test setup. Use at your own discretion. 

Please close if the issue is resolved.

**Comment by kujiy** [comment]
@sameersbn Thank you very much for your great answer.
I'm always using your `docker-compose.yml` for my basic configiration. 
I didn't want to change lots of lines of that and use extra `backend` commands, so I did this;
- `$ docker-compose up` with your yml(contained `link` lines)
- execute `$ docker network connect my-network gitlab`  
This means I'm using "docker link" and "docker network" at the same time.
It's a bad way(docker said "This would result in undefined behavior" you know) but so far works fine for me.

I hope the "link" lines in your `docker-compose.yml` will be removed in the future.
Thank you very much.
