### ISSUE TITLE
ldap working but not ldaps

### ISSUE THREAD

**Issue by vikas027** [sameersbn/docker-gitlab#574]
Below environment variables are not working for ldaps. However, these work fine with a omnibus installation (non Docker) on a separate host. Am I missing anything ?

```bash
    - LDAP_ENABLED=true
    - LDAP_LABEL=LDAP
    - LDAP_HOST=myhost
    - LDAP_PORT=636
    - LDAP_UID=sAMAccountName
    - LDAP_METHOD=ssl
    - LDAP_BIND_DN=MyDN
    - LDAP_PASS=MyPassword
    - LDAP_ACTIVE_DIRECTORY=true
    - LDAP_BASE=MyBase
```

**Comment by sameersbn** [comment]
I myself have not tested the LDAP integration, but other users have been successfully using it. You might want to look at the gitlab logs.

**Comment by vikas027** [comment]
@sameersbn Thanks. Indeed, it was something to do with firewall. Closing the issue.
