### ISSUE TITLE
Docker Gitlab + Jwilder/Nginx-proxy + Cloudflare ssl = Redirect Loop 

### ISSUE THREAD

**Issue by grimabe** [sameersbn/docker-gitlab#578]
Hi,

The title is quite explicit.
I had before an instance of docker-gitlab + jwilder/nginx-proxy with a self-signed-certificate and all was working (almost) well.

I tried to add recently Cloudflare with the flexible ssl encryption.

So I migrate my DNS Servers to Cloudflares DNS.
I disabled my self-signed certificate on jwilder/nginx-proxy.

And I'm getting redirect loop when I try to access my gitlab instance.

I changed nothing to docker-gitlab conf (as below) : 
    
    - GITLAB_HTTPS=true
    - SSL_SELF_SIGNED=true
    - GITLAB_PORT=80

Any suggestion ? 

Thank you

**Comment by ninja-** [comment]
you need to change cloudflare's SSL to "full"

**Comment by grimabe** [comment]
I figured out another way, I was having a problem with Jwilder/Nginx proxy conf. It is working with flexible SSL on cloud flare.

**Comment by sameersbn** [comment]
Thanks @ninja- for helping out.
@grimabe can you share your solution for the benefit of other users?

**Comment by juyscapco** [comment]
@grimabe yes, please share your solution if you don't mind.

**Comment by juanluisbaptiste** [comment]
@grimabe yes ! don't be a bad person and tell us how you fixed it please !

**Comment by grimabe** [comment]
@juyscapco @juanluisbaptiste I am sorry I switched to Gitlab omnibus package a while ago.
I am not using this docker image anymore and unfortunately, I do not remember my configuration.

However, I can tell you that my config with the omnibus package is working with CloudFlare flexible SSL.

I changed the following in the default settings 

nginx['listen_port'] = 80
nginx['listen_https'] = false
nginx['proxy_set_headers'] = {
   "Host" => "$http_host_with_default",
   "X-Real-IP" => "$remote_addr",
   "X-Forwarded-For" => "$proxy_add_x_forwarded_for",
   "X-Forwarded-Proto" => "https",
   "X-Forwarded-Ssl" => "on",
   "Upgrade" => "$http_upgrade",
   "Connection" => "$connection_upgrade"
  }

**Comment by hypnoboutique** [comment]
If anyone else is having this problem, one quick "solution" is to set the status of your A/CNAME DNS records to DNS only (click the orange cloud to make it grey).

Obviously, you're **not benefitting from all the perks of CloudFlare** if you do this (CDN, proxy) but it might help you out in a pinch.

There's a good article [here](https://support.cloudflare.com/hc/en-us/articles/200170416-What-do-the-SSL-options-mean-), at the time of writing, that explains what's going on with the SSL settings in CF (found under *yourdomain.tld* > *Crypto*)

For those of us who are on free plans, it's worth pointing out that you won't get any option to change this... it's locked to "flexible" (which menas CF tries to connect to your container over http, jwilder sees it is a non-secure request and tries to redirect you to the secure route... which CF still tries to access over :80, etc, ad infinitum)
