### ISSUE TITLE
Artifacts throw 500 error, after upgrade to 8.4.0

### ISSUE THREAD

**Issue by schmunk42** [sameersbn/docker-gitlab#579]
```
Archiving artifacts...
INFO[0000] Creating archive artifacts.tgz ...           
INFO[0000] Done!                                        
Uploading artifacts...
3.4M	artifacts.tgz
curl: (22) The requested URL returned error: 500 Internal Server Error

ERROR: Build failed with: exit status 1
```

Related issue: https://gitlab.com/gitlab-org/gitlab-ce/issues/3607

I also noticed a broken link in  `/home/git/gitlab`, but I don't know if that's an issue

```
lrwxrwxrwx  1 root root     22 Jan 23 08:39 log -> /var/log/gitlab/gitlab
```

**Comment by schmunk42** [comment]
Related https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/303#note_3356948

```
2016/01/23 21:31:37 error: handleFileUploads: extract files from multipart: exec: "gitlab-zip-metadata": executable file not found in $PATH
git.ourdomain.com @ - - [2016-01-23 21:31:36.991087607 +0000 UTC] "POST /ci/api/v1/builds/19321/artifacts HTTP/1.1" 500 22 "" "curl/7.35.0" 0.027105
```

**Comment by ayufan** [comment]
@schmunk42 Thanks for creating an issue.

**Comment by schmunk42** [comment]
I was able to hotfix this by `docker exec ...` these commands in the container:

```
ln -s /home/git/gitlab-workhorse/gitlab-zip-cat /usr/local/bin
ln -s /home/git/gitlab-workhorse/gitlab-zip-metadata /usr/local/bin
```

A better description can be found here: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/303#note_3357018

**Comment by sameersbn** [comment]
@ayufan @schmunk42 thanks for debugging this issue. I will move the installation of `gitlab-workhorse` to `/usr/local/` to resolve this issue.

**Comment by schmunk42** [comment]
@sameersbn Will you release 8.4.0-1 with this fix?

**Comment by sameersbn** [comment]
release 8.4.0-1

**Comment by schmunk42** [comment]
Great! I just wanted to confirm that it works as expected.
