### ISSUE TITLE
403 Forbidden when I sign out

### ISSUE THREAD

**Issue by ayapapa** [sameersbn/docker-gitlab#584]
I will report on the following things.
I downloaded docker-gitlab 8.4.1.
And I changed an environment "GITLAB_RELATIVE_URL_ROOT=" to "GITLAB_RELATIVE_URL_ROOT=/gitlab" in docker-compose.yml.
And I executed "sudo docker-compose up -d".
And I logged in GItLab via "http://localhost:10080/gitlab/users/sign_in".
There was no problem so far .
But then I signed out GitLab, I got "403 Forbidden when I sign out".

**Comment by sameersbn** [comment]
I am not sure about the issue you are seeing. Maybe you have set a signout path in the gitlab ui settings.

**Comment by ayapapa** [comment]
Thanks for your reply.
"a signout path" you said is "After sign out path" in "Admin Area"?
I checked "After sign out path" in "Admin Area", but found setting nothing.
To reconfirm this issue, I will try to recreate GitLab container on new virtual machine, and then I will report new result.
thanks.

**Comment by ayapapa** [comment]
Hi,
I tried to reconfirm this issue. Followings are the reconfirmation steps. I'm happy if any suggestions.  

prepared new virtual machine, OS is ubuntu14.04
updated OS(sudo apt-get update && sudo apt-get dist-upgrade)
installed docker, and docker-compose
git clone https://github.com/sameersbn/docker-gitlab
cd docker-gitlab
sudo docker-compose up -d
browsed http://192.168.11.22:10080
(192.168.11.22 is my virtual machin'd IP address)
signed in as root -> OK
changed password
signed in again -> OK
signed out  -> OK(displayed URL is http://192.168.11.22:10080/users/sign_in)
changed docker-compose.yml's "GITLAB_RELATIVE_URL_ROOT=" to "GITLAB_RELATIVE_URL_ROOT=/gitlab"
sudo docker-compose up -d
browsed http://192.168.11.22:10080/gitlab
signed in as root -> OK
signed out  -> OK(displayed URL is http://192.168.11.22:10080/gitlab/users/sign_in)
signed in as root again -> OK
changed "Sign-up enabled " to "OFF" and clicked "SAVE" button in "Admin area" page.
signed out -> NG(displayed URL is http://192.168.11.22:10080/) <- "403 Forbidden" error

and then,

browsed http://192.168.11.22:10080/gitlab -> No "Sign up" area was shown.
signed in as root again  -> OK
changed  "Sign-up enabled " to "ON" and clicked "SAVE" button in "Admin area" page.
signed out  -> NG(displayed URL is http://192.168.11.22:10080/) <- "403 Forbidden" error
browsed http://192.168.11.22:10080/gitlab -> "Sign up" area was shown.

That's all.
Maybe change of "Sign-up enabled" is related. 
Off course, I didn't changed "After sign out path" in "Admin area" page.

**Comment by sameersbn** [comment]
@ayapapa can you try a fresh install using instructions from the quickstart guide to check if this issue exists?

**Comment by ayapapa** [comment]
Oh, yes. I will try new release today.
Tanks.

**Comment by ayapapa** [comment]
Sorry for my late response. 
I tried a fresh install twice, version 8.4.3 and 8.4.4, and I confirmed this issue existence in both.
In these trial, I tried to change the items other than "Sign-up enabled"　in admin area, one was changing "Gravatar enabled" only, and another was changing "Maximum attachment size(MB)" only . 
Maybe is this Gitlab's issue?

**Comment by ayapapa** [comment]
Now this issue is discussing @ https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3989

**Comment by ayapapa** [comment]
Official solution is done. (https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3989)
Thanks a lot.

**Comment by sameersbn** [comment]
:+1:
