### ISSUE TITLE
local clone error

### ISSUE THREAD

**Issue by hhy5861** [sameersbn/docker-gitlab#588]
![image](https://cloud.githubusercontent.com/assets/8274977/12667542/dbaae658-c687-11e5-9c02-3f156e08791f.png)

**Comment by sameersbn** [comment]
The error indicates that the repository does not exist. Can you inspect the contents of the `repositories/` in the data volume. If it does exist, then maybe the file permissions are not correct. If that is the case, then you can launch the container with `app:sanitize` argument to correct any permission issues. Lastly you may need to check if you have permission to access the repo.
