### ISSUE TITLE
sameersbn/gitlab:latest exited with code 2

### ISSUE THREAD

**Issue by shsfoolish** [sameersbn/docker-gitlab#590]
I follow the instructions of http://www.damagehead.com/docker-gitlab/, run step 1, 2, 3.
No error came out. But I cannot wget http://localhost:10080
I tried to `sudo docker ps -a`, and following is the message:

CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                          PORTS               NAMES
    90b026841440        sameersbn/gitlab:latest      "/sbin/entrypoint.sh "   13 seconds ago      Exited (2) 12 seconds ago                       gitlab
    6f94fdcf5b37        sameersbn/redis:latest       "/sbin/entrypoint.sh"    59 minutes ago      Up 59 minutes               6379/tcp            gitlab-redis
    dd5c7a6b4457        sameersbn/postgresql:9.4-7   "/sbin/entrypoint.sh"    59 minutes ago      Up 59 minutes               5432/tcp            gitlab-postgresql`

sameersbn/gitlab:latest exited with code 2.
Is there any suggestion? Thanks in advance!

**Comment by sameersbn** [comment]
Please check the container logs using `docker logs gitlab`. You may also want to use the instructions listed here https://github.com/sameersbn/docker-gitlab#quick-start because they are the most up-to-date ones.

**Comment by shsfoolish** [comment]
Thanks a lot. I used `docker logs gitlab` and found that maybe I typed the wrong `DB_USER` `DB_PASS` set before in gitlab-postgresql.

How can I check the gitlab-postgresql user list and modify the password?

**Comment by shsfoolish** [comment]
Hi @sameersbn , that problem caused by the my db account setting. And the platform works perfectly now! Thanks and close the issue!
