### ISSUE TITLE
  Please configure the GITLAB_SECRETS_DB_KEY_BASE parameter.

### ISSUE THREAD

**Issue by TimCook1** [sameersbn/docker-gitlab#591]
What am I missing here?  I've upgraded multiple times, and all in the 8.x branch.  I've never run into this before, and I get it whether I try to deploy 8.4.2 or even roll back to 8.3.4-11 (which is the version I was just upgrading from).

Initializing logdir...
Initializing datadir...
Updating CA certificates...
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database
Configuring gitlab::redis
Configuring gitlab::secrets...
ERROR:
  Please configure the GITLAB_SECRETS_DB_KEY_BASE parameter.
  Cannot continue. Aborting...

docker run --name gitlab -d -h my.hostname.com --link postgres:postgresql --link redis:redisio --publish 32001:22 --publish 32000:443 --publish 32002:80 --env 'GITLAB_PORT=32000' --env 'GITLAB_SSH_PORT=32001' --env 'GITLAB_SECRETS_DB_KEY_BASE=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' --env 'GITLAB_HOST=my.hostname.com' --env 'GITLAB_SSH_PORT=32001' --env 'GITLAB_PORT=32000' --env 'GITLAB_HTTPS=true' --env 'SSL_SELF_SIGNED=true' --env 'SMTP_ENABLED=false' --volume /vol1/docker/sam/gitlab/gitlab:/home/git/data sameersbn/gitlab:8.4.2

**Comment by sameersbn** [comment]
I tested your launch command and found no issues. You can try adding `--env DEBUG=true` to debug.

**Comment by TimCook1** [comment]
docker logs doesn't show anything different:

Initializing logdir...
Initializing datadir...
Updating CA certificates...
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database
Configuring gitlab::redis
Configuring gitlab::secrets...
ERROR:
  Please configure the GITLAB_SECRETS_DB_KEY_BASE parameter.
  Cannot continue. Aborting...



root@synology:~# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   91d36fe
 Built:        Thu Jan 14 08:11:10 UTC 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   91d36fe
 Built:        Thu Jan 14 08:11:10 UTC 2016
 OS/Arch:      linux/amd64

**Comment by sameersbn** [comment]
> You can try adding `--env DEBUG=true` to debug

Please try this to see whats going on.

**Comment by TimCook1** [comment]
I did add that, the output didn't change.

**Comment by TimCook1** [comment]
Is it possible that for some reason the CLI isn't accepting my --env variables?

**Comment by TimCook1** [comment]
No thoughts at all?  Stinks having it down, not the end of the world obviously since I'm using it as more of an archive at the moment, but I'd like to get it up and running again.

**Comment by sameersbn** [comment]
I cannot say for sure whats going on in your environment. It certainly does look like the the container cannot see the ENV variables.

Can you run `docker run -it --rm -e 'GITLAB_SECRETS_DB_KEY_BASE=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' sameersbn/gitlab:8.4.2 printenv` and see if the `GITLAB_SECRETS_DB_KEY_BASE` variable is printed?

You could try `docker run -it --rm -e 'GITLAB_SECRETS_DB_KEY_BASE=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' ubuntu:trusty-20160119 printenv` as well.

You mentioned that it was working earlier. Do you remember making any changes such as updating the docker or maybe the system.

**Comment by sameersbn** [comment]
btw. a newer docker version was released today. you could try with that as well.

**Comment by TimCook1** [comment]
The variable wasn't printed, so it must not be taking the env flags. And unfortunately I can't update it by hand (well I probably could but it would be a mess) since it's currently running on a synology box and the current version is what's packaged.  

I guess I'll open a ticket with them and see if it gets me anywhere (HAH!)

**Comment by TimCook1** [comment]
Looks like I'm not the only one, so not a gitlab issue:
https://forum.synology.com/enu/viewtopic.php?f=260&t=109490

**Comment by TimCook1** [comment]
This is fixed as of DSM 6.0-RC for anyone else that might stumble upon this.
