### ISSUE TITLE
How to change ssh clone path

### ISSUE THREAD

**Issue by psstefanov** [sameersbn/docker-gitlab#601]
Hi,

It there a way to change the ssh git clone path from ssh://git@git.mycompany.com:10022/group/project.git to git@git.mycompany.com/group/project.git or at least to git@git.mycompany.com:10022/group/project.git?

Thank you in advance.

**Comment by sameersbn** [comment]
if you want the clone paths to look like `git@git.example.com`, then you need to use port 22 for the SSH server. If you are using the default docker-compose.yml, you would need to change `10022:22` to `22:22` and `GITLAB_SSH_PORT=10022` to `GITLAB_SSH_PORT=22`.  With this change, the host port 22 will be forwarded to the container port 22. This means that if you have an SSH server running on the host on port 22, you will need to update the host ssh server config to listen on some other port.

**Comment by psstefanov** [comment]
Great, thank you for the detailed description, and is there a way to remove the "ssh://" from the git clone url?

**Comment by sameersbn** [comment]
switching to port `22` will remove the `ssh://` from the clone url.

to reconfigure, you should stop the container, remove stopped container, make the changes in compose.yml and start again.

**Comment by psstefanov** [comment]
Thank you very much. This is exactly what I was looking for.

**Comment by psstefanov** [comment]
Hi,

When I've tried to change the Gitlab configuration to publish 22:22 for ssh I've received the following error: 
`ERROR: failed to create endpoint dockercitoolstack_gitlab_1 on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:22: bind: address already in use`

I've researched for a solution a lot but with no success. Does someone faced the same issue and is there a solution?

**Comment by sameersbn** [comment]
This is because the port 22 is already in use by the ssh server on the
host. You need to update the host ssh config to listen on some other port

**Comment by psstefanov** [comment]
Thank you again, that solved the issue.
