### ISSUE TITLE
2fa issues due time-sync

### ISSUE THREAD

**Issue by guybrush** [sameersbn/docker-gitlab#602]
i have issues with 2fa on my gitlab-installation (using this docker-compose). i did not fully investigate yet but the server is out of sync (~1min) and i *think* that is the issue.

i think installing ntp would fix the issue. if you want me to i can make a PR (just putting apt-get install ntp here should do the trick? https://github.com/sameersbn/docker-gitlab/blob/5362ee7/Dockerfile#L29-L34).

**Comment by sameersbn** [comment]
containers inherit the system clock. It means that your host clock should
be off as well

**Comment by guybrush** [comment]
oh! thanks for the information :) 

should i close the issue? feel free to close
