### ISSUE TITLE
[question] Difference from the official docker image

### ISSUE THREAD

**Issue by Elijen** [sameersbn/docker-gitlab#609]
Does it still make sense to use this unofficial Docker image instead of the [official one](https://hub.docker.com/r/gitlab/gitlab-ce/)?

If, yes, could you outline what are the main differences between these two? I think this might be a useful section in the README.md file.

**Comment by sheim-dev** [comment]
It still makes a lot of sense to use this image in favor of the official one if you do not like the 'omnibus' package installation used in the official image. That's also the main difference between the two images: Sameer's image does not use GitLab's Omnibus package installation. In addition, it provides many features that are not present in the official image and IMHO follows a much cleaner approach.

**Comment by sameersbn** [comment]
Its a matter of choice and requirements really. Here are some of the differences:

sameersbn/gitlab:

 - unofficial image, supported by the community.
 - only packages gitlab from source
 - can host gitlab on a relative url
 - easily enable ssl support
 - configurations using ENV variables
 - support for automated backups

refer the [readme](https://github.com/sameersbn/docker-gitlab/blob/master/README.md) for more details.

gitlab/gitlab-ce:

 - official image supported by Gitlab Inc (and the community).
 - packages gitlab using the omnibus method
 - packages postgresql and redis servers
 - packages (mattermost)[http://www.mattermost.org/]
 - relative urls might not work out-of-the-box**
 - no ssl support out-of-the-box**

refer to the [usage guide](http://doc.gitlab.com/omnibus/docker/) for usage instructions

** to the best of my knowledge, I do not intend to spread misinformation. 

(please close the support request if you feel your question has been answered)

**Comment by MarZab** [comment]
Sorry for reopening this thread but it does seem the best place to put this.

@sameersbn what is your plan regarding Koding?

**Comment by SolidNerd** [comment]
Hey @MarZab, it seems so koding will be in `8.11.0` available.  So far I can't say anything to it because currently it will have no impact on the image so far. There is a [MR](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/4769)  in the upstream for that. I would say we need to wait until the first rc is coming out and than we can say how much stuff need to be done for this integration.

**Comment by harobed** [comment]
It is possible to add this information in README

**Comment by harobed** [comment]
What do you think about add « Rationalize » section in README with this content: https://github.com/sameersbn/docker-gitlab/issues/609#issuecomment-189889529
