### ISSUE TITLE
[Question] Config file location and gitlab restart

### ISSUE THREAD

**Issue by cracker0dks** [sameersbn/docker-gitlab#612]
Is it possible to change the configfile without restarting the docker container with other parameters?
like changing hostname or smtp settings...
Where can I find the gitlab.rb and can I restart gitlab after changes like a normal gitlab?

thanks :)

**Comment by sameersbn** [comment]
@cracker0dks this image installs GitLab from source. The gitlab.rb file you are referring to is part of the gitlab-omnibus package and is not available in this image.

With this image, you will need to change environment variables and restart the image. If you need the gitlab.rb functionality you can using the official docker image for gitlab.

**Comment by cracker0dks** [comment]
ok thanks for the info. will do this :)
