### ISSUE TITLE
Unlinking stale socket /var/run/supervisor.sock cp: error writing '/home/git/gitlab-shell/config.yml': No space left on device cp: failed to extend '/home/git/gitlab-shell/config.yml': No space left on device

### ISSUE THREAD

**Issue by ImmanuelFredrick** [sameersbn/docker-gitlab#613]
Gitlab server suddenly went down and throwed 504 unreachable !! i tried restarting all the three containers (redis, postgres, gitlab)
Redis and postgres containers are getting launched but gitlab does not launch. It shows this trace in the logs

Unlinking stale socket /var/run/supervisor.sock
cp: error writing '/home/git/gitlab-shell/config.yml': No space left on device
cp: failed to extend '/home/git/gitlab-shell/config.yml': No space left on device

**Comment by sameersbn** [comment]
Can you check the available space on the disk partition with the `/var/lib/docker` directory. Maybe it is running out of space. You can clean up dangling containers, images and volumes using:

```bash
# removes stopped containers
docker rm -f $(docker ps -aq --filter status=exited)
# removed dangling images
docker rmi $(docker images -q --filter "dangling=true")
# removes dangling volumes
docker volume rm $(docker volume ls -q --filter "dangling=true")
```

this should free up some space.

**Comment by ragaar** [comment]
#necrobump
The above commands were able to resolve the issue for me.
Recommend closing this issue.
