### ISSUE TITLE
support gitlab 8.5.0  

### ISSUE THREAD

**Issue by mgcrea** [sameersbn/docker-gitlab#614]
https://about.gitlab.com/2016/02/22/gitlab-8-5-released/ :tada:

**Comment by xuwang** [comment]
Pulled sameersbn/gitlab:8.4.5 image but it seems still packaged with 8.4.4.:
```
core@ip-10-0-2-7-itla-admiral /var/lib/apps/gitlab/units $ docker inspect sameersbn/gitlab:8.4.5  | grep -i version
            "GITLAB_VERSION=8.4.4",
            "GITLAB_SHELL_VERSION=2.6.10",
            "GITLAB_WORKHORSE_VERSION=0.6.2",
```
Running the image doesn't seem to do any migration tasks.

**Comment by dlaabs** [comment]
Looks like the Dockerfile and change log was not updated to 8.4.5 along side commit 009dd2c513f13722cde0b3a06d36b1b26b83bcad.

**Comment by dlaabs** [comment]
Issue related to #611.

**Comment by sameersbn** [comment]
@xuwang release was incorrectly tagged as 8.4.5 instead of 8.4.4-1. sorry about this. have re-tagged as `8.4.4-1`.

I am currently travelling so 8.5.0 will be available in a few days.

**Comment by lenovouser** [comment]
:+1:

**Comment by MDXDave** [comment]
+8.5.1 :+1:

**Comment by ysaotome** [comment]
:+1:

**Comment by chengweiv5** [comment]
:+1:

**Comment by okaufmann** [comment]
:+1:

**Comment by vlsi** [comment]
:+1:

**Comment by schmunk42** [comment]
Until @sameersbn is back you can build your own image in the meantime, just by changing [this line](https://github.com/sameersbn/docker-gitlab/commit/36d2bab5c2b620ce29c5e3232b102fe21128d3a5#L4) to

    ENV GITLAB_VERSION=8.5.1
