### ISSUE TITLE
project-avatar image src should be 'https' when ssl is supported

### ISSUE THREAD

**Issue by junkboy0315** [sameersbn/docker-gitlab#623]
I setup ssl certification.
changed gitlab settig like below.

`-e GITLAB_PORT=443`
`-e GITLAB_HTTPS=true`

result of this setting,
my profile image src changed
`<img src="http://.....`
to
`<img src="https://.....`
automatically.

but project-avatar image src is still
`http://...`

because of this,
Chrome (or IE) detect 'Mixed Content', make cautions,
and ssl mark disappers.

**Comment by junkboy0315** [comment]
upgrading gitlab:8.5.1 solved this problem.
thanks.

**Comment by sameersbn** [comment]
awesome
