### ISSUE TITLE
GitLab Image not on Dockerhub

### ISSUE THREAD

**Issue by gaiapunk** [sameersbn/docker-gitlab#625]
Hi,

The link in the readme to the Dockerhub image returned 404.  I saw that it was also on quay.io but I was wondering if there was a reason it's no longer on Dockerhub?

**Comment by sameersbn** [comment]
Maybe the image was being built on DH at the time you tried. Can you please try again. Here is a complete list of tags that are present on DH: https://hub.docker.com/r/sameersbn/gitlab/tags/

**Comment by sameersbn** [comment]
Closing.. please reopen if issue persists
