### ISSUE TITLE
Support version 8.5.3 and 8.5.2

### ISSUE THREAD

**Issue by lenovouser** [sameersbn/docker-gitlab#626]
`v8.5.3` and `v8.5.2` have both been released. `v8.5.4` is going to be released soon.

[GitLab Release Tags](https://gitlab.com/gitlab-org/gitlab-ce/tags)

**Comment by Ilya-Kuchaev** [comment]
+1

**Comment by MDXDave** [comment]
Use fork: https://github.com/MDXDave/docker-gitlab :laughing:

**Comment by sameersbn** [comment]
out now!
