### ISSUE TITLE
Project avatars not displaying

### ISSUE THREAD

**Issue by locallycompact** [sameersbn/docker-gitlab#628]
Adding an avatar to a project results in a 404 for the image file.

**Comment by sameersbn** [comment]
I tested locally with `8.5.4` and had no issues. Can you share your `docker-compose.yml` file?

**Comment by locallycompact** [comment]
Hi, here's what I have:

http://www.fpaste.org/335753/57449502/

**Comment by sameersbn** [comment]
this is the sample docker-compose.yml correct? 
 - can you describe your setup?
 - are you using a load balancer?
 - what is your host os?
 - can you paste the link that results in 404 error?

In the meanwhile I will test using your docker-compose file.

**Comment by sameersbn** [comment]
I see that you have set `GITLAB_HOST=silvermoon`. Are you able able to access the gitlab instance using http://silvermoon:10080 ?

**Comment by locallycompact** [comment]
This seemed to have only been an issue on first boot. I can close this.
