### ISSUE TITLE
How to use the "hooks" to achieve "gitlab pages" ?

### ISSUE THREAD

**Issue by WilldNY** [sameersbn/docker-gitlab#632]
Have a tutorial?

**Comment by sameersbn** [comment]
Sorry for not replying earlier. GitLab EE has support for Github Pages like feature. Not sure if it can be done in the CE edition

**Comment by janhommes** [comment]
@sameersbn Gilab CE has intoduced gilab pages support in version 8.17. Any plans to add some enviorment-vars to support it?
https://docs.gitlab.com/ce/administration/pages/

**Comment by solidnerd** [comment]
This a closed PR. But you can have a look at an ongoing PR for that  #1095 .
