### ISSUE TITLE
Switch from SPDY to HTTP/2

### ISSUE THREAD

**Issue by davidwindell** [sameersbn/docker-gitlab#633]

**Comment by SolidNerd** [comment]
Done. Have a look at :
- [gitlab-registry](https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/config/nginx/gitlab-registry)
- [gitlab-ssl](https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/config/nginx/gitlab-ssl)
