### ISSUE TITLE
How "-v" gitlab profile

### ISSUE THREAD

**Issue by WilldNY** [sameersbn/docker-gitlab#634]
I try to "/data/gitlab/config:/home/git/gitlab/config" can not mount, and the container can not be started  

please,help!

**Comment by sameersbn** [comment]
This will not work. Please refer to https://github.com/sameersbn/docker-gitlab/issues/11 and https://github.com/sameersbn/docker-gitlab/issues/11#issuecomment-34221545 for more information. With the `8.5.5` release you can use https://github.com/sameersbn/docker-gitlab/releases/download/8.5.5/config.tar.bz2 as the template. Note `config.tar.bz2` is just a tarball of https://github.com/sameersbn/docker-gitlab/tree/master/assets/runtime/config, so if you want to use some other version, just download the relavant config template.

WARNING: Overriding the default configuration is for advanced users and no support will be offered. Do it only if you HAVE to. All configuration options can be configured using ENV variables. if there is something that is not supported please let us know and  we will try to add the required parameters. Thanks.

**Comment by sameersbn** [comment]
Please reopen if you have further questions. Thank you.
