### ISSUE TITLE
404: http://ppa.launchpad.net/evarlast/golang1.5/ubuntu/dists/trusty/main/binary-amd64/Packages

### ISSUE THREAD

**Issue by chengweiv5** [sameersbn/docker-gitlab#635]
http://ppa.launchpad.net/evarlast/golang1.5/ubuntu/dists/trusty/main/binary-amd64/Packages not found, like below

```
$ docker build
...
W: Failed to fetch http://ppa.launchpad.net/evarlast/golang1.5/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
```

```
$  wget http://ppa.launchpad.net/evarlast/golang1.5/ubuntu/dists/trusty/main/binary-amd64/Packages
--2016-03-11 13:42:45--  http://ppa.launchpad.net/evarlast/golang1.5/ubuntu/dists/trusty/main/binary-amd64/Packages
Resolving ppa.launchpad.net (ppa.launchpad.net)... 91.189.95.83
Connecting to ppa.launchpad.net (ppa.launchpad.net)|91.189.95.83|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-11 13:42:46 ERROR 404: Not Found.
```

**Comment by lazyfrosch** [comment]
Seems like the user deleted the PPA in the last few days.

**Comment by SergiuCip** [comment]
Hi! 

Until a proper solution is found and implemented my workaround this is:

wget https://storage.googleapis.com/golang/go1.5.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.5.linux-amd64.tar.gz
export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

and it will work as it should.

**Comment by lazyfrosch** [comment]
Maybe we should keep that "workaround"

**Comment by sameersbn** [comment]
Thanks for bringing this up. I will check what should be done. Ideally I want to get rid of golang once gitlab-workhorse is removed.

**Comment by sameersbn** [comment]
I am going to use this ppa instead https://github.com/golang/go/wiki/Ubuntu

**Comment by SergiuCip** [comment]
Great :+1:
