### ISSUE TITLE
How do you disable signups

### ISSUE THREAD

**Issue by SergiuCip** [sameersbn/docker-gitlab#639]
Hi there,

So in Gitlab-ce 8.x.x versions the variable signup_enabled has been removed. In order to disable signups I have been using a MYSQL query which should set enable_signups value to 0 in application_settings. However, if I run the command from within the functions file it is creating an additional row in the table.

Did anyone disabled signup successfully? (I do know it can be done using the admin panel, but I rather not used that).

Thanks,
Sergiu

**Comment by lazyfrosch** [comment]
In the admin settings inside GitLab

**Comment by SergiuCip** [comment]
I know, but what I meant it was without using the Admin Panel, during the Container runtime, I have a mysql query to do so, however, it is creating an extra record instead of appending the value in the existing column

**Comment by hknochi** [comment]
So can you provide your query for doing this. Otherwise it is not possible
to check what's going wrong

Sergiu Ciprian Cornea <notifications@github.com> schrieb am Do., 17. März
2016, 20:49:

**Comment by SergiuCip** [comment]
My MYSQL query is as follows:

 #        echo "Disabled signup" 
#        mysql -h "${DB_HOST}" -u "${DB_USER}" --password="${DB_PASS}" "${DB_NAME}" -e "UPDATE application_settings SET signup_enabled='0' WHERE id='1';"

I've also tried:

 #        echo "Disabled signup" 
#        mysql -h "${DB_HOST}" -u "${DB_USER}" --password="${DB_PASS}" "${DB_NAME}" -e "INSERT INTO application_settings (signup_enabled) VALUES ('0');"

But like I've said it is creating another record instead of existing one.

Regards,
Sergiu

**Comment by sameersbn** [comment]
have added `GITLAB_SIGNUP_ENABLED` configuration parameter to control enabling/disabling of user signup on the first run. 

Note: this setting only applies for the first run. On subsequent runs if you wish to change the behaviour then it should be toggled from the UI setting page and the parameter will not have any effect.

By default `GITLAB_SIGNUP_ENABLED=true`, meaning signups are enabled by default.

**Comment by SergiuCip** [comment]
Hi

Thank you very much for implementing that :) :+1: However, when I am trying to build the image I am getting the following error:

Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
file /usr/bin/nodejs got a new PT_PAX_FLAGS program header
Adding user `git' ...
Adding new group `git' (1000) ...
Adding new user `git' (1000) with group `git' ...
Creating home directory `/home/git' ...
Copying files from `/etc/skel' ...
passwd: password expiry information changed.
Cloning gitlab-shell v.2.6.10...
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500 Internal Server Error
fatal: The remote end hung up unexpectedly
The command '/bin/sh -c bash ${GITLAB_BUILD_DIR}/install.sh' returned a non-zero code: 128

Do you have an idea what might be causing this?

Those are the details from the Dockerfile:

FROM sameersbn/ubuntu:14.04.20160308
MAINTAINER sameer@damagehead.com

ENV GITLAB_VERSION=8.5.5 \


Thank you! 

Regards,
Sergiu

**Comment by sameersbn** [comment]
Shallow clones from gitlab git server are broken. This is resolved since release 8.6.6. However for the option to disable signups you need to build the master or use the `latest` image tag.

**Comment by SergiuCip** [comment]
Thanks a lot!!! It was to something with the configuration I was using. I've cloned a fresh version of your repo, changed the version to 8.7 and voila, works.

Thank you very much @sameersbn !

Regards,
Sergiu
