### ISSUE TITLE
version 8.5.8 not available

### ISSUE THREAD

**Issue by lksv** [sameersbn/docker-gitlab#641]
Thanks for perfect project and fast security release.
However I cannot upgrade to 8.5.8:
```
     lukas@Machine:~$ sudo docker pull sameersbn/gitlab:8.5.8
     Pulling repository docker.io/sameersbn/gitlab
     Tag 8.5.8 not found in repository docker.io/sameersbn/gitlab
```
...and page https://hub.docker.com/r/sameersbn/gitlab/tags/ shows last version as 8.5.7. as well.

I do not know if there is some "cache" and I have to wait a bit or there is some issue.

**Comment by sameersbn** [comment]
the build would probably not have been ready on dockerhub. It is now available. Please retry.

**Comment by lksv** [comment]
Thanks. Now it's ok.
