### ISSUE TITLE
gitlab dashboard not update

### ISSUE THREAD

**Issue by wupeng1988** [sameersbn/docker-gitlab#643]
Hi,

my gitlab dashboard does not update the push events, I googled and tried but the issue is still there, 

what shuold I do?

Best regards .

Adam

**Comment by wupeng1988** [comment]
I used latest sameersbn/gitlab image and mysql official image and redis official image

**Comment by wupeng1988** [comment]
fixed,  change mysql charset to utf8 will be ok

**Comment by sameersbn** [comment]
@wupeng1988 sorry for attending to your issue. glad that you got it resolved :smile: 
Do you think any changes are required in the gitlab image for the issue that you faced?

**Comment by wupeng1988** [comment]
@sameersbn Sorry, haven't logined for a long time, this issue is not about this image,  it's about mysql image,  using latin1 as default charset when auto created database, so I have change it to utf8
