### ISSUE TITLE
CSS broken after upgrade

### ISSUE THREAD

**Issue by ninja-** [sameersbn/docker-gitlab#645]
After upgrading to latest image, CSS is now broken and the CSS file referenced in rendered HTML will 404.
Do you have any idea what could be going on here?
I purged the cache multiple times and the issue persists.
Other assets are still there, like favicons and javascripts and they work OK.
There are no errors in gitlab logs or docker logs.

**Comment by ninja-** [comment]
clearly a regression, css is broken even for a clean setup of docker-gitlab on latest version

**Comment by sameersbn** [comment]
using GITLAB_RELATIVE_URL_ROOT?? If yes, stay away from `latest` builds.

On Thursday 24 March 2016 12:25 AM, ninja wrote:
> clearly a regression, css is broken even for a clean setup of
> docker-gitlab on latest version
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-gitlab/issues/645#issuecomment-200494319>
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com

**Comment by ninja-** [comment]
:( yes, on relative url

**Comment by ninja-** [comment]
<link rel="stylesheet" media="all" href="/gitlab/assets/application-c0f2658d29adbe2eb8bff8f10d06476438d47a6f3d756ab00e20ed87803333e9.css" />
root@bd7c885b7bd1:/home/git/gitlab/public/assets# ls application-*css
application-c0f2658d29adbe2eb8bff8f10d06476438d47a6f3d756ab00e20ed87803333e9.css

weird that it's causing 404 while other assets do work

**Comment by ninja-** [comment]
what exactly happened?

**Comment by sameersbn** [comment]
working on it. https://github.com/sameersbn/docker-gitlab/issues/39#issuecomment-200297120

**Comment by sameersbn** [comment]
fixed since release `8.6.0`
