### ISSUE TITLE
Tag for 8.6.0

### ISSUE THREAD

**Issue by schmunk42** [sameersbn/docker-gitlab#646]
I think it's available from :latest, but is there a special reason why there's no 8.6.0 tag here?

**Comment by Ilya-Kuchaev** [comment]
8.6.1 is available. They are really fast :)

**Comment by sameersbn** [comment]
there are some issues regarding relative_url with the 8.6 release. https://github.com/sameersbn/docker-gitlab/issues/39#issuecomment-200297120

**Comment by schmunk42** [comment]
Thank you for the info.

Another option would be a `8.6.0-beta1` tag for this repo.

**Comment by sameersbn** [comment]
@schmunk42 added a `8.6.0-beta1` tag.

**Comment by recteurlp** [comment]
Quick Fix it should work for other sub uri than /gitlab but not tested

```bash
docker exec -it gitlab bash
export RELATIVE_URL="/gitlab"
sed -i 's:try_files $uri $uri/ /index.html $uri.html @gitlab;:alias /home/git/gitlab/public/assets;:' /etc/nginx/sites-enabled/gitlab
sed -i "s:url(/assets/:url(${RELATIVE_URL}/assets/:g" application-c0f2658d29adbe2eb8bff8f10d06476438d47a6f3d756ab00e20ed87803333e9.css
sed -i "s:url(\"/assets/:url(\"${RELATIVE_URL}/assets/:g" application-c0f2658d29adbe2eb8bff8f10d06476438d47a6f3d756ab00e20ed87803333e9.css
supervisorcrl restart nginx
```

Could you consider something like this ? maybe for a 8.6.1-beta release ?
