### ISSUE TITLE
Migrating from 6.7.2 to 8.6.1 (latest) in different machines

### ISSUE THREAD

**Issue by maxcnunes** [sameersbn/docker-gitlab#651]
Hi,

I'm opening this issue here just to share my experience migrating from a really old version (6.7.2) to the latest version (8.6.1). There were many painful challenges and in case someone else need to do the same I guess here is the best place to share it.

## Migration Path

1. `v6.7.2`
1. `v7.13.2`
1. `v8.0.5-1`
1. `v8.6.1`

## Steps

1. `ssh root@your-gitlab-server.com.br`
1. `cd /home/git/gitlab`
1. create app backup `bundle exec rake gitlab:backup:create RAILS_ENV=production`
1. create a backup of `/home/git/.ssh/authorized_keys` (you may need due Problem 004)
1. access the new server machine
1. copy backup from the old server to new server
1. create and start the external gitlab DB
1. crate and start the external redis server
1. build a new image of docker-gitlab based in these changes https://github.com/maxcnunes/docker-gitlab/commit/92e65ef2837962e2a5635199ed946213de06bf95
1. execute the container with: `/app/init app:rake gitlab:setup` (setup DB for the first time - it is gonna crash, no worries)
1. copy backup into the `backups` folder inside the volume of the new gitlab server
1. execute the container with: `/app/init app:rake gitlab:backup:restore` (you may have problem 004 - checkout the solution)
1. execute the container with: `/app/init app:start` (it is gonna crash, no worries - Problem 001)
1. start the container in bash mode and follow the solution for the Problem 001)
1. execute the container with: `/app/init app:start` (start the app to ensure is ok. Even if it crashes due: *Check GitLab API access: FAILED. code: 502*. No worries, just ignore it.)
1. Upgrade to `v7.13.2`
1. Upgrade to `v8.0.5-1`
1. Upgrade to `v8.6.1`
1. I had problems importing the ssh authorized keys due especial characters in the ssh keys. Then I followed the solution for Problem 2. (You probably will not need it).
1. Test the ssh connection "ssh -T git@git-cloud-06.bravi.com.br”. Probably you will need to delete from the `known_hosts` the previous data for the old server.

### Problem 001 - undefined method `success?' for nil:NilClass

```bash
undefined method `success?' for nil:NilClass
/home/git/gitlab/lib/tasks/gitlab/enable_automerge.rake:34:in `block in create_satellites'
```

**Reference:** https://gitlab.com/gitlab-org/gitlab-ce/issues/172
> Remove L31 and change L34 with " if project.satellite.create". It works for me.
> bundle exec rake gitlab:satellites:create RAILS_ENV=production

```bash
sed -i -- 's%project.satellite.create%#project.satellite.create%g' /home/git/gitlab/lib/tasks/gitlab/enable_automerge.rake
sed -i -- 's%if $?.success?%if project.satellite.create%g' /home/git/gitlab/lib/tasks/gitlab/enable_automerge.rake
```

### Problem 002 - Could not find modernizr-2.6.2 in any of the sources

```bash
Fetching source index from https://rubygems.org/
Could not find modernizr-2.6.2 in any of the sources
```

**Reference:** http://stackoverflow.com/questions/22825497/installing-gitlab-missing-modernizer/22827382#22827382

### Problem 003 - unix:///var/run/supervisor.sock refused connection

**Reference:** https://github.com/docker/docker/issues/12080#issuecomment-162000092

Replace in the file `assets/init`:
```bash
/usr/bin/supervisord
```

With:
```bash
sed -i 's#/var/run//supervisor.sock#/dev/shm/supervisor.sock#g'  /etc/supervisor/supervisord.conf
touch /dev/shm/supervisor.sock
/usr/bin/supervisord -c /etc/supervisor/supervisord.conf
```

### Problem 004 - “Permission denied (publickey).” or “invalid byte sequence in US-ASCII (ArgumentError)"

**Reference:**  https://github.com/sameersbn/docker-gitlab/issues/519

Do not use the restore task to setup the ssh configurations. Instead of, just copy the `authorized_keys` from the old gitlab server (path `/home/git/.ssh/`).

**Comment by maxcnunes** [comment]
Closing it already. Since I was just sharing my solutions. Sorry, for create this "useless" issue, but here looked like the best place to share it.

**Comment by sameersbn** [comment]
@maxcnunes thanks for sharing. I'm sure other users should find it useful.

**Comment by veggiemonk** [comment]
@sameersbn should it be added to the doc?
