### ISSUE TITLE
8.5.1 to 8.6.1 upgrade failure.

### ISSUE THREAD

**Issue by vassilvk** [sameersbn/docker-gitlab#652]
**Steps to reproduce**:
1. Upgrade a sameersbn/gitlab setup from version 8.5.1 to 8.6.1.

**Observed behavior**:
The migrations kick off and then fail with the following message:

```
StandardError: An error has occurred, all later migrations canceled:

You must enable the pg_trgm extension. You can do so by running "CREATE EXTENSION pg_trgm;" as a PostgreSQL super user, this must be done for every GitLab database. For more information see http://www.postgresql.org/docs/current/static/sql-createextension.html
```

This same issue has been observed in other GitLab Docker implementations:
https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1185

**Comment by sameersbn** [comment]
Please see https://github.com/sameersbn/docker-gitlab/issues/39#issuecomment-200297120
If you have based your setup on https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml then please add the following line https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml#L8 and recreate the containers.

**Comment by veggiemonk** [comment]
@sameersbn Had the same problem and adding the pd_trgm extension to the docker-compose.yml worked! Thanks!

**Comment by vassilvk** [comment]
This worked, @sameersbn - thanks!
