### ISSUE TITLE
Docker container name is not equal to that in documentation

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [sameersbn/docker-gitlab#654]
In the many parts of README.md, container name is called `gitlab`.
But in the mine( I installed latest version today  ), the container name is `gitlabrunner_gitlab_1` not `gitlab`.
Do I miss anything? Or just are documentation needed update?

```
$ docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                        PORTS               NAMES
99a5fc3f0fad        sameersbn/gitlab:8.6.3        "/sbin/entrypoint.sh "   About an hour ago   Exited (137) 18 seconds ago                       gitlabrunner_gitlab_1
50980e86b2fd        sameersbn/postgresql:9.4-18   "/sbin/entrypoint.sh"    2 hours ago         Exited (137) 18 seconds ago                       gitlabrunner_postgresql_1
8e252a423b86        sameersbn/redis:latest        "/sbin/entrypoint.sh"    2 hours ago         Exited (0) 28 seconds ago                         gitlabrunner_redis_1
$ docker ps -a
```

**Comment by lazyfrosch** [comment]
The name prefix is generated from the directory name you ran docker-compose in, so its most likely your directory is named `gitlab-runner` or similar

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@lazyfrosch , Thanks! Yes, I ran in gitlab-runner directory, so.. can i avoid this naming? I want to sync the container name to that in the documentation.

**Comment by lazyfrosch** [comment]
Well, docker-compose is in my eyes not really meant for production, so in a production site you would set your names via the tool that controls the start of your containers. Like fleet, systemd, or custom scripts.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@lazyfrosch , Thanks thanks! You're been a big help.

**Comment by frenchbeard** [comment]
@b6pzeusbc54tvhw5jgpyw8pwz2x6gs docker-compose itself provides the -p flag to define the prefix, but an empty string passed to this flag defaults to the directory name, as you currently have. Also, I don't think you'd be able to remove the _1 at the end of the name (haven't been able to on my part so far).

**Comment by sameersbn** [comment]
There is a `container_name` parameter in docker-compose that allows you to give the container a specific name. However you may face issues with the auto detection of env parameters of linked containers. If you face this issue, manually specify the params instead of relying on autodetection.
- https://docs.docker.com/compose/compose-file/
