### ISSUE TITLE
Tag 8.6.5 not found in repository 

### ISSUE THREAD

**Issue by taniadaniela** [sameersbn/docker-gitlab#664]
Hi.. I need the 8.6.5 image but I when I try to download it I get this error:
docker pull sameersbn/gitlab:8.6.5
Pulling repository docker.io/sameersbn/gitlab
Tag 8.6.5 not found in repository docker.io/sameersbn/gitlab

can you upload it please?

**Comment by lenovouser** [comment]
Duplicate of #662
