### ISSUE TITLE
How to use gitlab-ci-multi-runner?

### ISSUE THREAD

**Issue by taniadaniela** [sameersbn/docker-gitlab#667]
I'm using a docker image of Gitlab 8.6.4 and I need to use CI. 
Should I install gitlab-ci-multi-runner in the gitlab container or into the host machine?

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
In my case, [docker-gitlab-ci-multi-runner](https://github.com/sameersbn/docker-gitlab-ci-multi-runner) is the best solution.!

**Comment by sameersbn** [comment]
`gitlab-ci-multi-runner` is used to configure runners for your builds. It can be run directly on the host or in a container like [docker-gitlab-ci-multi-runner](https://github.com/sameersbn/docker-gitlab-ci-multi-runner). Running it inside the gitlab container can adversely affect the performance of the gitlab ui. Avoid running it in the same container as gitlab

**Comment by taniadaniela** [comment]
thanks, I will try docker-gitlab-ci-multi-runner.
