### ISSUE TITLE
Reply by email without sub-addressing

### ISSUE THREAD

**Issue by Khorynthium** [sameersbn/docker-gitlab#670]
Hi. Met an issue with reply by email feature. Due to hosting provider limitation I can't use sub-addressing, only a dedicated address. But using of sub-addressing is forced by assets/runtime/env-defaults script (line 187). Is it possible to change this behavior? May be add some parameter for this.

**Comment by sameersbn** [comment]
When reply_by_email was implemented by gitlab sub addressing was required. Now it seems it may not be the case anymore http://doc.gitlab.com/ce/incoming_email/README.html. I will test and make the changes. Will also have to notify user that rely on https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/env-defaults#L187-L189

**Comment by Khorynthium** [comment]
Awesome. Thank you!
