### ISSUE TITLE
Please give ability to speicfy REDIS_DB_NUMBER for open source Redis

### ISSUE THREAD

**Issue by virtuman** [sameersbn/docker-gitlab#674]
You already have pretty much all the options for gitlab and redis. 
Would you please add option for REDIS DB NUMBER, we have multiple services that access Redis instance and some of them don't play well with others. 
Property would only need to modify this:

production: redis://{{REDIS_HOST}}:{{REDIS_PORT}}

Into this:
production: redis://{{REDIS_HOST}}:{{REDIS_PORT}}**/{{REDIS_DB_NUMBER}}**

I would recommend to add default value of "0", just for more transparent backward compatibility. But either way it will not affect any of the current users, unless they explicitly specify different DB number in their config.

Thank you.

**Comment by SolidNerd** [comment]
Hey,
i like your idea. I made a PR for that case. Could you test my PR ?.

**Comment by sameersbn** [comment]
The referenced PR has been merged
