### ISSUE TITLE
Expose client_max_body_size for Gitlab CI as config parameter

### ISSUE THREAD

**Issue by fruel** [sameersbn/docker-gitlab#675]
client_max_body_size for Gitlab CI is set to a fixed size of 10MB (https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/config/nginx/gitlab_ci#L27)

My CI runners try to submit artifacts greater than 10MB and fail:
```
ERROR: Uploading artifacts to coordinator... too large archive
```

Is it possible to expose this as config parameter? The comments in the nginx config file suggest that I can change this value to allow bigger artifacts but I don't really want to build the docker image manually to change it.

**Comment by SolidNerd** [comment]
Hey,
i made a PR for it. Could you test it ? To test it you need to build the docker image manually.

**Comment by sameersbn** [comment]
IMO you should avoid using the `GITLAB_CI_HOST` parameter and instead point your runners to `git.example.com/ci`. Internally gitlab will redirect always so updating the URL in the runners will avoid this redirection.

**Comment by sameersbn** [comment]
@SolidNerd since the redirection occurs internally maybe we could instead just set `client_body_max_size 0`

**Comment by fruel** [comment]
Ok, I realize now this issue was my own fault.

I completely missed the "Maximum artifacts size" option in the GitLab admin area and went looking for a solution in the config files. 

Nevertheless, thank you very much @SolidNerd for the fast response!
