### ISSUE TITLE
Feature Request: Environment variable to disable Gitlab CI

### ISSUE THREAD

**Issue by josdotso** [sameersbn/docker-gitlab#681]
I'm using Gitlab with Drone. When running Gitlab + Drone it is recommended that Gitlab CI be disabled in the `gitlab.yml` file [1].

[1] http://doc.gitlab.com/ce/ci/enable_or_disable_ci.html#site-wide-administrator-setting

**Comment by SolidNerd** [comment]
It's implemented look for the following env `GITLAB_PROJECTS_BUILDS`. To Deactivate it set it to false. `GITLAB_PROJECTS_BUILDS=false`. I hope i could help you.

**Comment by josdotso** [comment]
Thanks!
