### ISSUE TITLE
support multiple LDAP servers

### ISSUE THREAD

**Issue by robinro** [sameersbn/docker-gitlab#687]
Gitlab supports multiple LDAP servers. It would be nice to have support for this also in this image.

I might implement this myself if it becomes more relevant for our setup, but am happy is someone else does it.

My approach would be to just add one variable: LDAP_HOST_SECONDARY and if it's set add a secondary section which copies all other variables. While there are many possible configuration, I guess having a replication/slave server is the most common.
See https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/ldap.md for an example config of a secondary ldap server.

**Comment by ziirish** [comment]
Hello,

This feature is only available in Enterprise edition.
From the page you have linked we can read: 

> If you are installing GitLab Enterprise edition package you can use multiple LDAP servers

**Comment by robinro** [comment]
thanks for the hint @ziirish, I overlooked that somehow
