### ISSUE TITLE
Modifying config/gitlab.yml

### ISSUE THREAD

**Issue by auspex** [sameersbn/docker-gitlab#694]
Wonderful docker!  I hated the monolithic gitlab-ce package on Ubuntu, but had tried to build from source and been unsuccessful.

So, now, I've built an image based on  sameersbn/gitlab:8.7.5, but adding [support for iPython Notebooks](https://gist.github.com/martijnvermaat/6926070#existing-gitlab-installation). Unfortunately, this includes a change to `config/gitlab.yml.example` that doesn't propagate to the  `config/gitlab.yml` in the running container.

How is  `config/gitlab.yml` created in your image?

**Comment by SolidNerd** [comment]
Hey,
[here](https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/config/gitlabhq/gitlab.yml) you can found the gitlab.yml that is used in the project. So in that case you need to build your gitlab by your own instead using that this image as base, because everything happens in the image at runtime and not at the build process. So I hope i could help you. If you have more questions feel free to ask.

**Comment by auspex** [comment]
That's not the question. I certainly don't plan to build it on my own, as that loses any updates to this image.  I want to know how _that file_ is getting turned into config/gitlab.yml.  If I knew that, I could just add a three line patch to it.

**Comment by auspex** [comment]
Anyway, that's not what I'm looking for: assets/runtime/config isn't part of the created image, so can't be relevant.  You say "_everything happens in the image at runtime_". It's that "everything" that I want to understand.  Somewhere all those environment variables are getting substituted, and it's not using `assets/runtime/config/gitlab.yml` as the input to that process.

**Comment by sameersbn** [comment]
@auspex yes, you can override the gitlab.yml without the need for rebuilding the image. see https://github.com/sameersbn/docker-gitlab/issues/413#issuecomment-137476735

Let us know if you have any questions

**Comment by auspex** [comment]
I understand that. It's NOT what I'm trying to do. Now, _perhaps_ what I'm trying to do isn't what I _should_ be doing, but I'm pretty sure it is.

I'm using `docker-compose`, changing the `'build` parameter to use my own Dockerfile:
```
gitlab:
  restart: always
  build: gitlab
...
```

And my `gitlab/Dockerfile`:
```
FROM sameersbn/gitlab:8.7.5

USER    git
WORKDIR /home/git/gitlab
RUN     git remote add martijnvermaat https://github.com/martijnvermaat/gitlabhq.git && \
        git fetch martijnvermaat && \
        git checkout 8-7-stable-blob-ipython-notebook
USER    root
# needed for the iPython notebook converter
RUN     apt-get update && apt-get -y install pandoc python-pip
RUN     pip install ipython jinja2
```

This is working fine, _except_ that I need to inject three lines into `config/gitlab.yml`. Every attempt I've made so far has resulted in the same gitlab.yml you create, omitting those three lines.  If I have to put a `gitlab.yml` into `/srv/docker/gitlab/gitlab/config/` then it's no longer portable, and it doesn't have the benefit of the environment variables set in `docker-compose.yml`.

So, I'm trying to figure out how the existing process is injecting environment variables into gitlab.yml, apparently at container creation time, and where it gets the source for that process--because that `assets/runtime/config/gitlab.yml` file isn't there when the container is created.

**Comment by sameersbn** [comment]
@auspex oh got it.. like @SolidNerd mentioned, you need to override the `gitlab.yml` at the `/etc/docker-gitlab/runtime/config/gitlabhq/gitlab.yml` of the image. That is the runtime template. you download the template from the repo, edit/add whatever you need and add it to the image at the same location from your dockerfile.

**Comment by auspex** [comment]
OK, he didn't give me that path. I had no idea that `assets/runtime` is getting placed under `/etc/docker-gitlab`.

So, now, add `patch` to my apt packages, include a diff file in the context, and add
`RUN     patch -d /etc/docker-gitlab/runtime/config/gitlabhq gitlab.yml /tmp/gitlab.yml.diff`
as the last line of my Dockerfile, and the resulting gitlab.yml looks right!

Thank you!  (Now, to see if it actually works as intended--if it doesn't it's no fault of anybody here! ;-) )
