### ISSUE TITLE
go build -ldflags fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by peterwillcn** [sameersbn/docker-gitlab#696]
Downloading Go 1.5.3...
2016-05-22 03:04:54 URL:https://storage.googleapis.com/golang/go1.5.3.linux-amd64.tar.gz [80147269/80147269] -> "/etc/docker-gitlab/build/go1.5.3.linux-amd64.tar.gz" [1]
fatal: Not a git repository (or any of the parent directories): .git
go build -ldflags "-X main.Version=-20160522.030457" -o gitlab-workhorse
fatal: Not a git repository (or any of the parent directories): .git
go build -ldflags "-X main.Version=-20160522.030502" -o gitlab-zip-cat ./cmd/gitlab-zip-cat
fatal: Not a git repository (or any of the parent directories): .git
go build -ldflags "-X main.Version=-20160522.030503" -o gitlab-zip-metadata ./cmd/gitlab-zip-metadata
mkdir -p /usr/local/bin/
install gitlab-workhorse gitlab-zip-cat gitlab-zip-metadata /usr/local/bin/
Cloning gitlab-ce v.8.7.6...

**Comment by solidnerd** [comment]
I will close this because it's fixed now with #1187 and will be available in `9.1.0-1` or `latest`.
