### ISSUE TITLE
Add option to enable/disable user signup

### ISSUE THREAD

**Issue by sameersbn** [sameersbn/docker-gitlab#7]

**Comment by BrainTwister** [comment]
Is this flag still active? I used it with release v7.13.4, but the sign up is still possible.

**Comment by sameersbn** [comment]
That env variable is no longer available as it can be controlled from the
gitlab administration settings page.

**Comment by BrainTwister** [comment]
Thanks for the answer. Would you be so kind and say me how I can reach the administration page.

**Comment by sharpner** [comment]
![bildschirmfoto 2015-09-08 um 16 41 58](https://cloud.githubusercontent.com/assets/574362/9737781/9fa21fdc-5648-11e5-82e3-e514333d657a.png)
press this button when logged in as admin ^^

**Comment by inlikefletch** [comment]
We know how to disable sign up from the setting web ui, but how can we disable from the config yml or chef gitlab.rb recipe file?
