### ISSUE TITLE
difference to 'official' docker container?

### ISSUE THREAD

**Issue by thewilli** [sameersbn/docker-gitlab#706]
The Gitlab team started to publish their own, *official* [docker container](https://hub.docker.com/r/gitlab/gitlab-ce/). Will you continue to maintain this one, and how does your container differ from the official one?

Thanks in advance :)

**Comment by SolidNerd** [comment]
Yes this will be maintained by @sameersbn. The difference between this repo and the official is that this image uses the **source** of GitLab and **not gitlab-omnibus** like the official docker container. And It's more decoupled than the official. It has a seprate redis database and database. Another benefit is that you can configure everything with environment variables.

**Comment by baryshev** [comment]
Official docker container also can be fully configured with environment variable like this:
```
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url = "https://gitlab.exmplae.com"
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
``

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
What benefit is being offered from `decoupled`?
Is there someone who can answer more detail?

**Comment by sameersbn** [comment]
> Will you continue to maintain this one

I intend to maintain this image as long as we have users 😄 . In the event that 

> how does your container differ from the official one?

Please see my comment here #609

**Comment by thewilli** [comment]
@sameersbn great, thank you for clarification :smiley:
