### ISSUE TITLE
Set default project limit

### ISSUE THREAD

**Issue by ArneCoder** [sameersbn/docker-gitlab#717]
Maybe i am missing something, but it seems not to be possible to configure the default project limit via Environment settings?

**Comment by SolidNerd** [comment]
Yeah thats currently true after a short investigation i found out that it's don't exist in the source `gitlab.yml`. But in the `gitlab.yml` of omnibus it exists. I will try to implement this tomorrow.

**Comment by sameersbn** [comment]
used to exist, was removed in c37d3d68569d20f62003d8ee54193ede53dc4605
You can add it back if it makes sense.
