### ISSUE TITLE
Gitlab CI guidance - Create a runner.

### ISSUE THREAD

**Issue by azman0101** [sameersbn/docker-gitlab#720]
Hello,

I understood that gitlab-ci is merge with gitlab-ce.

How to create a runner inside the gitlab container ?

I'm not able to login in ssh in the box :(

```
This build is stuck, because the project doesn't have any runners online assigned to it. 
Go to Runners page
```

**Comment by sameersbn** [comment]
@azman0101 A runner is not started inside the gitlab container. 
You should use [gitlab-ci-multi-runner](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner) to setup the runner. [sameersbn/gitlab-ci-multi-runner](https://github.com/sameersbn/docker-gitlab-ci-multi-runner) image packages gitlab-ci-multi-runner (you may find the project readme useful).

Please see http://docs.gitlab.com/ce/ci/runners/README.html for additional details.

**Comment by khusnetdinov** [comment]
I've read docs in ci and gitlab and can't see right way. I need token and url for ci registration in gitlab. But how I can specify it on parallel start gitlab and ci? I have not found PARAMS in docs.

**Comment by solidnerd** [comment]
@khusnetdinov CI is intregated in GitLab. You need to setup your `.gitlab-ci.yml` for a project and register a runner before. How you can register a runner is explained in the documenation at https://docs.gitlab.com/ce/ci/runners/README.html

**Comment by khusnetdinov** [comment]
@solidnerd Thanks!
