### ISSUE TITLE
support for changing gitlabs title

### ISSUE THREAD

**Issue by GottZ** [sameersbn/docker-gitlab#736]
this is a feature request.
for reference: http://stackoverflow.com/questions/19945890/how-do-i-change-gitlab-title

**Comment by SolidNerd** [comment]
This seems to be a hack because you need to change some sources of GitLab and we try to be same to the official GitLab. If you want this customisation you can fork this project and do it on your own.

**Comment by sameersbn** [comment]
@GottZ I'd suggest submitting a P.R. to the upstream GitLab project

**Comment by SolidNerd** [comment]
Can we close this than now ?

**Comment by GottZ** [comment]
ye. sorry. i thought this was closed already after pointing out why this should not be added here.
