### ISSUE TITLE
Wrong permissions for /home/git/gitlab/shared/artifacts

### ISSUE THREAD

**Issue by umputun** [sameersbn/docker-gitlab#740]
Tried to upload artifacts for first time and run into `Uploading artifacts to coordinator… failed 500 Internal Server Error`. This is version 8.8.5, latest docker, host 14.04 with aufs. However I have not used artifacts on this particular box before and not sure if this is some fresh issue related to latest version.

Googling suggested cache issue or permissions. Clearing cache didn't do the trick, but discovered `/home/git/gitlab/shared/tmp` with root:root. Changed to git:git and everything got fixed, can use artifacts, no 500 anymore.

Not sure if this is your issue or gitlab's. Maybe it make sense to force git:git owner for this `shared` at startup phase.

**Comment by SolidNerd** [comment]
Hey, 
thanks for your report. So that i understand it correctly you mean build artifacts that are produced with `.gitlab-ci.yml`. If it's the correct one i will have a look into it tomorrow.

**Comment by umputun** [comment]
yeah, this is correct understanding.

**Comment by adamlc** [comment]
Any updates on this @solidnerd. I also came across this issue when using artifacts for the first time. Changing the owner of ```/home/git/gitlab/shared/tmp``` fixed the issue for me too :)

**Comment by gunr2171** [comment]
Same problem here. When using the docker gitlab runner and uploading artifacts I got these errors:

```
Uploading artifacts...
names.txt: found 1 matching files                  
WARNING: Uploading artifacts to coordinator... failed  id=1386 responseStatus=500 Internal Server Error status=500 Internal Server Error token=whsTSMJM
WARNING: Retrying...                               
WARNING: Uploading artifacts to coordinator... failed  id=1386 responseStatus=500 Internal Server Error status=500 Internal Server Error token=whsTSMJM
WARNING: Retrying...                               
WARNING: Uploading artifacts to coordinator... failed  id=1386 responseStatus=500 Internal Server Error status=500 Internal Server Error token=whsTSMJM
FATAL: invalid argument                            
ERROR: Job failed: exit code 1
```

I then `exec`'d into the main Gitlab container and ran these commands:

```
cd /home/git/gitlab/shared
chown -R git:git artifacts/
```

That might have been overkill, but at least artifacts will upload now:

```
Uploading artifacts...
names.txt: found 1 matching files                  
Uploading artifacts to coordinator... ok            id=1387 responseStatus=201 Created token=hzLJQtxw
Job succeeded
```

I am running Gitlab 11.3.0, Gitlab runner `gitlab/gitlab-runner:alpine-v11.3.0`.

**Comment by marthjod** [comment]
Thank you so much for the analysis! We ran into the same problem and were able to fix it by `chmod -R git:git /home/git/data/shared/artifacts/tmp` which belonged to `root`.
