### ISSUE TITLE
Nginx does not start with gitlab-registry.

### ISSUE THREAD

**Issue by pezzak** [sameersbn/docker-gitlab#750]
After update from 8.7.0 to 8.8.5-1 nginx in supervisor doesn't start. 
In log's i have: "nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 32" If i set server_names_hash_bucket_size 64 in http section everything works well. It would be good pass this param by docker var.

**Comment by SolidNerd** [comment]
Hey, 
thanks for your report. My `GITLAB_REGISTRY_HOST` is very short so i didn't have this problem. Could you send me your `GITLAB_REGISTRY_HOST` with an equivalent length of your current value. So i can reproduce it and test the possible fix.

**Comment by pezzak** [comment]
`GITLAB_REGISTRY_HOST` is set like a `docker.abcdef.ru`, this issue occurs if i start container on kvm host:
`root@1ab02093a3cc:/etc/nginx/sites-enabled# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             4
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 2
Stepping:              3
CPU MHz:               3392.292
BogoMIPS:              6784.58
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0-3`

if i start container on my machine everything work well

**Comment by SolidNerd** [comment]
So #786. It will resolves your problem if you set `NGINX_SERVER_NAMES_HASH_BUCKET_SIZE ` to `64`. If this solves not your problem. Please open a new issue. Thanks for reporting this issue.
