### ISSUE TITLE
Confusing keys in container_registry.md

### ISSUE THREAD

**Issue by umputun** [sameersbn/docker-gitlab#752]
This is about [container_registry.md](https://github.com/sameersbn/docker-gitlab/blob/master/docs/container_registry.md)

In "Generating certificate for authentication with the registry" it shows how to make set of registry-auth keys and then, in compose it shows some new `registry.key` in addition to generated `registry-auth.key`

```
   - GITLAB_REGISTRY_KEY_PATH=/certs/registry-auth.key
   - SSL_REGISTRY_KEY_PATH=/certs/registry.key
   - SSL_REGISTRY_CERT_PATH=/certs/registry.crt
```

Probably it should have `registry-auth` in all places, and maybe some explanation why one may even need both and different GITLAB_REGISTRY_KEY_PATH and SSL_REGISTRY_KEY_PATH. I think I understand what it supposed to do (proxy to external registry with different keys?) but will be helpful to see a little bit of documentation about this.

**Comment by SolidNerd** [comment]
You are right. `SSL_REGISTRY_*` is used as paths for the configuration of ssl in the `gitlab-registry` server_block config. `GITLAB_REGISTRY_KEY_PATH` is the private key of the `REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE`. This comes from [Docker Registry Auth Token Spec](https://docs.docker.com/registry/spec/auth/token/). So GitLab implemented this to be able to use the registry. For more information have a look at http://docs.gitlab.com/ce/administration/container_registry.html. I will add more information later to the documentation

**Comment by SolidNerd** [comment]
I updated the documentation of the `container_registry.md` in #789. I will close this issue now. If it's not solved your question of the container registry. **Reopen this issue and ping me**. So we can try to solve it for you and other people. This will help me to improve the docs again. Thank you for opening this ticket and ask this 👍 .
