### ISSUE TITLE
is registry authentication token realm started on its own?

### ISSUE THREAD

**Issue by rmartinez3** [sameersbn/docker-gitlab#754]
After using the compose file in the document. When i try to use the registry. It redirects me to the token realm in order to get access to the registry. However, a connection can never be established 

i used the compose file in here 
https://github.com/sameersbn/docker-gitlab/blob/master/docs/container_registry.md

are necessary things needed in order to push images to the registry?

**Comment by rmartinez3** [comment]
I noticed that the docker compose provided is missing gitlab registry issuer under gitalb configuration. After adding GITLAB_REGISTRY_ISSUER=gitlab-issuer. Which has to be the same as REGISTRY_AUTH_TOKEN_ISSUER in the registry config.

Also if you are using the same docker compose file. Make sure to have the correct port set for registry auth token realm

REGISTRY_AUTH_TOKEN_REALM=http://gitlab.example.com:10080/jwt/auth

**Comment by SolidNerd** [comment]
Thanks for your  report. I will update the container registry documenation later.

**Comment by SolidNerd** [comment]
I updated the documentation of the `container_registry.md` in #789. I will close this issue now. If it's not solved your question of the container registry. **Reopen this issue and ping me**. So we can try to solve it for you and other people. This will help me to improve the docs again. Thank you for opening this ticket and ask this 👍 .
