### ISSUE TITLE
Email notifications stopped working after upgrade to 8.9

### ISSUE THREAD

**Issue by ntrifunovic** [sameersbn/docker-gitlab#757]
Error is also reported on the following page: `/admin/health_check`

> Current Status:  Unhealthy
> no sendmail executable found.

**Comment by ziirish** [comment]
Temporary fix:

```
apt-get update
apt-get install exim4-daemon-light
```

Run these commands in your container (thanks to `docker exec` for instance)

**Comment by ntrifunovic** [comment]
@ziirish: Your temp fix seems to be working. Thanks!

**Comment by SolidNerd** [comment]
Thanks for your report. It's look like a problem the upstream. Have a look at https://gitlab.com/gitlab-org/gitlab-ce/commit/59b5bb033409901dc8e1fa7fa28c3a0fa38f495a . I tested your fix in #759 and it didn't work for me. The Health Check changed but mails won't be send after you install `exim4-daemon-light` same with `sendmail`.

**Comment by SolidNerd** [comment]
This will work when you upgrade to `8.9.1` now . So I will close this issue now.
