### ISSUE TITLE
Gitlab container registry s3

### ISSUE THREAD

**Issue by robertoamoreno** [sameersbn/docker-gitlab#761]
Does the current version work with docker container registry using s3 as the backend.

**Comment by SolidNerd** [comment]
It's not supported in the upstream directly. But I guess you could use it with a trick. Have a look at this [issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/17763) .

**Comment by SolidNerd** [comment]
@robertoamoreno It is possible to deal with what you need to change is the storage configuration of registry container. In this case GitLab can't do any backups for you, but if's okay than you can use s3. What configurations are needed have a look at https://docs.docker.com/registry/configuration/ .

**Comment by SolidNerd** [comment]
I updated the documentation of the `container_registry.md` in #789. I will close this issue now. If it's not solved your question of the container registry. Reopen this issue and ping me. So we can try to solve it for you and other people. This will help me to improve the docs again. Thank you for opening this ticket and ask this 👍 .
