### ISSUE TITLE
Some project page open up with 500 Error after upgrade to 8.9.1

### ISSUE THREAD

**Issue by datouxia** [sameersbn/docker-gitlab#765]
/var/log/gitlab/gitlab/gitlab-workhorse.log just says:

git.iyopu.com:10443 @ - - [2016-06-27 03:05:30.397901306 +0000 UTC] "GET /datouxia/sanbaopms-front HTTP/1.1" 500 2205 "https://git.iy
opu.com:10443/datouxia/sanbaopms-front/wikis/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like G
ecko) Chrome/51.0.2704.106 Safari/537.36" 0.088180
2016/06/27 03:05:30 ErrorPage: serving predefined error page: 500
2016/06/27 03:05:30 ErrorPage: serving predefined error page: 500

But all other inner page is OK, you can use url to switch between them.
Really need help! Thanks!

**Comment by Ilya-Kuchaev** [comment]
It's possible related to https://gitlab.com/gitlab-org/gitlab-ce/issues/19073
I have the same issue.

**Comment by SolidNerd** [comment]
@Ilya-Kuchaev  Yes this will be probably the origin of the problem.

At the moment I don't know how to solve here with an existing GitLab instance.
