### ISSUE TITLE
How can i downgrade docker-gitlab to 8.7.5 from 8.9.1 

### ISSUE THREAD

**Issue by octhreelara** [sameersbn/docker-gitlab#768]
I try to upgrade docker-gitlab from 8.7.5 to 8.9.0
All is worked after that, but some project page and creating projects open up with 500 Error.
Then i try to upgrade to 8.9.1, but issue is not gone.

I try to downgrade: I restore from backup(8.7.5) as in https://github.com/sameersbn/docker-gitlab#restoring-backups. 

BUT  when i start gitlab docker using 8.7.5
in
\# docker logs gitlab 
i get:
```
ERROR:
  Cannot downgrade from GitLab version 8.9.1 to 8.7.5.
  Only upgrades are allowed. Please use sameersbn/gitlab:8.9.1 or higher.
  Cannot continue. Aborting!
```

Is there way to make downgrade of docker-gitlab???

**Comment by SolidNerd** [comment]
Hey
did you try to run your restore command with the correct version and your backup should be a `8.7.5` as well. You should restore with a command like this.

```
docker run --name gitlab -it --rm [OPTIONS] \
    sameersbn/gitlab:8.7.5 app:rake gitlab:backup:restore BACKUP=1417624827
```

**Comment by octhreelara** [comment]
Yes, my restore command include exactly sameersbn/gitlab:8.7.5 and backup was a 8.7.5. But after success restoring and 
edit docker-compose.yml (string sameersbn/gitlab:8.9.1 to sameersbn/gitlab:8.7.5)
then
**docker-compose up** 
and I get this error again. What is my step wrong?

**Comment by nsymms** [comment]
I had this problem with earlier versions, and what worked for me was to do the restore into a completely empty and new installation of the older gitlab. I'm not sure if it's redis or something in the gitlab data tree, but somewhere it remembers which version you're on and prevents going backwards.

**Comment by SolidNerd** [comment]
Ah okay. It could be the database. Do you remove container and the related volume to that ? Pe

**Comment by octhreelara** [comment]
Yes, i remove container. Which related volume? 
```
volumes:
    - - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
```
This?

**Comment by SolidNerd** [comment]
Yep.

**Comment by octhreelara** [comment]
Thanks! i try!

**Comment by octhreelara** [comment]
It was necessary to delete all data in all volumes. And then restore. Then start with old version(8.7.5). It works!!! Thanks!
