### ISSUE TITLE
Upgrade base image to the latest stable release

### ISSUE THREAD

**Issue by frol** [sameersbn/docker-gitlab#769]
While I would love to see this image based on a small image like Alpine, I don't feel pain using your image with Ubuntu. However, it would be nice to have a newer OpenSSH server ~~(6.6.1 in Ubuntu 14.04 does not support ED25519 keys for authentication and [still supports DSA, which is considered weak](http://security.stackexchange.com/questions/112802/why-openssh-deprecated-dsa-keys))~~ (my fail). Ubuntu 16.04 was released quite a while ago, so I think there should be no issue moving there.

By the way, [Ubuntu 14.04 has 5 critical, 3 major, and 2 minor vulnerabilities](https://hub.docker.com/r/library/ubuntu/tags/trusty-20160624/)!

**Comment by tenken** [comment]
@frol just an fyi. 16.04 LTS does not automatically recommend update from 14.04 LTS until the .1 release which is likely sometime this month, July 2016 I believe. 16.04 while released is still not considered "stable" to upgrade from 14.04 until the OS itself recommends the upgrade automatically.

**Comment by SolidNerd** [comment]
I don't see so much vuln. At [quay.io](https://quay.io/repository/sameersbn/gitlab/image/e5a8587b406d440a89365b47950cca7cd837d10f91a63ee0f732f42f29e73afd?tab=vulnerabilities) all images will be checked with clair so far as i know. There says it has only medium vuln.

**Comment by J0WI** [comment]
`s/16.04/18.04/`

**Comment by J0WI** [comment]
s/18.04/20.04/
