### ISSUE TITLE
request     date and time settings  or automatic time zone  

### ISSUE THREAD

**Issue by WeiLiPenguin** [sameersbn/docker-gitlab#77]
Hi
Thank you for the `docker-gitlab`  first.
I use the GITLAB_BACKUPS=daily, and find the backup file is done by 6:00 am,
If I understand right, my time zone is not as same as yours.
I can ssh to the container and change, but ... 
Is there better way to do this date setup?

**Comment by stayclassychicago** [comment]
Just wanted to offer a variation (or more like a combination) of @sameersbn 's suggestion on how we're doing this

docker run option:
```
-e TZ=${TZ-`readlink /etc/localtime`}
```

And then this initialization is executed in the entrypoint.sh, since our java applications don't use the TZ environment variable:

```
if [ -n ${TZ} ] && [ -f /usr/share/zoneinfo/${TZ} ]; then
  ln -sf /usr/share/zoneinfo/${TZ}  /etc/localtime
fi
```

**Comment by caneraydinbey** [comment]
How can i change jre so  that i dont have to use command because command line doesnot work for my issue. i need to manually update with tzupdate for daylight http://stackoverflow.com/questions/40418187/update-docker-contanier-jre-timezone
