### ISSUE TITLE
Couldn't start Gitlab MySQL

### ISSUE THREAD

**Issue by Kaleesastha** [sameersbn/docker-gitlab#773]
I couldn't able to deploy a new instance using sameersbn/mysql:latest the docker image on another machine with existing setup (Which means existing mysql datas). While deploying it encounters the below error,

ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 104

ERROR 2013 (HY000) at line 1: Lost connection to MySQL server during query

Docker details-

Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-108.el7.centos.x86_64
Go version (client): go1.4.2
Git commit (client): 3043001/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Package Version (server): docker-1.7.1-108.el7.centos.x86_64
Go version (server): go1.4.2
Git commit (server): 3043001/1.7.1
OS/Arch (server): linux/amd64

Machine Details-

CentOS Linux release 7.0.1406 (Core)

Linux localhost 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux.

Do you need any other info kindly let me know and help me to resolve the above issue.

Thanks,

Kalesastha

**Comment by Kaleesastha** [comment]
Team,

          Any updates .???

Thanks,

Kalesastha

**Comment by SolidNerd** [comment]
Hey,

sorry for the late response. I need more information about your Setup. Do you use `docker-compose`and when it's true could you post your `docker-compose.yml`

**Comment by SolidNerd** [comment]
I tested with the official mysql image `mysql:5.7.13` and it works as excepted.

**Comment by Kaleesastha** [comment]
SolidNerd,

               Thanks for your response. The above mentioned issue had fixed . The issue was due to the existing mysql folder was not properly copied into another machine. 

Thanks,

Kalesastha
