### ISSUE TITLE
Jenkins not available in Service Templates version: sameersbn/gitlab:8.8.5-1

### ISSUE THREAD

**Issue by lethe3000** [sameersbn/docker-gitlab#776]
I'm running with images:
sameersbn/gitlab:8.8.5-1
sameersbn/postgresql:9.4-18
sameersbn/redis:latest

but in `admin` -> `service templates` list, jenkins template is not available, did I miss some config fields?
Below is the docker-compose file:

```
postgresql:
  restart: always
  image: sameersbn/postgresql:9.4-18
  environment:
    - DB_USER=gitlab
    - DB_PASS=gitlabpassword
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
  volumes:
    - /data/gitlab/postgresql:/var/lib/postgresql
gitlab:
  restart: always
  image: sameersbn/gitlab:8.8.5-1
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "22:22"
  environment:
    - DEBUG=false
    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
    - GITLAB_HOST=gitlab.my.host
    - GITLAB_PORT=80
    - GITLAB_SSH_PORT=22
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false
    - GITLAB_EMAIL=notifications@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com
    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false
  volumes:
    - /data/gitlab/gitlab:/home/git/data
redis:
  restart: always
  image: sameersbn/redis:latest
  volumes:
    - /data/gitlab/redis:/var/lib/redis
```

**Comment by sameersbn** [comment]
This image is built using the GitLab Community Edition. The Jenkins 
integration is part of the GitLab Enterprise Edition offering.

You may find relevant information here:
- https://about.gitlab.com/features/#compare
- http://docs.gitlab.com/ee/integration/jenkins.html

Please close this support request if the issue was resolved. Thanks.

On Monday 04 July 2016 08:15 AM, YiLi wrote:
> I'm running with images:
> sameersbn/gitlab:8.8.5-1
> sameersbn/postgresql:9.4-18
> sameersbn/redis:latest
>
> but in |admin| -> |service templates| list, jenkins template is not
> available, did I miss some config fields?
> Below is the docker-compose file:
> `postgresql:
> restart: always
> image: sameersbn/postgresql:9.4-18
> environment:
> - DB_USER=gitlab
> - DB_PASS=gitlabpassword
> - DB_NAME=gitlabhq_production
> - DB_EXTENSION=pg_trgm
> volumes:
> - /data/gitlab/postgresql:/var/lib/postgresql
> gitlab:
> restart: always
> image: sameersbn/gitlab:8.8.5-1
> links:
> - redis:redisio
> - postgresql:postgresql
> ports:
> - "10080:80"
> - "22:22"
> environment:
> - DEBUG=false
> - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
>
> |- GITLAB_HOST=gitlab.my.host - GITLAB_PORT=80 - GITLAB_SSH_PORT=22 -
> GITLAB_RELATIVE_URL_ROOT= - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true -
> GITLAB_NOTIFY_PUSHER=false - GITLAB_EMAIL=notifications@example.com -
> GITLAB_EMAIL_REPLY_TO=noreply@example.com -
> GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com -
> GITLAB_BACKUP_SCHEDULE=daily - GITLAB_BACKUP_TIME=01:00 -
> SMTP_ENABLED=false - SMTP_DOMAIN=www.example.com -
> SMTP_HOST=smtp.gmail.com - SMTP_PORT=587 - SMTP_USER=mailer@example.com
> - SMTP_PASS=password - SMTP_STARTTLS=true - SMTP_AUTHENTICATION=login -
> IMAP_ENABLED=false - IMAP_HOST=imap.gmail.com - IMAP_PORT=993 -
> IMAP_USER=mailer@example.com - IMAP_PASS=password - IMAP_SSL=true -
> IMAP_STARTTLS=false |
>
> volumes:
> - /data/gitlab/gitlab:/home/git/data
> redis:
> restart: always
> image: sameersbn/redis:latest
> volumes:
> - /data/gitlab/redis:/var/lib/redis`
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sameersbn/docker-gitlab/issues/776>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAZCI5kCyjg5JwPloOcKXsFcn60z09LAks5qSHPfgaJpZM4JEA1t>.
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com

**Comment by lethe3000** [comment]
thanks very much, close now.
