### ISSUE TITLE
Wrong tag in dockerhub

### ISSUE THREAD

**Issue by lekoder** [sameersbn/docker-gitlab#781]
Image which is supposed to be `sameersbn/gitlab:8.9.4` is pushed to dockerhub as `sameersbn/gitlab:v8.9.4`. Typo is either in tag name or README.md,

**Comment by medokin** [comment]
Oh, someone was faster. 
Anyway, we have already upgraded for security reasons.

**Comment by sameersbn** [comment]
fixed https://github.com/sameersbn/docker-gitlab/releases/tag/8.9.4
