### ISSUE TITLE
HTTPS does not work

### ISSUE THREAD

**Issue by Trefex** [sameersbn/docker-gitlab#784]
Hi,

I am using the 8.9.0 docker image and run it on my Synology in DSM 6.0.

When I start the container, this is the environment.

I have set GITLAB_HTTPS, however nothing is running or listeninng on that port inside the container.

Any ideas?

```
root@synology_gitlab:/etc/docker-gitlab/build# printenv
REDISIO_ENV_REDIS_USER=redis
REDISIO_PORT_6379_TCP_PROTO=tcp
DB_HOST=172.17.0.1
GOLANG_VERSION=1.5.3
HOSTNAME=synology_gitlab
DB_NAME=gitlab
GITLAB_HOME=/home/git
DB_PASS=xxxxxxx
TERM=xterm
GITLAB_SSH_PORT=30001
GITLAB_SHELL_VERSION=3.0.0
DB_TYPE=mysql
REDISIO_NAME=/synology_gitlab/redisio
SSL_SELF_SIGNED=false
GITLAB_SHELL_INSTALL_DIR=/home/git/gitlab-shell
GITLAB_PORT=30000
REDISIO_PORT_6379_TCP_ADDR=172.17.0.2
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
SMTP_PORT=587
REDISIO_ENV_REDIS_LOG_DIR=/var/log/redis
SMTP_USER=
SMTP_PASS=
REDISIO_PORT_6379_TCP_PORT=6379
SMTP_ENABLED=false
GITLAB_HTTPS=true
SMTP_DOMAIN=
SMTP_OPENSSL_VERIFY_MODE=peer
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GITLAB_EMAIL=trefex@gmail.com
PWD=/etc/docker-gitlab/build
GITLAB_INSTALL_DIR=/home/git/gitlab
SMTP_HOST=
REDISIO_PORT_6379_TCP=tcp://172.17.0.2:6379
GITLAB_RUNTIME_DIR=/etc/docker-gitlab/runtime
GITLAB_WORKHORSE_INSTALL_DIR=/home/git/gitlab-workhorse
GITLAB_BUILD_DIR=/etc/docker-gitlab/build
GITLAB_VERSION=8.9.0
SHLVL=1
HOME=/root
REDISIO_PORT=tcp://172.17.0.2:6379
GITL=myhost.tld
RAILS_ENV=production
UNICORN_TIMEOUT=180
GITLAB_CACHE_DIR=/etc/docker-gitlab
DB_USER=gitlab
GITLAB_DATA_DIR=/home/git/data
LESSOPEN=| /usr/bin/lesspipe %s
GITLAB_WORKHORSE_VERSION=0.7.5
GITLAB_SECRETS_DB_KEY_BASE=xxxxxxxxx
GITLAB_USER=git
GITLAB_LOG_DIR=/var/log/gitlab
REDISIO_ENV_REDIS_DATA_DIR=/var/lib/redis
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/printenv
OLDPWD=/etc/docker-gitlab
```

**Comment by SolidNerd** [comment]
Hey, 
you set your `GITLAB_PORT` to `30000` so your GitLab instance will be reachable via this port. If you have set `GITLAB_HTTPS` to `true`. It will create an nginx ssl sever_block for the `30000` port.

**Comment by Trefex** [comment]
Hi @SolidNerd that's what i do right, so from outside I do https://ip:30000, and if i connect to the docker instance with -it, and do ss -lunt, i can only see ports listening on 80 and 22. However, all documentations I saw said to change the external port mapping from 30000->80 to 30000->443. If I use the former it will say, can't serve SSL content. If I use the latter, it can't connect.

Not sure what's wrong :(

**Comment by SolidNerd** [comment]
I forget something to say. You need to change you port mapping from the container for example from `-p 80:80` to `-p 30000:80` as well. If you do that everything should work.

**Comment by Trefex** [comment]
I do that too of course. But SSL still doesn't work. I put certificates of course in right place.

**Comment by helt** [comment]
maybe publish 443 ?

anyways, @Trefex do you use the gitlab package by synology, or did you set up gitlab yourself?

**Comment by pilla** [comment]
I have the same issue, sameersbn/gitlab:8.15.2. I have run a bash shell inside the container and verified that GITLAB_HTTPS=true. netstat inside the container says that port 80 is open (the HTTP server is working) but there is no mention to 443.

**Comment by hhue13** [comment]
I'm facing the same problem with the following environment settings in my compose file:
    - GITLAB_HTTPS=true
    - SSL_SELF_SIGNED=false
    - GITLAB_HOST=localhost
    - GITLAB_PORT=10443
    - GITLAB_SSH_PORT=10022

and the nginx.conf does not have any config entries related to SSL. Can't get port 443 into LISTEN mode.

**Comment by hhue13** [comment]
OK .. could fix that by creating the certificates. Thought when using SSL_SELF_SIGNED the certificate would be created. Extended the container via a wrapper to generate the certificate and copy the the proper location via a custom entrypoint script which then call the /sbin/entrypoint.sh from the original container.

**Comment by Trefex** [comment]
Any update on this?

**Comment by Trefex** [comment]
I figured it out.

After setting the variables, i manually enter the docker container and run /sbin/entrypoint.sh app:init and then it worked !
