### ISSUE TITLE
How to use external MySQL database in docker-compose.yml

### ISSUE THREAD

**Issue by lilewis** [sameersbn/docker-gitlab#805]
please help me~

**Comment by Beanben** [comment]
Can anyone help me with this? @lijiapengsa did you figured out anything? If so please guide me.

**Comment by lijiapengsa** [comment]
docker run ....
--env 'DB_ADAPTER=mysql2' \
--env 'DB_HOST=192.168.1.248' \
--env 'DB_NAME=gitlabhq_production' \
--env 'DB_USER=gitlab' \
--env 'DB_PASS=password' \
 ....
