### ISSUE TITLE
Redis versioning

### ISSUE THREAD

**Issue by QuickJack** [sameersbn/docker-gitlab#809]
docker-gitlab uses 3 docker images by default. The gitlab and postgresql images are using a clear version number. However the redist container uses the latest tag. Suppose we would like to restore an old backup based on version 6. This requires to setup an empty GitLab instance which has exactly the same version as used in the backup. Using „docker pull sameersbn/redis:latest“ we pull the latest version of redis which might not be compatible with our old backup of version 6.

Wouldn't it be better to specify a clear version number for the redis image, too? This way we could re-create any version of GitLab at any point in time.

**Comment by mahzoun** [comment]
I think the version of redis doesn't matter, it's easy to restore from backup, all you need is to place the backup file `[TIME_STAMP]_gitlab_backup.tar` in backups folder of container and run `bundle exec rake gitlab:backup:restore RAILS_ENV=production` as git. if you got any trouble run `bundle exec rake gitlab:check RAILS_ENV=production`

**Comment by QuickJack** [comment]
Thanks I am already familiar with the backup/restore process. I do not know how redis is used behind the scenes. But it should be clear that each and every software component evolves over time. I it nearly impossible to guarantee that there will never be breaking changes. I always fear that there is a chance of loosing data when trying to restore a backup to a new server instance that uses the redis:latest component which might be newer than expected. I think it is simply a matter of time until this process would cause incompatibility problems if there wouldn't be a clear versioning scheme for the redis part.

**Comment by SolidNerd** [comment]
Hey,
redis will be used for communication between `gitlab-shell` and `sidekiq`. `sameersbn/redis` is a trustry ubuntu image .The redis version that will be used in there is `2.8.4`.Because it will be installed via package manager it's a bit harder to tag the image with version. The version can only determined via runtime so taging is a little bit complex. If you want use a versioned redis image use the official one with the same config from `sameersbn/redis` dockerfile. This should work as well.

**Comment by QuickJack** [comment]
By looking into https://github.com/sameersbn/docker-redis/blob/master/Dockerfile I see, that the image is based on Trusty's redis-server package which is currently at 2.8.4-2. For Xenial it's currently 3.0.6-1. The update to Xenial would happen anytime soon or later. The question is wheter these versions can simply be exchanged for each other without hitting incompatibility problems.
