### ISSUE TITLE
Source Branch Doesn't exists..

### ISSUE THREAD

**Issue by Kaleesastha** [sameersbn/docker-gitlab#812]
We deployed and hosted gitlab in a instance model ( Docker image https://github.com/sameersbn/docker-gitlab/ ) Couple of days before i migrated the GitLab CE version from 8.8.4 to 8.9.6 , in this migration i have been facing such issues and it's listed below -

i) In Existing MR doesn't update the latest commit .

ii) New branches not getting listed in a browser which is pushed via commandline . This error is fixed by cache clear command inside gitlab directory. BTW, everytime we need to do like this .?

Appreciate suggestions about why this might be happening or how to troubleshoot.

Thanks, Kaleeswaran N

**Comment by SolidNerd** [comment]
Hey,
cache clear will happen when you restart the container. Your described problems seems for me asset caching issues. This should be resolved after you restart the container. Otherwise I could be a problem in the upstream. I will close this than now.
