### ISSUE TITLE
SMTP Not working

### ISSUE THREAD

**Issue by hsitaa** [sameersbn/docker-gitlab#816]
Its not Working. Specified the conf. Do i need to expose any port in Docker compose yml.

my Host machine : Centos7
running it on Docker for gitlab,

mails are working for Host machine. But when try to send mail from gitlab. Nothing happens.

1.) Do i need to install postfix on Docker machine?
2.) Do i need to expose any port.
3.) Tried using Gmail smtp as well as extrernal mailserver. : Which 1 suggested?

**Comment by hsitaa** [comment]
@sameersbn @mikew 

Please help

**Comment by mikew** [comment]
Where is the server hosted? EC2? Is port 25 open?

**Comment by hsitaa** [comment]
No Local Hosted Server , but can send mail through Terminal.  Yes Port 25 is open.

**Comment by lazyfrosch** [comment]
@hsitaa what have you configured for the `SMTP_*` environment variables?

**Comment by hsitaa** [comment]
- SMTP_ENABLED=true
    - SMTP_DOMAIN=example.com  = our company domain
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=465
    - SMTP_USER={{email}}  = gmail id
    - SMTP_PASS={{pass}}   = gmail pass
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=plain
@lazyfrosch

**Comment by hsitaa** [comment]
Anyone any Idea ?

**Comment by lazyfrosch** [comment]
Im relaying locally, and don't have problems:

```
GITLAB_EMAIL=info@example.com
SMTP_ENABLED=true
SMTP_DOMAIN=example.com
SMTP_HOST=host.example.com
SMTP_PORT=25
```

With your config and my gmail account I see the following error in Background jobs:

    EOFError: end of file reached

Your mistake is with the SSL settings, you will need:

    #SMTP_STARTTLS=true
    SMTP_SSL=true

Port 465 is a normal TLS connection, no STARTTLS used there (which would be on port 25).

**Comment by patrickc91** [comment]
@hsitaa Did you ever get this issue resolved?

**Comment by sameersbn** [comment]
can you update the status? were you able to resolve the issue?

**Comment by dh1tw** [comment]
I have the same problem. Emails don´t get delivered.

**Comment by SolidNerd** [comment]
@dh1tw  Could you post your SMTP envvar's. So we can check it.

**Comment by sameersbn** [comment]
@dh1tw @hsitaa It would help if you could provide some basic information about your mail delivery system. 

Anyways, I think this is a basic configuration issue. Consider looking through past mail delivery issues. I'm sure you'll find an answer.

- https://github.com/sameersbn/docker-gitlab/issues?utf8=%E2%9C%93&q=is%3Aissue%20sendmail
- https://github.com/sameersbn/docker-gitlab/issues?utf8=%E2%9C%93&q=is%3Aissue%20smtp
- https://github.com/sameersbn/docker-gitlab/issues?utf8=%E2%9C%93&q=is%3Aissue%20email

**Comment by YahirAlejandro** [comment]
Worked for me when set:

```
gitlab_rails['smtp_enable_starttls_auto'] = false
gitlab_rails['smtp_tls'] = false
```
Since I wasn't using TLS.
Also:

`gitlab_rails['smtp_authentication'] = "plain"`

Worth notting that I'm using a GoDaddy domain.

Hope that helps.

**Comment by slim12kg** [comment]
@YahirAlejandro  What smpt prt 25 or 465

**Comment by hsitaa** [comment]
Apologies for delayed response. I changed the setting to relay from mailserver instead Gmail SMTP. and also whitelisted gitlab server at mailserver . It worked. Thanks for all the help @sameersbn @patrickc91
