### ISSUE TITLE
HTTPS/SSL not work! Not use load balancer.

### ISSUE THREAD

**Issue by kanlidy** [sameersbn/docker-gitlab#820]
### 1. follow the instruction:

    openssl genrsa -out gitlab.key 2048
    openssl req -new -key gitlab.key -out gitlab.csr
    openssl x509 -req -days 3650 -in gitlab.csr -signkey gitlab.key -out gitlab.crt
    openssl dhparam -out dhparam.pem 2048

    mkdir -p /srv/docker/gitlab/gitlab/certs
    cp gitlab.key /srv/docker/gitlab/gitlab/certs/
    cp gitlab.crt /srv/docker/gitlab/gitlab/certs/
    cp dhparam.pem /srv/docker/gitlab/gitlab/certs/
    chmod 400 /srv/docker/gitlab/gitlab/certs/gitlab.key

Add crt to my chrome HTTPS/SSL management. 

got error: NET::ERR_CERT_COMMON_NAME_INVALID.

### 2. here is my docker-compose.yml file:

	  gitlab:
	    container_name: "mygitlab"
	    restart: always
	    image: sameersbn/gitlab:8.9.5
	    depends_on:
	    - redis
	    - postgresql
	    ports:
	    - "12299:22"
	    - "12300:80"
	    volumes:
	    - /srv/docker/gitlab/gitlab:/home/git/data:Z

	    - GITLAB_HTTPS=true
	    - SSL_SELF_SIGNED=true

	    - SSL_KEY_PATH=/home/git/data/certs/gitlab.key
	    - SSL_DHPARAM_PATH=/home/git/data/certs/dhparam.pem
	    - SSL_CERTIFICATE_PATH=/home/git/data/certs/gitlab.crt
	    - NGINX_HSTS_MAXAGE=2592000

	    - GITLAB_HOST=publicamms.oicp.net
	    - GITLAB_PORT=12300
	    - GITLAB_SSH_PORT=12299
	    - GITLAB_RELATIVE_URL_ROOT=

**Comment by kanlidy** [comment]
ports:
    - "12299:22"
    - "12300:443"

I've tried 443 port, still not working

**Comment by SolidNerd** [comment]
Hey,
` NET::ERR_CERT_COMMON_NAME_INVALID.` means that your common name that you entered during the private key sigin is not equalivalent to `GITLAB_HOST`. I tested it and it works for me. 

Here is my `docker-compose.yml`:
```
version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - ./redis:/var/lib/redis:Z
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.4-24
    volumes:
    - ./postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm

  gitlab:
    restart: always
    image: sameersbn/gitlab:8.9.5
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:443"
    - "10022:22"
    volumes:
    - ./gitlab:/home/git/data:Z
    - ./logs:/var/log/gitlab
    environment:
    - DEBUG=false

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - GITLAB_HTTPS=true
    - SSL_SELF_SIGNED=true

    - SSL_KEY_PATH=/home/git/data/certs/gitlab.key
    - SSL_DHPARAM_PATH=/home/git/data/certs/dhparam.pem
    - SSL_CERTIFICATE_PATH=/home/git/data/certs/gitlab.crt

    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - GITLAB_SSH_PORT=1022
    - GITLAB_PORT=10080
    - GITLAB_HOST=gitlab.endor.dev

    - GITLAB_SECRETS_DB_KEY_BASE=superrandomsecret
```

Here is a part of  my `gitlab.crt`:
```
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            ad:36:d8:c8:00:43:70:f4
        Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=DE, ST=DE, L=DE, O=DE, OU=DE, CN=gitlab.endor.dev
        Validity
            Not Before: Jul 31 07:48:39 2016 GMT
            Not After : Jul 29 07:48:39 2026 GMT
        Subject: C=DE, ST=DE, L=DE, O=DE, OU=DE, CN=gitlab.endor.dev
...
```

As you can see in Subject of the certificate the *CN* Key stands for *Common Name* and it's equivalent to `GITLAB_HOST` .

**Comment by kanlidy** [comment]
root@ubuntu:/home/liwei/ssl# openssl x509 -in gitlab.crt -text -noout
    Certificate:
        Data:
            Version: 1 (0x0)
            Serial Number: 10093399534452036769 (0x8c12f566431b54a1)
        Signature Algorithm: sha256WithRSAEncryption
            Issuer: C=CN, ST=Hubei, L=Wuhan, O=Wayearn Ltd, OU=Wayearn, CN=Wayearn/emailAddress=lw96@live.com
            Validity
                Not Before: Jul 30 13:19:49 2016 GMT
                Not After : Jul 28 13:19:49 2026 GMT
            Subject: C=CN, ST=Hubei, L=Wuhan, O=Wayearn Ltd, OU=Wayearn, CN=Wayearn/emailAddress=lw96@live.com
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    Public-Key: (2048 bit)

Thanks a lot, you have solved my problem. Thank you. @SolidNerd
