### ISSUE TITLE
Google oauth - invalid hosted domain error

### ISSUE THREAD

**Issue by Estebanv** [sameersbn/docker-gitlab#822]
Hi,
Im getting this error message (invalid hosted domain) when trying to log using my gmail account on 8.10.2. 
it seems that gitlab doesnt like the restricted domain var empty (OAUTH_GOOGLE_RESTRICT_DOMAIN).
If i dont set that var, the config.ym,l file loks like this:

- { name: 'google_oauth2',
         label: 'Google',
         app_id: 'xxxx',
         app_secret: 'xxxx',
         args: { access_type: 'offline', approval_prompt: '', hd: [] } }

when i delete the hd arg it works just fine:

- { name: 'google_oauth2',
         label: 'Google',
         app_id: 'xxxx',
         app_secret: 'xxxx',
         args: { access_type: 'offline', approval_prompt: ''} }

Thanks in advance for any help you can provide.

**Comment by SolidNerd** [comment]
Thanks for your issue. I will resolve this asap.

**Comment by SolidNerd** [comment]
@Estebanv I fixed it and it works for me. Please pull `latest` when the build is done (https://hub.docker.com/r/sameersbn/gitlab/builds/).

@achretien Could you test it with `latest` as well to verify that multiple domains like you implemented it. It would be nice.

I will close this issue than later.

**Comment by gunr2171** [comment]
It seems that this change went public, however it's only on the "latest" tag. Could you make a `8.10.2-1` tag so that I can keep using explicit version numbers in my docker-compose file?

![image](https://cloud.githubusercontent.com/assets/8290105/17315415/4c0859c4-5839-11e6-9028-70abc14871a6.png)

**Comment by achretien** [comment]
Ok on the latest. The config file is generated correctly. Sorry for the issue @gunr2171 .

You can create the `8.10.2-1` tag for fix

**Comment by SolidNerd** [comment]
Okay. It's created wait for the tag. I will close this issue now. If the issue still exists please reopen this issue @Estebanv .

**Comment by gunr2171** [comment]
The `8.10.2-1` tag fixes the error for me. Thanks for the quick turn around.

Just a note, the other files on this repository haven't been updated for the new tag (the main readme, docker-compose example, kubernetes, etc).

**Comment by Estebanv** [comment]
Works fine for me. Thanks a lot Niclas.

**Comment by sameersbn** [comment]
Sorry that I haven't been very active on this repo. Thanks for the amazing work @SolidNerd. I hope you continue the excellent work while i tend to the other repo's that need some love.
