### ISSUE TITLE
Upgrade path from 8.0.5 to 8.10.6

### ISSUE THREAD

**Issue by faultylee** [sameersbn/docker-gitlab#844]
Hi, great work for this great dockerized gitlab.

I plan to upgrade gitlab from 8.0.5 to 8.10.6 and postgres from 9.4-12 to 9.5. I only managed to schedule a downtime this afternoon to do the upgrade. I've been following this repo on the issues to get a pulse on possible problems. I do aware of the postgres requirement and some of the env changes. These are the steps I planned to take:
- stop gitlab, run backup
- stop redis then postgres
- upgrade postgres & redis
- start postgres & redis
- upgrade & start gitlab

Just to be sure, is it advisable to upgrade directly from 8.0.5 to 8.10.6 or is there any intermediate version I should go through? 

Thanks in advance :)

**Comment by SolidNerd** [comment]
So far as I know you should upgrade to `8.0.5-1` as first step. Than you should be able to upgrade to 8.10.6 . Another important point is that since GitLab `8.6.0` the pg_trm extension is required for GitLab. So add to your postgresql environment variable `DB_EXTENSION=pg_trgm`. Your plan looks good to me. So I hope that I can help you. Please give us feedback when you have it done or report it to this issue. After your Upgrade was successful and you have wrote your feedback. Close this issue.

**Comment by faultylee** [comment]
Thanks @SolidNerd for the quick reply. I was indeed in `8.0.5-1`. 

I ran into some issues (self inflicted one). Just sharing in case someone else bumped into this. I migrated from using docker cmdline to compose v2. I missed the volume for gitlab itself, hence after upgrading, which went smoothly, all repo appears empty. I did some checking and corrected the problem. As I recall there's a migration step for git, so to avoid potential issue, I restore from backup and start again. 

Restoring presented with another problem, I still the have old `8.0.5-1` image, so I follow the usual restore steps which I've done once when I upgraded to `8.0.5-1` from `7.14.3`. It errored `Please configure the database connection.` and later similarly for redis. Probably cause by the upgraded postgres and redis, although I use the same env values. I found the error message coming for a validation check in `function`. I had to manually put in `DB_HOST`, `DB_USER` & `REDIS_HOST`. After that db migration failed during upgrade due to duplicate tables. Probably the restore only drop old tables from 8.0.5. So I renamed the db, create a new one, restore then upgrade. Now getting `ERROR: permission denied to create extension "pg_trgm"`. Found the solution [here](https://github.com/sameersbn/docker-gitlab/issues/115). Then finally it's up.

I'm curious on the first upgrade I didn't ran into permission issue with create extension.

Btw, I noticed that `NGINX_MAX_UPLOAD_SIZE` was removed, assuming it was replaced with `GITLAB_MAX_OBJECT_SIZE`. Might be good to mention in the config description for those who upgrade from older version like me. Might also be good to keep a list of deprecated config at the bottom for reference. Another change that I noticed is `DB_TYPE` to `DB_ADAPTER`. `DB_USER`

I use this to check what changed: [https://github.com/sameersbn/docker-gitlab/compare/0fc158823aa5cbc44f709e6037d3336c0ba3cc94...7829e50f44e2cf71cf0c46be57b29653530c8a28#files_bucket] The reason I didn't compare with master is that the diff didn't work when the config was replace with a table format.

**Comment by SolidNerd** [comment]
Thanks for you detailed feedback ❤️ . I hope you could upgrade successfully. You are right `NGINX_MAX_UPLOAD_SIZE` is replaced with `GITLAB_MAX_OBJECT_SIZE` this happened during `8.3.0` update. Yeah all `DB_*` and `REDIS_*` variables are required during the docker-compose v2 update. This happened because we run this as independent services.

**Comment by faultylee** [comment]
I'm seeing this 
```
gitlab-postgresql    | Initializing datadir...
gitlab-postgresql    | Initializing certdir...
gitlab-postgresql    | Initializing logdir...
gitlab-postgresql    | Initializing rundir...
gitlab-postgresql    | Setting resolv.conf ACLs...
gitlab-postgresql    | Creating database user: gitlab
gitlab-postgresql    | Creating database: gitlabhq_production...
gitlab-postgresql    | ‣ Loading pg_trgm extension...
gitlab-postgresql    | ‣ Granting access to gitlab user...
gitlab-postgresql    | Starting PostgreSQL 9.5...
gitlab-postgresql    | LOG:  database system was shut down at 2016-08-20 01:09:22 UTC
gitlab-postgresql    | LOG:  MultiXact member wraparound protections are now enabled
gitlab-postgresql    | LOG:  autovacuum launcher started
gitlab-postgresql    | LOG:  database system is ready to accept connections
```
on every restart of the postgresql container, I then proceed to remove `DB_USER`, `DB_PASS` & `DB_NAME`.

**Comment by faultylee** [comment]
All seems to be good now
