### ISSUE TITLE
500 Internal server error in project main page

### ISSUE THREAD

**Issue by tomasdelvechio** [sameersbn/docker-gitlab#845]
Hello, a few days ago, our gitlab install start to show error 500 when access to some projects.

For example, the page `http://gitlab.myorganization.com/<user>/<project>` raise error 500, but the subpaths, like `http://gitlab.myorganization.com/<user>/<project>/activity`, `http://gitlab.myorganization.com/<user>/<project>/tree/master` still work.

The `production.log` file show the next output:

```
Started GET "/<user>/<project>" for 170.210.96.68 at 2016-08-19 13:55:02 +0000
Processing by ProjectsController#show as HTML
Parameters: {"namespace_id"=>"<user>", "id"=>"<project>"}
Completed 500 Internal Server Error in 133ms (ActiveRecord: 11.7ms)
OpenSSL::Cipher::CipherError (bad decrypt):
app/models/project.rb:487:in `import_url'
app/models/project.rb:523:in `external_import?'
app/models/project.rb:515:in `import?'
app/models/project.rb:531:in `import_in_progress?'
app/controllers/projects_controller.rb:94:in `show'
lib/gitlab/middleware/go.rb:16:in `call'
```

I search in gitlab forums and issues, and I found [that issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/16999), but I don't understand the solution.

**Comment by SolidNerd** [comment]
Hey, 
i need some more information about your system. Which GitLab version do you use ?

**Comment by tomasdelvechio** [comment]
Sorry! The first error was detected in [8.10.5](https://github.com/sameersbn/docker-gitlab/releases/tag/8.10.5) but today I migrate to [8.10.6](https://github.com/sameersbn/docker-gitlab/releases/tag/8.10.6), and the the problem won't fixed.

**Comment by SolidNerd** [comment]
It seems that your `GITLAB_SECRETS_DB_KEY_BASE` is shorter than 32 characters. So check this please. If this is true you need to update your projects. Before you do this make an backup. After this you can run a command for it.

**Comment by tomasdelvechio** [comment]
Hi, my `GITLAB_SECRETS_DB_KEY_BASE` has 64 characters.

**Comment by tomasdelvechio** [comment]
Hello, sorry for this issue. I did a mistake, changing a few weeks ago the `GITLAB_SECRETS_DB_KEY_BASE` var. 

The solution to fixed my problem I found [here](https://gitlab.com/gitlab-org/gitlab-ce/issues/16999#note_11709073).
