### ISSUE TITLE
gitlab  restore  fails

### ISSUE THREAD

**Issue by yujianglei** [sameersbn/docker-gitlab#854]
HI:
     
    I have a problem whit gitlab.  help,help,help.  Follow logs:

## Unpacking backup ... done
Do you want to continue (yes/no)? yes
Removing all tables. Press `Ctrl-C` within 5 seconds to abort
Cleaning the database ...
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'keys CASCADE' at line 1: DROP TABLE IF EXISTS keys CASCADE
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `query'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/home/git/gitlab/config/initializers/connection_fix.rb:20:in `execute'
/home/git/gitlab/lib/tasks/gitlab/db.rake:37:in `block (4 levels) in <top (required)>'
/home/git/gitlab/lib/tasks/gitlab/db.rake:37:in `each'
/home/git/gitlab/lib/tasks/gitlab/db.rake:37:in `block (3 levels) in <top (required)>'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:49:in `block (3 levels) in <top (required)>'
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'keys CASCADE' at line 1
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `query'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/home/git/gitlab/config/initializers/connection_fix.rb:20:in `execute'
/home/git/gitlab/lib/tasks/gitlab/db.rake:37:in `block (4 levels) in <top (required)>'
/home/git/gitlab/lib/tasks/gitlab/db.rake:37:in `each'
/home/git/gitlab/lib/tasks/gitlab/db.rake:37:in `block (3 levels) in <top (required)>'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:49:in `block (3 levels) in <top (required)>'
Tasks: TOP => gitlab:db:drop_tables
(See full trace by running task with --trace)

**Comment by SolidNerd** [comment]
Hey, 
this seems to be an old error from the upstream. Which version do you run at the moment ?

**Comment by yujianglei** [comment]
8.8.5

**Comment by SolidNerd** [comment]
Hey,

i did some research and I found out that it's a problem in this version. Here is the related issue that i found for your problem https://gitlab.com/gitlab-org/gitlab-ce/issues/18403 .

**Comment by yujianglei** [comment]
Hey,
thx
