### ISSUE TITLE
runner output not shown on https only site (Mixed Content)

### ISSUE THREAD

**Issue by hoto** [sameersbn/docker-gitlab#858]
Hi

We upgraded from gtilab v8.6 or something to v8.10.7 (bf9e01b).  
We are using this command to start gitlab:

```
/usr/bin/docker run \
  -p 8030:80 -p 22:22 \
  --link redis:redisio \
  --env='SMTP_ENABLED=true' \
  --env='SMTP_DOMAIN=mycompany.com' \
  --env='SMTP_HOST=myloadbalancer.elb.amazonaws.com' \
  --env='SMTP_PORT=25' \
  --env='GITLAB_HOST=gitlab.mycompany.com' \
  --env='GITLAB_SECRETS_DB_KEY_BASE=xxx' \
  --env 'DB_ADAPTER=postgresql' \
  --env 'DB_HOST=rds.rds.amazonaws.com' \
  --env 'DB_NAME=gitlabhq_production' \
  --env 'DB_USER=gitlab' \
  --env 'DB_PASS=xxx' \
  -e SERVICE_22_NAME=gitlab-ssh \
  -e SERVICE_80_NAME=gitlab \
  -e SERVICE_ID=gitlab \
  --volume-driver=convoy \
  --dns=${XXX} \
  --dns-search=${XXX} \
  -v gitlab_mgmt:/home/git/data/ \
  -v gitlab_log_mgmt:/var/log/gitlab \
  --name=gitlab sameersbn/gitlab:8.10.7
```
We open gitlab in browser by `https://gitlab.mycompany.com/mygroup/myproject/builds/18241`
Everything works but the logs from builds are not loading.   
On the Chrome console we got this error:

```
application-24068fc….js:3 Mixed Content: 
The page at 'https://gitlab.mycompany.com/mygroup/myproject/builds/18379' 
was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 
'http://gitlab.mycompany.com/mygroup/myproject/builds/18379.json'. 
This request has been blocked; the content must be served over HTTPS.
```

We can click "RAW" to show logs and it works.  
We can also manually enter the `XMLHttpRequest` `http://gitlab.mycompany.com/mygroup/myproject/builds/18379.json` url in browser and it will redirect to https and we get a json with build logs.

My question is should we set the `GITLAB_HTTPS=true` and also `GITLAB_PORT` variables?  
We tried to set it to true, but then it just redirects forever.  
We just upgraded gitlab without changing any of the configuration so I'm wondering if something changed with getting those logs and we need to change our configuration now?

![gitlab](https://cloud.githubusercontent.com/assets/3105832/17909653/afad013e-6985-11e6-902b-7683fa73fa6f.png)

I also posted this issue here: https://gitlab.com/gitlab-org/gitlab-ce/issues/19422 as I'm not sure where to put it.

Thanks
Andrzej

**Comment by SolidNerd** [comment]
Hey, 
it seems that you don't set `GITLAB_HTTPS ` to `true`. This let GitLab know that it's running under https. This could lead to an mixed content. If this not solves your problem let me know and we will make a deeper investigation.

**Comment by Kiina** [comment]
I had the same problem, i just added proxy_set_header X-Forwarded-Ssl on; to my nginx and set GITLAB_HTTPS to false and it worked for whatever reason. maybe it will help you

**Comment by hoto** [comment]
We could not resolve this, we tried many different configurations but this still persists. We just click `View raw logs` as a workaround for now.
It's definitely something wrong with our configuration though, as no one else is complaing about this. Closing this one as unresolved. Thanks for help everyone :)
