### ISSUE TITLE
Upgraded from 8.9.4 to 8.11.0. Cannot access main project page

### ISSUE THREAD

**Issue by stephenjbarr** [sameersbn/docker-gitlab#861]
I just upgraded from 8.9.4 to 8.11.0. If I go to my project page, e.g. 

http://git.example.com:10080/stephenjbarr/some-existing-project

for some-existing-project, which existed before the upgrade, then I get the "500 Something Went Wrong" error.

However, if I create a new project, I can visit the page, 

http://git.example.com:10080/stephenjbarr/new-project

Is this an existing issue? How can I go about diagnosing this?

**Comment by torvitas** [comment]
Could you post the production.log somewhere?

**Comment by stephenjbarr** [comment]
Here is the relevant section:

```
Started GET "/sbarr/abstraction/" for 23.25.128.217 at 2016-08-25 22:05:47 +0000
Processing by ProjectsController#show as HTML
  Parameters: {"namespace_id"=>"sbarr", "id"=>"abstraction"}
Completed 500 Internal Server Error in 48ms (ActiveRecord: 4.8ms)

OpenSSL::Cipher::CipherError (bad decrypt):
  app/models/project.rb:491:in `import_url'
  app/models/project.rb:527:in `external_import?'
  app/models/project.rb:519:in `import?'
  app/models/project.rb:535:in `import_in_progress?'
  app/controllers/projects_controller.rb:94:in `show'
  lib/gitlab/request_profiler/middleware.rb:15:in `call'
  lib/gitlab/middleware/go.rb:16:in `call'
```

**Comment by stephenjbarr** [comment]
Note, when I upgraded, I added the following environment variables:

GITLAB_SECRETS_SECRET_KEY_BASE
GITLAB_SECRETS_DB_KEY_BASE
GITLAB_SECRETS_OTP_KEY_BASE

accompanied with 64 bit values.

**Comment by torvitas** [comment]
Same here, same error.

**Comment by SolidNerd** [comment]
Hey,
did you change your `GITLAB_SECRETS_DB_KEY_BASE` to another value from `8.9.4` ?

**Comment by stephenjbarr** [comment]
@SolidNerd Yes, I made a mistake. I had 2 entries for `GITLAB_SECRETS_DB_KEY_BASE`. I removed the new one and kept the old value, and things work working well now.
