### ISSUE TITLE
That's a errors  when  I visit my project that  restore via docker container  

### ISSUE THREAD

**Issue by yujianglei** [sameersbn/docker-gitlab#866]
Environment:
        docker-1.12.1
        gitlab:8.8.5
        mysql:latest
        redis:latest

ERROR:

Whoops, something went wrong on our end.

Try refreshing the page, or going back and attempting the action again.

Please contact your GitLab administrator if this problem persists.

**Comment by torvitas** [comment]
Hi,

could you please post your production.log ?

Greetings

**Comment by rakesh-k** [comment]
facing the same issue. I am getting this in the log:
```

ActiveRecord::StatementInvalid (PG::InsufficientPrivilege: ERROR:  could not open file "base/16385/17328": Permission denied
: SELECT "tags".* FROM "tags" INNER JOIN "taggings" ON "tags"."id" = "taggings"."tag_id" WHERE "taggings"."taggable_id" = $1 AND "taggings"."taggable_type" = $2 AND (taggings.context = 'tags' AN
D taggings.tagger_id IS NULL)):

```

What should be the right permission and where?

**Comment by yujianglei** [comment]
@torvitas   follow  productions.log:
  
Started GET "/weizhang/smc-cms" for 127.0.0.1 at 2016-09-18 19:58:14 +0800
Processing by ProjectsController#show as HTML
  Parameters: {"namespace_id"=>"weizhang", "id"=>"smc-cms"}
Completed 500 Internal Server Error in 49ms (ActiveRecord: 2.1ms)

OpenSSL::Cipher::CipherError (bad decrypt):
  app/models/project.rb:383:in `import_url'
  app/models/project.rb:413:in `external_import?'
  app/models/project.rb:405:in `import?'
  app/models/project.rb:421:in `import_in_progress?'
  app/controllers/projects_controller.rb:93:in `show'
  lib/gitlab/middleware/go.rb:16:in `call'
