### ISSUE TITLE
how is the docker-registry exposed

### ISSUE THREAD

**Issue by smoebody** [sameersbn/docker-gitlab#868]
Hi, first of all: thanks for the great work. Im using your images for my gitlab-infrastructure for a while now and I am very happy with it.

I was looking forward for container-registry support by your gitlab-images but now i am afraid i cannot use it the way you are providing it, but maybe i don't understand it right. so here are my questions.

it seems like you are providing registry access via docker-gitlab's own nginx instance which is forced to ssl. since i would like to use a seperate nginx-container to provide an ssl-reverse-proxy i would like to just expose the registry through this proxy. is this possible or are the `SSL_REGISTRY_` env vars mandatory?

Im i right with the suggestion that the `GITLAB_REGISTRY_HOST` and `GITLAB_REGISTRY_PORT` env vars are used to feed gitlab with the right information to provide to the frontend user or are they used to configure the nginx-proxy as well?

thanks in advance.

**Comment by SolidNerd** [comment]
Okay, I will try to clarify that. You are right  `SSL_REGISTRY_*`are not mandatory. They will be used to enable a proxy with ssl in the gitlab intern NGINX. It should be the way when you are not using an own proxy.  

`GITLAB_REGISTRY_HOST` and  `GITLAB_REGISTRY_PORT ` will be used for NGINX configuration and to display the correct information in the GitLab frontend. I use my self an external proxy for the registry. It works.

Here is a sample of configuration that I use to realize it:

gitlab_container:
```bash
GITLAB_REGISTRY_ENABLED=true
GITLAB_REGISTRY_HOST=registry.gitlab.example.com
GITLAB_REGISTRY_API_URL=https://registry.gitlab.example.com
GITLAB_REGISTRY_KEY_PATH=/certs/registry_auth.key
GITLAB_REGISTRY_ISSUER=gitlab-issuer
```
registry_container:
```
REGISTRY_LOG_LEVEL=info
REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
REGISTRY_AUTH_TOKEN_REALM=https://gitlab.example.com/jwt/auth
REGISTRY_AUTH_TOKEN_SERVICE=container_registry
REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/registry_auth.crt
REGISTRY_STORAGE_DELETE_ENABLED=true
```

**Comment by smoebody** [comment]
Thanks for the clarification. I will give it a try soon.

Closing.
