### ISSUE TITLE
lose data when I restart the container.

### ISSUE THREAD

**Issue by liiujinfu** [sameersbn/docker-gitlab#872]
hi, when I restart the container, I found that I lost everything I set in gitlab, including accounts, projects and so on， is something wrong with my setting?

**Comment by SolidNerd** [comment]
Hey, 
do you use volumes ? For persistence this is recommend. It seems that you don't mount `/home/git/data` to the host.

**Comment by liiujinfu** [comment]
thanks for anwser.
I use the docker for windows, it may be someting wrong with mountting volume to the host when I set PG, have you any ideas? 
https://forums.docker.com/t/data-directory-var-lib-postgresql-data-pgdata-has-wrong-ownership/17963

**Comment by SolidNerd** [comment]
Have look at this. https://forums.docker.com/t/data-directory-var-lib-postgresql-data-pgdata-has-wrong-ownership/17963/6 Let Docker4Win auto mount the directory and it will work.

**Comment by liiujinfu** [comment]
thank you, it works.
