### ISSUE TITLE
assets/build not found

### ISSUE THREAD

**Issue by zmkhp** [sameersbn/docker-gitlab#873]
When I build the Dockerfile(https://hub.docker.com/r/sameersbn/gitlab/~/dockerfile/) on 8.11.2-1,it occurs "Step5:assets/build/: no such file or directory"
Who can help me?
Thank you very much!

**Comment by SolidNerd** [comment]
You need to clone this repository. There all dependencies for building this docker image.

**Comment by zmkhp** [comment]
@SolidNerd Well Done!Thanks!
