### ISSUE TITLE
How to restore the automatic backup when running via docker-compose?

### ISSUE THREAD

**Issue by techraf** [sameersbn/docker-gitlab#874]
I am running `docker-gitlab` through docker-compose. Works well, creates daily backups.

I am at loss trying to restore the daily backup (at the moment for a test on a separate machine). The docs don't cover this scenario.

I tried running Redis and PostreSQL manually then:
```
docker run --name gitlab -it --rm \
    --volume /srv/docker/gitlab/gitlab:/home/git/data \
    --link gitlab-postgresql:postgresql --link gitlab-redis:redisio \
    --publish 10022:22 --publish 10080:80 \
    --env 'DB_ADAPTER=postgresql' \
    --env 'DB_HOST=postgresql' \
    --env 'DB_PORT=5432' \
    --env 'DB_USER=gitlab' \
    --env 'DB_PASS=password' \
    --env 'DB_NAME=gitlabhq_production' \
    --env 'REDIS_HOST=redis' \
    --env 'REDIS_PORT=6379' \
    --env 'TZ=Asia/Tokyo' \
    --env 'GITLAB_TIMEZONE=Tokyo' \
    sameersbn/gitlab:8.10.5 \
    app:rake gitlab:backup:restore
```

It does some work:
```
Initializing logdir...
Initializing datadir...
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database
Configuring gitlab::redis...........................................................
```

And whatever I do next, I always end up with a prompt to create a new password in GitLab when opening the browser. I assume this is a restore failure.

What are the steps to start with? There is literally zero feedback from the container whether it is restoring something or ignoring me completely.

It's not even clear what to do with the backup file, I assume it should be placed in the same directory as on the original server.

**Comment by SolidNerd** [comment]
Hey, 
you could use docker-compose for restoring the backup this could easily done with:
`docker-compose run --rm gitlab app:rake gitlab:backup:restore BACKUP=1470535244`

Important is here the `BACKUP` environment variable. This determines which backup will be restored. To have a look at `/home/git/data/backups` there are all backups store. The format is the `TimestampUnixTime_gitlab_backup.tar` . Set unixtimestamp value in the `BACKUP` env and it should work. Please shoutdown your gitlab container before you start to restore your backup

**Comment by techraf** [comment]
Works perfect, thank you!

I think I'll suggest an update the readme with your method and more importantly with the info what to expect of the restore procedure (the fact that it asks for confirmation; I need to check why it wasn't asking, but it made me lose much time).
