### ISSUE TITLE
gitlab ci multi runner

### ISSUE THREAD

**Issue by machi1990** [sameersbn/docker-gitlab#900]
Hi, thanks for this project. I have the image up and running however I have got one simple question (A newbie in docker so bare with me).

In my Gitlab's project, I want to be able to use the CI feature. To so I need to have Runners installed and configured for my systems. The question is - how do I install and integrate gitlab-ci-multi-runner?  

I have tried to add the command to do so in the docker-compose.yml file, but the installation fails. Any feedback will be appreciated.

**Comment by solidnerd** [comment]
Hey, 
have look at this documetation https://docs.gitlab.com/ce/ci/runners/README.html. It should help you to setup your runner.

**Comment by machi1990** [comment]
Thanks @solidnerd, to setup the runner is quiet straight forward after having installed the **gitlab-ci-multi-runner**. It's where I was stuck. What I wanted to do, is to install the gitlab-multi-runner tool as soon as my container is up and running. This has to be part of my configuration and **docker-compose up -d** will do the work (installation) for me. Instead of me launching up container's bash and installing it every time.
