### ISSUE TITLE
 "Remember me" login option doesn't work (two factor authentication)

### ISSUE THREAD

**Issue by JacobHenner** [sameersbn/docker-gitlab#901]
When 2FA is enabled, the "remember me" option doesn't seem to work properly, so a new login is necessary if the browser session ends. With 2FA disabled, "remember me" works as expected.

**Comment by solidnerd** [comment]
Hey,
this issue sounds for me that it should be reported in the upstream.

**Comment by JacobHenner** [comment]
@solidnerd I would agree, but it seems to be specific to this package, other users don't report this behavior in GitLab

**Comment by JacobHenner** [comment]
Disabling 2FA and re-enabling it on a per-user basis seems to have fixed this issue for now.
