### ISSUE TITLE
Please add support  config Mattermost parameters

### ISSUE THREAD

**Issue by sencho** [sameersbn/docker-gitlab#903]
Please add support  config Mattermost parameters

**Comment by solidnerd** [comment]
Hey,

what did you mean with support config parameters for Mattermost ? This container doesn't inculde a Mattermost. You need to run a separate mattermost container and configure your mattermost parameters there.

**Comment by sencho** [comment]
I have read the Gitlab documentation ,there is a parameter name mattermost_external_url in file gitlab.rb at /ect/gitlab/gitlab.rb, and need run sudo gitlab-ctl reconfigure.so i need the Mattermost parameters in container.

**Comment by virtuman** [comment]
I've also been trying to figure out the whole mattermost integration. Gitlab says that it ships with mattermost in omnibus image now but it is disabled by default, ie:
http://docs.gitlab.com/omnibus/package-information/defaults.html

Gitlab.com is not overly clear whether mattermost is something like a registry, that has to be activated with the config settings in order to work, but it looks that way? or am I wrong here and it needs to be installed completely separate and point to the externally running mattermost instance?

Could you clarify ?

**Comment by mindriven** [comment]
+1 for implementing it or- if it's out of scope of this project - please clarify where to look for answers.

**Comment by mindriven** [comment]
After some time spent digging around I think I know how the situation looks like. When installing Gitlab from Omnibus package then one gets the boundled-in mattermost. However this repo does installation from sources, so mattermost is not included. Can someone please confirm this?

If I got it correctly this "issue" should be seen as feature request.

**Comment by inful** [comment]
@mindriven mattermost is not included in the sameersbn-gitlab container, but you certainly integrate it when running it in a separate container.

**Comment by reynold-lariza** [comment]
Hmn... 

I have already installed mattermost docker container, its up and running, but there is no parameter to docker-gitlab for it? :|

**Comment by mindriven** [comment]
@reynold-lariza from what I understood integrating these two would require a contribution to this repository. I've read around a bit and it seems like this requires fairly intimate knowledge about gitlab. I was hoping that I can find how instructions from using omnibus package are mapped to docker version, but no success so far.

Can maintainers of this project let us know if this is something we could get in near future. I would love to contribute, but I will need some directions where to start.

**Comment by inful** [comment]
@reynold-lariza Read https://docs.mattermost.com/deployment/sso-gitlab.html
Then build a custom docker container for mattermost where you can pass the values as environment variables.

**Comment by joshuacox** [comment]
I recently built one using this:
https://github.com/joshuacox/mkmattermost

I did not need to pass those values in a environment variables, but I am mounting in configs as volumes.  All mirroring the official mattermost docker repo.  Then you can setup everything using mattermost itself.

**Comment by mindriven** [comment]
How come closed? Resolved or won't fix? Some clarity would be awesome. Thanks!

**Comment by joshuacox** [comment]
@mindriven post an issue in my project [here](https://github.com/joshuacox/mkmattermost). I'd gladly support your options.  I think these guys want to support gitlab only.  And thank you @sameersbn and @inful you guys are doing a great job!!!! I rely on your containers, keep 'em up!
