### ISSUE TITLE
Network Issue

### ISSUE THREAD

**Issue by pradeepasuri** [sameersbn/docker-gitlab#906]
I have increased the size of RAM and CPU, and restarted the machine. 
I am able to login into the server, but unable to open the URL in GUI. It says network error.

**Comment by solidnerd** [comment]
Hey,
could you provide the following information:
- The host distribution and release version.
- Output of the `docker version` command
- Output of the `docker info` command
- The `docker run` command you used to run the image (mask out the sensitive bits).
