### ISSUE TITLE
Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by WebEnd** [sameersbn/docker-gitlab#915]
Hi,

I use GitLab in a docker container that sits behind a nginx proxy

I get the following error when redirecting from SAML authentication
Started POST "/git/users/auth/saml/callback" for IP at 2016-10-03 13:28:35 +0000
Processing by OmniauthCallbacksController#failure as HTML
  Parameters: {"SAMLResponse"=>"......................"}
Can't verify CSRF token authenticity

I have added GITLAB_HTTPS=true to the env
And the following to my nginx server:
    location /git/ {
    proxy_read_timeout      300;
    proxy_connect_timeout   300;
    proxy_redirect          off;
    proxy_http_version 1.1;
    proxy_set_header    Host                $host;
    proxy_set_header    X-Real-IP           $remote_addr;
    proxy_set_header    X-Forwarded-Proto   https;
    proxy_set_header    X-Forwarded-Protocol https;
    proxy_set_header    X-Forwarded-Ssl     on;
    proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_pass http://hstgitlab/git/;
    }

Can you please let me know if I have setup something wrong?
It seems like there is a setting that could help 
nginx[‘listen_https’] = false
but I have no idea how to set this up.

Any help would be greatly appreciated

**Comment by mrusme** [comment]
@WebEnd this should solve your issue: https://gist.github.com/sameersbn/becd1c976c3dc4866ef8

**Comment by WebEnd** [comment]
great ;)
