### ISSUE TITLE
how to reset password?

### ISSUE THREAD

**Issue by ilyadavydyuk** [sameersbn/docker-gitlab#916]
in rake console, when i try find user with id = 1 - i get 'nil'.

**Comment by solidnerd** [comment]
Could you provide more information of your docker setup ?

**Comment by GJRTimmer** [comment]
@ilyadavydyuk is this still an active topic ?
If not could you close the case.

**Comment by waterdrops** [comment]
@ilyadavydyuk plz try this method, perform
1. docker exec -it GITLAB_CONTAINER_ID /bin/bash
2.su - git 
3.cd gitlab
4.bundle exec rails c production
   user = User.find_by_email("ROOT_EMAIL")
   user.password = 'NEW_PASS'
   user.password_confirmation = 'NEW_PASS'
   user.save
   exit
more details, plz refer to https://docs.gitlab.com/ee/security/reset_root_password.html

**Comment by kalaspuffar** [comment]
I only had one user so i got it and made me admin.

```
user = User.first
user.admin = true
user.save!
```

**Comment by hcientist** [comment]
in case anyone else finds this and is having trouble like I was, the other method of finding the root user worked for me. `user = User.where(id: 1).first` (found this in the same page @waterdrops linked to above)
