### ISSUE TITLE
Ruby should contain at least html-pipeline-2.0 to work according to documentation

### ISSUE THREAD

**Issue by zlolik** [sameersbn/docker-gitlab#942]
Look at my comment at https://github.com/gitlabhq/gitlabhq/pull/8007

**Comment by zlolik** [comment]
Request to brightbox: https://groups.google.com/forum/#!topic/brightbox-ruby-ubuntu-packaging/l7uhK7yGHpM

**Comment by zlolik** [comment]
Oops, its about Gitlab installation Gemfile
https://gitlab.com/gitlab-org/gitlab-ce/issues/24039

**Comment by solidnerd** [comment]
Hey, 
i will close this. Because it's a problem in the upstream.
