### ISSUE TITLE
Add option `ipv6only=off` breaks nginx

### ISSUE THREAD

**Issue by splattael** [sameersbn/docker-gitlab#949]
Hi,

as mention in https://github.com/sameersbn/docker-gitlab/commit/deb046a2589d24a70e7b9d4d097ca2a57fe2a273#commitcomment-19679893 adding the option `ipv6only=off` breaks my installation.

Currently, I had to disable it without knowing why :-(

Can someone reproduce the errors I have (see comment link above)?

Do you need more information?

Thanks,
  Peter

**Comment by splattael** [comment]
Oops, this is a duplicate of #945, probably.

**Comment by knight42** [comment]
Same  problem here.

From nginx docs:

>ipv6only=on|off
>this parameter (0.7.42) determines (via the IPV6_V6ONLY socket option) whether an IPv6 socket listening on a wildcard address [::] will accept only IPv6 connections or both IPv6 and IPv4 connections. This parameter is turned on by default. It can only be set once on start.

Therefore nginx will try to bind `0.0.0.0:80` twice if `listen 0.0.0.0:80;` and `listen [::]:80 ipv6only=off` are present in the config, which breaks nginx.

**Comment by solidnerd** [comment]
It will be fixed in `latest` tag. You need only to wait when the build is done have a look at https://hub.docker.com/r/sameersbn/gitlab/builds/  .

**Comment by splattael** [comment]
Works like a charm. Thanks for the quick fix @heximcz :green_heart:

**Comment by heximcz** [comment]
You are welcome :+1:
