### ISSUE TITLE
8.13.2 is broken due 'fix ipv6only'

### ISSUE THREAD

**Issue by GJRTimmer** [sameersbn/docker-gitlab#954]
8.13.1 worked like a charm, after upgrading I received the following 2 errors; there errors are thrown continuously until supervisor restarts nginx.

```nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)```

After a lot of searching I've found the problem. in the following file:
Source: ```docker-gitlab/assets/runtime/config/nginx/gitlab-ssl```
Target Location: ```/etc/nginx/sites-enabled/gitlab```

There are now dual entries for the default server; this prevents nginx from starting, nginx will enter a infinite retry loop.

Fix:
Removed line: ```listen [::]:80 ipv6only=on default_server;```
and line ```listen [::]:443 ipv6only=on ssl http2 default_server;```

these lines are causing an infinite nginx restart.

Anyone suggestion why this is happing ?

**Comment by splattael** [comment]
Good catch! It's already fixed in `master` and will be release with `8.13.3`.

See #945 #949

**Comment by splattael** [comment]
Well actually, it's already fixed in `lastest`.

See https://github.com/sameersbn/docker-gitlab/issues/949#issuecomment-258246075 :-)

**Comment by GJRTimmer** [comment]
Any idea when 8.13.2 will be release ?, I prefer not to use the gat 'latest'

**Comment by splattael** [comment]
@GJRTimmer I have no idea.

In the meantime you *could*:
* use `latest` image
* start your container and change it live in there ;)
* build your own image (even on GitLab CI itself) like I do

**Comment by GJRTimmer** [comment]
8.13.3 fixes the issues.
Tested and confirmed
