### ISSUE TITLE
gitlab data migration failed to get repository

### ISSUE THREAD

**Issue by aeoluswing** [sameersbn/docker-gitlab#966]
after having migrated my gitlab server and restored from the backups,success to log in the new gitlab websites,"no repository" errors occurred.I guess these processes mean gitlab cannot retrieve the git repository.Is there any method which can fix this issue?By the way,docker-gitlab version 8.13.5 and I  think connection with database(postgresql which vesion is 9.5)is correct because of the successful login.

**Comment by aeoluswing** [comment]
Making attempt to import repository will redirect to a '500' error code page.Does this mean gitlab-shell works incorrectly?

**Comment by aeoluswing** [comment]
Having Tried the steps which is Mentioned in [issue 244](https://github.com/sameersbn/docker-gitlab/issues/244),I'm sure the volume mounted successfully and located all my project repositories in the container's path `/home/git/data/repositories`.

**Comment by aeoluswing** [comment]
Thx a lot for help,`rake cache:clear` failed,'cannot load file haml_lint/rake_task' result to a loaderror.Any reason is conceivable,redis' cache state makes task unavailable.An alternative measure which worked for me,oprate redis by cli and process the `FLUSHDB` command to the gitlab redis db,after that restart gitlab container.

**Comment by zwsf** [comment]
tks, solve my question too

**Comment by bienhoang** [comment]
Thanks @aeoluswing for solution on Redis. It's save my life.
