### ISSUE TITLE
Wrong GitHub documentation / Installation of the SSL Certificates

### ISSUE THREAD

**Issue by megian** [sameersbn/docker-gitlab#967]
The documentation on GitHub does not reflect the current situation. [https://github.com/sameersbn/docker-gitlab](https://github.com/sameersbn/docker-gitlab) The section "Installation of the SSL Certificates" says that the directory /srv/docker/gitlab/gitlab/certs/ is the path, the SSL certificates should be placed. But the variables SSL_CERTIFICATE_PATH, SSL_KEY_PATH, SSL_DHPARAM_PATH and SSL_CA_CERTIFICATES_PATH, does point to /home/git/data/certs. I guess the section "Installation of the SSL Certificates" is outdated.

**Comment by splattael** [comment]
The [README states](https://github.com/sameersbn/docker-gitlab#enabling-https-support) that `/srv/docker/gitlab/gitlab` is mounted as `/home/git/data` *inside* the docker container.

So, when talking about `/srv/docker/gitlab/gitlab/certs` the README means the directory *outside* of the container on your host machine. The envvar descriptions refer to the pathes *inside* the docker container.

It's not outdated but might be a bit confusing at first, true.

I hope this helps.
