### ISSUE TITLE
Subgit support

### ISSUE THREAD

**Issue by DarkFranX** [sameersbn/docker-gitlab#970]
Not really an issue, but has anyone thought about adding Subgit support in the container?

**Comment by solidnerd** [comment]
Hey, 

I don't see this because it's not supported by the upstream and our image should be near as possible to the gitlab community edition. If you want to do this feel free to make a fork and implement it by our own. If you need help feel free to ask :) .

**Comment by DarkFranX** [comment]
Understood. Thanks for your reply :)

2016-11-16 14:25 GMT-05:00 Niclas Mietz <notifications@github.com<mailto:notifications@github.com>>:

Hey,

I don't see this because it's not supported by the upstream and our image should be near as possible to the gitlab community edition. If you want to do this feel free to make a fork and implement it by our own. If you need help feel free to ask :) .

**Comment by GJRTimmer** [comment]
@DarkFranX could you close this issue please.
