### ISSUE TITLE
How to backup/restore when using docker-compose

### ISSUE THREAD

**Issue by iamchanghyunpark** [sameersbn/docker-gitlab#987]
Hi, This is a question as well as a suggestion.
The main README.md is well documented in the backups/restore sections when using plain docker.

Is there a way to do it using docker-compose?
Or should I stop docker-compose, remove the docker containers (created by compose), execute the commands in the README.md, then restart docker-compose?

It'd be nice if the 'correct' way was also documented in the README.md file

**Comment by solidnerd** [comment]
Hey, 
yes there are several ways to make a backup with docker-compose. This is one solution:

**create backup**
```
docker-compose run --rm gitlab app:rake gitlab:backup:create
```

**restore backup**
```
docker-compose run --rm gitlab app:rake gitlab:backup:restore BACKUP=1460905799
```

Before you start with a backup please shutdown your gitlab container to prevent inconsistency of your database.

**Comment by iamchanghyunpark** [comment]
Great! Thanks @solidnerd,
When creating the backup, we first need to stop the containers, and then re-execute the backup command right?

Would you add the instructions to the README.md?
I'm sure there are other users whom would benefit from your answer :)

**Comment by chraibi** [comment]
This is interesting to me too! A little bit late, but hope to get an answer though. 
Is it not a bit odd to have to shutdown a production system, just to make a backup?

According to this [answer](http://stackoverflow.com/questions/33961240/how-to-enable-cron-backup-in-docker-gitlab-ce) we can start a new image and run inside it the backup command. 

Would this work?

**Comment by jostyee** [comment]
@chraibi GitLab supports scheduled backup already.

**Comment by chraibi** [comment]
thanks. Link perhaps? 

My question was not regarding the scheduled part, but just the condition for running the backup.

**Comment by iamchanghyunpark** [comment]
@chraibi [Link ](https://github.com/sameersbn/docker-gitlab#available-configuration-parameters)to the scheduled backup configuration.
Backups are stored in the path stored in `GITLAB_BACKUP_DIR` (default: `/home/git/data/backups`)
Also check out the following variables:

- `GITLAB_BACKUP_SCHEDULE`
- `GITLAB_BACKUP_TIME`
- `GITLAB_BACKUP_EXPIRY`
- `GITLAB_BACKUP_TIME`

etc. `GITLAB_BACKUP_*` are the variables you want to look at.

**Comment by chraibi** [comment]
thanks!
